### ISSUE TITLE
Adding Korean filter

### ISSUE THREAD

**Issue by nagato7** [AdguardTeam/AdguardForiOS#100]
Adblock iOS implements "[Korean Adblock List](https://github.com/gfmaster/adblock-korea-contrib)". However it hasn't been maintained for months, so it doesn't work well with Korean websites.
I found a filter called "[List-KR](https://github.com/SlowMemory/List-KR)". While it's pretty new (created in May) but it has been updated frequently and works better with Korean websites. Since iOS version cannot subscribe additional filter list, could you consider adding/replacing this one for Korean websites?

**Comment by Alex-302** [comment]
@Stillness-2 added. Waiting for @mmigi

**Comment by mmigi** [comment]
List-KR filter is added. Now you can find it by the it's name.
