### ISSUE TITLE
An explanation of how to better understand the new DNS query interface.

### ISSUE THREAD

**Issue by mozdevcontrib** [AdguardTeam/AdguardForiOS#1000]
**Feature Request:**

  AdGuard Pro eased the understanding of exactly which queries were or were not blocked using color codes. While I like the new interface, I believe it would be of use to people using AdGuard 3.0 as well as help to expand its usage by clearly detailing exactly what each query result means to end-users, now and when released to the App Store as the new release model.

### Steps to reproduce

1. When examining each DNS query, the given results are, essentially, obfuscated by not clearly denoting what denotes a blocked request and what denotes a processed request.
2. Write a sort of basic tech-spec explaining in clear words how to examine DNS queries as well as how to know the meaning of possible results / requests.

### Your environment

* Device model and storage size: iPad 6th Gen.; iPhone 6 Plus
* Operating system and version: 12.4

**Comment by ameshkov** [comment]
The blocking is now can be done on the server side only (if you're using an ad blocking DNS server).

I guess we can mark NXDOMAIN/127.0.0.1 items as blocked anyways. Marked as feature request.

**Comment by mozdevcontrib** [comment]
Now that's an interesting fact:

> ...blocking is now can be done on the server side only...

Perhaps this behavior is related / a possible cause of the ad blocking function not behaving consistently.

I do think the additional info as chosen by you, @ameshkov , is a good idea. :)

- intr0

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ameshkov** [comment]
We've changed the look and feel in v4.0, please let me know if you'd change anything therre

**Comment by mozdevcontrib** [comment]
I regret not following my instincts and telling you right away when the release initially came out that the new DNS interface is many levels above the previous releases. The ability to copy values simply by softly tapping on each one is beyond helpful. The increased amount of information given for each connection is amazing. And visual cues given to whitelist / blacklist each connection in (relatively) green / red is as close to perfect as anyone can ask. AdGuard (recreated) just keeps getting better and better. Thank-you to all involved (including the community of beta testers).

**Comment by zzebrum** [comment]
@mozdevcontrib thank you :)
