### ISSUE TITLE
Protection is disabled message persists

### ISSUE THREAD

**Issue by rodaimi** [AdguardTeam/AdguardForiOS#1001]
### Steps to reproduce

1. Enable dns privacy
2. Protection is disabled message on home screen is still visible.
3.
4.

### Expected behavior

Message should change to protection is enabled.

### Actual behavior

Protection is disabled message appears but dns blocking with adguard dns servers still works as expected.

<details><summary>Screenshot:
https://prnt.sc/nriy7r
</summary>

</details>

### Your environment

* Device model and storage size: iPhone XR
* Operating system and version: ios 12.2
* Browser: Safari

**Comment by ameshkov** [comment]
This is actually not a bug.

The message is there because you have not enabled AdGuard content blockers in Safari settings.
