### ISSUE TITLE
Feature for V3 : activate VPN only when not connected to a specific wifi 

### ISSUE THREAD

**Issue by F3000** [AdguardTeam/AdguardForiOS#1002]
E.g. on the home network I have a pi-hole setup so I wouldn’t need this . 
And at work there are other limitations. 
So would be nice to create a field where a user can add exception SSID’s

**Comment by worldsdream** [comment]
We should have a option called: "Add Wi-Fi network". AG will pause when connected to one of these WiFi networks. With a "+" indicator that if we click on it, we can add the SSID. It should also show the current network so you can tap it easily, so you don't have to type the SSID in the section.

Warp on iOS have this function. Go to settings>more settings>connection options.

**Comment by ameshkov** [comment]
Closed as dup
