### ISSUE TITLE
Let the names of AdGuard's Safari content blockers be translated.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1003]
Let the names of AdGuard's Safari content blockers be translated.
Please upload the phrases to onesky.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/q1ILWQy.png)
</details><br/>

**Comment by 08kovalchuk03** [comment]
The name of content blocker is saved in .plist file
.plist files can't be editted
