### ISSUE TITLE
[3.0 Beta][Feature request] Sort user filters by name or date

### ISSUE THREAD

**Issue by SebastianRasch** [AdguardTeam/AdguardForiOS#1005]
Would be nice to have the option to sort user filters automatically by name for better overview but also to be able to go back to sort by date to easily see the most recently added filters.

**Comment by Superkloton** [comment]
I'm really missing this feature guys 😢

**Comment by ameshkov** [comment]
We considered all pros and cons and decided to give up on this one -- draggable rows are too problematic to implement.

Also, you can always use the "Edit mode" to rearrange your user filter OR create a custom filter list somewhere (for instance, on Github) and edit it there.

**Comment by SebastianRasch** [comment]
OK thanks guys for considering it! 4.0 looks very promising anyway, good job!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
