### ISSUE TITLE
[3.0 Beta][Feature Request] Copy & Paste several user filters

### ISSUE THREAD

**Issue by SebastianRasch** [AdguardTeam/AdguardForiOS#1006]
I need an option to copy several or all filters at once. Right now, I can only delete marked filters.
Also, it should be possible to paste a bunch of filters at once and not only one by one. Not sure if this is possible right now because AdGuard crashes when I tap on "Add rule".

**Comment by ameshkov** [comment]
This is possible in "Edit mode" (available in v4.0)
