### ISSUE TITLE
[3.0 Beta][Bug] Link in user filters section leads to wrong page

### ISSUE THREAD

**Issue by Superkloton** [AdguardTeam/AdguardForiOS#1007]
### Steps to reproduce
1. Go to the user filters section
2. Click on the link on top (rule syntax)

### Expected behavior
Webpage with explanation of the rule syntax should open

### Actual behavior
Webpage with the feature overview of AdGuard opens instead

![IMG_1532](https://user-images.githubusercontent.com/22617697/58190463-dc1b8e00-7cbc-11e9-9190-87a33a33883a.jpg)

### Your environment
* iPhone X 64 GB
* iOS 11.3.1
* Safari
* Wi-fi

**Comment by Superkloton** [comment]
This is solved now in b134 but not yet localised (in the app of course, not the website).

**Comment by ameshkov** [comment]
Well, it's just because our knowledge base is not localized yet.

We will take care of it in the future, the whole knowledge base needs to be reworked.

**Comment by Superkloton** [comment]
@ameshkov No I meant the link text in the app. It was localised in version 129 but is now in English in version 134 (I use the app in German).

**Comment by ameshkov** [comment]
Uh, got it. We'll update translations next week
