### ISSUE TITLE
Bug in V3 : Wrong time in DNS query list 

### ISSUE THREAD

**Issue by F3000** [AdguardTeam/AdguardForiOS#1009]
Hi , I have seen that there is a false time stamp for each entry . 
My device is in region Germany with language also in German . 

![CFDF37B9-257F-4860-B435-9A7BB6286B17](https://user-images.githubusercontent.com/8161283/58195806-1be87280-7cc9-11e9-9bd1-c446c9822118.png)

In this example my local time is 19:37 and the app displays 23:37

And for what are the last 3 numbers ?

**Comment by ameshkov** [comment]
What build number are you using?

> And for what are the last 3 numbers ?

This is milliseconds.

**Comment by iDjay** [comment]
Fixed with the new build :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
