### ISSUE TITLE
First time load showing ads

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#101]
Please look here:

https://github.com/AdguardTeam/AdguardFilters/issues/1857#issuecomment-228131978

**Comment by ameshkov** [comment]
More info here:
https://forum.adguard.com/index.php?threads/filters-not-getting-updated-to-latest-version.11337/

It seems that right after the installation AG does not apply downloaded filters properly.

**Comment by worldsdream** [comment]
I think those are 2 different bugs. But I only can confirm that after safari filter gets updated.

**Comment by ameshkov** [comment]
Hm, yep, I got it all wrong. The original issue seems to be an iOS bug though.

**Comment by Stillness-2** [comment]
I moved installation problem in separate issue #102

**Comment by Alex-302** [comment]
Any news?
The same issue in Safari extension
https://github.com/AdguardTeam/AdguardFilters/issues/3663

**Comment by ameshkov** [comment]
Resolved in the latest beta of Safari extension.

Will be resolved in iOS version when #275 is done

**Comment by Alex-302** [comment]
Ok, thanks

**Comment by worldsdream** [comment]
This is fixed. 

Months ago...

Closed

**Comment by ameshkov** [comment]
@vozersky please review the open issues, we have dozens of obsolete issues here
