### ISSUE TITLE
[3.0 Beta] Can't delete the custom filters

### ISSUE THREAD

**Issue by loveqqzj** [AdguardTeam/AdguardForiOS#1012]
Device：iPhone XR  IOS [12.3]
anguage：Chinese
Issue：On custom filter page, when there are multiple filter subscriptions, I can't delete the filters successfully, I delete the filters, but after I exit adguard and re-enter, I find the filters are still exit, and I have try several times, the problem is still exit. 
Please look the attachments in detail. The package is the video of demonstration. Please decompress it and play.

[视频.zip](https://github.com/AdguardTeam/AdguardForiOS/files/3210849/default.zip)

**Comment by ameshkov** [comment]
Confirmed, thank you!

**Comment by loveqqzj** [comment]
I find the filters are still exit, and I have try several times, the problem is still exit.

**The "exit" should be "exist".**

**Comment by loveqqzj** [comment]
> Confirmed, thank you!

I find the filters are still exit, and I have try several times, the problem is still exit.

**The "exit" should be "exist".**
