### ISSUE TITLE
[3.0 Beta] Simplified Chinese and Traditional Chinese mixed on the interface

### ISSUE THREAD

**Issue by loveqqzj** [AdguardTeam/AdguardForiOS#1015]
Device: iPhone XR
OS: IOS 12.3
Language: Chinese
Simplified Chinese and Traditional Chinese mixed on the interface, which makes users feel a bit strange. It is unable to give users a consistent experience.
And if you could translate all the English descriptions of filters into Chinese, that would be great，of course this is just my suggestion, you can ignore it.
![20190523_141851000_iOS](https://user-images.githubusercontent.com/50936548/58261600-33982780-7dab-11e9-9ac3-155fd008e6f4.png)

**Comment by lancelot-moon** [comment]
Someone used Traditional Chinese for the phrase, "Ad Blocking", in Simplified Chinese (zh-CN).
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/T30VTQZ.png)
</details><br/>

It's not a bug.
Simply, there are many outmoded translations there.
Need Simplified Chinese translators to fix them.

**Comment by ameshkov** [comment]
@loveqqzj thank you! 

Just in case, anyone can contribute to AdGuard translations: https://kb.adguard.com/en/general/adguard-translations

**Comment by loveqqzj** [comment]
> @loveqqzj thank you!
> 
> Just in case, anyone can contribute to AdGuard translations: https://kb.adguard.com/en/general/adguard-translations

OK, I just have contributed 60 words translations, hope AdGuard is better than better

**Comment by ameshkov** [comment]
@loveqqzj thank you so mcuh!
