### ISSUE TITLE
[3.0 Beta] DNS Privacy Consistently not Working on Specific Wifi

### ISSUE THREAD

**Issue by shad0whawk** [AdguardTeam/AdguardForiOS#1019]
In general, the latest beta (v135) is fairly stable and consistent, and does a good job of blocking ads using DNS Privacy. It seems to quit working when I connect to Southwest Airlines inflight WiFi.  The Adguard VPN service is connected but doesn’t block the ads.  I’ve tried using DNS-over-HTTPS and DNSCrypt and neither work.  I’ve tried disabling and reenabling the Adguard service but no change.  I can see the VPN icon turn off and back on as I make the changes.  If I subsequently enable Adguard Pro connected to the Adguard DNSCrypt server, it blocks those ads with no issues.  I will send the logs to apple@adguard.com and add this issue number to the email.

### Steps to reproduce

1.  Connect to Southwest Airlines WiFi
2.  Enable DNS Privacy with either DNS-over-HTTPS or DNSCrypt
2.  Open Google Chrome and navigate to TheVerge.com
3.  Wait while page fully loads

### Expected behavior
Ads should be blocked and display ad placeholders

### Actual behavior
Ads load and continue updating instead of placeholders

### Your environment
iOS 12.3.1 on iPad Pro using Chrome on an inflight WiFi connection

**Comment by ameshkov** [comment]
@shad0whawk could you please re-send the logs? I've just checked the inbox but couldn't find anything from you from 3 days ago

**Comment by shad0whawk** [comment]
I just resent them.

Marc Burris
303.809.8149
marc.burris@gmail.com

**Comment by ameshkov** [comment]
According to the log, AdGuard DNS server is unavailable in this network.

What for Adguard Pro, could it be that you're using any local block lists? In this case, it can block requests regardless of what DNS server is configured.

**Comment by shad0whawk** [comment]
I do use the Adguard Pro SDN filter under subscriptions when it is enabled. How could it be unavailable across all three methods including HTTPS? Interesting...

**Comment by ameshkov** [comment]
> I do use the Adguard Pro SDN filter under subscriptions when it is enabled. How could it be unavailable across all three methods including HTTPS? Interesting...

In AG v3.0 there's no local filtering like we had in AG Pro due to their restrictions.

**Comment by shad0whawk** [comment]
Right makes sense. I’m just surprised that even https method was being blocked.

**Comment by ameshkov** [comment]
Well, DOH is on the same IP address, and it seems it was simply unavailable from that network.

**Comment by shad0whawk** [comment]
The last time I tried this all seemed to work well so I’ll close it.
