### ISSUE TITLE
Right after installation, filters update does not work properly

### ISSUE THREAD

**Issue by Stillness-2** [AdguardTeam/AdguardForiOS#102]
https://github.com/AdguardTeam/AdguardForiOS/issues/101#issuecomment-228172946

More info here:
https://forum.adguard.com/index.php?threads/filters-not-getting-updated-to-latest-version.11337/

It seems that right after the installation AG does not apply downloaded filters properly. Keeps the base version until the next filter update is received.

**Comment by worldsdream** [comment]
You closed it, does it mean you fixed it?

**Comment by Stillness-2** [comment]
@worldsdream Yes, it is in beta now, and will be in next release.
