### ISSUE TITLE
Beta 3.0 - Video Tutorial Needs Updating

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#1020]
The video tutorial needs updating. The video indicates that the user needs to enable the AdGuard Pro in Safari settings. Since version 3 contains multiple blockers per category, this needs to be reflected as well in the video.

**Comment by planet0** [comment]
Duplicate of #870?

**Comment by ameshkov** [comment]
Yep, closed as a duplicate
