### ISSUE TITLE
Encrypted DNS + Poor Connectivity causing timeouts

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForiOS#1021]
With the latest build, I’m now having issues using AdGuard DNS via DNS-over-HTTPS.

Apps can’t connect, but if I use the regular connection method, apps work straight away.

Turning DNS Privacy off and on didn’t work, and turning Wifi off and on didn’t work. Only method that worked is switching from DoH to Regular for AdGuard DNS.

### Steps to reproduce

1. Update to build 135
2. Wait an unknown period of time
3. Open Reddit iOS App

### Expected behavior

Reddit loads fine
### Actual behavior

Reddit can’t connect at all

<details><summary>Screenshot:</summary>

![4A6209B8-60B8-4284-91A8-9CDBD1563EE1](https://user-images.githubusercontent.com/46271764/58364390-0d7f9e00-7ef7-11e9-94aa-118e4df2b443.png)
</details>

### Your environment

* Device model and storage size: iPhone 8 Plus, 64GB
* Operating system and version: 12.3
* Browser (e.g. Safari): Reddit App, Safari
* Wi-fi or mobile internet connection: Wifi

**Comment by planet0** [comment]
And then, after some luck, all apps can work again after a period of time, including Reddit. After submitting this issue on here, the Reddit app works again.

It’s temperamental.

**Comment by iDjay** [comment]
Had the same issue with AdGuard DNS over TLS but they fixed it, HTTPS worked fine for me

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by planet0** [comment]
Today I was heavily using my phone via Wi-Fi instead of Mobile Data, and my Wi-Fi connection is much slower and unstable compared to Mobile Data. This might have something to do with that, as now that I'm back on Mobile Data, I've been okay.

Might change the issue to Encrypted DNS + Poor Connectivity causing timeouts.

**Comment by Irken-Skoodge** [comment]
The custom dns settings work most of the time but I have webpages just not load at all sometimes, when I refresh the page it works. It happens on any of the dns servers I choose. I am on iOS 12.4 beta. Don’t know if that’s the issue.

**Comment by Irken-Skoodge** [comment]
The custom dns settings work most of the time but I have webpages just not load at all sometimes, when I refresh the page it works. It happens on any of the dns servers I choose. I am

**Comment by Irken-Skoodge** [comment]
The custom dns settings work most of the time but I have webpages just not load at all sometimes, when I refresh the page it works. It happens on any of the dns servers I choose. I am

**Comment by ameshkov** [comment]
Hi folks,

To troubleshoot this case we need to get your logs.

Here's what we need you to do:
1. Reproduce the issue (and remember the exact time when it happened).
2. Disable "DNS Privacy"
3. Open the app, tap "Send Feedback", select "Contact Support"
4. The mail app will be opened, **change the recipient to `apple@adguard.com` (!)**
5. Mention this issue number in the email text

**Comment by planet0** [comment]
I’ve experienced this issue all day on 4G connection, moving between areas and different cell towers.

Sent via apple@adguard.com, most recently was trying to use Snapchat at 4:21pm, nothing was uploading.

At about 2:30pm, I was unable to load anything from the Facebook app, Messenger app, and Facebook Pages app.

**Comment by ameshkov** [comment]
> The only work around I found is to delete the VPN connection from iOS Settings, and relaunch AdGuard to setup DNS Privacy again. Or to reboot iOS.

What about turning airplane mode on and off again? It makes iOS reset the network settings completely.

**Comment by ameshkov** [comment]
Also, I've received the logs, thank you!

To devs: logs are stored in the private nextcloud

**Comment by iDjay** [comment]
@ameshkov send you my logs a few minutes ago. Realized that when this issue happens, the „VPN“ icon stays visible although it‘s disabled. Turning iPhone into flight mode solves the issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by planet0** [comment]
@ameshkov Yep, airplane mode works as well :-)

**Comment by planet0** [comment]
With this new build I can’t get Full-Tunnel mode to work, only Split-Tunnel. Airplane mode, or switching network types doesn’t resolve it.

Sent logs to apple@adguard.com again.

**Comment by ameshkov** [comment]
> Sent logs to apple@adguard.com again.

Hm, I've not received anything:( Could you please re-send it to `am at adguard.com` as well?

**Comment by planet0** [comment]
No problem, I’ve resent it to that email address as well.

**Comment by planet0** [comment]
Can continue to confirm that since sending the logs, I've been using Regular for AdGuard DNS and experienced no issues.

**Comment by ameshkov** [comment]
Thank you!

So far it seems that the problem is not just the encrypted DNS, but the full tunnel mode which starts misbehaving at some point. At the time when you experience this, I simply see no DNS queries.

**Comment by planet0** [comment]
Ah that makes sense. If there's anything you need from my device to figure out the issue with full-tunnel mode, I'd be happy to help. Otherwise I hope there's a way to resolve this, I found split-tunnel lets through things sometimes.

**Comment by ameshkov** [comment]
We'll try to find a reliable way to reproduce this on our side. It's interesting that regular DNS works okay, though, I don't understand why.

What about DNSCrypt, is it also okay?

**Comment by planet0** [comment]
I'm not sure either, the past 4 days have been trouble-free with Regular DNS, both Wi-Fi and Mobile Data.

Every night I set iOS to Airplane Mode and I manually update filters when I take it off Airplane Mode in the morning.

I've changed the connection type to DNSCrypt as of now, and I'll see how it goes.

**Comment by planet0** [comment]
Had issues with DNSCrypt today, nothing was going through. Turning off DNS Privacy allowed everything to 'reconnect' to the internet.

Will now switch to DNS-over-TLS and see how that goes.

**Comment by planet0** [comment]
Had issues with DNS-over-TLS as well. So there we go, all encrypted methods I have trouble with. Hope that helps @ameshkov!

**Comment by shamuscc** [comment]
I am having the same issue with both encrypted and regular DNS. I have tried full and split tunnel with the same result.

**Comment by planet0** [comment]
Just wanted to give an update, I'm actually having a pleasant experience since using iOS 13. Apple App Store loads now, haven't really had any issues... once or twice when switching between Wi-Fi and Mobile Data connections, but a simple toggle off and on of DNS Privacy resolves that.

**Comment by ameshkov** [comment]
I cannot reproduce this anymore in v4.0 beta. @planet0 could you please check it?

**Comment by planet0** [comment]
I haven't had any issues with the TestFlight build (huuuuge kudos for the new UI by the way, it's fantastic), really happy with it. No longer need to use AdGuard Pro and AdGuard together 👍 

Happy to say it's resolved.
