### ISSUE TITLE
[Request] Is User filter or Custom filter will work as Local DNS

### ISSUE THREAD

**Issue by lilws** [AdguardTeam/AdguardForiOS#1022]
In the old Adguard 2.1, there is a features that allow user to add server to blacklist 
![IMG_4C0BF758A52B-1](https://user-images.githubusercontent.com/12478478/58366618-3015b500-7eff-11e9-8182-50db0f076d88.jpeg)

then combine it with System Default DNS sever.
![IMG_0F2A5D01561E-1](https://user-images.githubusercontent.com/12478478/58366594-c72e3d00-7efe-11e9-9363-5d0c4d264ebc.jpeg)

So is it possible to do that in this version? Or I missed something here with User Filter and Custom Filter here? Because neither both of these filter I added, it is not working. There is no local System DNS to choose.

**Comment by lancelot-moon** [comment]
For passing Apple's review, AG team remove blacklist and whitelist but only remain DNS requests log.

The privacy settings in AG Pro for iOS is impossible in regular AG for iOS because of Apple.

iOS users need to have updates for Safari Content Blocker.

**Comment by planet0** [comment]
From my understanding @lancelot-moon is right.

You can only use external DNS servers, and local DNS functionality is removed due to Apple's policy.

The User Filter and Custom Filter is for Safari Content Blocking only. User Filter is for your custom rules in Safari, and Custom Filter is to subscribe to any other filters for Safari.

**Comment by lilws** [comment]
Thanks for verified that.

**Comment by ameshkov** [comment]
Yep, @lancelot-moon is right (unfortunately).

The only way to manage DNS filtering now is to run your own instance of [AdGuard Home](https://github.com/AdguardTeam/AdGuardHome) or [Pi-Hole](https://pi-hole.net) and use it as a custom DNS server.

**Comment by seanob86** [comment]
DNSCloak app was recently allowed back on the app store (was removed prior by apple), and the version allowed back on the app store provides a blacklist/whitelist option for system wide blocking while connected to either dnscrypt/DoH servers. This App was approved by Apple 4 months ago.
