### ISSUE TITLE
[Question] Red entries

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1023]
Why are some entries marked red? Is this an issue? ![GitHawk Upload by iDjay](https://i.imgur.com/NkreLYv.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sergskd** [comment]
I believe thous are trackers and advertising domains. AdGuard’s DNS should be blocking them. I could be wrong though?

**Comment by ameshkov** [comment]
Blocked (127.0.0.1 or 0.0.0.0) or non-existent domains are marked red. We can't say the difference from the client-side (ads and tracking domains look like non-existent).
