### ISSUE TITLE
[3.0 Beta] Editing User Filter when in Dark Mode can't see text under domain

### ISSUE THREAD

**Issue by Sergskd** [AdguardTeam/AdguardForiOS#1024]
When you try to edit User Rule in Dark Mode you cant see text under edit domain: 
It works in regular mode(white background) you can see the rule you are editing, but in dark mode text is there but it appears invisible. My guess font color needs to be changed, I personally would like it if it was green.

![dark](https://user-images.githubusercontent.com/31105646/58374370-f0ed6100-7f0a-11e9-8a65-17ee04fd15c8.jpg)
![light](https://user-images.githubusercontent.com/31105646/58374371-f0ed6100-7f0a-11e9-9d9a-4f3b9ca12823.jpg)

Also, this is more of a feature request: "Please give us a bigger window to edit rules, it's kind of tight like a government application tight" 😬

* iPhone 7 128GB
* iOS; 12.3.1
* Beta version 3.0.0 (135)
* Wi-fi or mobile internet connection

**Comment by aspasskaya** [comment]
The button "Сохранить" should be in uppercase -> "CОХРАНИТЬ"

![image](https://user-images.githubusercontent.com/43952607/58703959-1539b980-83b3-11e9-8c0c-06d5fbf44edc.png)
