### ISSUE TITLE
[3.0 Beta] DNS Privacy Log Not Updating

### ISSUE THREAD

**Issue by shad0whawk** [AdguardTeam/AdguardForiOS#1025]
The DNS Privacy log is not refreshing with new entries. The last update was 7 hours ago. I’ve tried pulling down within the log window to refresh it manually.  DNS Privacy is on and functioning as expected, but no log updates. I’ve tried turning DNS Privacy on/off and switching the server but no change in the log. I’ll send the logs from my phone if that helps. 

Update:  I just realized that the last entry in the DNS Privacy log is at 4:41 pm. I rebooted my phone at 4:42 pm. I verified this by using a system status app that provides this information. So it seems like the DNS Privacy log failed to start logging again after the reboot.

**Comment by shad0whawk** [comment]
Hmm the issue seems to have resolved itself now many hours later.

**Comment by ameshkov** [comment]
@shad0whawk uh, please reopen this issue and send the logs next time this happens.

Now it's too late for that, the log file size is limited :(

**Comment by shad0whawk** [comment]
I sent the logs last Night when I open the issue. I included the issue number in the log email.

Marc Burris
303.809.8149
marc.burris@gmail.com

________________________________

**Comment by ameshkov** [comment]
I guess you've sent it to the default support email? I didn't see anything in the `apple@adguard.com` inbox.

**Comment by shad0whawk** [comment]
Hmm I sent it to both actually. I’ll check my sent items.

Marc Burris
303.809.8149
marc.burris@gmail.com

________________________________

**Comment by shad0whawk** [comment]
I just resent the originally sent email to both the Apple and the Support Adguard addresses. 

Marc Burris
303.809.8149
marc.burris@gmail.com

**Comment by ameshkov** [comment]
Great, I've received this one, thank you!

**Comment by ameshkov** [comment]
Am I right that you were using AG alongside NordVPN all this time?

**Comment by shad0whawk** [comment]
Typically yes unless the router doesn’t allow it which I find occasionally.

**Comment by shad0whawk** [comment]
Well the latest build (140) did it again so I sent you some more logs.  I disabled NordVPN and it’s still not updating just in case that was an issue.

**Comment by shad0whawk** [comment]
Update:  

I was on a WiFi network when this occurred so I disabled it right after I sent the previous message, refreshed the log (again), and now it‘s updating again. In switching off the WiFi I noticed the DNS service restarted. I’m back on the WiFi and the logs are not updating again, but the DNS is filtering out ads using Chrome. So I’m not sure if it’s an AdGuard issue or something with the WiFi.

**Comment by Eugene-Savenko** [comment]
If you need more logs - 1264893

**Comment by zzebrum** [comment]
@shad0whawk is the issue still persist on the latest version?

**Comment by shad0whawk** [comment]
I haven’t noticed it lately so I’ll close it.
