### ISSUE TITLE
[Feature Request] redundant DoH / DoT servers.

### ISSUE THREAD

**Issue by mozdevcontrib** [AdguardTeam/AdguardForiOS#1026]
- [x] Feature request: At some time in the future development, the ability for users to choose more than a single DoH or DoT provider, I believe, would be helpful for the sake of redundancy, especially when adding custom addresses.

### Your environment

* Device model and storage size: (iPad 6th generation, iPhone 6 Plus)
* Operating system and version: (12.4)
* Browser (Any)
* Wi-fi or mobile internet connection (both)

**Comment by ameshkov** [comment]
Duplicates #903
