### ISSUE TITLE
Not blocking the popup

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#103]
I am running iOS with the filters enabled, English, dutch, annoyance, safari, mobileads and easyprivacy

I still get the popup advertisement. See more here:
https://github.com/AdguardTeam/AdguardFilters/issues/2406#issuecomment-228335252

Can anyone confirm with my list please if they get that advertisement. If not, what can I do? Where is the problem?

**Comment by worldsdream** [comment]
This is the link:
https://openload.co/f/lZaiHVdf0jc

When i click on play, i get a popup

**Comment by ameshkov** [comment]
@worldsdream could you please check this rule?
```
||onclickads.net^$popup
```

**Comment by worldsdream** [comment]
I added this rule, still get a popup. How can we troubleshoot this on device? Fiddler?

**Comment by ameshkov** [comment]
Fiddler would be great. Could you record a session and attach it here?

**Comment by worldsdream** [comment]
I pm'ed you on the forum

**Comment by worldsdream** [comment]
I added:

||large-format.net^
||november-lax.com^
||adrunnr.com^

Now I dont get to see large format or any other popup ads, now I get about:blank popup. How do we get rid of that?

**Comment by worldsdream** [comment]
I dont get a popup ad anymore. Resolved.
