### ISSUE TITLE
Prepare images for the App Store 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1030]
1. Images in all necessary resolutions
2. Translate text on all images

**Comment by lancelot-moon** [comment]
1. Translated texts on all images?
They'were English before.
I'm glad the English words in all images will be shown as translated words.

2. It seems that you recently updated overview on app store.
But I guess it's outmoded without the information about Premium features.
https://itunes.apple.com/us/app/adguard-adblock-privacy/id1047223162?mt=8

I just completed overview's translations.
May you update overview's translations again when releasing v3 on app store?
Thanks.
