### ISSUE TITLE
Show confirmation dialog when a rule was added from Safari app extension

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1034]
Mockup:
https://share.goabstract.com/78256cd9-6e5f-4a52-821e-8614e73a9e6c?mode=design&sha=be6f34e2d4b097512a255f4c94d3048cc2a6f0f9

Please note, that it should be done when the rule is added from Safari App extension only.

**Comment by aspasskaya** [comment]
## 1. The "Ok" button should be green.
## 2. Increase the size of the Adguard 3.0 icon to the size of the Adguard pro in action.
![image](https://user-images.githubusercontent.com/43952607/58638900-823f4780-82fe-11e9-880b-09800bddc9b6.png)
![image](https://user-images.githubusercontent.com/43952607/58639153-101b3280-82ff-11e9-9a19-f6f146cc1803.png)
