### ISSUE TITLE
Manually Setting DoT/DoH Server IP

### ISSUE THREAD

**Issue by Yuan573** [AdguardTeam/AdguardForiOS#1036]
Manually setting the DoT/DoH server IP allows us connection the encrypted DNS without via system default DNS.
Maybe like this...
![Use IP to AdGuard DoH](https://i.imgur.com/XFOh21I.jpg)
![Use IP to TWNIC DoH](https://i.imgur.com/WV9CEM4.jpg)

Or we can also manually set up bootstrap DNS like AdGuard Home.
![AdGuard Home](https://i.imgur.com/OYXa6WQ.jpg)

**Comment by ameshkov** [comment]
Makes sense, thank you for the feature request

**Comment by seanob86** [comment]
+1 for this feature as per Adguard Home.
I would like to add my dns stamp as a custom server in AG 3 to connect to my AGH server via DoH!

**Comment by ameshkov** [comment]
Well you can add a dns stamp, but AG at this moment will ignore the IP field.

**Comment by seanob86** [comment]
IP field? I can only see 2 fields in the ‘Edit Custom DNS Settings’ page!

1. Server Name
2. Enter DNS Upstreams

So I suppose the DNS stamp is entered in #2 above?

**Comment by ameshkov** [comment]
> IP field?

DNS Stamps support specifying resolver's IP address.

> So I suppose the DNS stamp is entered in #2 above?

Yep

**Comment by Versty** [comment]
@Yuan573 Bootstrap upstreams are now available in the low-level settings.
