### ISSUE TITLE
Possible to sideload Adguard pro?

### ISSUE THREAD

**Issue by rodaimi** [AdguardTeam/AdguardForiOS#1038]
I know this is a little bit off topic since it is not directly related to the new Adguard app.

First of all, I appreciate the time and effort the adguard team has put in to make a suite of adblocking software available to almost anybody for free or for a very low price.

I have been using the original Adguard Pro For a long time and would love to see more development on it. I understand apple's policy will not allow you to update it an appreciate that you are still keeping it on the app store. I would love to see a sideloaded version of Adguard Pro which won't be subject to apple's app store limitations. There are several sideload app stores available where you can publish the sideloaded version. Additionally, you can have an option for power users and developers to sign the .ipa files themselves to prevent apple from revoking your certificate.

I understand this may take time however, I would be willing to pay a subscription or purchase each ipa version if you decide to go this route.

Once again, I appreciate the hard work you put in to develop a suite of powerful adblocking software and I will contributing to the best of my abilities to further the development of Adguard.

**Comment by ameshkov** [comment]
> There are several sideload app stores available where you can publish the sideloaded version

Could you please give any examples?

**Comment by ameshkov** [comment]
Tbh, I hope that antitrust cases against Apple might help, and they'll allow sideloading the same way it's allowed on Android. This will take years, though:(

**Comment by rodaimi** [comment]
There is [Tweakbox] (https://www.tweakboxapp.com/)

**Comment by rodaimi** [comment]
Technically sideloading is possible on ios but it is mainly designed for developers to test apps. There is a whole subreddit dedicated to sideloading. https://www.reddit.com/r/Sideloaded/

**Comment by ameshkov** [comment]
Well, developer account costs money, and jailbreak is rare nowadays:(

**Comment by iDjay** [comment]
@ameshkov you don‘t need a jailbreak but I still wouldn’t recommend it because Apple may block your dev account and remove all your apps 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lancelot-moon** [comment]
This was suggested before...
https://github.com/AdguardTeam/AdguardForiOS/issues/842

But AG team don't consider MDM now.
