### ISSUE TITLE
Wi-Fi Exceptions

### ISSUE THREAD

**Issue by evilvibes** [AdguardTeam/AdguardForiOS#1043]
Under DNS Privacy could we get a Wi-Fi Exception. The need for this is when I'm outside of my network I need DNS Privacy but when I'm within my network I do not need it as I use Adguard Home. A good example of this is within the DNSCloak app.

**Comment by zzebrum** [comment]
actually, closed as a dup of #1045

**Comment by evilvibes** [comment]
#1045 is a dub of mine but it’s all good as long as it gets done.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
