### ISSUE TITLE
[3.0 Beta] False error when installing VPN

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForiOS#1044]
Noticed sometimes 50% of the time, AdGuard reports that the VPN wasn’t installed, even though iOS actually does and everything works fine.

Was happening to AdGuard Pro as well.
Screenshot of error below.

![GitHawk Upload by planet0](https://i.imgur.com/ZUjd76G.jpg)

**Comment by zzebrum** [comment]
@planet0 hi! is the problem still reproducible?

**Comment by planet0** [comment]
Hi @zzebrum, I actually haven't been able to reproduce it since. Not sure if something was done in AdGuard, or it was the recent iOS update.

**Comment by zzebrum** [comment]
maybe both :)
