### ISSUE TITLE
[Feature Request] Trusted Networks and Disable for Cellular

### ISSUE THREAD

**Issue by grgnday** [AdguardTeam/AdguardForiOS#1045]
Maybe an option to disable the VPN automatically when connected to the cellular network, plus a list were we can add trusted wifi networks can be added.

Just like Cloudflare’s 1.1.1.1 App:

![CC7A5EF5-5662-4737-8BF0-4D45060BE1F6](https://user-images.githubusercontent.com/44814506/58758005-c52b3600-851d-11e9-85b9-e9ed8802ea75.png)

**Comment by pro-sumer** [comment]
I would like this as well, both a configuration option for cellular and one for trusted networks on WiFi. In my case my router at home already does DNS over TLS and it offers additional security/privacy, so I prefer that above AdGuard. On the road or at work AdGuard DNS Privacy would be of value, but manually turning it on/off all the time is super annoying.

**Comment by choco** [comment]
Another vote for this feature. It would be cool to have the same options as the Cloudflare 1.1.1.1 app.

**Comment by ameshkov** [comment]
@AlikhanAliev please take a look. This looks a lot like #1276

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/837d7082-5bdc-4696-8edb-15e816b5e63d

**Comment by IvanIin** [comment]
this feature was implemented in task #1276
