### ISSUE TITLE
[Feature Request] Easy Mode (one-click Mode)

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1046]
Would love to see an one click mode (easy mode) for users like my father (😅) who are not really into the technical stuff behind AdGuard. So basically a one click button to activate the most important filters + eventually DNS Privacy

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zzebrum** [comment]
@iDjay all base filters are enabled by default, you just need to enable content-blocker in Safari settings. Enabling DNS by default won't be allowed by Apple probably. And making AdGuard DNS default server is a very-very dangerous move 😀 
By the way, we are ready for suggestions on how we can improve video tutorial.

**Comment by zzebrum** [comment]
One thing we can do though - add a button which redirects to Safari settings

**Comment by ameshkov** [comment]
well, we're trying to make it as easy as possible by default. hopefully, it's simple enough in v4.0
