### ISSUE TITLE
Change text after clicking on update button

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardForiOS#1047]
After clicking on update button there is a text "Scanning...", I think it should be "Updating..." or something like that.

### Steps to reproduce

1. Click on update button

### Expected behavior

There should be "Updating..." text or something similar.
### Actual behavior

There is "Scanning..." text.

Phrase on oneskyapp -http://adguard.oneskyapp.com/collaboration/translate/project/project/144733/language/16#/?keyword=skanowanie

<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/29142494/58824725-0bc38200-863d-11e9-9c51-36d484f994e3.png)

</details>

<details><summary>Screenshot 2:</summary>

![UpdatingAG](https://user-images.githubusercontent.com/29142494/58824510-80e28780-863c-11e9-9a8f-3ef43097964a.jpeg)

</details>

**Comment by lancelot-moon** [comment]
#47759456 phrase in the project of iOS/iPad app on onesky.
Yes, "Scanning..." is strange here.

**Comment by planet0** [comment]
Could I also add to perhaps have the update icon to rotate alongside the "Updating..." text? It feels odd having the icon completely still during an update.
