### ISSUE TITLE
iOS iMessage error when using GIF app

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1052]
Steps to reproduce

Use #images application (iOS Apple one) from iOS iMessage with Adguard Family activated.  

Expected behavior

Able to send a GIF image

Actual behavior

A mysterious certificate error. 

However no concern when using Adguard Default. 

Your environment

User ID: 2219646
Beta Tester
![D72E132C-ED03-4D8F-80C4-01226161699E](https://user-images.githubusercontent.com/49731083/59149536-426f1300-8a16-11e9-86d9-fb9453659725.png)

Adguard 3.0.0 (140)
iPhone XS Max
iOS 12.3.1
Wi-fi and mobile internet connection

**Comment by ameshkov** [comment]
@Alex-302 this must be a false positive by Family DNS, we should just figure what domain is the problem

**Comment by Quorum75** [comment]
FYI the error message appears also with "media.tenor.com" 
A domain that can't be added in the Whitelist.

**Comment by ameshkov** [comment]
@Quorum75 it seems we can't use `#images`.

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Reproduce the issue (and remember the exact time when it happened).
2. Disable "DNS Privacy"
3. Open the app, tap "Send Feedback", select "Contact Support"
3. The mail app will be opened, **change the recipient to `apple@adguard.com` (!)**
4. Mention this issue number in the email text

**Comment by Quorum75** [comment]
I guess u ou guys did something because since the last update 3.0.1 I cannot reproduced the problem... So somehow it is 'magically' solved.
