### ISSUE TITLE
Request push notifications permissions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1053]
Here's how we should use notifications:

1. [ ] When the license key becomes inactive, we should show a notification;

Here's a question for @AlikhanAliev: should we explain why we need notifications permissions before requesting them?

**Comment by AlikhanAliev** [comment]
I think no. Cause we already have too many things explaining :)

**Comment by planet0** [comment]
@ameshkov, I upgraded via TestFlight this morning and the app immediately asked me for notification permissions.

Once I tapped allow, the app completely crashed.

I could relaunch it without issues afterwards, however.
