### ISSUE TITLE
Custom DNS not work, always use upstream.

### ISSUE THREAD

**Issue by Mowd** [AdguardTeam/AdguardForiOS#1054]
### Steps to reproduce

1. Install AdGuard Home on my server.
2. Install AdGuard 3.0 for iOS.
3. Choose DNS Privacy and use my own DNS server on step 1. Server name is my server IP, upstream is 1.1.1.1
4. Surf on the internet for a while, then checkout AdGuard Home Dashboard, not DNS query record and no client information.
5. Only if I set both server name and upstream to my own server, AdGuard Home Dashboard shows my client IP and DNS query information.

### Expected behavior
AdGuard for iOS use my custom DNS server, not upstream DNS server.

### Actual behavior
AdGuard seems always use upstream server.

### Your environment
* Device model and storage size: iPhone XS Max
* Operating system and version: iOS 12.1.2
* Browser: Safari, FB in-app browser
* Both wifi and cellular network.

**Comment by ameshkov** [comment]
I don't fully understand what you mean.

Here's how it's configured in my case: https://uploads.adguard.com/up04_9pq61_Monosnap.png
Everything works as expected, DNS queries are sent to my AGH instance.

**Comment by Mowd** [comment]
I see. I mis-understand of the naming, I thought Server Name is the DNS IP and DNS upstream means secondary DNS server to prevent first DNS server fail.

I'm a Traditional Chinese user, I think this translation in Chinese for better user understanding will be:
Enter DNS upstream -> 輸入 DNS 上游 (X), 輸入 DNS 位置 (O)
It's not word by word translation, but make user easy understand.

**Comment by ameshkov** [comment]
Well, yeah, I guess this phrase may sound confusing in English as well.

I'll keep this issue open, we should find better wording indeed.

**Comment by lancelot-moon** [comment]
AdGuard team use "DNS upstreams" in not only AG for iOS but also AG for Android.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/yHFlDMp.png)
</details><br/>

> Enter DNS upstream -> 輸入 DNS 上游 (X), 輸入 DNS 位置 (O)

You ask to translate "DNS upstreams (上游)" to "DNS locations (位置)", which is unsuitable.
We also use the Chinese terminology, "DNS 上游 (upstreams)" or "upstream (上游的) DNS", in the aspect of DNS.
@ameshkov 
Please see the search results of "DNS 上游" (DNS upstreams) on google.
The Chinese terminology, "DNS 上游" (DNS upstreams), is accurate and used.
https://tinyurl.com/yyp6dqx2

You should first search what "DNS upstreams (上游)" or "upstream (上游的) DNS" is on google and learn.
Or learn in the knowledge base.
In the field of DNS upstreams, it's not only to input DNS servers IP.
There are also DNS stamps.
"DNS locations (位置)" isn't a good idea.

Translate according to the original English phrases.
Actually, you think that the English phrase lets you confused, which isn't related to Traditional Chinese translation.

Such like the case:
https://github.com/AdguardTeam/AdguardForiOS/issues/1047

You maybe think "Scanning..." isn't suitable there, like AdamWr and me.
But you can't say it's my wrong not to translate "Scanning... (正在掃描...)" to "Updating... (正在更新...)", like that you said it's my wrong not to translate "DNS upstreams (上游)" to "DNS locations (位置)".
They're totally different words.
It's English phrase's business, not a translator's problem.
BTW, "DNS upstreams (上游)" is good enough.

**Comment by ameshkov** [comment]
Moved to https://github.com/AdguardTeam/AdguardForiOS/issues/1098
