### ISSUE TITLE
Cancel button [UI]

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardForiOS#1056]
### Steps to reproduce

1. Open User Filter
2. Click "Select" title

### Actual behavior
"Cancel" text is not aligning with others.

![çç](https://user-images.githubusercontent.com/34379403/59218708-8e15ee00-8bc9-11e9-8e80-5fcd2baf73f7.png)

<details><summary>GIF:</summary>

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34379403/59219497-5019c980-8bcb-11e9-8df5-97dd869a893c.gif)

</details>

### Your environment

* Device model and storage size: iPhone 5s 16GB
* Operating system and version: iOS 12.3.1
* Browser : Safari 
* Wi-fi
* AdGuard Premium

**Comment by zzebrum** [comment]
the same thing in the Whitelist

**Comment by planet0** [comment]
Yep, experiencing this as well in English.
