### ISSUE TITLE
Whitelist issue

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardForiOS#1059]
AdGuard does not filter the site even if the domain name is deleted from the Whitelist.

### Steps to reproduce

1. Add a domain to the Whitelist
2. And delete this domain.
3. Open this domain in Safari
4. Filtering does not work.There are still ads.

### Expected behavior
Content filtering should continue.

### Actual behavior
Domain name removed from the Whitelist, but filtering is still disabled for the deleted site.

### Your environment

* Device model and storage size: iPhone 5s
* Operating system and version: iOS 12.3.1
* Browser : Safari
* Wi-fi
* AdGuard Premium

**Comment by ameshkov** [comment]
It may take some time to content blockers to reload. How long did you wait?

**Comment by PentagramTr** [comment]
@ameshkov 
About 10-15 minutes

**Comment by TheHasagi** [comment]
@PentagramTr 

You should try it with private tab, seems like it's a cache issue.

**Comment by PentagramTr** [comment]
Whitelist doesn't work completely now.
I added 2 domain last night and when I tried today I saw that they were still not working.

**Comment by Yevhen1996** [comment]
Seems like it's not working with iOS 13 beta according to the case 2245766

**Comment by ameshkov** [comment]
The same reason as in https://github.com/AdguardTeam/AdguardForiOS/issues/1062
