### ISSUE TITLE
Safari view controller not respecting the same rules as safari

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#106]
I have reeder app, it's an rss reader. I open links in that app (safari view controller)
The websites do not look the same, as you open them in safari.
For example, white space between text (where normally an ad is placed) in safari view controller and in safari all is good, without the white space between. 

Is this bug already known?

See image:
http://i.imgur.com/r7wKDkX.png

**Comment by ameshkov** [comment]
Yep, I've heard about the same issue before.

I have one idea: maybe SVC ignores filtering rules with domain limitations? Try adding this rule to the user filter and see if it helps:  `##.site-header__compare`

**Comment by worldsdream** [comment]
Error cannot add to user filter

**Comment by ameshkov** [comment]
Argh, what's wrong with the user filter @Stillness-2

**Comment by Stillness-2** [comment]
I added this rule on my test device. @worldsdream What error occurred?

**Comment by worldsdream** [comment]
I just tried again, same error. Stable and also beta release. 

Popup comes up and shows:

ERROR
Cannot add the filter rule. Rule text is invalid.

**Comment by ameshkov** [comment]
Check that there're no spaces and line breaks in the copy-pasted rule text

**Comment by worldsdream** [comment]
I did. I also copied it first to notes app, to make sure. Still the same error.

##.site-header__compare is what i copied

**Comment by Stillness-2** [comment]
Well... We need logs from Adguard. Can you 'Send Bug Report' from Adguard main menu, please?

**Comment by worldsdream** [comment]
Sent it right now, i did put the link of github in the email message. So you know.

**Comment by ameshkov** [comment]
In your case the culprit is the "simplified filters" option which prohibits cosmetic rules with no domains specified.

**Comment by worldsdream** [comment]
You are correct, i disabled it. I could add that line. But still the ad is shown in safari view controller

**Comment by ameshkov** [comment]
@Stillness-2 could you please check if it's possible to debug SVC through desktop Safari (like we do for the mobile safari)

**Comment by Stillness-2** [comment]
@ameshkov I don't found info about such possibility.

**Comment by Stillness-2** [comment]
@worldsdream If you press 'reload' in SVC, what is happen? Is the page shown correct?

**Comment by worldsdream** [comment]
Exactly, if you click refresh, it does look good.

**Comment by ameshkov** [comment]
Looks like #53

**Comment by worldsdream** [comment]
Will this be fixed for next update?

**Comment by Stillness-2** [comment]
@worldsdream It seems that it is iOS bug. We don't know how to solve this problem on our level.

**Comment by evgeniy-ADG** [comment]
logs: 1212314

**Comment by worldsdream** [comment]
@ameshkoc Any update on this one? Or still ios bug?

**Comment by worldsdream** [comment]
I am closing this issue as this is fixed. I'm on latest beta and ios 9.3.3.
I will open a new ticket if I will ever face this issue again.
