### ISSUE TITLE
Can’t add any domain to Whitelist (“Filters cannot be loaded into Safari”)

### ISSUE THREAD

**Issue by Arnoud-B** [AdguardTeam/AdguardForiOS#1062]
### Steps to reproduce

1. Open AdGuard 3.0 and go to Settings > Whitelist.
2. Tap “Add a domain” and fill in “example.com”.
3. Tap “Add”.

### Expected behavior

Domain “example.com” is added to the Whitelist.

### Actual behavior

Domain “example.com” only temporarily shows in the list, then a dialog pops up saying “Filters cannot be loaded into Safari. Therefore, your recent changes were not applied.”

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Device model and storage size: iPad Pro 12.9 2nd gen
* Operating system and version: 12.3.1 with AdGuard 3.0.0(141)
* Browser: Safari
* Wi-fi connection

**Comment by ameshkov** [comment]
Hi, what filter lists do you have enabled in AdGuard?

**Comment by Arnoud-B** [comment]
- AdGuard: Base, Mobile Ads, Tracking Protection, Social Media, Safari, Simplified domain names, Dutch, French
- Security: Malware Domains, Spam404, NoCoin

**Comment by ameshkov** [comment]
Got it, thank you!

Just in case, could you please try disabling some of the filters (or filter groups) to see which one causes this?

**Comment by Arnoud-B** [comment]
Turning them off one by one did not help. Then I turned them all off and re-enabled the groups one by one. It stopped working after enabling the Other group. I disabled "Simplified domain names" and it worked again. Continued turning the rest back on and no more issue.

**Comment by ameshkov** [comment]
Huh, got it, thank you!

**Comment by Quorum75** [comment]
Same here with latest build 3.0.1 and whatever the configuration.

**Comment by Quorum75** [comment]
True. 
The "Simplified Domain Names" filter is the one causing the bug. You must disable it to add whitelist domains and then re-enable it.
