### ISSUE TITLE
Use Done instead of Cancel

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardForiOS#1063]
### Steps to reproduce

1. Go to User Filter
2. Select a rule
3. Select a rule and delete it
4. Click Cancel at the bottom right to finish the process.

### Expected behavior
"Done" can be used instead of "Cancel"

### Actual behavior
"Cancel" title 

<details><summary>Screenshot:</summary>

![dl3 pushbulletusercontent com](https://user-images.githubusercontent.com/34379403/59475907-bc5c2d80-8e56-11e9-8daf-24e29394f1d2.png)

</details>

### Your environment
iPhone 5s
iOS 12.3.1
Wifi

**Comment by PentagramTr** [comment]
Also,Why is "Domain" used here?
"Rule" can be written here instead of "Domain"


<details><summary>Screenshot:</summary>

![IMG_5699](https://user-images.githubusercontent.com/34379403/59475936-e6adeb00-8e56-11e9-8f30-27eca6e646f1.jpg)


</details>

**Comment by ameshkov** [comment]
@08kovalchuk03 

1. We should use "Rule" in the user filter (in whitelist this is still a domain name).
2. Also, this should be a new string in oneskyapp
