### ISSUE TITLE
Filter categories not the same between iPhone and iPad versions

### ISSUE THREAD

**Issue by solusla** [AdguardTeam/AdguardForiOS#1067]
### Steps to reproduce
1. Open Settings > Filters on iPhone version.
2. Open Settings > Filters on iPad version.
3. Compare them.
4.

### Expected behavior
The filter categories—such as `Ad Blocking`, `Privacy`, `Social Widgets`, etc.—on the iPhone version should match those the iPad.

### Actual behavior
Filter categories on iPhone:
- `Ad Blocking`.
- `Privacy`.
- `Social Widgets`.
- `Annoyances`.
- `Security`.
- `Other`/
- `Language-specific`.
- `Custom`.

![IMG_0237](https://user-images.githubusercontent.com/35608295/59554705-d895c280-8f5b-11e9-8d39-0b070d9e58fb.png)

Filter categories on iPad:
- `AdGuard Filters`.
- `Easy List`.
- `Other`.
- `Annoyances`.
- `Security`.
- `Other`.
- `Language-specific`.
- `Custom`.

![IMG_0010](https://user-images.githubusercontent.com/35608295/59554706-e21f2a80-8f5b-11e9-9c7c-b9212f3d8554.png)

The options on the iPad version remind me more of the one available in the previous version before you split the filter categories into different content blockers.

The content blocker extensions listed under `Settings > Safari > Content Blockers` are the same on the iPhone and iPad, so I suspect this is just a UI issue.

</details>

### Your environment
* iPhone XS Max 256GB; iOS 12.3.1.
* iPad Pro 12.9" 256GB WiFi; iOS 12.3.1.

**Comment by zzebrum** [comment]
@solusla the only thing you can try is to reinstall the app on your iPad. Frankly, I've no idea how did this happen 😳

**Comment by solusla** [comment]
Thanks! After uninstalling, restarting the iPad, and reinstalling, the filter settings page appears to be fine.
