### ISSUE TITLE
Add an option to edit custom filter list name

### ISSUE THREAD

**Issue by minsk21** [AdguardTeam/AdguardForiOS#1068]
Options:

- custom name
- edit

Version of display on android more informative
<details >
Android

![IMG_0278](https://user-images.githubusercontent.com/26014600/59562756-4ebc2700-9039-11e9-937a-d3a2154c6454.jpeg)

iOS

![IMG_0277](https://user-images.githubusercontent.com/26014600/59562805-c5592480-9039-11e9-9d38-2024a281bfb6.jpeg)

</details>

**Comment by SebastianRasch** [comment]
You can add information to your filter list that also works with AdGuard. Add this on top of your filters:

!Title: YourTitleHere
!

Don't forget the second exclamation mark.
