### ISSUE TITLE
Adguard not showing in SVC, Version 1.0.8(50) beta

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#107]
I see in the changes: "in third party applications that use safari view controller to display web pages, imrpoved the work of Adguard assistant, you can now block elements on a webpage".

How? I dont see Adguard in there? 

**EDIT (by @ameshkov):** feature is supported since iOS 9.2 only

**Comment by ameshkov** [comment]
@Stillness-2 ?

**Comment by Stillness-2** [comment]
@worldsdream Did you enable Adguard Assistant, as shown on 'Manage Adguard from Safari"' video?


![main_screen](https://cloud.githubusercontent.com/assets/12689/16449091/54adf504-3e06-11e6-8093-8ca341fdc4cf.png)

**Comment by worldsdream** [comment]
Yes, I have it enabled in safari. I do see adguard when I browse in safari. But in changelog is showing that the adguard icon is also available in SVC mode. I dont see adguard there?

**Comment by Stillness-2** [comment]
@worldsdream give me a screens like these, please
https://www.dropbox.com/s/8h9jqdfnfzuyf75/IMG_0658.png?dl=0
https://www.dropbox.com/s/976x3jr0giyqa2f/IMG_0657.png?dl=0

**Comment by worldsdream** [comment]
https://www.dropbox.com/s/zv64nlg450rsvyo/IMG_1387.PNG?dl=0
https://www.dropbox.com/s/vfgtpehau9x4wrn/IMG_1388.PNG?dl=0

I clicked on MORE, but NO Adguard in there to enable!

**Comment by Stillness-2** [comment]
Hmm :(
@worldsdream what version of the iOS on your device?

**Comment by worldsdream** [comment]
iOS 9.0.2
Adguard is supported from iOS 9.0 or later

**Comment by Stillness-2** [comment]
@worldsdream check this link for example: http://www.idownloadblog.com/2015/10/28/whats-new-in-ios-9-2-beta-1-safari-view-controller-updates/

**Comment by worldsdream** [comment]
I see, but now you have to make the app iOS 9.2+ in the appstore correct? But that is not smart in my opinion, as a lot of user are still on iOS 9.0x. I am one of them.

**Comment by ameshkov** [comment]
> but now you have to make the app iOS 9.2+ in the appstore correct

No, why? It's just this feature is supported by SVC since iOS 9.2, no need to change anything in the app itself.
