### ISSUE TITLE
Can't browse Sonos music services

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1071]
**Steps to reproduce**

-> Open Sonos. 
-> Click on 'browse' icon
-> Click on a Google Play Music service. 
-> Result is a blank page with the error message 

Check the video posted which illustrates the steps. 

iOS Sonos 10.2.2 with Mixcloud, Google Play or any music services. 
Adguard 3.0.1 DNS Default or Family with DoH activated. 

**Expected behavior**

Operating normally -> Being able to browse within music service. 

**Actual behavior**

"Unable to browse music there a problem connecting to..."
See snapshot: https://ibb.co/4RgqbXt

However it works with DNS Regular 

**Your environment**

User ID: 2219646
Beta Tester iOS AG 3.0.1
iPhone XS Max or iPad Pro 11
iOS 12.3.1
Wi-Fi ac

**Comment by Alex-302** [comment]
Is it possible to reproduce without BT speakers? Cannot connect my headphones.
And please fill `Steps to reproduce`.

**Comment by Quorum75** [comment]
Sonos does not work on Bluetooth, only on Wi-Fi. 

Steps to reproduce is in the video I posted.

**Comment by Quorum75** [comment]
Any feedback? I cannot use Sonos with Adguard activated. This is very annoying.

**Comment by Quorum75** [comment]
I don't know if that can help. 

mclients.googleapis.com.	22	IN	CNAME	googleapis.l.google.com.
googleapis.l.google.com.	22	IN	A	172.217.11.10
googleapis.l.google.com.	22	IN	A	172.217.11.42
googleapis.l.google.com.	22	IN	A	172.217.12.170
googleapis.l.google.com.	22	IN	A	172.217.12.202
googleapis.l.google.com.	22	IN	A	172.217.9.234
googleapis.l.google.com.	22	IN	A	172.217.10.10
googleapis.l.google.com.	22	IN	A	172.217.10.42
googleapis.l.google.com.	22	IN	A	172.217.10.138
googleapis.l.google.com.	22	IN	A	172.217.3.106
googleapis.l.google.com.	22	IN	A	172.217.12.138
googleapis.l.google.com.	22	IN	A	172.217.6.202
googleapis.l.google.com.	22	IN	A	172.217.6.234
googleapis.l.google.com.	22	IN	A	172.217.7.10
googleapis.l.google.com.	22	IN	A	172.217.10.234

**Comment by Alex-302** [comment]
Please try to whitelist this domain. But I am not sure if this is a reason of the issue.

**Comment by Quorum75** [comment]
It does not work Alex. Like mentioned before there is an issue with the DNS I cannot explain. Same DNS works with DNScloak but not with AG app 🤔

**Comment by Quorum75** [comment]
@alex-302 

Any news on this issue, it is kind of outdated...

Also, you know the Whitelist does not work neither and it has not been fixed in the latest update....

So kind of stuck with and app I cannot use at the present time.

**Comment by ameshkov** [comment]
There's no whitelisting in the current version of AdGuard for iOS. If Apple allows it, we'll restore the system-wide blocking functionality in v3.2: #1107 

@Quorum75 is there any issue when you use Google DNS?

**Comment by Quorum75** [comment]
**> There's no whitelisting in the current version of AdGuard for iOS.**
I don't get it. What is the "Whitelist" domain in iOS AG Beta 3.0.1 ??

Also, you must uncheck "Simplified Domain Names" to add domains in the Whitelist section, and then check it again. Otherwise you always get the same error message "Filters cannot be uploaded into Safari..."

**> is there any issue when you use Google DNS?**
If I disable AG DNS I n to facing any issue.
However like I said in my previous post, if I active AG DNS in iOS DNScloak application I am not facing any problem. Then, AGDNS app does not work, however within a third party app everything is fine. There is something here I don't get....

I al sorry to say but there are some unconsistencies within the actual beta, aren't they?

**Comment by ameshkov** [comment]
> What is the "Whitelist" domain in iOS AG Beta 3.0.1 ??

This whitelist is for Safari content blocking only.

**Comment by ameshkov** [comment]
> If I disable AG DNS I am not to facing any issue.

Do you mean completely disable DNS privacy module, or do you mean that you switch to some other DNS service?

> if I active AG DNS in iOS DNScloak application I am not facing any problem

Yeah, this is weird indeed.

**Comment by Quorum75** [comment]
> Do you mean completely disable DNS privacy module, or do you mean that you switch to some other DNS service?
I switch in iOS VPN section. From AG VPN to DNScloak.

**Comment by Quorum75** [comment]
Does any one on your side has a Sonos system?

**Comment by Quorum75** [comment]
Remember...

Sonos browsing work with AGDNS DNScrypt but not with AGDNS DoH.

However DNScloak AG DNS DoH works well.

**Comment by ameshkov** [comment]
> Sonos browsing work with AGDNS DNScrypt but not with AGDNS DoH.

Huh, this is interesting! I'll think what can be causing it.

**Comment by Quorum75** [comment]
What?!! And would explain why it's not causing it in DNScloak?

**Comment by ameshkov** [comment]
What what?:) I said I will think about what can be causing it.

**Comment by Quorum75** [comment]
LOL my bad I thought you had an idea. :)

**Comment by Quorum75** [comment]
I tried several tests and I have strange results. 

1.  Adguard Pro
Whitelisting "mclients.googleapis.com" in the DNS section did not help to browse Google Play music service. 

KO Adguard 3.0.12 DNS Default - Regular or DNSCrypt or DoH or DoT 
KO Adguard 3.0.12 DNS Family - Regular or DNSCrypt or DoH or DoT. 

KO Adguard Pro 2.1.2 DNS Default or Family - Regular or Encrypted.

OK DNScloak with Adguard DNS Default or Family with or without DoH.

**Comment by Quorum75** [comment]
@ameshkov Hello any feedback on this issue?

I also found out that DNS DoH prevents album covert to appear. It works for only with DNSCrypt, any idea why? The DNS Log being empty I can't figure out why.

**Comment by ameshkov** [comment]
@Quorum75 would you mind trying beta version of AdGuard v4.0? A lot has changed since the previous version and it may be that the issue is already fixed.

**Comment by Quorum75** [comment]
@ameshkov Indeed everything is working fine now. However, it is hard to figure out where the problem was coming from because at the time of the issue only AdGuard Pro was running and still is in parallel with AdGuard 4, because only the Pro version can block Ads within iOS apps. 

By the way, I have been told that the Wide System from AG Pro will ne added to AG for Premium users. My question is, what will be left to AG Pro? why keeping 2 apps when one is never updated and will look like a duplicate?

**Comment by zzebrum** [comment]
@Quorum75 we planned to update AG Pro functions and make it equal to AG free version. 
you can read about it here: https://adguard.com/en/blog/adguard-pro-is-back.html

**Comment by Quorum75** [comment]
@zzebrum You are saying is that we paid an app to get functionalities that are free in the new one? Kind of strange. 

“ we will add system-wide filtering to our regular app and then we’ll update AdGuard Pro to match it in features.“
Should we understand here that both applications will be the same in final? Are talking about matching the free or paid features?

**Comment by zzebrum** [comment]
@Quorum75 what we have now:
- the old AG Pro app with 1 content blocker for Safari and system-wide ad blocking;
- new AG free app with 6 content blockers for safari and Premium (paid) functions - system-wide ad blocking.

in both cases system-wide ad blocking is paid feature.

**Comment by Quorum75** [comment]
FYI I have both paid applications activated. I am using AG Pro as my DNS wide system and AG Premium on the side, as the number of rules in AG Pro is already at its maximum in the Privacy section. 

I am sorry but personally I found everything pretty confusing, about today and tomorrow. Maybe a chat will be better to illustrate the differences?

**Comment by zzebrum** [comment]
@Quorum75 you can always contact us via email: devteam@adguard.com or apple@adguard.com

**Comment by Quorum75** [comment]
Yes I will but I am not sure I am the only person. Then, a clear description might be the interest of everyone.
