### ISSUE TITLE
Whitelist not working 

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1072]
Steps to reproduce

Trying to add a domain into the Whitelist section. 

Expected behavior

Operating normally.

Actual behavior

"Filter cannot be loaded into Safari."

Video of the issue : https://file.io/rE0bbX

Your environment

User ID: 2219646
Beta Tester iOS AG 3.0.1
iPhone XS Max or iPad Pro 11
iOS 12.3.1
Wi-Fi ac

**Comment by ameshkov** [comment]
Duplicate of https://github.com/AdguardTeam/AdguardForiOS/issues/1062

**Comment by Quorum75** [comment]
Sorry I looked but didn't find any recent one. I missed this one. Cheers
