### ISSUE TITLE
Missing filter tag

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardForiOS#1076]
Nordic filter
A tag is missing or there is an extra space here.
<details><summary>Screenshot:</summary>

![newtab](https://user-images.githubusercontent.com/34379403/59704275-609df580-9204-11e9-867a-e3fb895f6d39.png)

</details>

Also,there are no tags under these 2 filters.Is this normal?
<details><summary>Screenshot:</summary>

![newtab (1)](https://user-images.githubusercontent.com/34379403/59703824-70690a00-9203-11e9-962f-28633cd4464a.png)

</details>

### Your environment
* Device model and storage size: iPhone 5s 16gb
* Operating system and version: 12.3.1
* Browser: Safari
* Wi-fi

**Comment by zzebrum** [comment]
one more issue here @IvanIin :

<details>

![image](https://user-images.githubusercontent.com/44832195/59759131-18c8ae00-9298-11e9-8861-904cb1ed73ab.png)


</details>

**Comment by PentagramTr** [comment]
Filter tag issue still persists.This is not resolved in 3.0.1

<details><summary>Screenshot:</summary>

![59703824-70690a00-9203-11e9-962f-28633cd4464a](https://user-images.githubusercontent.com/34379403/62004905-1168b000-b134-11e9-83be-968334440f82.png)


</details>

**Comment by zzebrum** [comment]
there are no tags for those filters.
