### ISSUE TITLE
Internet is blocked when switching between Wi-Fi and a cellular connection

### ISSUE THREAD

**Issue by Marco224** [AdguardTeam/AdguardForiOS#1077]
hello there! I don't want to be the finicky part, but I care about Adguard's stability. The iusse concerning the problem already exists and was well described in past, even if it concerns another app... (AdGuard pro 2.1.1)
The bug presented here (and in the related threads) is also present in the new version of Adguard 3.0.1 (143)
I just wanted to add that the problem as it occurs in Full-Tunnel (with or without icon) so it occurs in Split-Tunnel but manifests itself in a different way, more rarely, and in this case the icon vpn disappears.

### Steps to reproduce
1. Setting up Full-Tunnel or Split-Tunnel and “restart when network changes” on

2. Access to a WiFi network

3. Open an app that requires a data connection (safari or other)

4. Disable the WiFi from the control center

5. Quickly initiate a data request by clicking a link on safari or other

### Expected behavior
The data request is successful by opening the link clicked or doing as required by the other app

### Actual behavior
The Internet is completely blocked, signalled by an infinite loading wheel on the status bar.
In split-tunnel also disappears the icon vpn

here are some examples:

iphone 6s iOS 12.3.1 Adguard 3.0.1 (143) Full-Tunnel (with icon) and "restart when the connection changes" on
https://uploadfiles.io/v8qhu7pm

iphone 6s iOS 12.3.1 Adguard 3.0.1 (143) Split-Tunnel and "restart when connection changes" on
https://uploadfiles.io/rj5dkqn0

**Comment by TheHasagi** [comment]
@Marco224 

Can you check with the 3.0.1 (156)?

**Comment by Marco224** [comment]
I can not give you a certain answer. I have updated my devices to the developer beta 3 of iOS 13, so I can only tell you that on this version the problem is not present with any version of Adguard 3.0, including the 3.0.1 (156)

**Comment by zzebrum** [comment]
reopen if needed

**Comment by Marco224** [comment]
Hey there! I'll reopen the report because trying to reuse the privacy module of AdGuard free 3.0.2 (157) with the beta 8 of ios13 continues to present the problem. 

I enclose in case you need the video. (Sorry for the 2 minutes video length but I wanted to play a normal use of the device without forcing the bug)

Keep an eye on the 4g/Wi-Fi icon. The banner appears at the bottom

https://ufile.io/w4y9zrci
