### ISSUE TITLE
"Edit" button in user filter

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#108]
Can you give us an "edit" button in user filter?

I add a lot of lines in userfilter, then I want to remove some of them or all that I did add. Also for testing, I do need to add and remove. If I swipe and delete, it takes time before it loads everything up.If you can click edit button. You select the lines in userfilter, that you want to delete and push delete, it loads one time only. Much faster and easier. 

Just like the filters section in ios app, we have an "edit" button over there, just click the edit button, select the filters you want or dont want. Click done.  One time loading.

**Comment by ameshkov** [comment]
More than this, we should implement some kind of a "filter creation dialog".

**Comment by ameshkov** [comment]
Can't yet give you an ETA, working on the "pro" version now. We'll update the roadmap after that.

**Comment by worldsdream** [comment]
I really need the edit feature. So I am able to delete more lines at one time. Takes me more then 3 minutes if I want to remove 10 lines right now.

**Comment by worldsdream** [comment]
This is going to be closed as we do have an input mode right now. When we dont want rules, we can remove them.
