### ISSUE TITLE
Reinstalled the 3.0.1 app on ios12.0 iphoneX and now no filters load

### ISSUE THREAD

**Issue by SleazyHedgehog** [AdguardTeam/AdguardForiOS#1080]
### Steps to reproduce

1.wifi won’t connect when privacy is toggled on
2.delete reinstall app from test flight
3.log in to ad guard beta key account
4.no filters load, refresh, restart, reinstall, again no filters load

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Device model and storage size: (e.g. iPhone 6s 64gb)
* Operating system and version: (e.g. 10.3.1)
* Browser (e.g. Safari)
* Wi-fi or mobile internet connection

**Comment by SleazyHedgehog** [comment]
alright fixed this issue by going into settings and disabling all adguard extensions under the safari content blocker settings.

now the only issue is wifi will not connect no matter the dns server with dns privacy toggled on

**Comment by ameshkov** [comment]
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Reproduce the issue (and remember the exact time when it happened).
2. Disable "DNS Privacy"
3. Open the app, tap "Send Feedback", select "Contact Support"
3. The mail app will be opened, **change the recipient to `apple@adguard.com` (!)**
4. Mention this issue number in the email text

**Comment by ameshkov** [comment]
@IvanIin logs are in the nextcloud

**Comment by IvanIin** [comment]
@SleazyHedgehog i can not reproduce this issue. And logs you sent do not contain logs from tunnel. It seems like the DNS Privacy module was not enabled. Could you tell if the problem is reproduced.

**Comment by zzebrum** [comment]
@SleazyHedgehog hi! Is the issue still reproducible?
