### ISSUE TITLE
Issues with the user filter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1081]
AdGuard still has problems with user filters. When I add new user filters I often get the following problems:

- Error message "Filters can’t be loaded into Safari. The last changes could not have been applied because of that." Filter is displayed in the user filter list for a short time and then disappears again.
- AdGuard crashes when I try to edit filters
- Deleted user filters reappear again after a few seconds
- Imports are reverted after a few seconds and the old filters are back again

When I restart Safari and AdGuard, it works without any problems for a while until it starts again. Really weird.

Oh by the way, the "Search" button in the user filter list is difficult to hit. You actually have to tap to
 the left of the button on the iPhone X. If you tap directly on it, nothing happens.

iPhone X, iOS 12.3, AdGuard 3.0.0(141)

![IMG_0050](https://user-images.githubusercontent.com/22617697/59968113-8133bb80-9534-11e9-98f4-5ceccb7ff608.png)

_Originally posted by @Superkloton in https://github.com/AdguardTeam/AdguardForiOS/issues/1013#issuecomment-504695452_

**Comment by PentagramTr** [comment]
> Oh by the way, the "Search" button in the user filter list is difficult to hit. You actually have to tap to
the left of the button on the iPhone X. If you tap directly on it, nothing happens.

I have that same problem.
Search icon doesn't respond at the first click.The icon works after clicking several times.Sometimes I have to click 10-20 times for it to works.

**Comment by unmec** [comment]
Hello there,

I have just experienced a similar issue that I can reproduce in the following way with:
- Adguard 3.0.1(156)
- iOS 10.3.3

Steps:
1. Enter user rules section and click import
2. Choose a txt file, UTF-8 encoded, contains several hundreds of rules from a local file management app
3. Back to Adguard, it crashes within 1 second

I have also tested the export with just one user rule, then import again, Adguard still crashes.

Happy to help if more information is required for debugging, thanks for making Adguard.

**Comment by Superkloton** [comment]
And I still get the "Filters couldn't be added to Safari" error occasionally when adding filters via the element picker in Safari. The new filters would then disappear again from the user filter list. Very annoying!

**Comment by zzebrum** [comment]
@unmec this might be a different bug. Anyway, I'll check it on Monday and create a new task for it. You can provide us with log files? Reproduce the issue, go to AdGuard settings - Send feedback - Contact support - change the recipient here to apple[at]adguard.com

@Superkloton thank you for reporting the problem still persist. Can you also send us log files?

**Comment by Superkloton** [comment]
I did already for issue #1137. It's in Nextcloud.

**Comment by unmec** [comment]
@zzebrum It's like the following:

```
2019/07/27 14:30:41:882 [1764987(com.apple.main-thread)]  Application started. Version: 3.0.1.156
2019/07/27 14:30:41:882 [1764987(com.apple.main-thread)]  (AppDelegate) Preparing for start application. Stage 1.
2019/07/27 14:30:41:884 [1764987(com.apple.main-thread)]  (PurchaseService) checkPremiumExpired
2019/07/27 14:30:41:884 [1764987(com.apple.main-thread)]  (AppDelegate) Preparing for start application. Stage 2.
2019/07/27 14:30:41:884 [1764987(com.apple.main-thread)]  (AppDelegate) Stage 2. Main service started.
2019/07/27 14:30:41:895 [1764987(com.apple.main-thread)]  (AppDelegate) Set background fetch interval: 10800.000000
2019/07/27 14:30:41:895 [1764987(com.apple.main-thread)]  (AppDelegate) Stage 2 completed.
2019/07/27 14:30:41:902 [1764987(com.apple.main-thread)]  (AppDelegate) applicationDidBecomeActive.
2019/07/27 14:30:41:998 [1764987(APVPNManager)]  (APVPNManager) Updated Status:
No manager instance.
2019/07/27 14:30:41:998 [1764987(com.apple.main-thread)]  (APVPNManager) Vpn configuration successfully loaded: Google DNS
2019/07/27 14:30:42:005 [1764987(com.apple.main-thread)]  (APVPNManager) Notify others that vpn connection status changed.
2019/07/27 14:30:42:006 [1765025(AAService)]  (ASAntibanner) repair update state - reset download session
2019/07/27 14:30:42:039 [1764991(NSOperationQueue 0x17402cbc0 :: NSOperation 0x17004bf10 (QOS: DEFAULT))]  (AppDelegate) Update process started by timer.
2019/07/27 14:30:42:039 [1764991(ASAntibanner)]  (AESAntibanner) begin background task
2019/07/27 14:30:42:040 [1764991(NSOperationQueue 0x17402cbc0 :: NSOperation 0x17004bf10 (QOS: DEFAULT))]  (AppDelegate) Begin of the Update Transaction from - invalidateAntibanner.
2019/07/27 14:30:42:046 [1764987(com.apple.main-thread)]  (ASAntibanner) Didn't start update process.
2019/07/27 14:30:42:046 [1764987(ASAntibanner)]  (AESAntibanner) end background task
2019/07/27 14:30:42:046 [1764987(com.apple.main-thread)]  (AppDelegate) Rollback of the Update Transaction from ASAntibannerDidntStartUpdateNotification.
```

Meanwhile in system crash log I can see the main thread crashed:
```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Application Specific Information:
abort() called

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed
```

Please note also that 1) I have VPN enabled on my phone but it's not by Adguard, 2) Adguard was first installed on this device like 2 years ago.

Hope it helps!

**Comment by unmec** [comment]
I have just realized that user custom rule section is now a paid feature. I guess the reason my AdGuard crashes is because I have been using this function for two years while it was free. Although it's a rare situation but it would be better to notify user with a proper hint somehow.

**Comment by Superkloton** [comment]
@unmec Custom rules (basically filter lists in a text file) are paid. User filters (that's the ones you can add via the element picker in Safari for example) are free.

**Comment by unmec** [comment]
@Superkloton Oh I didn't know that, thanks for pointing out. No wonder why I can still manually edit user filters. Then it's user filters that I was referring to.

3.0.2 was just made available to me on App Store, AdGuard now crashes when I click on just 'Import' in user filters section.
