### ISSUE TITLE
Issue with removed rules

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardForiOS#1087]
Even if we remove the rules, they still work.
### Steps to reproduce

1.Add rules to the User Filter.
2.Go to the site,refresh the page, confirm that the rules are working.
3.Remove the rules from the user filter.
4.Go back to the site and refresh the page.

### Expected behavior
Ads should appear again

### Actual behavior
Rules removed but ads still doesn not appear

(Also tried the site with private tab, but it was still the same.)

### Your environment

* Device model and storage size: iPhone 5s 16 GB
* Operating system and version: iOS 12.3.1
* Browser : Safari
* Wi-fi
* AdGuard Premium

**Comment by ameshkov** [comment]
It will be much more clear what's going on when https://github.com/AdguardTeam/AdguardForiOS/issues/1105 is done
