### ISSUE TITLE
V3.0 Filter Date is cut in ios 13 beta 1 PB

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#1088]
The filter date in both 3.0 and 2.1.1 in Regular and in Pro is cut . Not complete.

 Time is cut off next to Check for Updates.

Also reported here:

https://forums.macrumors.com/threads/-ios-13-working-broken-and-meh-apps.2183813/

Also VPN icon is missing for both Split Tunnel and FullTunner. ( not sure if this is ios bug or adguard bug )

Please close if this is duplicate.

Tried in iPadOS 13 and iOS13

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForiOS/issues/1088
