### ISSUE TITLE
Twitter share text not complete

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#109]
When clicking on the twitter icon in adguard ios app, it gives you a twitter popup to share. The image of adguard is correct, but the text is like:

Adguard - Adblock for iOS:

Is this like it should?

**Comment by ameshkov** [comment]
Not sure:)

**Comment by vbagirov** [comment]
We decided to change the text to 'premade'. The exact wording is not agreed upon yet.

**Comment by worldsdream** [comment]
Add some words like, amazing, outstanding, most advanced. To make it more "wow".
