### ISSUE TITLE
Google DNS Changing Endpoint to dns.google

### ISSUE THREAD

**Issue by Ryan-Goldstein** [AdguardTeam/AdguardForiOS#1091]
As announced today, Google Public DNS is changing their endpoint from dns.google.com to dns.google and in compliance with RFC 8484. The Google DNS option in the DNS Privacy section should be updated accordingly.

Details: https://security.googleblog.com/2019/06/google-public-dns-over-https-doh.html

**Comment by ameshkov** [comment]
Dup of #1092
