### ISSUE TITLE
Homepage icon

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardForiOS#1093]
I clicked the icon several times but it does not respond.
This issue only happen on some filters
Like two filters below

```
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/SocialShareList.txt
https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_newsletters.txt
```

### Steps to reproduce

1.
2.
3.
4.

### Expected behavior
The icon should open the filter page.

### Actual behavior
The icon is not responding.

<details><summary>Screenshot:</summary>

![IMG_5790](https://user-images.githubusercontent.com/34379403/60226455-f59f8f00-9893-11e9-8cb4-86b546cf228b.jpg)

</details>

### Your environment

* Device model and storage size: 5s 16 GB
* Operating system and version: iOS 12.3.1
* Browser : Safari
* Wi-fi

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForiOS/issues/1033
