### ISSUE TITLE
Whitelist does not work

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1097]
### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Device model and storage size: (e.g. iPhone 6s 64gb)
* Operating system and version: (e.g. 10.3.1)
* Browser (e.g. Safari)
* Wi-fi or mobile internet connection

**Comment by ameshkov** [comment]
Duplicate of https://github.com/AdguardTeam/AdguardForiOS/issues/1062

**Comment by Quorum75** [comment]
This was an error but I could not delete the post. Sorry.
