### ISSUE TITLE
Rename "Enter DNS upstreams" to "DNS server address"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1098]
I am talking about the "new custom DNS server" dialog.

Here's where it comes from:
https://github.com/AdguardTeam/AdguardForiOS/issues/1054

**Comment by lancelot-moon** [comment]
In AG for iOS v3, lack the below information.
`DNS upstreams one per line`
`IP, sdns://, https:// or tls://`
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/yHFlDMp.png)
</details><br/>

Honestly, I think it'll be enough if you mark them in app.
Anyway, it's up to you.
Sorry.

**Comment by Mowd** [comment]
Rename upstreams to address is more readable for anyone.
IP is an address, sdns, https or tls all of them are address.
Upstreams make people or non-IT people confused.

**Comment by ameshkov** [comment]
Yep, that's why I want to get rid of the "upstream" word everywhere.
