### ISSUE TITLE
Add "Trial period" and lifetime in-app option to the Get Premium screen

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1100]
Obviously, we should provide these options.

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/34ecf397-2ffd-4c50-b7a9-aff10f6a9317

**Comment by ameshkov** [comment]
New version:
https://share.goabstract.com/1fd34ff9-f8b5-40cf-ba64-5652b506caf9?mode=design&sha=20b8b798654f627fb485fc5ddcf271eef6f16963

**Comment by zzebrum** [comment]
In dark mode:
<details>

![IMG_0053](https://user-images.githubusercontent.com/44832195/62866743-47a05500-bd1a-11e9-9458-e0f1c11db3d9.PNG)


</details>
