### ISSUE TITLE
Add "Export logs" option to the "Send feedback" menu

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1102]
Sometimes, it's inconvenient to send an email with the logs. Also, the user may not have the Mail.app configured and this basically prevents him or her from getting to AdGuard logs.

Here's what I suggest:
1. Add "Export logs" option to the "Send feedback" menu
2. Logs must be placed to a single archive file. Name format: `adguardforios_logs_DDMMYYYYHHMISS.zip`
3. When the user opts to "contact the support" , we should attach the same archive instead of multiple archives as we do now.

**Comment by planet0** [comment]
Yes please, I use the Gmail app and only use Mail to send you logs.
