### ISSUE TITLE
Allow setting rules affinity to a content blocker

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1104]
The main issue with using multiple content blockers is that rules inside these content blockers cannot influence each other. This may lead to different unexpected issues. For instance, like this one: https://github.com/AdguardTeam/AdguardForiOS/issues/1055

I suppose we should let filters maintainers control the rules "affinity" to a content blocker by using a new pre-processor directive.

More info on the pre-processor directives:
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#pre-processor-directives

### `!#safari_cb_affinity`

Defines Safari content blockers affinity for the rules inside the `safari_cb_affinity` block.

**Syntax**
```
!#safari_cb_affinity(list)
@@||example.org^
example.org##banner
!#safari_cb_affinity
```

* `!#safari_cb_affinity(list)` -- start of the block.
* `list` -- comma-separated list of content blockers. There are 6 pre-defined values:
    * `general` -- "AdGuard - General" content blocker
    * `privacy` -- "AdGuard - Privacy" content blocker
    * `social` -- "AdGuard - Social" content blocker
    * `security` -- "AdGuard - Security" content blocker (missing from the 
    * `other` -- "AdGuard - Other" content blocker
    * `custom` -- "AdGuard - Custom" content blocker
    * `all` -- special keyword that means that the rules must be included into ALL content blockers.
* `!#safari_cb_affinity` -- ends the block of rules

**Comment by slavaleleka** [comment]
add this filter list as custom filter 
https://raw.githubusercontent.com/slavaleleka/webweb/master/customlist.txt

and do to [checkadblock.ru](https://checkadblock.ru)

<details>
  <summary>Expected result</summary>

![slbdzd8llfd08](https://user-images.githubusercontent.com/45171506/63264708-695a8880-c294-11e9-9881-221bb4012264.png)
 </details>
<details>
  <summary>Actual result</summary>

![slbdzd8ld48sx](https://user-images.githubusercontent.com/45171506/63264753-80997600-c294-11e9-9af4-16d4d3f6a964.png)
 </details>
