### ISSUE TITLE
Add "Content Blockers State" screen to the advanced settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1105]
This screen should be somewhere under "Advanced" settings, and it's purely informational.

Here's what we should show there:

* Content blocker name
* Content blocker state (enabled or disabled)
* Filter lists included into this content blocker
* Content blocker rules state (everything is okay, rules loading is in progress, an error occurred while loading the rules)
* The number of rules loaded into the content blocker
* If the number of rules is more than 50k, we should show how many rules were ignored

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/f634f9d6-e340-417b-bcb5-26316fad3316

filters and content blockers

**Comment by IvanIin** [comment]
Incorrect number of enabled and disabled rules are showed when you enable a lot of content blockers. 
<img width="431" alt="Screenshot 2019-08-05 at 10 20 43" src="https://user-images.githubusercontent.com/28860202/62446208-d3d6d900-b76a-11e9-84fd-c3ddbc68c5a8.png">

**Comment by ameshkov** [comment]
Moved back to in progress
