### ISSUE TITLE
Specify why exactly "protection is disabled" on the main screen

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1106]
Currently, even if a single one of the content blockers are disabled, we will show "protection is disabled"  on the main screen.

We should show short explanation (instead of showing the filters state): `One or many of AdGuard's content blockers are disabled in Safari settings. Please, enable all of them.`.

@AlikhanAliev ideally, I'd like to show which exact content blockers are disabled.

**Comment by worldsdream** [comment]
Yes please. A must!

**Comment by ameshkov** [comment]
Let's have three possible statuses:

* `Protection is disabled` -- all content blockers are disabled
* `Some content blockers are disabled` -- self-explanatory
* `Protection is enabled`
