### ISSUE TITLE
Restore the "system-wide blocking" functionality

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1107]
I see some apps on the App Store with system-wide blocking functionality, so there's a big chance that "AG Pro" will pass the review. Therefore, we should start restoring the system-wide blocking functionality.

Here are some ideas for you @AlikhanAliev:

1. Show the graph of the blocked/processed requests on the main screen
2. Allow enabling or disabling system-wide blocking from there
3. Show some total stats there: how many trackers were blocked? how many requests were processed?
5. Show some of these stats on the widget
5. Rework the requests log, mark "blocked" requests properly.
6. Detect if the domain belongs to a known tracker, show the tracker details (category and such).
7. Allow quickly blocking and unblocking requests from the log
8. Add blacklist/whitelist

Also, we should consider doing some renaming.

For instance:

1. Filters --> Safari Protection
2. DNS privacy -> System Protection

**Comment by bigdargon** [comment]
Good news!! Hope the Pro version will also be updated!

**Comment by iDjay** [comment]
How can we beta test the pro version when it‘s online?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by planet0** [comment]
It's good to see the Pro update passed recently! 🎉https://github.com/AdguardTeam/AdguardForiOS/issues/1112#issuecomment-510200614

**Comment by ameshkov** [comment]
> How can we beta test the pro version when it‘s online?

See the future plans here:
https://adguard.com/en/blog/adguard-pro-is-back.html

We're not going to push Pro updates unless the regular one matches it in the system-wide filtering part.

**Comment by lancelot-moon** [comment]
Only mentioned blacklist/whitelist above.
Will you bring DNS filters subscription to v3?

BTW, I more like the UI of AG Pro v2.
