### ISSUE TITLE
Add cancel button to configure Action extension

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForiOS#1110]
1. Install AG but do not run it
2. go to Safari and try to use Action extension

Actual behavior:
https://uploads.adguard.com/Screenshot_2019-06-05_at_18.04.41_2019-07-04_19-42-10.png

Expected behavior: an option to exit the screen (:

**Comment by AlikhanAliev** [comment]
![image](https://user-images.githubusercontent.com/30260021/63928895-1e413200-ca59-11e9-9aeb-44ae0e4c375a.png)
