### ISSUE TITLE
Remove "malware domains" filter list from AdGuard for iOS

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1112]
Apparently, there can't be any malware on iOS. The Pro version cannot pass the review because of this.

**Comment by iDjay** [comment]
True. @ameshkov are you working on a new pro version?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Eugene-Savenko** [comment]
@iDjay https://github.com/AdguardTeam/AdguardForiOS/issues/1107

**Comment by ameshkov** [comment]
@iDjay we're just trying to push the old update that was rejected a year ago. If it passes the review, it will indicate that we can proceed with #1107.

**Comment by lancelot-moon** [comment]
Malware domains filter was removed from the security group in the latest testflight version.

May you modify the overview on App Store?
- Security filters. Protect yourself from dangerous websites riddled with malware or fraud.
-> - Security filters. Protect yourself from dangerous websites riddled with **Crypto-jacking** or fraud.

B/R

**Comment by ameshkov** [comment]
Good catch! @zzebrum please take a look at the AppStore description.

**Comment by lancelot-moon** [comment]
The overview for AG Pro on App Store also need to be modified.
Delete `Malware Domains`.
— Includes popular adblocker filter subscriptions - EasyList, EasyPrivacy, Fanboy's Annoyances, Malware Domains. Block ads like a pro both with the public and AdGuard's own filters.
-> — Includes popular adblocker filter subscriptions - EasyList, EasyPrivacy, Fanboy's Annoyances...etc. Block ads like a pro both with the public and AdGuard's own filters.

**Comment by ameshkov** [comment]
Already modified in the version that is currently on review

**Comment by lancelot-moon** [comment]
But overview on onesky still aren't updated.
Good night.
Hope that you recover soon!

**Comment by lancelot-moon** [comment]
For more than 6 years, AdGuard helps all of its users enjoy the safe and clean Internet.

**Comment by aalpatkina** [comment]
resolved
