### ISSUE TITLE
AdGuard Pro 2.1.1 - Split-Tunnel not working in iOS 13 Public beta 2

### ISSUE THREAD

**Issue by stex12** [AdguardTeam/AdguardForiOS#1115]
AdGuard Pro - Split Tunnel not working in iOS 13 Public beta 2, it keep looping connect and disconnect, makes the network unusable. 

Temporary fix is switch to Full-Tunnel. 

Application version: 2.1.1(165)
Device: iPhone X
Platform: iOS
OS: 13.0 Public beta 2
Locale: en
Region: us

**Comment by Eugene-Savenko** [comment]
Works fine on my end; AdGuard Pro 2.1.1, iOS 13.0 public beta 2.

**Comment by ameshkov** [comment]
It's okay in v3.0.1 so if we're able to push updates to Pro, we'll resolve this.
