### ISSUE TITLE
Option to send crash logs automatically

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1116]
Wouldn’t it be easier if you add an option to send crash logs from the dns privacy feature f.e. Automatically? Other apps have that option too.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ameshkov** [comment]
Well, in the case of Apple, they already took care of it, crash reports are sent automatically, and we can see them in XCode.

**Comment by iDjay** [comment]
Thought about the VPN crash logs @ameshkov 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ameshkov** [comment]
@iDjay they're also collected and sent by Apple
