### ISSUE TITLE
Adding more rules in User Filter "Enter Rule" before pushing on Done

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#112]
See screenshot example:

1) http://i.imgur.com/8Wznbta.png
2) http://i.imgur.com/LHNt8Wh.png

Can you give us an add option in User Filter "Enter Rule", so we can add more rules there at once and then click on Done button?
When we want to add for example 4 rules. We need to add one single rule and click Done. It will load it up. Then we need to repeat 3 more times. Takes to much time for something just simple as that.

The better and easier for the users: Add rule and click Done, if you want to enter more rules, click the Add sign in top (screen1) or below the input (screen2) click the add more rule, a new input comes up below the last input in the screen and you can add your rule there, every time you hit the add button, a new input comes up. User only click once at Done and it does load into Adguard blocker.

**Comment by ameshkov** [comment]
Simpler solution is to make the text box multiline, so you'll be able to enter multiple rules at once.

**Comment by worldsdream** [comment]
That would be great too. Why dont we have that in adguard extension browser? Copy multiple rules and paste, instead copy one by one?

**Comment by ameshkov** [comment]
We will have it too, but after a redesign:)

**Comment by worldsdream** [comment]
This has been added. So it's closed.
