### ISSUE TITLE
Wrong URL for the tracking protection filter

### ISSUE THREAD

**Issue by grgnday** [AdguardTeam/AdguardForiOS#1120]
[Same thing for the ios app](https://github.com/AdguardTeam/AdguardForWindows/issues/2828)

**Comment by ameshkov** [comment]
@08kovalchuk03 you should simply update the filters metadata and make sure that we have them up-to-date on the server.

**Comment by 08kovalchuk03** [comment]
@grgnday when app starts filters metadata is force updated, we've checked data on the server and now it should work fine)
