### ISSUE TITLE
Add "filter details" screen

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1122]
See the artboard:
https://share.goabstract.com/209a6653-6e29-42c7-8f4b-4f905bb2833b?mode=design&sha=085c5f12cb92d51dd240fdad49cd82534f79b4b0

**Comment by zzebrum** [comment]
1. Filter name is missed.
2. don't forget to Change Enabled\Disabled to On\Off toggle #1169
3. align the On button to the left

**Comment by SoLenny** [comment]
Make headings bold.
https://uploads.adguard.com/solenny4y665.png
