### ISSUE TITLE
Change the "custom filters" section layout

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1124]
* https://share.goabstract.com/7e5ae2be-dbb1-4754-9696-8790705fe321?mode=design&sha=6a434811d3e723b03519d040cd0006bbac11e803
* https://share.goabstract.com/a428b367-84f7-45b7-a8e7-20c9d18f4e62?mode=design&sha=5f8ea3a1aeaf097d0559c9a784fcfbf671332d05 (please note, that it will be possible to set custom title)
* https://share.goabstract.com/12a0e6be-c12d-4531-8fa2-046354824e78?mode=design&sha=085c5f12cb92d51dd240fdad49cd82534f79b4b0

**Comment by zzebrum** [comment]
@08kovalchuk03 

when adding custom filter a link to homepage is underlined: https://share.goabstract.com/12a0e6be-c12d-4531-8fa2-046354824e78?mode=design&sha=085c5f12cb92d51dd240fdad49cd82534f79b4b0
