### ISSUE TITLE
Change the user filter and whitelist layout

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1125]
See the artboard:
* https://share.goabstract.com/ea996f24-68c2-4398-985f-ebe607b87caf?mode=design&sha=085c5f12cb92d51dd240fdad49cd82534f79b4b0

1. Regarding rules highlighting rules, use the same colors as we do in the Mac version.
2. Add "edit mode"

**Comment by zzebrum** [comment]
please, fix this. In whitelist too
<details>

![IMG_909D538BFC67-1](https://user-images.githubusercontent.com/44832195/62939020-ed19fe00-bdd8-11e9-8640-9eb9ada3602a.jpeg)


</details>
