### ISSUE TITLE
Crash when creating custom rule

### ISSUE THREAD

**Issue by alex11123** [AdguardTeam/AdguardForiOS#1127]
### Steps to reproduce

1. Create new rule in safari with picker
2.click open in adguard once done 
3. App crashes
4.

### Expected behavior

No crash 

### Actual behavior

Crash a few seconds after creating, rule is not saved. Doesnt happen all the time.

<details><summary>Screenshot:</summary>

</details>

### Your environment
Ipad pro 11” ios 12.3.1
Wifi

**Comment by Superkloton** [comment]
You mean user filter, not custom rules. Update to 3.0.1 and try if it still happens.

**Comment by zzebrum** [comment]
@alex11123 update to the latest 3.0.1(156) version, please.

**Comment by zzebrum** [comment]
reopen if needed.
