### ISSUE TITLE
Copy feature

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardForiOS#1132]
There must be a "Copy" feature to copy rules.
Like that

<details><summary>Screenshot:</summary>

![f9920cbb819ab20ffc41d537bff287cb](https://user-images.githubusercontent.com/34379403/61313641-84ecf200-a803-11e9-9386-249feda7cdb3.png)

</details>

### Your environment

* Device model and storage size: 5s
* Operating system and version: iOS 12.3.1
* Browser: Safari
* Wi-fi

**Comment by ameshkov** [comment]
Availbe via "Edit mode"
