### ISSUE TITLE
Incorrect count of filters after the update

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForiOS#1133]
Incorrect counter after the update from 3.0.0 to 3.0.1. 

### Steps to reproduce

1. Install 3.0.0
2. Enable 6 filters of 87
3. Update to 3.0.1
4. Check for enabled filters

### Expected behaviour

Filters should be counted as 6

### Actual behaviour

Filters counted as 4

**Comment by IvanIin** [comment]
@TheHasagi  We can not reproduce this bug. Can you reproduce it and record a video? Then upload the video and app logs to ncloud please.
