### ISSUE TITLE
Missed translations in v3.0.1 release.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1134]
1. Missed translations.
These phrases are early translated on onesky, but the translations aren't applied in app.
May you update translations again and take them?
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/6dGrOKF.png)

![image](https://i.imgur.com/oPXUYE3.png)
</details><br/>

2. When clicking "login", it should lead to the localized login page, but now it's the English login page.

3. Please update the overview of both AG for iOS v3 and AG Pro v2 on app store.
You know that you did some changes in the overview.
Some other languages' translations for new overview are ready.

**Comment by SoLenny** [comment]
Still missed Chinese localization in some screens. 
https://uploads.adguard.com/solenny0ss0c.png
https://uploads.adguard.com/solennyi5mz3.png
https://uploads.adguard.com/solennymr411.png

**Comment by lancelot-moon** [comment]
@SoLenny
Some phrases (ex: your 1st screenshot) were modified or uploaded to Crowdin **today**.
BTW, some translations which were done 6 days ago aren't applied in your 2nd screenshot.
My translations for new changes are already done.
Need to update locales files again.

Your 3rd screenshot belongs to AdGuard's website.
If you **ever visited** AdGuard's Traditional Chinese [中文 (繁體)] website, it should show Traditional Chinese login page.
<details><summary>Screenshots:</summary>

![image](https://uploads.adguard.com/solennymr411.png)
</details><br/>

Thanks.

**Comment by SoLenny** [comment]
@lancelot-moon
 Thanks for feedback :)

**Comment by lancelot-moon** [comment]
A missed translation in v3.1.233 release.
`Lost password?`
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/I7SlTVN.jpg)
</details><br/>

https://crowdin.com/translate/adguard-applications/17552/en-zhtw#3906142
