### ISSUE TITLE
Minor translation issues

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardForiOS#1136]
Please update the Turkish translation.

Incorrect                          | Correct
---                                    | ---
Beyazliste                     | Beyaz liste
Geribildirim gönder | Geri bildirim gönder
Bir filtre ekle | Filtre ekle
Bir kural ekle | Kural ekle
Özel kurallarınızı buraya girin **Kural sözdizimi hakkında**bu notu okuyun. | Özel kurallarınızı buraya girin. **Kural sözdizimi hakkında** bu notu okuyun.
Süre | Saat
Geçti | Geçen süre

AdGuard for iOS—Turkish translation

<details><summary>Screenshot:</summary>

![trsn](https://user-images.githubusercontent.com/34379403/61486536-5c542c00-a9ac-11e9-82b7-b1b2aac75435.PNG)

</details>

---

**Updated phrases**

Current                           | Updated
---                                    | ---
Updating...                    | Güncelleniyor...
DNS Privacy | DNS Gizliliği
Value your private data | Özel verilerinize önem verin 
SELECT | SEÇ
DNS server address | DNS sunucusu adresi

<details><summary>Screenshot:</summary>

![upt](https://user-images.githubusercontent.com/34379403/61487765-590e6f80-a9af-11e9-98f9-3a0a2130f220.png)

</details>

**Comment by aalpatkina** [comment]
@PentagramTr Your translations have been approved on OneSky. Thanks.
@IvanIin please update the Turkish localization.

**Comment by PentagramTr** [comment]
@zzebrum 


* Please use capital **D** — [ **Desteklenmeyen URL** ]


* **OK** should be translated as **Tamam**

![1](https://user-images.githubusercontent.com/34379403/62093890-a201d600-b283-11e9-817a-dc5bf2fa27aa.png)

**Comment by zzebrum** [comment]
@PentagramTr 

It's a system error message, not ours.
