### ISSUE TITLE
[3.0.1][User filter] Crash when tapping on "Add rule"

### ISSUE THREAD

**Issue by Superkloton** [AdguardTeam/AdguardForiOS#1137]
### Steps to reproduce
1. Go to the user filter section
2. Tap on "Add rule" at the top

### Expected behavior
Mask with a text field to enter a new filter rule opens

### Actual behavior
App crashes to springboard

### Your environment
[state.txt](https://github.com/AdguardTeam/AdguardForiOS/files/3412450/state.txt)
* Device model and storage size: iPhone X 64GB
* Operating system and version: iOS 12.2
* Wi-fi or mobile internet connection: Both

**Comment by zzebrum** [comment]
@Superkloton please send logs file to apple[at]adguard.com (AdGuard settings - Send feedback - Contact support - change the recipient here)

**Comment by Superkloton** [comment]
Done!

**Comment by zzebrum** [comment]
@IvanIin please, take a look.

**Comment by ameshkov** [comment]
Logs are in nextcloud

**Comment by 08kovalchuk03** [comment]
@Superkloton could you provide extra info about bug, i cannot reproduce it
In fact, when you tap "add rule" the only thing that happens is showing another view controller, and nothing can happen there.
It would be usefull if you provided more info about steps to reproduce an issue.

**Comment by Superkloton** [comment]
Unfortunately there's nothing more to it, I described the exact steps how it happens for me every single time. I literally crashes the app every time. A hundred times out of hundred tries the app crashes. Go to settings > user filters and tap "+ Add rule" on top of the user filter list. App crashes for me on iOS 12.2 iPhone X 64 GB. 

Maybe this helps: I have quite a few of my own user filters, around 500.

**Comment by zzebrum** [comment]
@Superkloton how many rules are there approximately?

**Comment by Superkloton** [comment]
@zzebrum around 500.

**Comment by zzebrum** [comment]
@Superkloton so, you were talking about rules, not filters :) 
@08kovalchuk03 @IvanIin any ideas?

**Comment by Superkloton** [comment]
@zzebrum the button is called "+ Add Rule" but the section in the app is "User filters". A filter is also a "rule", isn't it? I'm not talking about the premium "customer rules" in the filters section!

It's settings > user filters and NOT settings > filters > custom!!

**Comment by iDjay** [comment]
here's a video reproducing the issue with AdGuard 3.0.2 on iOS 13b5
https://we.tl/t-HumD7DdxND

**Comment by ameshkov** [comment]
Cannot reproduce on v3.1 dev build. We should re-test it when the beta version is out.

**Comment by Superkloton** [comment]
No this was a problem in an older version. The issue is over a month old. It works in the latest (non-beta) version 3.0.2.

I have however still the problem that added filters disappear again with the error message "filters could not be added to Safari right now" regularly. This is really annoying (#1081).

**Comment by ameshkov** [comment]
> I have however still the problem that added filters disappear again with the error message "filters could not be added to Safari right now" regularly. This is really annoying

This one should now be gone in v3.1 beta

**Comment by SebastianRasch** [comment]
This is happening again in 3.1.4, it crashes every time I tap on the plus icon.
I also lost all my user filters (~350) when I edited a range of search results (text editor view).

Why does AdGuard have so many problems with the user filters? It feels like a broken beta version all the time. This is the most important part of the adblocker for me, it should work reliably. Gonna take me months to get all my filters back.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zzebrum** [comment]
@SebastianRasch can you try the last beta version? If you are not in the beta program, I can add you there.

**Comment by SebastianRasch** [comment]
OK I tried the 4.0 beta and user filters seem to work fine. However, you can’t badge edit search results anymore. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SoLenny** [comment]
@SebastianRasch Hello, could you clarify what you mean by `you can’t badge edit search results anymore.`?

**Comment by SebastianRasch** [comment]
When you search for a website for example, it shows you all the filters for this website. You can’t edit those results as a group though (edit button at the bottom). Not really important since you can still edit them separately but it was nice to be able to do that. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zzebrum** [comment]
@SebastianRasch a bit complicated for regular editor, but we'll keep your suggestion in mind. Thank you!
