### ISSUE TITLE
AdGuard VPN prevents DAZN App from launching

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1138]
I can‘t get into „DAZN“ while being connected with AdGuard DNS VPN. They don‘t support VPN connections. Is it possible to fix it because AdGuard DNS is not a real VPN connection?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BlazDT** [comment]
Not reproduced on my iPhone SE and enabled AdGuard DNS and local VPN.

**Comment by zzebrum** [comment]
@iDjay I assume that DAZN service is working in your region. 
If they somehow can detect that your connection goes through VPN, we can't get around the problem on our side.

**Comment by iDjay** [comment]
@zzebrum 
https://we.tl/t-9EXVhdTwsC Video with the issue. Any chance to solve it by adding DAZN to a white list? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment]
For some reason it‘s working again, not sure if you changed something or it’s the new iOS 13 beta 6 but it‘s working :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
