### ISSUE TITLE
You need to refresh a page in order to make ads disappear

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#114]
- https://github.com/AdguardTeam/AdguardFilters/issues/2552 - the issue can be reproduce only after refreshing the page, it's somehow related, I think
- Also, was spotted here: https://github.com/AdguardTeam/AdguardFilters/issues/2458

**Comment by ameshkov** [comment]
Need more examples

**Comment by dzamyshlyayeva** [comment]
same issue

<details>

![image](https://cloud.githubusercontent.com/assets/23372054/20640166/c538c43a-b3df-11e6-821e-bd11418679e6.png)
![image](https://cloud.githubusercontent.com/assets/23372054/20640183/23a22bf6-b3e0-11e6-9a2a-1f787d5a26ac.png)
![image](https://cloud.githubusercontent.com/assets/23372054/20640189/2d04b09c-b3e0-11e6-9388-313d2882ddd1.png)
![image](https://cloud.githubusercontent.com/assets/23372054/20640192/3f4964c8-b3e0-11e6-9557-67842ca6c060.png)
![image](https://cloud.githubusercontent.com/assets/23372054/20640198/49fc2a2c-b3e0-11e6-86d6-327373a7d822.png)

</details>

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.35 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.16 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.83 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.6.81 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.5.94 Enabled=NO
ID=12 Name="Safari filter" Version=1.0.1.75 Enabled=YES
ID=101 Name="EasyList" Version=1.0.64.87 Enabled=NO
ID=104 Name="EasyList China" Version=1.0.69.93 Enabled=YES

Customer ID: 1422540

**Comment by vozersky** [comment]
obsolete
resolved in Filters
