### ISSUE TITLE
Ram cleaning

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardForiOS#1140]
Some filters are automatically enabled after RAM cleaning.

### Steps to reproduce

1.Turn off active filters.
2Start RAM clean process while AdGuard is on.
Cleaning method -https://www.youtube.com/watch?v=hpzgY4iWT3Q
3.Some filters are automatically activated after cleaning process.

https://streamable.com/v3oy2

### Your environment
* Device model and storage size: iPhone 5s 16 GB
* Operating system and version: iOS 12.3.1
* Browser: Safari
* Wi-fi

**Comment by hdtvspace** [comment]
Dont use ram cleaners on un*x, bsd or linux (Android). Its only marketing to earn money. This false thinking comes often from windows users. The ios kernel use as much ram for file caching.

**Comment by ameshkov** [comment]
Nothing can be changed on our side
