### ISSUE TITLE
Is it possible to let users selectively establish VPN profile in personal VPN or VPN configurations?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1144]
Is dummy VPN the only way of local content blocking for VPN profile in personal VPN?
(ex: FutureMind's AdBlock v2.8)

Is there any other method of local content blocking for VPN profile in personal VPN?

Some real VPNs establish VPN profile in VPN configurations.
If AG/AG Pro can selectively establish VPN profile in personal VPN, those real VPNs (OpenVPN...etc.) will be able to work alongside AG/AG Pro.

Disconnect Premium establish VPN profile in both personal VPN and VPN configurations.
https://apps.apple.com/us/app/disconnect-premium-vpn/id935480186
Its VPN profile in personal VPN is for real VPN (remote filtering), and VPN profile in VPN configurations is for local filtering.
Only use 1 mode at the same time.

**Comment by lancelot-moon** [comment]
This is a feature request.
But I don't know if Apple will allow dummy VPN (or other methods) for local content blocking while VPN profile is established in personal VPN.

**Comment by ameshkov** [comment]
> Is dummy VPN the only way of local content blocking for VPN profile in personal VPN?

Yes:(

> But I don't know if Apple will allow dummy VPN (or other methods) for local content blocking while VPN profile is established in personal VPN.

Actually, they ask everyone to stick to NEVPNManager API (personal VPN) so I don't even know why the old-style VPNs are still available
