### ISSUE TITLE
Bug: can’t login in the latest TestFlight bet version

### ISSUE THREAD

**Issue by F3000** [AdguardTeam/AdguardForiOS#1145]
![51312D53-C893-496E-99DF-C940619EB4DF](https://user-images.githubusercontent.com/8161283/61688077-5354b900-ad24-11e9-98d6-c879f1f89b0c.png)

**Comment by IvanIin** [comment]
@F3000  Please send us the logs and the exact time when the issue occurred

**Comment by F3000** [comment]
Hi here are the requested log files : 
Exact time : 17:49 (German time) 


[cb_annoyances.zip](https://github.com/AdguardTeam/AdguardForiOS/files/3422953/cb_annoyances.zip)
[cb_general.zip](https://github.com/AdguardTeam/AdguardForiOS/files/3422956/cb_general.zip)
[cb_other.zip](https://github.com/AdguardTeam/AdguardForiOS/files/3422957/cb_other.zip)
[cb_privacy.zip](https://github.com/AdguardTeam/AdguardForiOS/files/3422958/cb_privacy.zip)
[state.txt](https://github.com/AdguardTeam/AdguardForiOS/files/3422960/state.txt)

**Comment by Zhijie327** [comment]
@F3000 I have the same issue with you when I reset my iPhone to factory settings. You can try this method, which I have solved on my device:
1. Log in to your account at https://auth.adguard.com/login.html
2. Remove the registered mobile device which is using AdGuard for iOS Pro
3. Re-login on AdGuard for iOS

**Comment by ameshkov** [comment]
@Zhijie327 thank you! That's exactly what @F3000 should do
