### ISSUE TITLE
which version should I use?

### ISSUE THREAD

**Issue by Tspm1eca** [AdguardTeam/AdguardForiOS#1149]
AdGuard v3.0.1 or AdGuard Pro 2.1.2 ?

I bought the Pro version long time along.

**Comment by zzebrum** [comment]
@Tspm1eca I suggest reading the article: https://adguard.com/en/blog/adguard-pro-is-back.html especially the part about future plans and decide for yourself what is best for you based on your needs. Currently, you can use both: Pro version for DNS blocking and a regular version for better content blocking in Safari.
