### ISSUE TITLE
Please add system default DNS and general DNS in AG v3. (Maybe the layout of AG Pro v2 is better)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1151]
In AG Pro v2, it's DNS settings for general DNS and encrypted DNS.
But it's only DNS privacy for encrypted DNS in AG v3.

Consider about the enhancement.
https://github.com/AdguardTeam/AdguardForiOS/issues/1027
It's good to give the options of system default DNS and general DNS in AG v3.
However, it's a little weird if adding general (unencrypted) DNS in DNS privacy (encrypted).
Or modify DNS privacy to DNS settings.

Honestly, I think the layout of AG Pro v2 is better than v3.
I feel they're a bank of crowded settings and poor classification in v3.
The space of main screen in v3 is simply wasted.

In Pro v2, the classification of features is much better and clearer.
Users can easily reach any configurations.

ex: DNS log
In Pro v2, only 1 tap for DNS log.
In v3, need 3 taps for DNS log, which is inconvenient.

Just a user's experience.
Please ignore if you think this isn't good.

**Comment by TheHasagi** [comment]
Similar options will be realized after #1107.
