### ISSUE TITLE
Please give custom time zone setting in AG account and show time zone in New Device Login Alert.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1152]
Today, I activated my license on an iOS device and received the email (New Device Login Alert).
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/sPqxzKC.png)
</details><br/>

However, the time in New Device Login Alert is **Moscow time**.
May you give custom time zone setting in AG account and show **localized time zone** in New Device Login Alert?
ex:
July 31, 2019 15:00 (GMT+8)

**Comment by TheHasagi** [comment]
@lancelot-moon 

Looks legit, we will change format GMT to UTC.
