### ISSUE TITLE
AdGuard VPN prevents AdGuard update

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1153]
You can‘t install today’s 3.0.2 update when AdGuard DNS is enabled. I tried to install it from the AppStore and TestFlight and both didn‘t complete. It seems like Apple has changed something with the new iOS 13 beta 5 which prevents updates from an app you‘re connected via VPN with. Every other update works fine.
Workaround: disable AdGuard DNS during the update

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gurgun-dayioglu** [comment]
IOS 12 seems ok, this should be indeed an ios 13 problem

**Comment by gurgun-dayioglu** [comment]
IOS 12 seems ok, this should indeed be an ios 13 problem

**Comment by iDjay** [comment]
not sure if it was temporary or just an issue with the current beta, I‘ll check again when a new update is online :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zzebrum** [comment]
I think it was kinda AppStore network glitch, please, reopen if the issue will happen again.

**Comment by iDjay** [comment]
So I tried it again with „updating“ from the AppStore to the TestFlight version (which is the same) but it doesn’t work, video:

https://we.tl/t-rra1vQbm6u

Workaround: disable AdGuard VPN. 
This still only happens while VPN is available and just with the AdGuard app. Disable AdGuard VPN and the AdGuard installation is fine. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment]
It‘s definitely an issue with the latest iOS 13 beta, not sure if it‘s a bug or a feature from Apple. But it‘s not your fault :D

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment]
Still happening with iOS 13.1 b2 and AdGuard 3.1 @SoLenny any idea maybe?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SoLenny** [comment]
@iDjay Can u record a video and send me there?

**Comment by iDjay** [comment]
@SoLenny yes, when a new TestFlight / AppStore version is available :) don‘t want to downgrade to 3.0.2 now 😅

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment]
@SoLenny 
https://we.tl/t-YpIXGT5a7P happening on the final iOS 13.0 build

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SoLenny** [comment]
@iDjay Hello.
We will try to fix if soon.
Thank you for feedback.

**Comment by iDjay** [comment]
Not sure if you‘re able to fix it or if it‘s an iOS issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ameshkov** [comment]
Yeah, not sure as well. I don't really understand what's going on, and nothing helpful is in the log.

**Comment by iDjay** [comment]
No one else having this issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zzebrum** [comment]
@tosbsas does have the issue too on iOS 13.1.1

**Comment by iDjay** [comment]
Happening again. iOS 13.2 b3, trying to install AdGuard 3.1.2 Beta...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tosbsas** [comment]
Yep Same here. Need to dísable VPN to be able to install. 

Ruben 




_______________________________
Ruben Gutknecht
Lima, Perú  🇵🇪 
Cel: +51-99349-1515
Voice/Fax: 49 (0) 721-151-379204 
http://telegram.me/tosbsas
paypal.me/RubenGutknecht
Deutschland
tosbsas@gmail.com
ttosbsas@icloud.com

**Comment by iDjay** [comment]
I really have to test it with the next NordVPN Update while being connected to NordVPN to check if it‘s an issue in general.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment]
So this issue still exists. I skipped the TestFlight version and tried to update from 3.1.2 to 3.1.3 via AppStore which failed until I turned AdGuard DNS off.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ameshkov** [comment]
@iDjay is any DNS a problem or is it just with AdGuard DNS?

**Comment by iDjay** [comment]
@ameshkov just with AdGuard. NordVPN Updates without any problems while being connected to NordVPN.
But maybe it was an iOS issue which is fixed with 13.3. Have to wait again for the next AdGuard update.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ameshkov** [comment]
Appears to be a known issue of Apple NEPacketTunnel provider. However, Apple support said that this is a random issue and sometimes it happens:)

Reference:
https://forums.developer.apple.com/thread/128894
