### ISSUE TITLE
Hope to add a chinese filiter

### ISSUE THREAD

**Issue by loveqqzj** [AdguardTeam/AdguardForiOS#1157]
Hope to add a chinese filiter, it's very useful for many chinese webpages, his github homepage is https://github.com/YanFung/Ads.
The filiter address is https://raw.githubusercontent.com/YanFung/Ads/master/Mobile.txt
Please help to add it, thanks very much!

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/FiltersRegistry #216](https://github.com/AdguardTeam/FiltersRegistry/issues/216) via [**ZenHub**](https://www.zenhub.com/)
