### ISSUE TITLE
Change DNS status to Disabled if DNS privacy is disabled

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForiOS#1158]
If DNS privacy module is disabled: https://uploads.adguard.com/Image_2019-08-05_12-36-02.png

we should put the status Disabled on Settings screen: 

https://uploads.adguard.com/Image_2019-08-05_12-36-43.png

**Comment by ameshkov** [comment]
Let's do in v3.1.

v3.2 brings some really serious changes to DNS filtering functionality so this issue won't be relevant anymore.

**Comment by zzebrum** [comment]
closed as dup #1178
