### ISSUE TITLE
Adguard doesn't block any ad if you disable/enable it in 'Content blockers' settings

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#116]
Adguard doesn't block any ad if you disable/enable it in Content blockers. Other ad blocking apps work fine and do not have such behavior.

STR:

* go to settings > safari > content blockers
* disable Adguard
* enable Adguard
* go to any site with ads
* reload it or wait, the ads won't get blocked
* go to Adguard > check updates 
* go to a site, refresh the page - voila! ads are blocked

**Comment by ameshkov** [comment]
This is clearly Safari issue, we have nothing to do with it.

**Comment by evgeniy-ADG** [comment]
> 1Blocker
> Eluo
> I test here more es 10 content blocker, this content blocker are not in iOS multitasking. No issue. It blocking ad site!!
