### ISSUE TITLE
Crash when editing whitelist

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1161]
Video: 
https://we.tl/t-XpLJqqv82i
AdGuard 3.0.2
iOS 13 b5
crash happens wenn you click on "delete"
Workaround: click on the domain name instead and „remove“ it from the list.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zzebrum** [comment]
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Reproduce the issue (and remember the exact time when it happened).
2. Disable "DNS Privacy"
3. Open the app, tap "Send Feedback", select "Contact Support"
3. The mail app will be opened, **change the recipient to `apple@adguard.com` (!)**
4. Mention this issue number in the email text

**Comment by iDjay** [comment]
@zzebrum I thought you‘ll receive crash logs automatically? At the moment I can‘t update my whitelist, it always results in an issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment]
ah shit, never mind. it's an issue with the user filter, not the whitelist, so it's a duplicate with #1137 but still happening with 3.0.2

**Comment by iDjay** [comment]
okay this is weird, it's the same issue as #1137 but this time it's happening in whitelist and not user filter, however when I tried it in user filter, it crashes too.

**Comment by akmLaVx** [comment]
Additional logs available from user 2317247.

**Comment by ameshkov** [comment]
@akmLaVx is it still happening on v3.1?

**Comment by akmLaVx** [comment]
yes, we have an open issue: 2317247

**Comment by 08kovalchuk03** [comment]
@akmLaVx I can't find one file, that would be helpful, in your logs. It would be useful, if you send logs after crash to apple@adguard.com once more.
