### ISSUE TITLE
sports.ru

### ISSUE THREAD

**Issue by alexeykhon** [AdguardTeam/AdguardForiOS#1162]
Высылаю отчёт об ошибке?

**Comment by zzebrum** [comment]
@alexeykhon о какой ошибке идет речь?

**Comment by alexeykhon** [comment]
Использую приложение на iOS, версия 2.1.2
Столкнулся с проблемой, Адгард перестал блокировать рекламу в приложении sports.ru.

Прошёл по ссылке в браузере, чтобы проверить работу блокировщика, вышло такое сообщение: флеш-баннер не заблокирован.

Помогите решить проблему.

Thanks and kind regards
Cordiali saluti

Alexey Khon
6 авг. 2019 г., 12:23 +0200, zzebrum <notifications@github.com>, писал:

**Comment by zzebrum** [comment]
@alexeykhon какой ДНС сервер вы используете?

**Comment by alexeykhon** [comment]
Системный днс


Thanks and kind regards
Cordiali saluti

Alexey Khon
7 авг. 2019 г., 16:07 +0200, zzebrum <notifications@github.com>, писал:

**Comment by zzebrum** [comment]
@alexeykhon для блокировки рекламы в приложениях выберите обычный или семейный AdGuard DNS в настройках приложения.
