### ISSUE TITLE
Failure to properly disable filters/Adguard for iOS

### ISSUE THREAD

**Issue by gsk-jp** [AdguardTeam/AdguardForiOS#1164]
If you try to disable multiple filters in some categories at the same time, it looks like you've disabled them all in the display, but when you restart the app, only the first one you disabled is disabled and everything else remains enabled.

**Comment by gsk-jp** [comment]
![78ACB99C-4A4F-46FC-BC8C-33AA7A0A1ABE](https://user-images.githubusercontent.com/51118638/62767376-7aa2d880-bacf-11e9-869b-b6bef7b045fe.gif)

**Comment by zzebrum** [comment]
@gsk-jp enabling\disabling filters take about 30 seconds in the background, sometimes even more. So when you kill the app, you kill the unfinished process too.
