### ISSUE TITLE
Filter group details screen is broken after toggling on/off status

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForiOS#1171]
<details>

![IMG_2D9A4F482FF5-1](https://user-images.githubusercontent.com/44832195/62794645-46ceaf80-badd-11e9-8e9e-67c2f0b7ae14.jpeg)

</details>

**Comment by 08kovalchuk03** [comment]
@zzebrum can't reproduce

**Comment by zzebrum** [comment]
@08kovalchuk03 seems to be fixed with some other task.
