### ISSUE TITLE
Content blockers screen issues

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForiOS#1172]
1. Do not show enabled filters from disabled groups on Content blockers screen
2. There is "You have 5 content blockers.." sentence. But now we have 6 content blockers

Actually, let's discuss new strings with @aalpatkina on Monday
3. `41 498 out of 50 000 rules are being used` change to `41 498 rules are being used`

**Comment by SoLenny** [comment]
Still there is "You have 5 content blockers.." sentence. But now we have 6 content blockers.
https://uploads.adguard.com/solennyo97gc.png
https://uploads.adguard.com/solennyohdde.png

**Comment by SoLenny** [comment]
Fixed in 3.1(193) build.
