### ISSUE TITLE
When enabling a filter, let it update immediately

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#118]
**What happened:**
I enabled annoyance filter and went to a website that had a cookie, I saw the cookie. 
I did go to adguard app, I clicked on update. Annoyance filter got updated. It worked again. Not every person will do that. They will think, huh I enabled it, and it's not working.

**What should happen:**
I enable annoyance filter, it does load the uptodate annoyance filter from server, i go to the website with the cookie, I don't see the cookie.

**Comment by ameshkov** [comment]
We really cannot improve this situation. Safari applies content blocker updates asynchronously and we don't know when exactly it has finished.

What we do now is waiting for a callback from Safari signalling that updated content blocker was successfully compiled. It takes pretty much time, but still does not guarantee that Safari has already applied it.

**Comment by ameshkov** [comment]
Argh, sorry, now I understand your question

**Comment by ameshkov** [comment]
@Stillness-2 do we schedule an update check for the filter which was turned on?

**Comment by worldsdream** [comment]
It would be even better if you enable a filter, it will fetch the filter that you enabled from server and fetch all others that you have enabled as well. 

Example: you have english and spyware, you want annoyance to enable

Enable annoyance, it fetches the annoynce filter from server and also fetches english and spyware. Customer is up to date.

**Comment by Stillness-2** [comment]
@ameshkov 
>do we schedule an update check for the filter which was turned on?

I think no.. :(

**Comment by Stillness-2** [comment]
I found some bugs, which i fixed. Also I changed logic of the loading of the filter rules, when subscription is performed. Now we attempt to load rules from backend server firstly.

@worldsdream About `and fetch all others that you have enabled as well.`. I do not see important reason to do this. Because, when you enter into Adguard, and time has come to update, Adguard performs update.

**Comment by worldsdream** [comment]
Ok great! I hope it will fetch now from server after enabling a filter
