### ISSUE TITLE
Long URLs are incorrectly truncated in Filtering Log

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#1181]
### Issue Details

- **AdGuard version:** 3.0+
- **Device model and storage size:** iPhone 8, unspecified size
- **Operating system and version:** iOS 12.4
- **Browser or App:** n/a

### Expected Behavior

Long URLs in Filtering Log are incorrectly truncated. They cannot be neither selected nor copied.

### Actual Behavior

Truncated URLs in Filtering Log should either (a) expand on tap or (b) display its full address using word wrap.

### Screenshots

<details><summary>Screenshot:</summary>

![IMG_4210](https://user-images.githubusercontent.com/33634917/62955759-49414a00-bdfa-11e9-8781-85c156987088.png)

</details>

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/a81e46b0-41a6-4034-ad56-2243300dc0aa?sha=a300566945e29599277befd951ea7de8e888c1ea

We should copy a cell content, when we tap it. Like in our Android app
