### ISSUE TITLE
Cannot login anymore to Beta version

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1182]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - Beta AdGuard for iOS v3.0.2 (157)
- **Device model and storage size:**
  - iPad Pro 11' 128Go
- **Operating system and version:**
  - iOS 12.4
- **Browser or App:**
  - Safari

### Expected Behavior

Login as Beta testeur

### Actual Behavior

Pop up error window

### Screenshots

"An error occurred when trying to,login"

![IMG_0421](https://user-images.githubusercontent.com/49731083/63025128-d8a53680-bea8-11e9-9214-c54a22407840.png)

### Additional Information

Tried to contact the support twice but didn't get any answer.

**Comment by zzebrum** [comment]
@Quorum75 my bad, sorry for that. I got your logs and devs will look at them. 

Have you tried to reinstall the app?

**Comment by Quorum75** [comment]
Yep but it did not work. Strangely I could login on my iPhone. 

Sent from my iPad Pro

On 14 Aug 2019, at 15:36, zzebrum <notifications@github.com> wrote:

@Quorum75 my bad, sorry for that. I got your logs and devs will look at them.

Have you tried to reinstall the app?

**Comment by zzebrum** [comment]
Just in case, can you check your personal account and unbind the iPad?

**Comment by Quorum75** [comment]
I already checked. The iPad is not present, only the iPhone. 


Address not found
Your message wasn't delivered to quorum75@gmail.com because the address couldn't be found, or is unable to receive mail.
LEARN MORE
The response was:
550 5.1.1 The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at https://support.google.com/mail/?p=NoSuchUser r8sor18192229qtp.58 - gsmtp


On 14 Aug 2019, at 18:19, zzebrum <notifications@github.com> wrote:

Just in case, can you check your personal account and unbind the iPad?

**Comment by Quorum75** [comment]
I already checked. The iPad is not present, only the iPhone. 

On 14 Aug 2019, at 19:22, mailer-daemon@googlemail.com <quorum75@gmail.com> wrote:

I already checked. The iPad is not present, only the iPhone. 


Address not found
Your message wasn't delivered to quorum75@gmail.com because the address couldn't be found, or is unable to receive mail.
LEARN MORE
The response was:
550 5.1.1 The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at https://support.google.com/mail/?p=NoSuchUser r8sor18192229qtp.58 - gsmtp


On 14 Aug 2019, at 18:19, zzebrum <notifications@github.com> wrote:

Just in case, can you check your personal account and unbind the iPad?

**Comment by Quorum75** [comment]
Any other idea?

**Comment by zzebrum** [comment]
@Quorum75 

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Reproduce the issue (and remember the exact time when it happened).
2. Disable "DNS Privacy"
3. Open the app, tap "Send Feedback", select "Contact Support"
3. The mail app will be opened, **change the recipient to `apple@adguard.com` (!)**
4. Mention this issue number in the email text

**Comment by Quorum75** [comment]
I am sorry to say but this issue has been reported already since a week through 3 connections: here, to Adguard support and the email you mentioned. Also you said in your previous message that you already got the logs hence mm y messages. 

Finally please check my message... I can't disable DNS Privacy because it is not activated as I cannot login....

**Comment by zzebrum** [comment]
@Quorum75 Unfortunately, there was nothing helpful in those files :( 

> I can't disable DNS Privacy

then skip this step :)

**Comment by Quorum75** [comment]
@zzebrum Just sent it again. 

FYI no issue to connect on the website and with my my iPhone. The problem seems to be related only with the iPad.... 🤔

**Comment by zzebrum** [comment]
problem solved.

**Comment by Quorum75** [comment]
Special thanks to Maria 😉
