### ISSUE TITLE
White zone in Custom section

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardForiOS#1184]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Go to Filters - Custom - Add a filter.
A white zone still appears while clicking Continue and Cancel.
The same problem also exists on the login screen.

- **AdGuard version:** 3.0.2
- **Device model and storage size:** iPhone 5s 16 GB
- **Operating system and version:** iOS 12.4
  

### Screenshots

<details><summary>Custom section:</summary>

![IMG_6057](https://user-images.githubusercontent.com/34379403/63225425-90ec1b00-c1d8-11e9-88db-f033e526f832.PNG)

</details>

<details><summary>Login screen:</summary>

![IMG_6095](https://user-images.githubusercontent.com/34379403/63380453-3bae3600-c39f-11e9-8c2d-9083c2fc3f19.PNG)

</details>

### Additional Information

https://vimeo.com/354493461

**Comment by SoLenny** [comment]
Bug is fixed, but now missed localization of "next" button. (turkish localization)
https://uploads.adguard.com/solennygfu8c.png

**Comment by SoLenny** [comment]
https://github.com/AdguardTeam/AdguardForiOS/issues/1201
