### ISSUE TITLE
Localized distorted screen issues

### ISSUE THREAD

**Issue by SoLenny** [AdguardTeam/AdguardForiOS#1186]
**Steps to reproduce:**

1. Install last build 3.1(173).
2. Open device settings (iPhone 5S).
3. Open Safari settings.
4. Open "Content Blockers".
5. Allow some content blockers (not all, this important).
6. Open AdGuard main screen.

**Expected behavior:**

Status "Some content blockers are disabled" fully displayed.

**Actual behavior:**

Status not fully displayed, like "Some content blockers are dis..."

**Screenshot:**

https://uploads.adguard.com/solennygjx3n.png

**Comment by SoLenny** [comment]
In Russian localization layout of “Auto-update over Wi-Fi only” is displaced.

https://uploads.adguard.com/solennybhdi0.png

**Comment by SoLenny** [comment]
In Russian localization on the license screen layout of “Free trial for 1 week” is not fully displayed. build 3.1(177)
https://uploads.adguard.com/solennytvmd8.png (iPhone X)
https://uploads.adguard.com/solennyxj56u.png (iPhone 5s)

**Comment by SoLenny** [comment]
In Russian localization in General settings "Invert whitelist is not fully displayed. build 3.1(177)

https://uploads.adguard.com/solennyptgtn.png

**Comment by SoLenny** [comment]
In Russian localization in Filters "Social Widgets" is not fully displayed. build 3.1(177)

https://uploads.adguard.com/solennyh9hz7.png
https://uploads.adguard.com/solennyk9fe1.png

**Comment by SoLenny** [comment]
Still not fully displayed names of filters group. 3.1(190)
https://uploads.adguard.com/solennysgfdv.png
https://uploads.adguard.com/solenny85w7e.png

**Comment by IvanIin** [comment]
it’s ok to trim names in titles. This is the default behavior in ios applications.
