### ISSUE TITLE
Minor description text changes (user/custom filter related)

### ISSUE THREAD

**Issue by vyanovsky** [AdguardTeam/AdguardForiOS#1187]
Заменить "Value your private data" на "Protect your personal data" (см. картинку 1)
![1](https://user-images.githubusercontent.com/51786050/63268521-06b9ba80-c29d-11e9-908a-181c10c18fa5.png)

В описании (картинки 2а и 2b) user filter изменить:

Contains custom filtering rules -> Add your own filtering rules
Enter your custom rules here -> Enter your user-made rules here

![2а](https://user-images.githubusercontent.com/51786050/63268560-1d601180-c29d-11e9-817f-03bc41b1b0b2.png)
![2b](https://user-images.githubusercontent.com/51786050/63268564-2224c580-c29d-11e9-96b9-da581bcd56d4.png)

**Comment by ameshkov** [comment]
@08kovalchuk03 make sure that the new strings are uploaded to Crowdin

**Comment by SoLenny** [comment]
Still unchanged description of DNS.
https://uploads.adguard.com/solennyczjp6.png

**Comment by lancelot-moon** [comment]
https://crowdin.com/translate/adguard-applications/17552/en-zhtw#3905584
Enter your custom rules here -> Enter your user-made rules here -> Enter user-made rules here
(Please delete "your" here.)
