### ISSUE TITLE
"Restart when network changes" tumbler problem

### ISSUE THREAD

**Issue by SoLenny** [AdguardTeam/AdguardForiOS#1192]
**Steps to reproduce:**

1.Clean install last build 3.1 (177).
2.Open General settings.
3.Click on "Restart when network changes".
4.Click "Don't Allow".

**Expected behavior:**

Tumbler switched to OFF position.

**Actual behavior:**

Tumbler stay in ON  position.

**Comment by zzebrum** [comment]
Should we show the same error notification as we do when press `Don't Allow` button while creating VPN profile or we can show the error message something like `You need to enable VPN first`?
