### ISSUE TITLE
Login migration

### ISSUE THREAD

**Issue by 08kovalchuk03** [AdguardTeam/AdguardForiOS#1193]
uses licenseKey from keychain

**Comment by 08kovalchuk03** [comment]
[adguardforios_logs_232.zip](https://github.com/AdguardTeam/AdguardForiOS/files/3520996/adguardforios_logs_232.zip)

**Comment by 08kovalchuk03** [comment]
logs are in nextcloud

**Comment by IvanIin** [comment]
There was no error during login migration. There was an error related to inconsistent app state which led to many glitches, such as broken login, inability to add rules from action extension, and so on.
It is dificult to reproduce this behaviour. You must  install the application, launch it and kill it through the task manager before filters sucessfully installed. 
Launch it a second time and try logging in.
