### ISSUE TITLE
Proximity based enabling

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#1194]
### Problem Description

No associated problems detected.

### Proposed Solution

Quoting the user,

> I use pi-hole at home, then enable adguard pro on my iPhone when I leave my household. Would it be possible to add proximity based activation of the app on the iOS platform so this can be done on an automated basis?

### Alternatives Considered

None available.

### Additional Information

Reported by user 2291414

**Comment by SoLenny** [comment]
@akmLaVx 
Hello, thank you for the question, we are already working on it.
You can see details here https://github.com/AdguardTeam/AdguardForiOS/issues/1045 

If there will be any other question please, do not hesitate to reopen or leave a comment here. As for now the issue is closed.
