### ISSUE TITLE
(Pro) 1 filter updated, with 0 filters enabled

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForiOS#1195]
### Issue Details

- **AdGuard version:**
  - AdGuard Pro for iOS 2.1.2 (173)
- **Device model and storage size:**
  - iPhone 8 Plus 64GB
- **Operating system and version:**
  - iOS 12.4

### Expected Behavior

No filters are updated if no filters are selected

### Actual Behavior

1 mysterious filter is updated from time to time 👻

**Comment by SoLenny** [comment]
@planet0 
Hello, To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:

Reproduce the issue (and remember the exact time when it happened).
Open the app, tap "Send Feedback", select "Contact Support"
The mail app will be opened, change the recipient to apple@adguard.com (!)
Mention this issue number in the email text. And indicate the exact time when this error occurs (this important).

**Comment by planet0** [comment]
Hi @SoLenny, just reproduced the issue for you and sent an email now as provided. 👍🏼

**Comment by SoLenny** [comment]
@planet0 
I am very sorry that I didn't immediately say that at the moment we are not developing the pro version, but this does not mean that we no longer support it, in the near future we plan to revise this application. Once again, I apologize for the inconvenience.
