### ISSUE TITLE
www.very.co.uk - can't disable filtering for this site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#120]
![image](https://cloud.githubusercontent.com/assets/15856304/17165458/3368509a-53d9-11e6-95b9-cd092fe4e91e.png)
Cant disable Adguard on www.very.co.uk using the 'enable on this website' toggle on the share sheet extension, states filters cannot be loaded into Safari.

state
<details>
Application version: 1.0.8.54
Application lifetime: 2016-07-07 8:09:07 am +0000

Device: iPhone
Platform: iPhone OS
OS: 10.0
ID: B34DCDCD-F1F3-491E-AFDF-E724756E30C5

Locale: en
Region: gb

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.90 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.59 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.10.72 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.2.10 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.94 Enabled=YES
</details>
**1233134**

**Comment by vozersky** [comment]
I was able to reproduce it on ipad mini 2

**Comment by ameshkov** [comment]
Great!

**Comment by evgeniy-ADG** [comment]
The same for any other site

**Comment by vozersky** [comment]
Just tried to reproduce in iOS 10 public beta 6.
Looks like the problem is gone.
