### ISSUE TITLE
Whitelist incorrect behavior 

### ISSUE THREAD

**Issue by SoLenny** [AdguardTeam/AdguardForiOS#1202]
**Steps to reproduce:**

1. Install last build 3.1(190).
2. Open Whitelist editor.
3. Enter something there.
4. Save.
5. Delete.

**Expected behavior:**

What you wrote deleted and no longer displayed.

**Actual behavior:**

What u wrote isn't deleted and still displays.

Besides, if u exit whitelist and open it again, what u wrote can randomly appear and disappear.

**Comment by IvanIin** [comment]
fixed in 3.1.1
