### ISSUE TITLE
Vpn

### ISSUE THREAD

**Issue by noahamato1** [AdguardTeam/AdguardForiOS#1203]
My vpn keeps trying to reconnect every like 10 min. It would connect and i would start watching a youtube video and my internet would cut of because its trying to connect again.

**Comment by SoLenny** [comment]
@noahamato1 
Hello, To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:

Reproduce the issue (and remember the exact time when it happened).
Open the app, tap "Send Feedback", select "Contact Support"
The mail app will be opened, change the recipient to apple@adguard.com (!)
Mention this issue number in the email text. And indicate the exact time when this error occurs (this important).

And can you specify which version you use? ( free or pro)
Thanks.

**Comment by SoLenny** [comment]
@noahamato1 Hello. Цe didn't wait for an answer from you, therefore we are forced to close the task. If you run into a problem again feel free to open the task again
