### ISSUE TITLE
NBC iOS app video ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#121]
http://www.wilderssecurity.com/threads/adguard-dns-beta.387403/page-2#post-2606280

Check if it's possible to block these ads on DNS-level.

**Comment by xxcriticxx** [comment]
can you add history app it has 30 sec in stream adds. how do i get my hands one pro ver?

**Comment by ameshkov** [comment]
> how do i get my hands one pro ver?

You can take part in the beta test. More information here:
https://forum.adguard.com/index.php?threads/adguard-for-ios-beta-test.6344/

**Comment by Bohdan-SUP** [comment]
Any update on this?

Source report:
https://forum.adguard.com/index.php?threads/adguard-pro-ios-dns-and-tv-apps.14757/#post-107065

Logs in ticket 1021351

**Comment by ameshkov** [comment]
Should be filed to AdguardFilters,  sorry for waiting so long before closing it
