### ISSUE TITLE
Trial-page fixes

### ISSUE THREAD

**Issue by SoLenny** [AdguardTeam/AdguardForiOS#1213]
1. Change square to point like hear (https://uploads.adguard.com/solenny1ll5v.png) 
2. In dark theme change color of the point to color of the text like it done in light theme.
3. In dark theme change color of the heading (now https://uploads.adguard.com/solenny8mbh1.png)

**Comment by IvanIin** [comment]
also for lifetime license:
4. Write "Pay once and use AdGuard Premium features on all your devices!" above price selection button
5. hide last feature with thumbsup icon
