### ISSUE TITLE
VarageSale app is broken by Adguard Pro DNS blocking

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#122]
https://itunes.apple.com/ca/app/varagesale-buy.-sell.-shop./id622859960?mt=8

**Comment by Stillness-2** [comment]
@gshumihin Could you please test this on last pro beta? Before that add domain `cdn.optimizely.com` to whitelist.

**Comment by gshumihin** [comment]
The app can't even load while VPN is on.

**Comment by gshumihin** [comment]
My bad, added wrong domain in whitelist. Everything works fine with `cdn.optimizely.com` added to whitelist.

**Comment by Stillness-2** [comment]
@ameshkov @Alex-302 
We need decide what to do with this domain. It is blocked by Adguard DNS.

**Comment by ameshkov** [comment]
@Alex-302 please take care of it

**Comment by Alex-302** [comment]
Excluded

**Comment by jo2dan23** [comment]
@Alex-302 the @@|| filter was forgotten when you added it to exception list xD

**Comment by jo2dan23** [comment]
It looks like m.varagesale.com is being blocked by bnc.lt

**Comment by Alex-302** [comment]
> optimizely

Fixed exclusion. 


> bnc.lt

it is related to branch.io. Maybe it should be excluded. 
I can't this app.
@gshumihin Could you check this app again?

**Comment by Alex-302** [comment]
@Alex-302

**Comment by jo2dan23** [comment]
@Alex-302 i can test.

**Comment by jo2dan23** [comment]
Bnc.lt is the cname for m.varagesale somehow.. so it needs to be in dns exceptions

**Comment by Alex-302** [comment]
@jo2dan23 Exclusion will be applied after 2-3 hours.

**Comment by jo2dan23** [comment]
@Alex-302 if you go in browser to: http://m.varagesale.com/m/vLcp7UumTn  it is blocked by bnc.lt

**Comment by jo2dan23** [comment]
App works now @Alex-302

**Comment by Alex-302** [comment]
@jo2dan23 ok, thanks.
