### ISSUE TITLE
Long adding domain into inverted whitelist

### ISSUE THREAD

**Issue by SoLenny** [AdguardTeam/AdguardForiOS#1221]
**Steps to reproduce:**

1. Install build 3.1(209).
2. Enable inverted whitelist.
3. Write anything there.

**Expected behavior:**

Domain appears immediately.

**Actual behavior:**

Domain won't appear until u close whitelist and open it again or it can appear after several attempts.

**Comment by SoLenny** [comment]
https://github.com/AdguardTeam/AdguardForiOS/issues/1211

**Comment by ameshkov** [comment]
@SoLenny don't forget to set a milestone when you create new issues
