### ISSUE TITLE
System default appearance is inverted

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1223]
1. Install 3.1 beta
2. Change appearance to system default 
3. appearance is inverted
System white = AdGuard dark
System Dark = AdGuard white
iOS 13.1, AdGuard 3.1 (209)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment]
Update: it‘s inverted
System white = AdGuard dark
System Dark = AdGuard white
iOS 13.1 b1, AdGuard 3.1 (209)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SoLenny** [comment]
@iDjay Hello, can toy please reproduce it and send us a video?
I managed to reproduce only that the light theme is always used, regardless of the theme of the phone
Thank you.

**Comment by iDjay** [comment]
@SoLenny True, at the Moment both a Set to light, but yesterday it was dark during the day, will check tonight if it switches to dark when iOS changes to dark. Maybe it was an issue with iOS 13.1 b1 and yesterday‘s b2 fixed it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SoLenny** [comment]
@iDjay Thank you for the feedback. We will fix it as soon as possible!

**Comment by iDjay** [comment]
@SoLenny stays white, yes.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by IvanIin** [comment]
it will be fixed when ios 13 is released

**Comment by iDjay** [comment]
Not fixed with 222 build and iOS 13 GM build (final Version) @SoLenny 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SoLenny** [comment]
Hello, @iDjay.
We hid the possibility of choosing a "system default" theme until iOS 13 officially released.

**Comment by iDjay** [comment]
Still not working 🙃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment]
Fixed

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
