### ISSUE TITLE
Suggest to move language-specific filters from "general" to "other" content blocker. 

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1224]
A Safari content blocker can only contain 50k rules.
AG Base filter is a big guy.
AG Mobile Ads filter is also not small.
**Usually language-specific filters are larger.**
You can check the rules count of EasyList China (big guy).

Now, those filters in "other" group won't be used by me.
Suggest to move language-specific filters from "general" to "other" content blocker.

**Comment by zzebrum** [comment]
@lancelot-moon it may work incorrectly this way. Please read here: https://github.com/AdguardTeam/AdguardForiOS/issues/1104

**Comment by lancelot-moon** [comment]
Which filters groups belong to which content blockers, which is defined by AG team.

I can't understand your reply.
Why will it incorrectly work?

**Comment by ameshkov** [comment]
If we move them to another content blocker, they won't be able to override rules from the base filter list, and they often need to do this.
