### ISSUE TITLE
Update filters over "mobile data" (with a greater update period)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#123]
We currently do not check for updates at all when device is on mobile data. I think we'd better use another solution: let AG check for updates over mobile data, just use a greater update check period.

For instance:
1. Over Wi-Fi == 12 hours
2. Over mobile data: 48 hours

**Comment by worldsdream** [comment]
It would be nice if there was a option in settings, for example: 

Download filters: Wifi, Cellular, Wifi and Cellular.

**Comment by ameshkov** [comment]
Yep, I suppose this should be in the "advanced settings" section.

**Comment by onega** [comment]
Prompt, this feature is only available in the professional version of iOS for Adguard, or Adguard standard (free), too?

**Comment by ameshkov** [comment]
@onega it will be available for both.

If issue is not marked with "PRO" label it is for both versions.
