### ISSUE TITLE
AdGuard crash when clicking on „license“

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1230]
Open AdGuard 3.1 and go to settings -> about -> license. AdGuard crashes.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SoLenny** [comment]
@iDjay Hello, i can't reproduce it on my side.
Which build you use? 3.1(209) is the latest.

Can u try to reproduce it on this build and tell us if this is still reproducing?

**Comment by iDjay** [comment]
Yes, Build 209 on iOS 13.1 b2, iPhone XS

https://we.tl/t-wjJuWCmkKs

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SoLenny** [comment]
@IvanIin It's reproducible on German localization with premium.

**Comment by iDjay** [comment]
Fixed in 222 build

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
