### ISSUE TITLE
Cannot launch update process when 0 filters are enabled

### ISSUE THREAD

**Issue by dsolomakin** [AdguardTeam/AdguardForiOS#1232]
### Issue Details

- **AdGuard version:3.1 (209) **
- **Device model and storage size:**
IPHONE 8 256 GB
OS: 12.3.1

### Expected Behavior

When I tap the "Update" icon on Main Activity, it should start rotating,  check for updates and then say "Latest updates already installed"

### Actual Behavior

When 0 Filters are active, the update icon does not react upon a tap.

@IvanIin 
![photo_2019-09-05 16 20 35](https://user-images.githubusercontent.com/51234660/64345476-1b19e900-cff9-11e9-99d0-9e31850c8cb6.jpeg)
![photo_2019-09-05 16 20 36](https://user-images.githubusercontent.com/51234660/64345477-1b19e900-cff9-11e9-9060-aa4c783f2179.jpeg)

**Comment by IvanIin** [comment]
logs in ncloud
