### ISSUE TITLE
 energized hosts lists in AdGuard Pro not working

### ISSUE THREAD

**Issue by iOS6martinaa** [AdguardTeam/AdguardForiOS#1238]
1. Open AdGuard Pro (2.1.2) -> DNS Settings -> System Default
2. Then go to Privacy Settings -> Add Subscriptions
3. Add a 120K+ Domains hosts list https://raw.githubusercontent.com/EnergizedProtection/block/master/bluGo/formats/hosts
4. Enable the VPN

Result:
But it's not working. It's not blocking anything. And don't see a VPN icon and WiFi icon.

Notes:
https://energized.pro/#packs
The problem concerns all hosts list except the social list. Didn't test them all. Only the Low End Friendly and Mid End Friendly lists.

Device Information:
Device: iPad Air 2
iOS Version: 12.4.1

**Comment by hdtvspace** [comment]
Too large lists. Only lists with max. 50.000 are allowed. Just use there the Adguard SDN- and Standard-Filter.  I use  Pro App for blocking app requests with the VPN DNS and also a pi-hole @home. And the newer Adguard iOS-App *only* for Safari as content blocker with different blockers.  --> best solution.

**Comment by ameshkov** [comment]
Raw list size is about 20MB, while the total memory limit of a packet tunnel extension is 15MB.

**Comment by hdtvspace** [comment]
> Raw list size is about 20MB, while the total memory limit of a packet tunnel extension is 15MB.

No, that's wrong. The size is only 3,7MB pur text...  too much rules over 50.000 is the reason.

**Comment by ameshkov** [comment]
There's no rules limit for the DNS-level blocking rules. The only limit we have there is RAM -- it shouldn't consume more than 15MB.

3.7MB raw size means that it takes at least three times more in the memory (due to the fact that we have to create an additional "index" structure in the memory).
