### ISSUE TITLE
В русскоязычном App Store надписи на скриншотах на английском языке

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForiOS#1241]
### Issue Details

- **AdGuard version:**
  - AdGuard Pro for iOS 
- **Device model and storage size:**
  - 
- **Operating system and version:**
  - 
- **Browser or App:**
  - Browser 

### Expected Behavior
В русскоязычном App Store надписи на скриншотах на русском языке.

### Actual Behavior
В русскоязычном App Store надписи на скриншотах на английском языке.

### Screenshots

<details><summary>Screenshot:</summary>

![screenshot-apps apple com-2019 09 10-21_01_54](https://user-images.githubusercontent.com/19418601/64638373-409a5e80-d40e-11e9-977c-ee677d491882.png)

</details>

**Comment by ameshkov** [comment]
Это поправится автоматически когда мы наконец проху обновим, но надо ждать пока функционал блокировки на системном уровне в основной версии сравняется с AG Pro
