### ISSUE TITLE
When opening AG on iPad it shows not enabled for a second

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#1244]
When opening AG on iPad it shows not enabled for a second

Latest version of AG
Latest iOS version
Ipad 2018 

It’s not happening on my iPhone XS.

**Comment by SoLenny** [comment]
@worldsdream Hello, can you please specify which version ща Adguard and iOS you are using?
Try to reproduce it again and send us the video.

Now i can't reproduce it on my side.

**Comment by worldsdream** [comment]
Hi @SoLenny. See attached recording. 
iOS 12.4
Latest AG in appstore. Not Pro, not beta.

**Comment by SoLenny** [comment]
In near feature we will release new build. Wait for it please :)

**Comment by worldsdream** [comment]
The new build does not have this issue anymore. But it got something new. When opening it for the first time on ipad, it glitches. I can make a record of it and upload.
