### ISSUE TITLE
VPN icon not hidden in iOS 13

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#1246]
# Issue Details

Since updating to iOS 13, VPN icon is no longer hidden even when the corresponding option is selected in the settings.

- **AdGuard version:**
  -3.0.2.157
- **Device model and storage size:**
  - Unspecified iPhone
-  **Operating system and version:**
  - iOS 13.0

### Expected Behavior

VPN icon should be removed when AdGuard is set to not display it

### Actual Behavior

VPN icon is displayed regardless of AdGuard settings

### Screenshots

<details><summary>Screenshot:</summary>

![image0](https://user-images.githubusercontent.com/33634917/64919258-01bf2c80-d7b1-11e9-875b-c916f1f95626.jpg)

</details>

### Additional Information

Helpdesk ID: 1524752

**Comment by Eugene-Savenko** [comment]
The OP states that it still does not hide the VPN properly after the recent patch.

<details> <summary> screenshots </summary>

![image](https://user-images.githubusercontent.com/15856304/66292305-ab936400-e8ec-11e9-889c-939467e8f051.png)

![image](https://user-images.githubusercontent.com/15856304/66292318-b0f0ae80-e8ec-11e9-8a70-4dfff73f7e60.png)

</details>

**Comment by ameshkov** [comment]
Reopened and re-assigned to v3.1 patch2

**Comment by iDjay** [comment]
Would like to see a split tunnel without VPN icon option :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by IvanIin** [comment]
DnsCloak works different way. It does not set ipv4Settings and ipv6Settings. Sets localhost as DNS resolver address. And listen on the 53rd port dns requests. With this configuration, tunnel works in a split mode without vpn icon. To show VPN icons, DnsCloak sets fake ipv4Settings and ipv6Settings.
We can use the same scheme for split tunnel mode. For full tunnel mode, we cannot leave ipv4Settings and ipv6Settings settings empty.
This is a pretty big rework. Let's think and possibly implement the mixed scheme in 3.2

**Comment by 08kovalchuk03** [comment]
looks like it is fixed in 4.0
