### ISSUE TITLE
Full-tunnel not working when automatically switching between IPv6 networks

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#1247]
### Issue Details

Reported by 1542905:

> Home wifi network and my company has ipv6 connection. When I choose full-tunnel mode and switch wifi network from home to company, vpn does not work to solve dns. So I had to turn off the wifi and turn it back on before the vpn would work again.

The error does not occur when 2 switch wifi networks have no IPv6 connection. And switch wifi network manually.
- **AdGuard version:**
AdGuard Pro v. 2.1.2.173
- **Device model and storage size:**
  - 
- **Operating system and version:**
12.4.1

### Expected Behavior

AdGuard continues resolving all DNS requests

### Actual Behavior

AdGuard DNS only resolves domain names with ipv6

### Steps to reproduce

> 1. Turn on full-tunnel mode
> 2. Turn on “restart when network change” in Advenced settings
> 3. Connect to wifi network with ipv6 enabled
> 4. Move to another WiFi network (with IPv6 enabled), let IOS connect automatically
> 5. VPN not solve dns

### Additional info
Logs are in CRM, user 1542905.

**Comment by SoLenny** [comment]
@Eugene-Savenko Hello, can you please reproduce it on free version of AdGuard?

**Comment by bigdargon** [comment]
@SoLenny I will check the free version with Adguard DNS

**Comment by SoLenny** [comment]
@bigdargon Okay, thank you.
Waiting for it so.

**Comment by bigdargon** [comment]
@SoLenny Adguard Free has the same error as Adguard Pro. I sent the log with ID 1542905.

I noticed that, when switching networks with IPv6 connection in Full-tunnel mode, the application's VPN will default to using IPv6 to resolve without using IPv4 at all. Some websites with IPv6 addresses will still be accessible, while websites with only IPv4 addresses will not.

When manually turning off and on wifi network, VPN will switch back to using IPv4 as default and normal access.

**Comment by ameshkov** [comment]
Assigned to v3.2, than kyou!

**Comment by bigdargon** [comment]
@ameshkov I hope the Pro version will update too!

**Comment by ameshkov** [comment]
Yeah, some time after v3.2 we'll finally synchronize both apps.

**Comment by IvanIin** [comment]
@Eugene-Savenko @bigdargon 
could you check if the bug is reproducing on ios13?

**Comment by bigdargon** [comment]
@IvanIin Tested in the free version and pro on ios 13 have the same error

**Comment by ameshkov** [comment]
@bigdargon could you please check v4.0 beta version?

**Comment by bigdargon** [comment]
@ameshkov I will check it out soon

**Comment by bigdargon** [comment]
@ameshkov Tested. The bug does not affect in version 4.0 beta. You can close it. Thank you!
