### ISSUE TITLE
$elemhide exclusion issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#1253]
### Steps to reproduce:
0. Disable all filters;
1. Go to https://www.tf1.fr/tmc/quotidien-avec-yann-barthes/videos/quotidien-premiere-partie-3-mai-2019.html
2. Add these rules:
```
@@||tf1.fr^$generichide
##body
```
3. Refresh page.

### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** AdGuard for iOS v3.1
- **Device model and storage size:** iPad mini
- **Operating system and version:** 12.4.1
- **Browser or App:** browser

### Expected Behavior

BODY is not hidden(page is blank);

### Actual Behavior

BODY is hidden.
The same with `$generichide`.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardForSafari #285](https://github.com/AdguardTeam/AdGuardForSafari/issues/285) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
Not fixed in current build.

**Comment by IvanIin** [comment]
It seems the error is fixed in the converter 4.2.4 (Adguard v4.0(340))
@Alex-302 could you check it fixed?

**Comment by Alex-302** [comment]
@IvanIin the same...
