### ISSUE TITLE
Web Annoyances Ultralist missing on iPad

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#1257]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS 3.1.233
- **Device model and storage size:**
  - unspecified iPad
- **Operating system and version:**
  - 13.1
- **Browser or App:**
  - N/A

### Expected Behavior

Web Annoyances Ultralist should be available under Annoyances (as it is on iPhones & non-iOS devices)

### Actual Behavior

The filter is absent from the list and must be added manually.

### Screenshots

See helpdesk ID 2234242 for screenshots.

### Additional Information

None provided

**Comment by SoLenny** [comment]
https://github.com/AdguardTeam/AdguardForiOS/issues/1254
