### ISSUE TITLE
AutoBild app is broken

### ISSUE THREAD

**Issue by tiberian83** [AdguardTeam/AdguardForiOS#126]
AutoBild (Germany) app is broken when using Adblock PRO. It's not showing any content.

**Comment by ameshkov** [comment]
@tiberian83 could you please take a look inside of the "requests log" and see which domains are being blocked?

**Comment by tiberian83** [comment]
![image](https://cloud.githubusercontent.com/assets/10312300/17478487/71c3d660-5d6c-11e6-9d63-6ea3b00bfe5b.png)

**Comment by ameshkov** [comment]
Hm, nothing is blocked, weird. Please note that response could be cached, it is recommended to restart the VPN to get the proper log.

**Comment by tiberian83** [comment]
It must have been a problem at AutoBild. Right now I don't even get content without Adblock PRO. I think this can be closed.
