### ISSUE TITLE
Updating filters causes the filter update date to be displayed incorrectly

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#1261]
### Issue Details

- **AdGuard version:**
  - Pro 2.1.2.173
- **Device model and storage size:**
  - unspecified iPhone
- **Operating system and version:**
  - 13.0

### Screenshots
<details><summary>Screenshot:</summary>

![image0](https://user-images.githubusercontent.com/33634917/65392049-f2278100-dd78-11e9-9b8d-c840254a0d47.png)
![image1](https://user-images.githubusercontent.com/33634917/65392050-f2278100-dd78-11e9-8df2-51c582280f18.png)
![image2](https://user-images.githubusercontent.com/33634917/65392051-f2278100-dd78-11e9-8b26-1fa9a6de8de3.png)
![image3](https://user-images.githubusercontent.com/33634917/65392052-f2278100-dd78-11e9-82b2-abdb1eb760b9.png)

</details>

### Additional Information

Helpdesk ID: 1869597

**Comment by ameshkov** [comment]
Will be resolved automatically when Pro is updated to match the regular version
