### ISSUE TITLE
Add "Form: One" for Trial screen JA strings

### ISSUE THREAD

**Issue by vyanovsky** [AdguardTeam/AdguardForiOS#1262]
Add "Form: One" (without the `%1$d`) for the following Japanese strings:
`trial_description_label_days -> days`
`trial_description_label_weeks -> weeks`
`trial_description_label_months -> months`
`trial_description_label_years -> years`

**Comment by IvanIin** [comment]
fixed in 3.1.1.

**Comment by vyanovsky** [comment]
Andrey said that these strings in reality will be only in the singular form (day/week/month/year), so I just changed the text in the crowdin accordingly. Therefore, issue can be closed.
