### ISSUE TITLE
Security activates itself / filter for useful advertisement can't be activated

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardForiOS#1263]
- **AdGuard version:**
  - AdGuard for iOS v3.1(233)
- **Device model and storage size:**
  - iPhone 11 Pro Max
- **Operating system and version:**
  - iOS 13.0

### Expected Behavior

1. Filter section -> Security should stay disabled.
2. Filter for useful advertisement should be able to activate.

### Actual Behavior

1. In the filter section "Security" activates itself, even if there is no filter active.
2. Filter to allow useful advertisement can't be activated. Leads to an error message "filter could not be loaded.

### Screenshots

<details><summary>Screenshot:</summary>

![IMG_6036](https://user-images.githubusercontent.com/25068100/65423902-7d9d2280-de0a-11e9-975f-d6cfccafcc63.png)

![IMG_6037](https://user-images.githubusercontent.com/25068100/65424015-c7860880-de0a-11e9-9f56-3abbe7de6fa4.png)

</details>

**Comment by SoLenny** [comment]
@sergerosenthaler Hello, can you, please, write steps to reproduce?
I don't fully understand what's happening.
(I tried to reproduce it, but nothing succeeded)

**Comment by sergerosenthaler** [comment]
This are two different bugs.
1. Toggle "Security" off restart the app, "Security" is on again.
2. Active "Others" and the filter to allow useful advertisement. Try to update the the filters list leads to an error message "filter list could not be loaded". Disable the useful advertisement filter, error message disappears.

**Comment by SoLenny** [comment]
@sergerosenthaler
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

Reproduce the issue (and remember the exact time when it happened).
Open the app, tap "Send Feedback", select "Contact Support"
The mail app will be opened, change the recipient to apple@adguard.com (!)
Mention this issue number in the email text.
Abd indicate the time when the error occurred.

Second bug will be fixed in this task https://github.com/AdguardTeam/AdguardForiOS/issues/958

**Comment by 08kovalchuk03** [comment]
@sergerosenthaler the first one can happen if you immediately close the application after changing group's state, it just has no time to enroll to dataBase

**Comment by zzebrum** [comment]
@sergerosenthaler this indeed happens when the app is closed while it's still not finished doing something in the background. 
Try to enable/disable any filter or filter group and wait a minute, then restart the app, then check.

**Comment by sergerosenthaler** [comment]
@zzebrum
Problem 1:  I disabled the category Security and kept the application in the foreground for about 2 minutes. Afterwards I moved to other apps, but have not closed AdGuard. After a day the Security category was active again. -> definitely a bug.

Problem 2: Active "Others" and the filter to allow useful advertisement. Try to update the the filters list leads to an error message "filter list could not be loaded". Disable the useful advertisement filter, error message disappears. -> this filter cannot be activated anymore without problems. Tested on 6 different iOS devices.

**Comment by sergerosenthaler** [comment]
@zzebrum Send, unfortunately the second one I have sent to support@adguard.com instead of apple@adguard.com, sorry.

**Comment by zzebrum** [comment]
@sergerosenthaler got your logs, thanks

**Comment by zecanard** [comment]
I’m still seeing issue #1 in AdGuard for iOS, both with the Security and Custom groups. The toggle seems to stick to the _Off_ position for a while, but next time I open the app after a couple of days, both categories are re-enabled. I’ll send logs when I see it happen again.
