### ISSUE TITLE
Cannot upload filters into Safari 

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1264]
**Issue Details**

**AdGuard version**
Beta AdGuard for iOS v3.1 (233)

**Device model and storage size**
iPhone 11 Pro Max 256Go

**Operating system and version**
iOS 13

**Browser or App**
iOS Adguard

Expected Behavior
Upload filters into Safari. 

Actual Behavior
Pop up error window 
"Filters cannot be upload into Safari"

Screenshots
!["Filters cannot be upload into Safari" ](https://user-images.githubusercontent.com/49731083/65427841-86462680-de13-11e9-9e87-c802a69502ba.png)

Additional Information
Same configuration on iPhone and iPad. Only face the issue on the iPhone.

**Comment by SoLenny** [comment]
@Quorum75 Hello.
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

Reproduce the issue (and remember the exact time when it happened).
Open the app, tap "Send Feedback", select "Contact Support"
The mail app will be opened, change the recipient to apple@adguard.com (!)
Mention this issue number in the email text.
Abd  indicate the time when the error occurred.

**Comment by Quorum75** [comment]
@SoLenny. Done. Thanks.

**Comment by 08kovalchuk03** [comment]
@Quorum75 this will be fixed in https://github.com/AdguardTeam/AdguardForiOS/issues/1269

**Comment by Quorum75** [comment]
@08kovalchuk03

Thanks. I guess my problem isn't due to a slow device as I am using iPhone 11 Pro Max 🙃
