### ISSUE TITLE
Cannot send email tu AG support

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1265]
**Issue Details**

**AdGuard version**
Beta AdGuard for iOS v3.1 (233)

**Device model and storage size**
iPhone 11 Pro Max 256Go

**Operating system and version**
iOS 13

**Browser or App**
iOS Adguard

**Expected Behavior**
Being able to contact support.  

**Actual Behavior**
Pop up error window 
"Cannot setup an email"

**Screenshots**
![408DA6FE-1236-4751-986D-759760465490](https://user-images.githubusercontent.com/49731083/65427936-b4c40180-de13-11e9-99b8-ff9ef1c4598d.png)

**Additional Information**
Same configuration on iPhone and iPad. Only face the issue on the iPhone.

**Comment by SoLenny** [comment]
@Quorum75 Hello, you can open settings -> send feedback -> export logs.
Then send it to apple@adguard.com
Don't forget to indicate the time when the error occurred.

**Comment by Quorum75** [comment]
Done.

**Comment by Quorum75** [comment]
@SoLenny You close the thread but what is the solution to the issue??
