### ISSUE TITLE
Filters missing in iOS iPhone 

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1266]
**Issue Details**

**AdGuard version**
Beta AdGuard for iOS v3.1 (233)

**Device model and storage size**
iPhone 11 Pro Max 256Go

**Operating system and version**
iOS 13

**Browser or App**
iOS iPhone Adguard

**Expected Behavior**
Find "Web Annoyance Ultralist" filter 

**Actual Behavior**
The filter does not exist

**Screenshots**

iPhone filters  
![8283B0AA-89D4-45F6-AFEA-76115EF96E9F](https://user-images.githubusercontent.com/49731083/65431669-243cef80-de1a-11e9-83be-a3210d889a0b.png)

iPad filters 
![051D27F0-2BB1-4807-9285-F61FC7532726](https://user-images.githubusercontent.com/49731083/65431731-39b21980-de1a-11e9-9ed4-5e4366a5b87e.jpeg)

**Additional Information**
Same configuration on iPhone and iPad. Only face the issue on the iPhone.

**Comment by SoLenny** [comment]
@Quorum75 Please install the latest version from AppStore.
And try to reproduce it again.

**Comment by Quorum75** [comment]
@SoLenny 
As you may have noticed it is a bug report for the beta versions I am testing on both devices, iPad and iPhone. 
Installing the official release, means not testing the beta one. So why will I do that?

**Comment by SoLenny** [comment]
https://github.com/AdguardTeam/AdguardForiOS/issues/958

**Comment by Quorum75** [comment]
@SoLenny 
Sorry but I do not see the link with the issue #958. 
I was just pointing out an inconsistency but both iOS applications. 
Filters list should be the same.

**Comment by ameshkov** [comment]
@Quorum75 the list of available filters is loaded from the server, and it seems it fails to sync properly on one of the devices

**Comment by Quorum75** [comment]
@ameshkov
Andrea just FYI the issue is still présent even with latest release. 
Should I understand it is normal?
