### ISSUE TITLE
DNS Requests Log: Long Domains not fully visible

### ISSUE THREAD

**Issue by kevingrahl** [AdguardTeam/AdguardForiOS#1271]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v3.1(233)
- **Device model and storage size:**
  - iPhone 6s 16Gb
- **Operating system and version:**
  - iOS 13.1 (17A5844a)

### Expected Behavior

I was expecting to be able to see all domains in the DNS Requests Log

### Actual Behavior

Domains that are too long are being cut off, not possible to scroll or copy it. Adguard will only display the first 31 characters and completely cut off the rest of it.

### Screenshots

<details><summary>Screenshot:</summary>

Highlighted in Yellow.
![dns-log-crunch](https://user-images.githubusercontent.com/50027134/65525359-aea35300-deef-11e9-9c28-c702220f0c25.png)

</details>

### Additional Information

Proposed Solution: Like the "Responses" row, the "Domain" row should have two lines to allow for more horizontal space and it should be possible to copy the Domain. This would allow one to see even very long URL's by pasting them elsewhere.

**Comment by 08kovalchuk03** [comment]
already fixed in 4.0
