### ISSUE TITLE
change settings menu

### ISSUE THREAD

**Issue by IvanIin** [AdguardTeam/AdguardForiOS#1272]
- change settings screen
- make advanced settings screen
- make tunnel mode screen
https://share.goabstract.com/918abaaa-0c02-4c50-842e-332c6ca7be94?sha=d4cd05e1c021c66dba1a32792e4dbdb9572aab5e

**Comment by 08kovalchuk03** [comment]
<img width="357" alt="Снимок экрана 2019-10-01 в 14 48 12" src="https://user-images.githubusercontent.com/52201516/65959410-95078b80-e45a-11e9-98eb-5bf33e708ac1.png">
<img width="405" alt="Снимок экрана 2019-10-01 в 14 45 49" src="https://user-images.githubusercontent.com/52201516/65959414-9769e580-e45a-11e9-8435-a65bcfaf5b98.png">
