### ISSUE TITLE
New system protection navigation

### ISSUE THREAD

**Issue by IvanIin** [AdguardTeam/AdguardForiOS#1273]
Сreate system protection screen
Сreate dns request blocking screen(without dns filters)

**Comment by SoLenny** [comment]
https://app.goabstract.com/projects/2b264260-c732-11e8-a52a-07ba12563bc0/branches/18decfcc-baad-42bb-8689-d581c84577ef/commits/79424c6bd6972512ae8292911a3c2c38df339c43/files/0B986117-1199-42D4-99B7-06AE1C613873/layers/87C11363-B15E-4A6A-B53C-F559A326B546?mode=design

**Comment by 08kovalchuk03** [comment]
<img width="799" alt="Снимок экрана 2019-09-30 в 13 33 53" src="https://user-images.githubusercontent.com/52201516/65871404-feb66580-e386-11e9-9e35-83084abb1e8a.png">
<img width="346" alt="Снимок экрана 2019-09-30 в 13 34 28" src="https://user-images.githubusercontent.com/52201516/65871426-083fcd80-e387-11e9-8df3-efb35d0ce0d8.png">
