### ISSUE TITLE
Change dns request log

### ISSUE THREAD

**Issue by IvanIin** [AdguardTeam/AdguardForiOS#1275]
make dns request log corresponding to the new design

**Comment by 08kovalchuk03** [comment]
<img width="802" alt="Снимок экрана 2019-10-07 в 10 43 10" src="https://user-images.githubusercontent.com/52201516/66293426-47be6a80-e8ef-11e9-8454-f212126016f1.png">
<img width="792" alt="Снимок экрана 2019-10-07 в 10 43 00" src="https://user-images.githubusercontent.com/52201516/66293427-47be6a80-e8ef-11e9-84a3-d5124dca3ef4.png">
