### ISSUE TITLE
Adblock polskie reguły causes the issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#128]
I did a full system restore. Before the restoring Adguard worked fine but
afterwords it is just madness and it does not work at all.

I have removed the app, reset the iPhone, install the app again, removed
all filters, add filters one by one and still it does not work. App is
enabled in the safari settings. (It was on and off but without any result)

Screenshots in attachment
<details>
![screen shot 2016-08-09 at 11 11 34 am](https://cloud.githubusercontent.com/assets/15856304/17509352/300a16ba-5e22-11e6-9af8-4e6b02e54d91.png)
![screen shot 2016-08-09 at 11 11 44 am](https://cloud.githubusercontent.com/assets/15856304/17509353/300c3f30-5e22-11e6-90e9-c07fbc1a7df4.png)
</details>
It is "Adblock polskie reguły" whenever I try to enable them there's issue
mentioned previously.

**Comment by Stillness-2** [comment]
@evgeniy-ADG We need more info, like ticket number, if it exists.

**Comment by ameshkov** [comment]
@Stillness-2 nope, we need nothing, i've already found the cause

**Comment by ameshkov** [comment]
It appears that the issue we have is caused by this rule from "Adblock polskie reguły":
```
@@/:\/\/.*[.]wp[.]pl\/[a-z0-9_]{30,50}[.][a-z]{2,5}\b/
```

Due to Safari limited regular expressions it fails to compile the ad blocker:
https://webkit.org/blog/3476/content-blockers-first-look/

> The format is a strict subset of JavaScript regular expressions. Syntactically, everything supported by JavaScript is reserved but only a subset will be accepted by the parser. An unsupported expression results in a parse error.

> The following features are supported:

> Matching any character with “.”.
> Matching ranges with the range syntax [a-b].
> Quantifying expressions with “?”, “+” and “*”.
> Groups with parenthesis.

> It is possible to use the beginning of line (“^”) and end of line (“$”) marker but they are restricted to be the first and last character of the expression. For example, a pattern like “^bar$” is perfectly valid, while “(foo)?^bar$” causes a syntax error.


In this particular case the problem is the `\b` symbol. Temporary solution, use the following rule instead:
```
@@/:\/\/.*[.]wp[.]pl\/[a-z0-9_]{30,50}[.][a-z]{2,5}[/:&?]?/
```
