### ISSUE TITLE
[Adguard Pro] Error displaying update time iOS 13.1

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdguardForiOS#1283]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  Adguard Pro v2.1.2
- **Device model and storage size:**
  -  iPhone 8 Plus
- **Operating system and version:**
  -  13.1

### Screenshots

<details><summary>Screenshot:</summary>

![294DB236-C51F-4A22-BAF1-6352F1A792D6](https://user-images.githubusercontent.com/10969626/65689085-725e2700-e096-11e9-9ea8-490591634009.jpeg)
![D19A433C-23D1-445C-9BFE-729302AA7EE9](https://user-images.githubusercontent.com/10969626/65689086-72f6bd80-e096-11e9-9d21-d2e9f847f02e.jpeg)

</details>

### Additional Information

Adguard Pro does not display the time and date when it was last updated

**Comment by ameshkov** [comment]
This will be resolved automatically when the Pro version is updated to match the regular one
