### ISSUE TITLE
AdGuard Pro: VPN is broken when accessing ipleak.net 

### ISSUE THREAD

**Issue by sophisticated-zero** [AdguardTeam/AdguardForiOS#1285]
Environment:
- AdGuard Pro version: 2.1.2.173
- iPhone OS: 12.4.1
- Safari

Case number: 1542905

When the user visited ipleak.net website, the application's VPN was broken and repeated during DNS checking.

According to client's comments: 
"- I have deleted all subscriptions in privacy settings.
- Turn on "Restart when network changes".
- Test in both tunnel modes: Split-Tunnel ), Full-tunnel 
- The site will sometimes get the same error: app.ignition.fun
- Have tested Adguard Free – not similar"

**Comment by bigdargon** [comment]
Thanks for this issue!

**Comment by bigdargon** [comment]
### Steps to reproduce

1. Turn on Full-tunnel mode (Split-tunnel mode is the same error)
2. Turn on “Restart when network change” in Advenced settings
3. Delete all subscriptions in Privacy settings
4. Use Safari to visit ipleak.net
5. VPN broken at "DNS Address detection"

**Comment by ameshkov** [comment]
We should re-test it when we start using the new DNS library in AG

**Comment by ameshkov** [comment]
Cannot repro on v4.0 beta
