### ISSUE TITLE
Background crashes

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#1286]
### Issue Details

- **AdGuard version:**
  - AdGuard Pro 2.1.2.173
- **Device model and storage size:**
  - unspecified iPhone
- **Operating system and version:**
  - iOS 13.0
- **Browser or App:**
  - N/A

### Expected Behavior

AdGuard shouldn't have issue working in background.

### Actual Behavior

AdGuard seems to crash every once in a while.

### Additional Information

See helpdesk ID 2049187 for logs.

**Comment by TheHasagi** [comment]
Logs in ncloud.

**Comment by akmLaVx** [comment]
Additional logs: 2324343

**Comment by ameshkov** [comment]
Not relevant to the current app version, it will go away when the Pro version is updated
