### ISSUE TITLE
Beta 3.1.1 - Too Many Separator lines in filter Menu

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#1290]
The filter list menu is messy due to many white lines / separator lines.

Please remove the extras.

Tested version: 3.1.1 Beta

Pics
![D349EDBD-739A-4403-B3C9-E84A6750DED9](https://user-images.githubusercontent.com/27464836/65866697-997b6800-e3b8-11e9-9022-24e5d9d0789d.jpeg)

**Comment by ameshkov** [comment]
Good catch!
