### ISSUE TITLE
High battery consumption on iOS 13

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#1293]
### Issue Details

- **AdGuard version:**
  - Pro 2.1.2.173
- **Device model and storage size:**
  - unspecified iPhone
- **Operating system and version:**
  - 13.1.1

### Actual Behavior

The app started consuming too much battery charge after updating to iOS 13.

### Additional Information

Customer logs available in helpdesk ticket 1546147

**Comment by tom0034** [comment]
Same, AdGuard pro 2.1.2(137) on iPhone 11 pro ranked on the first place of battery consumption. 
It also makes the phone become very very hot.
Disabling AdGuard resolves the battery and hot problem.
Tested on 13.1/13.1.1/12.1.2

**Comment by ameshkov** [comment]
@SoLenny is it reproducible?

**Comment by Eugene-Savenko** [comment]
Another report w/ logs here: 1129246

**Comment by ameshkov** [comment]
Is there anyone able to reproduce this?

**Comment by SoLenny** [comment]
@tom0034 Hello, can you clarify how much approximately the application uses the battery?

**Comment by SoLenny** [comment]
@tom0034 @akmLaVx @ameshkov I tested it for ~6 hours and AdGuard Pro consuming 3%.
Our developers say that this is within normal limits.

**Comment by maxbat10** [comment]
The same for me...

**Comment by SoLenny** [comment]
@maxbat10 Hello, we need some more information.
 Can you clarify how much approximately the application uses the battery?

**Comment by maxbat10** [comment]
Hello,

9% for the last 24 hours.

**Comment by ruffes107** [comment]
![IMG_0695](https://user-images.githubusercontent.com/56410563/66598582-9e52cf80-eba1-11e9-8f82-ed6df1a3315e.jpeg)

Here is a Screenshot of the battery usage by Adguard Pro.
iPhone X IOS 13.1.2 

The Usage was 5 hours today in the Background and yesterday was 8 hours.

**Comment by ameshkov** [comment]
Background usage time is not a problem, the app runs all the time in the background when DNS filtering is enabled so obviously it will be high.

What matters is the CPU usage, and we don't observe any issues on our side. This might've been a consequence of the OS update, maybe the tunnel properties were corrupted. So if you see an unusually high "activity" values, first of all, try reinstalling AG and check if it changes anything.
