### ISSUE TITLE
Problem in displaying the update date

### ISSUE THREAD

**Issue by Skavarotti** [AdguardTeam/AdguardForiOS#1294]
After updating AdGuard PRO ver. 2.1.2 (173) on iPhone Xr (iOS 13.1.2), the filter update date is displayed incorrectly.Please fix it.
![IMG_2607](https://user-images.githubusercontent.com/41288157/65978052-ae6cff80-e47b-11e9-9d0f-0d7912c57dec.PNG)

**Comment by SoLenny** [comment]
@Skavarotti Hello, in the near future the pro version will be completely redesigned.
When the update will available, most likely your problem will be solved, and even if not, we will definitely return to it.
