### ISSUE TITLE
Mobile data connection doesn’t work when the privacy/DNS option is turned on

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#1295]
I’ve been using AdGuard Pro for a while but recently my mobile data connection doesn’t seem to work when the privacy/DNS option is turned on. When I run a mobile data speed test everything looks good but when I do something simple like a Safari search or type in an address in Apple Maps it’s like there’s not data connection even though there’s a strong signal. Everything works fine when I’m in WiFi but as soon as I leave and switch back to mobile data I have to disable the privacy/DNS setting in the app. 

### Issue Details

- **AdGuard version:**
  -  AdGuard Pro 2.1.2.173
- **Carrier**
  -  T-Mobile
- **Device model and storage size:**
  - iPhone XS
- **Operating system and version:**
  - 12.4.1
- **Browser or App:**
  - n/a

### Expected Behavior

AdGuard works on both mobile data and Wi-Fi

### Actual Behavior

Seems like there's no connection though the signal is strong and the Speed Test shows normal results

### Additional Information

Logs: 2330904

**Comment by SoLenny** [comment]
@Eugene-Savenko Hello, in the near future the pro version will be completely redesigned.
When the update will available, most likely your problem will be solved, and even if not, we will definitely return to it.

**Comment by Eugene-Savenko** [comment]
@SoLenny Should we then stop reporting all bugs for AdGuard Pro?..

**Comment by SoLenny** [comment]
@Eugene-Savenko Yes. Since the pro version will be completely changed, the bugs that are launched at the moment will not be relevant.

**Comment by gmogoody** [comment]
Is there an estimate on a beta or final release of this redesign. I’m on 2.1.2(173) for iOS and been using AdGuard for years but just switched to T-Mobile and now can’t use AdGuard. Really anticipating this potential fix

**Comment by SoLenny** [comment]
@gmogoody Would you like to try the beta version of our second program AdGuard - adblock&privacy? Everything should work well there :)
