### ISSUE TITLE
$urlblock exclusion issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#1297]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

$urlblock/genericblock exclusion does nothing. 

### Steps: 
1. Add `@@||popsci.com^$urlblock`
1. Open popsci.com
2. Check for blocked requests in Safari for MacOS

- **AdGuard version:** AdGuard for iOS v3.1.1) -->
- **Device model and storage size:** iPad
- **Operating system and version:**10.3.1) -->
- **Browser or App:** Safari

### Expected Behavior

Requests are not blocked.

### Actual Behavior

Requests are blocked.

**Comment by Mizzick** [comment]
@Alex-302 please provide a clear example

**Comment by ameshkov** [comment]
`@@||popsci.com^$generichide` is applied on that website, I see no urlblock/genericblock

**Comment by Alex-302** [comment]
Damn, my mistake. It works.
