### ISSUE TITLE
Le VPN s’active et se désactive de manière intempestive 

### ISSUE THREAD

**Issue by gui771** [AdguardTeam/AdguardForiOS#1299]
Bonjour, depuis iOS 13, le VPN fait que de se relancer, s’éteindre et s’allumer.

**Comment by SoLenny** [comment]
@gui771 Hello.

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

Reproduce the issue (and remember the exact time when it happened).
Open the app, tap "Send Feedback", select "Contact Support"
The mail app will be opened, change the recipient to apple@adguard.com (!)
Mention this issue number in the email text.

And please write an approximate period of time when this happens.

**Comment by SoLenny** [comment]
@gui771 Hello, unfortunately, we have not received a response from you. If suddenly the problem again bothers you, feel free to reopen the task again.
