### ISSUE TITLE
Make design changes

### ISSUE THREAD

**Issue by SoLenny** [AdguardTeam/AdguardForiOS#1300]
https://app.goabstract.com/projects/2b264260-c732-11e8-a52a-07ba12563bc0/branches/18decfcc-baad-42bb-8689-d581c84577ef/commits/cc02f76d7d49f29ee70e6efc7bb46ca84565bd71/files/0B986117-1199-42D4-99B7-06AE1C613873/layers/65369CD8-EE21-4D01-BCF2-62E68F13B5F8?mode=design

**Comment by 08kovalchuk03** [comment]
https://app.goabstract.com/projects/2b264260-c732-11e8-a52a-07ba12563bc0/branches/18decfcc-baad-42bb-8689-d581c84577ef/commits/758fb5e1ac3e7a22b93032079e870e3b3e51c98b/files/0B986117-1199-42D4-99B7-06AE1C613873/layers/F144346C-CF89-4970-988F-F7008EC53CBC?mode=design

**Comment by 08kovalchuk03** [comment]
https://app.goabstract.com/projects/2b264260-c732-11e8-a52a-07ba12563bc0/branches/18decfcc-baad-42bb-8689-d581c84577ef/commits/758fb5e1ac3e7a22b93032079e870e3b3e51c98b/files/0B986117-1199-42D4-99B7-06AE1C613873/layers/87C11363-B15E-4A6A-B53C-F559A326B546?mode=design
