### ISSUE TITLE
Несколько пожеланий.

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardForiOS#1302]
Есть несколько пожеланий по приложению для iOS:
1) Убрать из названия раздела AdGuard DNS в настройках слово "Family". Зачем оно там вообще надо, если это стандартный сервер DNS AdGuard (без семейной защиты)? Только путает...
![536635F6-C285-41EA-A24D-83BBBC1BD140](https://user-images.githubusercontent.com/34383288/66442211-2a49e780-ea3a-11e9-8e94-e0d22534cbde.jpeg)
2) Сделать кнопки перехода "назад" и настроек программы чуть виднее, хотя бы такими же как стрелки перехода в разделах настроек. 
![5AC3FA7A-7E35-481B-A404-89231EF1E2F4](https://user-images.githubusercontent.com/34383288/66442315-8d3b7e80-ea3a-11e9-95f6-8f3d082eb797.jpeg)
![867E7A61-A9CE-4D2D-88CF-DEFB337266BD](https://user-images.githubusercontent.com/34383288/66442316-8d3b7e80-ea3a-11e9-96a9-b7c5db4260c1.jpeg)
3) Считаю что хотя бы из платной версии стоит убрать с главной страницы баннер "поделится". Оставить только эмблему программы, статус защиты, фильтров и кнопку настроек разумеется.

**Comment by Vitalik93** [comment]
И ещё немного :)
4) Сделать иконку значка AdGuard в Safari побольше.
![FD490673-A954-4344-B26E-71FD8BAC0BCC](https://user-images.githubusercontent.com/34383288/66444354-32f2eb80-ea43-11e9-941c-405ba9df853e.jpeg)
5) Центрировать нижние кнопки в Белом списке и Пользовательском фильтре.
![6FEDF0F0-F6AC-436E-AD50-35679EFB1993](https://user-images.githubusercontent.com/34383288/66444427-89602a00-ea43-11e9-9bfb-47da81c332a6.jpeg)
6) В настройках DNS кнопку "Добавить свой DNS сервер" переместить в правый верхний угол в виде плюсика.
![5CBBBC85-85E3-4CC8-BE0D-E617B7AA2AE0](https://user-images.githubusercontent.com/34383288/66444556-ebb92a80-ea43-11e9-96af-9011bb360013.jpeg)
7) Вместо тегов фильтров поставить количество их правил (перенести их из раздела "Общие - Блокировщики контента"). Думаю там их находится логичнее...
![67C64A23-A697-41DD-ADBB-5BFD1D8BC8B3](https://user-images.githubusercontent.com/34383288/66444680-73069e00-ea44-11e9-99ce-f920424de882.jpeg)

**Comment by Vitalik93** [comment]
Что интересно, первые 2 пункта актуальны только если включена темная тема. Со светлой темой слова "Family" в стандартном DNS нет, кнопки настроек и перехода назад тоже в одном тоне со стрелочками разделов настроек. И опять же на темной теме очень плохо видны заблокированные DNS запросы (пример на фото)
![8171F4D9-FE6C-42C3-9785-1746A74E43AE](https://user-images.githubusercontent.com/34383288/66529019-12d63180-eb02-11e9-8589-ed76e5ce15f8.png)

**Comment by Vitalik93** [comment]
> Что интересно, первые 2 пункта актуальны только если включена темная тема. Со светлой темой слова "Family" в стандартном DNS нет, кнопки настроек и перехода назад тоже в одном тоне со стрелочками разделов настроек. И опять же на темной теме очень плохо видны заблокированные DNS запросы (пример на фото - нижние 4 запроса блокированы)
> ![8171F4D9-FE6C-42C3-9785-1746A74E43AE](https://user-images.githubusercontent.com/34383288/66529019-12d63180-eb02-11e9-8589-ed76e5ce15f8.png)

**Comment by Vitalik93** [comment]
Можно ещё в разделах Белый список и Пользовательский фильтр сделать шрифт описаний одинакового размера. В Белом списке он крупнее, можно такой же использовать в Пользовательском фильтре.
![3AC3D449-C830-462C-A155-10E560160272](https://user-images.githubusercontent.com/34383288/66610129-06fa7600-ebbb-11e9-80b9-25a2b774023b.jpeg)
![DBA6406A-E237-477D-BD14-4DC3B68072DA](https://user-images.githubusercontent.com/34383288/66610130-06fa7600-ebbb-11e9-92d8-6bd696bcbccf.jpeg)
И свои DNS-серверы логично было бы видеть вначале списка серверов а не в конце.
![C958D6E6-2976-4CA4-B949-C49F5C6ECEA3](https://user-images.githubusercontent.com/34383288/66610216-3e692280-ebbb-11e9-9ece-4c870f1999dc.jpeg)

**Comment by zzebrum** [comment]
Перенесла актуальные предложения в новую задачу #1501
