### ISSUE TITLE
Пожелание для AdGuardPro for iOS

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdguardForiOS#1303]
Есть ли возможность добавить в AdGuardPro for iOS возможность отключения сервиса при подключении к определенным сетям, например WiFi, как в DNSCloak или 1.1.1.1?

**Comment by SoLenny** [comment]
@YBS-PC Hello, in the near future the pro version will be completely redesigned.
When the update will available, most likely your feature will be added, and even if not, we will definitely return to it.
