### ISSUE TITLE
Unable to report a problem via app when using non-stock email apps

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#1304]
### Reproduction
1. Install any third-party email client (like Gmail) and make it default email client for your device
2. Try to contact support via the app
3. App won't be able to detect non-standard email clients

### Issue Details

- **AdGuard version:**
  - AdGuard 3.1
- **Device model and storage size:**
  - Unspecified iPhone
- **Operating system and version:**
  - Unspecified, probably iOS 13

### Expected Behavior

AdGuard should be able to detect third-party email clients

### Actual Behavior

You are unable to send support requests when using a third-party email client

### Screenshots

<details><summary>Screenshot:</summary>

![Image-2](https://user-images.githubusercontent.com/33634917/66509867-86654800-eadc-11e9-8e54-2a2ea57f0dbe.png)

</details>

### Additional Information

Helpdesk ID: 2338383

**Comment by IvanIin** [comment]
We cannot send files through mailto:. You can use the export logs function.

**Comment by ameshkov** [comment]
Then we'll need to use our mobile backend API instead.
