### ISSUE TITLE
Adguard Pro VPN Symbol not hiding 

### ISSUE THREAD

**Issue by ruffes107** [AdguardTeam/AdguardForiOS#1305]
iPhone X IOS 13.1.2 
Adguard Pro 2.1.2

The VPN Symbol doesn't hide even when its disabled in the settings.
Full-Tunnel whitout VPN symbol.

**Comment by SoLenny** [comment]
@ruffes107 Hello, in the near future the pro version will be completely redesigned.
When the update will available, most likely your problem will be solved, and even if not, we will definitely return to it.
