### ISSUE TITLE
Bring back "Log in" button to About screen

### ISSUE THREAD

**Issue by vyanovsky** [AdguardTeam/AdguardForiOS#1306]
Place "Log in" button (leads to AdGuard account log in screen) in top-right corner of About screen (Main screen -> Settings -> About).

(!) Please make sure to send crowdin string for translation before the release.

**Comment by Vitalik93** [comment]
Только что установил версию 3.1.2 (247) и не нашёл кнопку входа в аккаунт в разделе "о программе".
