### ISSUE TITLE
AdGuard Pro App needs DNS over HTTS support.

### ISSUE THREAD

**Issue by holderad** [AdguardTeam/AdguardForiOS#1307]
It appears the developer behind DNSCloak has abandoned the project.

I know you are moving everyone to the AdGuard 3.0 iOS App subscription model.

But, some of us who are willing to do a little more work would rather use AdGuard Home (or something like it - DOH-rust, etc) with a stable App that provides system wide DNS over HTTPS support for iOS.

I appreciate what you are doing with all the adblocking rules, but I prefer to simply use a DNS over HTTPS that I can control. Maybe Adguard Pro can simply become a companion App to Adguard Home? I don’t want the Premium 3.0. I support more that 40 devices. There is no way I am going to be paying for subscriptions for all of those devices as a small business owner.

I don’t want to move to NEXTDNS, but I will have too if I can not get a stable iOS client to use with DNS over HTTPS.

Thanks for considering.

**Comment by bigdargon** [comment]
@holderad Adguard Pro will be updated in the future https://github.com/AdguardTeam/AdguardForiOS/issues/1247#issuecomment-533814514

**Comment by lancelot-moon** [comment]
AG for iOS and AG Pro for iOS will be almost the same in v3.x if Apple approves their updates.
AG Pro for iOS v3 = AG for iOS v3 + Premium features.
(Just you may not need to do in-app purchasing in the future AG Pro for iOS v3 for Premium features.)
