### ISSUE TITLE
Adguard Pro won't work on iOS 10 Beta 5 because of a VPN issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#131]
Поломался VPN в iOS 10 beta 5. Постоянно подключается-отключается. Соответственно, соединения вообще нет.

**1382035**

**Comment by vgavrish** [comment]
Ответ пользователя на " Я так понимаю, что VPN сломался не сразу. Вы выполнили обновление на новую бету? Или просто в какой то момент перестало адекватно работать?"
" Обновился и сломался сразу"

**Comment by vgavrish** [comment]
Ответ: На мобильном интернете все ок а на wifi начинает скакать

**Comment by ameshkov** [comment]
@Stillness-2 do we have enough logging to troubleshoot such cases?

**Comment by evgeniy-ADG** [comment]
Logs: 1382035

**Comment by gshumihin** [comment]
У меня все по-прежнему работает нормально, уже на 6 бете.

**Comment by Bohdan-SUP** [comment]
Проблема все еще на месте - "Попробовал на другой сети - все то же самое".

**Comment by ameshkov** [comment]
@Stillness-2 а это не та же самая проблема что вот тут?
https://github.com/AdguardTeam/AdguardForiOS/issues/145

**Comment by Bohdan-SUP** [comment]
"Теперь все работает! Спасибо"
