### ISSUE TITLE
Wrong AdGuard DNS Logos

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForiOS#1311]
### Issue Details
The AdGuard DNS and AdGuard DNS Family logos are swapped incorrectly.

- **AdGuard version:**
  - AdGuard for iOS 3.1.1 (239)

### Expected Behavior
AdGuard DNS shows the AdGuard DNS logo.
AdGuard DNS Family shows the AdGuard DNS Family logo.

### Actual Behavior
AdGuard DNS shows the AdGuard DNS Family logo.
AdGuard DNS Family shows the AdGuard DNS logo.

### Screenshots

<details><summary>Screenshot:</summary>

![IMG_0186](https://user-images.githubusercontent.com/46271764/66896311-4bb16180-f040-11e9-910b-99542f362bdf.jpg)

![IMG_0187](https://user-images.githubusercontent.com/46271764/66896312-4ce28e80-f040-11e9-8f4e-433140ef29aa.jpg)
</details>

**Comment by SoLenny** [comment]
Note: this happens in a dark theme.

**Comment by Vitalik93** [comment]
#1302, пункт 1.

**Comment by planet0** [comment]
@Vitalik93 Oh yes, you already reported this issue. I tried searching for it but it didn't appear for a different language. Thank you. 👍

**Comment by planet0** [comment]
Issue resolved in 4.0.0(373)
