### ISSUE TITLE
Add Notifications Control

### ISSUE THREAD

**Issue by dsolomakin** [AdguardTeam/AdguardForiOS#1312]
In Settings -> General -> Other

Add :

Headline: Allow Notifications
Description: AdGuard sends security alerts and notifies you when filter updates are installed (On/Off)

![File.jpg](https://images.zenhubusercontent.com/5da43b918b2e250001841f9e/1b2a2db4-dcd9-43f3-8775-0487ea1b4a86)

**Comment by Vitalik93** [comment]
А фильтры у AdGuard для IOS на автомате разве обновляются? Ни разу не видел...

**Comment by artemiv4nov** [comment]
The task is too old, closed.
