### ISSUE TITLE
Grammar issues German

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1317]
In Settings under „Feedback senden“  the Description says „Helfen Sie uns AdGuard besser machen“
It should be „Helfen Sie uns AdGuard besser zu machen“ or even better „Helfen Sie uns AdGuard zu verbessern“ 
In „über“ -> „Lizenz“ it says „Sie sind abonniert“ which is totally wrong. Should be „Sie haben ein Abonnement“. And maybe use the word „besitzen“ instead of „haben“ same for the description „Sie haben eine Lizenz“
In „Einstellungen“ -> Allgemeine, it should be „Allgemein“ and then the description should be „Sie haben 6 Inhaltsblocker, von denen jeder“ and not „jeder von denen“.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aalpatkina** [comment]
corrected in Crowdin
