### ISSUE TITLE
Пожелания по фильтрам.

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardForiOS#1318]
После установки последней версии приложения для iOS заметил что Фильтр для Safari по умолчанию выключен. Может стоит сделать его по умолчанию включённым сразу после установки? Также не нашёл многих фильтров в списках фильтров. Например в разделе Безопасность нет Malware Domains. Хорошо бы вообще продублировать фильтры из приложения для Windows например, чтобы те что есть там были доступны и в IOS.

**Comment by Eugene-Savenko** [comment]
Фильтр Safari же помечен как obsolete, в нем больше нет необходимости, потому и отключен.

**Comment by Vitalik93** [comment]
> 
> 
> Фильтр Safari же помечен как obsolete, в нем больше нет необходимости, потому и отключен.

То есть даже с выключенным ним фильтрация в Safari будет? В чем тогда разница между тем, когда этот фильтр включен и выключен?

**Comment by Eugene-Savenko** [comment]
Да, будет. Все фильтры, которые Вы там видите, они все работают только в Safari и нигде больше. Если я не ошибаюсь, этот фильтр содержал оптимизированные правила для Safari, но необходимость в нем отпала, так как лимит в 50.000 правил более не является проблемой. A Malware Domains удалили, вот почему: https://github.com/AdguardTeam/AdguardForiOS/issues/1112

**Comment by Vitalik93** [comment]
Ясно. Тогда думаю тему можно закрывать...
