### ISSUE TITLE
DNS over https doesn't work 

### ISSUE THREAD

**Issue by itsnotv** [AdguardTeam/AdguardForiOS#1320]
### Issue Details

When DNS privacy is enabled with dns over https, ads are not blocked in other applications.

- **AdGuard version:**
  - AdGuard for iOS v3.1.1(239)
- **Device model and storage size:**
  - iPhone 8
- **Operating system and version:**
  - iOS 13.1.3
- **Browser or App:**
  - Google News

### Expected Behavior

Ads should be blocked in applications like google news.

### Actual Behavior

Ads are not blocked outside of safari.

### Additional Information

I am running latest Adguard Home (v0.99.0) as the DNS server with doh as https://my-server/dns-query. When I use DNSCloak, I can see the requests from my phone in the query log on the server which means adguard doh server is working fine. With Adguard for iOS, I do not see any requests at all.

**Comment by SoLenny** [comment]
@itsnotv Hello, can you please specify which AdGuard settings you have enabled?
And please describe expected behaviour and actual behaviour with more details.

**Comment by itsnotv** [comment]
@SoLenny I have enabled "DNS Privacy", and added a custom DNS Server (my own adguard home server). Tried both Split Tunnel and Full Tunnel VPN options.

When DNS Privacy is turned on, VPN connects, the device should use the configured server for DNS. But as per the logs on the server, it is not using the configured custom url. Ads show up in all other apps like google news.

**Comment by SoLenny** [comment]
@itsnotv To troubleshoot this issue, we need to get the app logs.
Here’s what we need you to do:
Reproduce the issue (and remember the exact time when it happened).
Open the app, tap “Send Feedback”, select “Contact Support”
The mail app will be opened, change the recipient to apple@adguard.com (!)
Mention this issue number in the email text.

**Comment by itsnotv** [comment]
I was able to fix this when I turned off cloudflare proxy for the adguard home server. It's strange that clouldflare didn't block when configured with DNSCloak app, but was blocking Adguard for iOS. Now I am able to block ads apps other than safari.

Could you show an error or block network on the device if the configured dns over https url is not reachable? It looks like it skips the doh server if it can reach it, without any indication to the user.

**Comment by IvanIin** [comment]
@itsnotv
