### ISSUE TITLE
Добавить метки к заблокированным DNS запросам.

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardForiOS#1321]
В журнале DNS запросов не хватает меток с типом заблокированного запроса. В PRO версии, насколько помню, они есть, например ads, tracking и т.п. То есть как бы указывается причина блокировки. Можно ли аналогичное реализовать в AdGuard для IOS Premium?

**Comment by Eugene-Savenko** [comment]
Есть в планах, п.5: https://github.com/AdguardTeam/AdguardForiOS/issues/1107
