### ISSUE TITLE
Can't add dnscrypt dns server AdGuard pro

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdguardForiOS#1322]
"Family Filter"
"Blocks access to all adult, pornographic and explicit sites. It also blocks proxy and VPN domains that are used to bypass the filters. Mixed content sites (like Reddit) are also blocked. Google, Bing and Youtube are set to the Safe Mode."
"CleanBrowsing"
ip=185.228.168.168:8443
key=sdns://AQMAAAAAAAAAFDE4NS4yMjguMTY4LjE2ODo4NDQzILysMvrVQ2kXHwgy1gdQJ8MgjO7w6OmflBjcd2Bl1I8pEWNsZWFuYnJvd3Npbmcub3Jn
can't save. why?

**Comment by IvanIin** [comment]
@YBS-PC Adguard Pro does not support sdns: scheme. You must explicitly specify the ip address and public key of the dnscrypt server.

**Comment by YBS-PC** [comment]
How can I get the public key (cleanbrowsing)?

**Comment by lancelot-moon** [comment]
AdGuard Pro v2 doesn't support DNSCrypt v2.
Wait for AdGuard Pro v3.

**Comment by evilvibes** [comment]
@YBS-PC have a look here https://dnscrypt.info/stamps
