### ISSUE TITLE
dns can't use in jb

### ISSUE THREAD

**Issue by winnieking** [AdguardTeam/AdguardForiOS#1323]
[adguardforios_logs_2971020192310.zip](https://github.com/AdguardTeam/AdguardForiOS/files/3768321/adguardforios_logs_2971020192310.zip)

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Device model and storage size:**
  - 
- **Operating system and version:**
  - 
- **Browser or App:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by SoLenny** [comment]
@winnieking Hello, Adguard Team does not encourage or support the use of jailbreak.
So unfortunately we not be able to help you with this problem.
You can try to install AdGuard from AppStore, we are sure that everything will work as it should.
