### ISSUE TITLE
AdGuard has stopped to block ads

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#1329]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 3.1.2(247)
  - 
- **Device model and storage size:** iPad A1489
  - 
- **Operating system and version:** 12.4.2
  - 
- **Browser or App:** Safari
  - 

### Expected Behavior

Ads are blocked.

### Actual Behavior

AdGuard does nothing. Tried to restart Safari, disable/enable content blockers in OS settings.
Even `##body` is not applied(page should be blank)
In the final I got en error about filters("cannot be loaded to Safari")

### Additional Information

[adguardforios_logs_3051120191311.zip](https://github.com/AdguardTeam/AdguardForiOS/files/3797634/adguardforios_logs_3051120191311.zip)

**Comment by Alex-302** [comment]
For example 
https://github.com/AdguardTeam/AdguardFilters/issues/43233
this ad must be blocked by `||cnzz.com^$third-party` from Base filter, and I see it in exported `cb_general`
```
	{
		"trigger": {
			"url-filter": "^[htpsw]+:\\/\\/([a-z0-9-]+\\.)?cnzz\\.com[/:&?]?",
			"load-type": [
				"third-party"
			]
		},
		"action": {
			"type": "block"
		}
	},
```

**Comment by Alex-302** [comment]
UPD: after device reboot and turning off-on filter groups filtering works again.

**Comment by IvanIin** [comment]
I don't see any errors in the logs. And content blocker jsons look correct. It seems like a bug in Safari that was fixed by rebooting.

**Comment by Alex-302** [comment]
Maybe:( Does Apple know about this problem?

**Comment by Alex-302** [comment]
> And content blocker jsons look correct.

export logs while issue was reproduced was failed.
