### ISSUE TITLE
[Adguard Pro] Ads are not blocked in Музыка ВК app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#133]
https://itunes.apple.com/ru/app/muzyka-vk-skacivaj-muzyku/id1088822111?l=en&mt=8
Original post:
https://forum.adguard.com/index.php?threads/%D0%A0%D0%B5%D0%BA%D0%BB%D0%B0%D0%BC%D0%B0-%D0%B2-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5.12583/

**Comment by ameshkov** [comment]
Hm I wonder if it is possible

**Comment by Stillness-2** [comment]
You should check this:

- Install the latest beta version of Adguard Pro
- Start the app and enable Adguard DNS
- Remove app Music VK
- Install again and launch the app Music VK

I think that the ads in the app associated with a domain `ads.mopub.com`. But if we allow the app to download the advertisement at least once, app will show it even if app will not be able to load ads.
