### ISSUE TITLE
„Update Filters“ sometimes doesn‘t react.

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1330]
Clicking on „Filter aktualisieren“ on the Main Screen doesn‘t work in 4/5 cases. Not sure if this issue is only happening in German. 
Does anyone else having this issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SoLenny** [comment]
@iDjay Hello, to troubleshoot this issue, we need to get the app logs.
Here’s what we need you to do:
Reproduce the issue (and remember the exact time when it happened).
Open the app, tap “Send Feedback”, select “Contact Support”
The mail app will be opened, change the recipient to apple@adguard.com (!)
Mention this issue number in the email text.

**Comment by iDjay** [comment]
I don‘t think there are any logs, it‘s just that the button doesn‘t react.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SoLenny** [comment]
@iDjay Which version do you use?

**Comment by iDjay** [comment]
Latest 3.1.2

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SoLenny** [comment]
From AppStore or Testflight?

**Comment by iDjay** [comment]
AppStore. I‘m always updating to the release version when it’s out, only on the TestFlight version when it‘s higher.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SoLenny** [comment]
Can't reproduce it on my side :(
Did you try to reinstall app?

**Comment by iDjay** [comment]
Yes. It‘s really weird because it’s only happening sometimes. Maybe an issue with the localization? (German)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SoLenny** [comment]
I've tried to reproduce it with german localization, but still nothing :(

**Comment by worldsdream** [comment]
I confirm that I can see the same on English setup with English AG version (appstore).
I can't see it happening on my XS but I can see it happening on my 6s.

Which phone are you using @SoLenny and @iDjay ?

**Comment by iDjay** [comment]
iPhone 11 Pro iOS 13.2 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SoLenny** [comment]
I tried it on X.

**Comment by worldsdream** [comment]
@SoLenny why did you close it? Is it fixed in a beta?

**Comment by SoLenny** [comment]
@worldsdream Now we are working on a new version of the program, it is quite possible that this problem will be fixed there.
Unfortunately, I cannot reproduce it on my side. But we could be helped by videos that show how filter updates behave.

**Comment by ameshkov** [comment]
Anyway, the main screen is changed considerably in the new version

**Comment by worldsdream** [comment]
Looking forward to the new version.

**Comment by worldsdream** [comment]
Just like to mention that this is finally fixed in version 4.0.3 https://github.com/AdguardTeam/AdguardForiOS/releases/tag/v4.0.3. 
This bug was NOT fixed but closed in November 2019. 

@ameshkov I hope the next time, the team can take a closer look and reproduce the problem and fix it (what finally happened).

**Comment by ameshkov** [comment]
Yeah, true, it took us too much time to properly fix it, sorry for that.
