### ISSUE TITLE
Host File Size Causing Disconnect

### ISSUE THREAD

**Issue by rolandscored1234** [AdguardTeam/AdguardForiOS#1331]
When I add a host file to the privacy module larger than say, 40 thousand entries, the VPN stays connected, but rather than the wifi I was just connected to, it looks like it connects to data, but I can’t actually load anything.

If I were to add, for example, [Energized Blu Go Hosts Txt](https://block.energized.pro/bluGo/formats/hosts) to the privacy module, the wifi would disconnect, it would show “5G” in the top right corner, and I would not be able to load any content at all (but in settings I am still connected to whatever wifi network).

Once I delete the host file and turn AdGuard’s filtering off and on again, the wifi will stay connected and I can load content again.

![E9939ACE-10FC-4E3A-BCFB-E6BDB2F17A23](https://user-images.githubusercontent.com/57322883/68087397-3abb6b00-fe0a-11e9-8f06-0c2586e7ac04.png)

![E270090E-2E5D-4BAC-9CC1-92EC39099B16](https://user-images.githubusercontent.com/57322883/68087400-40b14c00-fe0a-11e9-8aa3-217e75577283.png)

As you can see, the connection is broken despite me being connected to a wifi network. As a side note, this is consistent with any wifi network I use, and any* larger host file.

Edit: I am on public iOS 13.2, and was previously on each of the iOS 13.2 betas

**Comment by SoLenny** [comment]
Large host files lead to tunnel crashes due to lack of memory.
Unfortunately we can’t do anything about it.
