### ISSUE TITLE
Wrong language icon for "Liste AR" filter

### ISSUE THREAD

**Issue by IvanIin** [AdguardTeam/AdguardForiOS#1334]
![image.png](https://images.zenhubusercontent.com/5a71a07f4b5806bc2bc5045b/4d5cc2c5-a223-440d-b00a-794d276cbf4a)

must be [https://app.zenhub.com/files/43807802/ad341eab-802e-49a1-a825-1b01a11c40ad/download](https://app.zenhub.com/files/43807802/ad341eab-802e-49a1-a825-1b01a11c40ad/download)

**Comment by worldsdream** [comment]
There is no Arabic flag, because Arab is not a country.

**Comment by ameshkov** [comment]
Good catch:)
