### ISSUE TITLE
AdGuard Pro constantly disconnects/reconnects 

### ISSUE THREAD

**Issue by mike-shyu** [AdguardTeam/AdguardForiOS#1339]
On AdGuard Pro v2.1.2. iOS 13.2.2. The “VPN” connection constantly disconnects and connects without any user input. I did a screen recording. Notice the top right icon as it randomly shows the VPN connecting and disconnecting.

This makes AdGuard Pro almost impossible to use since connections get reset while browsing and I’ll have to refresh the query or try clicking the link again or reperform the action of using an app. 

Until then I’m most likely have to keep AdGuard Pro disabled until it gets fixed. 

https://www.dropbox.com/s/s4awr2m60pkcdon/Video%20Nov%2016%2C%2011%2011%2027%20AM.mp4?dl=0

**Comment by SoLenny** [comment]
@mike-shyu Hello, in the near future the pro version will be completely redesigned.
When the update will available, most likely your problem will be solved, and even if not, we will definitely return to it.
