### ISSUE TITLE
Internet stops when router is set up with AdGuard DNS

### ISSUE THREAD

**Issue by takeitout568** [AdguardTeam/AdguardForiOS#1343]
When I set set up my router with AdGuard DNS I no longer have access to the internet.  Is this a common issue?

**Comment by SoLenny** [comment]
@takeitout568 Hello, can you please specify which device you are using and which AdGuard program?

**Comment by takeitout568** [comment]
I’ve been using the AdGuard DNS with the AdGuard Pro App and on my router with no problem until recently.

Currently whenever I connect to any of the AdGuard DNS servers, whether on the AdGuard Pro app or through the DNS on my router, I no longer have internet access.

**Comment by takeitout568** [comment]
Also, when using the AdGuard DNS on the router, all devices connected to the router loose internet access.  

As for the AdGuard Pro App DNS, I’m running it on iOS 13.2.3

**Comment by SoLenny** [comment]
@takeitout568 Сould you check if the problem persists if you select another DNS server?  (not system and not adgard dns).

And to troubleshoot this issue, we need to get the app logs.
Here’s what we need you to do:
Reproduce the issue (and remember the exact time when it happened).
Open the app, tap “Send Feedback”, select “Contact Support”
The mail app will be opened, change the recipient to apple@adguard.com (!)
Mention this issue number in the email text.

**Comment by takeitout568** [comment]
The problem does not persist when I select another DNS server. I’m currently using OpenDNS servers and its working fine.  The problem only happens when using the AdGuard DNS servers.

I will send the logs to the email as suggested. 

Thank you for your help!

**Comment by SoLenny** [comment]
@takeitout568 Hello, we still need your logs :)

**Comment by takeitout568** [comment]
Hi Lenny,

The issue seems to have resolved itself as I’ve switched back to AdGuard DNS and am able to access the internet.

I did look in the AdGuard Pro iOS App for the “send feedback” button but was unable to find it.  Is the “report an issue” button the same thing?

If so, I’ll try the “report an issue” button if the problem happens again. 👍

**Comment by SoLenny** [comment]
Nice to know that your problem solved.
