### ISSUE TITLE
Unable to change DNS type from DoH to anything else

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#1347]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS 3.1.2.247
- **Device model and storage size:**
  - Unspecified iPhone
- **Operating system and version:**
  - iOS 13.2.3

### Expected Behavior

User should be able to change DNS type from DoH to anything else (e.g. DoT, DNSCrypt, regular)

### Actual Behavior

AdGuard does not allow changing DNS type.

### Screen recording

<details><summary>Screenshot:</summary>

[RPReplay_Final1574160863 (1).zip](https://github.com/AdguardTeam/AdguardForiOS/files/3889514/RPReplay_Final1574160863.1.zip)

</details>

### Additional Information

Logs: 
[adguardforios_logs_3261120191311.zip](https://github.com/AdguardTeam/AdguardForiOS/files/3889516/adguardforios_logs_3261120191311.zip)

User helpdesk ID: 2393642

**Comment by zaheerhakim** [comment]
If you need any other log from my iPhone 11 Pro do let me know.

**Comment by zaheerhakim** [comment]
Device model and storage size: iPhone 11 Pro 512GB.
