### ISSUE TITLE
[Bug] Full-tunnel mode sometimes does not work

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdguardForiOS#1349]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - Adguard for iOS v3.1.2 (247)
- **Device model and storage size:**
  - iPhone 8 plus 64gb
- **Operating system and version:**
  - iOS 13.2.3

### Actual Behavior

DNS queries arrive at the same time to the default DNS server on the router and the DNS server is installed in Adguard

### Steps to reproduce

1. Switch to full-tunnel mode
2. Turn on “Restart on network change”
3. Go to another wifi area, let ios automatically switch to that wifi

### Screenshots

<details><summary>Screenshot:</summary>

![IMG-3091](https://user-images.githubusercontent.com/10969626/69839661-0e6d0000-128b-11ea-9fee-167e05e31634.jpg)
![IMG-3092](https://user-images.githubusercontent.com/10969626/69839662-0e6d0000-128b-11ea-9949-9c5790db278f.jpg)
![IMG-3093](https://user-images.githubusercontent.com/10969626/69839663-0f059680-128b-11ea-8623-c89fc41d0282.jpg)
![IMG-3094](https://user-images.githubusercontent.com/10969626/69839664-0f059680-128b-11ea-9440-f16604a47ea6.jpg)

</details>

### Additional Information

The wifi area that my device moved to has the DNS address `203.113.188.1`. When the device automatically connects to that wifi, Adguard sends queries at the same time to both DNS servers, which are the DNS servers in the router and the Adguard app DNS server I have installed. This causes the resolution speed to increase significantly around 1800ms to 2000ms, resulting in a slower network speed.

The log I attached sent via email! Thanks!

User helpdesk ID: 1542905

**Comment by akmLaVx** [comment]
Logs available in helpdesk ticket 1542905

**Comment by ameshkov** [comment]
> When the device automatically connects to that wifi

@bigdargon could it be that this wifi network is protected with a captive portal?

It sounds as if the DNS server is simply not available and AdGuard falls back to the system DNS.

**Comment by bigdargon** [comment]
> could it be that this wifi network is protected with a captive portal?

No. This wifi network is connected directly to the Internet and not protected with a captive portal.

> It sounds as if the DNS server is simply not available and AdGuard falls back to the system DNS.

Nextdns server is always uptime. I will test with Adguard DNS and send a log via email.

**Comment by bigdargon** [comment]
@ameshkov I have checked with Adguard DNS and also the same error.  I attach the log and screenshot in the email.

This DNS is the default of ISP Viettel in Vietnam

![379D1112-3840-48EF-83BB-B23E93B2BCC4](https://user-images.githubusercontent.com/10969626/70200063-f9d6af00-1745-11ea-935d-1df7b811d4fc.jpeg)
![0E838BA4-78DB-49B0-BDAD-B4A15CCBFB20](https://user-images.githubusercontent.com/10969626/70200065-fa6f4580-1745-11ea-9de1-6acbe8182c10.png)
![A568B797-EADC-4178-82C3-B34557886A9D](https://user-images.githubusercontent.com/10969626/70200066-fa6f4580-1745-11ea-8c7f-8945723adde6.jpeg)
![7D1B6A19-EC28-4CF3-996C-93A7C14BFC87](https://user-images.githubusercontent.com/10969626/70200067-fa6f4580-1745-11ea-8a52-efa51d5ee817.jpeg)

**Comment by akmLaVx** [comment]
Additional logs have arrived.

**Comment by ameshkov** [comment]
Here's what's going on -- for some reason AdGuard fails to connect to AdGuard DOH in time and fallbacks to the system DNS. The question is why the connection times out.

We should re-test it when the new version is ready, DNS implementation is different there.

**Comment by bigdargon** [comment]
Thank you! I will keep checking this problem in the new version!

**Comment by SoLenny** [comment]
@bigdargon Hello, we added a new beta version in which your bug should be fixed. Soon he will appear in the TestFlight, please try it :)

**Comment by bigdargon** [comment]
@SoLenny Tested and unaffected in beta. Thank you!
