### ISSUE TITLE
Add a 'password protection' feature for Adguard PRO section

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForiOS#135]
So that a child couldn't deactivate 'family protection' mode, for example.

Originally from: https://forum.adguard.com/index.php?threads/12328/#post-95369

**Comment by vbagirov** [comment]
Any chance we are going to implement this?

**Comment by ameshkov** [comment]
A mere password protection does not make much sense as the VPN can be disabled in the phone settings.

**Comment by vbagirov** [comment]
Maybe add some kind of "uptime log" or "activity log"? So that the user can see at which times and which AG settings were changed, or when it was down etc.

**Comment by ToniKumpula** [comment]
Actually you can not turn off vpn through iOS settings when AdGuard has enabled it, if I turn off vpn through iOS settings it will re-enable itself.

Might be a iOS bug who knows.

**Comment by ameshkov** [comment]
https://adguard.com/en/blog/adguard-pro-discontinued/
