### ISSUE TITLE
Incorrect filter update in action extension in background

### ISSUE THREAD

**Issue by IvanIin** [AdguardTeam/AdguardForiOS#1350]
If user move the extension to background before filter update is finished, update proicess is suspended and never finished.

steps to reproduce:
1. open any site with ads(blocked by adguard)
2. open Adgard Action Extension
3. turn "enabled" switch off and immediately close action extension(tap "done" button)
4. reload web page

expected result:
ads is not blocked

result:
ads is blocked

**Comment by worldsdream** [comment]
This is not properly fixed. This happened with one of the last versions. Before this was working like it should. It’s misleading how it works now and not right. Please have a look below. 

What is should do:
Open the app and click on update
It’s spinning for checking for updates
Close the app to background
Open the app again
It should keep spinning as “updating”
Show as filters updated or that there is no filter update. 

What is happening at the moment:
Open the app and click on update
It’s spinning for checking for updates
Close the app to background
Open the app again
It shows filters updated: 8 dec 2019
After couple of seconds it shows updated filters/no filter update.
