### ISSUE TITLE
Last updated time cut off on iOS devices

### ISSUE THREAD

**Issue by BrentMifsud** [AdguardTeam/AdguardForiOS#1351]
See below screenshot:

I am using an iPhone XS Max

![9AC0BFA3-3BFD-4A06-B731-3ED25ABD0319](https://user-images.githubusercontent.com/18543934/69904273-b5789700-1372-11ea-9c10-d5007bdfb3f8.png)

**Comment by bigdargon** [comment]
Dup #1283

**Comment by SoLenny** [comment]
This will be resolved automatically when the Pro version is updated to match the regular one.
