### ISSUE TITLE
DNS filter for adguard ios

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdguardForiOS#1352]
Adguard for android with  a premium functions allows to use DNS filters, why there is no it in adguard for iOS? adguard for iOS for the same money turns out it is limited in functions and allows to block advertizing only in one safari browser...

**Comment by SoLenny** [comment]
@YBS-PC Hello. Unfortunately, in the current version of the application, we do not have dns filters. However, soon a new, improved version will be released in which such a function will be provided. In the meantime you can use AdGuard DNS - it filters on the server side.
