### ISSUE TITLE
Issue with premium function activation

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForiOS#1356]
### Issue Details

- **AdGuard version:**
  -  3.1.2.247
- **Device model and storage size:**
  -  iPad Air 2
- **Operating system and version:**
  -  13.2.3

### Expected Behavior

Activation of the premium function should be without any problems.

### Actual Behavior

When entering a login and password from your AdGuard personal account. 
This error occurs (look at the screenshot).
According to the logs, the premium is activated, but the user still gets an error.

**Note**: I checked his account for available keys to activate.
There are many available licenses, but there are also unactivated keys, maybe the application is trying to use them?

**Logs in NCloud**

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/70052688-e102b800-15e4-11ea-91ae-002f0cd79d63.png)

</details>

### User ID
Hidden from Telegram

**Comment by Chinaski1** [comment]
One more user faced this issue: **2235876**
He [cant activate](https://uploads.adguard.com/Chinaskic6ubw.png) premium functions.
Device model: iPhone 6/iOS 10.3.2
I asked for more information and log files.

**Comment by IvanIin** [comment]
@Chinaski1 
In the logs, I see network errors when trying to login.

**Comment by Chinaski1** [comment]
One more user faced a similar issue.
- Helpdesk ID: 2672115
- iPhoneXS and iOS is ver. 12.4.1;
- Application version: 3.1.4.254;
- Time|Date:  20:42-20:44 | 08.05.2020
- Logs are added to NCloud

**Comment by Chinaski1** [comment]
One more report from our user:
- HelpDesk ID: 2783767
- IPad and iOS version: 14.0
- App Version: 4.0.1.495
- Logs are added to NCloud

**Comment by worldsdream** [comment]
@ameshkov Version 4.0 is released, and this issue is still showing in the milestone. Is it not finished? Why not move it to a new milestone and close the milestone. Don't know who is in charge of this. Please keep it up to date as you got a public that likes to stay up to date.

**Comment by Chinaski1** [comment]
@worldsdream 
Hello there!

Did you face a similar issue?
It seems that we tritely forgot to close the task :)

**Comment by worldsdream** [comment]
@Chinaski1 Hi! No I don’t have such issue. I just like to watch the milestones and keep up to date before I submit any issues/features. 

Thank you for closing the task.

**Comment by zzebrum** [comment]
@worldsdream sorry for that. We now have the other private bug tracker, so things may be a little outdated here. But I will try to update info here too.
