### ISSUE TITLE
Add an option to reset statistics

### ISSUE THREAD

**Issue by SoLenny** [AdguardTeam/AdguardForiOS#1358]

**Comment by 08kovalchuk03** [comment]
https://app.goabstract.com/projects/2b264260-c732-11e8-a52a-07ba12563bc0/branches/11c2f816-a79f-4d44-9b26-3caee7273f88/commits/bc7940f2a8891f4ccda32f17ece72102b9c6a953/files/0B986117-1199-42D4-99B7-06AE1C613873/layers/DF4B20C0-C95E-4838-B5B8-98018D95542D?mode=build
