### ISSUE TITLE
Report a bug of Adguard For iOS (3.1.3)252

### ISSUE THREAD

**Issue by asdfj2381k** [AdguardTeam/AdguardForiOS#1359]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [√] I am running the latest version
- [√] I checked the documentation and found no answer
- [√] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**

![image](https://user-images.githubusercontent.com/56584082/70208399-6e224a00-1768-11ea-97f4-320a1e6f93d1.png)

- **Device model and storage size:**
iPhone X 64gb
- **Operating system and version:**
13.2.3

### Information Detail
![20191205140111](https://user-images.githubusercontent.com/56584082/70208192-d886ba80-1767-11ea-8e11-8e82143f51e2.png)

**Comment by SoLenny** [comment]
@asdfj2381k  Hello. Thanks for your feedback.
If you kill the application process immediately after making any changes, they may not be saved. Therefore, in order for the settings to be saved correctly, please wait a while before completing the program process.

**Comment by asdfj2381k** [comment]
@SoLenny 

According to your instructions, I tried again.

After modifying the settings, I waited for 2 minutes before killing the process, but still failed to save after returning.

Can you give it a try?         I can guarantee that the problem is real.

**Comment by SoLenny** [comment]
@asdfj2381k Unfortunately, I can’t reproduce this bug on my side. I use the same localization and phone as you. But we will definitely try to sort out your problem.
To troubleshoot this issue, we need to get the app logs.
Here’s what we need you to do:
Reproduce the issue (and remember the exact time when it happened).
Open the app, tap “Send Feedback”, select “Contact Support”
The mail app will be opened, change the recipient to apple@adguard.com (!)
Mention this issue number in the email text.

**Comment by asdfj2381k** [comment]
@asdfj2381k 

Honestly, I don't believe you can't reproduce the problem.

I have two iPhones here and an iPad Pro, which can reproduce this problem.

Can you take a short video to prove that you cannot reproduce the problem? 

This should not waste you a lot of time, thank you very much.

**Comment by SoLenny** [comment]
@asdfj2381k Sure, here it is https://uploads.adguard.com/RecordIt-1575538814.mp4

**Comment by asdfj2381k** [comment]
@SoLenny 

Here are my logs
[adguardforios_logs_3391220191712.zip](https://github.com/AdguardTeam/AdguardForiOS/files/3926119/adguardforios_logs_3391220191712.zip)

I exported them about 30 seconds after encountering problems.

Could you please analyze the cause of the problem?

**Comment by SoLenny** [comment]
@asdfj2381k Thanks. Our iOS developer @IvanIin will have a look.

**Comment by SoLenny** [comment]
@asdfj2381k 
This is very strange but this bug did not get into the logs, for some reason they break off after December 2. Could you try to throw logs from another device (reproduce the bug again and send them)?

**Comment by asdfj2381k** [comment]
[adguardforios_logs_3391220192012.zip](https://github.com/AdguardTeam/AdguardForiOS/files/3926723/adguardforios_logs_3391220192012.zip)

@SoLenny  dump from another iPhone

**Comment by SoLenny** [comment]
@asdfj2381k thx

**Comment by SoLenny** [comment]
@asdfj2381k It will be fixed in 3.2
Thanks a lot for feedback :)
