### ISSUE TITLE
[Adguard Pro for iOS] google.ca - Chrome self-advertising

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#136]
https://github.com/AdguardTeam/AdguardFilters/issues/2822

User enabled Annoyance filter that has the rule to block the ad, but

> I enabled the annoyance filter, tested when Safari is close from background and at launch when safari opens Google homepage the banner is still visible but when a new tab is opened the banner is blocked by Adguard. Why it's not blocking banner at startup of Safari?

**Comment by evgeniy-ADG** [comment]
The comment from the user:

>I noticed that since I have a shortcut of direct Google homepage on my dock the banner loads, if I use safari and manually go to Googlr homepage the banners are blocked. I think the shortcut page loads faster then the Adguard filters apply vs going through Safari where Adguard has time to load the filters while I am typing the Google homepage? Possible delay in Adguard filters being active upon browser launch?

<details>
![image1](https://cloud.githubusercontent.com/assets/15856304/17729625/c1f320e8-646d-11e6-8a5f-51af27fd6e5c.png)

**Comment by ameshkov** [comment]
It could be an old issue with the content blocking API (cosmetic rules aren't applied if the website is opened that way).

**Comment by Stillness-2** [comment]
#101
