### ISSUE TITLE
Custom Filter Subscription

### ISSUE THREAD

**Issue by Pusnow** [AdguardTeam/AdguardForiOS#1360]
### Problem Description

Unlike Mac version, iOS version does not have "custom filter subscription". 
I've already tested "New Subscription" under privacy section, and it does not work. (It seems to only allow domain list.)
I've tested with below file.
```
naver.com###PM_ID_ct > div.container:nth-child(3)
```

### Proposed Solution

Add a new menu like

![스크린샷 2019-12-05 오후 8 20 11](https://user-images.githubusercontent.com/6031017/70231558-e9522300-179d-11ea-8627-9e8dfd9ff67f.png)

**Comment by SoLenny** [comment]
@Pusnow Hello, adding custom filters is currently available in the free application, after purchasing a premium. In the pro version, this will available later, after a complete re-release of the application.
