### ISSUE TITLE
Bug: Reload not showing properly

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#1364]
This is not properly fixed. This happened with one of the last versions. Before this was working like it should. It’s misleading how it works now and not right. Please have a look below. 

What is should do:
Open the app and click on update
It’s spinning for checking for updates
Close the app to background
Open the app again
It should keep spinning as “updating”
Show as filters updated or that there is no filter update. 

What is happening at the moment:
Open the app and click on update
It’s spinning for checking for updates
Close the app to background
Open the app again
It shows filters updated: 8 dec 2019
After couple of seconds it shows updated filters/no filter update.

**Comment by ameshkov** [comment]
It appears that closing the app when filters reload is in progress may cause problems. The thing is that Safari stops loading content blockers update completely when the app that triggered it goes to the background.

**Comment by worldsdream** [comment]
This was not happening before. Before it was working great. It keps spinning, even if you move it to the background. I dont know if I was on another iOS version or if it’s with the newest app updates from AG.

**Comment by asdfj2381k** [comment]
Filter update indicators often do not work properly, as shown by stuck or unresponsive clicks.

I hope we can deal with this problem as soon as possible.    Such basic mistakes have affected the brand image of adguard.     @ameshkov

**Comment by ameshkov** [comment]
> It kept spinning, even if you move it to the background.

What matters is that Safari pauses loading content blockers internally. When the app gets back to the foreground, Safari continues loading from the same point where it was when you closed the app.

**Comment by worldsdream** [comment]
Yes understand that. But when it comes back to the foreground, it should show the spinning wheel. Because it’s updating. Now it does not show anything and if you tap on the screen for updates, nothing happens. All of a sudden you see the message that filters got updated.

**Comment by ameshkov** [comment]
Got it, thanks! We'll see why it could happen.
