### ISSUE TITLE
Please add and use zh-HK locale for Hong Kong users.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1376]
AG team uses zh-TW (Chinese Traditional, Taiwan) language file for not only Taiwan but also Hong Kong and Macao (apps or introduction on Google Play/Chrome web store/App Store/official website...etc.) due to the convenience.

Since AG team observed that zh-TW and zh-HK (Chinese Traditional, Hong Kong) are different locales and allowed zh-HK locale was added on Crowdin, it is much better not to use zh-TW for Hong Kong by default.

Please add and use zh-HK locale for Hong Kong users.
If you think zh-HK isn't ready, temporarily using zh-CN (Chinese Simplified) in iOS apps and app store for Hong Kong by default is much better.
Hong Kong is the territory of China.
Chinese Simplified (zh-CN) is also universal in Hong Kong.
In Hong Kong, Chinese Simplified is used in their real life more and more.

**Comment by ameshkov** [comment]
New translations are added only when @aalpatkina considers they're ready.

**Comment by lancelot-moon** [comment]
I don't want to argue.
But tw in zh-TW means Taiwan, not Hong Kong.
Since @aalpatkina allowed zh-HK on Crowdin, Hong Kong translators should make their own translations.
Did any AdGuard's translators not make their own translations by themselves?
Before zh-HK is ready, using zh-CN for Hong Kong is much better.
zh-TW is Taiwanese locale, not HK locale.
