### ISSUE TITLE
Random app crash (due to lack of resources?)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#138]
Source:
https://forum.adguard.com/index.php?threads/adguard-%D0%9F%D0%A0%D0%9E-%D0%B4%D0%BB%D1%8F-ios-v1-0-%D0%B1%D0%B5%D1%82%D0%B0.12328/#post-96042

Customer ID: 1240487

**Comment by Stillness-2** [comment]
#129
