### ISSUE TITLE
Fix Texts in 3.2

### ISSUE THREAD

**Issue by dsolomakin** [AdguardTeam/AdguardForiOS#1382]
Format: **Screen Name**
Old text -> New text
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

**About**
How to use -> Video Tutorial
Site -> Developer’s Website
Acknowledgments -> Knowledge Base
License - > Manage License

**Safari Protection**
This AdGuard module remove -> This AdGuard module removes

**Filters/Custom**
Allow adding third-party filters.
Available for Premium users. -->
Allows adding third-party filters.
Available for Premium users.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForiOS/issues/1424
