### ISSUE TITLE
[request] support Firefox

### ISSUE THREAD

**Issue by alexchandel** [AdguardTeam/AdguardForiOS#1385]
### Problem Description

Firefox for iOS [claims to support native app extensions](https://support.mozilla.org/en-US/kb/add-ons-firefox-ios) like Safari.  However, no ad blocking apps exist yet for Firefox.  Yet some websites' ads are refined cancer, using 1000x the page's bandwidth and clickjacking every tap, and must be blocked.

### Proposed Solution

Add support for Firefox content blocking.

### Alternatives Considered

Mozilla also releases [Firefox Focus](https://apps.apple.com/us/app/firefox-focus-privacy-browser/id1055677337).  However, Focus is infrequently updated and lacks most of the features of Firefox.

Firefox for iOS also claims [to not yet support](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_for_iOS#Addons) JavaScript extensions.  If this is a prerequisite, Adguard will have to monitor / gently nudge the implementation progress.

**Comment by SoLenny** [comment]
@alexchandel Hello. Unfortunately, the policy of Apple is such that all browsers with an engine other than WebKit (on which safari is made) are prohibited from being placed in the AppStore. Thus Firefox for iOS is not a real Firefox with all its functionality, but only a "wrapper" on WebKit. This means that this application does not support any extensions. We can only recommend you use the premium features of AdGuard, including DNS.

**Comment by ameshkov** [comment]
> Firefox for iOS claims to support native app extensions like Safari

@alexchandel I don't see where they claim by this link. Are you sure it's possible?

**Comment by alexchandel** [comment]
@ameshkov They seem to move it around, but it's [here](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_for_iOS#Addons):

> Firefox for iOS supports the native iOS extension ecosystem right now, but doesn't (yet) support JavaScript add-ons like Desktop or Android Firefox.

**Comment by alexchandel** [comment]
@SoLenny I know Apple WebKit's policy.  That has no bearing on extensions.

Like I said, I'm talking about iOS's native extension system, which Firefox [here claims to support](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_for_iOS#Addons), and which they have the technical ability to support regardless.

A precise API (like iOS Safari's Content Blocker API) may require some coordination with Firefox's iOS devs, but that's germane.

Please reopen this issue.

**Comment by ameshkov** [comment]
As I understand, they claim to support "Action extensions", "Share extensions" and this kind of stuff. I am pretty sure Content Blockers aren't supposed to be used anywhere save for Safari itself.

Just to be sure, I've asked Firefox devs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1608354
