### ISSUE TITLE
AdGuard DNS is blocking something not blacklisted

### ISSUE THREAD

**Issue by moust4ki** [AdguardTeam/AdguardForiOS#1386]
- **AdGuard version:**
  - AdGuard Pro 2.1.2(173)
- **Device model and storage size:**
  - iPhone 11 256Gb
- **Operating system and version:**
  - iOS 13.3
- **Browser or App:**
  - Apps

### Expected Behavior

Application that pull content should be working when domain is not blacklisted by DNS filter

### Actual Behavior

AdGuard Pro is setup to use content filetering and DNS filtering (SDN list) whit 1.1.1.1 DNS (Cloudflare) 
I have a service, Canary security cameras, that is not working until I whitelist the domain he use (canary.is, canaryis.com) but those domains are not it a blacklist (the DNS query is white in the log).
When I whitelist it or if I disable filtering, the app is working and I can see my camera.

### Screenshots

![IMG_2482](https://user-images.githubusercontent.com/10527028/71237983-3d631880-2303-11ea-8f89-ec1512024a3c.PNG)

![IMG_2483](https://user-images.githubusercontent.com/10527028/71237971-376d3780-2303-11ea-850c-0fb6eaaaae06.PNG)

### Additional Information

Here are my debug logs from the app.
[com.adguard.AdguardPro.tunnel.gz](https://github.com/AdguardTeam/AdguardForiOS/files/3987214/com.adguard.AdguardPro.tunnel.gz)
[filter.gz](https://github.com/AdguardTeam/AdguardForiOS/files/3987215/filter.gz)
[state.txt](https://github.com/AdguardTeam/AdguardForiOS/files/3987216/state.txt)
[com.adguard.AdguardPro.ActionExtension.gz](https://github.com/AdguardTeam/AdguardForiOS/files/3987217/com.adguard.AdguardPro.ActionExtension.gz)
[com.adguard.AdguardPro.gz](https://github.com/AdguardTeam/AdguardForiOS/files/3987218/com.adguard.AdguardPro.gz)

**Comment by SoLenny** [comment]
@moust4ki Hello, in the near future the pro version will be completely redesigned.
When the update will available, most likely your problem will be solved, and even if not, we will definitely return to it.

**Comment by ameshkov** [comment]
> is not working until I whitelist the domain he use (canary.is, canaryis.com)

Well, could it be that it's Cloudflare DNS that breaks them?

You see, when you whitelist a domain in AdGuard DNS, it starts sending the query to the system DNS resolver instead.

**Comment by moust4ki** [comment]
No, I tested with built in and it’s the same.
Will see with the futur pro version. Is there any timeframe for at least a beta of this new pro version? 
Thanks
