### ISSUE TITLE
DNS settings not respected when setting custom VPN

### ISSUE THREAD

**Issue by zjeffro** [AdguardTeam/AdguardForiOS#1387]
iOS version 13.3.1 beta 
Adguard iOS version 3.1.3
iPhone 7 A1660 Sprint

Let’s say you want to activate split tunnel VPN . If you decide to run custom Cisco OpenDNS “regular” instead of Crypt default and try to activate it, it swaps back to default for Cisco. Does this on multiple DNS settings

**Comment by SoLenny** [comment]
Hello, we know about this bug, it will be fixed in 3.2 
To avoid this problem, just tap on "Select" button, after changing server.

**Comment by SoLenny** [comment]
Duplicate https://github.com/AdguardTeam/AdguardForiOS/issues/1347
