### ISSUE TITLE
Pro doesn't work on 3G

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#139]
<details>
![image1 1](https://cloud.githubusercontent.com/assets/15856304/17802325/4cf9eef2-65f8-11e6-8021-6c0008ecde22.png)
</details>
>I noticed Adguard Pro VPN not connected when on 3G 

Logs: 1303217

**Comment by Stillness-2** [comment]
It needs to check on last beta version.
