### ISSUE TITLE
Ошибка в описании на IOS

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdguardForiOS#1392]
на скриншотах видно
![20191223_180929000_iOS](https://user-images.githubusercontent.com/52429295/71373627-e8582880-25c8-11ea-8e6b-9484ec46e41f.jpg)
![20191223_180905000_iOS](https://user-images.githubusercontent.com/52429295/71373632-eb531900-25c8-11ea-802a-669401f99bf1.jpg)

**Comment by IvanIin** [comment]
duplicate #1311
