### ISSUE TITLE
Suggestion: Category with a compiled set of recommended filters

### ISSUE THREAD

**Issue by sekizuri** [AdguardTeam/AdguardForiOS#1396]
### Issue Details

- **AdGuard version:**
  -  AdGuard Pro for iOS v2.1.2(173) 
- **Device model and storage size:**
  - iPad 6th gen. (2018) 32gb
- **Operating system and version:**
  - iOS 13.3
- **Browser or App:**
  -  Safari 13 

### Suggested Behaviour

A new category in the AdGuard Pro version, in Settings > Filter > top, which can make it easier to select filters, considering the limited amount of filters possible in the app (50,000). Especially relevant for novice users of the app (like myself), to attain some increased clarity regarding which filters are recommended to install, as some are obsolete (eg. Prebake), some are redundant (eg. Fanboys Social Blocking is already included in Fanboys Annoyances; so remove one from the set of recommended filters), and maybe even attempt to rank or group-rank them in terms of how critical they are to not risk one’s privacy (eg. listing Adguard Base Filter higher than Adguard Experimental Filter may make sense for the novice user). 

### Additional Information

I’m not a programmer or advanced user, I just installed the app so I’m kind of doing this for myself. Point being, don’t ask me something too advanced. I know nothing. I just want to know which filters and subscriptions are recommended to install.

**Comment by SoLenny** [comment]
@sekizuri Hello, in the near future the pro version will be completely redesigned.  
When the update will available, most likely your suggestion will be implemented.
