### ISSUE TITLE
Which filters are recommended to use for a novice user?

### ISSUE THREAD

**Issue by sekizuri** [AdguardTeam/AdguardForiOS#1397]
### Issue Details

- **AdGuard version:**
  -  AdGuard for iOS v2.1.2(173) 
- **Device model and storage size:**
  -  iPad 6th gen. (2018) 32gb
- **Operating system and version:**
  -  iOS 13.3 

### Background

Considering the limited amount of filters possible in the app (50,000), and that I’m a novice user of the app, I’d like some clarity regarding which filters are recommended to install. For example, I’m informed in the app that the Fanboys Social Blocking filters are already included in Fanboys Annoyances filters, but Fanboys Annoyances Filter was last updated in July this year; so it seems a bad idea here to go for the more encompassing Fanboys Annoyances Filter. Et cetera.

### Question
 
In relation to my other issue created (https://github.com/AdguardTeam/AdguardForiOS/issues/1396): I’m here wondering if anyone can recommend me a set of filters to use?

**Comment by SoLenny** [comment]
@sekizuri Hello, in the application, by default, the recommended set of included filters is used. For comfortable use this will be enough :)
