### ISSUE TITLE
There should be an explanation how automatic updates work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#140]
**Source:**
https://forum.adguard.com/index.php?threads/adguard-for-mac-filter-updates-automatically.11457/#post-89484

> Yeah, is there somewhere or someway to explain to the user thy have to actually open the Adguard iOS app to get updates? Otherwise, as I have seen as a field user, the filters won't get updated. Which means that there are probably a lot of users who are out there running the same filter definitions that were installed the day they installed the plugin. Thus, they could be months out of date.

**Comment by worldsdream** [comment]
https://github.com/AdguardTeam/AdguardForiOS/issues/249
