### ISSUE TITLE
Add an option to disable all content blockers at once

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#1404]
### Problem Description

If a user would like to completely stop filtering for Safari, they will have to disable each content blocker one by one.

### Proposed Solution

Add an option to disable all content blockers at once.

### Alternatives Considered

Add an app management screen.

### Additional Information

Submitted by: 2334753

**Comment by ameshkov** [comment]
There will be such an option in the next version.
