### ISSUE TITLE
[Bug] Content blockers loading into safari don't stop

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdguardForiOS#1405]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v3.1.4
- **Device model and storage size:**
  - iPhone 8 Plus 64gb
- **Operating system and version:**
  - 13.3

### Steps to reproduce

1. Exit the adguard application in the background
2. Click update
3. Go to settings > genaral > content blocker
4. Loading into safari don’t stop

### Video

https://youtu.be/OGwJwkA7wBI

### Additional Information

In addition, if you press 2 times to update when you open the application (after exiting the background), then pressing the "settings" button will be delayed 2 times (in the video)

**Comment by SoLenny** [comment]
Duplicate https://github.com/AdguardTeam/AdguardForiOS/issues/1365

**Comment by bigdargon** [comment]
@SoLenny Can you watch the video?  In addition to the Content Blocker failure, the setting is also delayed.  

1. Exit the application in the background
2. Open the application
3. Click on filter updates
4. While the filter is updating
5. Press the install button 2 times (maybe more)
6. Wait 1 moment, the setting item will appear 2  times or equal to the number of times the setting button is pressed.

**Comment by ameshkov** [comment]
@SoLenny could you please check this on the alpha version, do we still have this bug?

**Comment by SoLenny** [comment]
@ameshkov yep

**Comment by bigdargon** [comment]
I will keep checking this problem in the new version!
