### ISSUE TITLE
Add configurable fallback IP addresses for DoH and DoT

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdguardForiOS#1406]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Follow https://github.com/AdguardTeam/AdguardForiOS/issues/1349#issuecomment-563207437 Adguard will use the system dns to resolve the domain name of DoH or DoT to find the ip address.

For example, Google DNS DoH has the address `https://dns.google.com/dns-query`, when the network restarts Adguard will use system DNS to resolve `dns.google` to ip address `8.8.8.8`.  Assuming that the default DNS server blocking Google's domain will not be able to use DoH.

### Proposed Solution

Add fallback IP address, for the first DNS query when resolving the DoH or DoT server domain name to ip address.  Prevent the use of DNS domain name resolution system.

### Detail information

dnscrypt-proxy uses the fallback ip address

```
## Fallback resolver
## This is a normal, non-encrypted DNS resolver, that will be only used
## for one-shot queries when retrieving the initial resolvers list, and
## only if the system DNS configuration doesn't work.
## No user application queries will ever be leaked through this resolver,
## and it will not be used after IP addresses of resolvers URLs have been found.
## It will never be used if lists have already been cached, and if stamps
## don't include host names without IP addresses.
## It will not be used if the configured system DNS works.
## A resolver supporting DNSSEC is recommended.
##
## People in China may need to use 114.114.114.114:53 here.
## Other popular options include 8.8.8.8 and 1.1.1.1.

fallback_resolver = '9.9.9.9:53'
```

https://github.com/DNSCrypt/dnscrypt-proxy/blob/817d92fce04637d109e96005f77df717ac264541/dnscrypt-proxy/example-dnscrypt-proxy.toml#L186

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardForiOS/issues/1595
