### ISSUE TITLE
Filter options memory

### ISSUE THREAD

**Issue by etsuk001** [AdguardTeam/AdguardForiOS#1407]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Device model and storage size:**
  - 
- **Operating system and version:**
  - 
- **Browser or App:**
  - 

### Expected Behavior

Unselecting specific filters would result in those filter remaining off

### Actual Behavior
Filters turn back on after reconnect or network switchover 

Options return back to their on or selected status after a network switchover. Happens irregularly, approximately 1 in 10 times a network switchover or reconnect, also after renewing lease command sent to router.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by SoLenny** [comment]
@etsuk001 Hello. Please specify which application of AdGuard do you use? 
And please specify which version you are using and which filters you have enabled?

**Comment by SoLenny** [comment]
For a long time we did not receive a response from the user, therefore we close this task at the moment.  
But you can open it again at any time :)
