### ISSUE TITLE
Remove the VPN profile

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdguardForiOS#1408]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Users want to delete the VPN profile of the Adguard app to reinstall the VPN profile

### Proposed Solution

Add option “remove VPN profile”

**Comment by ameshkov** [comment]
Yeah, this makes perfect sense, thank you!
