### ISSUE TITLE
[Question] Is the source code for AdGuard Pro available on GitHub?

### ISSUE THREAD

**Issue by williamli** [AdguardTeam/AdguardForiOS#1410]
I bought AdGuard Pro (iOS) from the app store and am wondering if it is also available on GitHub so I can contribute to it from time to time.

**Comment by SoLenny** [comment]
@williamli Hello, you can ask your questions / create  tasks about Pro version for AdGuard in this repository.

**Comment by williamli** [comment]
but can i work on and make pull request to it?

**Comment by SoLenny** [comment]
> but can i work on and make pull request to it?

Sure.

**Comment by ameshkov** [comment]
Please note that AdGuard Pro is rather old and its code is not really relevant.

It makes sense to wait for the next AdGuard release when we finally update AdGuard Pro and make it match the free version.

**Comment by aAmahQpwRk** [comment]
> It makes sense to wait for the next AdGuard release when we finally update AdGuard Pro and make it match the free version.

Is there a rough ETA for this?

**Comment by ameshkov** [comment]
There are some troubles with Apple, and I am not sure if this will be even possible. I can't say any more at this moment, but once I have new information, if the news isn't good, I'll post an announcement here on Github. If the news is good, we'll simply push the update. Everything will be decided in a couple of weeks.
