### ISSUE TITLE
Автоматическое переключение темы

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardForiOS#1412]
На iOS 13 появилась возможность выставить автоматическое переключение светлой и тёмной тем в течении дня. Хотелось бы чтобы Adguard так же мог переключаться со светлой темы на тёмную и наоборот вместе с системой. Например можно в Настройки добавить пункт "Системная" и чтобы программа брала настройки темы из системы.

**Comment by ameshkov** [comment]
Будет такая возможность в новой версии

**Comment by ameshkov** [comment]
Хотя у нас по идее и в релизной версии это должно работать. Посмотрите в настройках приложения - там есть системная тема

**Comment by Vitalik93** [comment]
В релизной работает только ручное переключение. Либо темная либо светлая.
