### ISSUE TITLE
Need help to figure out why StevenBlack's recent filter list killed AdGuard Pro VPN

### ISSUE THREAD

**Issue by williamli** [AdguardTeam/AdguardForiOS#1416]
See https://github.com/StevenBlack/hosts/issues/1125.

It seems Steven Black's blacklist's Jan 14 update is killed AdGuard Pro VPN (local VPN refused to be connected after the list updated). The author of the repo claims that the update contains a very large update across from AdAway. 

I haven't looked at the logs to see why AdGuard Pro's local DNS / VPN stopped.

**Comment by williamli** [comment]
It seems the list went above 50K rules and killed AdGuard Pro's VPN.

**Comment by bigdargon** [comment]
See this https://github.com/AdguardTeam/AdguardForiOS/issues/616

**Comment by SoLenny** [comment]
@williamli there is no limit by the rules, there is a limit on the use of RAM - 15 MB.
Most likely the problem is this.
