### ISSUE TITLE
Crash in Today Extension

### ISSUE THREAD

**Issue by 08kovalchuk03** [AdguardTeam/AdguardForiOS#1421]
It works with newly added servers, but doesn't work with old ones, maybe some of the properties in old class are missing

**Comment by IvanIin** [comment]
how to reproduce:
1. Install Adguard v3.1.4(254) and run it
2. add any custom DNS server
3. update the app to v3.2.0(293)
4. open a screen with Today Extension

expected result:
Today Extension successfully showed

actual result:
Today Extension can not be loaded
