### ISSUE TITLE
Review all the strings in the dev build and fix mistakes

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1424]
Don't forget to remove obsolete strings.
Upload strings and update screenshots after that.

**Comment by lancelot-moon** [comment]
@aalpatkina 

1. https://crowdin.com/translate/adguard-applications/17552/en-zhtw#3860772
You may not have email configured on your device.
-> You may not have an email account configured on your device.

2. You changed some English phrases in different projects on Crowdin, but you didn't disapprove those phrases' translations.
Other translators don't know the changes so they don't fix translations.
For me, I need to spend time on checking all of your records of changing English phrases on Crowdin, which is inconvenient.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/hFCVIOV.png)
</details><br/>

**Comment by ameshkov** [comment]
@aalpatkina @08kovalchuk03 please take a look at this as well: https://github.com/AdguardTeam/AdguardForiOS/issues/1382
