### ISSUE TITLE
Optimal IOS Filiter Settings

### ISSUE THREAD

**Issue by Masterj2700** [AdguardTeam/AdguardForiOS#143]
Could some users recommend what filters and blockers they have switched on for IOS for optimal speed and performance?

**Comment by worldsdream** [comment]
Enable english filter, spyware filter, safari filter. 

Which country specific websites do you visit?

**Comment by xxcriticxx** [comment]
easylist? yes or no?

**Comment by Alex-302** [comment]
No, if English filter is enabled.

**Comment by xxcriticxx** [comment]
ok i guess this answers this https://github.com/AdguardTeam/AdguardForiOS/issues/147

what about easylist privacy?

**Comment by ameshkov** [comment]
> what about easylist privacy?

It overlaps with Adguard spyware filter. Although both are pretty good, it'd better to choose one. The difference is that spyware filter maintained by us while easyprivacy is maintained by easylist guys.
