### ISSUE TITLE
When Pro license is purchased and system protection is disabled show helper label on activity screen

### ISSUE THREAD

**Issue by 08kovalchuk03** [AdguardTeam/AdguardForiOS#1450]

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/adc09847-7fa9-43c2-8fce-53a84eddee65?

May be something like this? "Turn it on" led user to "System protection" screen

**Comment by ameshkov** [comment]
@AlikhanAliev no, this is a different case.

When System protection is disabled and you navigate to "Activity", we should show a placeholder.

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/b238e01f-1322-4aec-90fa-6413770d53a5?
