### ISSUE TITLE
BETA: Statistics Resets when Clicking “Update” in AdGuard 4.0(320)

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#1453]
Steps to Reproduce:

1. Open AdGuard.
2. Notice the statistics numbers.
3. Click “Update” or Refresh button.
4. Statistics resets to 0 and counts again.

Expected:

The statistics should not reset but only adds to the counts.

Pictures:

![BFBFFAE6-E4ED-4663-ACCF-855CA26890CF](https://user-images.githubusercontent.com/27464836/73069040-d1c32b00-3f00-11ea-8737-2b65b1623952.png)
![4FE425A2-EBBD-4C26-8C7D-BCCD07EFCBA6](https://user-images.githubusercontent.com/27464836/73069041-d25bc180-3f00-11ea-9e07-8b0dd7fd3977.png)

**Comment by zzebrum** [comment]
@zznosar last-minute fixes leads to more bugs, yay! thank you!

**Comment by zznosar** [comment]
@zzebrum i’ll report back if I see other issues or bugs. I’m currently testing in an older iPhone. Will test next in iPad. ✌🏻✌🏻✌🏻
