### ISSUE TITLE
BETA: Missing Share Options in AdGuard 4.0(320)

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#1455]
The Share Options is no where to be found in the app. Was it removed in this version?

The previous version can be shared using Facebook, Twitter and Messaging.

Is this a bug? Or is it located somewhere now?

**Comment by SoLenny** [comment]
It isn't a bug. We did it on purpose.
So far the share button will be absent, but its fate is still being decided.

**Comment by zznosar** [comment]
Thanks!

**Comment by zznosar** [comment]
Other testers might encounter this issue. We just need to let them know that this is a change in design! @SoLenny
