### ISSUE TITLE
BETA: Protocol Selection Not Saving in AdGuard 4.0(320)

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#1456]
Steps to Reproduce:
1. Open AdGuard
2. In System Protection, Select a third party DNS. E.G AdGuard DNS.
3. Select a different Protocol. E.G DNSCrypt.
4. Click the < (Back) button on the top.
5. Error message saying Changes Were Not Applied.

Expected:
The change should automatically save.
In version 3.1, it is save automatically.

Pictures:
![7EA5643D-D9F9-4596-8BFC-8A0F048A3E0F](https://user-images.githubusercontent.com/27464836/73070719-2d8fb300-3f05-11ea-9bb8-1796d0e26302.png)
![C6FF20DD-94FD-4357-ADB6-546ED77266F8](https://user-images.githubusercontent.com/27464836/73070720-2d8fb300-3f05-11ea-9f74-cbf75e7ddbb1.png)
![571000BF-56B5-4978-8805-06E9F2AEE585](https://user-images.githubusercontent.com/27464836/73070721-2e284980-3f05-11ea-9056-d3f8cd7093ce.png)

**Comment by SoLenny** [comment]
It isn't a bug. We did it on purpose.  
To save your changes click on the "Select" button after selecting the protocol. (it is in the lower left corner)

**Comment by zznosar** [comment]
Ok thanks.

**Comment by zznosar** [comment]
Other testers might encounter this issue. We  just need to let them know that this is a change in design! @SoLenny

**Comment by zzebrum** [comment]
@zznosar you are right. we can add this information to error message or consider some design changes if this situation raises questions.
