### ISSUE TITLE
BETA: Filtering Log incorrectly reports the filter used in Blocking for AdGuard 4(320)

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#1457]
Steps to Reproduce:
1. Open AdGuard
2. Add other third party filters in System Protection.
3. Disable AdGuard SDN filter in the list and only enable the third party. In my case, i enabled AdAway filter.
4. Check an app that has ads like Yahoo Mail.
5. Open AdGuard again and check the fliter logs.
6. Notice that the logs says AdGuard SDN filter even though it is disabled. 

Expected:
Should show the correct filter in the Log. The same as AdGuard Pro 2.1

Pictures:

AdGuard 4(320)

![8CA54313-A000-46B5-AF7E-55748E84CA7C](https://user-images.githubusercontent.com/27464836/73117747-49936300-3f9e-11ea-9cad-1359fc53416b.png)
![C05F6E37-DAE8-46D6-8F99-5393FC45635A](https://user-images.githubusercontent.com/27464836/73117748-49936300-3f9e-11ea-8177-a7d1e1899a3f.png)

AdGuard Pro 2.1

![B6FCA2F7-586C-4960-8A85-EDAE0FBDB3D2](https://user-images.githubusercontent.com/27464836/73117779-e81fc400-3f9e-11ea-9e0a-1fc06b226d10.png)
![ECCDD50A-3706-40C9-B650-93D14D5C6E60](https://user-images.githubusercontent.com/27464836/73117780-e81fc400-3f9e-11ea-8441-f0573cc7c083.png)

**Comment by SoLenny** [comment]
Duplicate https://github.com/AdguardTeam/AdguardForiOS/issues/1441
