### ISSUE TITLE
The improvement of activity log of v4.0.0 (320) beta.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1458]
1. In v4.0.0 (320) beta, it'll directly clear records of activity log after clicking clear.
I hope it'll show the dialog first, such like AG Pro for iOS v2.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/KR3BId0.jpg)
</details><br/>

2. Under dark mode, the colorful expressions for blacklisted, trackers and whitelisted requests are too dark.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/A6nmsvS.jpg)
</details><br/>

It's ok under light mode.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/vLHhAi0.jpg)
</details><br/>

I think users reported the same issue of dark mode about AG for Android.
If you use light colors of red, yellow and green, the appearance under dark mode will look better.

Otherwise, I more prefer the expressions of AG Pro for iOS v2.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ahl1e7I.jpg)
</details><br/>

**Comment by ameshkov** [comment]
The activity section will be changed a lot compared to what we have there now, consider the current implementation temporary.
