### ISSUE TITLE
1

### ISSUE THREAD

**Issue by lcwrxx** [AdguardTeam/AdguardForiOS#1460]
`<!--`  As an open-source project with a dedicated but small maintainer team, it can sometimes take a long time for issues to be addressed so please be patient and we will get back to you as soon as we can.
-->

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Comment by SoLenny** [comment]
@lcwrxx Hello, can you please describe your problem?
