### ISSUE TITLE
DNS Filters Issue

### ISSUE THREAD

**Issue by shad0whawk** [AdguardTeam/AdguardForiOS#1461]
I’m running the latest 4.0 beta on iOS 13.3. I’ve tried the following on both an iPhone 11 Pro and an iPhone 8. I’ve enabled system-wide DNS filtering using the Adguard DNS server. I’ve also added several filters under the DNS Request Blocking tab. If I enable more than a couple it prevents the DNS service from starting. It shows enabled in AdGuard but it’s shows not connected in the System VPN Settings. If I press “not connected” it shows as trying to connect and then reverts back to “not connected”.  If I disable the custom filters, it turns in fine. Is there a size or rule number limit for this feature?  A few small lists work fine but after that it fails. FWIW, this same exact behavior happens on the older AdGuard Pro app.

**Comment by SoLenny** [comment]
@shad0whawk Hello, to troubleshoot this issue, we need to get the app logs.
Here’s what we need you to do:
Reproduce the issue (and remember the exact time when it happened).
Open the app, tap “Send Feedback”, select “Contact Support”
The mail app will be opened, change the recipient to apple@adguard.com (!)
Mention this issue number in the email text.
Also please specify which filters do you use?

**Comment by shad0whawk** [comment]
Just sent it after enabling only a single filter that caused the issue probably due to size.

**Comment by SoLenny** [comment]
@shad0whawk Thx, we've got your logs.

**Comment by SoLenny** [comment]
@shad0whawk unfortunately, nothing is clear from the logs. Could you give links to custom DNS filters that you use?

**Comment by shad0whawk** [comment]
Here are a couple of the bigger ones. Add and enable them and then try turning on the DNS. I can add more but trying the first one by itself seems to cause the issue typically. 

https://raw.githubusercontent.com/EnergizedProtection/block/master/ultimate/formats/hosts

https://raw.githubusercontent.com/EnergizedProtection/block/master/porn/formats/hosts

https://raw.githubusercontent.com/EnergizedProtection/block/master/extensions/regional/formats/hosts

**Comment by SoLenny** [comment]
@shad0whawk Hello. We have limitations from Apple, 15 MB of RAM can use the tunnel. And your first filter weighs 27 mb, so we can’t use it in any way. We will make a special warning for files that are too large.

**Comment by SoLenny** [comment]
https://github.com/AdguardTeam/AdguardForiOS/issues/1474
