### ISSUE TITLE
"Activity" log changes

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1462]
### General changes

* Trim the trailing dot from the domain name.
* Make sure that DNS answer uses "short" format (`A, IPADDR`) instead of the full DNS answer

### List of records

When it's possible, print the tracker name.

Here's how it should look like in the simple mode:
```
Google Analytics
example.org
```

If we don't know what tracker it is, just print the domain name:
```
example.org
```

In the developer mode keep the current UI:
```
example.org
A, 127.0.0.1
```

### Details screen

First of all, change the order of the fields in the log record details.

```
### Tracker details
* Category
* Name
* Company

### General
* Domain
* Status
* Time
* Size (Developer mode only)
* Elapsed (Developer mode only)

### DNS (Developer mode only)
* Type
* DNS status
* DNS upstream
* DNS answer
```

**Comment by 08kovalchuk03** [comment]
https://app.abstract.com/projects/2b264260-c732-11e8-a52a-07ba12563bc0/branches/11c2f816-a79f-4d44-9b26-3caee7273f88/commits/eb82feb4d3e7fc20ebc39b05e65928d52e9fd17c/files/0B986117-1199-42D4-99B7-06AE1C613873/layers/5A7DB8E1-D053-479F-B395-E54F15C49831

**Comment by ameshkov** [comment]
Issues with the current implementation:

* Missing English translations for the strings
* In the list of records you should use tracker name, not company
* When developer mode is off, "DNS" header should be hidden as well
* Type: A --> Type: A (IPv4), Type: AAAA --> Type: AAAA (IPv6)
* Something wrong happens if I do the following:
    * Enable developer mode 
    * Go to some log record details
    * Go to settings, disable developer mode
    * Switch back to "Activity"
    * The layout will be broken, some items will still be hidden

**Comment by ameshkov** [comment]
And a couple more things:

* If the information about tracker comes from AdGuard, don't show the "help" tooltip
* Add "Website" record to the tracker details (show it with and without developer mode)

**Comment by ameshkov** [comment]
I don't see the "Website" item
I see an extra bottom border in the tracker details group: https://uploads.adguard.com/up04_7q7i3_Monosnap.png

**Comment by ameshkov** [comment]
There's one more change that is required.

1. Add a new section "FILTERING" and place it next to "GENERAL"
2. Move "Status" there
3. Add fields "Filter" and "Rule"
    * "Filter" should contain the name of the filter that matched the DNS query
    * "Rule" should contain the rule that matched the DNS query
    * If no rule matches the query, do not print "Filter" at all, and print "No rule found" in the "Rule" cell
    * If the query is matched by a rule from the "System Blacklist" or "System Whitelist", don't forget to print it in the "Filter" cell
4. This section should be visible in both regular and developer mode
