### ISSUE TITLE
easylist filters 

### ISSUE THREAD

**Issue by xxcriticxx** [AdguardTeam/AdguardForiOS#147]
i have easylist selected my active filters counter shows only 26595 filters enabled. i think it should be somewhere around 65000 filters? i know i read something about safari limit does this apply here?

**Comment by ameshkov** [comment]
Hi!

I advise you to read this discussion:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/230

There is a detailed description of filters optimization applied by Adguard.
