### ISSUE TITLE
The interface is not optimized for ipad

### ISSUE THREAD

**Issue by minsk21** [AdguardTeam/AdguardForiOS#1473]
The interface is not optimized for ipad.  Large and stretched interface elements.
<details>

![IMG_1358](https://user-images.githubusercontent.com/26014600/73401336-0158a580-42fc-11ea-92b1-c8877f7c1f61.png)

![IMG_1359](https://user-images.githubusercontent.com/26014600/73401352-0a497700-42fc-11ea-8d45-f1ad43e207f9.png)

![IMG_1361](https://user-images.githubusercontent.com/26014600/73401366-0e759480-42fc-11ea-8dc0-c9f09f908882.png)

</details>

Adguard 4.0.0 (320)

**Comment by ameshkov** [comment]
Ну вот проблематично что-то менять - в приложении просто нет контента, чтобы забить свободное место.

Так что главный экран останется примерно таким же.
Экран "Защита" мы еще будем дорабатывать.

Двух-колоночный интерфейс возможен, но сильно позже.
