### ISSUE TITLE
Wi-Fi exceptions still enabling VPN on trusted Wi-Fi

### ISSUE THREAD

**Issue by seanob86** [AdguardTeam/AdguardForiOS#1475]
- **AdGuard version:**
  Test Flight Beta v4.0.0 (346)
- **Device model and storage size:**
  iPhone 11 Pro 256GB
- **Operating system and version:**
  13.3.1

### Expected Behavior

- Enable System Protection in Adguard Settings > Successful

- Create Wi-Fi Exception > successful. 

- Connect to the SSID that was added as an Exception > successful.

- If AdGuard VPN was previously enabled, VPN should now disable because we have connected to the SSID that was previously added as an Exception > successful

### Actual Behavior

- Enable System Protection in Adguard Settings > Successful

- Create Wi-Fi Exception > successful. 

- Connect to the SSID that was added as an Exception > successful.

- If AdGuard VPN was previously enabled, VPN should now disable because we have connected to the SSID that was previously added as an Exception >  **UNSUCCESSFUL**

### Additional Information

The SSID which I added has the following characters in the SSID - ' _ (Apostrophe and underscore). Perhaps that could be the issue but haven't had a chance to test on WiFi without special characters)

FYI - Tunnel mode is set to Full-Tunnel.

I can provide logs from the app if required. Please advise and if so how I can send them.

**Comment by zznosar** [comment]
That’s weird. I tried recreating this and i can’t

VPN is disabled when i am connected to the wifi i included in the exemption. 

Pics below:
![631C5A85-8EA8-4B1F-9B07-D257FA19D478](https://user-images.githubusercontent.com/27464836/73497087-11f94080-440e-11ea-97f6-68bb2faa440e.png)
![D72AFF62-364B-4221-880C-05A5A6CCD674](https://user-images.githubusercontent.com/27464836/73497088-1291d700-440e-11ea-8468-3f70c3691906.png)
![D1C5E915-A8A1-469E-81AB-1A685A4C238E](https://user-images.githubusercontent.com/27464836/73497090-1291d700-440e-11ea-8236-bdcb5beb6286.png)

**Comment by seanob86** [comment]
I have tested with an SSID that has letters, numbers and a `-` and the wi-fi exception is working.
As per my original comment it is **NOT** working with the following special characters `'` and `_` in the SSID name. So it's either one of those characters which is causing the issue or both.

I don't have this issue where setting trusted wifi's on other VPN apps where I use the same WiFi SSID with `'` and `_`.

Also another observation. When the WiFi is trusted but the VPN indicatior is not shown in the top menu bar, in Settings > VPN it is still shown as connected. In other apps (that offer the same feature) the VPN is disconnected when the Wi-Fi is trusted. See screenshots below. The last screenshot is where the WiFi is trusted but VPN is disconnected (Windscribe VPN app).

![IMG_3308](https://user-images.githubusercontent.com/45988261/73500828-ab4b3700-43bb-11ea-801a-ba33fbf04cd5.jpeg)

![IMG_3309](https://user-images.githubusercontent.com/45988261/73501052-5eb42b80-43bc-11ea-96a5-7247984ad9c8.jpeg)

**Comment by zznosar** [comment]
Understood.

For your other observation, its probably because of the Full Tunnel mode setting? In full tunnel mode, you can’t have two VPN’s at the same time so this impacts the others? Maybe AdGuard team can provide more details about it if its an iOS bug or an Application bug.

This version however is more stable than the initial beta.

**Comment by seanob86** [comment]
> For your other observation, its probably because of the Full Tunnel mode setting? In full tunnel mode, you can’t have two VPN’s at the same time so this impacts the others?

I didn’t have any other VPN’s connected, plus in the screenshots in my last comment I changed to split tunnel mode. The windscribe VPN screenshot was just an example of how the status of the VPN should be when connected to a trusted Wi-Fi.

**Comment by seanob86** [comment]
Looks like in latest beta, VPN is disconnected (in Settings -> VPN) if network is trusted in Settings > VPN. So that is now fixed 👍

However, app will not trust WiFi if there are special characters in the SSID name. For example I have trusted my Home WiFi, which is `O’Brien_Home`, but AdGuard will still enable VPN even though WiFi is trusted.

**Comment by seanob86** [comment]
@zzebrum Can this be re-opened? Not sure why it was closed as only one of two issues reported was resolved. Refer to my previous comment.

> However, app will not trust WiFi if there are special characters in the SSID name. For example I have trusted my Home WiFi, which is O’Brien_Home, but AdGuard will still enable VPN even though WiFi is trusted.

> it is NOT working with the following special characters ' and _ in the SSID name. So it's either one of those characters which is causing the issue or both.

**Comment by IvanIin** [comment]
@seanob86 
We tried to reproduce this error unsuccessfully. Maybe you use different `'` characters in the Wi-Fi SSID and in AdGuard exceptions? In your comment, I see two different ones: `'` and `’`

**Comment by ameshkov** [comment]
@IvanIin let's do a simple thing - when the user tries to add a new Wi-Fi exception, we should fill the input with the current network's SSID.

**Comment by seanob86** [comment]
I have re-installed the app now since it can’t be reproduced on your end. I copied the SSID via the shortcuts app action to get the SSID exactly how the OS sees it and then copy to my clipboard. Anyway.. short story it work now but I agree with the previous comment that there should be a way for the app to automatically get the current wifi ssid and directly input that into the settings.
