### ISSUE TITLE
user filter error 

### ISSUE THREAD

**Issue by xxcriticxx** [AdguardTeam/AdguardForiOS#148]
`||fntajkb.wp.pl^` yesterday i had this filter working on iso 9.3.5 iphone 6

today i am getting error 

Filters cannot be loaded into Safari. Therefore, you recent changes were not applied.

why?

**Comment by ameshkov** [comment]
Which filters do you have enabled in AG?

I don't think the issue is caused solely by this rule, something else is responsible.

**Comment by xxcriticxx** [comment]
filters i have on:
english, spyware, social media, annoyances, mobile ads, safari, easyprivacy, anti-adblock filters 

filters i had to turn off because my filters wont update:
adblock polskie reguly, adblock polskie reguly cookies

**Comment by ameshkov** [comment]
@gshumihin please check what rule breaks converter (again).

**Comment by ameshkov** [comment]
@xxcriticxx the issue is fixed in Safari extension v2.4.10 and in AG for iOS beta version.

**Comment by xxcriticxx** [comment]
how to get beta version to test?

**Comment by ameshkov** [comment]
Here it is:
https://forum.adguard.com/index.php?threads/adguard-for-ios-beta-test.6344/
