### ISSUE TITLE
Surplus UI. Please delete the tab of protection in v4.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1482]
Surplus UI. Please delete the tab of protection in v4.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/E6LGc4Z.jpg)
</details><br/>

1. Try moving the mechanisms of enabling/disabling Safari or system protection in the home tab.
- Enable Safari protection but disable system protection.
- Enable system protection but disable Safari protection.
- Enable both Safari and system protection.
- Disable both Safari and system protection.
2. Please delete the tab of protection in v4. It's surplus.
3. Move the descriptions of Safari & system protection in the tab of protection into the tab of menu because Safari & system protection items are also there.

**Comment by lancelot-moon** [comment]
@ameshkov 
How do you think about the mechanisms of enabling/disabling Safari or system protection in the home tab?
They're my suggestions.
Tap the button for enabling/disabling Safari protection.
Turn right/left the button for enabling/disabling system protection.

(You should remove the tab of protection. It's surplus.
Enabling/disabling Safari /system protection should be done in the home tab.)
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/IJjNBJV.jpg)
</details><br/>

**Comment by lancelot-moon** [comment]
Another thought if you want to keep the tab of protection.
Move Safari & system protection items in the tab of menu into the tab of protection.
I hate many steps for getting into the items which I wish.
Succinct UI is better.

**Comment by zzebrum** [comment]
We will consider this option after the release, when we get more feedback.
