### ISSUE TITLE
Question : does AdGuard dns hide the network traffic from Hotel WiFi’s ?

### ISSUE THREAD

**Issue by F3000** [AdguardTeam/AdguardForiOS#1485]
So does somebody see my opened websites or not like a traditional VPN ?

**Comment by zzebrum** [comment]
@F3000 do you mean any public wi-fi network?

**Comment by F3000** [comment]
@zzebrum  in the end yes

**Comment by Calefornia** [comment]
This doesn’t hide your traffic. You’d need an actual VPN or Tor. Adguard’s DNS is only to setup the connections to a web server. The wifi can still see what servers and sites you visit, unless you encrypt your traffic with a VPN or Tor.

**Comment by zzebrum** [comment]
@F3000 well, anyway AdGuard can't hide traffic as a traditional VPN does.

**Comment by F3000** [comment]
Witch VPN is working well with AdGuard ? Can you recommend me something ?

**Comment by Calefornia** [comment]
I've had success with ProtonVPN, but I'm sure that others work great. The question I've seen in forums is whether or not your DNS query goes through the VPN's server, or your regular internet, thereby leaking your info. You should look on Adguard forums or other places. I'm not familiar enough to know or to point you towards an answer

**Comment by zzebrum** [comment]
@F3000 there was an issue about compatibility with VPN apps #162 
Probably we will need to recheck all the info there.
