### ISSUE TITLE
Ad Blocking Stats

### ISSUE THREAD

**Issue by Trooper27** [AdguardTeam/AdguardForiOS#1488]
Hi guys not reporting a bug but a request. On the latest iOS beta, is there any plan to add or show the amount of ads blocked? It seems like it is just tracking DNS blocking and not safari blocking. Thanks in advance!

**Comment by zzebrum** [comment]
@Trooper27 Hi there! Unfortunately it can't be done because Safari API doesn't provide such functions :(
