### ISSUE TITLE
Расширение в Safari не работает

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForiOS#1489]
### Issue Details

- **AdGuard version:** 4.0.0 (361)
  
- **Device model and storage size:** iPhone XR
  
- **Operating system and version:** 13.3.1
  
- **Browser or App:** Browser
  

### Expected Behavior

Работает расширение в Safari в меню «Поделиться».

### Actual Behavior

Расширение в Safari в меню «Поделиться» не работает.

### Screenshots

<details><summary>Screenshot:</summary>

![49CE9E30-9908-4353-A2A3-231FDDAF8627](https://user-images.githubusercontent.com/19418601/73765104-1febf000-4785-11ea-8ed3-14ec3e4e25a9.png)

</details>

**Comment by zzebrum** [comment]
@Rakleed а сможете логи отправить на apple@adguard.com с указанием времени? у меня не повторяется чего-то. А вообще еще одну бету чуть попозже опубликуем, там еще можно будет проверить.

**Comment by Rakleed** [comment]
@zzebrum после обновления до билда 367 проблема не повторяется.
