### ISSUE TITLE
adguard pro add new list 

### ISSUE THREAD

**Issue by xxcriticxx** [AdguardTeam/AdguardForiOS#149]
how do i add new user filter list to my iphone?

**Comment by ameshkov** [comment]
You mean a whole filter or just a filter rule?

**Comment by xxcriticxx** [comment]
Whole filter list

**Comment by ameshkov** [comment]
You can only enable filters from a pre-defined list, there is no way to import a third-party filter in iOS.

**Comment by xxcriticxx** [comment]
any plans for the future?

**Comment by ameshkov** [comment]
Yep, I suppose we will allow custom filters installation in future.
