### ISSUE TITLE
It should be possible to block a domain even if it's whitelisted by a filter list

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1491]
There are situations where a domain is whitelisted by a rule like this: `@@||www.googleadservices.com|` coming from AdGuard SDNS filter. Just in case, the reason for this particular rule is to not block "click-through" URLs in google search results.

Anyways, it must be still possible to block this URL via the interface.

In order to do this, the rule that you add should have the `$important` modifier:
`||googleadservices.com^$important`

Also, when a blocking rule from the filter list has this `$important` modifier, the only way to unblock the URL is to add it as well:
`@@||example.org^$important` 

Therefore, it makes sense to add this modifier to all custom whitelist rules.

The only situation when it is not possible to block a domain is when a whitelist rule from the filter list has this `$important` modifier.

## Summary

1. Allow blocking domains that are whitelisted by a filter list -- add `$important` modifier in this case.
2. Add `$important` modifier to the rules created by the "System Whitelist"
3. Consider the case when the whitelist rule from a filter list has `$important` modifier

**Comment by bigdargon** [comment]
Does this mean rule ` @@||example.com^| ` will no longer work?  And will rule ` @@||example.com^| ` be replaced by `@@||example.com$important ` in the filter to work on version 4.0?
