### ISSUE TITLE
DNS diesen work with freenet funk as a Provider 

### ISSUE THREAD

**Issue by F3000** [AdguardTeam/AdguardForiOS#1493]
More information you can find here : 
https://freenet-funk.de/

The DNS always reconnects . With beta 4 I have made an exception for my hotspot WiFi (where the Freenet sim is in)

**Comment by zzebrum** [comment]
@F3000 does it work with the default DNS server?

**Comment by F3000** [comment]
Yes when I connect without the adguard vpn it works

**Comment by zzebrum** [comment]
And what if you choose the default server in AdGuard app?

**Comment by F3000** [comment]
You mean the standard system DNS in in AG settings ?

**Comment by zzebrum** [comment]
@F3000 yes
