### ISSUE TITLE
Maybe modify a phrase for reporting issues?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1496]
https://crowdin.com/translate/adguard-applications/17552/en-zhtw#3905510
Report incorrect blocking
-> Report filters issues

**Comment by ameshkov** [comment]
I think it's easier to understand for people what "incorrect blocking" means. Some of them have no idea what filters are.

**Comment by lancelot-moon** [comment]
There are 5 kinds of filters issues on web reporting tools:
Missed ads, incorrect blocking, social media elements...etc.

I know your point, but I also don't think that using "Report incorrect blocking" is a good idea.
Some users may want to report missed ads.
They may feel confused and not click "Report incorrect blocking" because they actually want to report missed ads.
