### ISSUE TITLE
Not displaying correctly the page

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1497]
**Issue Details**

AdGuard version: 4.0.0 (373) with AG DNS (DNScrypt)
Device model and storage size: iPad 11 Pro
Operating system and version: 13.3.1
Browser or App: [MacHash](https://apps.apple.com/us/app/machash-news/id407673940)
Topic: https://ww.9to5mac.com/2020/02/07/databases-that-track-millions/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+9To5Mac-MacAllDay+%289+to+5+Mac+-+Apple+Intelligence%29#

**Expected Behavior**
Displaying correctly the page. 

**Actual Behavior**
The page is correctly displayed for 1 second then it is been cropped. 
After testing each filter I found out the DNS was the source of the problem. Don't know how to solve the problem. 

**Video**
https://www.swisstransfer.com/d/898d6999-df9e-428a-83fa-19b27ca52136

**Comment by zzebrum** [comment]
@Quorum75 what other settings do you have enabled?
Is the problem reproducible with other AdGuard DNS type? or with any other DNS provider?

**Comment by Quorum75** [comment]
Same issue with any type. However I cannot reproduce the problem with other provider today, neither with AG. So don't what happened or changed between yesterday and today. Will close it. Thanks.

**Comment by zzebrum** [comment]
It is ok on my side too :)
