### ISSUE TITLE
System protection completly blocks connection on some wifi networks

### ISSUE THREAD

**Issue by 08kovalchuk03** [AdguardTeam/AdguardForiOS#1499]

**Comment by 08kovalchuk03** [comment]
https://ncloud.adguard.com/remote.php/webdav/Support/Issues/iOS/1499/adguardforios_logs_41022020152.zip

**Comment by Chinaski1** [comment]
Logs added to NCloud
Time: 15:26-15:27/10.02.2020

**Comment by Marco224** [comment]
Hi!
On my side the problem has only been partially solved by updating to version 381 of AdGuard for iOS.

Now under Wi-Fi internet connection it works correctly, but it completely blocks the connection when disconnecting from it, when switching to mobile networks. The only solution is to activate and deactivate the airplane mode

**Comment by zzebrum** [comment]
Hi @Marco224! Can you please reproduce the issue,  collect log files and send it to apple@adguard.com ?

**Comment by Chinaski1** [comment]
@zzebrum 
I transferred log files to @08kovalchuk03

**Comment by zzebrum** [comment]
@Chinaski1 the new one?

**Comment by Marco224** [comment]
I also sent the log to apple@adguard.com (16:45-16:46)
