### ISSUE TITLE
[PRO] Random notification sounds 

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForiOS#150]
Check the [forum thread](https://forum.adguard.com/index.php?threads/adguard-%D0%9F%D0%A0%D0%9E-%D0%B4%D0%BB%D1%8F-ios-%D0%9F%D1%80%D0%BE%D0%B8%D0%B7%D0%BE%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%B7%D0%B2%D1%83%D0%BA%D0%BE%D0%B2%D1%8B%D0%B5-%D0%BE%D0%BF%D0%BE%D0%B2%D0%B5%D1%89%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B2-%D0%BF%D0%BE%D1%87%D1%82%D0%B5.13750/) for description

**Comment by gshumihin** [comment]
Wasn't able to reproduce this isuue.
