### ISSUE TITLE
The text is cover I can’t see the date or time

### ISSUE THREAD

**Issue by tenbad** [AdguardTeam/AdguardForiOS#1500]
i am using the latest version app, since half years ago, the date or time that show when I updated the filter, always cover by unknown reason, can u fix that?
![B2793087-B803-4FFC-A536-7B812CFA76C3](https://user-images.githubusercontent.com/35102165/74415261-fcf4c680-4e7d-11ea-8b36-b742fbd91c99.jpeg)

**Comment by zzebrum** [comment]
We will eventually fix this when the app gets the update with all AdGuard Premium functions.
