### ISSUE TITLE
Cannot Connect To The Wifi

### ISSUE THREAD

**Issue by 11Rick23** [AdguardTeam/AdguardForiOS#1503]
Hi. I'm using AdGuard Pro for a long time, and I really love it!

However, it seemed to me that there's a WiFi connection issue when trying to connect to a WiFi with the AdGuard VPN on.

Please check the screenshots attached.

Also, I tried restarting, quitting the app, turning VPN on and off, changing tunnel mode, changing DNS, etc.

Please help me!

![95320571-50BF-40CD-BE0C-6B67F7F710AE](https://user-images.githubusercontent.com/48012047/74564727-b6ff3780-4f3d-11ea-8bab-6c5afffb3451.jpeg)
![2F24D8A2-DF59-44F8-87BA-7BFF6A301FDD](https://user-images.githubusercontent.com/48012047/74564728-b797ce00-4f3d-11ea-8acc-cc3dfbc8f1e8.jpeg)
![95A1A20B-0E45-427E-8F35-55E78C715A79](https://user-images.githubusercontent.com/48012047/74564729-b797ce00-4f3d-11ea-9e6f-956417ef4109.jpeg)
![CA2BF86C-C4E6-42E3-AD04-F6052F51811A](https://user-images.githubusercontent.com/48012047/74564730-b8306480-4f3d-11ea-9fad-b40d328b8b97.png)

**Comment by SoLenny** [comment]
@11Rick23 Hello, in the near future the pro version will be completely redesigned.  
When the update will available, most likely your problem will be solved, and even if not, we will definitely return to it.

**Comment by SoLenny** [comment]
@11Rick23 Would you like to try the beta version of our second program AdGuard -adblock&privacy? Everything should work well there :)

**Comment by lancelot-moon** [comment]
@11Rick23
Choose AG for iOS there.
https://surveys.adguard.com/beta_testing_program/form.html

**Comment by 11Rick23** [comment]
Thank you so much!
I'll try the beta version, thank you!
