### ISSUE TITLE
System Protection and Aloha Browser

### ISSUE THREAD

**Issue by specter78** [AdguardTeam/AdguardForiOS#1505]
- **AdGuard version:**
AdGuard for iOS v4 (373)
- **Device model and storage size:**
iPhone 11
- **Operating system and version:**
iOS 13.3.1
- **Browser or App:**
Aloha Browser

### Expected Behaviour

System protection on.
Either system protection should work along with aloha vpn.
Or, when aloha vpn disconnects, system protection should reenable automatically.

### Actual Behavior

System protection on.
On using aloha vpn, system protection disables.
On disconnecting aloha vpn, system protection remains disabled.

**Comment by SoLenny** [comment]
@specter78 Hello. Unfortunately we can’t do anything with that. The VPN that you turned on last will work.
