### ISSUE TITLE
Widget doesn’t work

### ISSUE THREAD

**Issue by AliusX** [AdguardTeam/AdguardForiOS#1506]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

AdGuard for iOS v4.0.0 (373)
iPhone 7 (128 GB)
iOS 13.3.1

### Expected Behavior

Widget showing status

### Actual Behavior

Widget showing “not possible to load”

### Screenshots

![2C04226A-90F1-4E9F-B9AD-48B7F7974516](https://user-images.githubusercontent.com/51243093/74816037-9f87cc00-52fa-11ea-8654-d51cbd130a4a.jpeg)

**Comment by lrevenden** [comment]
I’m having this issue too. I am running the latest Adguard beta and the latest iOS public beta

**Comment by zzebrum** [comment]
guys, is the issue reproducible on the latest v4.0.0(390) from Testflight? If so, please, collect logs and send it to apple[at]adguard[dot]com

**Comment by AliusX** [comment]
@zzebrum: done.

**Comment by AliusX** [comment]
reproducible on v4.0.0 (396)

**Comment by tomacco81** [comment]
Reset statistics seems to be a workaround to restore the widget.

**Comment by AliusX** [comment]
I tried, but with no success. 🤔

![575B0440-CEC4-4AED-8982-71DF8C40A3D0](https://user-images.githubusercontent.com/51243093/77041687-a4ec3b00-69ba-11ea-89e3-eca58415a24d.png)

![0BF6E899-0A14-4D4F-84AB-B2F17D4B78E7](https://user-images.githubusercontent.com/51243093/77041693-a74e9500-69ba-11ea-85cd-286b069d61d2.jpeg)

**Comment by tomacco81** [comment]
I always reinstalled the app when the problem occurred. Now I have reset the statistics and closed the app. A long press on the app icon displayed the widget correctly again and it worked in the today view as well. I will test this again if the problem occurs again.

**Comment by zzebrum** [comment]
anyone, please, collect logs and send it to apple[at]adguard[dot]com again! Thanks a lot!

**Comment by AliusX** [comment]
Yaey! 4.0.0 (415) did it!

**Comment by IvanIin** [comment]
@AliusX, please send us the logs. They will help us figure out what the problem was.

**Comment by zznosar** [comment]
It’s broken again the in the current build. Can others check?

**Comment by AliusX** [comment]
For me it’s working. I will send you the logs so you can have a look inside.
Stay healthy!

**Comment by zzebrum** [comment]
@zznosar reproduce the problem and send logs to apple[at]adguard[dot]com thanks a lot!

**Comment by ameshkov** [comment]
@zznosar was it working before?

**Comment by AliusX** [comment]
With the update before it worked again, and it still does.

**Comment by zznosar** [comment]
It was working on the previous build. I will try to reinstall it from scratch and see if it will work.

**Comment by tomacco81** [comment]
The problem occurs again in the latest build.
Unfortunately I cannot send the logs, because Google recognizes the attachment as a virus :(

**Comment by tomacco81** [comment]
After the problem occurred again, I disabled the protection and reset the statistics. After that the widget worked again
