### ISSUE TITLE
VPN suddenly turns off in background

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForiOS#1508]
### Issue Details
The System Protection suddenly turns off in the background and I notice the VPN icon is missing. Going into AdGuard, only Safari Content protection is enabled.

- **AdGuard version:**
  - 4.0.0(381)
- **Device model and storage size:**
  - iPhone 11 64GB
- **Operating system and version:**
  - 13.3.1

### Expected Behavior
System Protection remains enabled in the background

### Actual Behavior
System Protection disables in the background, VPN turned off

### Additional Information
VPN is set to full-tunnel mode. Only thing enabled for system protection is AdGuard DNS Filter, System Default DNS as well.

**Comment by SoLenny** [comment]
@planet0 Hello. To troubleshoot this issue, we need to get the app logs.
Here’s what we need you to do:
Reproduce the issue (and remember the exact time when it happened).
Open the app, tap “Send Feedback”, select “Contact Support”
The mail app will be opened, change the recipient to apple@adguard.com (!)
Mention this issue number in the email text

**Comment by ameshkov** [comment]
I actually have had the very same issue, and it seems to be happening right after updating the app.

@IvanIin please find the logs are in the nextcloud

**Comment by TimofeyK** [comment]
I think I had the same issue several times with beta 381. I suspect it happened after filters were updated in the background because the requests log showed the last address filters.adtidy

Actually, Pro version had another issue where all requests would start returning “no response” and my observation was it happened after background filter update

**Comment by SoLenny** [comment]
@TimofeyK Thanks for the information! We are already dealing with this problem.
