### ISSUE TITLE
Can’t type / in Blacklist (Privacy Settings)

### ISSUE THREAD

**Issue by jonathanMNg** [AdguardTeam/AdguardForiOS#1509]
I’m using Adguard Pro v2.1.2 on iPhone 6 12.4.4

In the blacklist filter rules (Privacy Settings -> Blacklist/Whitelist), whenever I tried to type ‘/‘ it does not shown on both Blacklist and Whitelist doesn’t matter how many times I tried to type it. I’m able to type all other characters.

However, I’m able to type it on Safari Content Blocking -> User Filters.

I also tried to copy and paste, but the character / just doesn’t show.

**Comment by lancelot-moon** [comment]
Blacklist/Whitelist is for DNS filtering.
Only domain name format is accepted.

**Comment by jonathanMNg** [comment]
> Blacklist/Whitelist is for DNS filtering.
> Only domain name format is accepted.

How am I supposed to block the whole ling and not just the domain?
For example https://example.com/services/ads*
I tried to use Subscription to add my filter rules file, but it doesn’t seem to work.

**Comment by lancelot-moon** [comment]
Impossible on iOS locally.
With HTTPS filtering by Safari content blocker or AdGuard for Android, you can add rules for full URL.
For DNS filtering, only domains.
The system-wide blocking of AG Pro merely has DNS filtering.
The system-wide blocking of AG for Android has both HTTPS filtering and DNS filtering.
You can abandon iOS and go to use Android if you wish system-wide HTTPS filtering.

**Comment by SoLenny** [comment]
@jonathanMNg Hello, @lancelot-moon  is completely right, unfortunately, we cannot block URLs, only domains.
