### ISSUE TITLE
Pro disables Speedify

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#151]
Your VPN completely disabled Speedify. Is there any way you can change your VPN location from VPN configurations section to the Personal VPN section in iOS 10 ? Outside of that I noticed Skype dropped a call instantly after installing Adguard Pro. That may be just a glitch or the switch over to Adguard Pro but I didn't have that issue with Speedify or Cloak VPN dropping Skype calls during initial run.

ID: 1411818

**Comment by ameshkov** [comment]
The skype calls issue looks like a glitch.

What for second question: this is the restriction of a VPN API. Only one VPN is allowed at the given time.
