### ISSUE TITLE
iOS Widget - Unable to load 

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1510]
**AdGuard version:** 4.0.0 (381) with AG DNS (DNScrypt)
**Device model and storage size:** iPhone 11 Pro Max 256Go
**Operating system and version:** iOS 13.3.1
**Browser or App:** iOS
**Topic**: Widget

**Expected Behavior**
Displaying correctly information .

**Actual Behavior**
Unable to load

**Screen Shot**
https://postimg.cc/BPx9NLw2

**Comment by zznosar** [comment]
I think this is same?

https://github.com/AdguardTeam/AdguardForiOS/issues/1506

**Comment by Quorum75** [comment]
Correct. Sorry I missed it.
