### ISSUE TITLE
Please align text left in the descriptions of v4 beta.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1511]
I only have iPad Pro.
iPad's big screen can't let me check if you have aligned text left in the descriptions of v4 beta on iPhone.
But I found the tip aligns text center.
Bad looking.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/jZpkozQ.jpg)
</details><br/>

I think you can align text center for titles, but you should align text left in the descriptions.

**Comment by vozersky** [comment]
it's a native alignment, can't be fixed
