### ISSUE TITLE
Dns filter not updating

### ISSUE THREAD

**Issue by rodaimi** [AdguardTeam/AdguardForiOS#1512]
- **AdGuard version:**
  - 4.0.0(381)
 
- **Device model and storage size:**
  - iPhone Xr 128 GB
- **Operating system and version:**
  - iOS 13.3.1
- **Browser or App:**
 

### Expected Behavior

Adguard DNS filters should update automatically or when you pull down on the DNS filters page

### Actual Behavior

You can't update the filter without deleting and re adding the filter everytime. 

Original SDN filter updated on 2/29 can't be deleted.

### Screenshots

<details><summary>Screenshot:</summary>

![070FBF98-4ACD-4A1C-A948-920428744E60](https://user-images.githubusercontent.com/30921610/75850854-428a1c80-5db6-11ea-9301-87a57f916a44.png)
![1FEC3799-CEA4-4392-9FC4-5F9CFCBDEC2F](https://user-images.githubusercontent.com/30921610/75850856-43bb4980-5db6-11ea-9ef9-c4ebaa092f13.png)

</details>

**Comment by zznosar** [comment]
I can’t recreate this. Mine always update when i click the refresh button in the main page.

Its in the upper part - top.

There is no pull to refresh in the Filter page.

If we want pull to refresh, then it should be a feature request and not a bug.

**Comment by rodaimi** [comment]
It looks like the filters started updating again. As with most things, everything starts to work right before you report it.
