### ISSUE TITLE
Wrong perception of the network during VPN mode switching

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForiOS#1514]
### Issue Details

- **AdGuard version:**
  -  4.0.0(381)
- **Device model and storage size:**
  -  iPhone 11 Pro 256gb (European model MWC72ZD/A)
- **Operating system and version:**
  -  13.3.1

### Steps to reproduce

1) In full tunnel mode even when using 4g the phone think it’s WiFi connected (even if WiFi is turned off) 
2) When in split-tunnel mode there’s not this bug.
3) To test it just go to App Store settings and enable auto-play video on WiFi.
4) Test both tunnel mode and you’ll see that when in full tunnel mode video are auto-playing like it’s on WiFi.
5) You can do this also with the Facebook app that has the auto-play video on WiFi too.

> ###  A video that shows the issue in NCloud

### Additional Information

Reported by Timur from Telegram

**Comment by tupac55** [comment]
Hi, I’m Timur from telegram just saw that someone put my issue feedback here and I’ve some additional information about this issue

When in full tunnel without vpn icon, there’s not the issue as in split tunnel mode

So to resume

Split tunnel / full tunnel without vpn icon = no issue with 4g being considered as WiFi connection

Full tunnel = issue with 4g being considered as WiFi connection

**Comment by tupac55** [comment]
Here's a logs files reproduction of the issue tested with the latest adguard build 4.0.0 (415)

https://drive.google.com/file/d/17yxwxfzYfjop29H3So4k9Em2D8dHjnDD/view?usp=sharing

**Comment by IvanIin** [comment]
@tupac55, It all looks like a bug in iOS. We cannot control from a tunnel which network to use, wifi or mobile. The only option in your case is not to use the full tunnel mode with the VPN icon.
