### ISSUE TITLE
Incorrect main switch state

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdguardForiOS#1517]
### Issue Details

- **AdGuard version:**
  - AdGuard v4.0.0 (396)
- **Device model and storage size:**
  - iPhone 8 Plus
- **Operating system and version:**
  - 13.3.1

### Expected Behavior

The button appears correctly when opening the application

### Actual Behavior

Exit the Adguard application that is running in the background from multitasking.  Reopen the Adguard application, the button does not display correctly with the status enabled.

### Screenshots

<details><summary>Screenshot:</summary>

![46257399-B5A3-4E67-BAEF-44B5B8B4F591](https://user-images.githubusercontent.com/10969626/76703870-8f031f80-6707-11ea-9cfd-ca161073083f.jpeg)

</details>

**Comment by zznosar** [comment]
I second this! I see this big as well!
