### ISSUE TITLE
[UI] Add more the color of the switch button

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdguardForiOS#1518]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Add button colors when either of the “Safari protection” or “Tracking protection” features are enabled. So the user knows that the feature is missing.

### Proposed Solution

If either of the “Safari protection” or “Tracking protection” turned on, it shows orange

**Comment by ameshkov** [comment]
@bigdargon well, specifically for that we have two icons -- one for Safari protection, the second one is for Tracking protection.
