### ISSUE TITLE
Wi-Fi exception issue

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdguardForiOS#1519]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v4.0.0 (396)
- **Device model and storage size:**
  - iPhone 8 Plus
- **Operating system and version:**
  - 13.3.1

### Expected Behavior

Disable with the wifi name added exclusions, VPN will turn back on

### Actual Behavior

After adding the excluded wifi name, the default VPN will turn off. But if I disable the excluded wifi name, the VPN will continue to turn off.

### Screenshots

<details><summary>Screenshot:</summary>

![9C6C95FE-5A86-4555-9E71-632CF47EB6B5](https://user-images.githubusercontent.com/10969626/76704727-8f061e00-670d-11ea-9d4f-e0837fbf4923.jpeg)
![3942046B-195F-4A75-ACCD-C20758663A45](https://user-images.githubusercontent.com/10969626/76704731-94fbff00-670d-11ea-8d29-a85fcb4ca6c6.png)

</details>

**Comment by wduderude** [comment]
> ### Issue Details
> 
> 
> 
> 
> 
> 
> 
> - **AdGuard version:**
> 
>   - AdGuard for iOS v4.0.0 (396)
> 
> - **Device model and storage size:**
> 
>   - iPhone 8 Plus
> 
> - **Operating system and version:**
> 
>   - 13.3.1
> 
> 
> 
> ### Expected Behavior
> 
> 
> 
> Disable with the wifi name added exclusions, VPN will turn back on
> 
> 
> 
> ### Actual Behavior
> 
> 
> 
> After adding the excluded wifi name, the default VPN will turn off. But if I disable the excluded wifi name, the VPN will continue to turn off.
> 
> 
> 
> ### Screenshots
> 
> 
> 
> 
> 
> 
> 
> <details><summary>Screenshot:</summary>
> 
> 
> 
> 
> 
> ![9C6C95FE-5A86-4555-9E71-632CF47EB6B5](https://user-images.githubusercontent.com/10969626/76704727-8f061e00-670d-11ea-9d4f-e0837fbf4923.jpeg)
> 
> ![3942046B-195F-4A75-ACCD-C20758663A45](https://user-images.githubusercontent.com/10969626/76704731-94fbff00-670d-11ea-8d29-a85fcb4ca6c6.png)
> 
> 
> 
> 
> 
> 
> 
> </details>
> 
> 
> 
> ### Additional Information
> 
> 
> 
> 
> 
>

**Comment by sergerosenthaler** [comment]
@zzebrum @vozersky Where did the WiFi exception setting go? In the last few builds I can't find the WiFi exception setting anymore.

**Comment by IvanIin** [comment]
@sergerosenthaler you should turn on Developer mode in General settings. You can find Wi-Fi exceptions in Tracking protection-> Network settings then.

**Comment by sergerosenthaler** [comment]
@IvanIin This setting should be visible without enabling the Developer mode first. This is very confusing. Exceptions should be possible without digging in advanced settings first for many reasons:
1. company networks with specific DNS servers
2. tracking protection could interfere with, e.g. streaming devices etc.

**Comment by vozersky** [comment]
@sergerosenthaler yeah, fair enough, we're bringing the setting back
