### ISSUE TITLE
amazon advertisement

### ISSUE THREAD

**Issue by xxcriticxx** [AdguardTeam/AdguardForiOS#152]
still getting advertisement on amazon.com on adguard pro version

sample link:
https://www.amazon.com/Performix-Adguard-Adblock-for-Android/dp/B0158CTKR8

![img_3242](https://cloud.githubusercontent.com/assets/15007183/18572328/371bb94e-7b88-11e6-97fa-fac7625b5c8d.PNG)

**Comment by Alex-302** [comment]
Wrong repository. Write here in the next time:
https://github.com/AdguardTeam/AdguardFilters/issues
Add(copy-paste) these rules to user filter and check again:
```
||ssl-images-amazon.com/images/*/browser-scripts/da-
||ssl-images-amazon.com/images/*/banner/$third-party
```
