### ISSUE TITLE
[UI] Add extended filter tools for "Activity" tab

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdguardForiOS#1520]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Too many and overlapping domain logs between IPv4 and IPv6 make it difficult to track.

### Proposed Solution

Add some options for logs:
- IPv4 request
- IPv6 request
- Allowed
- Blocked

In addition, Add feature to disable logs or pause logs (only domain logs, debug logs still work)

### Screenshots

I attached the example from the Adblock application
<details><summary>Screenshot:</summary>

![IMG-4584](https://user-images.githubusercontent.com/10969626/76729714-62451b80-678c-11ea-8b1d-24b6b59c2f9d.PNG)

</details>

**Comment by ameshkov** [comment]
Dups: https://github.com/AdguardTeam/AdguardForiOS/issues/1403
