### ISSUE TITLE
It's an outmoded description for SDN filter in DNS filter. (v4 beta)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1523]
It maybe uses the outmoded description from SDN filter file:
https://filters.adtidy.org/extension/chromium/filters/15.txt
`Filter composed from several other filters (English filter, Social media filter, Spyware filter, Mobile ads filter, EasyList, EasyPrivacy, etc) and simplified specifically to be better compatible with DNS-level ad blocking.`

But we know that English filter and Spyware filter were renamed.
I remembered that you said Apple asked you to remove SDN filter from DNS filter.
(I'm curious why you still keep it in v4 beta.)
If so, ignore and close this issue.

**Comment by SoLenny** [comment]
@lancelot-moon Hello, we removed the SDN filter from the dns filter list. You most likely have it, because you updated from the old version and the filter remained in the settings. If you reinstall the application, the filter will disappear.
