### ISSUE TITLE
Can AdGuard Advanced Blocking for AG for Safari on macOS be realized on iOS?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1524]
For AG for Safari on macOS, the extension of AdGuard Advanced Blocking applies advanced blocking rules which are not supported by Safari Content Blocking API.
<details><summary>Screenshot:</summary>

![image](https://crowdin.com/s/93f363g3m483v6a3a3s493c585k4s4o435q433h463738393j4j6h6n4?size=origin&1585007101529)
</details><br/>

It sounds like extension and Safari Content Blocking API are different things on macOS.

AdGuard Advanced Blocking for AG for Safari on macOS can't be realized on iOS, right?

**Comment by zzebrum** [comment]
You are right, Safari on iOS do not provide advanced blocking

**Comment by lancelot-moon** [comment]
@ameshkov 
Bad news.
I wish system-wide HTTPS filtering for only browsers (Chrome, Safari, etc.) on iOS.
Should it be allowed by Apple since it's for browsers?

**Comment by lancelot-moon** [comment]
System-wide HTTPS filtering for only browsers seems to be allowed on Google Play.
https://play.google.com/store/apps/details?id=me.plusnow.shield.stable
