### ISSUE TITLE
Maybe move some options to Safari protection.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1525]
1. These are related to Safari content blockers.
It's better to move them to Safari protection.
Invert the Allowlist
Use simplified filters
Content blockers

2. Especially, "Invert the Allowlist" is very unclear.
For tracking protection, there is also allowlist.
Will it invert allowlists in both Safari & tracking protection if enabling it?
It's better to rename it to "Invert Safari content blocker's allowlist".

**Comment by zzebrum** [comment]
1. Invert the allowlist will be moved to Safari protection once the design is done. Othe options you've mentioned are under developer mode and I'm not aware of plans to move them

2. good point, thank you. Invert the allowlist is only a content blocker function.

**Comment by lancelot-moon** [comment]
@ameshkov 
General users will be confused between simplified filters and SDN filter.
They are related to Safari content blockers.
It's better to together move them to Safari protection.
