### ISSUE TITLE
Does it support domain format in the blocklist?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1527]
In the tutorial, it only mentions basic adblock rule syntax and hosts file.
https://kb.adguard.com/en/general/dns-filtering-syntax

If it actually also supports domain format in the blocklist, please remark domain format in the tutorial above.

**Comment by SoLenny** [comment]
@lancelot-moon Hello. 
There is no special processing of domain names in the application. A domain without any modifiers is a valid rule. There is no need to describe this separately in the documentation.

**Comment by lancelot-moon** [comment]
@SoLenny 
TBH, you should mention that domain names are supported format for DNS filters in the documentation, otherwise general users won't know it.
