### ISSUE TITLE
Dual VPN Connections

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForiOS#153]
Are there any known problems if you connect to two different VPNs at the same time on iOS?

For example, if you use Adguard PRO and: 
https://itunes.apple.com/ru/app/f-secure-freedome-vpn/id771791010?mt=8

It has to be tested.

**Comment by gshumihin** [comment]
Looks like Adguard and F-secure VPN could work together. 
myip.ru detects ip adress given by f-secure, and ads are filtered by adguard. pretty cool :)
