### ISSUE TITLE
Enhance the activities log like the filtering log of AG for Android.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1530]
1. The types of filtering requests in the activities log like the filtering log of AG for Android.
Blocked, allowed and so on.
(Well, you replaced `whitelisted` with `allowed` in AG for iOS.)
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/aLRiBlt.jpg)
</details><br/>

2. Pause the activities log.

**Comment by SoLenny** [comment]
@lancelot-moon Hello, we are in the process of improving the activity screen. More information will be available there.
