### ISSUE TITLE
Send feedback on GitHub doesn't work correctly 

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardForiOS#1531]
При нажатии на кнопку "пожаловаться на страницу" в IOS жалоба открывается в фоне - остаётся позади меню браузера "поделится", также не подхватывается ссылка сайта, на которую идёт жалоба, приходится копировать вручную.

**Comment by SoLenny** [comment]
@Vitalik93 Hello, please specify what version of programs and operating system do you use?

**Comment by Vitalik93** [comment]
IOS 13.4, Adguard 3.1.4 (254).

**Comment by zzebrum** [comment]
@Vitalik93 Проверьте на последней версии, пожалуйста. Не нахожу проблемы.

**Comment by Vitalik93** [comment]
У меня повторяется. Страница отправки отчета все еще открывается в фоновой вкладке, позади меню "поделится".

**Comment by zzebrum** [comment]
@Vitalik93 запишите, пожалуйста, видео. Какая версия iOS и версия. AdGuard у вас?
