### ISSUE TITLE
Unable to Update Subscriptions Under Privacy Settings

### ISSUE THREAD

**Issue by iamrahul10** [AdguardTeam/AdguardForiOS#1533]
Hello,

I'm unable to update the subscriptions I've added in the privacy settings. Last updated date is showing as 31 March. When I try to update, it's loading, but not completing. 

Please support. 

Thank you
![F9CE225D-5594-45A2-B456-138DCC3A8281](https://user-images.githubusercontent.com/33648855/78361497-1c82b280-75d6-11ea-9128-13d47262b192.png)

**Comment by SoLenny** [comment]
@iamrahul10 Hello, To troubleshoot this issue, we need to get the app logs.
Here’s what we need you to do:
Reproduce the issue (and remember the exact time when it happened).
Open the app, tap “Report an issue”, select “Contact Support”
The mail app will be opened, change the recipient to apple@adguard.com (!)
Mention this issue number in the email text.

**Comment by iamrahul10** [comment]
Just did as suggested.

**Comment by SoLenny** [comment]
@iamrahul10 Hello, you've got a subscription with URL https://hosts-file.net/ad_servers.txt 
Now it is unavailable. Try to remove it and everything should work correctly.

**Comment by iamrahul10** [comment]
I removed the filter and now the issue is resolved. Thanks.

**Comment by SoLenny** [comment]
@iamrahul10 Nice to know! :)
