### ISSUE TITLE
Implement Cloudflare 1.1.1.1 for Families

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardForiOS#1536]
Cloudflare offers new Malware and Malware / Adult filters via DNS, those are not implemented in AdGuard for iOS

### Proposed Solution

Implement the new Cloudflare DNS services into AdGuard
https://blog.cloudflare.com/introducing-1-1-1-1-for-families/

**Comment by sergerosenthaler** [comment]
@zzebrum Something for 4.0 release?

**Comment by zzebrum** [comment]
@sergerosenthaler this task assigned to v4.1
but please keep in mind [this](https://github.com/AdguardTeam/AdguardForiOS/issues/1410#issuecomment-619839166).

**Comment by balupton** [comment]
works great, thanks

**Comment by sergerosenthaler** [comment]
@zzebrum Please reopen this. There are three different Cloudflare DNS services the normal 1.1.1.1 and the following two:

Malware Blocking Only
Primary DNS: 1.1.1.2
Secondary DNS: 1.0.0.2

Malware and Adult Content
Primary DNS: 1.1.1.3
Secondary DNS: 1.0.0.3

For IPv6 use:

Malware Blocking Only
Primary DNS: 2606:4700:4700::1112
Secondary DNS: 2606:4700:4700::1002

Malware and Adult Content
Primary DNS: 2606:4700:4700::1113
Secondary DNS: 2606:4700:4700::1003

You have only implemented "Malware and Adult Content" not the "Malware Blocking only".

**Comment by ameshkov** [comment]
@sergerosenthaler this is actually for a reason. We can't use word "Malware" because it can't be used in an iOS app - we've got rejected a couple of times because of that.

**Comment by vozersky** [comment]
@sergerosenthaler we'll bring it back, just has to come up with a suitable naming :)

**Comment by balupton** [comment]
How come you get blocked by the 1.1.1.1 app doesn't 

![A3F96B24-2426-46D5-957E-A033488D5B07](https://user-images.githubusercontent.com/61148/91718351-87143a80-ebd6-11ea-9d6d-2e5b4eef9695.png)

**Comment by ameshkov** [comment]
@balupton because Apple is not consistent
