### ISSUE TITLE
AdGuard tracking protection not working in combination with Surfshark VPN

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardForiOS#1537]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v4.0.0 (437)
- **Device model and storage size:**
  - iPhone 11 Pro Max 512GB
- **Operating system and version:**
  - 13.4
- **Browser or App:**
  - Surfshark

### Expected Behavior

AdGuard tracking protection (default setting split tunnel) should work in combination with Surfshark VPN

### Actual Behavior

AdGuard tracking protection will be deactivated as soon as a Surfshark VPN (IKEv2 or OpenVPN) session is started. After finishing the Surfshark VPN AdGuard tracking protections needs to be activated manually again.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by SoLenny** [comment]
@sergerosenthaler Hello, unfortunately, we can not do anything about it. Only one VPN application can work at a time.
