### ISSUE TITLE
User filter lists don't update

### ISSUE THREAD

**Issue by SebastianRasch** [AdguardTeam/AdguardForiOS#1539]
I'm running version 4.0.0 (437) on iOS 13.3.1.

On refresh (button on main page), user filter lists are not being updated. They are also not updated automatically/periodically. All other filters are updated normally.

When I update my filter list on my server, AdGuard on macOS picks up the new version and downloads it. On iOS however, the old version remains and there are no new updates found. There is no way to update user filter lists except deleting it and adding it anew.

**Comment by SebastianRasch** [comment]
Also, the refresh button is somehow really hard to hit. It takes several tries to actually activate the updating process on my iPhone X.

**Comment by SebastianRasch** [comment]
This still consists in the final version 4.0 from the AppStore.

**Comment by curiosityseeker** [comment]
> On iOS however, the old version remains and there are no new updates found. There is no way to update user filter lists except deleting it and adding it anew.

I cannot confirm this for v 4.0 in iOS 13.4.1. Both Safari and DNS filters update for me.

**Comment by curiosityseeker** [comment]
I was talking about custom filter lists as well, of course (you cannot update specific filters). And they DO update for me.

**Comment by SebastianRasch** [comment]
@curiosityseeker Can I provide you with some logs or something? Because my own filter list always stays on the same version. The only way to update it is to remove it and re-add it again.
Standard filter lists like AdGuard base filters update normally. Also, my own filter list updates just fine on AdGuard for Mac and Windows. Just not on iOS.

**Comment by curiosityseeker** [comment]
> @curiosityseeker Can I provide you with some logs or something? 

Well, I guess it would make more sense to provide them to the AdGuard team ;-)

> Because my own filter list always stays on the same version. The only way to update it is to remove it and re-add it again.
> Standard filter lists like AdGuard base filters update normally. Also, my own filter list updates just fine on AdGuard for Mac and Windows. Just not on iOS.

Again, not here. I've added 5 lists and they update normally:

![grafik](https://user-images.githubusercontent.com/60518106/83946348-6d01d080-a810-11ea-9f50-747b85aceb9e.png)

**Comment by SebastianRasch** [comment]
Sorry, I thought you work for AdGuard.

**Comment by curiosityseeker** [comment]
> Also, I'm not talking about DNS filters. I'm talking about Settings > Protection in Safari > Filters > Custom lists (ka wie's auf Englisch heißt aber im Deutschen ist es "Benutzerdefiniert").

I've added 3 lists there which update properly as well. No problems here.

**Comment by zzebrum** [comment]
@SebastianRasch hi there, sorry for the late reply. Can you reproduce the issue and collect log files? You can send it to apple[at]adguard[dot]com right from the app (Settings - Send feedback - Contact support, change the recipient email there, please)

**Comment by SebastianRasch** [comment]
Will do!

**Comment by zzebrum** [comment]
@SebastianRasch my mistake, if you don't need to export logs, then yes, just change the email and send away 🙈

**Comment by SebastianRasch** [comment]
Anything new on this? Because this is still not working on 4.0.4!

**Comment by SebastianRasch** [comment]
Got a new M1 MacBook Air and I have the same problem there as well now: User filter lets don't update there either. It works for a day maybe and then it's stopping. Only solution is to remove and re-add the user list URL and then it works again for a day.

URL for my user list is:
https://onedrive.live.com/download?cid=DA525153D7ABF6E6&resid=DA525153D7ABF6E6%21177&authkey=AOghSjpNqmwFG0Q

**Comment by zzebrum** [comment]
@SebastianRasch maybe the link is the reason why it's not working? How did you create the link in OneDrive which could be added as a filter? I failed to do so 🙈

**Comment by SebastianRasch** [comment]
@zzebrum I used this tool: https://metadataconsulting.blogspot.com/2019/03/OneDrive-2019-Direct-File-Download-URL-Maker.html
Is it better to host them on Github? Never hosted anything on Github but I can try.

**Comment by zzebrum** [comment]
@SebastianRasch  ok, thanks, I've managed to add the filter. If I force updating process it goes well. Do I need to wait to reproduce the problem?

**Comment by SebastianRasch** [comment]
Yeah try again tomorrow, I will update the list and see if it works for you with the new version number (110 then tomrrow). Same day works for me as well but for some reason it stops afterwards.
Might it be helpful to add a date to the list? The version number should be enough, no?

**Comment by SebastianRasch** [comment]
Could you reproduce it @zzebrum?

**Comment by zzebrum** [comment]
@SebastianRasch nope! Let's try the second option - check with the filter hosted elsewhere, Github for example?

**Comment by SebastianRasch** [comment]
So it was still updating for you? That's odd. Is there some setting that might interfere with filter updates?

I'm trying with a list hosted on Github. Works for now but I'll report back tomorrow 😉

**Comment by SebastianRasch** [comment]
OK it actually seems to work now, even on iOS. So it might have been the hoster all along. I'll watch this a few more days but if it continues to work I'll close this issue. Thanks for your help @zzebrum!
