### ISSUE TITLE
Adguard blocker detected error

### ISSUE THREAD

**Issue by Zarthes** [AdguardTeam/AdguardForiOS#1541]
https://nxmac.com/

![4A9BC384-4E15-47A4-8988-34E18FCDFBEC](https://user-images.githubusercontent.com/56041562/78887930-69003f00-7a69-11ea-9b02-d4d8ce90d410.png)

**Comment by SoLenny** [comment]
@Zarthes Hello, I can't reproduce it on my side, any way you can try to enable Anti-Adblock killer (Settings -> Filters -> Annoyances).
If it won't help, please provide which filters do you use?

**Comment by Zarthes** [comment]
@SoLenny hello 
Ive activated Anti Adblock Killer as you suggested,but I still got the same error
Here on SS you can see the filter lists that I’m using on iOS,
Note: Adguard for Mac works without any problem

![50DBE78A-D433-4810-8932-E77828E3B9BB](https://user-images.githubusercontent.com/56041562/78891079-7d473a80-7a6f-11ea-9a60-b34fcb7a510a.png)

**Comment by SoLenny** [comment]
@Alex-302 have a look pls

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardFilters #53278](https://github.com/AdguardTeam/AdguardFilters/issues/53278) via [**ZenHub**](https://www.zenhub.com/)
