### ISSUE TITLE
custom user rule didn't work on Cosmetic css rules examples

### ISSUE THREAD

**Issue by FollowTheTrend** [AdguardTeam/AdguardForiOS#1543]
I learn rule on [Adguard official website](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters?utm_source=extension&aid=16593#cosmetic-css-rules-examples-1), and use` example.com#$#body { background-color: #333!important; }`  . But it couldn't save on Aguard Pro for iOS. It showed red error. Could you help me? Thanks a lot!

![QQ截图20200415002606](https://user-images.githubusercontent.com/13286382/79249617-1d59f500-7eb0-11ea-8105-8e688f7413ef.png)
![IMG_0755](https://user-images.githubusercontent.com/13286382/79249607-192dd780-7eb0-11ea-95f7-4db094401fa7.PNG)

**Comment by FollowTheTrend** [comment]
Same rule works on Adguard for PC.

**Comment by zzebrum** [comment]
@FollowTheTrend such type of rules won't work on iOS due to Safari Content blocking API restrictions.
