### ISSUE TITLE
App crashes when sent to background

### ISSUE THREAD

**Issue by rodaimi** [AdguardTeam/AdguardForiOS#1544]
### Issue Details
When you launch Adguard then switch to an already open app, Adguard crashes without exception.

- **AdGuard version:**
    - v4.0.0(462)
- **Device model and storage size:**
  -  iPhone XR
- **Operating system and version:**
  -  iOS 13.3.1  

### Actual Behavior

</details>

### Additional Information
[Adguard-2020-04-28-184500.txt](https://github.com/AdguardTeam/AdguardForiOS/files/4549000/Adguard-2020-04-28-184500.txt)

**Comment by SoLenny** [comment]
@rodaimi Hello.
To troubleshoot this issue, we need to get the app logs.
Here’s what we need you to do:
Reproduce the issue (and remember the exact time when it happened).
Open the app, tap “Send Feedback”, select “Contact Support”
The mail app will be opened, change the recipient to apple@adguard.com (!)
Mention this issue number in the email text.

**Comment by rodaimi** [comment]
Logs submitted 4/29 10:47 EDT

**Comment by rodaimi** [comment]
After a clean install, the issue has resolved itself. I wish my configurations could have been backed up to iCloud.
