### ISSUE TITLE
Adguard detected

### ISSUE THREAD

**Issue by Zarthes** [AdguardTeam/AdguardForiOS#1545]
Hello,
When I go to https://www.kirmiziturkmedya.com/forum/f23/ 
It detects adguard and doesn’t let me go
Edit: It takes 5-10 sec to recognises adguard then block appears
![1F9413FA-B06A-45AE-96DC-09F19D415458](https://user-images.githubusercontent.com/56041562/80727581-8e371900-8b0e-11ea-8ff1-9750e55fdbff.png)

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardFilters #54701](https://github.com/AdguardTeam/AdguardFilters/issues/54701) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
Wrong repository. Moved to Filters.
