### ISSUE TITLE
Adguard not work at iOS 13.4.1

### ISSUE THREAD

**Issue by LaurenceSamael** [AdguardTeam/AdguardForiOS#1547]
### Issue Details

- **AdGuard version:**
  - 3.1.4(254)
- **Device model and storage size:**
  - iPhone 7plus 32gb
- **Operating system and version:**
  - 13.4.1
- **Browser or App:**
  - Safari 

### Actual Behavior

After clearing Safari history and website data, Adguard was unable to load rules, which invalidated Safari's screening of ads. The custom rule is also invalid.

### Screenshots

![IMG_1018](https://user-images.githubusercontent.com/44238918/80944443-2d645500-8e1c-11ea-9a06-29bf58c21cad.png)
![IMG_1017](https://user-images.githubusercontent.com/44238918/80944432-23425680-8e1c-11ea-9f28-15a72604b7c8.png)

**Comment by SoLenny** [comment]
@LaurenceSamael Hello, thank you for the information provided, we will fix this error in the next update.

**Comment by nohli** [comment]
When I (also on the latest iOS) enable the very first button, it breaks my network connection.
(even with DNS-Settings -> System DNS)

**Comment by Maxim-Butov** [comment]
Is your problem still recurring?
