### ISSUE TITLE
Rule limit error details 

### ISSUE THREAD

**Issue by minsk21** [AdguardTeam/AdguardForiOS#1549]
4.0.0.0(462)

Если добавить слишком много правил, то выдает ошибку «ошибка обновления фильтров» не уточняя с чем она связана (сам догадайся)

Предложения:

1. Добавить подробности ошибки

2. В списке групп фильтров указывать сколько правил там есть и сколько ещё можно добавить

3. В описании каждого фильтра писать сколько в нем правил

========

If you add too many rules, it gives an error "filter update error" without specifying what it is connected with (guess it yourself)

 suggestions

 1. Add error details

 2. In the list of filter groups indicate how many rules are there and how many more can be added

 3. In the description of each filter indicate how many rules are in it

**Comment by SoLenny** [comment]
@minsk21 Здравствуйте, в ближайшее время выйдет крупное обновление, там будет предусмотрено оповещение о превышении количества используемых правил, помимо этого всегда можно будет посмотреть информацию на вкладке "Блокировщики контента".
