### ISSUE TITLE
Feature Request: Allow subscription to user lists

### ISSUE THREAD

**Issue by Madi0ne** [AdguardTeam/AdguardForiOS#155]
Dear All,

I want to request a feature in Adguard for iOS, which allow user to subscribe to their own lists from internet.

Regards,
Maddy

**Comment by ameshkov** [comment]
Hi @Madi0ne, thank you for the feedback!

This issue is duplicate for https://github.com/AdguardTeam/AdguardForiOS/issues/50 though.
