### ISSUE TITLE
WLAN Connection gets lost when opening AdGuard

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1550]
Everytime I Open AdGuard 4.0 (which is a great update), my WLAN connection switches to LTE. After closing the app it takes around 30 seconds until I‘m connected with WLAN again. 
I‘m connected with AdGuard DNS over TLS.
iPhone 11 Pro iOS 13.4.1
AdGuard 4.0 (AppStore release build)

WeTransfer link screen recording:

https://we.tl/t-DPi8gk1FHJ

**Comment by ameshkov** [comment]
Hi! Is there any change with other DNS servers?

**Comment by ameshkov** [comment]
Here's my guess -- when you open the app, AdGuard immediately re-applies DNS settings and this causes visual Wi-Fi disconnect. It stays this way until the first real network connection attempt occurs, at this point the VPN kicks in and starts working.

@IvanIin am I right?

**Comment by iDjay** [comment]
> Hi! Is there any change with other DNS servers?

Same with DNS-over-HTTPS.

**Comment by iDjay** [comment]
I can also report short disconnects (1-2 seconds) from WLAN while using my iPhone.

**Comment by zznosar** [comment]
This is what i notice even during the beta testing phase: i enabled the status message, and based on that, everytime the app is open, the rules are being converted and reapplied. So it disconnects and it connects again. I think thats the reason why other testers did not raise it as a bug? 

I haven’t experience the short disconnect while using the phone though. Only when opening the app.

I have three devices where it is installed. iphone 11 pro, iphone 7 and iPad Pro 11 inch. None has disconnect issue when browsing the internet.

Just only when opening the app, but it connects again after 2 seconds after rules are converted.

**Comment by iDjay** [comment]
> I haven’t experience the short disconnect while using the phone though. Only when opening the app.
> 

Happens 1x/hour for me, only for a short time (< 5 seconds).

**Comment by iDjay** [comment]
Do you need log files?

**Comment by zznosar** [comment]
I think this will be fixed soon. There is a new beta 4.0.1 that fixes this and the disconnection when opening the app is gone.

They probably change something in the logic that it should not automatically check an update when opening the app (probably same as AdGuard Pro). Not sure though. Just guessing.

Hopefully they release it soon.

**Comment by iDjay** [comment]
It‘s completely dead now, WiFi changing to LTE every second now then back to WiFi.

**Comment by iDjay** [comment]
Fixed in 4.0.1
