### ISSUE TITLE
Allow "NextDNS specific" characters in DNS server addresses

### ISSUE THREAD

**Issue by pro-sumer** [AdguardTeam/AdguardForiOS#1551]
### Problem Description

I want to use [NextDNS](https://nextdns.io) servers in AdGuard for iOS and I want them to identify my devices in Analytics and Logs.

This can be done by constructing the DNS server addresses in a specific way:
* **DOT**: _Prepend the name to the provided domain (the name should only contain a-z, A-Z, 0-9 and -). Use -- for spaces. For "John Router", you would use `John--Router-xxxxxx.dns.nextdns.io` as your DNS-over-TLS endpoint._
* **DOH**: _Append the name to the provided URL (the name should be URL encoded). For "John's Firefox", you would use `https://dns.nextdns.io/xxxxxx/John's%20Firefox` as your DNS-over-HTTPS endpoint._

However, AdGuard does not seem to accept `-` or `%20` when entering a DNS server address...

### Proposed Solution

Allow all characters required by the NextDNS setup when entering a DNS server address.

### Alternatives Considered

Alternative is to use NextDNS's own App and disable DNS functionality in AdGuard, but it would be nice if we could use DNS functionality in AdGuard itself.

### Additional Information

None.

**Comment by SoLenny** [comment]
@pro-sumer Hello, thank you for the information provided. You are right `%` sign is not allowed when entering the address, but the `-` sign should work correctly. We will deal with it.

**Comment by ameshkov** [comment]
@IvanIin let's do it in v4.0.1, the fix is trivial
