### ISSUE TITLE
 Several wishes for v4.0 Разобрать

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardForiOS#1552]
Есть несколько пожеланий по 4 версии:
1) Поменять иконку раздела "Защита" (внизу). Думаю щиток был бы логичнее. Текущий вариант не совсем удачный, по иконке не поймёшь что за раздел.
2) Кнопку "Удалить VPN-профиль" в расширенных настройках заменить на "Переустановить VPN-профиль" с соответсвующие функционалом.
3) Считаю что настройки работы туннеля должны быть в настройках DNS, как это было в предыдущей версии. Все таки туннель относится к DNS, так что пусть все эти настройки будут в одном месте.
4) Не удобно сделали что настройки DNS доступны только когда он включён. Опять же в прошлой версии их можно было внести заранее. И потом решить, надо ли включать или нет.
5) Кнопку выбора DNS-профиля перенести в правый верхний угол, вместо нижнего левого. 
6) Кнопку "Блокировщики контента" перенести из Расширенных настроек в Общие. Расширенные настройки рассчитаны на опытных пользователей, а учитывая что "Блокировщики контента" чисто информативный раздел, вряд ли там можно нажать что то не то...

**Comment by Vitalik93** [comment]
Ещё одно... Верните на главный экран информацию, когда последний раз обновлялись фильтры.

**Comment by SoLenny** [comment]
@AlikhanAliev Здравствуйте, спасибо за ваши предложения. Несколько из них мы взяли на вооружение. Но некоторые, к сожалению, не смогут быть сделаны. Вот почему:

>Кнопку "Удалить VPN-профиль" в расширенных настройках заменить на "Переустановить VPN-профиль" с соответсвующие функционалом.

Не совсем поняла, что вы имеете ввиду. Зачем это делать?

>Считаю что настройки работы туннеля должны быть в настройках DNS, как это было в предыдущей версии. Все таки туннель относится к DNS, так что пусть все эти настройки будут в одном месте.

Мы специально убрали эту настройку в расширенные, потому что считаем, что она слишком специфическая и нужна далеко не всем пользователям.

>Кнопку "Блокировщики контента" перенести из Расширенных настроек в Общие. Расширенные настройки рассчитаны на опытных пользователей, а учитывая что "Блокировщики контента" чисто информативный раздел, вряд ли там можно нажать что то не то...

Тут тоже самое, эта вкладка нужна для более продвинутых пользователей, которым такая информация может быть полезна.

>Ещё одно... Верните на главный экран информацию, когда последний раз обновлялись фильтры.

Специально убрали эту информацию с главного экрана, чтобы не засорять его.

По пожеланиям, которые мы будем исполнять, созданы отдельные задачи, а эту общую я закрою :)

**Comment by Vitalik93** [comment]
> Не совсем поняла, что вы имеете ввиду. Зачем это делать?

Имел ввиду что Adguard будет не просто удалять профиль VPN, но и ставить новый.

> Мы специально убрали эту настройку в расширенные, потому что считаем, что она слишком специфическая и нужна далеко не всем пользователям.

Может всё же лучше располагать настройки не по степени нужности а по принадлежности их к какой то функции/разделу? И по её ненужности тоже не согласен. Тем у кого установлен еще один VPN помимо Adguard DNS (как у меня) настройки их совместной работы нужны.


> Тут тоже самое, эта вкладка нужна для более продвинутых пользователей, которым такая информация может быть полезна.

Тот же ответ что и выше в таком случае :)

**Comment by ameshkov** [comment]
> Имел ввиду что Adguard будет не просто удалять профиль VPN, но и ставить новый.

Ну он ведь и поставится новый при включении защиты.
Так мы теряем одну из функций - когда человек именно хочет удалить профиль, если он например дальше не намерен использовать функционал, основанный на впн

> Может всё же лучше располагать настройки не по степени нужности а по принадлежности их к какой то функции/разделу? 

Ну вот раньше так делали и получали прорву настроек, которыми пользуется полтора человека.

**Comment by Vitalik93** [comment]
> Ну вот раньше так делали и получали прорву настроек, которыми пользуется полтора человека.

Видимо я вхожу в эти полтора) Ладно, нет так нет...
