### ISSUE TITLE
Adguard Premium IOS v4 blocking issue

### ISSUE THREAD

**Issue by sdugoten** [AdguardTeam/AdguardForiOS#1553]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ Y] I am running the latest version
- [ Y] I checked the documentation and found no answer
- [ Y] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - Adguard Premium v4
- **Device model and storage size:**
  - iphone 11 pro max
- **Operating system and version:**
  - 13.4.1
- **Browser or App:**
  - 

### Expected Behavior

Blocking log should show all blocking domain by bulit in filter, subscribe filter, or black list like what Adguard pro does

### Actual Behavior

The blocking activity screen on Adguard Premium v4 right now would not show what was block by subscribed filter list, or just not using the subscribed filter at all on IOS app

### Screenshots

Filter added in DNS filter section 

https://i.imgur.com/7lYqE8C.jpg

Nothing shown was block in activity 

https://i.imgur.com/GMplZA6.jpg

<details><summary>Screenshot:</summary>

</details>

**Comment by sdugoten** [comment]
Adguard pro on the other hand will show what was blocked by subscribed filter list like below


https://i.imgur.com/0nieJdH.jpg

**Comment by zznosar** [comment]
Mine seems to work well. I have premium activated. Full Tunnel Mode.

![7839534D-1E7F-4B0F-B7B9-7C8131E95B70](https://user-images.githubusercontent.com/27464836/81763108-c62c5c00-9511-11ea-8da1-0fbf3b847b25.png)

**Comment by zzebrum** [comment]
@sdugoten filters you have added are not for DNS filtering. Please, use [AdGuard SDN filter](https://kb.adguard.com/en/general/adguard-ad-filters#simplified-domain-names-filter) instead.
