### ISSUE TITLE
Bug: Theme header in Settings stays at top of display when scrolling

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForiOS#1555]
Version 4.0.0(462)

STR:

1. Tap the Settings button.
2. Select General.
3. Scroll down so the theme options are scrolled away.

Expected result:

The `Theme` at the top scrolls away, too.

Actual result:

`Theme` is displayed effectively as a header for the entire Settings screen.

**Comment by kovalchuk0803** [comment]
@carlylemiii it's not a bug, it's normal behavior for table view. You can experience the same behavior if you go to "Safari protection" -> "Filters" -> Tap on search icon in the top right corner -> scroll down

**Comment by 08kovalchuk03** [comment]
@carlylemiii it's not a bug, it's normal behavior for table view. You can experience the same behavior if you go to "Safari protection" -> "Filters" -> Tap on search icon in the top right corner -> scroll down

**Comment by carlylemiii** [comment]
Ah, I see now — on the iPad I'm using I would need to scroll just a hair more (but can't) and it would disappear. Thanks.

**Comment by 08kovalchuk03** [comment]
@carlylemiii you're welcome
