### ISSUE TITLE
Network request erroneously not blocked

### ISSUE THREAD

**Issue by curiosityseeker** [AdguardTeam/AdguardForiOS#1556]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version: AdGuard for iOS v4.0
- **Device model and storage size: iPhone 7 and iPad 2018
- **Operating system and version: 13.4.1
- **App: The YR weather app

### Expected Behavior

The app makes a network request to

https://app-measurement.com/sdk-exp

although I added the following blocking rule:

||app-measurement.com^$important

which should block above request according to, e.g., [this](https://adblockplus.org/en/filter-cheatsheet#blocking2) instruction.

### Actual Behavior

The network request to 

https://app-measurement.com/sdk-exp

is not blocked although it should.

### Screenshots

<details><summary>Screenshot:</summary>

![Bildschirmfoto](https://user-images.githubusercontent.com/60518106/81932263-d0228d80-95eb-11ea-8b5a-f1f3ffcd81eb.PNG)

</details>

**Comment by ameshkov** [comment]
There's a weird thing with this DNS query.

It does not query `app-measurement.com`. 
It queries exactly `https://app-measurement.com/sdk-exp` which is not a valid domain name, this is an URL. Basically, this is an invalid query and no DNS server can return anything for it.

I suppose there is a mistake in some Google library that triggers this kind of queries. It does no harm, but it looks rather weird.

If you want to block it in AG, add something like this: `/app-measurement.com/`.

**Comment by curiosityseeker** [comment]
> If you want to block it in AG, add something like this: `/app-measurement.com/`.

Thank you very much. That rule blocked that request, indeed!

Btw.: v 4.0 is a great release - congratulations!

**Comment by ameshkov** [comment]
Thank you:)
