### ISSUE TITLE
AG lets you select unsupported protocol for DNS servers

### ISSUE THREAD

**Issue by curiosityseeker** [AdguardTeam/AdguardForiOS#1557]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:  - AdGuard for iOS v4.0
 
- **Device model and storage size: iPhone 7 and iPad 2018
 
- **Operating system and version:** iOS 13.4.1
  
### Expected Behavior

In the settings for the selected DNS servers only the supported protocols should be available.

### Actual Behavior

When choosing, e.g., the Cloudflare DNS server, DoH is applied by default. In the log the status for the net requests is "encrypted" as it should. 

However, when changing the protocol for that DNS server to DNSCrypt, the status for the net requests is in my German version "verarbeitet", which probably translates to "processed". Which makes sense as DNSCrypt is not supported by Cloudflare - but it shouldn't be available in the menu at all to prevent users applying incorrect settings.

**Comment by floam** [comment]
Fixed?
