### ISSUE TITLE
DNS-over-TLS using non-standard port

### ISSUE THREAD

**Issue by Pusnow** [AdguardTeam/AdguardForiOS#1563]
### Issue Details

- **AdGuard version:**
  - 4.0

- **Device model and storage size:**
  - iPhone SE (2020) / 128 GB
- **Operating system and version:**
  - 13.5

### Expected Behavior

DoT using non-standard port should work.

eg) tls://xxx.xxx.xxx.xxx:20

### Actual Behavior

After upgrading to Adguard 4.0, DoT using non-standard port is not working.

**Comment by SoLenny** [comment]
@Pusnow Hello. When you add a DNS server with a non-standard port, does the application show you an error? Or added without errors, but not working?

**Comment by Pusnow** [comment]
Nevermind, it was my mistake.
