### ISSUE TITLE
Add an overlay over the chart when DNS protection is disabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1565]
Currently, it may be unclear to the user why the chart is empty:

![image](https://user-images.githubusercontent.com/5947035/83121227-b2b8ed80-a0da-11ea-9acc-9a95f0c59495.png)

**Comment by 08kovalchuk03** [comment]
The screen will be heavily redesigned in v4.3, so this task is not relevant anymore.
