### ISSUE TITLE
BETA - AdGuard Pro v4.0.1 crashes in Content Blockers Menu

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#1568]
AdGuard Pro v 4.0.1 beta crashes when checking the Content Blockers.

Steps to Reproduce:

1. Open AdGuard Pro v4.0.1
2. Go to Settings
3. Go to General
4. Go to Advance Settings
5. Go to Content Blockers

Expectation : Should Not Crash

Actual : AdGuard Crashes

I’m not sure what was change here. But normal AdGuard 4.0.1 Beta is fine. But AdGuard Pro 4.0.1 beta crashes.

**Comment by bigdargon** [comment]
Confirm the same error!

**Comment by zznosar** [comment]
Issue is fixed in the new beta
