### ISSUE TITLE
Краткая статистика разделов настроек

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardForiOS#1570]
Заметил что у некоторых разделов в настройках не отображается краткая статистика, например сколько фильтров или правил используется, хотя для аналогичных разделов рядом она отображается. Показал эти разделы на скринах. Неплохо бы привести это к одному виду.
![20B3261B-5F60-43B0-9EFB-742D917D4DDF](https://user-images.githubusercontent.com/34383288/83364033-6f8ea100-a39e-11ea-8f21-959915eafd6f.jpeg)
![21AE0221-36B0-4104-A595-DDC4CF2CE2D2](https://user-images.githubusercontent.com/34383288/83364036-72899180-a39e-11ea-8c53-f40ed7a6d760.jpeg)

**Comment by zzebrum** [comment]
@Vitalik93 будет сделано вместе с #1354
