### ISSUE TITLE
Cellular adblocking problem. 

### ISSUE THREAD

**Issue by Goddess-Bastet** [AdguardTeam/AdguardForiOS#1572]
Premium version. 
iOS 13.5.1. 
No longer blocking ads when on cellular connection - 4G. 
Message states I’m connected to an IPv6 - only connection & that I cannot use custom servers. I’m using AdGuard Default.

**Comment by Ei14Ji** [comment]
> Premium version.
> iOS 13.5.1.
> No longer blocking ads when on cellular connection - 4G.
> Message states I’m connected to an IPv6 - only connection & that I cannot use custom servers. I’m using AdGuard Default.

**Comment by iDjay** [comment]
I can confirm this on web-based apps.

**Comment by zzebrum** [comment]
@Goddess-Bastet @iDjay do you have AdGuard Pro?

**Comment by iDjay** [comment]
> @Goddess-Bastet @iDjay do you have AdGuard Pro?

No. 4.0.1 with AdGuard DNS.

**Comment by Goddess-Bastet** [comment]
Yes, AdGuard Pro (Not the newer Premium).

**Comment by zzebrum** [comment]
@Goddess-Bastet please, upgrade to the latest v4.0.1 that was released today

**Comment by Goddess-Bastet** [comment]
Thanks.
I’ll let you know whether the problem is fixed.

**Comment by Goddess-Bastet** [comment]
@zzebrum Problem appears to be solved with the latest version.
Thanks.
