### ISSUE TITLE
Заблокированные запросы

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardForiOS#1573]
В версии 4.0 (Premium) в журнале активности не отображаться заблокированные запросы. Даже с выключенной защитой Safari и после явной блокировки рекламы DNS раздел "заблокированные запросы" в журнале пустой, хотя запросы с пометкой "реклама" и нулевым ответом есть (если выбрать отображение всех запросов).
![BAE595EA-7686-43E9-B488-0D75EA00C1F0](https://user-images.githubusercontent.com/34383288/83931439-0c857b80-a79d-11ea-821a-35e2dd113eee.jpeg)
![6E6A2F2E-8861-4EF9-A8E0-6CF71F0617CF](https://user-images.githubusercontent.com/34383288/83931455-1a3b0100-a79d-11ea-8eb7-5df8bdb51859.jpeg)

**Comment by zzebrum** [comment]
@Vitalik93 
Pull to refresh - чтобы отображались запросы. это в будущем исправят #1567

**Comment by Vitalik93** [comment]
Странно. Вроде тянул, всё равно пусто... Можно еще добавить пожелание, чтобы заблокированные запросы как то выделялись среди остальных? Например красным цветом. В прошлой версии по моему это было.

**Comment by Vitalik93** [comment]
Проверил сейчас ещё раз - пусто, даже если потянуть.

**Comment by Vitalik93** [comment]
Почему запрос закрыли, если он решён? Связи с 1567 никакой тут нет...
