### ISSUE TITLE
Туннель не поддерживается в фоновом режиме

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdguardForiOS#1575]
Здравствуйте,

iPhone XR, iOS 13.5.1, AdGuard 4.0.0 (462). После включения VPN (Split-Tunnel) и выключения экрана туннель работает в фоновом режиме 5-7 минут. Затем DNS-фильтрация прекращается. При запуске приложения туннель также перезапускается и начинает работать снова. Логи в приложении. В прежней версии такой проблемы не было...

Спасибо!

[adguardforios_logs_163062020166 2.zip](https://github.com/AdguardTeam/AdguardForiOS/files/4765577/adguardforios_logs_163062020166.2.zip)
[adguardforios_logs_163062020166.zip](https://github.com/AdguardTeam/AdguardForiOS/files/4765580/adguardforios_logs_163062020166.zip)
[adguardforios_logs_163062020176.zip](https://github.com/AdguardTeam/AdguardForiOS/files/4765582/adguardforios_logs_163062020176.zip)

**Comment by zzebrum** [comment]
@ammnt попробуйте с другим DNS сервером, будут изменения?

**Comment by ammnt** [comment]
> @ammnt попробуйте с другим DNS сервером, будут изменения?

Пробовал AdGuard и свой сервер на базе AGH. Мне кажется нет разницы, но после последнего обновления стало работать явно стабильнее. Посмотрите еще вот эти [логи](https://github.com/AdguardTeam/AdguardForiOS/files/4793990/adguardforios_logs_169062020196.zip), пожалуйста.

**Comment by ammnt** [comment]
После сброса настроек и установки Pro-версии из App Store работает нормально.
