### ISSUE TITLE
No connection available when switching access points

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1576]
I can notice short (~2sec) WLAN dropouts when AdGuard 4.0.1 is enabled on my iPhone 11 Pro with iOS 13.5.1 and also on my iPad Air 2019 with iOS 13.5.1.
The issue happens while I‘m connected with AdGuard DNS.

**Comment by zzebrum** [comment]
@iDjay how does it happen? Does wi-fi icon disappear from status bar?

**Comment by iDjay** [comment]
Exactly, yes.

**Comment by zznosar** [comment]
Do you have DNS filter subscription? I believe connection crashes if you are subscribe to too many filters like 450K and above or the file is more than 10MB.

Have you tried without DNS subscription?

Mine is relatively stable and no disconnection at all (4.0.1).

My DNS filter list is below 200K.

**Comment by iDjay** [comment]
5 Safari Filter enabled (General, German, Spyware, Social-Media, Annoyances) ~ 50k rules
DNS-Filter no customized rules
DNS enabled for WLAN + Cellular
DNS Server AdGuard DNS-over-TLS (no VPN Icon)

**Comment by zznosar** [comment]
Ohh. Is your Tunnel Mode the “Full Tunnel Mode - No VPN icon”? 

That’s the unstable mode. DNSCloak has the same mode and its also unstable.

**Comment by iDjay** [comment]
> Ohh. Is your Tunnel Mode the “Full Tunnel Mode - No VPN icon”? 
> 
> 
> 
> That’s the unstable mode. DNSCloak has the same mode and its also unstable.

Yes, but I never had problems with AdGuard v3. I‘ll switch to see if it‘s better.

**Comment by iDjay** [comment]
It‘s stable now, but so would still recommend to have a look at the other option as I didn‘t experience the issues with AdGuard 3.x

**Comment by zzebrum** [comment]
@iDjay sorry, I wonder isn't it similar to #1550?

**Comment by iDjay** [comment]
> @iDjay sorry, I wonder isn't it similar to #1550?

Yes, but this one is fixed.

**Comment by iDjay** [comment]
The issue is happening with Full Tunnel with VPN icon too, so the tunnel is not the problem.

**Comment by iDjay** [comment]
Can confirm the dropouts with the Full Tunnel + VPN Icon too.

**Comment by zzebrum** [comment]
@iDjay I'm still confused :( what's the difference between these two tasks? Please, reproduce the issue and send the log to apple[at]adguard[dot]com

**Comment by iDjay** [comment]
> @iDjay Please, reproduce the issue and send the log to apple[at]adguard[dot]com

There is no way to reproduce it, but I will send you logs when the issue is happening again!

**Comment by iDjay** [comment]
@zzebrum I couldn‘t send the logs, delivery failed! I can send them to your support@ Mail.

**Comment by akmLaVx** [comment]
We've received logs from the OP. See ticket 1938768.

**Comment by iDjay** [comment]
Still happening, still annoying 😕

**Comment by zzebrum** [comment]
@iDjay please, wait for the next beta version in Testflight

**Comment by iDjay** [comment]
> @iDjay please, wait for the next beta version in Testflight

Not a beta user anymore, but thanks!

**Comment by zzebrum** [comment]
@iDjay I can add you temporary to check the problem if you want :)

**Comment by iDjay** [comment]
> @iDjay I can add you temporary to check the problem if you want :)

Yes, please.

**Comment by iDjay** [comment]
It‘s even worse with the current iOS 14 beta. No Wifi connectivity for about 10-15 minutes.

**Comment by iDjay** [comment]
I removed the VPN profile and now it‘s stable (both issues).

**Comment by iDjay** [comment]
Still happening.
AdGuard 4.0.2 (509) Beta
iOS 14 beta 4
AdGuard DNS-over-TLS 
Full Tunnel.

**Comment by iDjay** [comment]
@zzebrum sent you some new logs

**Comment by iDjay** [comment]
Could it be that this is happening because AdGuard updates the filters? However it's happening every 2-3 hours which is too often for updating filters.

**Comment by airobot60** [comment]
Thank you✌️✌️

เมื่อ พฤ. 13 ส.ค. 2563 เวลา 19:09 iDjay <notifications@github.com> เขียนว่า:

**Comment by iDjay** [comment]
Quick update, it's happening with LTE connection too, short dropouts and AdGuard reconnects.

**Comment by iDjay** [comment]
@zzebrum do you Need some more assistance? It's actually unusable for me so I disabled AdGuard DNS.

**Comment by zzebrum** [comment]
@iDjay background fetch is happening about  once at 3 hours

**Comment by iDjay** [comment]
> @iDjay background fetch is happening about  once at 3 hours

Okay so maybe that's the "issue". I closed the thread because I know that my internet router is having some VPN connection issues which will be resolved with the Software Update by the end of the year.

**Comment by iDjay** [comment]
Quick update: I got a new WLAN repeater from AVM:

https://avm.de/produkte/fritzwlan/fritzrepeater-2400/

Which is connected to my FritzBox Cable 6591.

I noticed with the Fritz WLAN App (speedtest) that as soon as the Connection switches from my router to my repeater the speed drops to 0 kbit's. These are exactly the WLAN dropouts which I still have when switching between WLAN and LTE.
