### ISSUE TITLE
The 3rd and 4th photos for AG Pro on Taiwan app store are wrong language.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1578]
https://apps.apple.com/tw/app/adguard-pro-adblock/id1126386264

Wrongly use Chinese Simplified.
<details><summary>Screenshot:</summary>

![image](http://i.imgur.com/Cl6B2yO.png)
</details><br/>

They should be Chinese Traditional.
You can get correct photos from regular AG on app store.
https://apps.apple.com/tw/app/adguard-%E5%BB%A3%E5%91%8A%E5%B0%81%E9%8E%96-%E9%9A%B1%E7%A7%81%E4%BF%9D%E8%AD%B7/id1047223162

**Comment by lancelot-moon** [comment]
Check later.
Already fixed.

**Comment by lancelot-moon** [comment]
Weird.
When opening the link by browser on PC or Android, we can see this issue.
But it’s normal when opening the link by App Store on iOS.

**Comment by ameshkov** [comment]
Can confirm, wrong screenshots for one of the resolutions.
