### ISSUE TITLE
Return color highlight for domains being resolved by DNS server

### ISSUE THREAD

**Issue by pengelana** [AdguardTeam/AdguardForiOS#1579]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

Is it possible to add coloring like previous Adguard Pro version when resolver return 0.0.0.0/127.0.0.1 for A and ::/::1 for AAAA Record? 

It will be helpful to to know which domain being blocked by resolver.

**Comment by lancelot-moon** [comment]
Yes, the green, red and yellow for DNS log of AG Pro v2 were ever user's idea.
The words are colorful, which is better than using color for the background.
Dislike the display of filtering log in AG for Android.
Under dark mode, the display isn't good.

**Comment by ameshkov** [comment]
> Is it possible to add coloring like previous Adguard Pro version when resolver return 0.0.0.0/127.0.0.1 for A and ::/::1 for AAAA Record?

Yep, we'll do that.

Additionally, we should consider "REFUSED" status blocked as well.
