### ISSUE TITLE
ios pro和free版本相比没有太大的变化

### ISSUE THREAD

**Issue by Vanjwu** [AdguardTeam/AdguardForiOS#158]
pro版仅仅增加了一个VPN模式，还和我的其它vpn软件相冲突，并且规则在中国并不好用。后期有没有增加其它功能的可能性？

**Comment by Vanjwu** [comment]
Pro version only adds a VPN mode, but also, and my other vpn software conflict, and the rules in China is not easy to use. Is there any possibility of adding other features later? Otherwise I can not find the reason to buy pro version.

**Comment by ameshkov** [comment]
@Vanjwu are you sure it conflicts with any third party VPN app?

For instance, we've tested it along with F-secure VPN #153 and it worked well.
However, I am not sure about all other VPN apps, we should check it. Which one do you use?

**Comment by Vanjwu** [comment]
The shadowsocksrocket .Could you have to add servers in China?

**Comment by ameshkov** [comment]
Adguard is not a real VPN, so we have no VPN servers at all.

We'll test AG Pro with shadowrocket:
https://github.com/AdguardTeam/AdguardForiOS/issues/162

**Comment by Vanjwu** [comment]
Adding ad filtering rules is a feature of adguard. We recommend adding and exporting personal ad filtering rules.

**Comment by ameshkov** [comment]
Yeah, I agree, we will add it eventually.

Also it'd better if you file new feature requests as a separate github issues.
