### ISSUE TITLE
Feature Request - Separate Region Specific List in another Category in Settings

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#1583]
Is it possible to seperate Regional Specific Blocklist in Safari Content Blocker? At the moment having English and multiple Regional List like Chinese, Korean, etc, goes more than 50K under General.

Probably have a separate one specific for Regional / Other Language Blocklist? Making the supported number from 300K to 350K.

A separate Regional Category in the Safari Settings e.g. AdGuard - Regional or AdGuard Pro - Regional

1Blocker has it separate. 😊☺️

**Comment by zzebrum** [comment]
please, read [this](https://github.com/AdguardTeam/AdguardForiOS/issues/1235#issuecomment-645901808)

closed as dup.
