### ISSUE TITLE
DNS filter should deduplicate between sources

### ISSUE THREAD

**Issue by javabean** [AdguardTeam/AdguardForiOS#1586]
### Issue Details

- **AdGuard version:** 4.0.1
- **Device model and storage size:** multiple (iPhone 7, iPad mini 4, iPad Air)
- **Operating system and version:** 13.5.1, 12.4.7

### Expected Behavior

In the DNS filter section, add 2 sources URLs which should contain the same rules (say: 1000 each).
Enable both filters.
The total number of filters should read "1000 rules activated"

### Actual Behavior

The total number of filters reads "2000 rules activated", which is the sum of the 2 (identical) filter sources.
This means AdGuard does not deduplicate between sources.

### Additional Information

AdGuard DNS filter is implemented as an iOS Network Extension which has very limited memory (documented in #745 to ~90K rules maximum).
In order to optimize its effectiveness, AdGuard should deduplicate entries.

**Comment by Maxim-Butov** [comment]
The total number shows the sum of all rules that have been added. But we store only a unique set of rules in the memory.

**Comment by javabean** [comment]
Shouldn’t we display the # of rules effectively in memory instead? This is a far more useful metric than the total number of rules (before deduplication)!
