### ISSUE TITLE
Does the application block CNAME?

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdguardForiOS#1587]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - Aguard Pro/Adguard 4.0.1
- **Device model and storage size:**
  - iPhone 8 Plus
- **Operating system and version:**
  - 13.5.1

### Actual Behavior

I tried adding rule lines to exclude the domain `@@||pagead2.googlesyndication.com^`, but there are rules to block `||doubleclick.net^` domains. When I checked the logs I saw that the domain was still not blocked in CNAME.

I remember introducing version 4.0 that could potentially block CNAME. Do I remember wrong?

### Screenshots

<details><summary>Screenshot:</summary>

IPv4

![IMG-5887](https://user-images.githubusercontent.com/10969626/85829423-c8dacc00-b7b4-11ea-9335-b1921658c464.PNG)
![IMG-5888](https://user-images.githubusercontent.com/10969626/85829425-caa48f80-b7b4-11ea-9e44-724fc32b722a.PNG)

IPv6
![IMG-5890](https://user-images.githubusercontent.com/10969626/85829457-dd1ec900-b7b4-11ea-82e2-26636e5af48b.PNG)
![IMG-5891](https://user-images.githubusercontent.com/10969626/85829462-dee88c80-b7b4-11ea-8bb7-feb71a4aa9d5.PNG)

</details>

### Additional Information

ID: 1542905

**Comment by ameshkov** [comment]
Exclusion rules have higher priority anyways
