### ISSUE TITLE
iOS 14 adds native support for encrypted DNS (DoH+DoT)

### ISSUE THREAD

**Issue by antoinelibert** [AdguardTeam/AdguardForiOS#1589]
### Problem Description

Apple introduced system wide support for DoH and DoT in iOS 14. Using Apple framework will further optimize the user experience (no device VPN) and increase battery life.

### Additional Information

More info here: https://developer.apple.com/videos/play/wwdc2020/10047

**Comment by zznosar** [comment]
+1 for this.

**Comment by ameshkov** [comment]
> Apple introduced system wide support for DoH and DoT in iOS 14. Using Apple framework will further optimize the user experience (no device VPN) and increase battery life.

The problem with it is that in this case you won't be able to see what DNS queries are made in the app.
Also, you won't be able to block/unblock them locally.

**Comment by s-crypt** [comment]
@ameshkov It should still be an option regardless, maybe under advanced settings.

**Comment by ameshkov** [comment]
Yeah, I agree

**Comment by zznosar** [comment]
I hope this is still track under 4.1 ✌🏻✌🏻✌🏻Probably put this option in Advance Settings and have a warning indicating that using the default ios framework, the session logs will not be available, or something like that... (if its not really available)

**Comment by antoinelibert** [comment]
Hello,

A competitor DNS service has made an online mobileconfig generator which enable DoT/DoH system wide without an app.

Maybe something to think on (may be easier to make too).

**Comment by ameshkov** [comment]
Like this? https://adguard.com/en/blog/encrypted-dns-ios-14.html

**Comment by antoinelibert** [comment]
Yes but their could actually be customized and generated on the fly (like excluding Wifi network)

**Comment by zznosar** [comment]
> Yes but their could actually be customized and generated on the fly (like excluding Wifi network)

That’s nextdns, but adGuard is different than nextdns. Nextdns requires a Config ID to work. AdGuard doesn’t. 
Also, nextdns is only focuses on dns as their product. AdGuard focuses on multiple apps. AdGuard dns is just one of those.
I rather have adGuard focus in the full featured app (both ios and mac) than wizard like creating a config profile page like nextdns. There is already an existing page created for us by the adGuard team. I think that’s enough until the apps support it.

**Comment by HongJheLi** [comment]
Really needs this feature. VPN sometimes causes issues when switching between mobile and Wi-Fi network.
