### ISSUE TITLE
Adguard pro 

### ISSUE THREAD

**Issue by Masterj2700** [AdguardTeam/AdguardForiOS#159]
Would I be able to be re-added to the test flight for Adguard pro as I lost access?  Thanks!  Email is steinerja29@gmail.com

**Comment by vbagirov** [comment]
@Masterj2700 I have removed you as a tester and then readded again. Please check if you received the invitation.

**Comment by vbagirov** [comment]
@Masterj2700 it is possible that you do not receive notifications because we currently do not have any active test builds. Once we add one, the notification will be automatically sent to your email.
