### ISSUE TITLE
Lost network connection when automatically switching networks (with IPv6)

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdguardForiOS#1592]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - Adguard Pro v4.0.1
- **Device model and storage size:**
  - iPhone 8 Plus
- **Operating system and version:**
  - 13.5.1

### Actual Behavior

After iOS automatically switches new wifi (with IPv6 connection), the entire network connection is lost. I have to turn the VPN off and on again in the app. After that, everything connected to the network is normal. I have attached the log before and after the error (with video recording).

### Screenshots

<details><summary>Screenshot:</summary>

![IMG-5963](https://user-images.githubusercontent.com/10969626/86196485-91d23500-bb7d-11ea-872f-c219ed3557d2.PNG)
![IMG-5964](https://user-images.githubusercontent.com/10969626/86196491-939bf880-bb7d-11ea-89b9-05cca7b7ba1e.PNG)
![IMG-5965](https://user-images.githubusercontent.com/10969626/86196495-94348f00-bb7d-11ea-834e-6b4056b6ea99.PNG)

</details>

### Additional Information

ID: 1542905

**Comment by ameshkov** [comment]
@bigdargon so one network has IPv6 address, and the second one does not?

**Comment by akmLaVx** [comment]
Logs from 1542905 have arrived

**Comment by bigdargon** [comment]
> @bigdargon so one network has IPv6 address, and the second one does not?

@ameshkov WiFi network before automatically connecting to the new WiFi has no IPv6 connection

**Comment by ameshkov** [comment]
Both are wi-fi networks?

**Comment by bigdargon** [comment]
No. New wifi network when ios automatically connects, has full ipv6 connection

**Comment by bigdargon** [comment]
It seems adguard's vpn is having problems with ipv6 connections

**Comment by ameshkov** [comment]
I am just trying to figure out properties of both networks at this point.

The problem may be that AdGuard does not adapt properly to the new network.

Could you please make a screenshot like [this](https://user-images.githubusercontent.com/10969626/86196491-939bf880-bb7d-11ea-89b9-05cca7b7ba1e.PNG) for the second network?

**Comment by bigdargon** [comment]
Screenshot that is automatically connected ios wifi network (with ipv6).  You mean the wifi network (without ipv6) before the network switch?
![96C86D04-EDE4-48F3-BE16-00CC45624BE1](https://user-images.githubusercontent.com/10969626/86477011-ce668200-bd71-11ea-9713-51dbaeb5f72a.png)

**Comment by ameshkov** [comment]
Yeah, I need to see both networks properties

**Comment by Maxim-Butov** [comment]
@bigdargon , any news?

**Comment by bigdargon** [comment]
> @bigdargon , any news?

@Maxim-Butov What else do I need to share?  I have screenshots on the 2 networks before and after connecting.  Can you explain more about what I need to share?

**Comment by bigdargon** [comment]
@Maxim-Butov I have sent additional application logs, wifi network details in the video recording. Hope it helps you!

**Comment by Maxim-Butov** [comment]
Logs received, thanks!

**Comment by bigdargon** [comment]
@Maxim-Butov This problem only affects full-tunnel mode, split-tunnel mode does not affect.

**Comment by bigdargon** [comment]
I sent more logs in split tunnel mode. Hope to help the Adguard team.

**Comment by akmLaVx** [comment]
Confirm, we've received the logs. Available in support ticket 1542905

**Comment by Chinaski1** [comment]
Two users from [AdGuard forum](https://forum.adguard.com/index.php?threads/ios-14-public-beta-3-adguard-pro-no-internet.39163/#post-200697) faced similar issues.
Logs are added to NCloud.

**Comment by Chinaski1** [comment]
HelpDesk ID: 1764594
Archive added to NCloud.

**Comment by bigdargon** [comment]
Checked and still affected.  I have attached the application log by email before and after restarting VPN.

**Comment by akmLaVx** [comment]
Fresh batch of logs available in ticket 1542905.

**Comment by ameshkov** [comment]
@bigdargon the newly published beta version (521) now has a switch to enable debug-level logs.

Could you please enable it, reproduce the issue and send us the new log?

**Comment by bigdargon** [comment]
@ameshkov I just got build 516. I will definitely test this bug with the latest beta.

**Comment by ameshkov** [comment]
Check Testflight, build 521 should be already available

**Comment by bigdargon** [comment]
Tested 2 times on build 526, the results have no effect.  May have been successfully fixed!

**Comment by ameshkov** [comment]
> I have attached the log in debug mode. Hope to help the team!

Could you please send it to devteam@adguard.com?

**Comment by bigdargon** [comment]
@ameshkov Forwarded

**Comment by vozersky** [comment]
@bigdargon hello! we've just pushed a new version to TestFlight, please test it, if you have a chance, this issue should be resolved now

**Comment by bigdargon** [comment]
Tested and not affected at v5.0.3 (534) :tada:

**Comment by vozersky** [comment]
@bigdargon great, thanks! one more beta tonight, hopefully the last :)

**Comment by bigdargon** [comment]
Build 546 has no errors. Thanks Adguard team! 🎉 🎉
