### ISSUE TITLE
Wi-Fi and Mobile Data both active at the same time with VPN tunnel

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForiOS#1593]
### Issue Details

At random times when a Wi-Fi network is present, the AdGuard VPN tunnel uses both an active Mobile Data connection and a Wi-Fi connection at the same time.

iOS will show the Mobile Data icon alongside the VPN icon, but iOS Settings shows an active Wi-Fi connection as well.

- **AdGuard version:**
  -  4.0.1 (495)
- **Device model and storage size:**
  -  iPhone 11 64GB
- **Operating system and version:**
  -  iOS 13.5.1

### Expected Behavior
The VPN tunnel uses either Mobile Data or Wi-Fi, and will only use one, the one active visible connection shown in the top right corner of iOS.

### Actual Behavior
The VPN tunnel uses both connections and IPs at the same time.

The 4G icon appears, even though I am still connected to Wi-Fi as shown in iOS settings, and can visit local 192.168.x.x addresses. However, all internet traffic uses my mobile data, and ‘What is my IP’ services for example displays my IP address from my mobile service instead.

### Screenshots

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/65204836/86201837-eb4d5a80-bba3-11ea-95ba-67e66ae680d7.jpeg)

![image](https://user-images.githubusercontent.com/65204836/86201826-e38db600-bba3-11ea-8f53-8d6b5b325463.jpeg)

![image](https://user-images.githubusercontent.com/65204836/86202553-deca0180-bba5-11ea-9c57-a0424583b7b7.jpeg)
</details>

### Additional Information

Full tunnel mode is being used.

- Restart protection on network change is enabled.
- IPv6 is not being used.
- Manually restarting protection, Wi-Fi or Mobile Data will resolve the issue.
- I have exported logs during this issue occurring and sent it to the Apple AdGuard email address.

**Comment by Maxim-Butov** [comment]
Try to set Split-Tunnel mode in app advanced settings.

**Comment by planet0** [comment]
I’ve now switched it over - I’ll see how this goes.

How much a difference does it make compared to full-tunnel? I read that iOS might bypass the VPN connection as a result.

**Comment by Maxim-Butov** [comment]
The iOS can turn off the VPN for a minute if the response from the DNS-server is late. After some time, VPN resumes work.
Usually in this mode, ads are blocked just as well.

**Comment by planet0** [comment]
Thank you @Maxim-Butov, since leaving it on split mode, the issue has not reoccurred.

I also feel more comfortable with this mode after your explanation.
