### ISSUE TITLE
Safari filtering stops working suddenly

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForiOS#1594]
### Issue Details

At some point, Safari filtering completely stops working, and ads begin to appear.

- **AdGuard version:**
  -  4.0.1 (495)
- **Device model and storage size:**
  -  iPhone 11 64GB
- **Operating system and version:**
  -  iOS 13.5.1
- **Browser or App:**
  - Safari

### Expected Behavior
Safari filtering filters in Safari as expected.

### Actual Behavior
Safari filtering stops working until manually disabled and re-enabled.

### Screenshots

<details><summary>Screenshots:</summary>

![IMG_0156](https://user-images.githubusercontent.com/65204836/86302498-3d49bb00-bc4c-11ea-9290-0f330e50aaba.PNG)

![IMG_0155](https://user-images.githubusercontent.com/65204836/86302502-4175d880-bc4c-11ea-9c9d-3405b7b0b18a.PNG)

</details>

### Additional Information

- Manually restarting protection and manually checking for an update will resolve the issue.
- I have exported logs shortly after this issue occurring and have sent it to the Apple AdGuard email address.

**Comment by Maxim-Butov** [comment]
Have you noticed any pattern? When the issue appears? To be honest in logs it seems to be working ok.

**Comment by planet0** [comment]
It has only happened once, and it was during the same time as the issues with full tunnel mode (https://github.com/AdguardTeam/AdguardForiOS/issues/1593)

Since it hasn’t reappeared, perhaps it was just a one-off issue and not worth looking into.
