### ISSUE TITLE
FaceTime call freezes/disconnects when answering the call with AdGuard DNS for mobile enabled

### ISSUE THREAD

**Issue by cn46375** [AdguardTeam/AdguardForiOS#1599]
### Prerequisites
- I am running the latest version
- I checked the documentation and found no answer
- I checked to make sure that this issue has not already been filed
- I am using split-tunnel mode for the DNS settings

### Issue details
- **AdGuard version**: AdGuard for iOS 4.0.1(495)
- **Device**: iPhone 11 Pro Max, Space Gray Unlocked 256GB
- **Operating system**: iOS 13.5.1
- **Mobile carrier**: Verizon

### Expected behavior
Incoming/outgoing FaceTime calls on the device with AdGuard for iOS installed with WiFi off and using only mobile data will not have any connection issues/interrupts, given that the mobile connectivity from both parties is fine.

### Actual behavior
Incoming/outgoing FaceTime calls when answered will result in the connection starting, but will later freeze because the connection through the AdGuard DNS VPN profile will disconnect. The mobile device will then make an effort to re-establish its cellular data connection through the AdGuard DNS VPN profile while the FaceTime call is still active, but frozen. If the connection is re-established in time, the call will resume. Otherwise, the FaceTime call will fail and disconnect before being able to re-establish the connection.

### Steps to replicate

1. Have AdGuard for iOS with DNS protection enabled (check the top left corner of the status bar under control center and note the "VPN" indicator next to the carrier name)
2. Make an outgoing, or receive an incoming FaceTime call when on cellular data
3. Upon the connection starting, notice when the video feed freezes and invoke the control center and pay attention to the top left portion of the status bar, where the "VPN" indicator that was previously there alongside the carrier name disappears
4. One of two situations will then occur from here
   - The top right portion of the status bar will at some point show that the connection to the AdGuard DNS VPN profile was re-established and the FaceTime call will resume from when the video feed froze
   - The FaceTime call will fail in the middle of the call, and will then later re-establish a connection through the AdGuard DNS VPN profile when observing the top right portion of the status bar

Logs are attached showing the issue below.
[adguardforios_logs_187072020147.zip](https://github.com/AdguardTeam/AdguardForiOS/files/4875845/adguardforios_logs_187072020147.zip)

**Comment by Maxim-Butov** [comment]
Judging by the logs, you previously had a Full tunnel mode. FaceTime is unstable with this setting, if the problem persists, check that the advanced settings has Split tunnel mode.

**Comment by cn46375** [comment]
I attached a new set of logs after a fresh reboot ensuring that only split-tunnel mode is selected. The VPN profile disconnect and reconnect still persists.

[adguardforios_logs_188072020067.zip](https://github.com/AdguardTeam/AdguardForiOS/files/4879334/adguardforios_logs_188072020067.zip)

**Comment by cn46375** [comment]
Do you need anything else other than the updated logs that I attached?

**Comment by Maxim-Butov** [comment]
We looked at the logs, but the problem is not obvious. Try disabling the “Restart protection when network changes” in General -> Advanced settings. Will there be an improvement?

**Comment by cn46375** [comment]
@Maxim-Butov After unticking the option to "Restart protection when network changes", it still causes the same issue. I've attached a log with the instance when the FaceTime call has actually failed.

[adguardforios_logs_191072020117.zip](https://github.com/AdguardTeam/AdguardForiOS/files/4898738/adguardforios_logs_191072020117.zip)

**Comment by cn46375** [comment]
I've made attempts to also swap between protocols, DNS servers, along with adding the domains specific to Apple to the allow list. None of these toggles have worked for me when trying to FaceTime on mobile data. I would have to disable DNS filtering for mobile data entirely in the AdGuard settings in order for FaceTime to function on mobile data without any sort of hiccups.

**Comment by cn46375** [comment]
Another set of logs from an iPhone Xs Max under the same software and network conditions, with the problem still occurring only when DNS protection is enabled and engaging a FaceTime call on mobile data.

[adguardforios_logs_192072020177.zip](https://github.com/AdguardTeam/AdguardForiOS/files/4906041/adguardforios_logs_192072020177.zip)
