### ISSUE TITLE
DNS over HTTPS and TLS are broken on iOS 14 Beta

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1601]
1. enable AdGuard DNS
2. switch the connection once to LTE then back to wifi
3. Wifi Connection doesn‘t work anymore
4. LTE works fine

iOS 14 Beta 2, AdGuard 4.0.1

Workaround: delete the VPN profile until it‘s fixed.

Let me know if you need my screen recording.

**Comment by Maxim-Butov** [comment]
Unable to retry the bug. Please send the app logs.

**Comment by iDjay** [comment]
Sent + screen recording video with the issue.

**Comment by akmLaVx** [comment]
Logs available in helpdesk ticket 1938768.

**Comment by Maxim-Butov** [comment]
Thanks for the logs. Try enabling in advanced settings "restart when network changes" option.

**Comment by iDjay** [comment]
> Thanks for the logs. Try enabling in advanced settings "restart when network changes" option. 

Does not fix the issue.

**Comment by Maxim-Butov** [comment]
Does your problem recur with any dns server? Try changing to another one and try again.
This is for statistics.

**Comment by Chinaski1** [comment]
Looks like one more user faced a similar issue
HelpDesk ID: 2793594
Archive with the log files is added to NCloud.

**Comment by iDjay** [comment]
Still happening on iOS 14 beta 3

**Comment by Sissing** [comment]
I'm having the same issue. For me it helped to change to DNSCrypt or Regular from the AdGuard DNS.
iOS 14 beta 3 - AdGuard 4.0.1

**Comment by iDjay** [comment]
> I'm having the same issue. For me as a workaround it helped to change to DNSCrypt or Regular from the AdGuard DNS.
> iOS 14 beta 3 - AdGuard 4.0.1

True, it seems to be a problem with DNS over TLS only.

**Comment by iDjay** [comment]
> I'm having the same issue. For me as a workaround it helped to change to DNSCrypt or Regular from the AdGuard DNS.
> iOS 14 beta 3 - AdGuard 4.0.1

True, only DNS over HTTPS and TLS seem to be broken on iOS 14.

**Comment by Chinaski1** [comment]
One more user faced a similar issue: 432180
Logs are added to NCloud.

**Comment by neilio** [comment]
Confirming DNS over HTTPS here as well. I will post logs when I have a minute.

**Comment by iDjay** [comment]
> I'm having the same issue. For me as a workaround it helped to change to DNSCrypt or Regular from the AdGuard DNS.
> iOS 14 beta 3 - AdGuard 4.0.1

DNSCrypt is incredible slow for me. How does it work for you?

**Comment by Sissing** [comment]
@iDjay I don't experience any network issues with DNSCrypt. It works fine on my network.

**Comment by ameshkov** [comment]
Any changes in the new beta (4.0.2)?

**Comment by iDjay** [comment]
> Any changes in the new beta (4.0.2)?

Please invite me to it :)

**Comment by ameshkov** [comment]
@iDjay 

Plz send a message to apple@adguard.com, mention your Apple ID email.

**Comment by ameshkov** [comment]
@iDjay we haven't received anything yet:( You can also try `devteam@adguard.com`

**Comment by iDjay** [comment]
> Any changes in the new beta (4.0.2)?

Seems to be fixed, yes :)

**Comment by ameshkov** [comment]
Awesome, thanks for testing it!
