### ISSUE TITLE
No Connectivity with DNS Protection Enabled on Hotspot in iOS 14

### ISSUE THREAD

**Issue by Ryan-Goldstein** [AdguardTeam/AdguardForiOS#1603]
### Issue Details

Running iOS 14 public beta 2 on an iPhone XR, while connected to a hotspot and with DNS Protection enabled in Adguard, there is no connectivity. It worked fine in iOS 13.

- **AdGuard version:**
  - 4.0.1(495)
- **Device model and storage size:**
  - iPhone XR, 64 GB
- **Operating system and version:**
  - iOS 14 public beta 2 (18A5319i)

### Expected Behavior

Connectivity works with DNS Protection enabled while connected to a hotspot.

### Actual Behavior

There is no connectivity with DNS Protection enabled while connected to a hotspot.

### Additional Information

The Testflight version of Cloudflare's 1.1.1.1 app appears to have been updated a few weeks ago that might have been to fix the same or a similar issue (version 5.4 (2007031616.1)). And indeed, there is connectivity with the 1.1.1.1 app redirecting DNS requests while connected to a hotspot.

From the changelog for that version: "... improved DNS compatibility for iOS 14"

**Comment by Maxim-Butov** [comment]
Please send the application logs with an emerging problem.(settings - advanced - export logs).

**Comment by Ryan-Goldstein** [comment]
Here are the logs: [adguardforios_logs_202072020117.zip](https://github.com/AdguardTeam/AdguardForiOS/files/4948735/adguardforios_logs_202072020117.zip)

Prior to exporting those logs, I deleted and reinstalled AdGuard, connected to a hotspot with AdGuard enabled and tried connecting to www.example.com and www.example.net, which didn't load, then connected to 1.1.1.1, which did load (as expected, since no DNS resolution is done). I then disabled AdGuard's DNS protection and was able to load www.example.org and other sites over the hotspot as expected.

I then switched to WiFi and experienced some other issues connecting, turned off the 'Restart protection when network changes' option, and eventually I was able to get everything working with AdGuard enabled over WiFi.

Let me know if there's anything else you need to be able to reproduce this issue.

**Comment by zzebrum** [comment]
@Ryan-Goldstein is the issue still reproducible on your side?

**Comment by Ryan-Goldstein** [comment]
> @Ryan-Goldstein is the issue still reproducible on your side?

I just checked, and as of iOS 14.4 (18D52) and AdGuard for iOS 4.1.0(621), using DNS Protection with AdGuard DNS (DNS-over-QUIC), it's working as expected with full connectivity. So I'm closing out this issue.

Thanks, AdGuard team!
