### ISSUE TITLE
Adguard Pro VPN constantly disconnects and reconnects in iOS13

### ISSUE THREAD

**Issue by narwhaljack** [AdguardTeam/AdguardForiOS#1604]
Using the Adguard DNS, on page load requests, the VPN will disconnect and then immediately reconnect before the page load completes. That means that before any interaction on iOS involving using a data or WiFi connection, there is significant lag before data transfer takes place. This very same issue was reported by a user in November of last year:

https://github.com/AdguardTeam/AdguardForiOS/issues/1339

and it was closed out by the Adguard team, promising a total rebuild of the Adguard Pro application. 

The issue still persists in the most recent update.

**Comment by narwhaljack** [comment]
Devs, please let me know if there is anything error logging collected in the app that I might be able to access and post here to assist in resolving this.

**Comment by Maxim-Butov** [comment]
Please send logs from the application (settings - advanced - export logs). We'll see it and try to fix the problem.

**Comment by narwhaljack** [comment]
[image: Zip Archive]
adguardforios_logs_1990720201…
<https://drive.google.com/file/d/1o1BrfLaPYT2P_2_gRgBOh4zxPSouH73k/view?usp=drivesdk>

Kindly see the attached log export and let me know if there’s anything else
I can provide you with. Thank you for looking into this!

Best,

Jake

**Comment by Maxim-Butov** [comment]
Your google account is closed, I can not access the logs. Please share the file in the access settings.

**Comment by narwhaljack** [comment]
Please check if this link works:

https://drive.google.com/file/d/1o1BrfLaPYT2P_2_gRgBOh4zxPSouH73k/view?usp=drivesdk

If not I will log into my computer at home tonight and upload the file
directly.

**Comment by Maxim-Butov** [comment]
Now everything is ok, thanks.

**Comment by Maxim-Butov** [comment]
The logs are accepted, thanks.

**Comment by vozersky** [comment]
Please reopen if it still occurs
