### ISSUE TITLE
Encrypted DNS in iOS 14

### ISSUE THREAD

**Issue by Ryan-Goldstein** [AdguardTeam/AdguardForiOS#1607]
### Problem Description

Adguard DNS seems a bit buggy in iOS 14 (e.g. #1601 and #1603).

### Proposed Solution

Implement the [Encrypted DNS](https://developer.apple.com/videos/play/wwdc2020/10047/) feature introduced in iOS 14 if possible rather than using a local VPN.

### Alternatives Considered

Addressing the bugs in iOS 14 with a local VPN is an alternative, but it's probably better to use the recommended method of Encrypted DNS unless it breaks AdGuard's core functionality due to Apple-imposed limitations on the use of Encrypted DNS.

### Additional Information

NextDNS announced a public [TestFlight beta](https://testflight.apple.com/join/AFDFPLP3) yesterday using the Encrypted DNS functionality in iOS 14. This would also permit users to connect through a VPN while still using AdGuard's DNS Protection. See [this report](https://www.reddit.com/r/nextdns/comments/hw0uog/best_of_both_worlds/) on Reddit of someone using NextDNS and MullvadVPN simultaneously.

**Comment by Ryan-Goldstein** [comment]
As a follow-up to the Additional Information section mentioning being able to use a VPN alongside AdGuard'sDNS Protection, according to the [Encrypted DNS](https://developer.apple.com/videos/play/wwdc2020/10047/) video, starting at 5:41, it looks like connections using a (true) VPN will use the VPN's DNS settings:

> Some aspects of compatibility are handled for you automatically. For these, you don't need to specify network rules. ... If a VPN is active, resolution within the VPN tunnel will use the VPN's DNS settings and not your system-wide settings.

Still certainly worth implementing this recommended way to configure system-wide secure DNS if possible, though!

**Comment by zznosar** [comment]
+1 for this!

**Comment by zzebrum** [comment]
closed as dup of #1589
