### ISSUE TITLE
Allow blocking domains with user filter rules

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#161]
For instance, if I add `||iadsdk.apple.com^`, access to that domain should be blocked on the DNS level.

**Comment by jo2dan23** [comment]
Awesome!

**Comment by ameshkov** [comment]
> Would we be able to override the whitelisting of domains that whitelisted from your side? Like scorecardresearch for example

Yeah, you will. Adguard Pro is not aware of the actual filter used on the DNS side, it just gets the result (blocked or not blocked). So if you decide to block anything, DNS rules won't mess with your decision.

**Comment by jo2dan23** [comment]
Cool. Is this in the latest adguard beta? I still wasnt invited yet to testflight program

**Comment by ameshkov** [comment]
> Cool. Is this in the latest adguard beta?

Not yet, but it's planned for it.

> I still wasnt invited yet to testflight program

Inviting @vbagirov here then.

**Comment by jo2dan23** [comment]
@ameshkov this would be a very useful feature for saving more data and speeding up internet! Very excited

**Comment by Stillness-2** [comment]
commit 81ef592
