### ISSUE TITLE
Сортировка DNS-запросов в разделе "Активность"

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardForiOS#1610]
Данный запрос относится к ранее открытому мной и ошибочно закрытому запросу #1573. AdGuard для iOS до сих пор показывает неправильную статистику при выборе сортировок "показывать только заблокированные" и "показывать только разрешённые". Раздел блокированных всегда пустой, хотя явно были заблокированные рекламные куки, а разрешённых наоборот содержит как разрешённые, так и блокированные. Нужно это исправить, чтобы раздел блокированных куки показывал их, если надо, а разрешённых показывал только разрешённые. Также в разделе "показывать все запросы" сделать выделение цветом блокированных запросов, например красным, чтобы они выделялись среди прочих.

**Comment by zzebrum** [comment]
@Vitalik93 если у вас добавлены днс подписки, то все должно корректно отображаться, и заблокированные, и разрешенные. 
А для обычной фильтрации днс сервером специально убрано выделение цветом и вообще любое упоминание о том, что запрос заблокирован. Иначе были трудности с публикацией очередного обновления в аппстор.

**Comment by Vitalik93** [comment]
> 
> 
> @Vitalik93 если у вас добавлены днс подписки, то все должно корректно отображаться, и заблокированные, и разрешенные.
> А для обычной фильтрации днс сервером специально убрано выделение цветом и вообще любое упоминание о том, что запрос заблокирован. Иначе были трудности с публикацией очередного обновления в аппстор.

Тогда зачем вообще сделали сортировку запросов по заблокированным, не заблокированным и всем, если она не работает как положено? Может убрать этот переключатель и оставить только общий список?

**Comment by zzebrum** [comment]
она работает же при использовании днс подписок блокирующих.
