### ISSUE TITLE
Access to DNS AllowList crashes AG Pro

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1613]
### Issue Details

- **AdGuard version:**
  - AG Pro 4.0.1 (498)
- **Device model and storage size:**
  - iPhone 11 Pro Max
- **Operating system and version:**
  - iOS 13.6
- **Browser or App:**
  - Safari

### Expected Behavior

AG Pro works fine. However it crashes when you access the AllowList from:
DNS Protection -> DNS Filtering -> AllowList 

### Actual Behavior

Access to DNS Protection -> DNS Filtering -> AllowList should be allowed. 

### Screenshots

Video of the crash: https://file.io/PuvFH780O32f

### Additional Information

I have the exact same settings in AG Pro on my iPad Pro 11 and there is not issue when I access the DNS AllowList menu.

**Comment by Maxim-Butov** [comment]
I couldn't repeat the bug. Also, the video link is not available. Please reload the video
 and send new logs immediately after repeating the error. Thanks.

<img width="492" alt="MaximButov rbexb" src="https://user-images.githubusercontent.com/67098694/89175954-646c1300-d591-11ea-96f1-1da10413050d.png">

**Comment by Quorum75** [comment]
To who should I resend the logs? Support@ ?

**Comment by Chinaski1** [comment]
- HelpDesk ID: 2334847
- Logs are added to NCloud

**Comment by Quorum75** [comment]
FYI I replicate my settings on AG Premium on my iPhone and I am facing no application crash when when accessing DNS AllowList menu. 

iPhone:
AG Pro Beta: **KO**
AG Beta: OK

iPad:
AG Pro Beta: OK
AG Beta: OK

**Comment by Maxim-Butov** [comment]
Not a typical UI error. We will try find a trouble, thanks.

**Comment by Quorum75** [comment]
Thanks. Let me know if I can help.

**Comment by Quorum75** [comment]
The problem appears again today in AG Pro on iPad iOS 14. 

Strangely no issue on iPhone iOS 14.

**Comment by ameshkov** [comment]
Could you please do the following: settings -> privacy -> analytics&improvements -> analytics data -> find the crash report and attach it here
