### ISSUE TITLE
Proxy certification installation when not connected to wifi

### ISSUE THREAD

**Issue by shenlihartono** [AdguardTeam/AdguardForiOS#1615]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [v ] I am running the latest version
- [ v] I checked the documentation and found no answer
- [ v] I checked to make sure that this issue has not already been filed

### Issue Details

https://kb.adguard.com/en/technical-support/how-to-install-certificate#ios

I follow the instruction here but it seems only work when connect to wifi, because i specify the local ip address (my computer) to route to, when happen when i do not connect to wifi? it does not work and the ads still showing up

- **AdGuard version:**
  -  v4.0.1 (495)
- **Device model and storage size:**
  -  iphone 8 plus 64gb
- **Operating system and version:**
  -  ios 13.6
- **Browser or App:**
  -  app name: OLX

### Expected Behavior

the filtering / blocking will work when connected to data

### Actual Behavior

the filtering does not work when connected using data  (only work when using wifi) 

### Screenshots

<details><summary>Screenshot:</summary>

![Photo 4 Aug 2020 04 03 17](https://user-images.githubusercontent.com/19544482/89227597-2d851400-d608-11ea-9a05-f557fb02f10a.jpg)

![Photo 4 Aug 2020 04 03 25](https://user-images.githubusercontent.com/19544482/89227688-4f7e9680-d608-11ea-8a4e-bae6e65db70c.jpg)

</details>

**Comment by Maxim-Butov** [comment]
To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Reproduce the issue (and remember the exact time when it happened).
2. Disable "DNS Privacy"
3. Open the app, tap "Send Feedback", select "Contact Support"
3. The mail app will be opened, **change the recipient to `apple@adguard.com` (!)**
4. Mention this issue number in the email text

**Comment by Maxim-Butov** [comment]
This instruction contain next rule: 
>Note that these devices must be in the same network as the PC or Mac that has AdGuard installed.
This is a required for the correct work of the local proxy. Wi-Fi here acts as a local subnet. If you want use AdGuard proxy filtration with mobile data or other net, your desktop need static global ip (and this ip must be entered in client AdG app settings).

**Comment by Maxim-Butov** [comment]
This instruction contain next rule:

>Note that these devices must be in the same network as the PC or Mac that has AdGuard installed.

This is a required for the correct work of the local proxy. Wi-Fi here acts as a local subnet. If you want use AdGuard proxy filtration with mobile data or other net, your desktop need static global ip (and this ip must be entered in client device settings).
