### ISSUE TITLE
Auto Update not working

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1616]
### Issue Details

After a week filters are still not update. Manual update is then required. 

- **AdGuard version:**
  - AG Pro 4.0.1 (498)
- **Device model and storage size:**
  - iPhone 11 Pro Max
- **Operating system and version:**
  - iOS 13.6
- **Browser or App:**
  - Safari

### Expected Behavior

Auto update (daily or weekly?) of Safari and DNS filters. 

### Actual Behavior

Auto update is not working on WiFi and cellular. Manual update is required. 

### Screenshots

N/A

### Additional Information

Even with « Auto Update over WiFi only » activated doesn’t help

**Comment by Maxim-Butov** [comment]
Please send logs, we try find a reason.

**Comment by Maxim-Butov** [comment]
To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Reproduce the issue (and remember the exact time when it happened).
2. Disable "DNS Privacy"
3. Open the app, tap "Send Feedback", select "Contact Support"
3. The mail app will be opened, **change the recipient to `apple@adguard.com` (!)**
4. Mention this issue number in the email text

**Comment by Quorum75** [comment]
@Maxim-Butov What you are asking is impossible. We are talking about the auto update function within AG. 
How do I know when the auto update is happening?

**Comment by Maxim-Butov** [comment]
Sorry for that, the template was sent by mistake. In any case, log files would be appreciated. And we are trying to figure out what is wrong. =)

**Comment by Quorum75** [comment]
Can't you use the log files I sent you yesterday?

**Comment by zznosar** [comment]
Do you have background refresh set to On for AdGuard?

Auto update will not work if that is disabled.

**Comment by Quorum75** [comment]
Yes.

**Comment by Eugene-Savenko** [comment]
We have a similar complaint w/ logs from another user here: 2881483

**Comment by jeremygaither** [comment]
I am seeing this issue as well, on a clean install of iOS. Logs and info emailed to `apple@adguard.com`. I performed a manual rule refresh before exporting the logs, but widget reported filters were 5 days old.

- AdGuard version:
  AG Pro 4.0.3 (544)
- Device model and storage size:
  iPhone 12 Pro
- Operating system and version:
  iOS 14.2
- Browser or App:
  Safari

**Comment by Quorum75** [comment]
@Maxim-Butov 

From where I stand the new beta v4.0.4 (585) seem to solved the issue. 

Nice work guys 👍🏻 and congratulations to the dev team. 👏🏻
