### ISSUE TITLE
VPN disconnects with manual update

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1617]
### Issue Details

When launching a manual filters update AG/VPN disconnects when it should remain activated. 

- **AdGuard version:**
  - AG Pro 4.0.1 (498)
- **Device model and storage size:**
  - iPhone 11 Pro Max
- **Operating system and version:**
  - iOS 13.6
- **Browser or App:**
  - Safari

### Expected Behavior

AG should keep the VPN connection active when updating manually the filters

### Actual Behavior

AG disconnects when updating manually the filters

### Screenshots

Video link: https://www.swisstransfer.com/d/4f2354e4-fd0c-4c70-bbc1-7c8290f161a2

Look at the VPN icon on top right.

**Comment by Maxim-Butov** [comment]
This is because DNS filters are updated as well. This is normal :)

**Comment by Quorum75** [comment]
Thanks.
