### ISSUE TITLE
Add DNSPod DoH server prompts illegal

### ISSUE THREAD

**Issue by Silentely** [AdguardTeam/AdguardForiOS#1619]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

-  I am running the latest version
-  I checked the documentation and found no answer
-  I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v4.0.1
- **Device model and storage size:**
  - iPhone Xr 
- **Operating system and version:**
  - iOS 14 beta4
- **Browser or App:**
  - Safari

### Actual Behavior

When I add a custom DoH server (https://doh.pub/dns-query), I am prompted to add an illegal upstream server

### Screenshots
![](https://ftp.bmp.ovh/imgs/2020/08/b01732a3594188ae.jpg)

**Comment by Maxim-Butov** [comment]
I could not reproduce the error, the server was added and is working successfully. Please send us logs:

> Here's what we need you to do:
> 1. Reproduce the issue (and remember the exact time when it happened).
> 2. Disable "DNS Privacy"
> 3. Open the app, tap "Send Feedback", select "Contact Support"
> 3. The mail app will be opened, **change the recipient to `apple@adguard.com` (!)**
> 4. Mention this issue number in the email text

**Comment by Silentely** [comment]
Sorry, just tried to reproduce the problem. Can already be added and saved successfully. The problem is currently resolved.
