### ISSUE TITLE
Incompatibility with Amcrest View Pro

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#1620]
### Issue Details

- **AdGuard version:**
  - 4.0.1.495
- **Device model and storage size:**
  - Unspecified iPhone
- **Operating system and version:**
  - iOS 14.0
- **Browser or App:**
  - https://apps.apple.com/us/app/amcrest-view-pro/id950978683

### Actual Behavior

When protection is enabled, user is unable to view security cam footage. The app times out.

### Screenshots

_Unavailable_

### Additional Information

Logs: see support ticket 1580549

**Comment by Aydinv13** [comment]
Hello! Do you still have this problem after Adguard and iOS updates?

**Comment by jtb1234** [comment]
Hey there. Everything seems to be working now thank you for the follow up.

On Dec 14, 2020, at 4:45 AM, Aydinv13 <notifications@github.com> wrote:

﻿

Hello! Do you still have this problem after Adguard and iOS updates?

**Comment by Aydinv13** [comment]
Thank you for a feedback. This issue will be closed but you can write here anytime
