### ISSUE TITLE
Несколько замечаний по последней версии.

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardForiOS#1624]
Обновился сегодня до последней версии (4.0.2), сразу есть несколько замечаний:
1) Кнопка удаления VPN профиля работает некорректно - срабатывает при нажатии на кнопку выше (туннельный режим) и не срабатывает, если нажать нужную.

![IMG_0670](https://user-images.githubusercontent.com/34383288/90581145-d025c100-e1ca-11ea-969e-3ecaf4f90154.PNG)

2) Куча не переведённого на русский текста.

![IMG_0671](https://user-images.githubusercontent.com/34383288/90581169-dcaa1980-e1ca-11ea-9693-7b10ed006899.PNG)
![IMG_E0675](https://user-images.githubusercontent.com/34383288/90581185-e6cc1800-e1ca-11ea-9be3-3fcdfd072e25.JPG)
![IMG_E0669](https://user-images.githubusercontent.com/34383288/90581202-f0558000-e1ca-11ea-8280-5b1a365ddded.JPG)
![IMG_E0676](https://user-images.githubusercontent.com/34383288/90581211-f77c8e00-e1ca-11ea-9e48-25eaf0707b08.JPG)
![IMG_E0674](https://user-images.githubusercontent.com/34383288/90581223-0105f600-e1cb-11ea-9451-516ad92a7f56.JPG)

3) Не перезагружается автоматически страница, для которой была отключена фильтрация.
4) DNS защита перезапускается, если в момент её работы проверить обновления фильтров.

**Comment by Maxim-Butov** [comment]
Здравствуйте! Большое спасибо за обратную связь!
Тк на каждую проблему желательно создавать отдельную задачу, то эту я закрою. Вместо нее создал две отдельные задачи, и отметил Ваше участие в них.
1) Кнопку обязательно [починим](https://github.com/AdguardTeam/AdguardForiOS/issues/1625) .
2) С локализациями тоже [разберемся](https://github.com/AdguardTeam/AdguardForiOS/issues/1626) .
3) Если я правильно вас понял, то перезагрузка страницы - уже функционал самого Safari, и у нас нет возможности реализовать такую функцию.
4) Рестарт VPN туннеля это нормально, тк обновляются так же DNS фильтры. Это сделано целенаправленно.

**Comment by Vitalik93** [comment]
>     3\. Если я правильно вас понял, то перезагрузка страницы - уже функционал самого Safari, и у нас нет возможности реализовать такую функцию.

Раньше, насколько помню, страница сама перезагружалась после выключения на ней фильтрации.
