### ISSUE TITLE
iOS content blocking for non-safari

### ISSUE THREAD

**Issue by zaheerhakim** [AdguardTeam/AdguardForiOS#1627]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Additional Information

On iOS and iPadOS for AdGurad app add a option for content blocking filters to be added in non-safari browser for example Brave Browser.

**Comment by Maxim-Butov** [comment]
Unfortunately, on IOS, only the Safari browser allows you to somehow influence the filtering. This is due to internal Apple policies.
