### ISSUE TITLE
Incorrect icons under "Protection"

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#1628]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS 4.0.2
- **Device model and storage size:**
  - Irrelevant
- **Operating system and version:**
  - iOS 13

### Screenshots

<details><summary>Screenshot:</summary>

![image0](https://user-images.githubusercontent.com/33634917/90918093-c11e5900-e3ec-11ea-8d1b-9999440a42dd.jpeg)

</details>

### Additional Information

Helpdesk ticket ID: 2654499

**Comment by Maxim-Butov** [comment]
Thank! We will fix that soon. =)
