### ISSUE TITLE
Активный Граджанин - не работает кнопка "Поделиться в Fb"

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#163]
> Оказалось, что функция поделиться информацией в Facebook после голосования внутри приложения Активный гражданин не работает, окно авторизации открываетсяи тут же закрывается.
> https://itunes.apple.com/ua/app/aktivnyj-grazdanin/id873648765?mt=8

Application version: 1.1.0.21
Application lifetime: 2016-10-01 06:11:13 +0000

Device: iPhone
Platform: iOS
OS: 10.0.2
ID: C4E7E024-E994-48AA-8024-8A7A733E8634

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.96.1 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.81 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.12 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.4.59 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.40.22 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.2 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.42 Enabled=YES

**Comment by gshumihin** [comment]
I have same situation with VPN enabled. Without Adguard's VPN share option works fine.
That's how DNS log looks like:
<description>
![DNS Log](https://cloud.githubusercontent.com/assets/8577547/19383725/8e576c48-920e-11e6-9ef2-5d7cbfd41802.jpg)
</description>

**Comment by ameshkov** [comment]
I guess we need the whole log file

**Comment by gshumihin** [comment]
Tried to "share" at 18:16.
Here's log: [aktivnyj-grazdanin.txt](https://github.com/AdguardTeam/AdguardForiOS/files/533855/aktivnyj-grazdanin.txt)

**Comment by ameshkov** [comment]
@gshumihin please use fiddler instead

**Comment by gshumihin** [comment]
Here is it:
[actgrdn.saz.txt](https://github.com/AdguardTeam/AdguardForiOS/files/539417/actgrdn.saz.txt)

**Comment by Alex-302** [comment]
@gshumihin only ad domain is blocked - googleads.g.doubleclick.net
You can check it without DNS filtering, but with desktop Adguard with our filters.

**Comment by gshumihin** [comment]
With DNS disabled issue does not exist.

**Comment by Alex-302** [comment]
Try to reproduce without DNS, but with blocked `googleads.g.doubleclick.net` and 'appsflyer.co'

**Comment by gshumihin** [comment]
Reproduced this issue with blocked `googleads.g.doubleclick.net` and `appsflyer.co` by content-block Fiddler's addon. 
Here's log: [grazhdanin.saz.txt](https://github.com/AdguardTeam/AdguardForiOS/files/575754/grazhdanin.saz.txt)

**Comment by Alex-302** [comment]
I see only one blocked request
http://i83.fastpic.ru/big/2016/1107/68/3cd9e6165659a4eba4b1742802069568.png
Could you block googleads.g.doubleclick.net without DNS filtering?(filtering should be disabled on iPhone, and domain should be blocked by Fiddler ContentBlock plugin, or in other way)

**Comment by gshumihin** [comment]
DNS filtering was disabled this time.

**Comment by Alex-302** [comment]
Please try to block that domains separately.  It seems the problem is caused by blocking of `googleads.g.doubleclick.net`

**Comment by gshumihin** [comment]
Hmm. Pretty weird. Now this "share" desn't work with fiddler at all.
Here's log:
[grazhdanin2.saz.txt](https://github.com/AdguardTeam/AdguardForiOS/files/576083/grazhdanin2.saz.txt)

**Comment by Alex-302** [comment]
Strange. Did you turn off desktop AG?

**Comment by gshumihin** [comment]
Yes.

**Comment by gshumihin** [comment]
@Alex-302 some news?

**Comment by Alex-302** [comment]
No. I don't have iDevice)

**Comment by gshumihin** [comment]
Check this issue with ur iPad please.

**Comment by Alex-302** [comment]
@gshumihin I can't register here, lost my megafon sim card.

**Comment by Alex-302** [comment]
Was not reproduced with default dns. Messages were posted to twitter and FB

**Comment by vozersky** [comment]
obsolete
