### ISSUE TITLE
Have to turn off AdGuard to play Marvel Puzzle Quest

### ISSUE THREAD

**Issue by Bubba200** [AdguardTeam/AdguardForiOS#1630]
- **AdGuard version:**
  - latest TestFlight beta, and previous versions. 
- **Device model and storage size:**
  - 2019 iPad 128gb
- **Operating system and version:**
  - iPadOS 13.6.1 
- **Browser or App:**
  - Marvel Puzzle Quest

### Expected Behavior

Nothing. 

### Actual Behavior

Game becomes seriously lagged with AdGuard turned on.  Sometimes AdGuard crashes, bug reports sent from device. Turning off AdGuard causes all issues to resolve. It’s behaved this way for all 4.x releases of AdGuard 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Maxim-Butov** [comment]
We cannot find any logs from you. Please, either write the number of the ticket that was sent to technical support, or send the logs again, according to this instruction:

To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Reproduce the issue (and remember the exact time when it happened).
2. Disable "DNS Privacy"
3. Open the app, tap "Send Feedback", select "Contact Support"
3. The mail app will be opened, **change the recipient to `apple@adguard.com` (!)**
4. Mention this issue number in the email text

**Comment by Bubba200** [comment]
Logs sent, issue occurred around 8:08 pm. No crash (yet) just performance. 

Other logs in the past have been sent through crash reporter.

**Comment by Bubba200** [comment]
Here’s the header for the crash report 

date=1597959000000&sf=143441&tid=be8c9caf6749728b26c64ba6b10912f41d80bd377a97eac2b93aca1375e88f38&ttype=e","app_name":"Adguard","app_version":"4.0.2","timestamp":"2020-08-26 20:32:35.00 -0400","slice_uuid":"2215cfde-ed69-3c16-bb33-b5dadc8116ad","adam_id":1047223162,"build_version":"527","bundleID":"com.adguard.AdguardExtension","share_with_app_devs":1,"is_first_party":0,"bug_type":"109","os_version":"iPhone OS 13.6.1 (17G80)","incident_id":"17D733B1-3FC9-4A22-ABF8-839728531395","name":"Adguard","is_beta":1}
Incident Identifier: 17D733B1-3FC9-4A22-ABF8-839728531395
Beta Identifier:     9372FE38-1580-4B0E-807B-DB450F206F33
Hardware Model:      iPad7,5
Process:             Adguard [4691]
Path:                /private/var/containers/Bundle/Application/82266CE8-EAF9-480C-AC12-BF5A6D0496DD/Adguard.app/Adguard
Identifier:          com.adguard.AdguardExtension
Version:             527 (4.0.2)
AppStoreTools:       11E707
AppVariant:          1:iPad7,5:13
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                unknown
Parent Process:      launchd [1]
Coalition:           com.adguard.AdguardExtension [869]


Date/Time:           2020-08-26 20:32:35.5155 -0400
Launch Time:         2020-08-26 20:31:59.6868 -0400
OS Version:          iPhone OS 13.6.1 (17G80)
Release Type:        User
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace RUNNINGBOARD, Code 0xdead10cc
Triggered by Thread:  0

**Comment by Maxim-Butov** [comment]
Sorry, we couldn't find your logs by your message. Please try reproduce this situation with game and after send the logs by Settings->Support->Export Logs to my mail m.butov@adguard.com

And this moment:
> No crash (yet) just performance.
But you say:
>Sometimes AdGuard crashes
how to understand it?

**Comment by Bubba200** [comment]
The logs I tried to email have just the performance issue in them starting at 20:08. AdGuard didn’t crash at that time. I’ll try to resend them. 

The snip above is from the crash reporter of an earlier incident , I’m guessing you can look up the crash dump via the report id?

**Comment by Maxim-Butov** [comment]
We got logs. Try to set a system (default) dns server. Does the problem repeared?

**Comment by Bubba200** [comment]
No change.  Want another log with default dns?

**Comment by Maxim-Butov** [comment]
While the logs are not needed. Try disabling the dns filter (judging by the logs, you have it enabled), leaving the dns protection itself enabled.

**Comment by Bubba200** [comment]
No change

**Comment by Bubba200** [comment]
I’m beginning to think it’s something else.  AdGuard is completely off and I’m experiencing the issue.

**Comment by Maxim-Butov** [comment]
If the adguard dns was turned off, and the bug repeated itself, then the problem is definitely not in the our app. Since we simply cannot influence other applications with dns filtering turned off.
