### ISSUE TITLE
does not see the local DLNA media server

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdguardForiOS#1633]
the VLC program (and similar players) does not see the local DLNA media server when Adguard is enabled. Although when using NextDNS, 1111, etc., VLC normally shows the media server on the corresponding tab. I can't exclude the local network from the rules , because in this case ad blocking is disabled.

PS. However, everything works in split-tunnel mode - I just don't know how effectively ads are blocked in this case.

AdguardPro (Adguard premium) with last update. iphone 6,7 and 11 with ios 13.6

**Comment by Maxim-Butov** [comment]
The split mod is just for such cases. Use it, it shouldn't decrease the quality of ad blocking.
