### ISSUE TITLE
Не работает режим VPN без иконки

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdguardForiOS#1634]
Всем привет,

iOS 13.7, AdGuard для iOS 4.0.2 (527). Не работает режим туннелирования без иконки, перезагрузка и переустановка профиля VPN не помогает. К тому же при попытке переключить режим постоянно зачем-то вызывается функция удаления VPN профиля, хотя для этого есть отдельный раздел:
https://yadi.sk/i/tn5mkpXVmHYXOw

Логи:
https://yadi.sk/d/JvA_ky0GLum5cQ

Спасибо.

**Comment by Maxim-Butov** [comment]
Режим туннелирования без иконки - является "недокументированной возможностью" iOS, которую мы используем. Поэтому в описании режима есть слово "нестабильный". На каких то конфигурациях он может не работать, и мы ничего не можем с этим поделать. 
Касаемо бага в удалении VPN-профиля (задача #1625), то мы уже исправили этот маленький, но неприятный недочет в версии 4.0.3, которая выйдет со дня на день =).
