### ISSUE TITLE
Estonian filter icon uses flag of Ethiopia

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#1636]
### Issue Details

- **AdGuard version:**
  - 4.0.1
- **Device model and storage size:**
  - unspecified iPhone
- **Operating system and version:**
  - iOS 13

### Screenshots

<details><summary>Screenshot:</summary>

<img width="307" alt="photo" src="https://user-images.githubusercontent.com/33634917/92333964-38f9ae00-f092-11ea-95a8-d779c9e10511.png">

</details>

**Comment by Maxim-Butov** [comment]
Thank you for your attention, we will definitely fix this mistake =)
