### ISSUE TITLE
AdGuard no longer blocking ads within Yahoo Mail app

### ISSUE THREAD

**Issue by aaronzorzi** [AdguardTeam/AdguardForiOS#1637]
It was working like a charm before, but after a recent update that the yahoo mail app implemented I am once again seeing that annoying little ad at the top of my inbox. Running iOS 13.7 on iPhone XS Max with AdGuard Premium 4.0.2. If there is a custom filter/rule I can use to rid myself of these ads I’d greatly appreciate the tip. Thanks!
![AAC91725-9604-428D-B3AD-E9E162F0076B](https://user-images.githubusercontent.com/58090646/92823135-f0e0d100-f39a-11ea-9d72-e083c75f6d65.jpeg)

**Comment by zznosar** [comment]
Mine works well. I’m using DNSCrypt AdGuard DNS and also has the Steven Black’s Host File + AdGuard Tracking Protection filter list.

**Comment by aaronzorzi** [comment]
> Mine works well. I’m using DNSCrypt AdGuard DNS and also has the Steven Black’s Host File + AdGuard Tracking Protection filter list.

I changed my DNS to DNSCrypt (I was using over HTTPS before) and added that host file and I’m still seeing the ads in my Yahoo mail app unfortunately  :(

I have almost every filter enabled, so I’m not sure what’s going on that it’s managing to get through when it was working so well before.

**Comment by zznosar** [comment]
Have you checked the logs in the app if its blocking or not?

Mine has this in the logs:

![94D6F649-27EE-4172-9CA9-E67551CF4BF1](https://user-images.githubusercontent.com/27464836/93217098-e9129980-f7ab-11ea-9bc4-d644dc6de8e1.png)

**Comment by aaronzorzi** [comment]
Yeah so, wow I feel bad now lol. I didn’t realize until last night when I was checking the logs that I could just manually block the ad requests myself. After doing so for a few different pesky URLs, the ads are gone :) I feel a little dumb haha but hey at least I learned more about what I can do with AdGuard! Thank you.

**Comment by zzebrum** [comment]
@aaronzorzi don't forget that custom DNS rules may break something in other sites/apps
