### ISSUE TITLE
Can't broadcast YouTube to TVs' nor Xbox One's YouTube apps

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#164]
<details>

![image2](https://cloud.githubusercontent.com/assets/15856304/19103106/786271ea-8add-11e6-87c0-272f3891eded.png)

![image1 2](https://cloud.githubusercontent.com/assets/15856304/19103109/7981d69c-8add-11e6-87d8-da8d22fc40da.png)

</details>

**1423882**

**Comment by Stillness-2** [comment]
@gshumihin Please test this :)

**Comment by evgeniy-ADG** [comment]
I was able to reproduce, the broadcast button is not available when you run Adguard Pro with DNS filtering enabled.

**Comment by gshumihin** [comment]
@ameshkov i guess we need Xbox One :)

**Comment by ameshkov** [comment]
I guess it could be a hardcoded limitation of the app.

@evgeniy-ADG could you please check it with any other VPN app?

**Comment by yonika** [comment]
Hi, I sent you the bug report on this issue.
I just saw this was not solved on 1.1.2 :(

But, sorry to ruin your plans on buying an Xbox One :) you can also buy a Smart TV with YouTube App. I have a Samsung SmartTV but I believe chromcast will also do it.

**Comment by ameshkov** [comment]
@yonika have you tried any other VPN app?

**Comment by Stillness-2** [comment]
This problem repeated with other VPN. This is not Adguard issue.

**Comment by yonika** [comment]
Hi,

I'm the user who opened the issue.

If you think about it, of course it happens with other VPNS... that's because they are real VPNs so they are tunneling the traffic to another network, which does not have a YouTube enabled device. The iOS device does not see other devices in the LAN when it is in a VPN.

But Adguard is a Fake VPN... and should not alter the traffic of the local LAN.

please advise.

**Comment by Stillness-2** [comment]
At this moment I don't know why this happens, Adguard really does not touch local or global traffic. Adguard changes routes traffic of the specific IP addresses  only, this is IP addresses of the Adguard DNS servers. You may to see this in our sources.

https://github.com/AdguardTeam/AdguardForiOS/blob/master/AdguardExtension/AdguardPro/tunnel/PacketTunnelProvider.m#L111 
111-153 rows

**Comment by ameshkov** [comment]
I suppose it is possible, that iOS VPN API has the same flaw as Android one: it may forbid incoming connections, which might be necessary for broadcasting.

**Comment by ameshkov** [comment]
Second thought is that YT app does an explicit check if there's any active VPN connection and disables broadcasting feature if it is.

**Comment by Stillness-2** [comment]
The second thought is similar to the truth :)

**Comment by yonika** [comment]
If what you are saying is true (about the second thought)
Then the following experiment can prove it:

Set up a VPN between the iOS device and the LAN that has the broadcast capable device (like the TV or XBOX).
Launch YouTube and check if the broadcast is showing in the App.

It should show because the communication will be tunneled to to and from the LAN. Unless it does this checking.

**Comment by ameshkov** [comment]
> Set up a VPN between the iOS device and the LAN that has the broadcast capable device (like the TV or XBOX).
> Launch YouTube and check if the broadcast is showing in the App.

> It should show because the communication will be tunneled to to and from the LAN. Unless it does this checking.

What Adguard does is even less restrictive as our VPN routes are literally empty, so traffic stays untouched.

**Comment by TheHasagi** [comment]
Reopened - 1897223.

**Comment by TheHasagi** [comment]
Problem is reproducible with any DNS.

**Comment by ameshkov** [comment]
It just means that the problem is caused by mere VPN tunnel presence :(

**Comment by Eugene-Savenko** [comment]
They say it works with the [DNSCloack app](https://itunes.apple.com/us/app/dnscloak-dnscrypt-doh-client/id1330471557?mt=8),

**Comment by zebrum** [comment]
@Eugene-Savenko we have checked and it's working. Ask user to connect a phone to a TV by entering a code in youtube settings in the phone
