### ISSUE TITLE
Protection drops when opening some apps / switching between Wi-Fi hotspots

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#1640]
### Issue Details

- **AdGuard version:**
  - 4.0.2.527
- **Device model and storage size:**
  - Unspecified iPhone
- **Operating system and version:**
  - iOS 13.5

### Actual Behavior

Launching arbitrary apps can cause AdGuard to drop protection. Switching between Wi-Fi hotspots causes AdGuard to drop protection.

### Screen recording & debug logs

See helpdesk ticket 2892055.

**Comment by Eugene-Savenko** [comment]
Similar bug:

> [...] from time to time I am facing the problem that no data are transmitted thru the VPN tunnel. It happens often if the device is restarted or the connection type switches from mobile to WLAN or the other way. It could even happen if airplane mode would be disabled. Restarting VPN when switching the connection type is activated!

AdGuard Pro 4.0.2.527
iOS 13.7

See helpdesk ticket 1671146

**Comment by ng4ever** [comment]
I am having the same issue with hotspot where dns protection just doesn't work anymore unless I disable then reenable it :( 

Will this be fixed please ?

**Comment by akmLaVx** [comment]
Got a few extra reproductions from the original user. See helpdesk ticket 2892055.
