### ISSUE TITLE
Encrypted DNS for iOS14

### ISSUE THREAD

**Issue by Silentely** [AdguardTeam/AdguardForiOS#1643]
Hello, the official version of iOS14 is currently online. When will it support iOS14 Encrypted DNS? Nextdns Testflight has supported Encrypted DNS for a long time. I look forward to the launch of Adguard

**Comment by zznosar** [comment]
Dup:

https://github.com/AdguardTeam/AdguardForiOS/issues/1589

**Comment by Silentely** [comment]
Thank you very much, looking forward to the completion of 4.1

> 重复。
> 
> 为此已经有一张票了。当前标记为版本4.1（大约是明年还是今年年底？不确定）
> 
> [＃1589](https://github.com/AdguardTeam/AdguardForiOS/issues/1589)

Thank you very much, looking forward to the completion of 4.1
