### ISSUE TITLE
TYPE65 Requests

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardForiOS#1644]
just was wondering what the type65 requests are. i didnt start seeing them til ios 14 beta. i see alot of type65 requests that aren't blocked like they should be, but that same domain that is requested is blocked on ipv6 and ipv4. is this a bug or something changed with apples new dns request system?

**Comment by jordanelliott23** [comment]
![18C60F5F-D3F2-4E61-B52A-AF30DCA651E7](https://user-images.githubusercontent.com/71462072/93518458-6e07cb00-f8f2-11ea-9631-367a11ff1bad.png)

here is example

**Comment by zznosar** [comment]
I think kts part of ios 14 based in the below:

https://support.umbrella.com/hc/en-us/articles/360049713451-DNS-Resolver-Selection-in-iOS-14-and-macOS-11

**Comment by zzebrum** [comment]
@jordanelliott23 @zznosar yeah, I found only the same info so far. Also will ask our devs about it.

**Comment by zzebrum** [comment]
not much so far - those are a new type of DNS responses `https 65` 🤷‍♀️  
but we are going to do a little research: https://github.com/AdguardTeam/DnsLibs/issues/80
