### ISSUE TITLE
Hi Vladimir, I'd love to discuss with you about my Safari Extension project. Please let me know when you are available. Thank you

### ISSUE THREAD

**Issue by Awesome194** [AdguardTeam/AdguardForiOS#1645]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by zzebrum** [comment]
@Awesome194 please, fill the form above if you have any issues with the AdGuard app.
