### ISSUE TITLE
bug? cant block url type request in dns log

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardForiOS#1646]
i dont know if this is a bug or maybe i have to block them with a specific filter syntax, but i always get these two requests that id like to block in my adguard log but cant find the right filter type to block them. maybe they cant be blocked? they are:

https://notify.bugsnag.com/
https://app-measurement.com/sdk-exp
![533070BF-DC2F-4EB2-B46D-6B859ACCBA33](https://user-images.githubusercontent.com/71462072/94067066-f256c400-fdb2-11ea-931d-59917bc9fce1.png)

**Comment by Maxim-Butov** [comment]
Try using this syntax. Works?

<img src="https://user-images.githubusercontent.com/67098694/94133090-ddd50300-fe68-11ea-86f1-bc4202503de6.jpeg" width="400" />

**Comment by jordanelliott23** [comment]
yeah i tried that. i think it is a bug. it requests it by the url instead of the domain which is maybe why its not able to be blocked?

**Comment by jordanelliott23** [comment]
@ameshkov i tried using the recommended block filter when i see the url but it still doesnt block.

**Comment by jordanelliott23** [comment]
the recommended filter was: ||https://app-measurement.com/sdk-exp^$important

which doesnt work. mind you this is a dns request im trying to block via the dns filtering part coming from an app not from the browser filtering part.

**Comment by jordanelliott23** [comment]
@ameshkov

**Comment by Maxim-Butov** [comment]
If you block all unwanted requests through the "Activity list" tab? By clicking on the request itself and tap on "Add to Blocklist"? In this case, requests will be blocked?

**Comment by ameshkov** [comment]
Wait-wait-wait, I know what's going on.

`https://app-measurement.com/sdk-exp` **is not a valid DNS query**. The problem is that some software (probably Google's library) misbehaves and causes invalid DNS queries to be sent. They are harmless, but anyway, they look strange.

If you want to have them blocked, use something like this in the blocklist:
`/app-measurement.com/`
