### ISSUE TITLE
Bug: No Update Found when opening adGuard (4.0.3)

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#1647]
No Update found when opening adGuard after 6 to 24 hours ( or more ).

Steps to reproduce:
1. Open adGuard after sometime ( e.g after a day or more )
2. Screen shows No Update found. But when you click the refresh icon, there are updates and the filter gets updated.
3. Version affected is 4.0.3

Expected:
There should not be a message saying No Update Found when opening adGuard for sometime. It should only be shown if there are really no updates.
We can have the message to NOT Show ( like previous version ) or say “New Updates Found” if there are updates or  when the app is opened after sometime.

Actual:
No Update Found but there are updates when clicking the refresh wheel.

Screenshot:

![4A303807-4D4C-45FC-8775-6E92A2A375DF](https://user-images.githubusercontent.com/27464836/94086367-0c91b000-fe4e-11ea-9c4d-63f5827ed39e.jpeg)

**Comment by Maxim-Butov** [comment]
To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Reproduce the issue (and remember the exact time when it happened).
2. Disable "DNS Privacy"
3. Open the app, tap "Send Feedback", select "Contact Support"
3. The mail app will be opened, **change the recipient to `apple@adguard.com` (!)**
4. Mention this issue number in the email text

**Comment by zznosar** [comment]
I tried sending the logs via email but it’s always failing. Not sure why. Can i just upload it here?

**Comment by Maxim-Butov** [comment]
Hmm... Then try manually export logs _(Settings -> Support -> Export Logs)_ and send it to my mail m.butov@adguard.com.

**Comment by zznosar** [comment]
@Maxim-Butov sent. I tried your email address and the apple email address above using proton mail instead of my yahoo email which seems to be having an issue sending emails.

**Comment by Maxim-Butov** [comment]
Yes, I received the logs, thanks! We will analyze it =)

**Comment by Maxim-Butov** [comment]
We looked at the logs and couldn't find anything =(.
 Please enable "debug logs" in the settings->general->advanced settings, try reproduce the error and  after that send the logs right away again to my mail.

**Comment by zznosar** [comment]
This is still not fixed in the current beta.... it’s not a show stopper though
