### ISSUE TITLE
Weird issue with Ad Guard Pro when I connect iPad to iPhone for internet I get no active internet from my hotspot at all this is only when DNS protection is enabled on iPad so far

### ISSUE THREAD

**Issue by ng4ever** [AdguardTeam/AdguardForiOS#1649]
Using the latest Ad Guard Pro on iOS. 

Please help thanks!

**Comment by ng4ever** [comment]
Fixed it had to make sure Ad Guard Pro was setup the same way on my iPhone with DNS protection enabled as well. Thanks. 

BTW is there anyway to guarantee getting rid of the video ads on CNN app please? 

Also what about the advertisement place holders in the BBC News app please ?

**Comment by zznosar** [comment]
Not all ads can be blocked in some apps. One example is youtube app. It may or may not work well with BBC and CNN.

**Comment by ng4ever** [comment]
> 
> 
> Not all ads can be blocked in some apps. One example is youtube app. It may or may not work well with BBC and CNN.

Thanks will the actual AdGuard VPN service help any with this or no ?

**Comment by Maxim-Butov** [comment]
Do you mean our new AdGuard VPN application, which is in beta?

**Comment by ng4ever** [comment]
> 
> 
> Do you mean our new AdGuard VPN application, which is in beta?

Yes

**Comment by Maxim-Butov** [comment]
Our vpn application - makes the functionality of the classic vpn. Although it uses an improved proprietary protocol and has the ability to integrate with Adgard, it has no effect on advertising.

**Comment by Maxim-Butov** [comment]
Our VPN app - makes the functionality a classic VPN. Although it uses an improved proprietary protocol and has the ability to integrate with Adgard, it does not affect ads by itself.
