### ISSUE TITLE
Family protection blocks images on www.dilbert.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#165]
Family protection enabled: Dilbert's cartoon image file is not displayed  
<details>
![file_000 1](https://cloud.githubusercontent.com/assets/15856304/19105469/bd39df62-8aea-11e6-98ce-eb1591843a9e.png)

</details>

Default protection: Dilbert's cartoon image file is displayed  
<details>
![file_000 2](https://cloud.githubusercontent.com/assets/15856304/19105488/de4f87e2-8aea-11e6-82c4-ad755c87af00.png)

</details>

**Comment by ameshkov** [comment]
@vozersky family protection false positive

**Comment by Alex-302** [comment]
Works as expected on my end.

**Comment by vozersky** [comment]
our parental control doesn't dilbert.com

**Comment by evgeniy-ADG** [comment]
I reproduced this one before posting here, I made those screenshots actually. Works fine now =\

**Comment by vozersky** [comment]
Maybe someone has already whitelisted it before i tried to :)
