### ISSUE TITLE
"Firewall friendly" profile

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#1650]
Requested by 2805671

> Could you use other ports than 53 and 5353 for the AdGuard DNS server profile in iOS 14? I was in an Enterprise Network which only allowed HTTP/HTTPS Ports and some mailserver ports - nothing else. The Ports 53 and 5353 were obviously blocked... Maybe you could generate something like a "Firewall friendly" profile?

**Comment by Maxim-Butov** [comment]
In DNS-over-HTTPS (DOH) mode, all DNS requests will go through the http port. You can use the solution from this article: https://adguard.com/en/blog/encrypted-dns-ios-14.html or select DNS-over-HTTPS server type
 <img src="https://user-images.githubusercontent.com/67098694/94421794-c199d480-018e-11eb-8b56-78231cf01319.jpeg" width="400" />

in AdGuard for iOS app. 
Did this solve your problem? Or did I misunderstand you?
