### ISSUE TITLE
AdGuard Browser Asistant not displayed in some websites (iOS 14)

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdguardForiOS#1651]
Some websites Adguard Brower Asistant not working

```
https://www.techz.vn/
https://ictnews.vietnamnet.vn/
```

### Issue Details

- **AdGuard version:**
  - Adguard Pro 4.0.3 (544)
- **Device model and storage size:**
  - iPhone 8 plus
- **Operating system and version:**
  - 14.0.1

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/10969626/94359633-be411300-00d2-11eb-8eda-baba2a0bdef1.png)

![image](https://user-images.githubusercontent.com/10969626/94359644-c9943e80-00d2-11eb-9ca6-2acd94d043a0.png)

</details>

**Comment by bigdargon** [comment]
.

**Comment by 08kovalchuk03** [comment]
@bigdargon I've checked your websites with last app version and assistant is working.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-02-20 at 13 05 05](https://user-images.githubusercontent.com/52201516/108591940-51c5f980-737c-11eb-939d-f3d81dcac0b2.png)
