### ISSUE TITLE
Tunnel gets restarted even though "Restart on network changes" is disabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1652]
### Issue Details

- **AdGuard version:**
  - AdGuard 4.0.3
- **Device model and storage size:**
  - iPhone 11
- **Operating system and version:**
  - iOS 14

### Expected Behavior

1. Go to settings -> advanced -> disable "Restart on network changes"
2. Disable (or enable) Wi-Fi, i.e. cause a network change 

When "Restart on network changes" is disabled in Advanced settings, the tunnel mustn't be restarted when network changes.

### Actual Behavior

I can see that the tunnel reconnects in Settings -> VPN & Networks, i.e. goes to "Connecting..." state and then back to "Connected"

Logs:
```
2020/09/29 11:45:58:756 [7848950(com.apple.main-thread)]  (PacketTunnelProvider) reachability Notify. Status: 2 last status: 0
2020/09/29 11:45:58:756 [7848950(com.apple.main-thread)]  (PacketTunnelProvider) update settings
2020/09/29 11:45:58:756 [7848950(com.apple.main-thread)]  (DnsProxyService) - stop
2020/09/29 11:45:58:758 [7850029(dns proxy resolve queue)]  (DnsProxyService) - stopped
2020/09/29 11:45:58:758 [7850029(dns proxy resolve queue)]  (PacketTunnelProvider) updateSettings - update tunnel settings
2020/09/29 11:46:00:136 [7848950(com.apple.main-thread)]  (PacketTunnelProvider) Start Tunnel with configuration: My AdGuard Home
2020/09/29 11:46:00:136 [7848950(com.apple.main-thread)]  (DnsProxyService) - stop
2020/09/29 11:46:00:137 [7850029(dns proxy resolve queue)]  (DnsProxyService) - stopped
2020/09/29 11:46:00:137 [7850029(dns proxy resolve queue)]  (PacketTunnelProvider) Update Tunnel Settings
2020/09/29 11:46:00:137 [7850029(dns proxy resolve queue)]  (PacketTunnelProvider) Available network interfaces:
[stripped]
[stripped]
[stripped]
2020/09/29 11:46:00:137 [7850029(dns proxy resolve queue)]  PacketTunnelProvider) Start Tunnel mode: SPLIT
2020/09/29 11:46:00:138 [7850029(dns proxy resolve queue)]  (PacketTunnelProvider) - createTunnelSettings. ipv4Available: YES  ipv6Available: YES
2020/09/29 11:46:00:138 [7850029(dns proxy resolve queue)]  (PacketTunnelProvider) Tunnel settings filled.
2020/09/29 11:46:00:266 [7850029(com.apple.NSXPCConnection.user.endpoint)]  (PacketTunnelProvider) update Tunnel Settings 
2020/09/29 11:46:00:267 [7850029(com.apple.NSXPCConnection.user.endpoint)]  (PacketTunelProvider) - startDnsProxy 
```

**Comment by ameshkov** [comment]
Huh, it appears that this is not a bug, and this is not a "restart".

When we apply new settings on network change, we set `self.reasserting = YES` in the tunnel settings, and that's why it looks like "Connecting..." in VPN settings.

**Comment by iDjay** [comment]
It's worse today, are you doing something on your end right now?

**Comment by ameshkov** [comment]
Everything works locally, we simply can't influence it from the outside.

**Comment by iDjay** [comment]
It's definitely not fixed. @ameshkov

**Comment by ameshkov** [comment]
There was nothing to fix, I explained the behavior here: https://github.com/AdguardTeam/AdguardForiOS/issues/1652#issuecomment-700571076

**Comment by iDjay** [comment]
But it is actually connecting, my apps don't load for about ~5 seconds @ameshkov

**Comment by ameshkov** [comment]
Does it happen every time the network changes?

When it reloads filter lists, it marks it "connecting" which means that no connection goes through until the process is finished.

**Comment by iDjay** [comment]
No not every time,  it sometimes a few times per hour, so items definitely not updating the filter list.

**Comment by iDjay** [comment]
Sent you a mail @ameshkov

**Comment by iDjay** [comment]
Update 2:

It seems to be a bug with AdGuard VPN. For some reason since the new beta (build 98), it tries to automatically connect. 
AdGuard: Full Tunnel
AdGuard VPN: integrated mode

After deleting the AdGuard VPN profile it seems to work fine.

**Comment by iDjay** [comment]
Sorry, but it's completely unstable.

**Comment by ameshkov** [comment]
> Sent you a mail @ameshkov

Hi, I don't see them, where have you sent it.

Are you using it alongside AdGuard VPN?
Configured full or split tunnel?

@IvanIin is it possible to shorten the time we spend on the filter lists reinit?

**Comment by iDjay** [comment]
am@adguard.com

Full Tunnel,
AdGuard VPN integrated mode, but I'm not connected with it.

**Comment by ameshkov** [comment]
> Full Tunnel,
> AdGuard VPN integrated mode, but I'm not connected with it.

Please note, that they can't work together when you're using the full tunnel.

They'll be constantly "fighting" for which one of them manages the connection.

**Comment by iDjay** [comment]
All right, it was unclear for me because the integrated mode sounds like it's working with AdGuard DNS anyway. 
I'll test it with the split tunnel now.

**Comment by iDjay** [comment]
There is definitely something messed up on my system since running AdGuard VPN Beta:

https://github.com/AdguardTeam/AdGuardVPNForiOS/issues/5

@ameshkov

**Comment by iDjay** [comment]
Still happening with split tunnel and no AG VPN profile installed :(

**Comment by ameshkov** [comment]
@iDjay next time it happens, please send the logs to us. Regular logging level would be enough, I just want to check how long does it take to initialize the DNS filter. Also, I'll need to know the exact time when it happened.

**Comment by iDjay** [comment]
@ameshkov I wasn't able to re-create it yet (it never works when you try wo force it). Only some small ~2-3 seconds of connection loss sometimes. Maybe it's indeed stable now with the following setup:
AdGuard DNS over HTTPS (Split Tunnel)
AdGuard VPN profile not installed (going to install the profile again with the next beta).

**Comment by iDjay** [comment]
Sent you a good example of the issue! @ameshkov

**Comment by ameshkov** [comment]
@iDjay hm, I haven't received anything. Could you please forward it to my personal email? `am at adguard.com`

**Comment by iDjay** [comment]
That's what I did, I sent the mail on Saturday.

**Comment by ameshkov** [comment]
Can't find it in the inbox, the last once I received from you was on two weeks ago

**Comment by iDjay** [comment]
Now?

**Comment by ameshkov** [comment]
@iDjay I received it, but there're no attachments :(

**Comment by iDjay** [comment]
@ameshkov https://we.tl/t-TCy1cvYyfa

**Comment by ameshkov** [comment]
Got it

**Comment by ameshkov** [comment]
@iDjay argh, now the file is "unsupported format"
![Uploading image.png…]()

**Comment by iDjay** [comment]
@ameshkov could it be that DNS-over-TLS is unstable at the moment? I'm experiencing more dropouts than with HTTPS.

**Comment by iDjay** [comment]
@ameshkov The number of reconnects alone makes it unusable at the moment.

**Comment by iDjay** [comment]
@ameshkov I'm doing some additional testing at the Moment. It seems like it's actually more stable when I choose the full tunnel without vpn icon mode. Could it be that it's an iOS issue? It seems like the connection loss only appears when the vpn icon disappears and reappears 🤨

**Comment by iDjay** [comment]
@ameshkov sent you some new logs! I noticed that you added AdGuard DNS to AdGuard VPN. Is it possible to send me a 7 days trial code so I can test if the issue is happening while being connected to AdGuard VPN (DNS) too?

**Comment by ameshkov** [comment]
@iDjay weird thing, I am just not receiving anything from you.

> Is it possible to send me a 7 days trial code so I can test if the issue is happening while being connected to AdGuard VPN (DNS) too?

Generated a 30-days license on your `@icloud.com` account. But note that the implementation is very different and it's not the same as in AG for iOS.

**Comment by iDjay** [comment]
@ameshkov thst's indeed weird because the mail was sent. I received your mail, thanks for the activation! 
I deleted the AdGuard DNS profile and connected my iPhone to your vpn & DNS Server in Standard Mode. Seems to be stable after one hour of testing.

Will keep you updated.

**Comment by iDjay** [comment]
I've tested AdGuard VPN with the AdGuard VPN DNS server for about three hours now:

- much more stable than the DNS Connection with the normal AdGuard App
- no dropouts so far
- the VPN Icon does not disappear and reappear in the status bar when switching between WiFi and LTE.
- ad filtering quality seems to be the same in web based apps
- some AdGuard VPN servers (f.e. Germany) Are incredible slow.

**Comment by ameshkov** [comment]
> some AdGuard VPN servers (f.e. Germany) Are incredible slow.

This is going to be much better in a few days.

**Comment by iDjay** [comment]
@ameshkov I could recreate the issue with AdGuard VPN four minutes ago. Hope the logs are working:

https://we.tl/t-OKXc2VsFjB

I honestly don't understand what causes the issue for me and why it seems like I'm the only one who's affected...

**Comment by iDjay** [comment]
@ameshkov I'm experiencing the same issue with AdGuard VPN so I guess it's an iOS issue. However with AdGuard VPN, it's able to kill the connection after a few seconds seconds without connectivity.

**Comment by iDjay** [comment]
@ameshkov Adguard DNS via VPN Runs Fine.

**Comment by iDjay** [comment]
@ameshkov I have to revise. Adguard VPN has the same problems, but they don't occur as often as with AdGuard.
