### ISSUE TITLE
Access to DNS allow list crashes AG Pro

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1655]
### Issue Details

- **AdGuard version:**
  - AG Pro Testflight 4.0.3 (544)
- **Device model and storage size:**
  - iPad Pro 11"
- **Operating system and version:**
  - iOS 14.0.1
- **Browser or App:**
  - Safari

### Expected Behavior

AG Pro works fine. However it crashes when you try to access the AllowList from:
DNS Protection -> DNS Filtering -> AllowList 

### Actual Behavior

Access to DNS Protection -> DNS Filtering -> AllowList should be allowed. 

### Additional Information

I have the exact same settings in AG Pro on my iPhone 11 Pro Max and there is not issue when I access the DNS AllowList menu.

**Comment by Maxim-Butov** [comment]
To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Reproduce the issue (and remember the exact time when it happened).
2. Disable "DNS Privacy"
3. Open the app, tap "Support", select "Repor a bug"
3. The mail app will be opened, **change the recipient to `apple@adguard.com` (!)**
4. Mention this issue number in the email text

**Comment by Quorum75** [comment]
Issue reproduced today at 4:20pm CET. 

Email with logs sent today at 4:22pm CET

**Comment by Quorum75** [comment]
FYI I faced the same issue in the past and it has been solved #1613.

**Comment by Quorum75** [comment]
@Maxim-Butov helo, did you get my logs?

**Comment by zzebrum** [comment]
@Quorum75 yep, we received your email 👍

**Comment by Quorum75** [comment]
I hope you find again a quick solution because many websites and applications break. Thanks!

**Comment by Quorum75** [comment]
Sorry guys but any ETA on the resolution? I can't use my device anymore with AG Pro.

**Comment by zzebrum** [comment]
@Quorum75 can you go to Settings app - Privacy - Analytics & Improvements - Analytics Data and export crash files?

**Comment by Quorum75** [comment]
The re-installation of the app did not help. I guess I will have to wait. 

It is strange because I already had this problem on tje past and you solved it, so I don't understand why it came back.

**Comment by Quorum75** [comment]
Case close. Thanks.
