### ISSUE TITLE
AdGuard crashes after trying to link it to AdGuard Home

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#1658]
### Reproduction

1. Install app, go to DNS Protection and try to link it to local AdGuard Home deployment
2. AdGuard will crash

### Issue Details

- **AdGuard version:**
  - 4.0.3.544
- **Device model and storage size:**
  - Unspecified iPhone
- **Operating system and version:**
  - iOS 14.0.1

### Screen Recording

[Video (1).zip](https://github.com/AdguardTeam/AdguardForiOS/files/5338054/Video.1.zip)

### Additional Information

Helpdesk ID: 1646796

**Comment by zzebrum** [comment]
1. You can not just link the AG for iOS app to AG Home
2. But AG shouldn't crash like that. We will take look at it

P.S. In AG Home there will be a special config for iOS devices soon.

**Comment by vozersky** [comment]
Fixed in v4.0.4
