### ISSUE TITLE
Feature Request: Support uBO's filter rules

### ISSUE THREAD

**Issue by gontazaka** [AdguardTeam/AdguardForiOS#1659]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

`||example.com^$3p` doesn't work.

### Proposed Solution

Support rules `$3p`, `$first-party` and `$1p`.
I can substitute it with `$third-party`, but I don't want to modify existing filter.

### Additional Information

`$3p` are the equivalent to `$third-party`.
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#3p

`$first-party` and `$1p` are the equivalent to `$~third-party`.
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#first-party
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#1p

The impact on implementation will be minimal.
https://github.com/AdguardTeam/AdguardForiOS/blob/v4.0.3/AdguardExtension/SharedComponents/Services/JSConverter.js#L2640

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/SafariConverterLib #1](https://github.com/AdguardTeam/SafariConverterLib/issues/1) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ameshkov** [comment]
> The impact on implementation will be minimal

It's not that simple, we're moving to a new Swift-converter, JS version is going to be deprecated

**Comment by gontazaka** [comment]
> It's not that simple, we're moving to a new Swift-converter, JS version is going to be deprecated

Sorry, I commented without understanding much.
