### ISSUE TITLE
vpn disconnects on latest ios beta

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardForiOS#1660]
hello. i hope someone else can reproduce this issue i am having. it has happened about four or five times now.

**Comment by jordanelliott23** [comment]
i am wondering if there has been a change in code on latest beta. hope this can be figured out

**Comment by jordanelliott23** [comment]
i am using the dns over tls option wonder if that could be the problem or just changes in latest ios beta networking code

**Comment by jordanelliott23** [comment]
i tried turning debug log on but vpn wont connect with that option enabled so i dont know how i can get this log to you guys

**Comment by zzebrum** [comment]
@jordanelliott23 what iOS version do you have?

**Comment by jordanelliott23** [comment]
so guys its looking like its the newest ios 14 public beta maybe is causing the vpn disconnect problems it happened while i was looking at my ipad and iphone at same time but my ipad didn't disconnect because its one update behind. hopefully this will be fixed in final version. i cant reproduce either

**Comment by jordanelliott23** [comment]
updated info. so it seems the issue might be dns over tls because it disconnected on my ipad which isn't on current version. i will post in a few hours with updates. i switched back to dnscrypt

**Comment by jordanelliott23** [comment]
seems to be fixed after i switched to dnscrypt. dont know if it was that or my old wifi modem but will close.
