### ISSUE TITLE
cant use internet til i turn wifi on and off sometimes 

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardForiOS#1665]
i dont know if this is a ios issue or adguard issue but sometimes i have to fully turn off wifi then back on for me to be able to use the internet even. this has happened a couple times. idk, im assuming nobody else is having this issue probably because im on a beta version of ios

**Comment by jordanelliott23** [comment]
im on ios 14.2 goldmaster for reference

**Comment by zzebrum** [comment]
@jordanelliott23 
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Reproduce the issue (and remember the exact time when it happened).
2. Disable "DNS Privacy"
3. Open the app, tap "Send Feedback", select "Contact Support"
3. The mail app will be opened, **change the recipient to `apple@adguard.com` (!)**
4. Mention this issue number and the time from step 1 when the internet is down in the email text

**Comment by jordanelliott23** [comment]
@zzebrum i couldnt find the send feedback part only found report a bug. but i can confirm this happens on official ios 14.2. i came back home and the wifi auto connected but it had no internet connection so i had to toggle wifi on and off. hopefully someone can reproduce this. id also like to mention i dont have a cellular data plan so my phone is on airplane mode always. idk if that would make a difference in finding the bug
