### ISSUE TITLE
AdGuard shows DNS requests although disabled

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1667]
I've deactivated AdGuard DNS for weeks, but I still see 90 requests (78 encrypted) every day. Is that a bug?

AdGuard 4.0.4 (566)

![image](https://user-images.githubusercontent.com/4127356/98017487-a1011200-1dff-11eb-90d7-ae1ed4581b90.png)

**Comment by iDjay** [comment]
I still have the issue with 4.1.

**Comment by zzebrum** [comment]
@iDjay that's weird, I remember I've tested it. Ok, need to recheck 👌
