### ISSUE TITLE
Test Adguard Pro in app ad blocking

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#167]
We will keep track of the Adguard Pro performance with the top iOS apps.
#### The list of apps Adguard Pro blocks ads within
- [theScore](https://itunes.apple.com/us/app/thescore-sports-scores-news/id285692706)
- [Flipboard](https://itunes.apple.com/en/app/flipboard-your-social-news/id358801284)
#### The list of apps Adguard Pro cannot block ads
- Facebook
- Twitter
- Instagram
- Youtube

**Comment by ameshkov** [comment]
@gshumihin use https://www.appannie.com/ top

**Comment by ameshkov** [comment]
@gshumihin test "theScore": https://itunes.apple.com/us/app/thescore-sports-scores-news/id285692706?mt=8

**Comment by ameshkov** [comment]
@gshumihin one more app to test: Flipboard

**Comment by jo2dan23** [comment]
Does this mean we might be able to add our own filters to block in app ads also?

**Comment by gshumihin** [comment]
Do I need to upload logs here, if there any missed ads?

**Comment by ameshkov** [comment]
@gshumihin yep, it would be great
