### ISSUE TITLE
all type65 requests blocked when using opendns

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardForiOS#1670]
idk if its an issue on opendns side or app side but every type65 request is blocked. @Alex-302 

![20B8C95D-8D5F-463B-8840-6FC9DA649367](https://user-images.githubusercontent.com/71462072/98482838-b2646880-21c9-11eb-97a4-e389c3dff632.png)

**Comment by bigdargon** [comment]
This is caused by the OpenDNS server and not by the Adguard application. Please read more here https://support.opendns.com/hc/en-us/articles/360049861971-DNS-Resolver-Selection-in-iOS-14-and-macOS-11

```
Encrypted resolvers designated by domain owners

The owner of a DNS zone will be able to designate a specific resolver to be used for resolving its zone. In iOS 14 and macOS 11, only DoH resolvers can be designated. This designation is made using a dedicated DNS record type (type 65, named “HTTPS”), and validated either by DNSSEC or well known URIs. 

As such designations would result in queries bypassing OpenDNS, the OpenDNS resolvers return a REFUSED response for queries for the HTTPS DNS record type, meaning that such designations would not be discovered.
```
