### ISSUE TITLE
Adguard Pro Safari Filters Don't Update

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1671]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AG Pro Testflight 4.0.4 (566)
- **Device model and storage size:**
  - iPad Pro 11" or iPhone 11 Pro Max
- **Operating system and version:**
  - iOS 14.2
- **Browser or App:**
  - Safari

### Expected Behavior

Manually updating the filters generates a Filter Error message. 

### Actual Behavior

Filters should update themselves. 

### Additional Information

The error message concerns only Safari Filters and not DNS Protection. ![image](https://user-images.githubusercontent.com/49731083/98824145-3bcaa380-2433-11eb-93a1-67496177cce5.png)
![image](https://user-images.githubusercontent.com/49731083/98824163-3ff6c100-2433-11eb-84cc-87771266d2ae.png)
![image](https://user-images.githubusercontent.com/49731083/98824170-42f1b180-2433-11eb-811e-7221180a5d06.png)

**Comment by zznosar** [comment]
Try removing the "Fanboy's Enhanced Tracking List", then update.

**Comment by zznosar** [comment]
Try removing or disabling all the Fanboy's List under Privacy, Those seems to be causing the issue.

**Comment by Quorum75** [comment]
Indeed, Facebook and Third-party fonts ones. Those that are identified as problematic. 

Will the problem be solved in a near future or should I get rid of these filters for once and for all?

**Comment by Quorum75** [comment]
No update? Thanks

**Comment by zzebrum** [comment]
@Quorum75 please, remind me of your ticket id from support autoreply email.  I'll try to make devs take a look into it )

**Comment by Quorum75** [comment]
@zzebrum 

I just checked my emails from Nov 7th at 6:29pm CET when I reported the issue. However thee is no ticket number mentioned in the emails. Email subject was: "Filters Update Error" message 

From where I stand the new beta v4.0.4 (585) seem to solved many issues I was facing:
- Access to AG settings is no working. 
- No error message when updating fiters including Fanboy's filters identified as problematic. 
- AG widget is also loading property. 

Nice work guys 👍🏻 and congratulations to the dev team. 👏🏻

BTW I have a question, hope you can answer because I get différents answers which I confusing. 
What is the maximum filter rules you can add in the DNS FILTERS section?
I received 2 answers 400K and 500K. 

Thanks!

**Comment by zzebrum** [comment]
@Quorum75 the truth is there is no exact number :) The limit is 15MB of RAM.

**Comment by Quorum75** [comment]
@zzebrum I am talking about number of rules not memory 😉

**Comment by zzebrum** [comment]
@Quorum75 if we are talking about Safari content blockers, then yes, there is an exact number of 50k rules per each content blocker. But with DNS rules it is different, the app stores DNS rules in RAM, so different rules can take up a different amount of RAM.

**Comment by Quorum75** [comment]
@zzebrum Maybe a picture wil be better than words 😁
![image](https://user-images.githubusercontent.com/49731083/101823263-caae0700-3b2a-11eb-8a23-55ef6c135e3b.png)

**Comment by Quorum75** [comment]
@zzebrum  any feedback? Thanks
