### ISSUE TITLE
Built-in Ad-free YouTube support

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1672]
As what you know, the latest AG for Android nightly provides ad-free YouTube via share from the official YouTube app...
Honestly, YouTube Vanced app on Android is much better.

But iOS users more need ad-free YouTube because Safari content blockers already can't perfectly block ads on YouTube.

**Comment by zzebrum** [comment]
@lancelot-moon unfortunately, there is no better way to block youtube ads on iOS.

**Comment by lancelot-moon** [comment]
@ameshkov 

I think you can give browser-based YouTube player in AG app.
Or even you push another browser-based YouTube player on app store since Safari can't support full adblock rule syntax.

**Comment by ameshkov** [comment]
I doubt a browser-based player will be allowed.

Regarding "share to view YT" -- we may try this, let's keep this feature request open.

**Comment by lancelot-moon** [comment]
> I doubt a browser-based player will be allowed.

There are many browser-based YouTube player on app store.
Evercast: Available for Taiwan, Japan and other countries, not for USA and Russian.
It's made by Japanese.
https://apps.apple.com/tw/app/evercast-%E8%A6%96%E9%A0%BB%E6%92%AD%E6%94%BE%E5%99%A8/id665446587

Tube Browser - Adblocker:
https://apps.apple.com/us/app/tube-browser-adblocker/id1447070587

Anyway, you decide how to realize.
Only an idea.

**Comment by ameshkov** [comment]
Thanks for the references!

**Comment by Quorum75** [comment]
I will suggest that you pay for the service you get. Some people are making a living from their videos. 

Who works for free?

Also, if you have some financial issues you can still subscribe to YouTube Premium through YouTube India - the cheapest subscription WW. It wil cost you a $1 per month. Who can't afford a dollar, can you?

**Comment by rtsaab** [comment]
> I doubt a browser-based player will be allowed.
> 
> Regarding "share to view YT" -- we may try this, let's keep this feature request open.

Is there a way to pin AdGuard to the top of the sharing to app feature rather than it being farther down the list in the Android version and if so would that work on iPhone as well?

**Comment by ameshkov** [comment]
> Is there a way to pin AdGuard to the top of the sharing to app feature rather than it being farther down the list in the Android version

I believe Android will put it there if you use that feature often and the same is true for iOS.
