### ISSUE TITLE
Cannot add new custom DNS server

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdguardForiOS#1673]
### Issue Details

Application crashes when pressing "Save and select"

- **AdGuard version:**
  - Adguard Pro 4.0.4 (566)
- **Device model and storage size:**
  - iPhone 8 Plus
- **Operating system and version:**
  - 14.2

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by akmLaVx** [comment]
Screen recording and logs available in support ticket 1542905.
The app crashes to desktop when attempting to add a custom DNS.

**Comment by zzebrum** [comment]
@bigdargon  can you go to Settings app - Privacy - Analytics & Improvements - Analytics Data and export crash files? (if there are any)

**Comment by bigdargon** [comment]
@zzebrum Is this file you want to find?
![592B5541-B9EE-4A42-9AF8-BFC0306358E5](https://user-images.githubusercontent.com/10969626/100359806-a3cfdb00-302a-11eb-81f5-197dc44c8c05.png)

**Comment by zzebrum** [comment]
@bigdargon yep, but there should be entries with AdGuard's name. Is there any?

**Comment by bigdargon** [comment]
@zzebrum Unfortunately there is no name "Adguard" or "ProTunnel" anymore.  Some apps crash will record diagnostics, but when Adguard crashes no diagnostics.

**Comment by zzebrum** [comment]
@bigdargon one stupid question: if you add DNS server by typing in the form the same DNS, not pasting it, what happens then?

**Comment by bigdargon** [comment]
@zzebrum I found this error when the VPN is on, if the exclusion is not affected.  I tried typing without pasting.  You can check via video (youtube has flagged the video, so you need to log in to watch).  Thank you!
New video https://youtu.be/QeUSn8vGsRk

**Comment by bigdargon** [comment]
Does not affect build 585. I will close this issue. Thank you!
