### ISSUE TITLE
The rule from Base filter in not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#1674]
- **AdGuard version:**4.0.4 547
  - 
- **Device model and storage size:**  ipad mini 2
  - 
- **Operating system and version:** 12.43.8
  - 
- **Browser or App:** Safari
  - 

### Actual Behavior

The rule, which exists in Base filter(https://filters.adtidy.org/ios/filters/2_optimized.txt) is not working
https://github.com/AdguardTeam/AdguardFilters/commit/1c2e2c65104524478ade44bc825fcbbd81bec618#diff-beb9872d5fbb0d321b23246ef65d99c4d842cd31f5654869bb0974cbd0b97dc4R501
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=keralatelecom.info`
When it is added to user rules, adblock is not detected by the site.
When enabled Base filter only, I see blocked `pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` in console.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/99961228-b0d49c00-2d96-11eb-9967-e9ac5b4be32b.png)

</details>

**Comment by Alex-302** [comment]
Another example:
`/cookieconsent.$domain=~alginor.no` from Annoyances rule exists in optimized filter version but not working
https://filters.adtidy.org/ios/filters/14_optimized.txt
https://github.com/AdguardTeam/AdguardFilters/issues/68266

**Comment by ameshkov** [comment]
I am almost sure this is due to the new compiler

**Comment by Alex-302** [comment]
Both issues are not reproduced in Safari for Mac.

**Comment by Sergey-Lyapin** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/69337
Looks like same problem here, `###privacy-consent` from Annoyances doesn't work

**Comment by AdamWr** [comment]
I think that in case of `polygon.com` it doesn't work due to exception - `polygon.com#@##privacy-consent`
As I recall, on this website is necessary to accept cookie notice, otherwise video player may not works/loads.

**Comment by Sergey-Lyapin** [comment]
> I think that in case of `polygon.com` it doesn't work due to exception - `polygon.com#@##privacy-consent`
> As I recall, on this website is necessary to accept cookie notice, otherwise video player may not works/loads.
@AdamWr
Oops, now I see, thank you
