### ISSUE TITLE
Support Setapp ios 

### ISSUE THREAD

**Issue by BobCashStory** [AdguardTeam/AdguardForiOS#1675]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Problem Description

I love you app on mac i use it within setapp, but on iphone i cannot link to my setapp account, i would like to paid with my setsapp account not paid a second time.

### Proposed Solution

Integrate the setapp sdk

**Comment by zzebrum** [comment]
@BobCashStory Setapp integration will be ready soon!
