### ISSUE TITLE
Today extension is crashing in the latest beta version (v4.0.4.584 beta)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1677]
Crash report: 
[AdGuardTodayExtension-2020-12-05-011800.ips.beta.zip](https://github.com/AdguardTeam/AdguardForiOS/files/5648721/AdGuardTodayExtension-2020-12-05-011800.ips.beta.zip)

**Comment by Quorum75** [comment]
@ameshkov 

From where I stand the new beta v4.0.4 (585) seem to solved many issues I was facing:

- AG widget is also loading property. 

Nice work guys 👍🏻 and congratulations to the dev team. 👏🏻
