### ISSUE TITLE
Today ads are no longer being filtered on safari for Youtube videos. 

### ISSUE THREAD

**Issue by Drew-source** [AdguardTeam/AdguardForiOS#1678]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Device model and storage size:**
  - 
- **Operating system and version:**
  - 
- **Browser or App:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Drew-source** [comment]
![BEST PRANKS (Season 8) - The Office US - YouTube](https://user-images.githubusercontent.com/69595794/101268205-e5663180-3760-11eb-844b-ee1043608b41.png)

**Comment by ameshkov** [comment]
1. Check the filters updates
2. Try disabling/enabling any filter list to see if it makes any difference

**Comment by Drew-source** [comment]
Already done before contacting you. Didn’t work.

**Comment by ameshkov** [comment]
Please export AG settings and logs and attach to this issue or send to `devteam@adguard.com`. Mention this issue in the email.

**Comment by Drew-source** [comment]
here they are 
[adguardforios_logs_3421220201112.zip](https://github.com/AdguardTeam/AdguardForiOS/files/5652185/adguardforios_logs_3421220201112.zip)

**Comment by zzebrum** [comment]
@Drew-source I've attached log file to our inner issue system and removed from here, thanks a lot  👌

**Comment by zzebrum** [comment]
@Drew-source in the meanwhile can you also restart the Safari, please?

**Comment by Drew-source** [comment]
I tried that. I restarted Safari & the phone.

**Comment by sgreadly** [comment]
Just wanted to mention that I too see the same issue here - ads aren’t being filtered anymore on safari for YouTube :/ I presume you have all the data you need ?

**Comment by Quorum75** [comment]
Guys, I will suggest that you pay for the service you get. Some people are making a living from their videos.

Who works for free?

Also, if you have some financial issues you can still subscribe to YouTube Premium through YouTube India - the cheapest subscription WW. It wil cost you a $1 per month. Who can't afford a dollar, can you?

**Comment by zznosar** [comment]
Can you try accessing the desktop version instead of the m.youtube.com mobile site?

**Comment by Drew-source** [comment]
It's possible for a Swiss customer to subscribe through youtube india ? Because here it's 20$ per month and I can't afford that just to block ads no.

**Comment by Drew-source** [comment]
@zznosar No on mobile it goes straight to mobile even if I enter the desktop url

**Comment by Drew-source** [comment]
@Quorum75 I tried getting the india one but it keeps railroading me on the swiss one.

**Comment by zzebrum** [comment]
@sgreadly could you please also send log files to devteam[at]adguard[dot]com? 

@Drew-source please check that content blockers are enabled in Safari settings.

**Comment by Drew-source** [comment]
@zzebrum first thing i did. I even reset them.

**Comment by sgreadly** [comment]
> @sgreadly could you please also send log files to devteam[at]adguard[dot]com? 

I will do. Unfortunately it started to work again about an hour later when I tested it. 

I've noticed this behaviour before and wonder if it's related to what we are seeing here. 

If you're on a low signal on wifi where it starts to drop or fall back to GSM, or if you're on low signal with GSM, AdGuard stops blocking ads - not just on Safari YouTube but apps in general on iOS. 

disable / enable it doesn't help, unless/until you have a stable connection again. 

I'd be happy to troubleshoot this further for you but will need some time due to work (end of year rush...), unless you're aware of the behaviour or bug?

Ta.

**Comment by Quorum75** [comment]
> It's possible for a Swiss customer to subscribe through youtube india ? Because here it's 20$ per month and I can't afford that just to block ads no. 

For anyone in fact. 
Just get a VPN, like Winscribe, which offer a free version, just to sign in with aby location in India. After words.you don't need it anymore. 
Look in Google for a real random Indian address. 
Then pay with PayPal or credit card. They don't check your billing address so no worries here.

**Comment by Drew-source** [comment]
That's a genius idea thanks mate !

Andrea D. Edelman
*F**ounder & Developer *
http://app-y.ch/
 +41 79 768 67 26

**Comment by Chinaski1** [comment]
Please reopen if it still occurs
