### ISSUE TITLE
The app is crashing when trying to open settings (v4.0.4.584 beta)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1679]
The crash report:
[Adguard-2020-12-06-001100.ips.beta.zip](https://github.com/AdguardTeam/AdguardForiOS/files/5648723/Adguard-2020-12-06-001100.ips.beta.zip)

**Comment by Quorum75** [comment]
Some thing here. iPhone and iPad.

**Comment by bigdargon** [comment]
This issue and #1677, this error is random in some devices.  My phone is the same, but when I delete the app and reinstall everything appears normal

**Comment by Quorum75** [comment]
@ameshkov 

From where I stand the new beta v4.0.4 (585) seem to solved many issues I was facing:
- Access to AG settings is no working. 
- No error message when updating fiters including Fanboy's filters identified as problematic. 
- AG widget is also loading property. 

Nice work guys 👍🏻 and congratulations to the dev team. 👏🏻
