### ISSUE TITLE
Widget doesn't load on v4.0.4.584 beta

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1680]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v4.0.4.584 beta
- **Device model and storage size:**
  -  iPhone 11 Pro Max and iPad 11 Pro
- **Operating system and version:**
  -  iOS 14.2

### Expected Behavior

 AG widget should show AG status.

### Actual Behavior

 Widget doesn't load anymore. Used to work with previous beta

### Screenshots

![image](https://user-images.githubusercontent.com/49731083/101283976-015be880-37de-11eb-8107-17084036d96e.jpeg)

**Comment by zznosar** [comment]
Weird. I don’t have this issue. Mine seems to load ok.

**Comment by bigdargon** [comment]
Dup #1677 
@zznosar This is only a bug when updating the beta, but if you remove the app and reinstall it then this error doesn't appear!
