### ISSUE TITLE
PTR requests bypass vpn and take long time to process 

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardForiOS#1681]
![E73E8395-6846-47F4-8D1E-AB60E0AA3AA3](https://user-images.githubusercontent.com/71462072/101703933-4041a680-3a49-11eb-9a97-003c7e8d660b.png)

![A18E718D-F74E-4166-A85B-C95E8144F882](https://user-images.githubusercontent.com/71462072/101704014-6ff0ae80-3a49-11eb-98b8-3613024cbd4a.png)

**Comment by zzebrum** [comment]
@jordanelliott23 rebooting the phone should help. It looks like a bug in the system, not on our side.

**Comment by jordanelliott23** [comment]
@zzebrum i thought it was a software update att did with my modem because i didnt used to see those logs. but now regular domains are bypassing the vpn. this is on beta. here i attached screenshots. 
![4DCCDCAF-E9D2-454A-97BB-90192FFC12C6](https://user-images.githubusercontent.com/71462072/101822964-bb5d9800-3aef-11eb-8d10-fe59e9ef485d.png)

th
![B047F73F-EC83-42A4-916B-9E5D0EED2924](https://user-images.githubusercontent.com/71462072/101822969-bd275b80-3aef-11eb-8169-a64918647b0a.png)

that request was supposed to go through the quic dns on the app but instead went through my system dns settings.

**Comment by jordanelliott23** [comment]
![EEA8430B-80F4-4971-953E-074B27A6F2DC](https://user-images.githubusercontent.com/71462072/101823477-6cfcc900-3af0-11eb-8702-3e54c9353072.png)
![E96E7ABE-E9C5-477B-8976-AFC4F2995BE5](https://user-images.githubusercontent.com/71462072/101823481-6ec68c80-3af0-11eb-9140-db88559b0d0c.png)
![EE3EBAA2-0ECF-47A4-842C-9C030E4E5B6F](https://user-images.githubusercontent.com/71462072/101823482-6f5f2300-3af0-11eb-9fda-01cb02e854c3.png)
![88E92BB7-EBD6-4661-B215-7ED93B5AFF29](https://user-images.githubusercontent.com/71462072/101823484-70905000-3af0-11eb-8fc5-fd8b89ea5675.png)

**Comment by jordanelliott23** [comment]
i attached two more domain requests that say processed instead of encrypted and those also bypassed the vpn instead of upstream through adguard quic dns

**Comment by jordanelliott23** [comment]
could we reopen this @zzebrum

**Comment by zzebrum** [comment]
@jordanelliott23 please, check with the latest release v4.0.4

**Comment by jordanelliott23** [comment]
looks like it is still doing it on latest official release. hopefully it can be fixed. i have it on full tunnel also it shouldn't be bypassing the quic dns. idk. 

![8851EA1F-13F6-4F4F-813D-EB942058E2C3](https://user-images.githubusercontent.com/71462072/102699574-64507500-420b-11eb-9b7f-af833dd039f0.png)
![2FED2951-7E11-43CE-8949-CEF1C8395EFB](https://user-images.githubusercontent.com/71462072/102699575-6581a200-420b-11eb-98f1-678698ab7e01.png)
![00C6FC47-59BA-45C3-8455-568C5F008C2E](https://user-images.githubusercontent.com/71462072/102699577-674b6580-420b-11eb-8aed-6f495aa4b9e1.png)


@zzebrum

**Comment by jordanelliott23** [comment]
wondering why it says processed not encrypted and the upstream shows my system dns instead of quic dns. is it a ui glitch or something with a bug.
