### ISSUE TITLE
Can‘t add AdGuard to my Home Screen

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1684]
I can't add AdGuard from my App Library to my iOS 14 homescreen after removing it from my homescreen.
AdGuard:
![image](https://user-images.githubusercontent.com/4127356/102210519-917ee980-3ed2-11eb-9d63-0a50b76b2274.png)
AdGuard VPN (as reference)
![image](https://user-images.githubusercontent.com/4127356/102210553-9ba0e800-3ed2-11eb-9f1e-55c4f72168c0.png)
I'm not sure if this is your issue or some weird iOS 14 glitch.

**Comment by Aydinv13** [comment]
Hello! Try to hold the app and pull it out from Library to Home screen. As another option you may just update iOS

**Comment by iDjay** [comment]
Adding it manually once fixed the issue.
