### ISSUE TITLE
Adding networks to exceptions using external keyboard issue

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#1685]
I wanted to report a minor bug in the iOS app: under DNS Protection → Network Settings → Wi-Fi Exceptions, hitting the Return/Enter key on an external keyboard adds a carriage return to the excluded SSID. It should instead Add the SSID to the list of exceptions. I experienced this issue on an iPad Pro connected to an Apple Magic Keyboard via Smart Connector. However, I imagine it would occur with a Bluetooth-connected keyboard as well.

Reported by: 1446221

**Comment by Fraktan** [comment]
Thx for information



Gesendet von myMail für iOS


Donnerstag, 18. Februar 2021, 12:16 +0100 von ***@***.***  ***@***.***>:
