### ISSUE TITLE
Enable dns filter for specific apps

### ISSUE THREAD

**Issue by domoritz** [AdguardTeam/AdguardForiOS#1688]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I would like to filter ads in specific apps so it would be great if I could enable dns filtering per app. 

### Proposed Solution

Enable the vpn when a specific app opens and disable it when it closes. 

### Alternatives Considered

This solution would help with issues where someone wants to use two vpns, which is currently not supported.

**Comment by rtsaab** [comment]
This feature would be great!

**Comment by Aydinv13** [comment]
It would be a great feature but in order to filter per app we need to have access for specific app which is impossible due to Apple restrictions. Thanks for your question!
