### ISSUE TITLE
Sharing menu does not disappear after clicking "Report an issue on this page"

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForiOS#1689]
### Issue Details
- **AdGuard version:**
  - AdGuard for iOS v. 4.0.4 
- **Device model and storage size:**
  - iPhone XR 64 GB 
- **Operating system and version:**
  - iOS 14.3 
- **Browser or App:**
  - Safari 14.0 

### Expected Behavior
Sharing menu will disappear after clicking "Report an issue on this page".

### Actual Behavior
Sharing menu does not disappear after clicking "Report an issue on this page".

### Screenshots
<details><summary>Screen recording:</summary>

[RPReplay_Final1608415508.zip](https://github.com/AdguardTeam/AdguardForiOS/files/5720212/RPReplay_Final1608415508.zip)

</details>

### Additional Information
I could be wrong, but there was no such problem in version 3.x.

**Comment by Aydinv13** [comment]
Yeah that's a bug and it's supposed to be fixed soon.

**Comment by Rakleed** [comment]
А почему закрыли issue, если как минимум в стабильной версии это еще не исправлено?

**Comment by zzebrum** [comment]
@Rakleed v4.0.4?

**Comment by Rakleed** [comment]
Yes.
