### ISSUE TITLE
http://www.ran.de/ - incorrect blocking by DNS filtering

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#169]
http://www.ran.de/tennis/live/wta-turnier-in-peking-im-kostenlosen-livestream

Before: <details>
![1](https://cloud.githubusercontent.com/assets/15856304/19142909/7325203e-8ba9-11e6-9eae-ed87b2af90b5.png)

</details>

After: <details>
![2](https://cloud.githubusercontent.com/assets/15856304/19142916/7667712a-8ba9-11e6-960a-e20176d220e9.png)

</details>

**_1424706**_

**Comment by Alex-302** [comment]
@evgeniy-ADG Are you sure that is blocked by DNS, and is not hidden by rules from user filter?

**Comment by ameshkov** [comment]
@Alex-302 how's it going with the content blocker?

**Comment by Alex-302** [comment]
@ameshkov that block is hidden by user filter
<details>
![image](http://imagizer.imageshack.com/img923/1993/jbCbpY.png)
</details>

**Comment by ameshkov** [comment]
ah, ok then

**Comment by Alex-302** [comment]
@evgeniy-ADG read this https://github.com/AdguardTeam/AdguardForiOS/issues/169#issuecomment-252193046
