### ISSUE TITLE
Hide the VPN icon when enabling "Full-Tunnel without VPN icon"

### ISSUE THREAD

**Issue by Marco224** [AdguardTeam/AdguardForiOS#1691]
### Issue Details

At the moment when you select the option "Full-Tunnel without VPN icon" as default tunnel mode, the VPN icon is hidden only when the device is connected to a Wi-Fi network, as soon as you switch to a cellular connection it shows up again.

- **AdGuard version:**
4.0.4(588)
- **Device model and storage size:**
iPhone XS 
- **Operating system and version:**
  iOS 14.3

### Expected Behavior

When using cellular data the VPN icon does not show up.

### Actual Behavior

VPN icon is present while using cellular connection even though "Full-Tunnel without VPN icon" option is selected.

**Comment by zzebrum** [comment]
@Marco224 "Full-Tunnel without VPN icon" is an unstable mode and I doubt we can change this behavior.
