### ISSUE TITLE
DNS query leaks on a network change

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1692]
### Issue Details

- **AdGuard version:**
  - 4.0.4
- **Operating system and version:**
  - iOS 14

### Steps to reproduce

In order to test this, you'll need a Wi-Fi network with a DNS server which logs you can access (and verify that there're leaked DNS queries from your device there). Contact me to get access to our office network DNS logs -- you'll need access to http://adguard.home/

1. Configure AdGuard to use any DNS server.
2. Block `ocsp.apple.com` in AG (iOS contacts it every time a network changes so it's a good indicator).
3. Switch Wi-Fi off and on again
4. Check the DNS logs

### Expected Behavior

No `ocsp.apple.com` queries

### Actual Behavior

These queries show up there (sometimes)

**Comment by ameshkov** [comment]
Relevant video: https://t.me/adguard/104211

**Comment by privacy-advo** [comment]
Could this be an issue of on-demand VPN?

@ProtonVPN claims they have a solution:
https://protonvpn.com/support/always-on-vpn/
https://protonvpn.com/blog/apple-ios-vulnerability-disclosure/

Apple's doc:
This:
https://developer.apple.com/documentation/networkextension
Leads us to: [iOS Deployment Reference](https://support.apple.com/guide/deployment-reference-ios/always-on-vpn-iore8b083096/1/web/1) 
"Always On VPN activation requires device supervision." 

Further, when creating a VPN profile for a managed device with Apple Configurator 2 Always-on is only available when choosing IKEv2.

**Comment by ameshkov** [comment]
@privacy-advo I don't think it is an Apple issue, more likely the bug is in AdGuard and the way we reload DNS configuration on network changes.

**Comment by privacy-advo** [comment]
IMHO: I would guess that this is a intenional behaviour. Most users would be confused when they can't connect with e.g. WIFI hotspots (hotels, bar etc.) due to failed captive checks. The "real" enforced always-on VPN is reserved for managed devices in certain enviroments handled by admins. Would not be the first time Apple restricts access to features/configs which could potentially break things for inexperienced users.

**Comment by ameshkov** [comment]
Well, the thing is that there was no bug in v4.0.3 (at least it hasn't been reported to us) so there's a chance that this one is on us.

**Comment by privacy-advo** [comment]
Thanks. Looking forward to a successful patch.

**Comment by 08kovalchuk03** [comment]
We've made a research and it is impossible to avoid query leaks due to the restrictions that OS imposes on us. When network changes system DNS ip addresses can change and we need to know them. To reveal new ip addresses we need to resolve them, so we set empty tunnel settings. It takes about 1-1.5 seconds to reveal addresses and set new system addresses. While tunnel settings are empty DNS queries can leak, and we were not able to find a different way to get system DNS addresses. But we've made everything to minimise time empty tunnel time, and now it is rather hard for DNS queries to be leaked.

**Comment by privacy-advo** [comment]
Thank you @08kovalchuk03 for commenting the issue.
Which frameworks is Adguard for iOS using? As Adguard is advancing in new markets (VPN), are there difference in the realisation of the VPN/on system tunneling?

**Comment by 08kovalchuk03** [comment]
AdGuard uses our own framework, we do not use third party frameworks when it comes to privacy and user data. Speaking about AdGuard VPN, It doesn't need to read system DNS, so we don't use such workarounds there. Only location or DNS server change will cause tunnel restart.

**Comment by 08kovalchuk03** [comment]
We are thinking about adding one more tunnel mode where we won't read system DNS, but in that case a user will have to set bootstraps and fallbacks manually.

**Comment by privacy-advo** [comment]
Probably my question was poorly stated: I wanted to ask about the iOS frameworks used.

**Comment by 08kovalchuk03** [comment]
When dealing with tunnel we use only NetworkExtension.

**Comment by privacy-advo** [comment]
> 
> 
> We are thinking about adding one more tunnel mode where we won't read system DNS, but in that case a user will have to set bootstraps and fallbacks manually.

I guess many would welcome such an approach. I was observing a lot of leaked queries by the well known _friends_ e.g. braze.com, adjust, app-measurement etc. Some of these already offer a asynchronous functionality which allows to upload the already obtained data once there is connectivity. [adjust: offline-mode]

**Comment by ameshkov** [comment]
@08kovalchuk03 in theory, we don't need to do this tunnel restart if the user explicitly specified bootstrap DNS servers.

Can we at least do this logic change?

**Comment by 08kovalchuk03** [comment]
@ameshkov Yes, I've thought about it. We can, but only when both bootstraps and fallbacks are specified in low level settings.

**Comment by 08kovalchuk03** [comment]
In the end we've decided to completely remove reasserting as it does nothing. When we've removed reasserting the tunnel behaviour hasn't changed at all. To **completely avoid DNS query leaks** you need to:

1. Turn off `restart protection when network changes` option
2. Turn on full tunnel mode in low level settings
3. Set custom fallbacks and bootstraps servers
4. Do not use system default DNS server

**Comment by privacy-advo** [comment]
Sad news.
How to customize fallbacks and bootstraps servers?
As far as I understand you can only set a single custom server.

Thanks ahead.

Another one:
Is there a way to import DNS rules in AdGuard iOS?

**Comment by 08kovalchuk03** [comment]
@privacy-advo If you are a beta tester you can go to **General** -> **Advanced settings** -> **Low-level settings** and customize servers. This feature will be available in 4.1 version.

**Comment by ameshkov** [comment]
> Is there a way to import DNS rules in AdGuard iOS?

The easiest way would be to add them as a separate DNS filter.

**Comment by privacy-advo** [comment]
hi @08kovalchuk03 
Did you retest the behaviour with AdGuard Pro for iOS **and** the DoQ server?
With short testing, I can't discover the leakage anymore with DoQ.

a) What is your opinion?
b) How did you solve this issue for AdGuard VPN?
