### ISSUE TITLE
There is no icon on the top of the Activity tab

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForiOS#1694]
### Issue Details
- **AdGuard version:**
  - AdGuard for iOS v. 4.0.4
- **Device model and storage size:**
  - iPhone XR 64 GB
- **Operating system and version:**
  - iOS 14.3

### Expected Behavior
On the Activity tab, the icon is displayed at the top.

### Actual Behavior
On the Activity tab, the icon is not displayed at the top.

### Screenshots
<details><summary>Screenshot:</summary>
Activity tab:

![IMG_0326](https://user-images.githubusercontent.com/19418601/103170296-5aa2bf00-4854-11eb-95ba-cc134e6230b7.jpeg)
Setting tab:

![IMG_0328](https://user-images.githubusercontent.com/19418601/103170298-5c6c8280-4854-11eb-981d-8faa5306907a.PNG)

</details>

### Additional Information
This icon is displayed on two adjacent tabs - Protection and Settings.

**Comment by ameshkov** [comment]
Assigned to v4.1
