### ISSUE TITLE
Back gesture doesn't work well

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForiOS#1695]
### Issue Details
- **AdGuard version:**
  - AdGuard for iOS v. 4.0.4
- **Device model and storage size:**
  - iPhone XR 64 GB
- **Operating system and version:**
  - iOS 14.3

### Expected Behavior
If I start sliding my finger not from the very edge of the screen and release it after sliding it down less than half the width of the screen, or if I slide my finger from the very edge and release it before the middle of the screen, the Back gesture will work.

### Actual Behavior
If I start sliding my finger not from the very edge of the screen and release it after sliding it down less than half the width of the screen, or if I slide my finger from the very edge and release it before the middle of the screen, the Back gesture doesn't work.

### Additional Information
The difference can be felt in comparison with system and other apps (Telegram, VK, Bear and others).

**Comment by Aydinv13** [comment]
Hello there! It's working as it's supposed to do because we set 30% (not half of the screen)

**Comment by Rakleed** [comment]
@Aydinv13 so why did you do it differently from all other applications? This greatly degrades the user experience.

**Comment by Aydinv13** [comment]
@Rakleed We found it more comfortable for people to slide a bit to get back. If you want to slide you do it on purpose)

**Comment by Rakleed** [comment]
@Aydinv13 It seems to me that we do not understand each other. I sent a bug report stating that you need to swipe 50% of the screen to activate the Back gesture, although in other applications it is 20–35%. At the same time, you tell me that the opposite is true. Why, if in practice it works as I describe?

**Comment by Aydinv13** [comment]
@Rakleed Can you provide the video of what you are concerned? I think I explained all that you wanted to know

**Comment by zzebrum** [comment]
@Rakleed well, I agree that telegram is more sensitive, but overall I would not say that gestures at AG app are working bad at the moment.

**Comment by Rakleed** [comment]
@zebrum the problem is that in the vast majority of applications the sensitivity of the Back gesture is the same as in Telegram. And in AdGuard, the Back gesture is less sensitive, and it is very frustrating.

**Comment by Rakleed** [comment]
@zzebrum @Aydinv13 so can you make a normal sensitivity like all other applications?
