### ISSUE TITLE
On the About screen, you can login/logout of your account

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForiOS#1696]
### Issue Details
- **AdGuard version:**
  - AdGuard for iOS v. 4.0.4
- **Device model and storage size:**
  - iPhone XR 64 GB
- **Operating system and version:**
  - iOS 14.3

### Expected Behavior
You can login/logout to your account on the License screen.

### Actual Behavior
You can login/logout to your account on the License and About screens.

### Screenshots
<details><summary>Screenshot:</summary>

License screen:
![IMG_0332](https://user-images.githubusercontent.com/19418601/103181062-d715bc00-48ad-11eb-80c7-4b429919fb82.PNG)

About screen:
![IMG_0333](https://user-images.githubusercontent.com/19418601/103181063-d8df7f80-48ad-11eb-9d09-0220392e3ab2.PNG)

</details>

### Additional Information
The same feature is duplicated in two different places in the application.

**Comment by Chinaski1** [comment]
Hello there!

Actually, this is done for the convenience of users and is not a mistake.

**Comment by Rakleed** [comment]
@Chinaski1 This is just misleading. When I went to the About screen, I simply could not understand what the Logout button is for. Is it logging out of the app or account? Therefore, it seems reasonable to me to leave the option to log in / out of the account only on the License screen.

**Comment by Rakleed** [comment]
@Chinaski1 so what do you think?
