### ISSUE TITLE
Only DNScrypt allows internet access

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1699]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

I am confused about something. 

I am using AG Pro in parallel with Windscribe Pro. 

If AG Pro DNS set up is not DNScrypt I have not internet. Then, it excludes the use of DoQ, Doh...

However if I use DNScloak and AG DoH server I have to issue at all. 

So why I can't get internet with AG Pro with Doh but I can with DNScrypt AG DoH?

- **AdGuard version:**
  - AG Pro 4.0.4 (588) Beta-->
- **Device model and storage size:**
  - iPhone 11 Pro Max -->
- **Operating system and version:**
  - iOS 14.3
- **Browser or App:**
  - Safari and Winscribe Pro

### Expected Behavior

Getting internet connection whatever the choice of DNS protocol.

### Actual Behavior

Only DNSCRYPT protocol allows be to get I nternet. 

### Screenshots

N/A

</details>

**Comment by zzebrum** [comment]
@Quorum75 it seems that Windscribe uses some DNS with private IP which we can't access. Most probably it would work with AdGuard v4.1 when the bootstrap DNS option will be released.
