### ISSUE TITLE
DNS filtering issue

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdguardForiOS#1703]
With rule `||tinder.app.link^` in Blocklist direct following to the link tinder.app.link is being blocked, but when I go to  https://go.tinder.com/web-ios-download it redirects to tinder.app.link and onwards to the app store - no blocking occurs.
WIth AG Home blocking occcurs in both cases. (same on Android)

Related issue: https://github.com/AdguardTeam/AdguardFilters/issues/71709

**Comment by jordanelliott23** [comment]
Try using $important after the ^

**Comment by Sergey-Lyapin** [comment]
same with `$important`

**Comment by vozersky** [comment]
can't reproduce (v4.1 beta)

**Comment by Sergey-Lyapin** [comment]
@vozersky ok, but FYI how it looks on 4.0:
https://user-images.githubusercontent.com/18536328/106465774-7d577180-64ab-11eb-964f-ef421df9b0ff.mp4

**Comment by Alex-302** [comment]
@vozersky

**Comment by Sergey-Lyapin** [comment]
The problem is no longer reproduced in 4.2.0.
