### ISSUE TITLE
BETA : Native DNS over TLS is not working in adGuard 4.1.0 and Pro 4.1.0 for AdGuard DNS

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#1704]
Using native DOT in iOS 14 for adGuard DNS is not working. Safari goes to infinite loading.

Steps to recreate:

1. Open adGuard 4.1.0 beta ( applicable to Pro as well)
2. Select Native in DNS Implementation under DNS protection
3. Select AdGuard DNS and protocol is DNS over TLS.
4. Select adGuard App in iOS - Settings - General - VPN and Network - DNS.
5. Open Safari and check if you can browse or go to AdGuard Test site.

Expectation: site should load.
Actual: No site is loading.

**Comment by zznosar** [comment]
Native DOT is still buggy. It’s frustratingly slow. Sometimes the page load sloowwly, sometimes it will just not load at all.. Native DOH is fine.. I think the DOT DNS it self has an issue?

**Comment by zzebrum** [comment]
@zznosar there were problems on the server-side, it should be ok now.

**Comment by zznosar** [comment]
All good! Works great now!
