### ISSUE TITLE
BETA : White SPACE Cosmetic Issue in DNS Protection module in 4.1.0 beta

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#1705]
There is a white space cosmetic issue in the current beta of adguard 4.1.0. Tested using iPhone 7. Please see attached photos

<img width="375" alt="PNG image 3" src="https://user-images.githubusercontent.com/27464836/105797907-10446780-5fe5-11eb-985e-2dc57b08a49b.png">

click Switch Mode.

notice a white space on top of the page.

<img width="375" alt="PNG image 4" src="https://user-images.githubusercontent.com/27464836/105797921-16d2df00-5fe5-11eb-9c9c-55abc5846eb1.png">

**Comment by 08kovalchuk03** [comment]
@zznosar thank you for this UI bug. It is already fixed, the fixed version will be available in next beta :)

**Comment by zznosar** [comment]
This seems fix in the current beta.thank you.

tested in iphone 7.
