### ISSUE TITLE
DNS Rule Search Crashes AG

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1706]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AG iOS 4.0.1 (621)
- **Device model and storage size:**
  -  iPhone 11 Pro Max. 
- **Operating system and version:**
  -  iOS 14.3
- **Browser or App:**
  -  AG Pro Beta

### Expected Behavior

 When searching for a specific rule within "DNS Protection / DNS Filtering / Allowlist" should return a result 

### Actual Behavior

 But AG simply cashes when typing for the search. 

### Video

<details><summary>Video: link valid for 30 days: https://www.swisstransfer.com/d/08715f31-4464-4cc1-93d0-35727f03ea9b

</details>

### Additional Information

 Strangely it does not happen on my iphon 11 Pro Max with the exact same configuration.

**Comment by Quorum75** [comment]
Still crashing with version Bêta 4.0.1 (628)

**Comment by SergeyBerdov** [comment]
@Quorum75 
Can you please export your allowlist file? You can do it in DNS Protection -> DNS Filtering -> Allowlist -> Export button

**Comment by Quorum75** [comment]
> @Quorum75 
> 
> Can you please export your allowlist file? You can do it in DNS Protection -> DNS Filtering -> Allowlist -> Export button

@SergeyBerdov 
It is already exported as a back and to sync between my devices. 

Do you need it?

**Comment by SergeyBerdov** [comment]
@Quorum75
Yes, it might be helpful.

**Comment by Quorum75** [comment]
Where do you want me to send it? AG support email?

**Comment by SergeyBerdov** [comment]
Make export allowlist file from  DNS Protection -> DNS Filtering -> Allowlist screen and send it to apple@adguard.com

**Comment by Quorum75** [comment]
Email sent to your attention

**Comment by Quorum75** [comment]
Working now with Beta 4.1.0 (637). Thanks.
