### ISSUE TITLE
DNS Protocols won't work with VPN

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1707]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AG iOS 4.1.0 (621)
- **Device model and storage size:**
  -  iPhone 11 Pro Max or iPad 11 Pro. 
- **Operating system and version:**
  -  iOS 14.3
- **Browser or App:**
  -  AG Pro Beta

### Expected Behavior

 Whatever DNS protocols you choose you should be able to access the internet without any interruption. 

### Actual Behavior

 All DNS Protocols except DNScrypt, block the internet access with third part VPN like Proton or Windscribe even with split tunnel mode activated. However it happens mostly when the devices go to sleep, but also sometimes while simply surfing the web. 

### Screenshot 

<details><summary> N/A

</details>

### Additional Information

 Putting the device in Plane Mode and re-activating the wifi and cellular networks sometimes helps to regain the internet. Otherwise a restart of the devices is mandatory. 
The only solution as today seems to keep only DNScrypt activated.

**Comment by ivan-ilin** [comment]
Windscribe VPN sets the local IP address as the DNS server (10.255.255.2). We are trying to use it as bootstrap DNS for doh, dot, quic protocols. But this address is not available to us from the tunnel. To solve this problem, you can set a custom bootstrap DNS(for example 1.1.1.1). This setting will be available in Adguard  v4.1.0(now in beta)

**Comment by Quorum75** [comment]
> Windscribe VPN sets the local IP address as the DNS server (10.255.255.2). We are trying to use it as bootstrap DNS for doh, dot, quic protocols. But this address is not available to us from the tunnel. To solve this problem, you can set a custom bootstrap DNS(for example 1.1.1.1). This setting will be available in Adguard  v4.1.0(now in beta)

Thanks for the reply. 

As mentioned above I am using the latest beta. However what you are suggesting does not ring a bell for me. 
Can't you give me some guidance about how setting a bootstrap to try your recommendation please?

Thanks.

**Comment by zzebrum** [comment]
@Quorum75 run AdGuard app and go to Settings - General - turn on Advanced mode -Advanced settings - Low-level settings - Bootstraps. There you need to set a bootstrap DNS server and save it.

**Comment by Quorum75** [comment]
@zzebrum  thanks for your response. 

I finally setup the **Bootstrap** to _9.9.9.11_ and the **Fallbacks** to _https://dns11.quad9.net/dns-query_

Will keep you posted if there is any issue.

**Comment by Quorum75** [comment]
@sfionov Hello. Question, should I add a fallback address? Like Cloudfare? Is it really necessary? Thanks for your response.

**Comment by 08kovalchuk03** [comment]
@Quorum75 
1. If you leave "Fallback servers" empty, we will use system DNS servers.
2. If you fill "Fallback servers" with your addresses, we will use your addresses.
3. If you fill "Fallback servers" with 'none' word, we will set empty list of fallbacks.

**Comment by sfionov** [comment]
Fixed, will be included in Adguard for iOS 4.2
