### ISSUE TITLE
Debug Logs breaks,network connection

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1708]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AG iOS 4.0.1 (621)
- **Device model and storage size:**
  -  iPhone 11 Pro Max and iPad 11 Pro. 
- **Operating system and version:**
  -  iOS 14.3
- **Browser or App:**
  -  AG Pro Beta

### Expected Behavior

 Activating Genaral / Advanced Settings / Debug Logs shouldn't break the network connection.  

### Actual Behavior

 When you activate the Debug Logs option, AG breaks the Wi-Fi connection and cannot reconnect.   

### Video

<details><summary>Video: link valid for 30 days: https://www.swisstransfer.com/d/be1775e8-4c42-4dc4-9c66-d9b086fec71d

</details>

### Additional Information

 The only solution is to manually disconnect AG and re-launch the connection.

**Comment by 08kovalchuk03** [comment]
@Quorum75 it's absolutely normal. If you wait a little bit (about 15-30 seconds) the tunnel will start. When debug logs are on we log more information, every message log takes some time to be executed. What is more, when the tunnel is started with debug logs on, you can experience long page loading. Debug logs are made to catch a bug, it is not a feature to use on regular basis.
