### ISSUE TITLE
VPN restarts when entering the app

### ISSUE THREAD

**Issue by kwasi101** [AdguardTeam/AdguardForiOS#1709]
The vpn restarts when entering app. Am on version 4.1.0(621) iPhone 8. Attached is a link to video preview

[](https://share.icloud.com/photos/0o64rbfW6v7QAVUsBf-BFpwgA)

**Comment by jordanelliott23** [comment]
same thing happens to me

**Comment by Aydinv13** [comment]
@jordanelliott23 @kwasi101 please check if the issue persists on the latest version

**Comment by kwasi101** [comment]
It still persist on wifi...

**Comment by Aydinv13** [comment]
Could you please send logs to us? Reproduce the issue (and remember the exact time when it happened);
apple@adguard.com ;
Mention this issue number in the email text.

**Comment by jordanelliott23** [comment]
> Could you please send logs to us? Reproduce the issue (and remember the exact time when it happened);
> [apple@adguard.com](mailto:apple@adguard.com) ;
> Mention this issue number in the email text.



> @jordanelliott23 @kwasi101 please check if the issue persists on the latest version

yes it does i posted logs on my issue number

**Comment by kwasi101** [comment]
I emailed the logs around 2:14 GMT this morning.
