### ISSUE TITLE
Block Twitch App ads

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1710]
Hey, is it possible to block the pre-roll ads in the current twitch app? I never experienced them before on iOS so I‘m not sure if they were introduced recently or if AdGuard DNS blocked them until today and now it doesn‘t work anymore.

AdGuard Pro 4.0.4
Twitch 10.0
iOS 14.4

**Comment by iDjay** [comment]
Update: no ads today, I‘ll come back if it changes.

**Comment by Aydinv13** [comment]
Hello,
this issue has been closed. If the problem persists please let us know and open it again

**Comment by bingoxo** [comment]
> Hello, this issue has been closed. If the problem persists please let us know and open it again

please open it again
