### ISSUE TITLE
VPN restarts on latest beta on multiple apps

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardForiOS#1711]
hello. i just updated to the latest beta and i went into the facebook app and it restarted the vpn. is there a way i can grab a log.

**Comment by jordanelliott23** [comment]
sadly i couldn't get a log in time but this happens randomly sometimes where i open a app and it restarts vpn. like if i go to type in safari bar. but i cant ever get a log. maybe im the only one with the vpn restarting problem

**Comment by Aydinv13** [comment]
Hello!
Please, write steps to reproduce for us to try it our side. When it happens again go to Setting- Support- Export logs. In addition, specify your operating system

**Comment by jordanelliott23** [comment]
hello. here is one log. i just opened the adguard app and the vpn restarted. i know it usually does that when u check for updates but i didnt check for updates so hopefully this helps fix the crash for other apps https://ufile.io/silgt2yk

**Comment by jordanelliott23** [comment]
also im on ios 14.4

**Comment by jordanelliott23** [comment]
i got it to crash in the facebook app. check for vpn restart in log at timestamp 15:16-15:20 in between those four minutes something triggered the vpn to restart while in facebook app. 

https://ufile.io/40pxxlx4

**Comment by jordanelliott23** [comment]
both these log files should help fix vpn restarts in both facebook and adguard app i hope

**Comment by jordanelliott23** [comment]
i got another vpn restart when entering safari. check timestamps between 19:48-19:51 https://ufile.io/svlp65w6

**Comment by jordanelliott23** [comment]
@08kovalchuk03 did these logs help? i got another restart this morning when using discord app but i didnt catch the timestamp as i was barely awake. hopefully these logs help these restarts be fixed

**Comment by 08kovalchuk03** [comment]
@jordanelliott23 we’ve found a bug that can cause this behavior. The fix will be available in the next beta version.

**Comment by jordanelliott23** [comment]
> @jordanelliott23 we’ve found a bug that can cause this behavior. The fix will be available in the next beta version.

awesome! will beta be pushed to testflight today?

**Comment by 08kovalchuk03** [comment]
@jordanelliott23 Not today :) it will be published before the weekend. We are still in the process of fixing other bugs.

**Comment by jordanelliott23** [comment]
> @jordanelliott23 Not today :) it will be published before the weekend. We are still in the process of fixing other bugs.

awesome, thankyou!

**Comment by 08kovalchuk03** [comment]
You’re welcome

**Comment by jordanelliott23** [comment]
@08kovalchuk03 

i am on todays beta. and got a restart of vpn after i left an app. the timestamp of the restart is between 16:31-16:35 https://ufile.io/7749rmgs

hopefully it will show why it happened

**Comment by jordanelliott23** [comment]
i got another restart between 2am and 330 am approximately last night because i woke up this morning and the time the vpn said it was running was less then when i shut the screen off and fell asleep. idk if it will still show in the logs since im grabbing them so late. i will try again tonight and see if it happens. but here: https://ufile.io/zkpzg4se

**Comment by jordanelliott23** [comment]
@SergeyBerdov could u look at the two logs above and see if theres anything useful to fix the restarts. i saw ur the one who fixed it in the commit so i thought id tag u.

**Comment by jordanelliott23** [comment]
heres last log ill post til next version. restart between timestamp 23:54 and 23:58 https://ufile.io/vt9p0483

**Comment by zznosar** [comment]
I can’t reproduce this. As far as i can see, even the current stable version 4.0 and the previous versions, do this. The fake VPN restarts after very long data exchange or if its connected for too long.

It also disconnects when the device falls to sleep and will reconnect when there is connection process (this is to save battery) this is how ios works.

It happens to other proper regular to VPN app too.
 
I don’t think this will do an Always On VPN connection. Always On is for Supervised Deviced.

this is using Connect On Demand. So it will do disconnection every now and then.

If you are waking your device from sleep, you might see vpn reconnetion...

my current test devices are :
iphone 7 and ipad pro 11: both have beta 4.1.0
Iphone 11 pro: current stable 4.0
Iphone 6 plus: old version 2.0 pro

**Comment by jordanelliott23** [comment]
> I can’t reproduce this. As far as i can see, even the current stable version 4.0 and the previous versions, do this. The fake VPN restarts after very long data exchange or if its connected for too long.
> 
> It also disconnects when the device falls to sleep and will reconnect when there is connection process (this is to save battery) this is how ios works.
> 
> It happens to other proper regular to VPN app too.
> 
> I don’t think this will do an Always On VPN connection. Always On is for Supervised Deviced.
> 
> this is using Connect On Demand. So it will do disconnection every now and then.
> 
> If you are waking your device from sleep, you might see vpn reconnetion...
> 
> my current test devices are :
> iphone 7 : beta 4.1.0
> Ipad pro 11: beta 4.1.0 and stable 4.0 Pro.
> Iphone 11 pro: current stable 4.0
> Iphone 6 plus: old version 2.0 pro

ok. i didn't know about the sleep part. but my other two longs it wasnt a big data transfer and it wasn't even connected for that long when i got two of the three restarts.

**Comment by ameshkov** [comment]
@08kovalchuk03 let's make reassertion behavior configurable.

Add a new low-level setting:
* `Reassert on network change`
* `Don't accept connections when network change is in progress to avoid query leakage`

Keep it disabled by default since it's clearly rather annoying and the risk of query leakage is low anyway.

For those who want to completely avoid query leakage, you'll need to:
1. Enable "reassertion"
2. Enter Bootstrap DNS and Fallback DNS servers
