### ISSUE TITLE
No message while choosing native DNS. (v4.1.0.628)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1712]
1. I don't see the message while choosing native DNS. (v4.1.0.628)
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/U95IggJ.png)
</details><br/>

2. Also, general users don't know how to use it.
I see the photo above.
To enable native DNS, you need to open <b>System settings</b>, go to <b>General > VPN & Network > DNS</b> and select <b>%@</b> there.

%@ = AdGuard Pro

By the url: https://adguard.com/en/blog/encrypted-dns-ios-14.html
I don't see AdGuard Pro after installing https://cdn.adguard.com/public/Dns/adguard-dns.mobileconfig
I only see AdGuard DNS in DNS setting.
<details><summary>Screenshot:</summary>

![image](https://cdn.adguard.com/public/Adguard/Blog/encrypted-dns/instruction-3.png)
</details><br/>

You should clearly explain how to use native DNS on iOS 14.
To enable native DNS, you need to open System settings, which is wrong.
To enable native DNS, you need to install profile first.
Without the installation of DNS profile, users even can't see VPN & Network in iOS setting. (only VPN in iOS setting)
Do you understand that users are confused?
**Please rewrite the description.**

**Comment by 08kovalchuk03** [comment]
@lancelot-moon the article you've attached is not related with "native DNS" feature. The config is not created when the app is installed. When you switch to native DNS implementation in AdGuard Pro settings the config should be created and it is located exactly where the dialog says. If it is not so, please send logs to verify the problem.

**Comment by lancelot-moon** [comment]
No, the config isn't created on iPadOS 14.
After 1st running native DNS implementation in AdGuard Pro settings, it still only shows "VPN" in iOS setting, not "VPN & Network".

**Comment by 08kovalchuk03** [comment]
Did you select native implementation?

**Comment by zzebrum** [comment]
@lancelot-moon also, you need to enable DNS protection to be able to see this message.

**Comment by lancelot-moon** [comment]
Thanks, solved.
