### ISSUE TITLE
Weak connection function on AG VPN for iOS

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/AdguardForiOS#1714]
### Issue Details

- **Device model and storage size:**
 IPhone X
  - 
- **Operating system and version:**
14.3
  - 
- **Browser or App:**
 AdGuard VPN
  - 

### Expected Behavior
When we click on connect VPN is activated without any problems

### Actual Behavior
There are a lot of reconnections and failures while connecting

### Screenshots

<details><summary>Screenshot:</summary>
https://uploads.adguard.com/Image_from_iOS.MP4

</details>

**Comment by rtsaab** [comment]
You may have more luck or focused help if you move the issue to the official
[AdGuardVPNForiOS](https://github.com/AdguardTeam/AdGuardVPNForiOS) repository.

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/AdGuardVPNForiOS #53](https://github.com/AdguardTeam/AdGuardVPNForiOS/issues/53) via [**ZenHub**](https://www.zenhub.com/)
