### ISSUE TITLE
Ads not getting blocked and home page stats are not updating

### ISSUE THREAD

**Issue by mmurali88** [AdguardTeam/AdguardForiOS#1715]
### Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v4.0.4(588)
- **Device model and storage size:**
  - iPhone 11 128gb
- **Operating system and version:**
  - 14.3
- **Browser or App:**
  -  APP

### Expected Behavior

1. Enable all the filters on the iOS app
2. Ads are blocked
2. Blocked stats are updated on the ios app home screen.

### Actual Behavior

1. Enable all the filters on the iOS app
2. Ads are not blocked
2. Blocked stats are not getting updated on the ios app home screen.

### Screenshots

<details><summary>Screenshot:</summary>

![IMG_4365](https://user-images.githubusercontent.com/4982265/106709580-9ba39700-65a9-11eb-8242-66dcd31a30a2.PNG)
![IMG_4364](https://user-images.githubusercontent.com/4982265/106709585-9d6d5a80-65a9-11eb-8b33-19a1cbf5ddf9.PNG)
![IMG_4363](https://user-images.githubusercontent.com/4982265/106709588-9e9e8780-65a9-11eb-9f56-f64b55f06ac3.PNG)
![IMG_4362](https://user-images.githubusercontent.com/4982265/106709590-9f371e00-65a9-11eb-943a-9d683bd90aa6.PNG)

</details>

### Additional Information

The issue happens on the iPad app too

**Comment by zzebrum** [comment]
@mmurali88 you need to enable DNS protection. Go to settings tab - DNS protection: https://uploads.adguard.com/up03ub5cu.png

Also, you may need to add a DNS filter for better blocking quality, here is the instruction: https://kb.adguard.com/en/ios/solving-problems/how-to-add-your-own-filter
