### ISSUE TITLE
Discord broken on IOS VPN

### ISSUE THREAD

**Issue by kenjiwing** [AdguardTeam/AdguardForiOS#1718]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
Adguard for IOS v 4.0.4 (588)
- **Device model and storage size:**
  Iphone 11 Pro 14.5 beta (also broke with 14.4)
- **Browser or App:**
Discord

### Actual Behavior

When you open discord it should work. Instead it hangs at connecting. If you disable adguard it works just fine.

### Screenshots

Not needed it simply goes to connecting with discord open.

### Additional Information

As soon as you disable the adguard vpn/protection discord works fine. I dont see any blocks in the DNS list.

**Comment by kenjiwing** [comment]
This broke around January im wondering if its related to DNS over Quic. Also see thread 

https://forum.adguard.com/index.php?threads/adguard-dns-blocks-discord.41689/

**Comment by SergeyBerdov** [comment]
@kenjiwing 
Could you please send logs ?

**Comment by jordanelliott23** [comment]
Mine does same thing. But it works sometimes. But I get the connecting hang thing sometimes also. Would a regular log help find the problem or is it need debug log

**Comment by SergeyBerdov** [comment]
@jordanelliott23
Regular log

**Comment by jordanelliott23** [comment]
For me it takes awhile when it shows connecting then it eventually connects. But here is a log idk if it will show anything to help. But here https://ufile.io/arxv7x93

**Comment by nileplumb** [comment]
was trying to report via the submission form but it wouldn't let me click next after selecting dns filter.

I too having lots of issues trying to connect to Discord with the vpn enabled

**Comment by SethuSenthil** [comment]
I'm having this issue too even when just using the DNS profile, hope they fix this soon! Also, it only seems to happen on iOS.

**Comment by calebmorse** [comment]
I have this issue as well. I can try and gather any logs that may help resolve the issue as well. I've found that sometimes clearing the app to restart it fixes the issue but not always.

**Comment by SethuSenthil** [comment]
The "best" and easiest workaround I found was to simply disable the DNS profile in iOS settings (Settings > VPN & Network > DNS) which would allow the messages to load. This is obviously not ideal

**Comment by calebmorse** [comment]
> The "best" and easiest workaround I found was to simply disable the DNS profile in iOS settings (Settings > VPN & Network > DNS) which would allow the messages to load. This is obviously not ideal

Requiring users to enable and disable the DNS filtering feature would be a poor fix. Ideally they update the app or DNS filters to work correctly.

**Comment by ameshkov** [comment]
Quick question - does it depend on which DNS server you choose or is it happening with any DNS server?

**Comment by calebmorse** [comment]
> Quick question - does it depend on which DNS server you choose or is it happening with any DNS server (even with the System one)?

It's hard to tell because swapping DNS choices in the app refreshes the network connection and causes Discord to reload. I've done a bit of back and forth switching with some of the larger chat groups that would require loading and it does seem that while connected to the adguard DNS servers it doesn't load but switching to system DNS it will them load. To be clear my method of testing is the following:

1. While connected to adguard VPN with adguard DNS go to discord
2. Messages won't load.
3. Go back to adguard and change DNS to system DNS.
4. Return to discord and messages will load.

It's seems like there is some sort of throttling or request timeout happening while connected to the adguard DNS servers. 

As stated before, while staying connected to the adguard DNS servers sometimes I can clear Discord from recent applications and open it again and messages will load again. That is hit or miss though as sometimes it will just show "connecting" or not load messages.

**Comment by ameshkov** [comment]
What if you choose a different server, not just AG DNS (try Cloudflare or Google for instance)?

**Comment by calebmorse** [comment]
> What if you choose a different server, not just AG DNS (try Cloudflare or Google for instance)?

I tried that a few times and the same result as before. Messages begin to load one switching off the AdGuard DNS to any of the alternatives.

**Comment by SethuSenthil** [comment]
> What if you choose a different server, not just AG DNS (try Cloudflare or Google for instance)?

Yeah, switching makes the messages load. Specially cloud-flare in my case

**Comment by ameshkov** [comment]
And hopefully the last question - does it make a difference if you choose "AdGuard DNS Non-Filtering" configuration? The one that doesn't block anything.

Sorry for that many questions, we just cannot reproduce it on our side.

**Comment by nileplumb** [comment]
I'll switch mine over now and let you know if it hiccups at some time today (using app based dns vpn)

**Comment by nileplumb** [comment]
it hasn't locked up on me all day on the no filtering adguard server, will try tommorrow too

**Comment by nileplumb** [comment]
I had 1 lock up today however it also lined up with me leaving wifi and switching to 4G which was prone to bugger discord up for a bit anyway.

Possibly safe to assume the issue is with the filtering versions in some way

**Comment by ameshkov** [comment]
Next time this happens, could you please export AG logs and send the archive to `devteam@adguard.com`? 

Please mention the following in the email:

1. Link to this issue
2. Exact time when it happened

**Comment by nileplumb** [comment]
I've sent at least 3 exports now hope it helps

**Comment by nileplumb** [comment]
I've sent at least 3 exports now hope it helps

**Comment by ameshkov** [comment]
@nileplumb I've got the logs, thank you!

What's strange is that there's nothing blocked at the time when the problem occurs for you.

Could you please do one more thing for us? Let's use local DNS filtering (i.e. tracking requests will be blocked locally right on your device) but a different DNS resolver.

Here's how to do that:
1. Enable "Advanced mode" in AdGuard settings
2. Go to DNS protection -> DNS filters
3. Add "AdGuard DNS filter", here's the link to it: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt (you'll need to enter it there)
4. Switch to a different DNS that was not causing any issues (Cloudflare, Google, AdGuard DNS Non-Filtering)

If the issue is reproduced again, please send us the logs one more time.

**Comment by nileplumb** [comment]
> If the issue is reproduced again, please send us the logs one more time.

I've only had 1 instance of discord having connection issues since changing but a simple restart of the discord app fixed that, it seems more stable either way

**Comment by nileplumb** [comment]
just reporting still much more stable using the filters file + no filter dns

**Comment by ILikePlayingGames** [comment]
I'm having this issue a lot on AdGuard DNS over QUIC via VPN. Here are my discord debug logs for reference. The requests seem to be timing out after 2 seconds. Like others have mentioned, no DNS requests appeared to be blocked for me either.

![image](https://user-images.githubusercontent.com/22475143/113524027-e7f35f00-9579-11eb-80d9-47249d573a2c.jpeg)

![image](https://user-images.githubusercontent.com/22475143/113524029-eb86e600-9579-11eb-97cf-a04fb495d147.jpeg)

![image](https://user-images.githubusercontent.com/22475143/113524030-ee81d680-9579-11eb-8124-3799c75427ae.png)

**Comment by dhklein** [comment]
> Here's how to do that:
> 
> 1. Enable "Advanced mode" in AdGuard settings
> 
> 2. Go to DNS protection -> DNS filters
> 
> 3. Add "AdGuard DNS filter", here's the link to it: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt (you'll need to enter it there)
> 
> 4. Switch to a different DNS that was not causing any issues (Cloudflare, Google, AdGuard DNS Non-Filtering)

This _immediately_ fixed my issue. I restarted my device after changing the settings for good measure. I've been using Discord all morning without any problems after months of constant trouble. I'm using Cloudflare Secure DNS now. Thanks for the suggestion.

**Comment by nileplumb** [comment]
Yeah definitely acceptable connection times still using file filter instead of basic dns.

**Comment by ameshkov** [comment]
We've made some changes to AdGuard DNS recently (we had a problem with Google serving us Chinese IPs). I wonder could it be that Discord was affected by the same issue?

Could you please try AG DNS again just to check if the issue is still there?

**Comment by nileplumb** [comment]
has there been an app update or just cycle the settings in current one?

**Comment by ameshkov** [comment]
> has there been an app update or just cycle the settings in current one?

This seems to be an AdGuard DNS issue so no update is required.

**Comment by nileplumb** [comment]
nope issue returned

**Comment by dhklein** [comment]
I also had the issue return.

**Comment by ameshkov** [comment]
So let me please summarize:

1. First, there's no issue when you're using AdGuard DNS Non-Filtering configuration (i.e. no blocking on the server-side).
2. The issue is there with any other AdGuard DNS configuration (Default or Family), but it does not appear right away, it takes some time to re-appear.
3. The issue goes away if you use AdGuard DNS filter locally and use your ISP of CloudFlare DNS.

Am I right?

**Comment by nileplumb** [comment]
seems so, though I've not tested adguard family mode dns.
I had no issues on
Dns implementation: Adguard local
dns server: Adguard non filtering or cloud flare secure
dns filtering: Adguard dns filter file (previously linked)

**Comment by nileplumb** [comment]
the issue more often presents itself when reopening/switching back to the app eg after a notification you might tap that to return to the chat you were in and then the content will rarely/never load, even after quitting discord and reloading

**Comment by ameshkov** [comment]
@nileplumb could you please email me at `am@adguard.com`?

If you don't mind, I could share a test DNS endpoint with pretty much the same configuration as the normal AdGuard DNS. This way I could see what requests are made and what happens to them.

**Comment by nileplumb** [comment]
of course

**Comment by nileplumb** [comment]
so far so good on the test endpoint you senf me (unfortunately for debugging???)

**Comment by ameshkov** [comment]
Yeah, this is indeed unfortunate. Tbh, I am out of ideas for now, that server had pretty much the same configuration as the public one..

**Comment by nileplumb** [comment]
I believe discord has some sort of IP protection, I know webhook IFTTT recipes will fail for no reason other than lots of other users badly configured triggers going off causing some sort of block. Perhaps reach out to the discord devs to see what's possibly going on (they don't have ads so probably wouldn't be offended you asking), mind you I guess it wouldn't explain why it's only bring reported from ios?

**Comment by nileplumb** [comment]
Just had a lot of connection issues perhaps related? Do you need my logs or can you grab?

19th April 08:58-09:02 UTC+1

**Comment by nileplumb** [comment]
Just had a lot of connection issues perhaps related? Do you need my logs or can you grab?

19th April 08:58-09:02 UTC+1

**Comment by ameshkov** [comment]
@nileplumb probably just a glitch, I see nothing special in the logs. Note that this is a test endpoint, it sometimes gets restarted/updated randomly.

**Comment by nileplumb** [comment]
happened again  approximately 12:07 onwards still can't connect now

**Comment by ameshkov** [comment]
@nileplumb 12:07 what time zone?

In fact, I see one strange thing in the DNS log, it returns a suspicious HTTPS record for `discord.com`:
```
discord.com. 67 IN HTTPS 1 . alpn="h3-29,h3-28,h3-27,h2" ipv4hint="0.0.0.59,0.46.3.110,115.49.192.55,10.104.111.115,116.109.97.115"
```

`ipv4hint` contains invalid IP addresses. I'll check what could it be.

**Comment by nileplumb** [comment]
Cool good to switch back to iOS QUIC app based dns without filter files now?

**Comment by ameshkov** [comment]
@nileplumb yep, it should work just okay
