### ISSUE TITLE
BETA : BUG : Disabling DNS filters breaks the internet connection in 4.1.0

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#1719]
Disabling some DNS filters added by user breaks the internet and the local fake vpn is stuck in connecting.

steps to recrete:
1. Open AdGuard Beta 4.1.0
2. Under DNS protection, disable one or two DNS filters.

<img width="375" alt="PNG image 4" src="https://user-images.githubusercontent.com/27464836/107435484-50c4e900-6b80-11eb-89e1-b92bc3ff1e27.png">

3. notice that the local vpn icon is gone.

<img width="375" alt="PNG image 5" src="https://user-images.githubusercontent.com/27464836/107435533-6508e600-6b80-11eb-92e7-5291af0efe35.png">

4. check settings and the VPN is stuck in Connecting.

<img width="375" alt="PNG image 6" src="https://user-images.githubusercontent.com/27464836/107435594-77831f80-6b80-11eb-9af4-148cb28ca4e7.png">

5. check internet in safari.

<img width="375" alt="PNG image 7" src="https://user-images.githubusercontent.com/27464836/107435682-9bdefc00-6b80-11eb-8c09-4cc533ccf8aa.png">

Expected: disabling some of the filters should not break the internet connection and the local vpn should reconnect.

actual: no internet connection and local vpn is stuck in connecting.

test device: iphone 7 and ipad pro 11. Screenshots from iphone 7.

additional info. I recreated it mutiples and also waited for the local VPN to reconnect. I assumed, probably the reconnection is just slow, but it did not reconnect after 10 mins.

**Comment by vozersky** [comment]
@zznosar hi! could you please try the new 4.1.0 (644) build?

**Comment by zznosar** [comment]
Thank you. This seems to be fixed. Tried the above steps and there the vpn is not stuck in reconnecting anymore.
