### ISSUE TITLE
filter update stock in update loop

### ISSUE THREAD

**Issue by xxcriticxx** [AdguardTeam/AdguardForiOS#172]
My adguard pro ver 1.1.0 on ios 9.3.5 stock on Check Filter Updates in loop for less 3 hr. i already try reboot the phone few times, kill the app, turn on/off wifi nothing works do you guys have any other suggestions?

**Comment by ameshkov** [comment]
@Stillness-2 what do you think?

**Comment by Stillness-2** [comment]
It possible if backened service is not available. But why this happens... We need logs.

**Comment by Stillness-2** [comment]
@xxcriticxx If you disable Adguard DNS, then update goes normal?

**Comment by xxcriticxx** [comment]
i dont use adguard dns. it updated today at 6:45 am so it took about 22h to update. now i can pull updates with no problem. i will keep eye on this for next few days.

**Comment by jo2dan23** [comment]
My just started doing this also

**Comment by jo2dan23** [comment]
is there a way to disable auto update because mine keeps getting stuck in a update loop and i don't know whats causing it.

**Comment by vozersky** [comment]
@jo2dan23 sorry for not coming back to you, please let me know if you still experience any issues with update
