### ISSUE TITLE
Wrongly show English in 2 places.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1720]
It doesn't correctly show translations in Chinese Traditional interface.

1. English "default" in blocking mode of low-level setting.
It should show the translation of default.

2. All descriptions of default DNS servers are English.
It should show the translations.

Change the language of AG to Chinese Traditional in iOS setting.
You'll observe this.

**Comment by 08kovalchuk03** [comment]
@lancelot-moon 
1. Default word won't be localized
2. DNS servers are localized now. The fix be available in the next beta version

**Comment by lancelot-moon** [comment]
@08kovalchuk03 
Default word is localized in the screen after entering blocking mode selection.
It's better to also localize it in the screen of low-level setting.

**Comment by lancelot-moon** [comment]
About "default", it may be a bug.
It is already localized in the screen after entering blocking mode selection.
But it shows English in the screen of low-level setting.
You can see you uploaded the word on Crowdin.
https://crowdin.com/translate/adguard-applications/17548/en-zhtw#3935498
