### ISSUE TITLE
Не удалось завершить операцию. AdGuard_Pro.Complex-ProtectionError, ошибка 0

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdguardForiOS#1723]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v4.1.0
- **Device model and storage size:**
  - iPhone XR
- **Operating system and version:**
  - 14.4

### Behavior

Error after resetting settings. To reproduce it, reset the settings and click on the green icon of the shield, but cancel the request.

### Screenshots

<details><summary>Screenshot:</summary>

![AdGuard](https://user-images.githubusercontent.com/45385632/108390251-87a29b00-7221-11eb-8ef7-f4121d1b0cfa.PNG)

</details>

### Additional Information

The [verbose logs](https://github.com/AdguardTeam/AdguardForiOS/files/6004444/AdGuard_logs.zip) is attached.

**Comment by 08kovalchuk03** [comment]
@ammnt This is normal behaviour ant isn't related to settings reset. This error is shown by the OS and we can't handle it.
