### ISSUE TITLE
Mark those settings that won't work in Native Implementation

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardForiOS#1726]
as far as I know, low-level settings can not be applied if Native DNS mode is enabled

so it would be better to make `Low-level settings` in Advanced settings inactive. and if users are trying to choose those, the app should recommend them to switch to AdGuard implementation

**Comment by ameshkov** [comment]
I'd prefer not to hide it completely, but to mark those settings that cannot be properly applied.
