### ISSUE TITLE
Multiple vpn restarts on 4.1.0 (651)

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardForiOS#1727]
restart between 12:29-12:32

https://ufile.io/2y5khsel

**Comment by jordanelliott23** [comment]
another one between 21:50-21:53

https://ufile.io/p5e66sln

**Comment by jordanelliott23** [comment]
restart between 15:59-16:02
https://ufile.io/b7586247

**Comment by jordanelliott23** [comment]
@SergeyBerdov can u see if these logs help find reason for restart

**Comment by jordanelliott23** [comment]
last log for now cuz im sure the others show the same but if not just in case:

restart between 18:01-18:04

https://ufile.io/dhxidqkw

**Comment by ameshkov** [comment]
@08kovalchuk03 please check the logs
