### ISSUE TITLE
Filters update status switches from "not found" to "N filters updated"

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardForiOS#1729]
Использую последнюю версию приложения для iOS (4.1.0(651)) на последней версии iOS (14.4). На главном экране странно отображается статус обновления фильтров после ручной проверки. Сначала появляется надпись "обновление...", потом "обновления не найдены", но после этого высвечивается "обновлено X фильтров". Если обновления для фильтров есть и они загружаются, то почему перед этим Adguard пишет что их нет? Может стоит исправить?

**Comment by ameshkov** [comment]
Посмотрим, похоже на баг, но нам бы не помешали логи приложения.

В следующий раз когда это произойдет - можете пожалуйста экспортировать лог и прицепить к задаче?

**Comment by Vitalik93** [comment]
> 
> 
> Посмотрим, похоже на баг, но нам бы не помешали логи приложения.
> 
> В следующий раз когда это произойдет - можете пожалуйста экспортировать лог и прицепить к задаче?

У меня это каждый раз происходит, когда есть обновления.

**Comment by ameshkov** [comment]
Ну тем проще получить лог

**Comment by Vitalik93** [comment]
Прикрепил логи.
[AdGuard_logs.zip](https://github.com/AdguardTeam/AdguardForiOS/files/6037810/AdGuard_logs.zip)

**Comment by zznosar** [comment]
This has been an issue since 4.0. I even raised it and they said they fixed it.

https://github.com/AdguardTeam/AdguardForiOS/issues/1647

They close the ticket but i did mentioned that it was not fixed.

**Comment by ameshkov** [comment]
Yeah, it's a rather weird race condition issue, we thought it's fixed but apparently it's not:(
I hope we'll fully fix it in v4.2.

**Comment by Laicure** [comment]
I would love to see app logs (not the debug logs), at least on a read-only text box, instead of a one-liner status label.

**Comment by ammnt** [comment]
Yeah, it's really annoying😤

**Comment by ammnt** [comment]
The detailed and regular logs is attached - please, take a look:

[regular_AdGuard_logs.zip](https://github.com/AdguardTeam/AdguardForiOS/files/6352887/regular_AdGuard_logs.zip)
[detailed_AdGuard_logs.zip](https://github.com/AdguardTeam/AdguardForiOS/files/6352888/detailed_AdGuard_logs.zip)

https://user-images.githubusercontent.com/45385632/115596832-38d8b680-a2e1-11eb-8e71-bcd9e9ec6d55.mov

**Comment by artemiv4nov** [comment]
Fixed in the 4.3 version
