### ISSUE TITLE
enable/disable button

### ISSUE THREAD

**Issue by xxcriticxx** [AdguardTeam/AdguardForiOS#173]
can you guys please add enable/disable button?

**Comment by ameshkov** [comment]
For what exactly?

**Comment by xxcriticxx** [comment]
if website dont work you can turn off adblocker and turn on or maybe pause button be better idea

**Comment by ameshkov** [comment]
It is already possible to do it in Safari (tap share button and find Adguard action there)

**Comment by xxcriticxx** [comment]
@ameshkov i switched phones my testflight app is asking for new invitation code can you get aegis to send me one

**Comment by ameshkov** [comment]
Summoning @vozersky here

**Comment by vozersky** [comment]
@xxcriticxx 
You are already a registered tester. Just log in with your apple id.
If testflight keeps asking for code, use the same one you've received with the first notification letter.

**Comment by xxcriticxx** [comment]
i dont have my old phone any more. i am logged in with my apple id but testflight tells me adguard pro is unavailable to enter your testflight invitation code. i also click on my apple id and remove my old phone because i had 2 devices there. i make some pictures shortly

**Comment by xxcriticxx** [comment]
![img_3438](https://cloud.githubusercontent.com/assets/15007183/19280055/16b93a9e-8fb2-11e6-882e-609bca21962b.PNG)
![img_3439](https://cloud.githubusercontent.com/assets/15007183/19280059/19e3ec14-8fb2-11e6-9b8d-e846fe9ecc13.PNG)
![img_3440](https://cloud.githubusercontent.com/assets/15007183/19280065/1cbb9216-8fb2-11e6-95f2-435cc3b96df3.PNG)
![img_3441](https://cloud.githubusercontent.com/assets/15007183/19280068/1f4a8906-8fb2-11e6-8de0-eedbdbd5afd7.PNG)

**Comment by vozersky** [comment]
check your email, i've deleted your tester's id and re-invited you, let's see if it works

**Comment by xxcriticxx** [comment]
ok i have open and waiting for it

**Comment by xxcriticxx** [comment]
still nothing

**Comment by xxcriticxx** [comment]
@vozersky i never received that email from you can you please resend

**Comment by vozersky** [comment]
@xxcriticxx  it's not from me, it should be from @email.apple.com, please check again, I've recreated your tester's account one more time. Also, let's communicate through forum PM please, since this conversation is not really related to the current issue.

**Comment by vozersky** [comment]
resolved
