### ISSUE TITLE
DNS filterlists are updated on the disk without reloading DNS filtering which causes random filtering issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1732]
Here's the problem:

1. DNSProxy indexes DNS filterlists files and loads full rule texts in a lazy manner
2. When you update the DNS filterlist file AND do not reload DNS filtering, it uses the old index to access the NEW file. This causes random issues - for instance, it will read just a part of the rule `com^` instead of `||example.com^`. 

Probably, this is done during background fetch.

This is rather easy to reproduce:
1. Subscribe to a custom blocklist with the only rule:
    ```
    ! this is comment
    ||example.com^
    ```
2. Change that blocklist to:
    ```
    ! this
    ||example.com^
    ```
3. Wait for the background fetch to happen, the filterlist will be updated on the disk
4. It will start blocking all `.com` domains because the old index points to `.com^`

**Comment by sfionov** [comment]
From support chat:
![image](https://user-images.githubusercontent.com/47204/127155189-485ae722-0ae1-4a0f-8eb8-065d10010b12.png)

**Comment by planet0** [comment]
I'm experiencing this issue!

Was noticing random things being blocked in local filtering and wasn't understanding why.

Anything I can do in the meantime?

![image](https://user-images.githubusercontent.com/65204836/135739554-1fb8d1c3-fc2b-44f5-b2be-ca688bf4f148.png)

**Comment by ameshkov** [comment]
@planet0 next update should resolve it for good.

**Comment by planet0** [comment]
@ameshkov Would turning off background app refresh for AdGuard help with this issue in the meantime?

**Comment by ameshkov** [comment]
@planet0 yep, it will help
