### ISSUE TITLE
Add iCloud backup/export configuration option to Adguard

### ISSUE THREAD

**Issue by rodaimi** [AdguardTeam/AdguardForiOS#1733]
### Problem Description

Right now,if there's an issue with the Adguard app, I have to go to each black/whitelist, manually export the lists, and record all of my settings before deleting and reinstalling the app.

### Proposed Solution

The solution I'm proposing is an optional toggle switch to automatically backup all blocklists and settings to iCloud as well as an option to export everything to a local folder.

Additionally, an import settings option would make restoring an Adguard configuration simple

**Comment by zzebrum** [comment]
dup #479
