### ISSUE TITLE
adguard vpn restarts everytime app is opened on fresh start and when switched back to in app drawer 4.1.1 (660)

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardForiOS#1734]
reproduce: fully close app from task tray, then reopen and you will get a restart in icon bar.

reproduce 2: leave app open (dont fully close just switch to a different app, then switch back to adguard and vpn will restart in icon bar)

**Comment by zznosar** [comment]
Weird. I don’t have this issue. The fake VPN icon of adGuard is not restarting. Even the main adGuard VPN +AdGuard Blocker (fake vpn combo) works without any restart.

I have three devices which i used for the current beta.

just a question though, do you have blocklist enabled, if yes, how many and which blocklist? Too large blocklist will cause the fake vpn to crash.

also, have you tried:
Reinstalling the fake VPN.
Reinstalling the app.

**Comment by zzebrum** [comment]
@jordanelliott23 please, reproduce the problem and send logs to apple[at]adguard[dot]com

**Comment by kwasi101** [comment]
It can be reproduced in the latest beta. I just enter the app and it restarts. I have sent some logs.

**Comment by jordanelliott23** [comment]
https://ufile.io/oizg1672

restart between timestamp 12:02-12:05

**Comment by jordanelliott23** [comment]
https://ufile.io/zfv9uc1h

restart between 12:05-12:07

**Comment by jordanelliott23** [comment]
still happened today on latest beta.

first: between 13:22-25 https://ufile.io/ngoxvv94

second 13:25-13:27

https://ufile.io/ux32rmto 

@SergeyBerdov @08kovalchuk03

**Comment by jordanelliott23** [comment]
another  between 13:30-32

https://ufile.io/g9x2m8o4 @IvanIin
