### ISSUE TITLE
"No updates found" showed even if there are any filter updates

### ISSUE THREAD

**Issue by amadejpapez** [AdguardTeam/AdguardForiOS#1735]
### Issue Details

- **AdGuard version:**
  AdGuard for iOS v4.1.0(651)
- **Device model and storage size:**
  iPhone 8 Plus 64GB
- **Operating system and version:**
  iOS 14.5 (18E5164h)

### Expected Behavior

"Filters updated: *" is shown if filters were updated without showing "No updates found".

### Actual Behavior

When updating, "No updates found" is first shown after the update, if there were any updates found or not. If there were any updates found text would change to "Filters updated: *" after a few seconds.

### Screenshots

Screen recording:
[https://streamable.com/lwi9wu](https://streamable.com/lwi9wu)

**Comment by 08kovalchuk03** [comment]
duplicates https://github.com/AdguardTeam/AdguardForiOS/issues/1729
