### ISSUE TITLE
VPN restart on latest beta 4.1.1 (668) when closed app and reopen

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardForiOS#1736]
https://ufile.io/wy5fjn1w

vpn restart between 19:40-19:43

**Comment by zznosar** [comment]
Yep. I recreated this too, but I don’t think it’s a show stopper - an issue.

this seems to be a change in design. The team can confirm though.

the current beta, for me, is stable enough.

This is what i notice, based on the logs, everytime you open the app, it performs an update to the DNS filter list that you added. So it will always have the latest version when you open the app. Everytime that the DNS filters are updated, the VPN needs to be restarted for it to take effect. I’m actually ok with this approach.

The current stable version doesn’t do auto DNS filter update when opened. You need to click the refresh button to update the filters then the VPN will restart or wait for the “expiration” for it to auto update when the background refresh is enabled.

in the normal world, I don’t think people will close, open, close , open the app.

**Comment by zzebrum** [comment]
yep, when you start the app now, it checks for filters update and restarts the VPN if needed.
@zznosar the log files are outdated, its from 651 build

**Comment by jordanelliott23** [comment]
ok  noted

**Comment by jordanelliott23** [comment]
i got a restart while i was browsing in safari. the timestamp was 18:33-18:36 https://ufile.io/i13qbnoo
