### ISSUE TITLE
Do WiFi exceptions for the DNS protection in native mode still work?

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardForiOS#1737]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard 4.1.1(668 beta
- **Device model and storage size:**
  - iPhone 12 Pro Max and iPad Pro 11-inch (2nd generation)
- **Operating system and version:**
  - iOS and iPadOS 14.4.1
- **Browser or App:**
  - Safari

### Expected Behavior

When the DNS protection is set to native mode I still see the network settings where I can add WiFi exceptions. I don't think these settings are taken into account, when In native mode. If so, this setting should not be accessible in native mode.

### Actual Behavior

WiFi exceptions can be made in native mode.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by 08kovalchuk03** [comment]
@sergerosenthaler It's okay. This feature is able to work alongside native implementation. If it is not so, please describe a bug found :)

**Comment by sergerosenthaler** [comment]
@08kovalchuk03 If the WiFi exceptions in native mode still work, then all is fine. As you know in native mode there is no VPN sign which in AdGuard mode disappears when accessing a WiFi which is on the exception list. I fully trust you that in native mode, it works too:-) In this case this issue can be closed.

**Comment by 08kovalchuk03** [comment]
@sergerosenthaler The Apple API for VPN configuration and DNS configuration are very similar, so we are able to provide this feature in native mode too.
