### ISSUE TITLE
AdGuard and AdGuard Pro still distributed unter Performix, time to transfer

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardForiOS#1738]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

AdGuard and AdGuard Pro are still distributed via the Performix account in the AppStore. As you have created a new account called Adguard Software Limited it's now time to transfer AdGuard and AdGuard Pro to this account.

### Proposed Solution

https://support.appmachine.com/hc/en-us/articles/360000012284-Transfer-your-app-to-another-iOS-Developer-Account
https://developer.apple.com/support/app-store-connect/

**Comment by zzebrum** [comment]
@sergerosenthaler unfortunately for us, we are stuck with Performix until Apple come up with the solution or change the rules :(
Apple's guidelines have a constrain for transferring the app to another dev account:
- `No version of the app can use an iCloud entitlement.`

**Comment by ameshkov** [comment]
Yup, the only option is to re-upload the app. But this way we won't be able to transfer in-app purchases :(
