### ISSUE TITLE
Please Report to Apple: Fake AdGuard App in iOS

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#1739]
Hi Team, someone is pirating your App in App Store with same name as AdGuard. Please report to Apple. 

https://apps.apple.com/au/app/adguard-adblocker-for-safari/id1558269198

![798C1F18-97F1-4D0E-BCCD-E99D9B2DF049](https://user-images.githubusercontent.com/27464836/111756322-2e945880-88ee-11eb-8167-eb50909bbd13.png)

**Comment by zzebrum** [comment]
@zznosar got it, thanks!

**Comment by Dariamag** [comment]
reported!
