### ISSUE TITLE
Consider implementing a simple Firewall feature

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#174]
I suppose we can do it using the appRules:
https://developer.apple.com/reference/networkextension/netunnelprovider/1406531-apprules

**Comment by jo2dan23** [comment]
Would this mean we can block system apps from using data and wifi?

**Comment by ameshkov** [comment]
> Would this mean we can block system apps

Can't say until we test it.

**Comment by ameshkov** [comment]
Unfortunately, it seems impossible to detect installed apps and to detect what app the traffic belongs to.
