### ISSUE TITLE
Youtube Ads sneaking through on IOS Safari browser

### ISSUE THREAD

**Issue by Blind-Watcher** [AdguardTeam/AdguardForiOS#1740]
### Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details
On youtube in the IOS Safari browser, a white blank “video” is appearing with a “skip ad” button. Youtube is likely testing a new anti-adblock measure, and this is the result.

### Expected Behavior
A seemless ad free experience on Youtube, which had been the case until today.

### Actual Behavior
Ads, if very broken ones.

**Comment by zzebrum** [comment]
@Blind-Watcher sorry for the late reply! What filters are enabled for Safari?

**Comment by Blind-Watcher** [comment]
Adguard base filter
Mobile ads filter
Easylist filter
Peter Lowe’s blocklist

And it’s all updated.

**Comment by MacCZ** [comment]
Same problem here. When I open YouTube video I see white “video” with text “skip ad” 

filters used: 
AdGuard base filters 
AdGuard mobile filters 
Easy privacy 
AdGuard social media filters 
AdGuard annoyances filter 
Region specific filter (Czech and Slovak filter)

**Comment by Aydinv13** [comment]
@MacCZ @Blind-Watcher can you please provide us with recent logs? It's not reproducible on our side so your logs will help us. Could you also turn on debug logs and after that surf in YouTube 
Here is email: apple@adguard.com
Thank you!

**Comment by Blind-Watcher** [comment]
Ads are now getting through in full. Sent logs.

**Comment by sgreadly** [comment]
Same here, past ~2 or so weeks ads were creeping in, but since today morning Youtube ads are not being blocked at all. Every video has an ad. 

Attached debug logs. 

This seems also related to Issue 1760. 

[AdGuard_logs.zip](https://github.com/AdguardTeam/AdguardForiOS/files/6476086/AdGuard_logs.zip)

**Comment by sgreadly** [comment]
Thanks, yea that seems to work here as well. I hope they can take out the working part from their experimental section into production ^_^

**Comment by ameshkov** [comment]
Guys, you may want to check this out: https://adguard.com/en/blog/how-to-add-a-shortcut-to-block-youtube-ads.html

**Comment by sgreadly** [comment]
It looks like the experimental section didn't last long.. I got hit with ads again yesterday until now :(

**Comment by sgreadly** [comment]
The shortcut method does work so far. I'll keep testing it to see if any bugs/issue arise.
