### ISSUE TITLE
DNS filtering feature not available when native mode enabled.

### ISSUE THREAD

**Issue by CSharper63** [AdguardTeam/AdguardForiOS#1744]
Hello, could you implement custom user rule dns filtering when dns native mode is enabled (I saw that it was only available when the dns mode is set on Adguard). The goal would be to block system wide domain like facebook or whatever.

**Comment by 08kovalchuk03** [comment]
@CSharper63 As this feature is provided by OS itself and Apple hasn't provided API for blocking domains it appears to be impossible.
