### ISSUE TITLE
Fanboy's Anti-thirdparty Fonts

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#175]
could we add this list to filters?

https://fanboy.co.nz/fanboy-antifonts.txt

**Comment by ameshkov** [comment]
Yeah, I guess we can.

@mmigi @Alex-302 could you please take care of it?

**Comment by Alex-302** [comment]
Added to
```
\ABP\OtherFilters\FanboyAntifonts\
```

**Comment by jo2dan23** [comment]
Thankyou

**Comment by ameshkov** [comment]
@jo2dan23 wait a bit, don't close it until @mmigi add it on the server side.

**Comment by jo2dan23** [comment]
could we still add this to the filter lists in adguard?

**Comment by ameshkov** [comment]
@jo2dan23 my bad, I should've moved it to the proper repo LONG ago:
https://github.com/AdguardTeam/AdguardFilters/issues/5382

Will do soon.

**Comment by buawf** [comment]
@ameshkov  
 
 Is there any font filter provided by AdGuard ? or kindly suggest (a better alternative from AdGuard itself) Me Dear.

**Comment by ameshkov** [comment]
@buawf not really, it makes little sense to replicate Fanboy's filter list as the list is actually very short and rarely changes.
