### ISSUE TITLE
AdGuard forgets Setapp license ~24 hours after activation

### ISSUE THREAD

**Issue by adamfeldman** [AdguardTeam/AdguardForiOS#1750]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  AdGuard for iOS v4.1.1 (668) 
- **Device model and storage size:**
  - iPhone 11 Pro Max 
- **Operating system and version:**
  - iOS 14.4.2 

### Expected Behavior

AdGuard worked perfectly with Setapp until sometime in March 2021. One day I realized my AdGuard for iOS had forgotten its Premium license, which was activated via Setapp. 

The only way to re-activate it was to delete the AdGuard app and re-install – this caused me to lose my settings and statistics each time, which was frustrating. 

After reactivating, AdGuard for iOS always again loses its Premium license activation, after approximately 24 hours.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by zzebrum** [comment]
@adamfeldman hi there! I'll check the issue on our side 👌

**Comment by adamfeldman** [comment]
Thank you @zzebrum! My last re-test of this was when I filed this issue ~23 hours ago, and the license hasn't yet been forgotten – as of a week ago it wasn't working. Will update here again regardless about a day from now.

**Comment by adamfeldman** [comment]
This seems to be fixed – my Adguard for iOS has not lost its Premium license since re-licensing a few days ago. Love Adguard and Setapp, thanks yall! @zzebrum

**Comment by adamfeldman** [comment]
This is not fixed. The same problem is still occurring. 

It is possible the problem is triggered by (1) excluding the current WiFi network from DNS protection, then (2) leaving that WiFI network. 

The reason I believe that is because the licensing was working properly , until I realized a few days later that I forgot to exclude the WiFi network as I had previously.

I will try to test this.

**Comment by zzebrum** [comment]
@adamfeldman if you want to try beta version where the issue should be fixed let me know
