### ISSUE TITLE
Feature Request: When using Native Implementation, opens ios settings

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#1752]
Hi team,

Can we please have the ability that when I selected Native Implementation and i enabled it, when the pop up says go to settings, the OK button when Clicked will go to the iOS settings?

Currently, when you click ok, it just remove the pop up. It will be great if when clicked, it will go to the iOS settings -> VPN and Network Menu. Instead of manually opening the settings app.

The nextdns app has this. When enabled, and the user click OK, it will open the iOS settings automatically.

it will be less click.

**Comment by Aydinv13** [comment]
@zznosar hi there!
For now there are complications with this feature because it's based on undocumented APIs(it's unlikely that we definitely can pass review) and recently Apple is rejecting apps with this approach (since iOS12).
