### ISSUE TITLE
Another Fake adGuard App - Please report to Apple

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#1756]
Hi all,

Can you please report this fake adGuard app to apple? 

https://apps.apple.com/au/app/adguard-secure/id1542070854

![6AB66C3A-9C1A-4FA0-BD44-4D3F285593FE](https://user-images.githubusercontent.com/27464836/116859307-22b4e980-ac43-11eb-9681-5e7606118aed.png)
![2EDED074-E4C2-42DF-BCB2-32BC1F962A22](https://user-images.githubusercontent.com/27464836/116859315-27799d80-ac43-11eb-8c37-92f163a582e3.png)

**Comment by Quorum75** [comment]
Why is it fake? It is just another app. The term of Adguard isn't copyrighted.

**Comment by zznosar** [comment]
You mean this?

https://euipo.europa.eu/eSearch/#details/trademarks/W01309055

also, it will confuse user. Think about it as like this, you are selling something, and a competitor is selling the exact same name as yours. People bought it, when they have issues to that product, they will come to you since googling it will show you as the owner.

**Comment by zzebrum** [comment]
Thank you! We've reported about it to Apple 👍
