### ISSUE TITLE
AdGuard forgets Setapp license ~24 hours after activation

### ISSUE THREAD

**Issue by adamfeldman** [AdguardTeam/AdguardForiOS#1757]
I am reopening #1750. The same problem is still occuring.

Please see this comment: https://github.com/AdguardTeam/AdguardForiOS/issues/1750#issuecomment-823271117.

I have opened a new issue because the old issue has the following labels which I cannot remove: `Resolution: Fixed`, `Status: Closed`

Thank you!

**Comment by Aydinv13** [comment]
We've reopened previous issue https://github.com/AdguardTeam/AdguardForiOS/issues/1750
We will check it again
Thank you!

**Comment by adamfeldman** [comment]
Thank you @Aydinv13!
