### ISSUE TITLE
Fongo - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#176]
App link:
https://itunes.apple.com/us/app/fongo-world-edition/id860809977?mt=8

Source:
http://forums.macrumors.com/threads/ios-9-content-blockers-mini-reviews.1918483/page-36#post-23693900

**Comment by gshumihin** [comment]
Here's log
[fongo.txt](https://github.com/AdguardTeam/AdguardForiOS/files/524941/fongo.txt)

**Comment by Alex-302** [comment]
@gshumihin а время запуска приложения?

**Comment by Alex-302** [comment]
@gshumihin

**Comment by gshumihin** [comment]
Here's new log:
[fongo.txt](https://github.com/AdguardTeam/AdguardForiOS/files/533458/fongo.txt)
Launched Fongo at 15:30-15:31

**Comment by ganja24** [comment]
I am still getting in app ads for Fongo

**Comment by ameshkov** [comment]
@gshumihin please record log with Fiddler for this app

**Comment by Alex-302** [comment]
Please check following rules in Adguard for Windows, when iOS is connected through Fiddler
```
||iadsdk.apple.com^
iadsdk.apple.com.edgekey.net
||e4805.a.akamaiedge.net^
```

**Comment by ameshkov** [comment]
@gshumihin first try it with `||iadsdk.apple.com^` alone. I suppose other requests are made due to response form that domain.

**Comment by gshumihin** [comment]
I can still see this banner with Alex's rules:
<details>
![slack for ios upload-2](https://cloud.githubusercontent.com/assets/8577547/19519013/99e6d8d4-9612-11e6-9d86-7c6b698fb36b.jpg)
</details>

Here's log: 
[Fongo.saz.txt](https://github.com/AdguardTeam/AdguardForiOS/files/538978/Fongo.saz.txt)

**Comment by gshumihin** [comment]
BTW: It looks like this is built-in banner.

**Comment by Alex-302** [comment]
Looks like builtin dummy.

**Comment by gshumihin** [comment]
So should we close this issue?
