### ISSUE TITLE
The rule doesn't work on youtube.com

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdguardForiOS#1760]
The rule `&pltype=adhost^` from the base filter doesn't work on youtube.com (log in to check), it exists in optimized filter and works from user rules.

<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/18536328/118007346-bded4380-b354-11eb-880e-abc7504dae5e.png" />
</details>

**Comment by Sergey-Lyapin** [comment]
FYI: I added`&pltype=adhost$domain=youtube.com` to the base filter

**Comment by sgreadly** [comment]
I've noticed this over the past 2 weeks at least. Eventually it starts blocking again, but today it refuses to block youtube ads at all. Attached debug logs. 

[AdGuard_logs.zip](https://github.com/AdguardTeam/AdguardForiOS/files/6475158/AdGuard_logs.zip)

**Comment by sgreadly** [comment]
This seems also related to issue 1740.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/SafariConverterLib #16](https://github.com/AdguardTeam/SafariConverterLib/issues/16) via [**ZenHub**](https://www.zenhub.com/)
