### ISSUE TITLE
Filter updates: no updates found

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1762]
While updating your filters, AdGuard (4.1.1) mentions „no updates found“ first and then x filters updated.
AdGuard should directly mention how many filters were updated.

https://user-images.githubusercontent.com/83946731/119118195-455c4600-ba2a-11eb-9400-1a99c5d048fe.MOV

**Comment by Aydinv13** [comment]
@iDjay This part will be completely fixed in version 4.2 as well as other issues here https://github.com/AdguardTeam/AdguardForiOS/issues/1755 . Check for any changes in this issue because it's related problem. Thank you!
