### ISSUE TITLE
Add a new action extension for blocking YouTube ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1763]
We'll use the same approach as the one we're using here: https://adguard.com/en/blog/how-to-add-a-shortcut-to-block-youtube-ads.html

1. The difference is that this action extension will be installed automatically alongside AdGuard.
2. Also, there'll be an instruction explaining how to use it

We should push an update with it asap, not waiting for other tasks scheduled on 4.2.

**Comment by lancelot-moon** [comment]
Also upload its English phrases to Crowdin for translating.
