### ISSUE TITLE
Migration of DoQ upstream does not work with v4.2

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#1766]
Here's what happened:

1. I updated v4.1 to v4.2
2. The custom DoQ upstream I had in my settings was seemingly updated and port `:784` was added (which is expected behavior)
3. However, nothing changed in reality. According to the logs, the app was still trying to use it without any port.
4. When I opened "Custom upstreams", opened that upstream and tried to "Save" it, it was not working. Again, according to the logs it was ignoring the port despite that it was written in the input field.
5. Only when I removed the port and added it back it started to work.

**Comment by Aydinv13** [comment]
This problem seems to be fixed in 4.2.0
