### ISSUE TITLE
TextNow - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#177]
Link to the app:
https://itunes.apple.com/us/app/textnow-free-text-+-calls/id314716233?mt=8

Source:
http://forums.macrumors.com/threads/ios-9-content-blockers-mini-reviews.1918483/page-36#post-23693900

**Comment by gshumihin** [comment]
There is no ads inTextNow for me:
<img src="https://cloud.githubusercontent.com/assets/8577547/19311410/f049706e-9096-11e6-93bc-eb70169ae872.jpg" width="300">

**Comment by jo2dan23** [comment]
admarvel.s3.amazonaws.com
www.leanplum.com

**Comment by ganja24** [comment]
Which filters do you have enable? I still see the ads on TextNow?

**Comment by gshumihin** [comment]
@ganja24 in-apps ads are filtered by DNS, so it doesn't really matters what filters are enabled.

**Comment by ganja24** [comment]
I provided the screenshots seems like ads won't go away for these 2 apps

**Comment by ganja24** [comment]
As you can see in the pics Adguard DNS is enabled but the in app ads for both apps TextNow and Fongo are showing. How is it possible you are not seeing ads and I am seeing the ads? Did you purchase in app to remove ads?

**Comment by jo2dan23** [comment]
The two hostnames i posted above are probably causing the ads. They are both ad companys

**Comment by jo2dan23** [comment]
Leanplum is the most complete mobile marketing platform it says

**Comment by ameshkov** [comment]
I suppose @jo2dan23 is right, we should block both

**Comment by ameshkov** [comment]
@Alex-302 ?

**Comment by Alex-302** [comment]
@ameshkov 
Added to Mobile filter
```
||admarvel.s3.amazonaws.com^$empty
||leanplum.com^$empty
```

**Comment by Alex-302** [comment]
Please don't close it. 
I will check these rules in DNS filter later and close.

**Comment by ganja24** [comment]
In app ads for TextNow is still showing and thread is closed?

**Comment by Alex-302** [comment]
S

**Comment by Alex-302** [comment]
Strange. Please Collect a new log.

**Comment by jo2dan23** [comment]
No ads seen on my side and thats with no premium purchased.

**Comment by ganja24** [comment]
How do I collect a log?

**Comment by gshumihin** [comment]
You can send Bug report from app. Log will be included by default.

**Comment by ameshkov** [comment]
@gshumihin it'd be better if you use fiddler to extract requests done by the app.

**Comment by gshumihin** [comment]
Here's Fiddler log: [TextNow.txt](https://github.com/AdguardTeam/AdguardForiOS/files/536914/TextNow.txt)

**Comment by ameshkov** [comment]
@Alex-302 please take a look.

@gshumihin next time export it in the HTTP archive format so that we could use softwareishard.com/har/viewer/ to analyze.

**Comment by Alex-302** [comment]
@gshumihin Please make a screenshot of the banner.
And check this rule
```
||iadsdk.apple.com^
```
You can do it with Adguard for windows, when iPhone is connected through Fiddler.

**Comment by gshumihin** [comment]
I have no ads in this app.

**Comment by ameshkov** [comment]
In fact as i know they also use `qwapi.com` for iAds.

@gshumihin please check that blocking these two domains won't break the app:
`iadsdk.apple.com`
`qwapi.com`

If the app is ok, we should add both domains to "mobile ads filter".

**Comment by ganja24** [comment]
firehose.us-west-2.amazonaws.com

cognito-identity.us-east-1.amazonaws.com

I noticed these 2 above possible are parts of the in app ads showing in the Adguard Pro DNS requests log. Possible the ads are targeted for different regions is why i see ads and some don't?

**Comment by ameshkov** [comment]
@ganja24 

First one belongs to [Amazon Kinesis](https://aws.amazon.com/kinesis/streams/)
Second one belongs to [Amazon Cognito](https://aws.amazon.com/cognito/).

These are not ad servers, so blocking it could mess with apps work.

JFYI, in the next version you'll be able to block any DNS request manually using your user filter (#161), so you won't need to wait until DNS rules are updated and check anything manually.

**Comment by gshumihin** [comment]
Looks like app works fine with this 2 domain added to blacklist. But finally, I was able to see banner in this app:
<details>
![TextNow](https://cloud.githubusercontent.com/assets/8577547/19559453/9cabb528-96d8-11e6-8d4a-74bff9aa8a35.jpg)
</details>
And here's log: 
[TextNow.saz.txt](https://github.com/AdguardTeam/AdguardForiOS/files/541649/TextNow.saz.txt)

**Comment by ameshkov** [comment]
@gshumihin i am pretty sure this ad is built-in.

@Alex-302 could you please check the log? If everything is ok, we should add these two domains to mobile ads filter.

**Comment by gshumihin** [comment]
Yeah I think this is built-in too.

**Comment by Alex-302** [comment]
@ameshkov I see only iadsdk.apple.com(blocked), but no qwapi.com
@gshumihin do you see only the dummy at the bottom? Top banner should be blocked.

**Comment by gshumihin** [comment]
Yes, only dummy at the bottom, nothing else.

**Comment by Alex-302** [comment]
Ok, iadsdk.apple.com is in DNS filter now.

**Comment by gshumihin** [comment]
I guess we can close this one?
