### ISSUE TITLE
“Report an issue on this page” webpage is broken

### ISSUE THREAD

**Issue by notDavid** [AdguardTeam/AdguardForiOS#1773]
### Issue Details

- **AdGuard version:**
  - Adguard for iOS 4.1.1
- **Device model and storage size:**
  - iPad Pro 12.9
- **Operating system and version:**
  - iPadOS 14.6
- **Browser or App:**
  - Safari

### Expected Behavior
1. In Safari go to some webpage
2. Click Share -> Adguard Pro > Report an issue on this page]
3. You are redirected to https://reports.adguard.com/en/new_issue.html?filters=2.3.6.8.11.101.106.107.118.204.225&product_version=4.1.1&dns.enabled=false&url=https:%2F%2Fgithub.com%2FAdguardTeam%2FAdguardForiOS%2Fissues%2Fnew?assignees%3D%26labels%3D%26template%3DBug_report.md&product_type=iOS&browser=Safari
4. Fill in the questions to report a non working webpage

### Actual Behavior

In Step 5, after you upload the screenshot, you will get stuck at the “Submit a screenshot” page because the “Next” button is disabled / not clickable.

### Screenshots

<details><summary>Screenshot:</summary>

![IMG_0071](https://user-images.githubusercontent.com/1530401/121190005-eb051700-c86a-11eb-9443-f2c94334c496.jpeg)

</details>

**Comment by Aydinv13** [comment]
@notDavid You need to upload two photos as it's described above
https://uploads.adguard.com/Aydin2kuab.png
