### ISSUE TITLE
iOS 15

### ISSUE THREAD

**Issue by dahauss** [AdguardTeam/AdguardForiOS#1774]
I know the beta of iOS 15 just came out yesterday, but i screwed to report AdGuard does not work. Safari tells me no internet connection. I disable it, and all works.  There are other apps that will not work when this is enabled as well.  

Thank you…

**Comment by 08kovalchuk03** [comment]
@dahauss Try to disable iCloud Private Relay in Settings -> Wi-Fi -> Your Wi-Fi name -> iCloud Private Relay

**Comment by dahauss** [comment]
> @dahauss Try to disable iCloud Private Relay in Settings -> Wi-Fi -> Your Wi-Fi name -> iCloud Private Relay

Looks like that may have solved it.  I’m going to test and will report back in a day or two

**Comment by Aydinv13** [comment]
The issue has been closed for now. Reopen if the problem persists, please.
