### ISSUE TITLE
lost internet connection then vpn restart loops until i restart the phone 4.2.0 (704)

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardForiOS#1775]
i was playing a game and then it lost connection from the vpn my wifi was working on other devices so i know it is a bug but it wouldn't stop connecting and reconnecting so i had to restart my phone. hopefully this log helps. 

https://ufile.io/7e9vvlrs

also here is a video showing the restart loop:

https://ufile.io/dy6cmwjhi

**Comment by jordanelliott23** [comment]
restart loop between 16:00-16:09

**Comment by zzebrum** [comment]
@jordanelliott23 thanks, devs are taking a look into it already

**Comment by jordanelliott23** [comment]
i got another restart while using the facebook app. can this be looked into. the restart happens between 14:56-14:59


https://ufile.io/we5gkdq3

**Comment by zzebrum** [comment]
@jordanelliott23 those crashes from your logs were fixed in v4.2.1 beta

**Comment by Aydinv13** [comment]
@jordanelliott23  Can you please check if the behaviour is reproducible?
