### ISSUE TITLE
Optimize User Rules

### ISSUE THREAD

**Issue by VGisHere** [AdguardTeam/AdguardForiOS#1780]
### Problem Description
Today, if I have to add user rules for a certain website, each of user rules gets added as new rule. And If I have many user rules enabled along with some other rules available over the net, it may happen that one can cross 50k limit and hence has to disable some rules. So, I was guessing if Adguard could add an option -> Optimize User Rules, which will be an action that cant be undone, to reduce the no. of user rules by clubbing those for same website.
PS: By user rules, I mean Elements added by -> "Block an element on this page"

### Proposed Solution
On clicking Optimize User Rules, a script will run on the user rules which will first sort all the domains present.
Once we have a sorted list, we then go parse the all elements and if starting domain is similar, we append the rules thereby reducing the no. of rules.

Eg,
Rule 1: example.org##.eg1, .eg2
Rule 2: example.org##.eg3
Rule 3: example1.org##eg4
Rule 4: example2.org##eg5
Rule 5: example.org##eg6
Rule 6: ||exam.org

On optimizing,
Rule 1: example.org##.eg1, .eg2, .eg3, .eg6
Rule 2: example1.org##.eg4
Rule 3: example2.org##.eg5
Rule 4: ||exam.org

Effectively reducing the no. of user to no. of unique domains.
If 'www.' is present in front of some rule, trim it

If rule doesnt start with alphabetORdigit, append it as is.

**Comment by VGisHere** [comment]
@AdamWr  @Alex-302  @BlazDT  @Sergey-Lyapin @ameshkov

**Comment by VGisHere** [comment]
@ameshkov 
Say if I add elements from website to block and a couple of days later they come up with another element that I need to block, and then some more elements, in that scenario, in my opinion, it would be better to have just 1 rule instead of multiple rules.
AdGuard is definitely using optimisation for their rules, and I’m requesting a similar feature for user rules.

**Comment by ameshkov** [comment]
AdGuard internally will group cosmetic rules into a single rule even though in the editor they'll look like N different rules.
