### ISSUE TITLE
YouTube ads are back (YouTube symbol block)

### ISSUE THREAD

**Issue by MacCZ** [AdguardTeam/AdguardForiOS#1781]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS ver. 4.2.0 (704)
- **Device model and storage size:**
  - Phone 6s 32gb 
- **Operating system and version:**
  - iOS 14.6.
- **Browser or App:**
  - iOS Safari

### Expected Behavior

Block ads by default 

### Actual Behavior

YouTube video blocked with YouTube symbol 

### Screenshots

<details><summary>Screenshot:</summary>

![IMG_E0003](https://user-images.githubusercontent.com/50764475/122915487-15230280-d35c-11eb-8c8e-4bc586e18b92.JPG)

</details>

**Comment by VGisHere** [comment]
You may want to try this https://github.com/AdguardTeam/BlockYouTubeAdsShortcut 

Steps -
1. Open Youtube
2. Click on share
3. Click on Block Ad by adguard option (v4.2)
4. Play video and done. No more ads
5. If you reload, you have to go back to step 2

**Comment by MacCZ** [comment]
> 
> 
> You may want to try this https://github.com/AdguardTeam/BlockYouTubeAdsShortcut
> 
> Steps -
> 
>     1. Open Youtube
> 
>     2. Click on share
> 
>     3. Click on Block Ad by adguard option (v4.2)
> 
>     4. Play video and done. No more ads
> 
>     5. If you reload, you have to go back to step 2

Thanks for reply, but from what I understand AdGuard in ver. 4.2.0. (TestFlight) has this shortcut integrated in the content blocker so its not needed to start it manualy.

**Comment by VGisHere** [comment]
> 
> 
> > You may want to try this https://github.com/AdguardTeam/BlockYouTubeAdsShortcut
> > Steps -
> > ```
> > 1. Open Youtube
> > 
> > 2. Click on share
> > 
> > 3. Click on Block Ad by adguard option (v4.2)
> > 
> > 4. Play video and done. No more ads
> > 
> > 5. If you reload, you have to go back to step 2
> > ```
> 
> Thanks for reply, but from what I understand AdGuard in ver. 4.2.0. (TestFlight) has this shortcut integrated in the content blocker so its not needed to start it manualy by default.

Well, I fear the assumption is wrong.
By integrated it means, we dont need an additional shortcut like previously we had to add an additional shortcut.
But the way of implementation still remains the same, you got to call it from sharesheet.
If you dont see "with Adguard" in youtube logo, that means you would still see ads.

**Comment by Aydinv13** [comment]
Please describe in more detail what you did before it happened. Does phone reboot help solve the problem? Do you see "Block Youtube Youtube ads" in share sheet? Are there additional apps/extensions related to adblocking in your phone?

**Comment by MacCZ** [comment]
> 
> 
> > > You may want to try this https://github.com/AdguardTeam/BlockYouTubeAdsShortcut
> > > Steps -
> > > ```
> > > 1. Open Youtube
> > > 
> > > 2. Click on share
> > > 
> > > 3. Click on Block Ad by adguard option (v4.2)
> > > 
> > > 4. Play video and done. No more ads
> > > 
> > > 5. If you reload, you have to go back to step 2
> > > ```
> > 
> > 
> > Thanks for reply, but from what I understand AdGuard in ver. 4.2.0. (TestFlight) has this shortcut integrated in the content blocker so its not needed to start it manualy by default.
> 
> Well, I fear the assumption is wrong.
> By integrated it means, we dont need an additional shortcut like previously we had to add an additional shortcut.
> But the way of implementation still remains the same, you got to call it from sharesheet.
> If you dont see "with Adguard" in youtube logo, that means you would still see ads.

Well thats weird.. Because after updating to version 4.2.0. I havent seen ads until yesterday (without need for using shortcut). 

@Aydinv13 Actually I did nothing, but its true that I didnt use shortcut for blocking youtube ads. It was working just fine until yesterday.. But after using shortcut "block youtube ads" its working fine again. But I found it weird that it was working fine even without need for shortcut.

**Comment by Aydinv13** [comment]
New version 4.2.0 implies working Adguard using this shortcut. You may see no ads without using shortcut for some time but the fact is that ad is leaking through anyway so you need to use "Block Youtube Ads" to be sure that there is no ad in Youtube. If you see ad when shortcut is on please let us know and reopen this issue
