### ISSUE TITLE
FaceID / TouchID protection on all the app for pro.

### ISSUE THREAD

**Issue by Macqael** [AdguardTeam/AdguardForiOS#1786]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Actually if I let someone to use me phone he can disable or modify the settings of AdGuard.

### Proposed Solution

Add FaceID / TouchID to open the app.
Unlike the request here : https://github.com/AdguardTeam/AdguardForiOS/issues/474
It's not only for dns but for all the app.

### Alternatives Considered

None.

### Additional Information

None.

**Comment by anastenko** [comment]
@Macqael Hello.
The issue you mentioned considers not only DNS-protection, but the entire application. So I'm closing this one as a duplicate.

**Comment by Macqael** [comment]
@anastenko Sorry but you have done a mistake reread it : "The DNS filtering as a new Pro feature is nice, but children or other users can easily disable this feature. That's why there should be a possibility to protect accessing the app via Touch ID.".

HE talk about ONLY about dns feature it's not a duplicate, and Three year after none reaction it say (no we won't do it)

**Comment by anastenko** [comment]
@Macqael Originally it was meant for DNS filtering feature only, but after several other comments it was clear the users need pin or Touch ID for the entire application, so [#474](https://github.com/AdguardTeam/AdguardForiOS/issues/474) is the main feature request to this matter, and others are being closed.
