### ISSUE TITLE
Ads in apps Fongo and TextNow

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardForiOS#179]
Fongo:
https://itunes.apple.com/ca/app/fongo-free-calls-+-free-texts/id473770452?mt=8
TextNow:
https://itunes.apple.com/us/app/textnow-free-text-+-calls/id314716233?mt=8
Device: iPhone
<details>Platform: iOS
OS: 10.1
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.96.65 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.98 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.36 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.3 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.46 Enabled=YES
</details>
Screenshots
<details>
![fongo](https://cloud.githubusercontent.com/assets/20476168/19282239/2b3b1eda-8ff6-11e6-86eb-408128d7f72a.PNG)
![textnow](https://cloud.githubusercontent.com/assets/20476168/19282240/2b55e468-8ff6-11e6-9705-7867a14b54c7.PNG)
</details>
Ticket ID 1303217

**Comment by gshumihin** [comment]
There is no ads inTextNow for me:
<img src="https://files.slack.com/files-pri/T0B41S97U-F2NAKH5DH/slack_for_ios_upload.jpg" width="300">

**Comment by gshumihin** [comment]
And we already have opened issues for this apps: #176 and #177
