### ISSUE TITLE
Add the ability to customize notifications

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForiOS#1793]
### Problem Description
I don't need all the notifications from AdGuard, but I can't customize it.

### Proposed Solution
Add the ability to customize notifications in the app settings. That is, so that I can separately enable/disable notifications when I enable the extension to block ads on YouTube, license expiration, and so on.

### Alternatives Considered
Add notification customizing to System Settings > Notifications > AdGuard.

**Comment by anastenko** [comment]
@rakleed Hello.
There's no need in implementing this feature, since we don't have lots of notifications from the application. Furthermore, it won't be a problem for iOS version 15 and higher.

**Comment by rakleed** [comment]
@anastenko why won't this be the problem in iOS 15 and higher?

**Comment by anastenko** [comment]
There will be no need in clicking "Block YouTube ads by AdGuard" button, so the notification won't bother.
