### ISSUE TITLE
Safari Web Extension for applying advanced rules (extended CSS, scriptlets, etc)

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForiOS#1794]
### Problem Description
The current implementation of Safari extensions for iOS is very limited, which is why AdGuard cannot block some ads, disable AMP, etc.

### Proposed Solution
Make a Safari extension for iOS 15 and newer using the WebExtensions API.

### Additional Information
- https://developer.apple.com/documentation/safariservices/safari_web_extensions
- https://developer.apple.com/videos/play/wwdc2021/10104
- https://adguard.com/en/blog/apple-wwdc21-browser-extensions-on-ios.html
- https://www.reddit.com/r/iOSBeta/comments/om1q3k/list_of_safari_extension_on_testflight/

**Comment by ameshkov** [comment]
@rakleed it's already in progress, but we didn't have a public task for that. Now we have, thank you:)

**Comment by rakleed** [comment]
@ameshkov iOS 15 came out a few days ago, but the Web Extension for iOS still isn't there. Why?

**Comment by ameshkov** [comment]
@rakleed expect it to be ready really soon.

**Comment by zeezeepiggy** [comment]
@ameshkov , will this update have an option to disable AMP pages? Android version already has it. Hopefully we can integrate it to ios now that ios 15 supports safari extension. 

I will create a separate request ticket of required.

**Comment by ameshkov** [comment]
@zeezeepiggy definitely need a new issue for that

**Comment by zeezeepiggy** [comment]
https://github.com/AdguardTeam/AdguardForiOS/issues/1827

Raised for this.

**Comment by RouterCFW** [comment]
> @rakleed expect it to be ready really soon.

🤩

**Comment by RouterCFW** [comment]
[](https://tenor.com/view/stranger-things-stranger-things2-netflix-eleven-soon-gif-14953342)

> @rakleed expect it to be ready really soon.

**Comment by RouterCFW** [comment]
> @rakleed expect it to be ready really soon.

[](https://tenor.com/view/stranger-things-stranger-things2-netflix-eleven-soon-gif-14953342)

**Comment by RouterCFW** [comment]
> @rakleed expect it to be ready really soon.

![EC347207-1343-4DF8-84B0-3C802367AA94](https://user-images.githubusercontent.com/44432632/140846688-98fae8ef-3fd6-4e8b-8b75-ee4d240c7412.gif)

**Comment by rakleed** [comment]
@ameshkov is there any news? Otherwise, you have been conducting internal testing for almost two months (https://github.com/AdguardTeam/AdguardForiOS/tags), but at least you have not published a new version in TestFlight (https://testflight.apple.com/join/XqF1FkBg). Why haven't you added version 4.3.0 to TestFlight yet?

**Comment by ameshkov** [comment]
@rakleed I am sorry for the delay, internal testing takes more time than expected. Bugs need to be addressed before this version is available for public testing.

> Why haven't you added version 4.3.0 to TestFlight yet?

We usually only publish beta versions when we're sure that they're stable and internal QA cannot find any serious issues.
