### ISSUE TITLE
Animation appears with a delay when I click on the update filters icon

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForiOS#1795]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v4.2.1
- **Device model and storage size:**
  - iPhone XR 64GB
- **Operating system and version:**
  - iOS 15.0 public beta 3

### Expected Behavior

When I click on the icon to update the filters, the animation of the icon appears immediately.

### Actual Behavior

When I click on the icon to update the filters, the animation of the icon appears with a delay of 2-4 seconds.

**Comment by zzebrum** [comment]
AdGuard's code under refactoring now so it won't be a problem in the next versions.
