### ISSUE TITLE
Is it possible to check if Adguard is enabled using SafariViewController?

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#18]
For instance we may open a test webpage there and check if ads are blocked

**Comment by maxart2007** [comment]
Like iphone does: it goes to captivate.apple.com to check if internet is available or redirect to some wi-fi gateway is being used.

**Comment by worldsdream** [comment]
Yes it is now possible:

https://adguard.com/en/test.html

@ameshkov will this be added in the adguard ios app, so we can click on it and it will open up the test page: https://adguard.com/en/test.html

Or we click on a button in adguard app and it will check and tells us if all is OK and running.

**Comment by ameshkov** [comment]
> @ameshkov will this be added in the adguard ios app, so we can click on it and it will open up the test page: https://adguard.com/en/test.html

> Or we click on a button in adguard app and it will check and tells us if all is OK and running.

Isn't it redundant to have it inside of the app? I mean you are inside of the app already.

**Comment by worldsdream** [comment]
Exactly. You're in the app already. But have you enabled it in safari settings? Thats what the most forget.

**Comment by ameshkov** [comment]
This will be resolved in v2.0 (the first beta is rather close).

The thing is that we can now programmatically check if it's enabled in Safari settings, no need to use ugly hacks (like an invisible safariviewcontroller or smth like that).

**Comment by worldsdream** [comment]
Perfect!

**Comment by ameshkov** [comment]
Closing as it's done already
