### ISSUE TITLE
TapeACall - recordings can't be reached with Adguard enabled

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardForiOS#180]
TypeACall
https://itunes.apple.com/us/app/tapeacall-pro-record-phone/id577499909?mt=8
Trying to access my call recordings which are on the Developer's servers, it
does cannot be reached.
Once I stop Adguard DNS, everything returns to normal.

When Adguard Disabled
<details>![1](https://cloud.githubusercontent.com/assets/20476168/19282537/6c9e08be-8ff7-11e6-8311-1d5b702dd7c4.jpg)
</details>
When Adguard Enabled
<details>![2](https://cloud.githubusercontent.com/assets/20476168/19282551/8075f9f0-8ff7-11e6-9fd7-259c3a525d04.jpg)</details>

Ticket ID 1423882

**Comment by Alex-302** [comment]
There are too many records in DNS log. Please ask for a new log after few attempts, and with a time when attempts were made.

**Comment by Alex-302** [comment]
Like this
<details>
<img src="https://cloud.githubusercontent.com/assets/8577547/19383725/8e576c48-920e-11e6-9ef2-5d7cbfd41802.jpg">
</details>

**Comment by gshumihin** [comment]
@Fridrix contact user please

**Comment by evgeniy-ADG** [comment]
New logs: 1423882

**Comment by Alex-302** [comment]
@gshumihin please check this app without dns filtering and with blocked these domains
```
sdk.fiksu.com
api.segment.io
cdn.segment.com

www.googleadservices.com
gate.hockeyapp.net
ssl.google-analytics.com
e.crashlytics.com
```

**Comment by ameshkov** [comment]
@gshumihin ?
