### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1801]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AG iOS Beta 4.2.1 (710)
- **Device model and storage size:**
  -  iPhone 11 Pro Max. 
- **Operating system and version:**
  -  iOS 14.7
- **Browser or App:**
  - 

### Expected Behavior

 AG should connect automatically. 

### Actual Behavior

 For some unknown reasons AG tries to connect but can't make it. 

### Additional Information

 Log and Analytics data sent. Incident time July 30th at 2:48pm

**Comment by Quorum75** [comment]
@anastenko Just wondering, did you get this email?

**Comment by zzebrum** [comment]
@Quorum75 yep, thanks!

**Comment by Quorum75** [comment]
> @Quorum75 yep, thanks! 

Any feedback? Cheers.

**Comment by Aydinv13** [comment]
@Quorum75 will be fixed soon

**Comment by Quorum75** [comment]
> @Quorum75 will be fixed soon

It seems 4.3.0 (915) solved the issue, isn't it? I did not face any connection issue at the present time.

**Comment by AleksandrShulgin** [comment]
@Quorum75 
Refactoring was carried out in version 4.3.0, so most likely this problem shouldn't be repeated.
