### ISSUE TITLE
Block all outgoing connection to an app

### ISSUE THREAD

**Issue by errorsxp** [AdguardTeam/AdguardForiOS#1803]
There are some apps I like to use that function normally offline but they connect to the internet for advertisements or to send usage data. There should be a way to block a specific apps ability to connect to the internet by making AdGuard detect any domains used by that specific app. I know I can block each one individually but some apps have hundreds.

### Proposed Solution
A list of apps we can toggle to allow outgoing requests would be the ideal solution. 

### Alternatives Considered
Some way to just deny an app from connection would be good because it can also save data. The blocking now is good but there are also remnants of advertisements left behind that don't show with network off that aren't filtered.

### Additional Information
I'm not really suggestion a change to filters in general, I just want a way to massively block connections to an app. (I looked around for a solution but I couldn't find one)

**Comment by zzebrum** [comment]
@errorsxp Apple won't let apps to know basically anything about the other apps. So we can't implement this feature request :(
