### ISSUE TITLE
adguard restart twice while playing game on latest beta 4.2.1 (718)

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardForiOS#1806]
better 17:45-17:50 there was two restarts

https://ufile.io/818qvc9z

**Comment by Aydinv13** [comment]
Thanks for report, our devs are informed! We will work it out

**Comment by jordanelliott23** [comment]
anyone been able to pin down or reproduce

**Comment by 08kovalchuk03** [comment]
I've investigated the logs and it seems that we've already fixed this error. The fix will be available in the upcoming version, if the problem will persist let us know.
