### ISSUE TITLE
Not able to find ipa file for Adguard for Ipad 2.

### ISSUE THREAD

**Issue by EvansPM** [AdguardTeam/AdguardForiOS#1808]
I would like to install old version on my Ipad 2. I look at the release list and do not found it.

**Comment by Aydinv13** [comment]
Hi there!
Unfortunately, we don't distribute `.ipa` files for AdGuard and we don't support iOS lower than 11.2
In fact `.ipa ` files are not available on iOS (except for cases when using jailbreak)
