### ISSUE TITLE
Adguard doesn't block ads on imobile.com

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardForiOS#181]
Device: iPhone
<details>
Platform: iOS
OS: 10.0.2
ID: A276A090-3F67-4CB2-AAA4-A3CB11EAAC2E
Locale: en
Region: us
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.96.89 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.3 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.42 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.10 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.13 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.49 Enabled=YES
ID=101 Name="EasyList" Version=1.0.63.51 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.66.83 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.66.85 Enabled=YES</details>
Screenshot 
<details>
![im](https://cloud.githubusercontent.com/assets/20476168/19283080/4ce555c0-8ff9-11e6-9bdc-d3476b8e551b.PNG)
</details>
Ticket ID 1326352

**Comment by Alex-302** [comment]
Can't acces - DNS_PROBE_FINISHED_NXDOMAIN

**Comment by ameshkov** [comment]
@Alex-302 what do you mean?

**Comment by Alex-302** [comment]
This site is not working on my end, also with different DNS servers.

**Comment by vozersky** [comment]
obsolete
