### ISSUE TITLE
restart loop for 3 minutes

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardForiOS#1810]
i was using facebook app and clicked a news link article and it started restarting the vpn at 14:41 and stopped af 14:44

https://ufile.io/zeaafthu

**Comment by jordanelliott23** [comment]
i have had this happen the other day also where it kept looping but i never grabbed a log hopefully this help fixes that loop also

**Comment by jordanelliott23** [comment]
another restart loop while clicking link in tik tok app starts at 17:24 ends at 17:28 

https://ufile.io/rpq59a8i

**Comment by anastenko** [comment]
@jordanelliott23 Hello.
Thanks, our developers will look into it.

**Comment by jordanelliott23** [comment]
anyone been able to pin down or reproduce

**Comment by Birbber** [comment]
@jordanelliott23 
Still working on it. 
The new version is coming pretty soon, so there's a chance that it will be fixed in it.
