### ISSUE TITLE
Security filters get disabled after AdGuard reload

### ISSUE THREAD

**Issue by NaylyaM** [AdguardTeam/AdguardForiOS#1811]
### Issue Details

- **AdGuard version:**
  AdGuard for iOS v 4.2.1(718)
- **Device model and storage size:**
  iPhone Xr 128gb) -->
- **Operating system and version:**
  14.7.1

STR:

1. Open AdGuard Settings --> Safari Protection --> Filters --> Security
2. Enable Security filtering together with two available filters (Spam404 and NoCoin Filter List)
3. Swipe AdGuard app away from the device memory
4. Launch AdGuard app again.

### Expected Behavior

All filters enabled at Step 2 are still enabled.

### Actual Behavior

Some Security filters get disabled. Randomly, we get one filter disabled or both disabled or both enabled with entire Security section disabled or even everything enabled as it was expected.

### Additional Information

Please find some logs here: https://uploads.adguard.com/Naylya1ppyj.zip
The issue was detected on our side at 18:29 MSK today, on 18 Aug 2021.
Support ticket 530104

**Comment by artemiv4nov** [comment]
Fixed in the 4.3 version.
