### ISSUE TITLE
Google iOS 14 search in-page “pop up” issue

### ISSUE THREAD

**Issue by WoodpeckerBaby** [AdguardTeam/AdguardForiOS#1813]
I think this issue has been affecting almost everyone on iOS 14. 

https://discussions.apple.com/thread/251955316 

I hope there is a built-in way to stop this, as none of the filters can block it currently. 

I think this can be done with a cosmetic filter, but don’t know why no filter maintainer has done it. So, maybe it needs something deeper from the app developers.

**Comment by anastenko** [comment]
@WoodpeckerBaby Hi, I'm afraid there's nothing we can do about it. There's no way to block it.

**Comment by WoodpeckerBaby** [comment]
> @WoodpeckerBaby Hi, I'm afraid there's nothing we can do about it. There's no way to block it.

Is there a reason why it is impossible to block? Just curious.
