### ISSUE TITLE
blocking “request personal data” pop-up notifications

### ISSUE THREAD

**Issue by exrector** [AdguardTeam/AdguardForiOS#1816]
Greetings.  I love AdGuard and don't understand how you can live without it in the modern world.  The next thing I would like to ask you to do is block special site notifications.  Now each site asks for confirmation and consent to the collection of personal data.  Often this notification takes up half of the screen.  Usually I refuse or press X. But a lot of tricksters.  More and more often you have no choice, only the "accept" or "ok" button.  I do not want sites to collect personal data and do not want to allow them to do so.  I want to block any such windows.  In time, any of you will understand me.  Perhaps later you will understand and support my initiative.  Now you mindlessly agree to site requests and give marketing agencies information about yourself.  think about it!  (sorry for my English)

**Comment by anastenko** [comment]
@exrector Hello.
Have you tried "AdGuard Annoyances" or "I don't care about cookies" filters?

**Comment by exrector** [comment]
@anastenko I am using adguard pro for dns blocking.  The filters you listed are in the settings for safari.  But I am using chrome.  So.  My question is relevant regarding the dns level.  Thanks.

**Comment by anastenko** [comment]
@exrector Unfortunately, it's impossible to do on dns level.
