### ISSUE TITLE
Minor UI Glitch When Updating Filters

### ISSUE THREAD

**Issue by Ryan-Goldstein** [AdguardTeam/AdguardForiOS#1818]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v4.2.1(718)
- **Device model and storage size:**
  - iPhone XR 64 GB
- **Operating system and version:**
  - iOS 15 Public Beta 7

### Expected Behavior

When pressing the update button on the top right of the app home screen, I expect it to show how many filters were updated after it finishes.

### Actual Behavior

It shows "No updates found" briefly before showing how many filters were updated.

### Screen Recording

<details><summary>Screen recording:</summary>

https://user-images.githubusercontent.com/8300089/131572931-405f5a3d-a985-42c2-a9de-4a5ff9f0cc82.MP4

</details>

**Comment by anastenko** [comment]
@Ryan-Goldstein Hi, thanks for noticing. We've already received similar requests. AdGuard's code is under refactoring now, so there shouldn't be an issue in future versions.
