### ISSUE TITLE
Adguard PRO reported to slow down loading times of App Store and Music

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForiOS#182]
Source:
https://twitter.com/WarmTurtleTank/status/785913367013781508

Requested logs from customer **1429042**

**Comment by BlazDT** [comment]
Possible related issue:

https://forum.adguard.com/index.php?threads/apps-laden-im-appstore-nur-ganz-langsam.28026/

**Comment by ameshkov** [comment]
Duplicate of #413

Read this for details:
http://joemaller.com/2577/itunes-slowdowns-with-google-dns/
