### ISSUE TITLE
Feature request: Make ROad-Block List Light available in the Language-specific section

### ISSUE THREAD

**Issue by bogiord** [AdguardTeam/AdguardForiOS#1821]
Currently, only the (main) ROad-Block list is available as a stock filter list. It would be great if [the Light version](https://raw.githubusercontent.com/tcptomato/ROad-Block/master/road-block-filters-light.txt) were available as well, to give users a choice. 

Alternatively, you could consider only providing the light version, as some filters in the main version seem to be controversial. Also, the light version has received some fine-grained filter updates that, for some reason, don't seem to have propagated to the main list.

For reference, uBlock Origin [switched to the light version](https://github.com/gorhill/uBlock/commit/51bae66785dc828aadc01bacefc9bee046699574) some time ago; some discussion [here](https://github.com/gorhill/uBlock/issues/3603).

**Comment by Birbber** [comment]
I've moved this issue to another repository. Closing it here.
[Here's the link](https://github.com/AdguardTeam/FiltersRegistry/issues/526) to your feature request.
