### ISSUE TITLE
iOS 15 Private Relay with AG

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1823]
Hi.

I was wondering, how do you test the fact that AG it's working or not?

AG activity log still show a full list of requests blocked.

**Comment by Birbber** [comment]
@Quorum75 Hi!
AG activity log shows DNS requests. In order to check content blocking you can connect to mac via a wire and look into the console: there should be "blocked by content blocker" requests.

**Comment by Quorum75** [comment]
@Birbber Thanks. So AG blocks everything, so why support team says it doesn't work with Private Relay on?

**Comment by Birbber** [comment]
@Quorum75 I feel like I might misunderstood the question of yours. You asked how to test if Private relay works/ doesn't work with AdGuard, right?
Visually you can't tell if it works or not, but our team experimentally concluded that it surely doesn't work in Full-Tunnel mode. In Split-Tunnel mode it can partially work (there might be some unblocked requests).

**Comment by Quorum75** [comment]
> You asked how to test if Private relay works/ doesn't work with AdGuard, right?

@Birbber Correct. Also, I forgot to mention that I use Windscribe Pro in split tunnel with AG. It caches what AG doesn't do especially with iOS applications.

**Comment by Aydinv13** [comment]
>AG activity log still show a full list of requests blocked.

You mean you see only blocked requests? If so, select "All requests" in Activity tab
https://uploads.adguard.com/IMG_EBE8B7F05D2E-1.jpeg

**Comment by Quorum75** [comment]
> >AG activity log still show a full list of requests blocked.
> 
> 
> 
> You mean you see only blocked requests? If so, select "All requests" in Activity tab
> 
> https://uploads.adguard.com/IMG_EBE8B7F05D2E-1.jpeg
> 
> 

Nope that's not what I meant.

**Comment by AleksandrShulgin** [comment]
@Quorum75 
Do you have any more questions?

**Comment by Quorum75** [comment]
> @Quorum75 
> 
> Do you have any more questions?

Sorry for the delay. Nope thanks.
