### ISSUE TITLE
Adguard won't work on mobile data

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForiOS#183]
Cell provider - Videotron
Works fine with Wi-Fi, but not 3G/LTE

Log and further details - customer ID **1428730**

**Comment by jo2dan23** [comment]
It might be your cell provider. Works fine on mine on latest version

**Comment by ameshkov** [comment]
@Stillness-2 please take a look

**Comment by evgeniy-ADG** [comment]
1408227 : My carrier is T-Mobile USA.

**Comment by ameshkov** [comment]
@evgeniy-ADG could you please elaborate: what "does not work" mean?
It does not block anything? Or it cannot start? Or something else?

**Comment by evgeniy-ADG** [comment]
Doesn't block ads

>When I use Adguard DNS under the wifi, Adguard DNS blocks almost every ads in apps(even it still does not block YouTube ads ). But when it switches to Cellular, the Adguard DNS does not function well

**Comment by ameshkov** [comment]
Does the ticket contain "tunnel.txt" log?

**Comment by evgeniy-ADG** [comment]
requested here: 1425202

**Comment by evgeniy-ADG** [comment]
We have logs. 1425202

**Comment by ameshkov** [comment]
@evgeniy-ADG ?

**Comment by zebrum** [comment]
@ameshkov 
other similar vendor request i have:
app does not work on iPhone 5S (iOS 10.1.1) in Bouygues Telecom LTE mode. There are ads everywhere in safari and apps. It certainly due to my mobile network provider because I compared with an other provider and adguard works nice.

have this log: 
[com.adguard.AdguardPro.tunnel.gz](https://github.com/AdguardTeam/AdguardForiOS/files/616432/com.adguard.AdguardPro.tunnel.gz)

**Comment by vbagirov** [comment]
A small addition to the previous comment:
user ID there is 1454382

Also, according to user, he doesn't have ads in Safari anymore; still true for ads in apps on his iPhone 5S (not on iPhone 7 though).

**Comment by ameshkov** [comment]
Waiting for @Stillness-2 to examine the log files then

**Comment by runeruly** [comment]
Same problem here with iPhone 7 with T-Mobile. On LTE mode, ads are every where  in apps and in other browsers (safari still blocks ads). On WiFi though, it blocks ads very effectively.

**Comment by ameshkov** [comment]
@runeruly what if you switch Adguard off and on again while being on mobile data?

**Comment by runeruly** [comment]
@ameshkov I tried. No success blocking ads. But It worked great before the latest update from yesterday.

**Comment by ameshkov** [comment]
@runeruly weird, the last update was just a hotfix and didn't change anything in DNS-level ad blocking.

Anyway, what we need to check is if DNS requests are going through AG or not. Here's what I suggest: when you're on mobile data, open and enable requests log in Adguard and then do some web surfing. Then check the requests log again. Do you see any DNS requests there?

**Comment by BooBerry** [comment]
This may or may not be of importance, but I heard that T-Mobile recently is forcing a move to IPv6 without any IPv4 fallback apparently.

**Comment by runeruly** [comment]
@ameshkov the DNS requests log is empty when I surf the web with wifi off.

**Comment by runeruly** [comment]
@ameshkov when I check the log with wifi on, the log is filled with various websites. Definitely something wrong with how T-Mobile is handling this.

**Comment by runeruly** [comment]
@BooBerry i checked various forums and I see lot of people having problems with VPN and other things. Is there a way to only use ipv4 instead of v6? I can't find an settings on iPhone. I have always had Android so it was easier to change it on those phones.

**Comment by BooBerry** [comment]
Mmmm, maybe, not sure. It seems T-Mobile made a complete mess from dropping IPv4 support and pushing IPv6.

(Fortunately for me) I don't have T-Mobile service nor an iOS device currently, so I can't test this. I imagine it's not just limited to iOS devices either, however unlike iOS/iDevices Android supports 464XLAT so it's less of if not an issue at all for non-iOS users.

**Comment by ameshkov** [comment]
I guess this is the same issue:
https://forum.adguard.com/index.php?threads/sonos-problem.18425/#post-121140

> Mmmm, maybe, not sure. It seems T-Mobile made a complete mess from dropping IPv4 support and pushing IPv6.

This is not really a good example, but anyway, I am with T-Mobile sim card right now, and Adguard for Android can switch DNS settings just ok.

So I suppose it is possible to fix this issue in iOS version as well.

**Comment by ameshkov** [comment]
Just tested it on my friend's iPhone 6S with t-mobile sim and it works.

Interesting thing is that the guy in that forum thread I've linked above can see some requests in the requests log.

Empty requests log means, that iOS does not actually use the DNS settings Adguard has provided.

@Stillness-2 I suppose we should start with extending Adguard's log. We need to know current network settings before and after turning VPN on. All the network interfaces, gateway addresses, primary/secondary dns, etc.

**Comment by runeruly** [comment]
I an confused by why it suddenly stopped working. I bought the pro app about week ago and i think it was blocking ads on mobile date. But after the recent update, it stopped working suddenly. Recent update didn't change that much though. I uninstalled and reinstalled the app it but still the ads aren't blocked with wifi off. The log request doesn't show anything once the wifi is turned off.

**Comment by ameshkov** [comment]
@runeruly could it be that you've changed anything in VPN profile settings?

**Comment by runeruly** [comment]
I haven't changed anything.

**Comment by ameshkov** [comment]
Just in case, do you use any other VPN app along with AG?

**Comment by runeruly** [comment]
No this app is the only one.

**Comment by ameshkov** [comment]
And what about VPN profiles? Is there any?

**Comment by ameshkov** [comment]
I just thinking of AG's own profile duplicate for instance.

**Comment by runeruly** [comment]
The only VPN porfile is adguard pro

**Comment by ameshkov** [comment]
The only possible flaw I see is that IPv6 configuration is a bit different. We'll fix it in the next beta version. @runeruly will you be able to check it once it's done?

**Comment by runeruly** [comment]
Yes definitely!

**Comment by runeruly** [comment]
@ameshkov how can I try the beta version?

**Comment by ameshkov** [comment]
@runeruly here is an instruction:
https://forum.adguard.com/index.php?threads/adguard-for-ios-beta-test.6344/

We'll comment on this once new beta is ready.

**Comment by lukewrites** [comment]
I'm having the same issue with AdGuard Pro. I use MetroPCS, which is on T-Mobile. Checking my logs, when I switch from WiFi to LTE no requests come through, but there are lots of requests logged when on WiFi. I'd be happy to take part in the beta once this is addressed. Can share logs etc with you too, if needed.

**Comment by ameshkov** [comment]
@Stillness-2 please let me know if you made necessary changes in the latest beta build?

@lukewrites updated beta test instruction:
https://blog.adguard.com/en/adguard-beta-test/

**Comment by wan-an** [comment]
fwiw OpenVPN updated their iOS app recently for NAT64 support

> Changes between 1.1.0 and 1.1.1:
> * updated ovpn3 backend and plugin
> * better support for NAT64
> * workaround for sweet32 vulnerability
> * implementation of relay protocol

**Comment by Stillness-2** [comment]
@ameshkov Not yet, will be done in the next beta.

**Comment by evgeniy-ADG** [comment]
In case you need it, another complaint here: 1498020
> Hi, I use the data connection (3g / 4g / 2g) the VPN is activated as usual but does not block any advertisements in your applications, if I use the wifi it works. I live in Italy, the provider is Tim and this affects all apps.

**Comment by evgeniy-ADG** [comment]
MTS Russia, doesn't block google ads on the mobile connection: 1496878

**Comment by Stillness-2** [comment]
@runeruly can you check last beta?

**Comment by Stillness-2** [comment]
Did anybody check the latest beta?

**Comment by X8716e** [comment]
As for AT&T, prelim tests show Adguard Pro functioning w/ cellular connection. Will report back after more extensive testing.

**Comment by ameshkov** [comment]
> though queries routed through AT&T DNS

Does it happen when you set AG Pro to use custom DNS?
Could it be that AT&T intercept plain DNS requests and respond by themselves?

**Comment by vozersky** [comment]
please re-open if the issue happens again
