### ISSUE TITLE
Adguard causing bad battery drain on iPhone even when idle

### ISSUE THREAD

**Issue by sgreadly** [AdguardTeam/AdguardForiOS#1831]
### Issue Details

- **AdGuard version:** 4.2.2(721)
- **Device model and storage size:** iPhone XS Max  256GB
- **Operating system and version:** iOS 15.0.2 (and 15.0.1)
- **Browser or App:** Safari & Firefox

### Expected Behavior

Adguard not consuming a lot of battery, causing battery drain. 

### Actual Behavior

As of several days ago, Adguard is causing a huge battery drain even when not doing anything. I'd have the phone charged and at the end of the day it's empty. Refer to screenshot for example, overnight it was around 60%, and by morning it's drained. 

I uploaded support logs into ticket 545697 via the app.

### Screenshots

![unnamed-0](https://user-images.githubusercontent.com/1705194/138179453-306bff1f-d570-41b5-902f-01066bd39a31.jpg)
![unnamed-1](https://user-images.githubusercontent.com/1705194/138179460-e6a508ee-f9ec-4a66-9328-6c18b8d57025.jpg)
![unnamed-2](https://user-images.githubusercontent.com/1705194/138179464-fd4190a8-7810-445b-a6f1-aee00ccbbd1d.jpg)
![unnamed-3](https://user-images.githubusercontent.com/1705194/138179466-cc45321b-9a58-4a8f-a69e-c3312e4d6931.jpg)
![unnamed-4](https://user-images.githubusercontent.com/1705194/138179467-fe233854-fe2f-4abf-a1dd-93548f7860b9.jpg)

### Additional Information

Unsure to what started this, but it's still ongoing even today. I tried switching off/on the iPhone, and a hard reboot too, didn't help.

**Comment by loca-lhost** [comment]
Experiencing same. Overnight and battery is drained sometimes going off.

**Comment by AleksandrShulgin** [comment]
If it happens again. Do the following:
1. Go to **Activity** tab
2. Click on the **three dots** to reset the log than click **Yes**
3. Leave the device for a while (e.g. night)
4. Check **Activity** tab

There may be blocked records. This means that some app is constantly trying to connect to some DNS, and AdGuard is blocking it. Therefore, the battery power can be drain in the background.

**Comment by AleksandrShulgin** [comment]
I'm closing the issue.
You can reopen this if necessary.

**Comment by ViRb3** [comment]
Have been experiencing the exact same issue for the past few weeks. Not sure when it started, possibly after 15.1 update? My battery drain graph looks identical and my phone goes from 80% to 10% overnight. However, I'm not convinced it's actually AdGuard to blame, just that it's the only app running at the time. I am experimenting more now, will come back if I find anything conclusive.

**Comment by MirodePiro** [comment]
I have a similar problem. Adguard uses a lot of battery in the background. Now i tried to switch off DNS and the battery drain is still pretty high. I tried resetting the log but it did not help unfortunately. I am on IOS 15.1
![1341253F-A70D-4A3C-B794-396A4F5A04ED](https://user-images.githubusercontent.com/88776547/146642147-9a2d102a-a908-43de-aec3-4cbdc0d272b2.png)
![634C5914-25D9-46F1-9F28-F50AC10B0EDA](https://user-images.githubusercontent.com/88776547/146642153-4cb565dc-571b-4628-9920-93ecea3023b5.png)

**Comment by hal0003** [comment]
Ich habe exakt das gleiche Problem.
Über Nacht verliert das iPhone 10% Akku pro Stunde. (auch am Tag, auch wenn es nicht benutzt wird und im standby ist)
Auch bei mir wird angezeigt, das Adguard im Hintergund läuft, obwohl ich die **Hintergrundaktivität deaktiviert** habe.
Im Aktivitätsprotokoll ist nichts Auffälliges zu sehen.

iOS 15.3
(auch schon bei iOS 15.2)
Adguard 4.3.2 (935)
iPhone 12 pro **und** iPhone 11

Das Problem ist bei mir gefühlt mit Adguard 4.3.1 aufgetreten. Davor lief jahrelan alles sehr gut.
Ich würde gerne auf Version 4.2.2 downgraden. Leider geht das ja nicht.

**translated with deepl**
I have exactly the same problem.
Overnight, the iPhone loses 10% battery per hour. (even during the day, even when it is not in use and in standby).
I also have Adguard running in the background, even though I have disabled background activity.
There is nothing noticeable in the activity log.

iOS 15.3
(also with iOS 15.2)
Adguard 4.3.2 (935)
iPhone 12 pro **and** iPhone 11

The problem occurred with Adguard 4.3.1. Before that, everything ran very well for years.
I would like to downgrade to version 4.2.2. Unfortunately, this is not possible.
