### ISSUE TITLE
Filtering is mostly non-functional when using System DNS on iOS/iPadOS 15.1

### ISSUE THREAD

**Issue by verdi1987** [AdguardTeam/AdguardForiOS#1834]
Edit: I previously stated Native DNS when I meant System DNS.

### Issue Details

On iOS/iPadOS 15.1, when selecting DNS server “System DNS,” filtering in both Safari and apps mostly does not work. Intermittently, it does work. iCloud Private Relay is disabled.

When selecting AdGuard DNS server, filtering works as expected in Safari and apps. (Other DNS options were not tested.)

I am almost certain System DNS filtering did work on iOS/iPadOS 15.0.

Things I tried:
-Toggling master protection off and on
-Toggling individual filters off and on
-Force quitting apps
-Reinstalling VPN
-Restarting devices

- **AdGuard version:**
4.2.2
- **Device model and storage**
iPhone 12 Pro 256 GB; iPad Pro 12.9 5th Gen. 256 GB
- **Operating system and version:**
iOS/iPadOS 15.1
- **Browser or App:**
Safari and apps

### Expected Behavior

When selecting System DNS, Safari and apps are filtered.

### Actual Behavior

When selecting Native DNS, Safari and apps are not filtered consistently. AdGuard DNS does filter as expected.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by curiosityseeker** [comment]
> When selecting Native DNS, Safari and apps are not filtered consistently. AdGuard DNS does filter as expected.

I'm not sure that I follow. In AdGuard there are Safari filters and there is DNS filtering. Safari filters are only applied to Safari, and DNS filtering is applied to DNS requests from the system (iOS) and apps. Hence, it's a contradiction in terms if you write: "apps are not filtered consistently. AdGuard DNS does filter as expected"

DNS filtering only works if you 
- either select a **filtering** DNS server  (like AdGuard DNS)
- or (if using the system DNS) you add filterlists to AdGuard (DNS protection -> DNS filtering-> DNS filters).

**Comment by verdi1987** [comment]
Thank you for the clarification. I will close it.
