### ISSUE TITLE
Remove app banners + login popups

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#1835]
With iOS 15, AdGuard should now be able to remove the annoying "please use our app" banners as well as login popups from pages like Reddit, Twitter, Facebook, Linkedin & Instagram:
![IMG_0121](https://user-images.githubusercontent.com/83946731/139286400-0f36492d-d3d1-42a3-a0d0-4c05963fe643.PNG)

**Comment by AleksandrShulgin** [comment]
@iDjay Hi
Sorry for the late reply! On iOS 15, this will be possible in the next version of AdGuard

**Comment by iDjay** [comment]
@AleksandrShulgin any news here? :)

**Comment by AleksandrShulgin** [comment]
@iDjay 
The new version of AdGuard for iOS is already in beta testing stage
