### ISSUE TITLE
Adguard will not work on cellular data connection anymroe

### ISSUE THREAD

**Issue by sloanmomoney** [AdguardTeam/AdguardForiOS#1838]
have been using adguard on my data network for weeks. not it says it cannot be used is that a problem on their side or adguard?
![25324512-0584-45CB-830A-0A6158238570](https://user-images.githubusercontent.com/93847422/140628024-9b527be5-e937-46b4-a037-6c3f1fb040f2.png)

**Comment by sloanmomoney** [comment]
i have att btw

**Comment by sloanmomoney** [comment]
ok weird. if i turn off connect on demand it works now? never had fo be that way before is it a new ios update?

**Comment by Aydinv13** [comment]
Can you specify what version of AdGuard&iOS you have this problem with?

**Comment by sloanmomoney** [comment]
latest store version of adguard and ios 15.1

**Comment by Aydinv13** [comment]
Thanks for bug report. Expect it to be fixed in one of the upcoming release builds

**Comment by Aydinv13** [comment]
@sloanmomoney by the way, could you please check that Filter Mobile data is ON in `Settings-> DNS protection-> Network settings-> Filter Mobile data`?

**Comment by sloanmomoney** [comment]
that fixed it. i dont know how ads were still being blocked if that toggle was off?

**Comment by Aydinv13** [comment]
It was most likely due to Safari protection. I'm closing the for now. Reopen if needed, please
