### ISSUE TITLE
Inconsistent behavior between 1.1.0 and 1.0.8

### ISSUE THREAD

**Issue by SlowMemory** [AdguardTeam/AdguardForiOS#184]
A user reported that he gets different filtering results in Adguard for iOS 1.1.0 and 1.0.8.

The user gets adblock detection in `www.yuncomics.com` with 1.1.0 version,
but as soon as the user downgrades the version to 1.0.8 on a rooted iPad he/she doesn't get a detection.

The user have English, Spyware, Social Media, Mobile ads, Safari filter and List-KR enabled. Safari filter contains a rule @@||yuncomics.com^$generichide which should take care of the detection.

I am posting it here, because it could be an issue of Adguard itself, not of filter lists. Can somebody reproduce it? Let me know if you need more information.

**Comment by ameshkov** [comment]
In fact I can reproduce it with Safari extension as well.

It worked in 1.0.8 because $generichide worked just as $elemhide there.
