### ISSUE TITLE
why is the “I don’t care about cookies” list from 2018? 

### ISSUE THREAD

**Issue by andrewmoroz** [AdguardTeam/AdguardForiOS#1840]
![A2619CF8-4E7D-42A5-A478-4093F4685DFB](https://user-images.githubusercontent.com/36525603/141859551-e32974c1-99af-4d9a-9634-837c6622da9d.png)

why is the “I don’t care about cookies” list from 2018?

**Comment by AleksandrShulgin** [comment]
@andrewmoroz Hi
Try enabling it and updating the filters manually.

**Comment by andrewmoroz** [comment]
Yeah I had tried that, but it didn’t work. I ended up uninstalling and reinstalling—now it works. I hadn’t used the app in years, so maybe that’s related.
