### ISSUE TITLE
Twitch 

### ISSUE THREAD

**Issue by JmStyx** [AdguardTeam/AdguardForiOS#1848]
Any solutions for twitch ads on iOS?

**Comment by AleksandrShulgin** [comment]
@JmStyx Hi,
What kind of ads do you have in mind?
Web app or native?

**Comment by JmStyx** [comment]
Ads that play in the beginning and mid roll ads. Web apps

**Comment by AleksandrShulgin** [comment]
@JmStyx 
We are working on a solution to this problem and it'll be available in one of the next versions.

**Comment by bingoxo** [comment]
> @JmStyx We are working on a solution to this problem and it'll be available in one of the next versions.

you might want to find another soluttion because ads are still there (web)
