### ISSUE TITLE
Yandex.Navigator - ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForiOS#185]
id 1428019, 1428890, 1430075

**Description**: Реклама в приложении
https://appsto.re/ru/Z7esC.i

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19389325/4a3bb578-922c-11e6-884f-a30725d19769.png)
![image](https://cloud.githubusercontent.com/assets/18548949/19416638/44babdba-939e-11e6-9980-805b0ef276fc.png)
</details>

**Adguard version**: 1.1.1.23

**Filters list**:
<details>
Optimazed enabled: NO
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.97.23 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.12 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.49 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.24 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.40.97 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.29 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.20 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.51 Enabled=YES
ID=101 Name="EasyList" Version=1.0.63.60 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.67.4 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.63.60 Enabled=YES
ID=114 Name="ROList" Version=1.0.0.83 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.67.17 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.27 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.67.18 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.64.3 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.63.73 Enabled=YES
</details>

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by ameshkov** [comment]
Ad is loaded from yandex own domain, we can't block it without breaking the whole app.
