### ISSUE TITLE
domains dont appear in allow only and take a while to switch from the allowed only back to all requests in log section

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardForiOS#1854]
https://user-images.githubusercontent.com/71462072/145769242-8547b7ba-e7b2-47dd-a64c-e937be1a6762.MOV

also been having app crashes but i hit submit crash report when i get them

**Comment by AleksandrShulgin** [comment]
@jordanelliott23 Hi
Please specify which version you are using.

**Comment by AleksandrShulgin** [comment]
We had the similar problem in v.2.2.
This is now fixed, so i'm closing this issue.
if you have this problem again, reopen this task.

**Comment by jordanelliott23** [comment]
still having same problem in latest beta.
