### ISSUE TITLE
custom dns block list is gone from app

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardForiOS#1856]
hello. i just noticed the custom dns filter blocklist has disappeared from my app i am on latest beta version

**Comment by jordanelliott23** [comment]
but my custom dns rules are still being blocked. odd.🤔

**Comment by jordanelliott23** [comment]
it might have to do with new ios beta? because i think i remember it being there a couple days ago

**Comment by Quorum75** [comment]
Nope still present in the Beta version. The way to reach it has been changed though.

**Comment by AleksandrShulgin** [comment]
@jordanelliott23 Hi
Please specify what do you mean?
Do you have DNS rules  disappeared from the blocklist or something else?

**Comment by jordanelliott23** [comment]
where is the custom dns block list? @Quorum75

**Comment by jordanelliott23** [comment]
> @jordanelliott23 Hi
> Please specify what do you mean?
> Do you have DNS rules disappeared from the blocklist or something else?

how do you get to that section

**Comment by jordanelliott23** [comment]
i cant get to the dns section at all
