### ISSUE TITLE
Safari extension doesn't work as expected on iPad; whatever I do in the extension UI, it just opens a new empty tab

### ISSUE THREAD

**Issue by ArttuLai** [AdguardTeam/AdguardForiOS#1860]
### Issue Details

- **AdGuard version:**
  - 4.3.0 (911) TestFlight beta
- **Device model and storage size:**
  - iPad Pro 12.9" 2020 (or something?) 64GB
- **Operating system and version:**
  - iPadOS 15.3 beta

### Expected Behavior

I can use the Safari extension to disable/enable ad blocking on the website I’m on, or use the element blocker, via the extension UI that's accessed via Safari toolbar.

### Actual Behavior

After I press the toggle to disable blocking on a website, or use the element blocker and hit 'Block,' instead of adding this new rule to AdGuard it just opens a new empty tab in Safari. Only way to add sites to allowlist or block elements on the iPad is to open the AdGuard app and input the rules manually. 100% reproducible, and there's a video below.

### Screenshots

<details><summary>Screen recording:</summary>

https://user-images.githubusercontent.com/42007282/147087069-34cf5e39-235c-4a94-b787-1e27ad396b02.mov

</details>

### Additional Information

The extension UI works fine and responds normally on iPhone, this issue affects iPad only.

**Comment by AleksandrShulgin** [comment]
@ArttuLai Hi
Could you please collect the logs (Settings tab --> Support --> Export log) and send it to devteam@adguard.com

**Comment by ArttuLai** [comment]
@AleksandrShulgin sent

**Comment by AleksandrShulgin** [comment]
@ArttuLai 
We cannot reproduce this problem on either iPad or iPhone.
Please update to v.4.3.0 (915) and try it again.

**Comment by AleksandrShulgin** [comment]
@ArttuLai 
This problem has nothing to do with AdGuard.
Try changing the orientation of the screen (flip).

**Comment by ArttuLai** [comment]
@AleksandrShulgin Yes, it apparently works when I flip the screen to portrait orientation. It's a Safari bug it seems. I can confirm that for example 1Password has similar behavior when I use an action via the extension UI that launches the full app; it only works in portrait.
