### ISSUE TITLE
Please update zh-TW in v4.3.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1863]
Some obviously wrong wordings were made by Dasha.
I fixed them and others.
Please update zh-TW.

https://crowdin.com/translate/adguard-applications/17552/en-zhtw#3954371
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/AVORNDd.png)
</details><br/>

https://crowdin.com/translate/adguard-applications/17552/en-zhtw#3954419
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ouCtuCj.png)
</details><br/>

**Comment by artemiv4nov** [comment]
@lancelot-moon Hi!
Thanks, will be fixed in the v4.3.1 version
