### ISSUE TITLE
where is dns blocklist

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardForiOS#1864]
just updated to newest version, cant find dns blocklist section?

**Comment by AleksandrShulgin** [comment]
@jordanelliott23 Hi
In order for the DNS section of the blocklist to be visible, you need to enable `Advanced mode` in the Settings.

**Comment by hitechtalk69** [comment]
Could you do a screenrecord to show us where it is located . I have advanced enabled also and dot see it

**Comment by AleksandrShulgin** [comment]
@jordanelliott23 @hitechtalk69 
I am attaching a video

https://user-images.githubusercontent.com/88375929/147446505-25fd3bed-7f1c-436b-a498-4228db8311a0.MP4

**Comment by hitechtalk69** [comment]
i am so sorry. i found it. usually am good with technology. i forgot to close this even my bad

**Comment by hitechtalk69** [comment]
i dont see a close button on this issus you can go ahead and close it. thankyou so much for replying tho.
