### ISSUE TITLE
"New AdGuard features in iOS 15" prompt 

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForiOS#1869]
### Issue Details

- **AdGuard version:**
  - 4.3.0(915)
- **Device model:**
  - iPhone SE (2020)
- **Operating system and version:**
  - 15.2

### Expected Behaviour
"New AdGuard features in iOS 15" prompt is dismissed when you tap 'Continue', see the instructions and close.

### Actual Behaviour
"New AdGuard features in iOS 15" prompt appears on every launch (quit app and relaunch, or device restart), unless you swipe it away and ignore the Continue button, then it disappears permanently.

**Comment by AleksandrShulgin** [comment]
@planet0 Hi
Thanks for your issue. It will be fixed in the next version.
