### ISSUE TITLE
Add 'AdGuard URL Tracking filter' to the Privacy filter list

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForiOS#1870]
### Problem Description
There is no AdGuard URL Tracking filter in the Privacy filter list

### Proposed Solution
Add the AdGuard URL Tracking filter in the Privacy filter list

### Alternatives Considered
Allow the iOS app to refresh the list of filters dynamically

**Comment by ameshkov** [comment]
It won't work anyway:( 

Even with the web extension Safari is still limited in some ways.
