### ISSUE TITLE
Add Anti-tracking features

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForiOS#1873]
Could you please add Anti-tracking features to the iOS application? Since with the advent of Web Extension API support in iOS 15, you have a lot more options.

**Comment by AleksandrShulgin** [comment]
@rakleed Hi
Thanks for your feature request, but it's not possible right now.

**Comment by rakleed** [comment]
@AleksandrShulgin even with the advent of WebExtensions API support for extensions in Safari?

**Comment by AleksandrShulgin** [comment]
@rakleed 
Unfortunately yes, even with the web extension Safari is still limited in some ways.
