### ISSUE TITLE
The main screen interface in version 4.3

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardForiOS#1875]
После обновления Adguard для IOS до версии 4.3 сразу заметил на главном экране 2 бага - 1) Кнопка ручного обновления фильтров стала слишком маленькая. Раньше точно была больше, заметнее и удобнее. Может стоит вернуть прежний размер? 2) Линия, отображающая количество заблокированных DNS-запросов стала какая-то размытая, нечеткая. Зачем к ней был добавлен блюр, не понятно. Визуально выглядит не очень.

![IMG_1745](https://user-images.githubusercontent.com/34383288/147383840-6785254a-6776-42ab-aec7-6231914311f9.PNG)

**Comment by AleksandrShulgin** [comment]
@Vitalik93
Визуально график не претерпел никах изменений с версии 4.2.
Кнопка обновления имела неправильную форму, поэтому ее перерабатывали. Рассмотрим ваще предложение по ее увеличению.

Спасибо.

**Comment by Vitalik93** [comment]
> Кнопка обновления имела неправильную форму, поэтому ее перерабатывали. Рассмотрим ваше предложение по ее увеличению.

Странно, вроде нормальная круглая была.

**Comment by Vitalik93** [comment]
> Рассмотрим ваше предложение по ее увеличению.

Надеюсь предложение в силе? Вообще было бы неплохо и Надпись "Adguard" там же сверху увеличить немного. Всё таки логотип...

![IMG_E1921](https://user-images.githubusercontent.com/34383288/159954568-18ce7f15-d4dd-4923-98c7-ca86799101f7.JPG)
