### ISSUE TITLE
Name of setting

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardForiOS#1876]
В информации о релизе версии 4.3 для IOS написано, что появилась новая настройка, позволяющая выбрать интервал обновления фильтров. Только почему-то в приложении эта настройка называется "интервал обновления приложения". Может все таки стоит переименовать на "интервал обновления фильтров", если уж данная настройка отвечает именно за это? Тем более учитывая что обновления приложения происходит через AppStore и данная настройка точно никак на это не влияет. 

![IMG_1746](https://user-images.githubusercontent.com/34383288/147383936-abb50f94-058f-402f-89bb-24a1f63dba23.PNG)
![IMG_1747](https://user-images.githubusercontent.com/34383288/147383938-68faff22-a792-4838-9d94-a4b0742505c1.PNG)

**Comment by AleksandrShulgin** [comment]
@Vitalik93 
Такое название связано с тем, что происходит не только обновление фильтров, но и иных процессов приложения.
Поэтому не совсем уместно привязываться только в обновлению фильтров.
