### ISSUE TITLE
Moving DNS and Safari protection

### ISSUE THREAD

**Issue by Vitalik93** [AdguardTeam/AdguardForiOS#1877]
В версии 4.3 настройки защиты Safari и DNS-защиты были перенесены из раздела Настройки в раздел Защита. Не совсем логичное решение по моему. Поначалу подумал, что эти настройки вообще выпилили, только тыкнув на соответствующие кнопки в разделе Защита понял, что они там. Может всё таки настройкам программы место в настройках, как было раньше?

**Comment by AleksandrShulgin** [comment]
@Vitalik93 
Спасибо за ваше предложение, но такая реализация нам показалось наиболее удобной и логичной.

**Comment by Vitalik93** [comment]
>... наиболее удобной и логичной.

Столько времени была в настройках и тут поменяли? По-моему не удобно и не логично наоборот.
