### ISSUE TITLE
Safari Protection toggle button does not work

### ISSUE THREAD

**Issue by proce55ing** [AdguardTeam/AdguardForiOS#1878]
### Issue Details

AdGuard iOS 4.3.0
iPad OS 15.2
iPad Pro 12.9" 4th Gen (MXF92B/A)
Safari

New Safari Protection toggle does not work.

### Expected Behavior
Click the AdGuard icon in the safari address bar.

Clicking the "Safari Protection" toggle in the extension popup should disable blocking for the current website.

### Actual Behavior

The browser opens a new tab on the start page and does not disable protection.

**Comment by zeezeepiggy** [comment]
It works for me. But i think the way it works is not what you are expecting.

what happens is, when you turn off the Safari Toggle, it will open a new tab and will ask you to open the AdGuard App. Once open, the site will then added to your Allowlist. It’s like its confirming if you want to add the site in your allowlist.

it could be a limitation or it could be better in the next version.

**Comment by proce55ing** [comment]
I don't receive any form of popup or notification once the new tab is open. Opening the app manually does not display anything about an allow list.

Attempted both with the Adguard app closed and open.

Reinstalled the app and rebooted with no change.

**Comment by proce55ing** [comment]
Actually just managed to trigger it there. The start page takes up the entire screen until I manually navigate another app and then back again.

The start page then appears as a popup under the address bar that can be closed and the Adguard notification is visible underneath it.

This is likely an iOS bug at this point so can probably be closed.

**Comment by proce55ing** [comment]
Further investigation the behaviour only occurs when the Apple magic keyboard is attached.
