### ISSUE TITLE
[AdGuard PRO] Where is my long waited update?

### ISSUE THREAD

**Issue by dnmTX** [AdguardTeam/AdguardForiOS#1879]
@AdguardTeam so....the FREE version got update but not the PRO one. Way to go guys....way to go !!!!!!!!!
😞

**Comment by zeezeepiggy** [comment]
The PRO version will be updated in the next coming days before New Year. It was mentioned in their twitter and reddit account.

i have a feeling that Apple’s approval in the PRO version got delayed while the Premium version gets approved first. you know how apples approval work. It works in mysterious and delayed ways. I think apple also mentioned that approval process will be delayed this holiday season.

**Comment by dnmTX** [comment]
Thank you @zeezeepiggy for the encouraging news 👍  I gues nothing can be done but wait. We all know Apple 😉 
**С Рождеством и счастливых праздников на всей команде!** 🎄
