### ISSUE TITLE
yandex.metro - ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForiOS#188]
id 1428890, 1430075
**Description**: Реклама в приложении
https://itunes.apple.com/ru/app/yandex.metro/id392589075?l=en&mt=8

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19416660/38b0bafa-939f-11e6-8c70-36e6f0b2db79.png)

</details>

**Adguard version**: 1.1.1.23

**Filters list**:
<details>
Optimazed enabled: NO
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.97.26 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.12 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.50 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.25 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.40.99 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.29 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.21 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.51 Enabled=YES
ID=101 Name="EasyList" Version=1.0.63.61 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.67.6 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.63.61 Enabled=YES
ID=114 Name="ROList" Version=1.0.0.83 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.67.19 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.28 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.67.20 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.64.5 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.63.75 Enabled=YES
</details>

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by ameshkov** [comment]
Same as here:
https://github.com/AdguardTeam/AdguardForiOS/issues/185
