### ISSUE TITLE
Allow only section is broke in dns filter section

### ISSUE THREAD

**Issue by hitechtalk69** [AdguardTeam/AdguardForiOS#1884]
hi. i am on 4.3.0 when i go to filter dns activity by allowed only nothing appears in there.

**Comment by AleksandrShulgin** [comment]
@hitechtalk69 Hi
The problem isn't reproducible.
Please describe the steps to reproduce or attach a screen recording

**Comment by hitechtalk69** [comment]
https://user-images.githubusercontent.com/96637039/148799535-bacb7118-e291-4bef-ab9c-9d68d4570c13.MOV

**Comment by hitechtalk69** [comment]
im not on the latest beta. is 4.3.1 the latest version in general?

**Comment by AleksandrShulgin** [comment]
@hitechtalk69 
> im not on the latest beta. is 4.3.1 the latest version in general?

Yes, it is

It looks like you just don't have any allowed records.
In this case, this is normal behavior.

**Comment by hitechtalk69** [comment]
> @hitechtalk69
> 
> > im not on the latest beta. is 4.3.1 the latest version in general?
> 
> Yes, it is
> 
> It looks like you just don't have any allowed records. In this case, this is normal behavior.

it actually isnt normal.

**Comment by AleksandrShulgin** [comment]
@hitechtalk69 
1. Add to the DNS allowlist `example.org`.
2. Go to `example.org` in Safari.
3. Open Activity tab and select `allowed only`

There you should see these allowed records.

**Comment by hitechtalk69** [comment]
ok that worked but it should also show domains that arent being blocked not domains that are whitelisted thats why there is an allowed section and a blocked section... @AleksandrShulgin

**Comment by AleksandrShulgin** [comment]
@hitechtalk69 
Not really, the "Allowed only" section contains only records with the "Allowed" status. It makes no sense to output records with the status "Processed" or "Encrypted" there.
