### ISSUE TITLE
Very long lag when refreshing dns activity log

### ISSUE THREAD

**Issue by hitechtalk69** [AdguardTeam/AdguardForiOS#1887]
hi i am on 4.3.0 i can do a screen recording if need be to show issue

**Comment by AleksandrShulgin** [comment]
@hitechtalk69 Hi
Please attach a screen recording.

**Comment by hitechtalk69** [comment]
https://user-images.githubusercontent.com/96637039/148798423-b26761ca-a563-45b2-b232-b89351ab7550.MOV

**Comment by royerlraph79** [comment]
Same for me. You guys fucked up with this version.

**Comment by hitechtalk69** [comment]
> Same for me. You guys fucked up with this version.

you can say that again LOL!!

**Comment by hitechtalk69** [comment]
i dont think adguard owns themself anymore lmao

**Comment by hitechtalk69** [comment]
last version was perfect didnt have any of these bugs. the refacfored code is a jumbled mess

**Comment by royerlraph79** [comment]
> last version was perfect didnt have any of these bugs. the refacfored code is a jumbled mess

Yep. Last version was practically flawless and they fucked it up by trying to repair something that isn’t broken.

**Comment by ameshkov** [comment]
This issue must've been normalized in the latest beta version (which will very soon become stable).

Please reopen it if it occurs for you (I hope not:))
