### ISSUE TITLE
new adguard feature message pops up upon fresh open everytime 4.3.0

### ISSUE THREAD

**Issue by hitechtalk69** [AdguardTeam/AdguardForiOS#1888]
whenever i open the app on fresh open (app not open in app drawer) it gives me the new features message for advanced protection even tho i have that enabled. so i have to hit continue and then it brings me to advanced protection screen  then i have to hit back button

**Comment by AleksandrShulgin** [comment]
@hitechtalk69 Hi
Please update to 4.3.1. it should be fixed.
