### ISSUE TITLE
Very small updating message

### ISSUE THREAD

**Issue by DoctorLizardo** [AdguardTeam/AdguardForiOS#1889]
I’m on a iPhone 12 Pro Max (iOS 15.2) and just noticed the tiny updating message at the bottom of the screen. My opinion is that it would look better if it was a little bigger. I’ve attached a screenshot.

*love the app by the way.

![D370CA5D-F530-4478-857F-6A7619AACF1A](https://user-images.githubusercontent.com/18344741/147777725-ab9111a1-1f42-4f1b-b260-c3fe7a58ba31.jpeg)

**Comment by AleksandrShulgin** [comment]
@DoctorLizardo Hi
In the next version this will be reworked. We will consider your offer.
