### ISSUE TITLE
Adguard crashes when a huge file is imported

### ISSUE THREAD

**Issue by zhuochenming** [AdguardTeam/AdguardForiOS#189]
when i import too long filter rule，it cause crack，i think it is because memory waring, so i think you can add the function，it can give a better UX, thank you

**Comment by ameshkov** [comment]
Thank you for reporting it!

@gshumihin could you please test it?

**Comment by gshumihin** [comment]
@zhuochenming can you give an example rule that crashes adguard?

**Comment by gshumihin** [comment]
I tried rule with more than 50 characters and it was added normally.

**Comment by gshumihin** [comment]
Tried to add rule that included 1,100,000 chars. Worked fine. Adding 1,100,000 words broke Adguard.

**Comment by worldsdream** [comment]
Maybe this?

https://github.com/AdguardTeam/AdguardForiOS/issues/193

**Comment by mickkkkk** [comment]
你好，请问adguard贴吧问题您解决了吗？

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardForiOS/issues/193
