### ISSUE TITLE
DNS Not Working..

### ISSUE THREAD

**Issue by eldelamai** [AdguardTeam/AdguardForiOS#1894]
### Issue Details

- **AdGuard version:**

  AdGuard for iOS v4.3.1

- **Device model and storage size:**
  
  iPhone 11 Pro Max 64gb

- **Operating system and version:**
  
  iOS 15.2

### Expected Behavior

All worked well, able to upload blocklists, traffic being encrypted, DNS and Safari protection working as expected. Quad9 DNS server selected, all is well. 

### Actual Behavior

DNS randomly disconnects and refuses to connect back. My stats went to 0, and I was instructed to delete app and reinstall. When redownloaded, and when I try to turn it on, my phone settings say “reconnecting” and issue is not resolved. I noticed that when reducing my uploaded blocklist from 6 to 2, the app ‘worked’ for a longer period of time (a few more hours). Iva restarted my phone, deleted app, turned DNS settings on and off, and everything else I could think of. Nothing worked. 

### Screenshots

![72661DE7-F570-4490-AF5B-D356C38E578F](https://user-images.githubusercontent.com/96963449/147863918-1df87da1-698b-478c-b385-56145d4e4506.jpeg)

(Screenshot above) functioning as expected before randomly turning off. Both DNS and Safari Protection turned on  

![1F397693-6B3C-4A0F-A83D-9F5E5E5BA6A3](https://user-images.githubusercontent.com/96963449/147863935-9d619d06-df43-40dc-aa17-979c6618e98c.jpeg)

(Screenshot above) Phone settings switching from ‘connecting’ to ‘disconnecting’ on a loop

![880D7B29-C58D-42D4-B9FF-445B96E99126](https://user-images.githubusercontent.com/96963449/147863958-f09556d6-a6d0-49de-a36a-ce5a85d160b6.jpeg)

(Screenshot above) As mentioned, phone settings switched from ‘connecting’ to ‘disconnecting’, before eventually manually being turned off 

![495D8542-29A9-4DD8-AD7F-956D321FE62A](https://user-images.githubusercontent.com/96963449/147863979-b3fb6401-c1af-42b2-bb80-00cdb42838c4.jpeg)

(Screenshot above) Here it is manually turned off. If I don’t, it loops forever and I can’t use my phone (since connection is being switched on and off)

![C8C6BEF0-87D7-4D0F-9029-6D119D13540E](https://user-images.githubusercontent.com/96963449/147864012-eb6c43c6-ffb5-4270-8c82-2d67fe8f78b8.jpeg)

(Screenshot above) Throughout the whole thing, the AdGuard app shows DNS on. 

### Additional Information

I’ve tried switching DNS on and off both within the AdGuard app and in my phones settings, and neither have worked. 
Might I add: submitting this was very hard, I had to turn off wifi connection completely. 

EDIT: nothing has changed, but I noticed a pattern. 

When DNS is turned off on the AdGuard app, but turned on in my phone settings, it seems to work for the longest amount of time (as compared to other methods that also just result in the inevitable loop of ‘connecting and disconnecting’). When DNS is on in app, and off in phone settings, it is actually off (obviously). Trying to be as descriptive as possible, hope this edit helps. Will be updating if anything new arises.

**Comment by AleksandrShulgin** [comment]
@eldelamai Hi
Could you please send the logs to our email: devteam@adguard.com

**Comment by AleksandrShulgin** [comment]
I'm closing the task because I didn't get an answer
Reopen the task if necessary
