### ISSUE TITLE
Ability to import export app configuration settings

### ISSUE THREAD

**Issue by rodaimi** [AdguardTeam/AdguardForiOS#1896]
### Problem Description

When the adguard app is removed and reinstalled or installed on a new device, you must manually reconfigure the app to your preferred configuration each time you install the app.

### Proposed Solution

If users were able to export their current configuration and import it into a new instance of AdGuard, it would make installing AdGuard on new devices easier.

### Alternatives Considered

Alternatively, adguard could allow you to import dns blocklist, allowlist, Safari user rules, and app configuration in one big zip file.

**Comment by AleksandrShulgin** [comment]
@rodaimi Hi
Thanks for your feature request. We have such a task on version 4.4.
