### ISSUE TITLE
Advanced rules do not work if rule contains `www.` at the beginning

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardForiOS#1897]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v4.3.1(919)
- **Device model and storage size:**
  - iPad mini
- **Operating system and version:**
  -  iOS15.2
- **Browser or App:**
  -  Safari

### Steps to reproduce
1. Add this rule to user rules:
```
www.example.org#%#alert(1);
```
2. Open Safari and navigate to - https://www.example.org/

### Expected Behavior
An alert should be displayed.

### Actual Behavior
Alert is not displayed.
It works fine if I add:
```
example.org#%#alert(1);
```

**Comment by iOSjNaGeR** [comment]
Yeah thanks for the heads up Adam!!!
