### ISSUE TITLE
Filters autoupdate doesn't work as intended

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForiOS#190]
Filters are not always update in the due time, both for WiFi and cellular data. In some cases filters do not update for 2 weeks:
https://forum.adguard.com/index.php?threads/11672/#post-105792

**Comment by onega** [comment]
I start the issue #NYG-855-99276 on AdGuard HelpDesk, giving the necessary logs. Now I'm waiting for a response from the developers.

**Comment by ameshkov** [comment]
We'll take a deeper look during next weeks.

**Comment by Stillness-2** [comment]
#200

**Comment by Stillness-2** [comment]
We need many testings...
