### ISSUE TITLE
Certain user filters never work on delayed dom elements 

### ISSUE THREAD

**Issue by mqudsi** [AdguardTeam/AdguardForiOS#1900]
### Issue Details

There are certain “simple” elements that are inserted into a website post-load via JS that AdGuard has never been able to hide (element picker zaps them but on reload the element is visible even after the rule is saved and filters reloaded).

Chief among them is Reddit’s “see this in the app” banner, which should correspond simply to the following CSS rule:

    reddit.com##div.XPromoPill__container
    
But the rule never seems to take. 

- **AdGuard version:**
  - 4.2.2 
- **Device model and storage size:**
  - iPhone 11 
- **Operating system and version:**
  - iOS 15 
- **Browser or App:**
  - iOS 15 Safari 

### Expected Behavior

The element should be blocked per the rule. 

### Actual Behavior

The element is never blocked. 

### Screenshots

Expand to see:

<details><summary>Screenshot:</summary>

![8BF62419-9234-4694-8409-DCB0BAA51FC5](https://user-images.githubusercontent.com/606923/148420725-ede0dd83-e5c8-4019-a446-ea0b4b127117.png)

</details>

**Comment by AleksandrShulgin** [comment]
@mqudsi Hi 
Please update to version 4.3.1. This is made possible thanks to Advanced protection.
