### ISSUE TITLE
Constant crashing on reddit.com

### ISSUE THREAD

**Issue by jimmysofat6864** [AdguardTeam/AdguardForiOS#1903]
### Issue Details

Reddit seems to crash on any article with AdGuard enabled. To reproduce, just open a reddit article with some filters and eventually the page will crash and you will get the message I get. If it doesn't happen, just refresh the page a few times or load comments or look at some articles and eventually, it will crash and display the message I got. If I enable all the filters in annoyances or privacy, it crashes much faster sometimes without even reloading. Oddly this doesn't seem to be an issue with my iPhone X on IOS 15 just on my 7 Plus on 14.8 and my iPhone 6 Plus on 12.5.5.

- **AdGuard version:**
  - 4.3.1
- **Device model and storage size:**
  - iPhone 7 Plus & iPhone 6 Plus
- **Operating system and version:**
  - 14.8 & 12.5.5
- **Browser or App:**
  - Safari

### Expected Behavior

Reddit works just fine

### Actual Behavior

Reddit constantly crashes 

### Screenshots

<details><summary>Screen Recording:</summary>

https://user-images.githubusercontent.com/69532417/148837847-fee22b37-3064-45a8-aeac-8ed43521ba8b.MP4

</details>

### Additional Information

Might be a memory issue or something. 

Referred from this issue 

https://github.com/AdguardTeam/AdguardFilters/issues/101155

**Comment by AleksandrShulgin** [comment]
@jimmysofat6864 
This problem is not related to AdGuard, it is on the Safari side.
Try to fix it similarly as described here for Mac: https://browserhow.com/how-to-fix-safari-mac-problem-repeatedly-occurred-error/

**Comment by jimmysofat6864** [comment]
> @jimmysofat6864 This problem is not related to AdGuard, it is on the Safari side. Try to fix it similarly as described here for Mac: https://browserhow.com/how-to-fix-safari-mac-problem-repeatedly-occurred-error/

@AleksandrShulgin 

I already tried everything on that site and it doesn't work. The only solution for me is to disable AdGuard and the site loads fine without any crashing. It seems to only affect older devices and older IOS versions. I tested it on my 6 Plus on 12.5.5 and on my 7 Plus on 14.8 and they all crashed.

**Comment by jimmysofat6864** [comment]
@AleksandrShulgin any chance of reopening this issue?
