### ISSUE TITLE
Reddit constant crashing

### ISSUE THREAD

**Issue by jimmysofat6864** [AdguardTeam/AdguardForiOS#1904]
### Issue URL (Incorrect Blocking)
 [https://www.reddit.com/r/ios/comments/r2e6qo/apple_should_focus_on_ios_and_user_experience/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.reddit.com%2Fr%2Fios%2Fcomments%2Fr2e6qo%2Fapple_should_focus_on_ios_and_user_experience%2F)
### Comment
Username: @jimmysofat6864
> Reddit seems to crash on any article with AdGuard enabled. To reproduce, just open a reddit article with some filters and eventually the page will crash and you will get the message I get. If it doesn't happen, just refresh the page a few times or load comments or look at some articles and eventually, it will crash and display the message I got. If I enable all the filters in annoyances or privacy, it crashes much faster sometimes without even reloading. Oddly this doesn't seem to be an issue with my iPhone X on IOS 15 just on my 7 Plus on 14.8 and my iPhone 6 Plus on 12.5.5. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/LzOypPe.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/9Yom29X.png)
</details>
<details>
  <summary>Screenshot 3</summary>

  ![Screenshot 3](https://reports-img.adguard.com/3GM3TyS.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.2.2
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances

_Originally posted by @adguard-bot in https://github.com/AdguardTeam/AdguardFilters/issues/101155#issuecomment-980504421_

https://streamable.com/pnf6kb

**Comment by AleksandrShulgin** [comment]
This issue is duplicated in https://github.com/AdguardTeam/AdguardForiOS/issues/1903
