### ISSUE TITLE
Slow application launching

### ISSUE THREAD

**Issue by royerlraph79** [AdguardTeam/AdguardForiOS#1905]
https://user-images.githubusercontent.com/30907279/148887412-34c24481-7ac6-4647-a79f-3e79adb34e03.MP4

Everything was so smooth on the previous version, but now the app takes ages before loading, adding new DNS rules and refreshing queries. 

I’ve attached a screen recording. I’m using an iPhone 12 on iOS 14.7.1 with version 4.3.1 of AdGuard Pro.

**Comment by royerlraph79** [comment]
https://user-images.githubusercontent.com/30907279/148887559-9f8d3e26-6261-44d4-9ed6-e356711c26ec.MP4

**Comment by royerlraph79** [comment]
YES I did try deleting and reinstalling the app before you even ask.

**Comment by ameshkov** [comment]
The situation has been improved a lot in the beta version. Closing this since the release is soon to come.
