### ISSUE TITLE
iCloud sync does not work with AG Family Protection

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#191]
@gshumihin please check it and find out what's responsible for that.

**Comment by ganja24** [comment]
Need Sync for iOS and Mac with iCloud

**Comment by gshumihin** [comment]
For me iCloud works fine with "Family Protection" enabled.
But still, here's log: [icloud.saz.txt](https://github.com/AdguardTeam/AdguardForiOS/files/548335/icloud.saz.txt)

**Comment by Bubu92** [comment]
I totally disagree with gshumihin. The sync does not work. If I may, I want to clarify the issue.

Let's say you have Adguard Pro with DNS Family Protection enabled on an iPhone and an iPad for instance. Try to add a calendar event on the iPad, then it will never appear on the iPhone and vice versa.
If you enable the Default Protection, then the synchronisation will work.

**Comment by ameshkov** [comment]
@Bubu92 thank you for the clarification! @gshumihin we need a new log

**Comment by gshumihin** [comment]
Seems pretty weird to me. What i did:

1. Enabled Family Protection in Adguard DNS settings.
2. Checked that auto sync enabled for calendar and photos in iphone settings
3. Added new event from iphone
4. Went to `https://www.icloud.com/#calendar` 
5. Event from step **3** was already there
6. Added new event from browser

_**Result**_: everything works as it should.

**Comment by gshumihin** [comment]
@Bubu92 Do you have that issue in both type of network?
Also can you please sent us bug report with logs from app (logs are autoincluded)? 
In order to make it easier for us to find out the problem please specify at what time bug was reproduced. 
You can sent them to `gs@adguard.com` this is my email.

**Comment by gshumihin** [comment]
Thanks for logs! As soon we'll find out something, I'll let you know.

**Comment by gshumihin** [comment]
Here's logs @Stillness-2 
https://www.dropbox.com/sh/6ap9bo2p11lp4o2/AAAebFfEdav-v8w17l3xTtA8a?dl=0

**Comment by Bubu92** [comment]
Hello. Any news on this issue?

**Comment by ameshkov** [comment]
@Bubu92 waiting for @Stillness-2 to return from vacations.

Also the situation will be better with the next AG DNS servers update, we'll get rid of quite a few false positives with it.

**Comment by Bubu92** [comment]
OK thanks for the reply!

Then, we'll wait for his return. I hope you guys will solve quickly the issue.

By the way I realized something strange I could not explain.

As I told you I am using Norton DNS address on my WiFi connection. 
However by using also AG Pro DNS, it seems that AG is working over Norton DNS. 
In summary I can access websites that I should not...

**Comment by ameshkov** [comment]
@Bubu92 yep, that shouldn't surprise you, when you turn AG DNS on, it overrides current DNS settings. This applies to wi-fi settings as well.

In future versions we'll introduce "dns filtering" feature which will allow to have dns-level ad blocking along with using whichever DNS you want.

**Comment by Bubu92** [comment]
I understand. However, because it was going through VPN configuration so it was kind of confusing.

I also, found out that you could use a VPN app as TunnelBear in addition to AG DNS. 
But some other VPN app like OpenVPN does not work because they appears in VPN Configuration menu instead of Personal VPN one in iOS VPN settings. A mystery for me... ;-)

Anyway, I deactivated the AG DNS until you find a solution to that Apple iCloud sync issue. Norton DNS is doing a fine job for the present time.

Thanks

**Comment by ameshkov** [comment]
> I also, found out that you could use a VPN app as TunnelBear in addition to AG DNS. 
> But some other VPN app like OpenVPN does not work because they appears in VPN Configuration menu instead of Personal VPN one in iOS VPN settings. A mystery for me... ;-)

Yeah, I wonder how Apple managed to do it. We keep track of compatible VPN apps here: #162

**Comment by Bubu92** [comment]
Interesting information thank you. 

It is too bad that Openvpn Is not compatible. Unlike other VPN services you can input the address you want. 
To be honest there are too many VPN offers on the markets and it is difficult to know the good and honest ones. I found out that some of them are using Malware or your data to push spam and ads. :(
People think they are safe because they are using a vpn. But they don't know if their provider is not sniffing their data which goes through...

**Comment by ameshkov** [comment]
Here you are:
https://thatoneprivacysite.net/vpn-comparison-chart/

**Comment by Bubu92** [comment]
Wow! Excellent. Thank you very much for this information.

**Comment by Bubu92** [comment]
Hello. May I ask what is the update regarding this issue? Cheers

**Comment by Bubu92** [comment]
Hi guys. Is this issue still in progress? I did get any feedback and it has been a while now. Thanks for your response.

**Comment by Stillness-2** [comment]
I can't reproduce this on last debug version. We plan to release beta version this Friday...

**Comment by Bubu92** [comment]
OK. Should I try it and come back to  you?

**Comment by Bubu92** [comment]
If it can help, I just found out something strange about this issue. 

It seems the synchronisation does not work when I on Wi-Fi at home but works on cellular network. 

At the present time I could not understand why.

**Comment by ameshkov** [comment]
> OK. Should I try it and come back to you?

Would be great, do you have access to testflight?

**Comment by Bubu92** [comment]
Yes indeed. 

Did you see my last feedback on the topic? Strangely, the bug seems to be active only in my wifi environment. 

On 19 Dec 2016, at 16:26, Andrey Meshkov <notifications@github.com> wrote:

OK. Should I try it and come back to you?

Would be great, do you have access to testflight?

**Comment by ameshkov** [comment]
> Did you see my last feedback on the topic? Strangely, the bug seems to be active only in my wifi environment.

Yeah, I saw, I just didn't get if it is on the latest version only?

**Comment by Bubu92** [comment]
No not on the beta. On the latest official release.

**Comment by ameshkov** [comment]
@Bubu92 sorry for the delay, I am back from vacation now.

@vozersky please test the issue once again with the latest release.

**Comment by Bubu92** [comment]
The issue is still persistent with latest release on OSX and iOS. Just did another test today.

Again, the calendar syncs when you disable iOS DNS.

**Comment by ameshkov** [comment]
Hm, I just came up with an idea.

Instead of simply trying to reproduce this on our side (which we should do anyway tho), we should just take a look at TWO log files from @Bubu92 and compare them. 

@Bubu92 could you please help us with that?

Here is an instruction:

1. Switch to Adguard Family protection
2. Restart the device (just in case)
3. Reproduce the issue
4. Send us an email from the app itself. Tunnel.gz file attached contains DNS requests log.

5. Switch to Adguard default DNS
6. Restart the device
7. Do successful sync
8. Send us an email again.

I'll need to know your customer ID or email address in order to find the ticket.

**Comment by vozersky** [comment]
I've tried to reproduce with both ipv4 and ipv6, but no luck.

@Bubu92 hi! do you still have the issue only in one particular network? 
Would really appreciate the log file.

**Comment by Bubu92** [comment]
**Sync not working** with with **DNS Family** Protection activated
  **User ID**: 1021351
  **Subject**: [Adguard Pro for iOS] Bug Report

FYI the sync works with with DNS Default Protection activated.

**Comment by Bubu92** [comment]
@vozersky 
In fact it does not work in WiFI environnment (network). 
If you are connected to the telco network there is no issue with the synchronization.

**Comment by ameshkov** [comment]
@Bubu92 second log is with family protection, but in telco?

**Comment by Bubu92** [comment]
@ameshkov Sorry I forgot to mention it. Whatever the protection chosen (Family or Default), the synchronisation works.

**Comment by Bubu92** [comment]
@ameshkov Do you mean you want a log during Telco connection?

**Comment by ameshkov** [comment]
@Bubu92 it's just I see two messages from you, in which case sync was ok? I'd like to compare two logs - problematic and successful

**Comment by Bubu92** [comment]
@ameshkov I see, I get it now. Because I did not receive the automatic email I though the second report did not go through. 

Actually, the second log is still with WiFi connection but with DNS Default Protection activated.

**Comment by Bubu92** [comment]
So to summarize. 

Both connection are in Wi-Fi. 
First log, DNS Family: sync did not work
Second log, DNS Default: sync worked

**Comment by ameshkov** [comment]
A week ago I've added a few domains to family protection exceptions. Any change on your side?

**Comment by Bubu92** [comment]
Just tried again today. It did not synchronise. However I still do lot understand why it works on cellular and not on Wi-Fi network.

**Comment by Bubu92** [comment]
Just tried again today. It did not synchronise. However I still do lot understand why it works on cellular and not on Wi-Fi network. 

On 25 Jan 2017, at 16:26, Andrey Meshkov <notifications@github.com> wrote:

A week ago I've added a few domains to family protection exceptions. Any change on your side?

**Comment by ameshkov** [comment]
> However I still do lot understand why it works on cellular and not on Wi-Fi network.

Neither am I :(

The only thing that comes to my mind is that it may be caused by IPv6/IPv4 settings.
@Stillness-2 should add better support for IPv6 in further updates. Then will see.

**Comment by Bubu92** [comment]
FYI my internet provider does not support yet IPv6.
Also, I attached a screen shot of my Apple AirportTime
![dns address](https://cloud.githubusercontent.com/assets/23118229/22892924/78104624-f214-11e6-8349-3af1ff8c551e.jpg)
 Capsule configuration.

**Comment by vozersky** [comment]
obsolete
