### ISSUE TITLE
The rule doesn't work on an iPhone at vox.com

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdguardForiOS#1913]
The rule `###privacy-consent` from the annoyances filter doesn't work on iPhone at vox.com (checked on 3 iPhones), it exists in the optimized filter and works from user rules. 

<details>
<summary>This cookie-message must be blocked by ###privacy-consent rule</summary>
<img src="https://user-images.githubusercontent.com/18536328/150345554-8d3be469-3b4b-4c88-9b70-6a02424c192f.jpg" />
</details>

iOS 15.2.1
AG 4.3.1

**Comment by AleksandrShulgin** [comment]
Pop-ups have become possible to block with the appearance of the "Advanced Protection" feature.
As I see from the screenshot, the AdGuard extension isn't enabled in the Safari, so the "Advanced protection" doesn't work.
Turn it on, as it says on the "Advanced Protection" tab, and try again.

**Comment by Sergey-Lyapin** [comment]
@AleksandrShulgin
But `###privacy-consent` must work even without "Advanced protection"
