### ISSUE TITLE
DNS Filter Update Dates

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1915]
Why do DNS filters update dates disappeared in AG Pro 4.3.2 (923) except for AG filter?

[image](https://user-images.githubusercontent.com/49731083/151017985-379833b3-8a62-4389-84ee-9c66726bb7a9.jpeg)

**Comment by AleksandrShulgin** [comment]
@Quorum75 
Could you please attach links to these filters.

**Comment by Quorum75** [comment]
@AleksandrShulgin here you go. Thanks. 

https://curbengh.github.io/malware-filter/phishing-filter-agh.txt

https://curbengh.github.io/pup-filter/pup-filter-agh.txt

https://malware-filter.netlify.app/tracking-filter.txt

https://curbengh.github.io/malware-filter/urlhaus-filter-agh-online.txt

**Comment by AleksandrShulgin** [comment]
@Quorum75 
These filters have different metadata names, so the app doesn't recognize them.
We'll return to this issue in the future.

**Comment by Quorum75** [comment]
> @Quorum75 
> 
> These filters have different metadata names, so the app doesn't recognize them.
> 
> We'll return to this issue in the future.

Then, Would you mind to explain why in the past the dates were present with the same filters?

Also, I don't understand the relationship between the names and the dates of update.

**Comment by Quorum75** [comment]
> @Quorum75
> These filters have different metadata names, so the app doesn't recognize them.
> We'll return to this issue in the future.

Hello Alexander. I didn't get any additional answer from my last question?
It seems that updates, blockings don't work properly with external links.

**Comment by badmojr** [comment]
@Quorum75 ,
Is this still happening?
