### ISSUE TITLE
Missed ads

### ISSUE THREAD

**Issue by wlqdevil** [AdguardTeam/AdguardForiOS#192]
https://itunes.apple.com/cn/artist/shen-me-zhi-de-mai/id518213359
https://itunes.apple.com/us/app/qq/id444934666?mt=8
https://itunes.apple.com/cn/app/wei-xin/id414478124?mt=8
https://itunes.apple.com/cn/app/shang-hai-yi-dong-shou-ji/id583700738?mt=8
https://itunes.apple.com/us/app/teng-xun-shi-pin-hd/id407925512?mt=8
https://itunes.apple.com/cn/app/id412395632?mt=8

Why slow speed if use dns？

**Comment by ameshkov** [comment]
@gshumihin please record requests logs of these apps.

**Comment by ameshkov** [comment]
> Why slow speed if use dns？

Coud you please elaborate a bit? Is it slow web surfing or something else?

**Comment by wlqdevil** [comment]
yes it slow web surfing，if you did not use adguard dns ，web open very quick ，then it will stay some second

**Comment by wlqdevil** [comment]
miss ad
智行火车票 for 12306、火车票、高铁自动抢票 作者是 suanya .cn
https://appsto.re/cn/fNM0M.i

**Comment by gshumihin** [comment]
Here's results:
| App | Logs|
| https://itunes.apple.com/us/app/qq/id444934666?mt=8 | [QQ.saz.txt](https://github.com/AdguardTeam/AdguardForiOS/files/553816/QQ.saz.txt) |

**Comment by Alex-302** [comment]
> QQ.saz.txt
> wechat.saz.txt

nothing.

> Tickets, train tickets

Maybe ads are loaded from
http://m.ctrip.com/restapi/soa2/10103/json/GetAdsList
But we can't block this domain completely.

**Comment by Alex-302** [comment]
@wlqdevil please make screenshots of ads for all apps.

**Comment by ameshkov** [comment]
> yes it slow web surfing，if you did not use adguard dns ，web open very quick ，then it will stay some second

I guess that's because we don't yet provide asian DNS servers. Should be better when we do.

**Comment by vozersky** [comment]
@wlqdevil please re-open if the issue still appears
