### ISSUE TITLE
Расширенный CSS на iOS не всегда работает

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForiOS#1921]
> ### Issue URL (Annoyance)
> [https://alternativeto.net/software/todoist/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Falternativeto.net%2Fsoftware%2Ftodoist%2F)
> 
> ### Comment
> Username: `@rakleed`
> 
> > 
> 
> ### Screenshots
> Screenshot 1
> ### System configuration
> Information	value
> AdGuard product:	AdGuard/AdGuard Pro for iOS v4.3.1
> Browser:	Safari
> DNS filtering:	disabled
> Filters:	Ad Blocking:
> AdGuard Base,
> AdGuard Mobile Ads
> 
> Privacy:
> AdGuard Tracking Protection
> 
> Social Widgets:
> AdGuard Social Media
> 
> Annoyances:
> AdGuard Annoyances
> 
> Language-specific:
> AdGuard Russian

_Originally posted by @rakleed in https://github.com/AdguardTeam/AdguardFilters/issues/107120#issue-1106608436_

Тут применяется расширенный css. На iOS он может не всегда работать. Но если ios ниже 15, то работать не будет вообще.

_Originally posted by @Alex-302 in https://github.com/AdguardTeam/AdguardFilters/issues/107120#issuecomment-1027802259_

-----

Возможно ли улучшить это поведение на iOS 15 и выше?

**Comment by ameshkov** [comment]
@maximtop продиагностируй пожалуйста

**Comment by maximtop** [comment]
Не получилось повторить, добавил набор фильтров из задачи, дождался, когда все фильтры и контент блокеры загрузились, зашел на страницу

extended css правила применяются как должны, рекламного блока нет

**Comment by rakleed** [comment]
Действительно, сейчас у меня тоже не отображается реклама. @maximtop а вообще могут ли в AdGuard для iOS c использованием Расширенной защиты быть проблемы с такими правилами?

**Comment by ameshkov** [comment]
Есть одна заметная разница между AG для iOS и другими платформами - задержка перед применением правил на iOS выше.

**Comment by rakleed** [comment]
@ameshkov да, зачастую замечаю это. А это из-за ограничений со стороны Apple или вы всё же можете это улучшить со своей стороны?

**Comment by ameshkov** [comment]
Не из-за ограничений, скорее из-за их деталей реализации расширений. Они там часто убиваются системой и долго инициализируются. Решений каких-то адекватных нет. Там-сям можем наверное чуть ускорить, но это полностью проблему не уберет.
