### ISSUE TITLE
Persian translation pluralization broken in extension

### ISSUE THREAD

**Issue by Jeehut** [AdguardTeam/AdguardForiOS#1922]
The Persian Stringsdict translation file [here](https://github.com/AdguardTeam/AdguardForiOS/blob/master/AdguardExtension/AdguardApp/fa.lproj/Localizable.stringsdict) has 2 problems:

1. It's empty, while all other languages have some entries in there.
2. It's invalid XML/Plist format, cause it has a `</dict>` end-tag but no opening `<dict>` start-tag.

Here's the Stringsdict files full content right now:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict/>
</plist>
```

**Comment by ameshkov** [comment]
@Jeehut hi, does it break the app in some way?

These files are actually auto-generate when we import translations from [Crowdin](https://crowdin.com/profile/adguard/) so we could accept your fix for now, but the ultimate solution would be to translate these strings:)

**Comment by Jeehut** [comment]
I don't actually use the app in that language, I'm just writing a translation  tool and recognized it in my unit tests and thought I should report it. :)

**Comment by ameshkov** [comment]
@Jeehut thank you, helped a lot!
