### ISSUE TITLE
TDL wildcard not working on iOS 15.4

### ISSUE THREAD

**Issue by TommieWong** [AdguardTeam/AdguardForiOS#1924]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v4.3.1(919)
- **Device model and storage size:**
  - iPhone SE 2nd edition
- **Operating system and version:**
  - iOS 15.4
- **Browser or App:**
  - Safari

### Expected Behavior

I have "||youtube.TLDˆ" as a DNS custom rule, which, as I understand it, should block youtube.com, youtube.de, etc., and all their subdomains.

### Actual Behavior

No youtube.*** or their subdomains are actually blocked.

### Additional Information

Other rules, such as "||youtube.comˆ" or "[IP address] youtube.com" work and properly block the domain (and subdomains for the first one).

**Comment by ameshkov** [comment]
Actually, it shouldn't work like that, we don't support proper TLD syntax in the DNS filtering rules.

You should use this rule instead:
`||youtube.*`

**Comment by TommieWong** [comment]
Thanks for the reply. I had found this here (https://kb.adguard.com/en/general/dns-filtering-syntax) and thought it was confirmed here (https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#wildcard-for-tld).
Now I see that I may have skipped the fact that this was for the Android or the Home versions in the first link.
