### ISSUE TITLE
When adding a lot of rules in user filter, it crashes adguard

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#193]
Go to user filter and copy and paste the below code and click on done. It crashes. It should not crash.

Also please when will we be able to add such rules as below in the ios app? At the moment I have to copy it one by one to test. Takes to much time. 

```
@@||q.gs^$generichide
@@||adf.ly^$generichide
@@||static.adf.ly/static/image/
@@||s1-adfly.com/show.php?url=
q.gs#@##bottom
q.gs#$##rf2 { position: absolute!important; left: -100000px!important; }  
q.gs#$##rf { position: absolute!important; left: -100000px!important; }  
adf.ly#$##rf { position: absolute!important; left: -100000px!important; }  
adf.ly#$##rf2 { position: absolute!important; left: -100000px!important; }    
||adf.ly/funcript
||adf.ly/fp.rev3.php
@@||q.gs/1market.php?
```

**Comment by ameshkov** [comment]
@Stillness-2 at least we should handle multi-line copy/paste properly.

**Comment by worldsdream** [comment]
try to add this in userfilter: 

`indiatimes.com#%#AG_onLoad(function() { function unblock() {$('body').children('div, p, span, center, content').each(function(){$(this).css({opacity:'1'})});$("#blcontent").css({opacity:0});$("#blwrapper").css({opacity:0});document.body.style['overflow'] = "visible"; $("#blcontent,#blwrapper").hide();setInterval(unblock,1000); } unblock();});`

it will crash, not professionally. We should see a message like: 

`"This rule can't be added, please check and try again"`

**Comment by Stillness-2** [comment]
#285
