### ISSUE TITLE
There are wrong words in version history on Taiwan app store.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#1931]
Just a trifle...
注目, not 註目.
Here, 注=focus. 註=explanatory note.
千里, not 千裡.
里=unit of distance. 裡=inside.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/SsLhaQD.png)
</details><br/>

There are 2 different kinds of Chinese characters in the world, Chinese Traditional (zh-TW used in Taiwan) and Chinese Simplified (zh-CN used in China).

AG staff should only learn Chinese Simplified in China and don't know Chinese Traditional.

The conversion of Chinese Simplified to Chinese Traditional by translator machine is rough.
Wrong Chinese Traditional characters often occurred in your staff's translations.

Taiwan and China are different countries.
You can still keep Chinese Simplified on China app store.
But you don't have to use translations in version history on Taiwan app store if you only depend on translator machine to convert zh-CN to zh-TW and can't correct wrong Chinese characters.
English in version history on Taiwan app store is acceptable.

**Comment by ameshkov** [comment]
Huh, weird thing is that auto-conversion tools do actually convert it properly so this is a human mistake.

Thank you!

**Comment by lancelot-moon** [comment]
@ameshkov 
Well, 注 and 註 are often not the same meaning in modern Chinese Traditional.
(It seems that no 註 is in Chinese Simplified because the similar pronouncing words were simplified to the same word, 注, in Chinese Simplified.)

里 and 裡 are not the same meaning in modern Chinese Traditional.
(It seems that no 裡 is in Chinese Simplified because the similar pronouncing words were simplified to the same word, 里, in Chinese Simplified.)

I forget that AdGuard still isn't allowed on China app store, right?
Your staff don't learn Chinese Traditional.

Even so, there are online Chinese Traditional dictionaries.
https://pedia.cloud.edu.tw/Entry/Detail/?title=%E5%AD%97%E5%85%B8

Or search words & show Chinese Traditional results on google and only check wordings on Taiwanese websites, www.xxx.tw.

Just rough and wrong conversion from zh-CN to zh-TW because it's *.com.cn (Chinese website, not Taiwanese website)
http://edu.people.com.cn/BIG5/n1/2019/0621/c1053-31173412.html

Information on google search aren't absolutely correct.
Need to pick up.
https://www.google.com/search?q=%E4%B8%8D%E7%A9%8D%E8%B7%AC%E6%AD%A5&tbs=li:1&sa=X&ved=2ahUKEwjjue_qo__1AhXzlFYBHSbAB2UQpwV6BAgBECY
