### ISSUE TITLE
DNS server's domain name cannot be resolved using the default DNS server of a Wi-Fi network

### ISSUE THREAD

**Issue by LucasMucGH** [AdguardTeam/AdguardForiOS#1932]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v4.3.2
- **Device model and storage size:**
  - iPhone XR 64gb
- **Operating system and version:**
  - 15.3 (19D50)

### Expected Behavior

Have internet connection when connected to Wi-Fi.

### Actual Behavior

No internet connection.

### Additional Information

- Debug-Logs: https://we.tl/t-G3JlCtedZ8
  - If requester i can provide more logs.
- Activating „Restart protection when network changes“ doesn’t help.
- I have the same problem on my iPad Air 4
  - If requested I can provide logs
- Some Wi-Fi’s are working
- It appears kind of random
- It never appears when connected via cellular
- Maybe?? related to: #1901, #1892

Note: This is Not a new Problem. It already exist since a couple of app versions. I didn’t reported it jet, because I hoped it would be resolved by #1901 or #1892.

**Comment by ameshkov** [comment]
The reason for this is that AdGuard cannot resolve `dns.adguard.com` using your Wi-Fi's system DNS server:
```
2022/02/09 19:14:55:753 [4046128(DnsAdGuardSDK.DnsRequestProcessedEventHandler.eventQueue)]  (DnsRequestProcessedEventHandler) - handleEvent; Error: Upstream (https://dns.adguard.com/dns-query) exchange failed: first reason is Could not resolve dns.adguard.com
, second is: Could not resolve dns.adguard.com
```

It'd help to troubleshoot it better if you enable debug-level logs (currently the logging level is INFO).

Here's what we need you to do:

1. Go to Settings -> General -> enable Advanced Mode -> Advanced Settings -> enable "Debug logs"
2. Reproduce the issue
3. Export logs and send them to `devteam@adguard.com`
4. Mention this issue in the email

The DNS server it tries to use to resolve `dns.adguard.com` is `192.168.188.1`. It'd be interesting to see what happens if you run `nslookup dns.adguard.com 192.168.188.1` on your computer connected to the same Wi-Fi network. Is it able to resolve the domain successfully?

**Comment by ameshkov** [comment]
> But as to my knowledge, DEBUG logs were enabled. Do I have to restart the app/protection for it to work? Otherwise I’m not sure why those weren’t DEBUG logs.

Well, in theory it should be enough to restart DNS protection

**Comment by LucasMucGH** [comment]
Debug logs are send. The `nslookup dns.adguard.com 192.168.188.1` will be tested tomorrow.

**Comment by ameshkov** [comment]
Received, thank you!

Oh, and besides nslookup question there's another one: does it work okay when you choose "System default DNS" in AdGuard settings?

**Comment by LucasMucGH** [comment]
```
nslookup dns.adguard.com 192.168.188.1
Server:		192.168.188.1
Address:	192.168.188.1#53

** server can't find dns.adguard.com: NXDOMAIN
```
AdGuard works on my MacBook without problems, despite being connected to the same wifi and DNS provider.

When selecting `System default DNS` connection also works on my iPhone.

**Comment by ameshkov** [comment]
Well, something is very wrong with your provider's DNS server. For some reason, it decided (or blocked) `dns.adguard.com`.

The solution would be to use a custom bootstrap server and ignore your provider's DNS:
Settings -> Advanced -> Low-level -> Bootstrap servers

You could use ours as bootstrap: `94.140.14.14` (or Google/Cloudflare/etc).

**Comment by ameshkov** [comment]
Just in case, what's your ISP?

**Comment by LucasMucGH** [comment]
Omg, I think I realized something….
Im using iCloud Private relay; maybe there is an compatibility issue. Due to iCloud private relay my current isp is „ iCloud Private Relay
AS36183 Akamai Technologies, Inc.“ but his can change quite often.

**Comment by ameshkov** [comment]
Well, iCloud Private relay is what's used by your macOS, the server on `192.168.188.1` is from your real ISP.

**Comment by LucasMucGH** [comment]
Im not sure if I’m using iCloud private relay on my macbook, but I’m using it on my iPhone and iPad. Both devices have problems connecting to the internet when using the AdGuard DNS server. The ISP `iCloud Private Relay AS36183 Akamai Technologies, Inc.` mentioned earlier is what my iPhone think that my ISP is. I will look the ISP later up, when iCloud private relay is disabled.

**Comment by ameshkov** [comment]
Note that iCloud Private Relay is not a full-scale VPN, it only routes some connections through the relay.
I doubt that `192.168.188.1` belongs to it, and I don't think `nslookup` is routed through the relay.

**Comment by LucasMucGH** [comment]
That means there is something wrong with my ISP, and except for
> The solution would be to use a custom bootstrap server and ignore your provider's DNS:
> Settings -> Advanced -> Low-level -> Bootstrap servers
there is nothing I can do?

PS: i enabled these setting and will check later, when I’m back home, wether it works. When I’m back I also will look up the ISP of the Wi-Fi.

**Comment by LucasMucGH** [comment]
My ISP (without iCloud private relay) is:
```
Vodafone Kabel Deutschland
Kabel Deutschland Customer Services
AS3209 Vodafone GmbH
```

When adding the bootstrap server, the internet connection is working. But I’m still confused, why I never had a problem on my MacBook; all AdGuard settings were always the same (same dns configuration, filters, etc.) and it was always connected to the same WiFi. The only difference is that I’m using AdGuard for Mac and that I’m not using iCloud private relay (I’m still on Big Sur, and it is a feature of Monterey).

**Comment by ameshkov** [comment]
> But I’m still confused, why I never had a problem on my MacBook; all AdGuard settings were always the same (same dns configuration, filters, etc.) and it was always connected to the same WiFi

Hmm, this all sounds very, very strange.

Have you disabled AdGuard for Mac when running `nslookup`? Is there any change if you stop AdGuard before doing it?

Also, AG on macOS can fall back to your provider's DNS when the upstream is blocked, this may be the reason why it works in general on macOS.

> The only difference is that I’m using AdGuard for Mac and that I’m not using iCloud private relay (I’m still on Big Sur, and it is a feature of Monterey).

AG for Mac is not compatible with Private relay btw (as is any network extension):
https://kb.adguard.com/en/macos/solving-problems/icloud-private-relay

But there're no such issues on iOS.

**Comment by LucasMucGH** [comment]
> Have you disabled AdGuard for Mac when running nslookup? Is there any change if you stop AdGuard before doing it?

Tried both variants again, just to be sure. But there is no change.

> Also, AG on macOS can fall back to your provider's DNS when the upstream is blocked, this may be the reason why it works in general on macOS.

This could be the case. But that means, that i will have to configure the bootstrap server for my mac too, for him to work correctly? Also is there any way to figure about, weather it is working on my mac or if it falls back to the provider dns Server?

> AG for Mac is not compatible with Private relay btw (as is any network extension):
https://kb.adguard.com/en/macos/solving-problems/icloud-private-relay
> 
> But there're no such issues on iOS.

Thank you for the information, I will keep this in mind for when I update to Monterey.

**Comment by ameshkov** [comment]
> But that means, that i will have to configure the bootstrap server for my mac too, for him to work correctly?

Yep, that's right, can be done via "advanced settings".

> Also is there any way to figure about, weather it is working on my mac or if it falls back to the provider dns Server?

Check if it's detected properly on https://adguard.com/test.html

**Comment by ameshkov** [comment]
Argh, wrong link in the commit

**Comment by LucasMucGH** [comment]
> Check if it's detected properly on https://adguard.com/test.html

Yes, it wasn't enabled probably on my Mac.

> Also, AG on macOS can fall back to your provider's DNS when the upstream is blocked, this may be the reason why it works in general on macOS.

You are completely right.

Therefore the issue is resolved. But nevertheless I would like to mention, that it is a little bit misleading, that AdGuard falls back to provider on Mac. It may be not expected my most users and in my case made it look like there is an issue with the IOS App. Im not sure if it should be changed and if how. I will leave that to you professional opinion.

Last but not least, thank you very much for looking into my problem and explaining it to me. I added the bootstrap to all devices and now it is working with out problems. Keep it up!

**Comment by ameshkov** [comment]
Awesome, thanks for taking your time to debug this!

We will try to contact your ISP and ask them why `dns.adguard.com` is blocked on their network.
However, it might help if you ask their support service about this as well. You're a customer after all so they might listen to you.

**Comment by ameshkov** [comment]
@LucasMucGH I've tried to contact Vodafone Kabel on this matter, but it seems that in order to escalate this issue they need a customer to contact them directly :(

**Comment by LucasMucGH** [comment]
Thank you, I will contact them as soon as I have time. 🙏
