### ISSUE TITLE
DNS protection randomly uses mobile data with Wi-Fi icon

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForiOS#1934]
### Issue Details

- **AdGuard version:**
  - Version 4.3.2(938)
- **Device model and storage size:**
  - iPhone SE (2020) 64GB
- **Operating system and version:**
  - iOS 15.3.1

### Expected Behavior
DNS protection will use mobile data when mobile data icon is visible, and Wi-Fi when Wi-Fi icon is visible.

### Actual Behavior
DNS protection will start to use mobile data when Wi-Fi icon is visible. Only way to resolve is to disable and re-enable DNS protection.

### Additional Information
Doesn't happen too often, but it is a frustrating issue when you have limited mobile data and it suddenly runs out because of this issue.

- Implementation is via AdGuard, not Native
- DNS server is System default
- DNS filtering is enabled and uses AdGuard DNS filter
- Network settings/exclusions are left as default
- 'Restart protection when network changes' does not make a difference as it thinks it is still on the Wi-Fi network
- Tunnel mode is left as Split-Tunnel
- Background app refresh interval is set as Every hour

**Comment by ameshkov** [comment]
Oh, this will be **really** not easy to troubleshoot since I don't really understand what could be the reason here.

The thing is that we reload DNS protection on every network change exactly to make sure that DNS protection uses the active connection.

First of all, we'll need as many details as possible about this:

1. How do you detect this behavior?
2. What's the scale of it? When it happens, how much data does it actually use?
3. Anything else you can add.

**Comment by planet0** [comment]
I had a feeling it would be difficult. The next time it occurs I will definitely send logs, but until then:
1. The quickest way is that I get an SMS from my mobile provider that I have used 50%, or 75% of data at a really unexpected date. That's when I realise I am not actually using my Wi-Fi connection.
2. The last time this occurred was a few days ago, and used 573 MB of mobile data in six minutes, instead of Wi-Fi. Since then, my mobile provider usage info and the iOS mobile data usage show only 1~3 MB of mobile data being used daily (as I'm at home using Wi-Fi.
3. I've made sure Wi-Fi assist was turned off and that iCloud Drive for mobile data was also turned off.
That's all I can think of for now.

**Comment by ameshkov** [comment]
> The last time this occurred was a few days ago, and used 573 MB of mobile data in six minutes, instead of Wi-Fi

This is weird, 573 MB of DNS traffic is like resolving half of the internet domains.

**Comment by planet0** [comment]
Hmm, it can't just be DNS traffic. I think iOS is also using the mobile data when this occurs. Can that occur if the Wi-Fi icon is visible alongside the VPN icon, but iOS also routes all data through mobile data?

**Comment by ameshkov** [comment]
In general, iOS can start using mobile data when it thinks that it's faster/better than the current Wi-Fi connection.

**Comment by planet0** [comment]
Even with Wi-Fi assist turned off? The Wi-Fi connection here is 432 Mb/s with 100 megabit internet and Wi-Fi 6, and the mobile service here is much poorer. This issue only occurs with the VPN tunnel too.

I once used full-tunnel mode as described here but that also caused the same issue to occur more frequently.
https://github.com/AdguardTeam/AdguardForiOS/issues/1881

**Comment by ameshkov** [comment]
Hm, without Wi-Fi assist it shouldn't be doing that.

We actually can try to troubleshoot this using AdGuard logs. Look for the strings that start with `NWPathMonitor received the current path update` (that's how AG monitors network changes).

If the first interface in the list is `en0` then you're on Wi-Fi. If it is `pdp_ip0`, you're on cellular.

Now what's left is to figure when exactly the issue kicks in so that we could find the right place in the log.

**Comment by planet0** [comment]
It took a little while for me to detect it, but it just occurred for me.

The Wi-Fi icon was visible and showing live signal strength, but was using my mobile data and my IP address was showing my mobile provider.

Once I opened the AdGuard app, it corrected itself and the IP address was showing my home ISP.

I've exported logs just after it resolved itself and emailed it, hopefully there is something there…

**Comment by ameshkov** [comment]
Got the log, but I don't see us using mobile data.

Here's how you can verify it using the log. Every time the tunnel starts up, there are log records that look like this:
```
2022/03/15 15:37:51:262 [127006(DnsAdGuardSDK.DnsProxyBuilder.resolveQueue)]  (DnsLibs) - RouteResolver resolve: Match 94.140.14.14:53 -> en0
```

This is the DnsLibs checking which route to use to send DNS queries through. In this case it uses `en0` which means your Wi-Fi connection.

**Comment by planet0** [comment]
How odd. I saw my apps using mobile data (Snapchat on low data mobile mode), and Safari was showing my IP address from my mobile provider.

Does this mean that it is iOS that refuses to use the VPN connection during this moment, even when on Full-Tunnel mode?

**Comment by ameshkov** [comment]
Not really, only the DNS traffic is routed through the tunnel. Everything else goes directly to your active network.

Tbh, looks like an iOS bug.

**Comment by planet0** [comment]
Sure, happy to close this since it's out of AdGuard's control. Thanks for looking into this though.
