### ISSUE TITLE
Checkbuttons in front of each rule in user filter/whitelist

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#194]
Can we have checkbuttons in front of each rule?

If I am testing rules, right now I have to delete and add all the time. I want to uncheck it, so I can test and check again. Simplifies so much. 

Just like we have on adguard windows and adguard mac. And extension is going to have it hopefully within couple of months.

**Comment by worldsdream** [comment]
@ameshkov. On ios, we will not have check buttons. Will // in front of a line work to disable that rule? Or is there something else to disable a rule. If yes, can this be added in the app. Because I can't find anything about it.

**Comment by ameshkov** [comment]
@worldsdream 

> On ios, we will not have check buttons. 

Eventually, we will. I'd like us to have the same functionality as Android version:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1279

> Will // in front of a line work to disable that rule?

`!` will
