### ISSUE TITLE
Missing description inside the message to the support service

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1940]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

When sending a bug report through AG for Mac or iOS there is no history of the bug Description attached to AG email. 
Then when AG support contacts the user, we don't know which report they are referring to. 

### Proposed Solution

 Add in AG support message à copy of the description issue sent by the user.

**Comment by ameshkov** [comment]
Okay, I got it, there's a task about that on our support service side. Not a program bug.

**Comment by Quorum75** [comment]
@ameshkov Indeed, no a program bug, more a CRM issue. I didn't know where to mention it though.
