### ISSUE TITLE
Crash due to an invalid filtering rule in the EasyList Cookie List

### ISSUE THREAD

**Issue by CSM6061** [AdguardTeam/AdguardForiOS#1941]
- [X ] I am running the latest version
- [ X] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

### Issue Details

Adguard for iOS v4.3.2 running on iphone 12 and iPad 6 running iOS v15.3.1 constantly crashes to the point the app is inop. Cannot update or access various app features causes crash as well.  I wish I could be more descriptive but the app will start, but when any app feature is used the app crashes.

**Comment by ameshkov** [comment]
Could you please export the crash report?

Settings -> Privacy -> Analytics -> find AdGuard crash report and attach it here.

**Comment by moisterrific** [comment]
I have the same issue, it was working fine before now constantly crashing whenever I open it. Using the latest version 4.3.2 on iPhone 13 Pro Max running stable iOS 15.3.1. To rule out any lack of available memory issues I tried opening AdGuard Pro right after refresh reboot and it still crashes about 5-10 seconds after I open it. 

I managed to get a log exported from within the app before it crashed and also found the .ips in analytics, which I have attached. I can add the in-app logs too if necessary.

[catbox upload for IPS file](https://files.catbox.moe/ywsnwz.ips)

**Comment by moisterrific** [comment]
Worth mentioning there are actually a lot of .ips files related to AdGuard, the one I’ve included above is the most recent one. 
![94738F0E-DA44-4358-AE10-4B56749C9B3D](https://user-images.githubusercontent.com/57187883/154896666-b8f44a82-c672-4de3-b9e6-a7aa751aab9e.jpeg)

**Comment by ameshkov** [comment]
Every crash generates an ips file (crash report) so this is understandable.

**Comment by ameshkov** [comment]
Just in case, does it help to reinstall the app?

**Comment by moisterrific** [comment]
> Just in case, does it help to reinstall the app?

I will try that now.

**Comment by moisterrific** [comment]
Still crashes when I try to manually refresh the filters after a reinstall. It’s not crashing as long as I don’t try to refresh/update the filters. Also it’s worth mentioning that the crash seems to happen **after** I imported my own user rules (158 of them)

**Comment by ameshkov** [comment]
> after I imported my own user rules (158 of them)

This one may be VERY important. Is it possible to share that list with us privately? You can send it to `devteam@adguard.com` and mention this issue.

**Comment by moisterrific** [comment]
> > after I imported my own user rules (158 of them)
> 
> This one may be VERY important. Is it possible to share that list with us privately? You can send it to `devteam@adguard.com` and mention this issue.

Sure thing, no problem.

**Comment by ameshkov** [comment]
Received it, thank you!

**Comment by CSM6061** [comment]
I have attached the most recent 4 *.ips files as requested     On Sunday, February 20, 2022, 03:25:58 AM CST, Andrey Meshkov ***@***.***> wrote:  
 
 


Could you please export the crash report?

Settings -> Privacy -> Analytics -> find AdGuard crash report and attach it here.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ameshkov** [comment]
@moisterrific definitely the issue is in the custom rules, it fails to convert on of them. Would be rather easy to fix.

@CSM6061 without seeing your crash report I can't say if your issue is the same.

**Comment by CSM6061** [comment]
Here are the latest crash files, thank you!
[Adguard-2022-02-15-050640.zip](https://github.com/AdguardTeam/AdguardForiOS/files/8118632/Adguard-2022-02-15-050640.zip)

**Comment by ameshkov** [comment]
@CSM6061 yeah, looks like the same issue.

Just in case, do you have "EasyList CookieList" enabled? If you do, try disabling it for now.
