### ISSUE TITLE
DNS-Filter: "https://app-measurement.com/sdk-exp" not blocked while on block list

### ISSUE THREAD

**Issue by Knubbel** [AdguardTeam/AdguardForiOS#1942]
### Issue Details

- **AdGuard version:**
  - AG for iOS v4.3.2 (938)
- **Device model and storage size:**
  - iphone SE 2020 128GB
- **Operating system and version:**
  - ios 15.3.1

### Expected Behavior

"||https://app-measurement.com/sdk-exp^$important " is on my personal DNS blocklist and as such it is marked with a red dot in the "last activity" view.
I expect this to be blocked and the blocking to result in the same entry to have a red background.

### Actual Behavior

This blocking rule does not work and subsequently it is not marked with a red background.
At the same time my other rule "||app-measurement.com/sdk-exp^$important " does work as it should.
The preceding "https://" seems to cause issues.

![adguard bug](https://user-images.githubusercontent.com/8947374/154642311-b63da32a-db24-47ea-848b-1664e4e43267.PNG)

I do wonder why both items are logged separately as well (this double logging is the trigger for me setting up two block entries).

**Comment by sfionov** [comment]
Seems that some library tries to resolve something that is not domain.

Since adblock-style rules has auto-conversion for compatibility with regular adblock-style lists, protocol is stripped during parsing and therefore not used during matching. Hosts rules has domain validation, so can't be used too.

However, regex rules like `/https:/` or `/app-measurement.com/` should work

**Comment by Knubbel** [comment]
` /app-measurement.com/` does seem to work. Thanks for the suggestion.

I still consider it a bug and also assume there is a bug that this specific request gets through to the DNS request log in the "https:" format while in absolutely all other cases (and you know today pretty much all webpages are "https:") this prefix does not appear.

**Comment by ameshkov** [comment]
We're receiving this question rather often, I am already thinking of adding it to FAQ.

**Comment by royerlraph79** [comment]
Go in your blocklist and add *appmeasurement.com*
