### ISSUE TITLE
DNS-over-QUIC randomly breaks internet in v4.3.3 beta

### ISSUE THREAD

**Issue by AidanGee7** [AdguardTeam/AdguardForiOS#1945]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

Since updating to iOS 15.4 Beta 3 earlier this week, AdGuard DNS protection seems to be breaking internet connectivity (Mostly when the phone is first turned on or if you turn off and on WiFi/mobile data).

Turning off DNS protection fixes the issues and a lot of the time simply turning DNS protection off and back on again fixes this.

- **AdGuard version:**
  - AdGuard for iOS 4.3.3 (940) testflight
- **Device model and storage size:**
  - iPhone 13 Pro Max 256GB
- **Operating system and version:**
  - 15.4 Beta 3

### Expected Behavior

DNS protection should work like normal and allow you to browse the internet/use different apps.

### Actual Behavior

Internet connectivity on the phone breaks until you either disable DNS protection or cycle it off and on.

### Screenshots

Will attach a video recording:
https://user-images.githubusercontent.com/28673281/154856214-45c33d0d-807e-48d2-b2d4-d0cc594ab1b3.mp4

In the video example, I have DNS protection turned on, set to AdGuard VPN implementation, using NextDNS (quic protocol). I try to browse the internet and click on a link however the page doesn't load and times out with an error on Safari. Going back to AdGuard and disabling DNS protection then fixes the issue and I can browse the internet again.

### Additional Information

Only started happening since the latest iOS beta.

This is the first issue I've ever raised on here so please let me know if you need me to do anything else!

**Comment by AidanGee7** [comment]
**Update:**

Using DNS-over-TLS/DNS-over-HTTPS seems to stop the issue from happening.

It appears to be an issue with DNS-over-QUIC.

A similar thing has started happening on AdGuard for Windows too (Having to turn protection off and then on again to fix connection when using a DNS-over-QUIC server).

**Comment by ameshkov** [comment]
Hmm, interesting. Could you please collect debug logs (ideally, from AdGuard for Windows) and send them to `devteam@adguard.com`? We'll need to know the exact time when the issue happened.
