### ISSUE TITLE
[Suggestion] Add a "continue without subscription" button in the initial step-by-step guide

### ISSUE THREAD

**Issue by All3xJ** [AdguardTeam/AdguardForiOS#1948]
### Prerequisites

- [X] I am running the latest version (downloaded from AppStore)
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description

New user who download AdGuard for iOS, will receive the subscription message, and who doesn't know that AdGuard can be used for free, may close and delete the app. abandoning it

### Proposed Solution

I propose to add a possibility to choose the "free" subscription, instead of manually close with X button the subscription window (I in the first place thought that there was only premium subscription possible).

### Additional Information

I am talking about iOS (iPad) version.

**Comment by zzebrum** [comment]
@All3xJ tbh your suggestion may lead to decreasing sales.
