### ISSUE TITLE
Make Safari block automatic, instead of manually clicking in the extension button and enable it

### ISSUE THREAD

**Issue by All3xJ** [AdguardTeam/AdguardForiOS#1949]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version (from AppStore)
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description

When I complete step-by-step guide when I opened Adguard the first time, and I open YouTube with Safari, I still have ads. This is because I have to manually click on extension Safari button, and then manually enable Adguard to perform actions on the website. This may not be great for people that are not very techy, and they may think that Adguard does not work.

### Proposed Solution

If this is not fixable in a easy way, I'd add a message after the step-by-step guide which tell that you have to manually enable Adguard when you open Safari. Or maybe a warning that gives you this info if you haven't enabled Adguard on Safari extensions button yet.

### Additional Information

I have this "problem" in my iPad

**Comment by ameshkov** [comment]
If you're on iOS 15, you can enable AdGuard's advanced protection and allow it to work all the time.
