### ISSUE TITLE
L'Express : l'actualité en temps réel app issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#195]
Yesterday the ad disappeared at the launch of this application :
L'Express : l'actualité en temps réel by GROUPE ALTICE MEDIA https://appsto.re/us/SoUbv.i
But since today the screen remains blank and I have to close the invisible ad.
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/19624643/630a77c2-9909-11e6-8834-d0b8a15a301e.png)

</details>
1021351

**Comment by gshumihin** [comment]
There's log: 
[lexpress.saz.txt](https://github.com/AdguardTeam/AdguardForiOS/files/548474/lexpress.saz.txt)

**Comment by Alex-302** [comment]
Try to block this domain
```
mobile.smartadserver.com
```

**Comment by gshumihin** [comment]
Today I wasn't able to see this ad. 
Adding mobile.smartadserver.com to blacklist doesn't break app.

**Comment by Alex-302** [comment]
@gshumihin I mean it should to remove overlay like on screenshot.

**Comment by ameshkov** [comment]
@Alex-302 should we block the whole `smartadserver.com` domain?

**Comment by Alex-302** [comment]
@ameshkov in generally - yes. But this domain was excluded, because anti-adblock script on bild.de checks this domain.
Exclusion replaced by:
```
@@||cdn1.smartadserver.com
@@||eqx.smartadserver.com
@@||itx4.smartadserver.com
@@||tmk.smartadserver.com
@@||ww251.smartadserver.com
```
