### ISSUE TITLE
Excessive battery  consumption

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1953]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  AdGuard Pro Beta v4.3.3
- **Device model and storage size:**
  -  iPad 11 Pro
- **Operating system and version:**
  -  iPadOS 15.3.1
- **Browser or App:**
  -  N/A

### Expected Behavior

 Less battery  consumption 

### Actual Behavior

 Excessive battery  consumption 

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49731083/156408126-d546de07-a487-4303-9b58-659aa41af3ae.jpeg)

</details>

**Comment by ameshkov** [comment]
The root cause must be the same as for #1954

**Comment by Quorum75** [comment]
@ameshkov I don't think so because my iPad is Wi-Fi only. So the Wi-Fi/Cellular issue doesn't apply to me.

**Comment by ameshkov** [comment]
@Quorum75 still reproducible with the release?

**Comment by Quorum75** [comment]
> @Quorum75 still reproducible with the release?

Nope. Much better now. Thanks. 

![image](https://user-images.githubusercontent.com/49731083/161688496-ea6a9c70-7be7-4f0b-aa48-354c4900a7d8.png)
