### ISSUE TITLE
Switching networks disables internet

### ISSUE THREAD

**Issue by loca-lhost** [AdguardTeam/AdguardForiOS#1954]
When I switch from wifi to mobile data and vice versa, internet doesn't work unless I toggle dns protection off and on before it works.

AdGuard Pro 4.3.3 (946)
iOS 15.4 Public Beta 5

**Comment by ameshkov** [comment]
the bug was introduced in build 946, the fix is on the way

**Comment by dobby1970** [comment]
It's still not fixed for me in the latest build 4.3.3 (947)
I have turn adguard of and on manually when switching WiFi/4G-5G

**Comment by ameshkov** [comment]
@dobby1970 this is definitely a differ issue then, I am quite sure that all "simple" cases are solved in v4.3.3 and the only thing that's left is what cannot be reproduced on our side.

If you can reproduce it, we need your help to figure it out.

Please do the following:
1. Enable Advanced mode in the settings
2. Switch the logging level to Debug
3. Reproduce the issue
4. Settings - Support - Export logs
5. Send the logs to devteam@adguard.com

Please mention this issue in the email and also the approximate time when it happened.
