### ISSUE TITLE
[UI] Issue with the query graphic

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdguardForiOS#1955]
Hello,

I have a very strange problem with the query graphic:
![1024F5DF-D2FC-4838-A32C-3A8B6DAD7CE8](https://user-images.githubusercontent.com/45385632/156571077-38c289ef-9b4a-4c72-a7f8-027a64c726dd.png)
![D3CD1950-8B7A-494B-94A2-CE3D6EF95257](https://user-images.githubusercontent.com/45385632/156571083-3d30cc11-9937-49fd-995b-29002ccef6dd.png)
![2665ADA8-D638-419C-BA26-5C9B9290EE11](https://user-images.githubusercontent.com/45385632/156571085-1c8c4455-3090-4b1a-b3d5-6b4c8a99d9b3.png)
![12B8C276-54FD-4E93-8811-1A2BA54AA213](https://user-images.githubusercontent.com/45385632/156571088-0977818b-4d97-41d1-a1a6-c24caf7b28f0.png)

Only one straight line. It's impossible😂 iOS 15.3.1, AdGuard for iOS Pro 4.3.2 (938).

Thank you.
Best regards😘

**Comment by zzebrum** [comment]
@ammnt sorry for the late reply! Please update to the latest v4.3.3(947)

**Comment by ammnt** [comment]
@zzebrum, I have the same thing with the last version. Do I need to reset the stats first? Thank you.

**Comment by ammnt** [comment]
@zzebrum, I still have this issue even after reset the stats☹️
