### ISSUE TITLE
Appzapp notify app - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#196]
https://itunes.apple.com/us/app/appzapp-notify-personal-alerts/id845046425?mt=8

<details>
![image2](https://cloud.githubusercontent.com/assets/15856304/19625876/4f3b2d1c-992d-11e6-8033-61ef13a3b41d.PNG)
![image4 1](https://cloud.githubusercontent.com/assets/15856304/19625877/54597f60-992d-11e6-9294-17a5fbbebf89.PNG)

</details>

logs and stuff: 1434424

**Comment by Alex-302** [comment]
@evgeniy-ADG What the ad system is it? Not Google Ads?

**Comment by gshumihin** [comment]
No ads for me as always) 
But here's log:
[appzap.saz.txt](https://github.com/AdguardTeam/AdguardForiOS/files/548469/appzap.saz.txt)

**Comment by ameshkov** [comment]
@Alex-302 anything there?

**Comment by Alex-302** [comment]
@ameshkov on screenshot we see Google Ads banner, but I don't see requests to google in SAZ file.
Also there are few urls, probably related to that banners,
<details>
![image](http://i85.fastpic.ru/big/2016/1027/d3/9d26c150893be760b66a906f33ff66d3.png)
</details>
but we can't block them by DNS.

**Comment by ameshkov** [comment]
Yeah, you're right, I don't see how this can be blocked with a DNS
