### ISSUE TITLE
The  content blocker is inoperative.

### ISSUE THREAD

**Issue by Richelieu4771** [AdguardTeam/AdguardForiOS#1960]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard for iOS 4.3.3(947) release channel 
- **Device model and storage size:**
  - iPhone 12 Pro Max, 256GB
- **Operating system and version:**
  - iOS 15.4 
- **Browser or App:**
  - Safari 

### Expected Behavior
 It just needs to block advertisements as it used to.

### Actual Behavior
 It does not block advertisements at all, and only empty spaces remain due to DNS blocking.

### Screenshots

<details><summary>Screenshot:</summary>

![IMG_5479](https://user-images.githubusercontent.com/68171816/158292203-e6fbf6df-30e6-40e8-bd56-8e9943a07f36.PNG)

![IMG_5480](https://user-images.githubusercontent.com/68171816/158292218-6ef7d955-7a37-4cdd-aff8-49a90e48e3e8.PNG)

![IMG_5481](https://user-images.githubusercontent.com/68171816/158292231-562fb8ce-2cc7-4aea-843d-b07e4462475f.PNG)

</details>

### Additional Information
 The same problem is occurring in my iPad Mini 6 Gen. Therefore, it will be easy to implement this. If you need a log, I can send it to you by email.

**Comment by Richelieu4771** [comment]
I just turned off the toggle(disabled) in the Safari user rules section, and the content blockers became normal. I hope this will help solve the problem.

**Comment by Richelieu4771** [comment]
![image](https://user-images.githubusercontent.com/68171816/159150781-237cf658-b546-4f96-b08b-5386ca68fdcb.jpeg)

Oh, you may not need to solve this problem. When I removed the filter named List-KR, I could see that everything was back to normal as shown in the screenshot above. From a few days ago, the number of filters in List-KR decreased to 1/10, indicating that there is a problem with the filter.

Currently, it has been about a day since the filter was removed, but there is no problem, so if you read this issue, you can close this.

Thank you!

**Comment by zzebrum** [comment]
@Richelieu4771 please, reopen this issue if the problem appears again.
