### ISSUE TITLE
na.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#1967]
@adguard-bot commented on [Sun Mar 27 2022](https://github.com/AdguardTeam/AdguardFilters/issues/113942)

### Issue URL (Incorrect Blocking)
[NSFW] [http://www.na.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.na.com)
### Comment
Username: @sam20e
> Hello. I tried sending an email to support email 2 times now. It’s been more than a month without any reply that’s why openings a bug report. 
> 
> I’m using iOS and latest adguard. I’m using adguards dns protection which successfully unblocks some of our countries blocked websites. But whenever I switch from 4g to wifi or vice versa the dns protection is automatically turned off. I tried reinstalling the app also but it’s a little bit inconvenient to go back and turn on dns protection Everytime when there is a network change. Can you check and advise?
> 
> Thanks. 

### [NSFW] Screenshots
<details>
  <summary>Screenshot 1</summary>

  [Screenshot 1](https://reports-img.adguard.com/ZUsXUaH.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  [Screenshot 2](https://reports-img.adguard.com/ZUsXUaH.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.3.3
Browser: | Chrome
DNS filtering: | server: `https://dns.adguard.com/dns-query`<br>
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances

**Comment by zzebrum** [comment]
#1966
