### ISSUE TITLE
`:xpath` related rule is not working properly or suppress errors while handling rules (same on AdGuardForSafari)

### ISSUE THREAD

**Issue by seia-soto** [AdguardTeam/AdguardForiOS#1968]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  AdGuard Pro for iOS v4.3.3 (947)
- **Device model and storage size:**
  -  iPhone 8 GSM 256GB
- **Operating system and version:**
  -  iOS 15.4
- **Browser or App:**
  -  Safari only

#### *PLEASE REFER THE FOLLOWING ISSUE OCCURED SAME ON MACOS SAFARI BROWSER EXTENSION*

- https://github.com/AdguardTeam/AdGuardForSafari/issues/698

AdGuard should run properly without any error and block ads on the website I am visiting.

Or even if the error occurred during the parsing process, AdGuard should execute remaining the proper rules regardless of the error status.

### Actual Behavior

AdGuard crashed during its execution of extension content if there is `:xpath` syntax in the filter list.

```
Unhandled Promise Rejection: Error: CssParser: parse error at position 240
```

### Screenshots

<details><summary>Screenshot:</summary>

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/30369714/161123254-c889fd21-1fec-4a34-9418-0a8f6e89f26d.png">

</details>

### Additional Information

I know that we need more investigation about this but the problematic `:xpath` rule is working well on Chrome and Firefox with AdGuard browser extension installed.

If I apply following filters into AdGuard Safari Extension, I can see that ad is blocked properly without any error.
Note that YousList includes `:xpath` rule first and I disabled manually.

```css
namu.wiki#?#div:not([class]):has(> table + .wiki-paragraph)
namu.wiki#@#:xpath(//article/h1/following-sibling::div[1]/following-sibling::div//div[count(*)>1]//div[count(*)>1][not(ancestor::div[count(*)>1]/ancestor::div[count(*)>1]/ancestor::article)]/div[.//ul/li|.//a[contains(@href,'/w/%EB%B6%84%EB%A5%98:')]]/following-sibling::div[.//div[contains(concat(' ',normalize-space(@class),' '),' namuwiki-toc-ad ')]|.//div[contains(concat(' ',normalize-space(@class),' '),' wiki-paragraph ')]]/following-sibling::div[count(.//*[count(img[starts-with(@src,'//w.namu.la/s/')]|img[starts-with(@src,'//ww.namu.la/s/')]|img[starts-with(@src,'data:image/png;base64,')])>1])>1])
namu.wiki#@#:xpath(//article/h1/following-sibling::div[1]/following-sibling::div//div[count(*)>1][not(ancestor::div[count(*)>1]/ancestor::article)]/div[1])
```

### Related

- https://github.com/List-KR/List-KR/pull/271
- https://github.com/AdguardTeam/AdGuardForSafari/issues/698

**Comment by zzebrum** [comment]
closed as [dup](https://github.com/AdguardTeam/SafariConverterLib/issues/36).
