### ISSUE TITLE
The rule, which exists in Base filter, is not applied

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#1970]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/113164#issuecomment-1080530295

That ads must be blocked by
`msn.com#$?#.swipenav > li:has(>a.nativead) { remove: true; }`   (https://filters.adtidy.org/ios/filters/2_optimized.txt)
When I add that rule to user filter - it works. **Do not** add the rule before visit the site.

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/114742
another case - `popjav.tv,hpjav.tv##.video-boxad` is not applied, but exists in optimized Base filter.

**Comment by ameshkov** [comment]
Is it reproducible with AdGuard for Safari or with AG for iOS only?

**Comment by Alex-302** [comment]
> msn.com

iOS only. With Safari for Mac I see related ads with disabled anvanced blocking only(checked just now).



Removed unnecessary exclusion for hpjav.tv Works fine now on iOS and Mac.

**Comment by Alex-302** [comment]
Not reproduced at the moment(no such ads)
