### ISSUE TITLE
[Question] Activity Log

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#1972]
Hi. 

I am using AdGuard Pro and NextDNS as my main DNS. Also, I have no DNS blocking list within AG DNS. 

In NextDNS page log I can see obviously all my blocked requests. 
In AdGuard Pro log section there are only few blocked requests, much less that you can find on NextDNS account page. 

Why is there such difference between those two logs? 
AdGuard should show everything or nothing but why only some? Any idea?

Thanks.

**Comment by zzebrum** [comment]
@Quorum75 sorry for the late reply! The situation you described is most likely because AdGuard cannot recognize by implication that the request has been blocked by NextDNS.
