### ISSUE TITLE
Filters update error

### ISSUE THREAD

**Issue by OOOHA** [AdguardTeam/AdguardForiOS#1973]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  4.3.3(947)
- **Device model and storage size:**
 iPhone 13 Pro 128GB
- **Operating system and version:**
ios 15.4.1
- **Browser or App:**
App

### Expected Behavior

Filters update successful

### Actual Behavior

Filters update error

### Logs
[AdGuard_logs.zip](https://github.com/AdguardTeam/AdguardForiOS/files/8473632/AdGuard_logs.zip)

**Comment by OOOHA** [comment]
And there's a additional issue about the statistics graph on the home page seems wrong.
![20220412_142814000_iOS](https://user-images.githubusercontent.com/45551120/162985557-212dcff7-aeae-4871-aa86-ddbcdda982d1.png)
![20220412_142809000_iOS](https://user-images.githubusercontent.com/45551120/162985581-0f6854d1-a9d3-4e43-a8e0-725fbda23738.png)
![20220412_142800000_iOS](https://user-images.githubusercontent.com/45551120/162985597-c88dbdc0-c016-41a2-8e32-927337647bba.png)

This is just no way.

**Comment by maxikuzmin** [comment]
@OOOHA tell me, is the question still relevant?

**Comment by OOOHA** [comment]
> @OOOHA tell me, is the question still relevant?

It's fixed.
In v4.4.0 I still got the same error so I reinstall it again.
It seems to be fixed recently.
I'm still monitoring.

**Comment by maxikuzmin** [comment]
@OOOHA great news! The question is closed
