### ISSUE TITLE
is there a way to create an "open in adguard" link for dns filters?

### ISSUE THREAD

**Issue by DetachHead** [AdguardTeam/AdguardForiOS#1976]
### Problem Description
i know you can create a link to open the adguard app with a `abp:subscribe?location=https://site.com` url, but that takes you to the safari section. is there a way to make a link that opens to the dns filters instead?

### Additional Information
[my filter lists](https://detachhead.github.io/ublock-filters/) includes one that's only intended to be used as a dns filter (the "apple cert revokes" one), it's useless if it's added as a safari filter

**Comment by zzebrum** [comment]
@DetachHead unfortunately, your request can't be implemented.
