### ISSUE TITLE
"Narwhal" app

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#198]
https://itunes.apple.com/us/app/narwhal-for-reddit/id845422455?mt=8
![image1](https://cloud.githubusercontent.com/assets/15856304/19639249/56061cfc-99e0-11e6-830e-c92a20cf476f.png)

logs: 1436166

**Comment by Alex-302** [comment]
@evgeniy-ADG 
what is the ad system? Looks like facebook ad choices.

**Comment by gshumihin** [comment]
I didn't faced this banner yet.
<details>
![slack for ios upload-4](https://cloud.githubusercontent.com/assets/8577547/19653422/26f760a0-9a1d-11e6-9b28-c0570a2d253b.jpg)
</details>

But here's log: 
[narwhal.saz.txt](https://github.com/AdguardTeam/AdguardForiOS/files/548358/narwhal.saz.txt)

**Comment by jo2dan23** [comment]
@gshumihin  what is the program u use to get that log?

**Comment by gshumihin** [comment]
Fiddler

**Comment by evgeniy-ADG** [comment]
Can't reproduce it, too. So I asked for logs, user provided another set of logs here: 1436166

**Comment by evgeniy-ADG** [comment]
The same issue here: **1434752**
User says it happens on mobile connection only.

**Comment by gshumihin** [comment]
Tried both connections. Result for me still same: no ads.

**Comment by Alex-302** [comment]
look for graph.facebook.com in the log and graph.facebook.com/network_ads in Fiddler.

**Comment by gshumihin** [comment]
There's no graph.facebook.com in the log for me.

**Comment by Alex-302** [comment]
@gshumihin check in the DNS log at the same time when you launch this app.

**Comment by gshumihin** [comment]
Did it. There is no graph.facebook.com neither in DNS log nor in fiddler's one.

**Comment by rhett121** [comment]
The ad are coming from mpx.mopub.com I get them every day and it shows up in the logs. Mopub is an ad serving network and I've tried just making a blanket block of ||*mopub.com* but it doesn't do anything for the DNS. I can repeat this issue any time I go online and it is different ads sometimes but always the mpx.mopub.com that isn't getting blocked.

**Comment by Alex-302** [comment]
Thanks, added
```
||mpx.mopub.com^
```

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/20193175/897f66b6-a795-11e6-9301-27a6dc08ecaf.png)

new ad appears. the previous one was fixed

**Comment by Alex-302** [comment]
@evgeniy-ADG ёлки, ну просите время указывать. Больше 5000 строк.

@gshumihin можешь фидлером лог записать?

**Comment by rhett121** [comment]
The time is at the top of the screenshot. It was 3am. I took the screenshot and immediately posted the bug so it should be one of the few that are at 3am. Thanks.

Время указано вверху экрана- 3 утра. я сделал скриншот и сразу же запостил баг. Так что он должен быть одним из немногих, размещенных в 3 утра. Спасибо за помощь.

**Comment by Alex-302** [comment]
@rhett121 скрин может быть и старым)
В логе ничего подозрительного не заметил. Попробуйте с выключенным интернетом проверить(два варианта - выключением в настройках, и по возможности с включенным интернетом но вне зоны покрытия). Возможно баннер встроен, или загружается с основного домена, который нельзя блокировать.
Какой адрес открывается при нажатии на баннер?

**Comment by ameshkov** [comment]
Кстати на втором скриншоте по ходу баннер другой рекламной сети.

На первом светится рекламная отметка (то ли adchoices, то ли admob, надо тапнуть проверить чей баннер). А на втором никаких отметок не видать.

**Comment by evgeniy-ADG** [comment]
1436166 - вот тут еще логи и скрины, посмотрите, пож-та.

**Comment by Alex-302** [comment]
@ameshkov 
> На первом светится рекламная отметка (то ли adchoices

днсофейсбучную рекламу не заблокировать по ДНС, фейсбук сломается.


@evgeniy-ADG 
> 1436166 - вот тут еще логи и скрины, посмотрите, пож-та.

Опять время не указано. Больше пяти тысяч строк там.

**Comment by rhett121** [comment]
Я не против того, чтобы сломать ФБ. Я им не пользуюсь. Вообще.

**Comment by Alex-302** [comment]
Зато другие миллионы пользователей против. Нормально заблокировать возможно только в Дроиде. У иОС скудные возможности в этом плане(т.е. это не ограничение самого Адгарда).

**Comment by ameshkov** [comment]
Ну вообще надо сказать, что в будущей версии появится возможность использовать пользовательский фильтр для блокировки ДНС-запросов.

Вот тогда-то и можно будет спокойно у себя заблокировать фейсбук, а других пользователей это не затронет.

**Comment by Alex-302** [comment]
о, крайне полезная функция

**Comment by vozersky** [comment]
obsolete
