### ISSUE TITLE
Beta 4.4.0 deleted everything 

### ISSUE THREAD

**Issue by maciboy** [AdguardTeam/AdguardForiOS#1983]
With 4.4.0 beta (via TestFlight) ALL my settings were deleted and the app was reseted as if I newly installed it!

iPhone 13 Pro
iOS 15.4.1

**Comment by maciboy** [comment]
Sh**, you are right, the app is resetting every time after closing, not only once after the update 😭 (since the iOS can’t export and import settings, this is quite annoying)

**Comment by michael1900** [comment]
Seems that the support/update for the ios adguard app has been a bit slowed down :(

**Comment by wh1terabbit91** [comment]
I just reinstalled the previous version in testflight again for now until this gets fixed

**Comment by AidanGee7** [comment]
Same issue for me, all settings/data gets reset every time you close and re-open the app.

Version 4.4.0 (1) on iOS 15.5.

**Comment by maciboy** [comment]
Seems to be fixed with newly released beta (952).
Updating from 4.3.3 was fine.

**Comment by wh1terabbit91** [comment]
Yup i just updated back to the most recent version after i reinstalled an old build. All my settings are and lists are normal. I just need to remember all the filter lists i was using lol. Theres a lot i don't remember

**Comment by ameshkov** [comment]
Sorry for that issue, it's been resolved in the new beta:(
