### ISSUE TITLE
Native DNS is not operating

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [AdguardTeam/AdguardForiOS#1987]
The dashboard of AdGuard for iOS Pro states that Native DNS is not operating, when it's selected.

![image](https://user-images.githubusercontent.com/95468948/167251649-e4383fee-f46c-4948-b5e5-b4f6a94da446.png)
![image](https://user-images.githubusercontent.com/95468948/167251651-bba37bf1-aa2d-48a5-9667-af2e338dfafc.png)
![image](https://user-images.githubusercontent.com/95468948/167251653-bef377e6-3905-4f69-8111-dbb086672432.png)
![image](https://user-images.githubusercontent.com/95468948/167251655-6ed5a140-85f6-48f2-a9e4-df32adf976b1.png)

**Comment by ameshkov** [comment]
You should select "AdGuard Pro" DNS profile. You've selected your manually crafted AdGuard Home profile instead.

**Comment by ameshkov** [comment]
@gGkAC3qfszbdViFkw4Fk9ooS2u could you please try the v4.4.0's AdGuard implementation? The issue with the network change should be gone now. Please let us know if it's okay now.

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
> @gGkAC3qfszbdViFkw4Fk9ooS2u could you please try the v4.4.0's AdGuard implementation? The issue with the network change should be gone now. Please let us know if it's okay now.

Thanks for answering the question, it still seems a bit ambiguously written - but as long as it's operating as it's meant to.

As for the network issues, they seems to be resolved when using AdGuard for iOS's DNS implementation.
This was testing by moving out of range of my wifi router, and experiencing the internet still working.
