### ISSUE TITLE
[BUG] Popups not correctly blocked.

### ISSUE THREAD

**Issue by michael1900** [AdguardTeam/AdguardForiOS#1988]
iOS: 15.5
AdGuard 4.4.0

Some stream in this site: https://streamgoto.me/a/ Depends on stream, there are many.

Try this stream for example http://streamgo.to/ud_1 Look how many **adfpoint.com**, **anduvayacaqmx.com**, **tiendeo.it** popups appear!

I mane a video to show you the problem: https://youtu.be/VtSJbIpV-2M
**_Using AdGuard PopupBlocker script with Macaque extension and script works._**

I haven't this problem with adguard on mac.

iOS: 15.5
AdGuard 4.4.0

**Comment by michael1900** [comment]
UP

**Comment by maxikuzmin** [comment]
@michael1900 when I click on Watch, I am watching the event and no popup window opens in both OS. Could you please elaborate on which popups you are talking about? Is it possible to attach a link to the video?
But I also noticed that with AdGuard enabled, the video does not play on this site (Mac OS). Do you have this problem?

**Comment by michael1900** [comment]
About first question: it depends on which events, because the sources of events are different and also their behaviour.
About second: with adguard enabled i can see sometimes the video, it starts automatically sometimes, depends always from source.

For example: try this now http://streamgo.to/nb_3 
With adguard on mac video starts automatically and no popup appears, on ios i need to click on plau button but before video starts i have many popups opened like adpoint.com, gearbest popup, etc..

For example with other http://streamgo.to/nb_6 i have popup on both platforms.

**Comment by maxikuzmin** [comment]
@michael1900 I'm not getting popups on both platforms. Can you record a video and attach it here? Or send a link to it

**Comment by michael1900** [comment]
The adguard devs and support are still with us?

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
> > @michael1900 I'm not getting popups on both platforms. Can you record a video and attach it here? Or send a link to it
> 
> 
> 
> Done: https://youtu.be/VtSJbIpV-2M
> 
> 
> 
> https://streamgoto.me/a/
> 
> https://livefootball24.com
> 
> 
> 
> 

I could not replicate this.

Your pop up's should be getting blocked both by Safari's inbuilt pop up blocker, enabled in Settings > Safari, and by AdGuard.

Ensure you have AdGuard setup correctly, and specifically check that the annoyances filter is enabled as this is what blocks the pop ups from AdGuard.See the below images.

![image](https://user-images.githubusercontent.com/95468948/169772891-45fef58f-cd3e-45d1-8ba0-625aa7ac0cd7.png)
![image](https://user-images.githubusercontent.com/95468948/169773128-27a6d22c-b608-400c-bc4d-ca7801848414.png)
![image](https://user-images.githubusercontent.com/95468948/169773160-ef8a08ab-8523-42e3-824a-bbe4979c6c49.png)

As for the developers - yes, they're still around. You check check the activity in all the other projects going on within AdGuards GitHub. Sometimes it just takes time to respond.

**Comment by michael1900** [comment]
Popup problem is when you try to watch some streams like this: http://streamgo.to/la_1

Try and click on Play button. I have popup

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
> Popup problem is when you try to watch some streams like this: http://streamgo.to/la_1
> 
> 
> 
> Try and click on Play button. I have popup

I was able to reproduce it. I have raised the issue [here](https://github.com/AdguardTeam/AdguardFilters/issues/119613), it should be resolved soon.

**Comment by michael1900** [comment]
Try this stream for example http://streamgo.to/32_1 Look how many adfpoint popup appear!

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
> Try this stream for example http://streamgo.to/32_1 Look how many adfpoint popup appear!
> 
> 
> 
> https://youtu.be/VtSJbIpV-2M
> 
> 

This website shouldn't show any pop-unders now, it's been attended to by the filters team.

**Comment by michael1900** [comment]
> > Try this stream for example http://streamgo.to/32_1 Look how many adfpoint popup appear!
> > https://youtu.be/VtSJbIpV-2M
> 
> This website shouldn't show any pop-unders now, it's been attended to by the filters team.

Still all adfpoint popups. 
http://streamgo.to/8b_1

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
> > > Try this stream for example http://streamgo.to/32_1 Look how many adfpoint popup appear!
> 
> > > https://youtu.be/VtSJbIpV-2M
> 
> > 
> 
> > This website shouldn't show any pop-unders now, it's been attended to by the filters team.
> 
> 
> 
> Still all adfpoint popups, also these https://snammar-jumntal.com/1f773d50-24c4-417f-a4b4-c9b8b06d5bbd?websiteid=4761337&quality=3&categoryid=136&country=IT&formfactorname=Smartphone&campaignid=7259967&campaignname=IT%20IOS%20409&screenresolution=1024x600&impressionid=858289522&bid=0.000500000
> 
> 
> 
> http://streamgo.to/8b_1
> 
> 
> 
> we need a way to block these fucking adfpoint and similar popups

https://github.com/AdguardTeam/AdguardFilters/issues/119864

**Comment by michael1900** [comment]
> > > > Try this stream for example http://streamgo.to/32_1 Look how many adfpoint popup appear!
> > 
> > 
> > > > https://youtu.be/VtSJbIpV-2M
> > 
> > 
> > > 
> > 
> > 
> > > This website shouldn't show any pop-unders now, it's been attended to by the filters team.
> > 
> > 
> > Still all adfpoint popups, also these https://snammar-jumntal.com/1f773d50-24c4-417f-a4b4-c9b8b06d5bbd?websiteid=4761337&quality=3&categoryid=136&country=IT&formfactorname=Smartphone&campaignid=7259967&campaignname=IT%20IOS%20409&screenresolution=1024x600&impressionid=858289522&bid=0.000500000
> > http://streamgo.to/8b_1
> > we need a way to block these fucking adfpoint and similar popups
> 
> [AdguardTeam/AdguardFilters#119864](https://github.com/AdguardTeam/AdguardFilters/issues/119864)

Maybe also AdGuard PopupBlocker must be updated?

**Comment by michael1900** [comment]
> > > > Try this stream for example http://streamgo.to/32_1 Look how many adfpoint popup appear!
> > 
> > 
> > > > https://youtu.be/VtSJbIpV-2M
> > 
> > 
> > > 
> > 
> > 
> > > This website shouldn't show any pop-unders now, it's been attended to by the filters team.
> > 
> > 
> > Still all adfpoint popups, also these https://snammar-jumntal.com/1f773d50-24c4-417f-a4b4-c9b8b06d5bbd?websiteid=4761337&quality=3&categoryid=136&country=IT&formfactorname=Smartphone&campaignid=7259967&campaignname=IT%20IOS%20409&screenresolution=1024x600&impressionid=858289522&bid=0.000500000
> > http://streamgo.to/8b_1
> > we need a way to block these fucking adfpoint and similar popups
> 
> [AdguardTeam/AdguardFilters#119864](https://github.com/AdguardTeam/AdguardFilters/issues/119864)

http://streamgo.to/ud_1

**Comment by michael1900** [comment]
http://streamgo.to/hd_1 look how many adfpoint.com, anduvayacaqmx.com, tiendeo.it popups appear!

@Chinaski1 @Stillness-2 @sfionov

**Comment by maxikuzmin** [comment]
@michael1900 we're looking for a solution

**Comment by jellizaveta** [comment]
@michael1900 Fixed, filters update should be available in 1-2 hours. Feel free to mention me if the problem appears.

**Comment by zloyden** [comment]
One important point - when you update filters, do not close the app for 1-2 minutes.
After that, check the site.

**Comment by michael1900** [comment]
> @michael1900 Fixed, filters update should be available in 1-2 hours. Feel free to mention me if the problem appears.

> One important point - when you update filters, do not close the app for 1-2 minutes.
> After that, check the site.


Hi guys thank you, the situation is better now but sometimes like in these 2 streams, also if you click in one of the black part around the Play button: 
**http://streamgo.to/sb_1** and **http://streamgo.to/34_1**
Look how many now different popups may appear: **c.adsco.re, it.gearbest.com, juvcsgdf.com, vfqycsfycr.com, snammar-jumntal.com, placebonusextra.com, choosetreats.com, smarttimeliness.com, btcsquare.net**

I think we need to solve also these, i dont know if there will be other different the next time i will try. We should block the source of these fucking ads popups. i don't know if the PB from adguard needs to be update also. Because for example this issue: https://github.com/AdguardTeam/PopupBlocker/issues/270 is very similar to mine.

I need to open an issue also in popup blocker page? Can you guys advice me? Thank you! Please advice me if must open an issue also there in PopupBlocker git page. Thank you!

**Comment by michael1900** [comment]
UP!

**Comment by maxikuzmin** [comment]
@michael1900 we study the problem

**Comment by jellizaveta** [comment]
@michael1900 In AdGuard for Safari a race condition is possible. This means that the scriptlet may not have time to load before the script is executed. I have updated and fixed the rules. Please check filters update in 1-2 hours. If the popups reappear, please open the task in the relevant AdGuard Filters repository.
