### ISSUE TITLE
[FEATURE REQUEST] Sync backup with icloud.

### ISSUE THREAD

**Issue by michael1900** [AdguardTeam/AdguardForiOS#1991]
Hi again, sorry but i can't find an option to backup for example on icloud or export the settings. Where is this option located? Thanks

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
> Hi again, sorry but i can't find an option to backup for example on icloud or export the settings. Where is this option located? Thanks

The only settings you can export are the user rules, and allowlist.

![image](https://user-images.githubusercontent.com/95468948/169770638-c6a5911a-e42c-4d99-99a3-7e7d077ec2d5.png)

As for iCloud backup data, [here's Apple's official document](https://support.apple.com/en-au/HT204215) on accessing backup data.

**Comment by zzebrum** [comment]
closed as dup #479
