### ISSUE TITLE
Protection page gives no indication that there may be subpages when tapping on the first 3 options

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#1994]
In iOS, all pages that have further settings will indicate with a '>', telling the user that there may be more settings.
If a switch is required to enable that setting, it should be shown when the subpage is tapped.

On the Protection page, the first 3 options on the page show no indication that there will be more user facing settings if tapped. It only shows that there is something to enable.
On iOS you'll never see this done. As an example, view any of the menus within the Settings.

Note that this image alone isn't indicative of the only place this occurs, and happens in many places throughout the app.

![image](https://user-images.githubusercontent.com/95468948/170911099-9fb96c7c-ecc7-4a7c-842e-f8833165f24c.jpeg)

Below is a good example of how it should look.
We can clearly see what can be enabled, and what has further options that can be enabled when another page is opened.
We can also tab the Enabled area, and it won't take me to a mystery subpage.
![image](https://user-images.githubusercontent.com/95468948/170911918-d82d2cf4-ff96-4e47-b4a6-2a8104b30bf9.png)

**Comment by mozartinio** [comment]
@gGkAC3qfszbdViFkw4Fk9ooS2u Thank you for your comment!
Actually we are planning to change it in a way it supposed to be (design already exists need a time to develop it). Check the updates! Hopefully very soon it will happen.
