### ISSUE TITLE
Consider a more elegant way to show filter updates/conversions

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [AdguardTeam/AdguardForiOS#1995]
When tapping the filter update button in the top right, it shows a white bar down the bottom, showing some text to give the status of the filter update which feels out of place in the overall design of the app.

![image](https://user-images.githubusercontent.com/95468948/170912659-e55df22d-66d0-4e97-9184-54e58917381f.png)

Consider using Apple's iOS Human Interface Guideline recommendations using an alternative such as the favoured progress bars.

https://developer.apple.com/design/human-interface-guidelines/ios/controls/progress-indicators/

**Comment by mozartinio** [comment]
@gGkAC3qfszbdViFkw4Fk9ooS2u 
Hello! In the future builds we will surely change it but now we have more prioritized things to do. Thanks for your suggestion!
