### ISSUE TITLE
Bring 3 dot menu (kebab) in-line with iOS expectations

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#1996]
The 3 dot menu (kebab) gets shown on the Safari user rules page vertically which represents something you'd be more accustomed to see on AndroidOS.

In iOS, this is usually presented horizontally, for example see the Photos (or GitHub) app.
This is reinforced, as when you tap on the 3 dot menu for both these apps, they show what's called a context menu.

![image](https://user-images.githubusercontent.com/95468948/170914242-74bf26f4-4fae-41bc-b1ad-a5a04ed6b060.jpeg)
![image](https://user-images.githubusercontent.com/95468948/170913994-792d462e-efda-4eb6-adb3-9aa56616bf6e.jpeg)

**Comment by mozartinio** [comment]
@gGkAC3qfszbdViFkw4Fk9ooS2u 
As for 3 dot menu that represents vertically its AdGuard App design. For now we have horizontal 3 dot menu in VPN App but very soon it will be vertical as well.
