### ISSUE TITLE
aA menu is missing the reporting tool button

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [AdguardTeam/AdguardForiOS#1997]
The outdated Safari action extension had a way to quickly report issues with websites, along with other functions.

The new Safari AdGuard extension in the aA menu appears to be missing this.

![image](https://user-images.githubusercontent.com/95468948/171086081-b08cba85-b517-4925-b4b0-8a87c6a2fbb8.png)
![image](https://user-images.githubusercontent.com/95468948/171086113-ff624af4-9fb2-4229-8193-e948fd3dbb64.png)

**Comment by mozartinio** [comment]
We need you to sent logs to us so we can figure out where is there a problem. (on latest AdGuard and IOS versions everything works fine - had a way to quickly report issues with websites, along with other functions as well)  @gGkAC3qfszbdViFkw4Fk9ooS2u

**Comment by mozartinio** [comment]
This feature is still working on the latest versions that is not forgotten function.

**Comment by mozartinio** [comment]
Here's what we need you to do:
AdGuard logs

    Open Settings --> General --> Turn Advanced mode on --> Advanced settings --> Turn Debug logs switch on;
    Reproduce the issue and remember the exact time when it happened;
    Disable "DNS Privacy";
    Open the settings --> Support --> Export logs;
    System popup will be opened --> Choose "Mail" app
    Enter apple@adguard.com as a recipient;
    Mention this issue number in the subject and add the time the issue was reproduced at.
    VPN for iOS
@gGkAC3qfszbdViFkw4Fk9ooS2u

**Comment by mozartinio** [comment]
So in new AdGuard version you can use that extension in the "share" menu -> "report an issue on this page".
