### ISSUE TITLE
Automatically fill GitHub username on issue reporting too in-app

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [AdguardTeam/AdguardForiOS#1998]
When reporting an issue from the AdGuard app, it pre-fills a lot of information from the app.

Could GitHub usernames also be included in this pr-fill data as an option?

![image](https://user-images.githubusercontent.com/95468948/171086720-c6efea56-f0d0-4363-9d01-ae571f5e8415.png)

**Comment by mozartinio** [comment]
Applications requires a link so it doesnt know your GitHub username. @gGkAC3qfszbdViFkw4Fk9ooS2u's
