### ISSUE TITLE
[BUG] DNS filtering does not work on iPhone hotspot via Wi-Fi

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForiOS#1999]
@grovolis commented on [Sat May 28 2022](https://github.com/AdguardTeam/AdguardForMac/issues/1073)

### Steps to reproduce

1. Enable DNS filtering in the app and select a DNS server (in my case AdGuard private DNS address)
2. Connect to iPhone wifi network (I just used my iPhone hotspot) 
3. Go on [ipleak.net](https://ipleak.net) and check DNS server IP
4. In my case I just see my mobile data ISP DNS

### Expected behavior

I should be able to use the selected DNS server even when connected via hotspot

### Actual behavior

In my case I just see my mobile data ISP DNS

PS. If I download the AdGuard profile for macOS, it works just fine even when connected to a hotspot. 

---

@Chinaski1 commented on [Tue May 31 2022](https://github.com/AdguardTeam/AdguardForMac/issues/1073#issuecomment-1142050494)

Hello there!

Please clarify, are you using your iPhone as a hotspot and connecting to it from your macOS? 
Did I understand you correctly?

---

@grovolis commented on [Tue May 31 2022](https://github.com/AdguardTeam/AdguardForMac/issues/1073#issuecomment-1142069864)

> Hello there!
> 
> 
> 
> Please clarify, are you using your iPhone as a hotspot and connecting to it from your macOS? 
> 
> Did I understand you correctly?

Hello, yes that is correct! Enable hotspot in iPhone settings, then connect my Mac to the iPhone hotspot via WiFi!

**Comment by grovolis** [comment]
> @grovolis  
> 
> 
> 
> I managed to reproduce the issue and moved it to AdGuard for the iOS section.
> 
> The developers will try in the near future to figure out what caused it.
> 
> 
> 
> Thank you for the report!

Perfect thanks! 🙌
