### ISSUE TITLE
Create a Safari Action Extension to whitelist (or remove from whitelist) the website

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#2]

**Comment by ameshkov** [comment]
Read about shared links first:
https://developer.apple.com/library/prerelease/ios/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html

**Comment by Stillness-2** [comment]
![tipa01](https://cloud.githubusercontent.com/assets/12689/10816115/804e4fcc-7e41-11e5-8aa0-37fce34866a7.png)

![tipa 02](https://cloud.githubusercontent.com/assets/12689/10816124/90bd02cc-7e41-11e5-8e90-c97a77c0a9f2.png)
