### ISSUE TITLE
Filter list grouping 

### ISSUE THREAD

**Issue by colinxs** [AdguardTeam/AdguardForiOS#2001]
As I under it the filter lists are partitioned into 6 groups (Ads, Social, etc) to get around iOS limits. These groups are chosen to be maximally independent to minimize duplicate work among the six content blockers which run independently.

Assuming I got that right, was any attempt at algorithmically (as opposed to manually) partitioning the rules ever made? Currently I'm over the limit for the Custom group, but if dived up amongst the other 5 groups there'd  be plenty of room.

Thanks!

**Comment by Versty** [comment]
@colinxs 
We discussed your suggestion and came to the conclusion this feature would be technically difficult to implement for now. 
So I can recommend you to review added custom user rules and delete outdated.
