### ISSUE TITLE
[BUG] White spaces between news in a specific site

### ISSUE THREAD

**Issue by michael1900** [AdguardTeam/AdguardForiOS#2002]
Hi. When i read this site: _**https://m.calcionapoli24.it/**_ i see always white spaces between news. I have this “problem” **ONLY** with this site.

Using always last AdGuard 4.4.0 on iOS 15.5. 

Hope that it can be fixed! Thanks

**Comment by Versty** [comment]
Hello, @michael1900! It would be great if you add more specific info about your in-app settings. Could you please fill in our [form](https://reports.adguard.com/new_issue.html) for better understanding and we'll investigate this issue.
