### ISSUE TITLE
Custom subscription lists

### ISSUE THREAD

**Issue by aleksandersumowski** [AdguardTeam/AdguardForiOS#2006]
### Prerequisites

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed

### Problem Description

I can't add custom subscription lists/content blockers to AdGuard. Example list I'd like to be able to add is:
https://www.i-dont-care-about-cookies.eu/abp/

But I'd like to be able to add any lists I come across

### Proposed Solution

Allow users to modify the subscription list

**Comment by Versty** [comment]
This list is pre-installed in the app already. Please open Protection tab, click on the **Safari protection: Filters: Annoyances** and activate **I don't care about cookies** filter.
In case you want to add more filters use same path but filter's category: Custom.
