### ISSUE TITLE
DoQ not working anymore.

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#2008]
NextDNS DoQ with port 8853 doesn't work anymore. 
NextDNS support suggested to change the port to 853 to get it work. 

Their answer. 
"try forcing the port to 853, seems like the AdGuard iOS application still have an old version of DoQ with the old standard port."

[NextDNS DoQ Supoort](https://help.nextdns.io/t/p8hwq4l/dns-over-quic-doesnt-work-anymore)

**Comment by Versty** [comment]
@Quorum75 
AdGuard DoQ protocols will be changed to the new version in the next update. The best solution right now is to force port 853 manually.

**Comment by Quorum75** [comment]
Since today the problem came back. Invalid stream...😡
