### ISSUE TITLE
Shazam app - sponsored ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#201]
![file_000](https://cloud.githubusercontent.com/assets/15856304/19724997/cbff2726-9b8b-11e6-9b20-04494cd2b68a.png)

1415775

**Comment by Alex-302** [comment]
@evgeniy-ADG I think it is impossible to block this ad by DNS. 
@gshumihin could you check it?

**Comment by jo2dan23** [comment]
Only blockable domain i found is analytics.vadio.com

**Comment by ameshkov** [comment]
So I guess they load ads from their own domain

**Comment by jo2dan23** [comment]
@ameshkov we should add analytics.vadio.com to dns filter

**Comment by Alex-302** [comment]
Added

**Comment by evgeniy-ADG** [comment]
Sponsored ad on the start page in the app.

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/26199953/bc33edc4-3bd4-11e7-96f3-19861d5fa330.png)

</details>

It's reproducible with the Standard Adguard DNS, do you need a log?

**Comment by Alex-302** [comment]
No, I need traffic, captured by Fiddler:
https://forum.adguard.com/index.php?threads/missed-ads-submission-rules.1879/
`2. How to capture traffic of the site or the application?​`
Could you do it? I can't reproduce that banner.

**Comment by vozersky** [comment]
obsolete
