### ISSUE TITLE
Reporting tool doesn't detect app configuration when opened from the web extension

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForiOS#2018]
### Issue Details

- **AdGuard version:**
  - 4.4.0
- **Device model and storage size:**
  - 
- **Operating system and version:**
  - iOS 15.6
- **Browser or App:**
  - Safari

### Expected Behavior

When loading the reporting tool from the Action menu or the web extension, they should work the same way.

### Actual Behavior

 When loading the reporting tool from the Action menu, the app configuration page automatically populates used filters from the AdGuard for iOS app.
When loading the reporting tool from the web extension, it does not.

### Screenshots

![image](https://user-images.githubusercontent.com/95468948/177871059-a63c458b-78dd-4227-88de-70969fda3575.jpeg)
![image](https://user-images.githubusercontent.com/95468948/177871073-185ffa9b-3ec0-4d3f-a358-832b8b3424ee.jpeg)

**Comment by Versty** [comment]
@jslawler Hi!

Memory used by extension menu strictly limited and not enought to transfer info about enabled filters from the AdGuard for iOS app. Perhaps we will find a better solution to implement this feature for the extension menu and add it in the next versions.

**Comment by jslawler** [comment]
@Versty does the second point allow you to increase your current limits at all?
This has been added in the latest iOS beta update

![image](https://user-images.githubusercontent.com/95468948/223841880-0bd71b33-ff74-4cce-be8e-7d859150c038.jpeg)
