### ISSUE TITLE
Love the extension! Do you know how to exclude subdomains from urls in content-blockers?

### ISSUE THREAD

**Issue by Daniyaldehleh** [AdguardTeam/AdguardForiOS#2019]
Hi there,

Hope you’re doing well,

Do you know how to exclude the subdomains from urls in content blockers?

Like: Block "www.youtube.com" but not "https://www.youtube.com/results?search_query". I've tried using "ignore-previous-rules" & regex but none seem to be working.

Thanks,
Daniyal

**Comment by Versty** [comment]
Hi @Daniyaldehleh!

The best way to exclude subdomains is to add User rules.
For example, in your case this rule `@@||https://www.youtube.com/results?search_query` will unblock the desired subdomain while YouTube.com remains blocked.

You can read more about AdGuard custom rules syntax [here](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#example-unblocking-an-address).

Regards,
Diana
