### ISSUE TITLE
Tango app ads and trackers

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#202]
adj.st (adjust.com subdomain, it is tracking)
ulink.adjust.com (tracking)
beap1.cb.g01.yahoodns.net (yahoo beap is used for ads)
beap.gemini.yahoo.com
adback.tango.me
adinfo.tango.me
admarketing.yahoo.net

Tango - Free Video Call, Voice and Chat by TangoMe, Inc.
https://appsto.re/us/iKbnw.i

**Comment by ameshkov** [comment]
@jo2dan23 good work, thank you!

**Comment by Alex-302** [comment]
Added.
