### ISSUE TITLE
Filters take a long time to update

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#2022]
I like to keep Adguard up to date, so I open the app once a day and wait for Adguard to download all the updates.

The issue is that it takes a long time.

I am on iPhone XS and iOS 15.5 (latest).

Is there anything from your end that can be fixed so it will check the filters versions before downloading or downloading the filters faster? I have 5 filters that need to check and download every time.

Thanks

**Comment by Versty** [comment]
@worldsdream Hi! 

The app is currently under the code refactoring process. We are working on the reduction of the filers update time. And if this issue still stands after next major release, please, create a new issue thread.

**Comment by worldsdream** [comment]
@Versty good to hear and good luck with development.
