### ISSUE TITLE
Block Smart App Banners

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForiOS#2023]
### Problem Description

 
When you have an app such as Reddit installed, and visit Reddit.com, you'll get a [smart app banner](https://developer.apple.com/documentation/webkit/promoting_apps_with_smart_app_banners) up the top of Safari.
<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/95468948/179204413-392e9ede-3177-4c8e-ad0c-2d8a53e5027d.png)
</details>

As far as I know, there is no way to block Smart App Banners with AdGuard.

### Proposed Solution

 On the App Store, there are apps that used to remove these Smart App Banners such as Unsmartiier which work by creating an extension that accesses every web page which looks like it prevents websites seeing an extension exists.

### Alternatives Considered

 I've seen that this has rejected many times in the AdGuard Filters repo due to being part of HTML, so I'm not sure if there's a more advanced method AdGuard can come up with.

I initially thought it might be able to be blocked on a script basis, however I dug up a [document ](https://github.com/dhowe/AdNauseam/wiki/Inline-script-tag-filtering#does-adblock-plus-support-this-filter-syntax) that states it inevitably ends up causing a large performance overhead.

**Comment by Versty** [comment]
@jslawler Hi! 

Great idea! We are planning to add this feature in the next versions.

**Comment by ameshkov** [comment]
@jslawler could you please check if adding this rule to User rules helps

`#?#meta[name="apple-itunes-banner"]:remove()`

It seems to be working on my side. If you confirm that it works, we'll add this rule to Annoyances filter.

PS: My initial thought about the necessity of removing that meta tag **before** the page is loaded by the browser seems to be wrong. Safari is capable of detecting that the meta tag is removed even after the page has been already loaded.

**Comment by ameshkov** [comment]
It seems that the rule helps when you don't have the corresponding app installed.

But if it is installed, it won't help :(

**Comment by ameshkov** [comment]
Ah, wait, the proper rule is `#?#meta[name="apple-itunes-app"]:remove()`

**Comment by ameshkov** [comment]
I've checked Unsmartifier and it uses the same approach:
```
    let appMetaTag = document.querySelector("[name='apple-itunes-app']");
    appMetaTag.remove();
```

And it suffers from the same issue, if an app is already installed, the smart banner is still there :(

**Comment by ameshkov** [comment]
Well, this is a method that's implemented inside the corresponding app (i.e. YouTube, Github, Reddit), we cannot interfere with it.

> Still, it would be useful to hide the Smart App Banner from the website side with the Annoyance filter, without heavily emphasising it's existance as to not confuse people into thinking it will block it all scenarios.

Yeah, we've added that rule to the Annoyances filter. Since this rule does the same as what Unsmartifier does, we can expect that it least handles it partly.
