### ISSUE TITLE
delicious-audio.com - the rules did not apply

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#2027]
@adguard-bot commented on [Sun Jul 03 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123408)

### Issue URL (Annoyance)
 [https://delicious-audio.com/bd-2-best-blues-driver-style-pedals-clones/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdelicious-audio.com%2Fbd-2-best-blues-driver-style-pedals-clones%2F)
### Comment
> Using the “Reader” option gets around the issue but when I tried to block in regular mode the warning disappears but the page is then blocked by something else and will not scroll.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/BU9acdw.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.4.0
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>Adblock Warning Removal List

---

@adguard-bot commented on [Thu Jul 07 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123408#issuecomment-1178144190)

### Issue URL (Anti Adblock Script)
 [https://delicious-audio.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdelicious-audio.com%2F)
### Comment
> Issue reported a few days ago and claimed fixed on github but it’s not working for me. In addition, the site owners appear to have disabled the ‘Reader’ option so there is no longer a workaround. The warning cannot be removed and nothing on the page including scrolling works after the warning displays. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/kOo68sC.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.4.0
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList, <br/>Peter Lowe's Blocklist<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances

---

@adguard-bot commented on [Sat Jul 09 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123408#issuecomment-1179471084)

### Issue URL (Anti Adblock Script)
 [https://delicious-audio.com/bd-2-best-blues-driver-style-pedals-clones/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdelicious-audio.com%2Fbd-2-best-blues-driver-style-pedals-clones%2F)
### Comment
> This is claimed to have been fixed twice but still isn’t working for me.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/yiL1rDU.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.4.0
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>Adblock Warning Removal List

---

@Alex-302 commented on [Wed Jul 13 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123408#issuecomment-1182893772)

Cannot reproduce with your settings. 
Please try to disable-enable content blockers in Safari settings and restart Safari, and check for filters update.
Do not close AdGuard window 30-60 seconds, because iOS will breaks configuration process.

---

@adguard-bot commented on [Thu Jul 14 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123408#issuecomment-1184885173)

### Issue URL (Anti Adblock Script)
 [https://delicious-audio.com/bd-2-best-blues-driver-style-pedals-clones/#POPULAR_BLUES_DRIVER_MODS_USED](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdelicious-audio.com%2Fbd-2-best-blues-driver-style-pedals-clones%2F%23POPULAR_BLUES_DRIVER_MODS_USED)
### Comment
> - [ ] Adguard warning will not appear when page loads unless you start scrolling.
> - [ ] After you start moving the page it still takes 20 to 30 seconds for the warning to appear.
> - [ ] After another 20 to 30 seconds any page scrolling and access to any of the site links is blocked.
> - [ ] If you reload the page the whole process starts again.
> - [ ] This has happened on all the website pages of this site that I have tried to load.
> - [ ] I was having the same problem on my Macbook though when I tried earlier today it was okay (though I didn’t report the issue from my Macbook.)
> - [ ] I followed your suggestions to fix on IOS but it hasn’t helped. This website seems quite clever at making it seem there is no problem as there is a delay before the warning appears, giving the impression it’s not going to appear - but it still does appear and won’t allow me to use the site once I start moving around.
> I hope this helps!

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/zeFDKmO.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.4.0
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList, <br/>Peter Lowe's Blocklist<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances

---

@Alex-302 commented on [Fri Jul 15 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123408#issuecomment-1185427525)

Still not reproduced.
Please test: `delicious-audio.com#%#//scriptlet("abort-on-property-read", "adBlockerState")`

---

@fazer1k143 commented on [Sat Jul 16 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123408#issuecomment-1185993193)

When you say ‘test’ I assume you mean as an adguard user rule, which I have now tried and I still get the message appear and the page still locks. I think I have now managed to block the box that appears (which I could not before because the page still locked). Okay that hasn’t worked either. I guess I may just have to avoid the site. 

---

@Alex-302 commented on [Wed Jul 20 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123408#issuecomment-1190003627)

I don't know why both rules are not working on your device. Which iOS version?

---

@fazer1k143 commented on [Wed Jul 20 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123408#issuecomment-1190698581)

Took a while to find but it’s IOS 15.5.

I have more lists enabled  than previously indicated but could not remember how to access that section. I can confirm now though, that the only lists I do not have enabled are Fanboy’s anti-third party fonts list and the filter which would remove search engine ads and self promotion.

On re-checking just now I can confirm the problem still exists.

---

@Alex-302 commented on [Fri Jul 22 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123408#issuecomment-1192453801)

@fazer1k143 Please test with AdGuard Base + AdGuard Annoyances only.
Do not close AdGuard window 30-60 seconds, because iOS will breaks configuration process.

---

@fazer1k143 commented on [Sat Jul 23 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123408#issuecomment-1192963086)

@Alex-302 
Just tested with those two filters only enabled, and additionally with the user rule you said I should try earlier also enabled, and the result is the same as previously in both cases - I get the warning and my access to the site is blocked. (I waited until adguard had finished re-configuring.)

---

@fazer1k143 commented on [Mon Jul 25 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123408#issuecomment-1193583246)

@Alex-302 
An addition to my last message - I have now updated my IPad to IOS 15.6 and there is no change to this issue.

**Comment by Alex-302** [comment]
Antiadblock popup must be blocked by the rules from AdGuard Anoyances filter:
```
delicious-audio.com#$##cboxOverlay { display: none!important; }
delicious-audio.com#$##colorbox { display: none!important; }
delicious-audio.com#$#body[style="overflow: hidden;"] { overflow: visible!important; }
```
They work on out devices, but not on @fazer1k143 's device.

Antiadblock popup opens after ~15 seconds.

**Comment by Versty** [comment]
@Alex-302 
Unfortunately, it doesn't reproduce on my side either.

**Comment by Alex-302** [comment]
@fazer1k143 Hi. Please check for filters update and check this issue again.

**Comment by fazer1k143** [comment]
Hi Alex,

Thanks for your email.

I was going to post on the new thread but found it has been closed quite quickly by someone saying (I believe) that they could not reproduce the fault - somewhat confusing!

Since receiving your email I have updated the Adguard filters on both my Macbook and IPad. The fault still exists on my IPad, which is what I expected to be honest. However, my Macbook, which was okay last time I checked is now exhibiting the same problem again. Are the Delicious Audio website management just exceptionally good at preventing the use of ad-blockers, do you think? Anyway, sorry to have to inform you that neither of my devices can access the site for more than a few (say 15 to 20) seconds without having access denied - the page just freezes.

If be happy to help if I can with testing new rules etc. if that would help. For the time being, I haven’t been using the site as I’m not willing to disable Adguard for them (their loss really if they wish to push site visitors away!). I’m in the UK by the way so I don’t know if that could affect anything i.e. why some people in your area are not denied access yet I have problems. 

Best wishes,

Paul.

**Comment by Alex-302** [comment]
@fazer1k143 Hi. It seems this is another problem now.
Previously, the rules were in optimized filters, but not applied. Now the rules were auto-excluded from optimized version of Base filter. Added a new rule + directives to avoid removing of previous rules.
Please check for updates and do not close AdGuard window during ~30-60 seconds during this process.

**Comment by fazer1k143** [comment]
Hi Alex

I’ve rechecked again on both my devices.

My Macbook appears to work perfectly on both the site home-page and several sub-pages I tested.

My IPad no longer responds to accessing the home-page, which is great and made me believe at first the problem might be fixed. However, on accessing another site page (marked The Best Klon Centaur Clones) I received the familiar warning after 15-20 seconds and the site then froze completely after a few seconds more. In contrast I re-entered the site and tried another link (The Mad Professor, The Green Wonder) and did not have a problem. The link to Strymon Lex v2 also works okay. I then had another go with the Klon Clones page and received the warning and was then frozen out again.

I hope you find this result less confusing than I do!

Best wishes,

Paul

**Comment by Alex-302** [comment]
@fazer1k143 Please check for updates again. A bit changed the rules.

**Comment by fazer1k143** [comment]
No change on  IPad my side. The Klon Clones page still recognises my use of adguard and freezes me out of the page. (I did wait for the adguard update to complete and restarted Safari).

**Comment by fazer1k143** [comment]
I could not send this email as it was said to be “too large” with the attachments. 

I believe I see what is happening now. On further investigation it seems that only pages with written information such as the site pedal guides trigger defensive action against me for using adguard. When I click on pages that really only then allow you to investigate shopping  links no defences against me as an  adguard user are triggered. Would that make sense? Anyway, I hope this helps. 

I have attached some images from pages that did trigger the adguard defence.

**Comment by fazer1k143** [comment]
![3A291968-DBA9-49B7-9736-3A4D05D5E5BA](https://user-images.githubusercontent.com/109391397/184650656-d7cdcec9-e28e-48b5-95cd-37db9003690a.png)
![E0A0955E-D6C3-43F3-B254-6BB11945279C](https://user-images.githubusercontent.com/109391397/184650678-c8bb1b60-7a81-4c89-aa0f-8516fc9e8e67.png)
![A568F8D9-A5F0-4724-97B9-48CEE53CBF3C](https://user-images.githubusercontent.com/109391397/184650689-01778252-c66d-4880-95d8-93008a278788.png)

**Comment by fazer1k143** [comment]
I attempted to reply to this email with attachment images but received the message that it was too large to send. I have now posted the message and images to the site directly instead.

**Comment by Versty** [comment]
@fazer1k143 Let's find a reason the issue reproduces on your device only. Possibly, you have some uncommon settings enabled.
Could you send us logs using in-app option? 
Settings -> Leave feedback -> Make sure checkbox `Attach application logs` is marked 

In the description, please, mention the GitHub issue number `2027`.

**Comment by fazer1k143** [comment]
@Versty I attach logs, as requested. Please bear in mind that the pages which are affected have changed since the start of this issue (originally all pages were) and that my Macbook has also been affected differently throughout as described above. 
[Github 2027 AdGuard_logs.zip](https://github.com/AdguardTeam/AdguardForiOS/files/9365323/Github.2027.AdGuard_logs.zip)

**Comment by fazer1k143** [comment]
Posted directly to website in case attachments on email failed again. Thanks.

**Comment by fazer1k143** [comment]
@Versty Now I’m even more confused - the only link that triggered the response just now when I checked was this one (IPad used):
https://delicious-audio.com/best-uni-vibe-pedals-ultimate-guide/

**Comment by Versty** [comment]
@fazer1k143 Weird thing. 
So, the anti-adblock banner doesn't pop up on the main page [https://delicious-audio.com](https://delicious-audio.com)? 
But it pops up on the [https://delicious-audio.com/best-uni-vibe-pedals-ultimate-guide/](https://delicious-audio.com/best-uni-vibe-pedals-ultimate-guide/). And does not pop up on the [https://delicious-audio.com/bd-2-best-blues-driver-style-pedals-clones/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdelicious-audio.com%2Fbd-2-best-blues-driver-style-pedals-clones%2F) for now.
Please, correct me if I'm wrong.

**Comment by fazer1k143** [comment]
It is a very strange situation that I have found confusing all along.

The situation you describe was exactly right yesterday, and I checked several times to make sure. However, strangely enough I just tried accessing those links again today, several times, and nothing happened at all. Yesterday, I also tested with my Macbook again and received no anti-blocking response there. 

I’ve pretty much given up using that site now due to the annoyance it can cause. It seems as though the site web administration people are moving the goalposts for access requirement regularly though that makes no sense to me either, especially as  I seem to be the only one having this problem. In general adguard is great software and I have no problems on any other site I visit.

Did the logs I sent identify any issues?

**Comment by fazer1k143** [comment]
@Alex-302 
@Versty  I’m not sure whether you received the following  by email yesterday:

All the links I tried earlier today work okay including the ones below. However, I found a new one that doesn’t: https://delicious-audio.com/category/two-stage/

I retried after trying a few more links in-between and got the same result a second time.

I’m getting the same result today also.

**Comment by Alex-302** [comment]
I can't reproduce.
We use two solutions:
- CSS to hide popup and unblock scrolling
- scriptlet to break anti-adblock script.
On my macbook with AdGuard for Safari and on iOS applied the first solution.

**Comment by Versty** [comment]
@fazer1k143 Could you check the web pages behaviour with only AdGuard filters enabled? 

1. Please, disable every filter except for: 
    - AdGuard Base filter
    - AdGuard Mobile Ads filter
    - AdGuard Tracking Protection filter
    - AdGuard Social Media filter
    - AdGuard Annoyances filter
    - AdGuard Popups filter
    - AdGuard Mobile App Banners filter
    - AdGuard Other Annoyances filter
    - AdGuard Widgets filter

2. Wait for content blockers update to be completed 
3. Restart Safari 
4. Check if the issue still persists

**Comment by fazer1k143** [comment]
Hi Diana

I just spent approx 20 mins on the Delicious Audio site surfing around after enabling only the filters you have given below. Nothing yet has triggered the defensive response so I’m inclined to think (or at least hope) this has fixed the issue permanently. Thanks!

Have you identified the ‘offending’ filter yet (assuming that’s the problem)?

**Comment by Versty** [comment]
@fazer1k143 Awesome news! 
You are completely right, one of the filters interferes with the others and breaks the blocking. 
We have not yet figured out which one.

**Comment by fazer1k143** [comment]
Hi Diana

All the links I tried earlier today work okay including the ones below. However, I found a new one that doesn’t: https://delicious-audio.com/category/two-stage/

I retried after trying a few more links in-between and got the same result a second time.
