### ISSUE TITLE
Youtube app tracker

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#203]
video-stats.l.google.com

**Comment by ameshkov** [comment]
I recall these `.l.google.com` domains causing some issues in past.

Also I don't think we should block first-party tracking, this is YT app in the end.

**Comment by jo2dan23** [comment]
@ameshkov what about adding s.youtube.com then since it is in easy privacy. S.youtube.com is a constant tracking pixel thats keeps being requested when playing a youtube video

**Comment by ameshkov** [comment]
There is a huge downside though: it breaks your history in the YT app.

It was in our spyware filter previously, but we had to remove it due to lots of users complaints.

**Comment by jo2dan23** [comment]
Alright. Understood.
