### ISSUE TITLE
Scriptlet rule doesn't apply fast enough to block entry banner on webpage 

### ISSUE THREAD

**Issue by 88Va2wFDcYd1CT** [AdguardTeam/AdguardForiOS#2032]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [v] I am running the latest version
- [v] I checked the documentation and found no answer
- [v] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v4.4.0
- **Device model and storage size:**
  - iPhone 13 256gb
- **Operating system and version:**
  - ios 15.6
- **Browser or App:**
  - safari browser

### Expected Behavior

https://kb.adguard.com/en/ios/overview#advanced-protection-1
to adguard for ios With advanced protection,
scriptlet rule it should work

So https://meeco.kr/free/35700998 with anti adblock
when you visit the site,
works fine on windows
https://github.com/List-KR/List-KR in the filter
meeco.kr#%#//scriptlet("abort-current-inline-script", "$", ".adsbygoogle")
The rules should work.

### Actual Behavior

https://meeco.kr/free/35700998
anti adblock
with advanced protection
in ios safari
You cannot bypass

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Versty** [comment]
@88Va2wFDcYd1CT Hi! 
You have experienced common behaviour of scriptlets on iOS. They start to work later because of the strict limitations of Safari.
