### ISSUE TITLE
DNS-protection doesn't work in MTS network

### ISSUE THREAD

**Issue by AlexTheFive** [AdguardTeam/AdguardForiOS#2036]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v4.4.0(954)
- **Device model and storage size:**
  - iPhone 11 Pro Max 64gb
- **Operating system and version:**
  - 15.6

### Expected Behavior

DNS-protection must block ads in applications and allow internet traffic in browser and in apps

### Actual Behavior

If DNS-protection is ON, all of internet traffic blocked. Browser and applications can't use internet

### Additional Information

iPhone works in MTS network. Problem with DNS-protection was appeared since 27/07/2022

**Comment by Versty** [comment]
Hi! @AlexTheFive 
Seems like you have been affected by regional wave of DNS bans. 
The best solution here is to change DNS server manually using **Add a custom DNS server** option. 
Depends on the server you were using add in the DNS server field: 
- AdGuard DNS ->  dns.adguard-dns.com
- AdGuard DNS Family Protection -> family.adguard-dns.com
- AdGuard DNS Non-filtering -> unfiltered.adguard-dns.com

Read more about the current [state of the AdGuard applications in Russia](https://adguard.com/ru/blog/adguard-vpn-russian-ban.html).
