### ISSUE TITLE
AdGuard not working!

### ISSUE THREAD

**Issue by Githubmaniak** [AdguardTeam/AdguardForiOS#2038]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  AdGuard for iOS v4.4.0
- **Device model and storage size:**
  -  iPhone 6s+ 32GB
- **Operating system and version:**
  -  15.6
- **Browser or App:**
  -  Safari

### Expected Behavior

Ads should be blocked normally.

### Actual Behavior

Adguard not working with ad blocker.  Re-installing the app and resetting it doesn't work.

### Screenshots

<details><summary>Screenshot:</summary>

![31CF5F7E-4A52-4E24-8235-3E380CD18057](https://user-images.githubusercontent.com/103377449/182631755-d6ea1ba0-9135-46f9-bccb-a963e45196e3.png)
![9EEA9899-DDEF-4F5F-B427-2B560D64BAC9](https://user-images.githubusercontent.com/103377449/182631733-83546276-f019-4bdc-88b3-352ba1bc5ec5.png)

</details>

**Comment by Versty** [comment]
@Githubmaniak Hello! 
Is this issue only occurring on naver.com?

**Comment by Githubmaniak** [comment]
@Versty Ads on all webpages are not blocked.

**Comment by Versty** [comment]
@Githubmaniak Seems like content blockers are disabled in the system settings.  
Could you check it for me? **Settings -> Safari -> Extensions** 
If so, please, enable all content blockers, it should help.

**Comment by Githubmaniak** [comment]
@Versty 
![597601D8-D759-4D01-92F6-B09B554E5B32](https://user-images.githubusercontent.com/103377449/182915957-d8ba6fb2-9917-4479-9c61-c8691ecb444a.png)

safari's content blocker is still on.  It seems like it was a temporary error.  Now everything works fine.

**Comment by Versty** [comment]
@Githubmaniak Awesome news! 
In case the issue returns, please reopen this thread.
