### ISSUE TITLE
Fully disable statistics function

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdguardForiOS#2039]
Hello,

please add a function to completely disable statistics🙏🏼

Thank you.
Best regards😙

**Comment by Versty** [comment]
@ammnt Hi!
We have discussed your suggestion. Statistics is an important function that helps users keep an eye on the utility of our app. From our perspective it would be incorrect to completely disable statistics, so we have no plans to implement this feature in the future versions.
