### ISSUE TITLE
Plants vs zombies ads

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#204]
www.ultraadserver.com 
abtest.swrve.com (says on the website: A comprehensive mobile marketing platform)

https://appsto.re/us/n5iPJ.i

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||abtest.swrve.com^
```

**Comment by jo2dan23** [comment]
Ultraadserver.com was missed

**Comment by Alex-302** [comment]
That's because no any comment for it. I thought is related to abtest.swrve.com.
Added.

**Comment by jo2dan23** [comment]
Oh,  im sorry. My bad.
