### ISSUE TITLE
TestFlight for AdGuard iOS has expired

### ISSUE THREAD

**Issue by tonyping** [AdguardTeam/AdguardForiOS#2040]
### Additional Information

The TestFlight for AdGuard iOS has just expired; will there be another build (even just with no changes would be fine), just to renew the testing period?

**Comment by Versty** [comment]
@tonyping Hi! 
New TestFlight builds for beta testers are deactivated due to the replacement of the developer account with a new one. 
Announcements in our social media about how to rejoin as a beta tester will appear be very soon. Please stay tuned.
