### ISSUE TITLE
Use root certificate in iOS to better block ads in all apps.

### ISSUE THREAD

**Issue by ItsX12** [AdguardTeam/AdguardForiOS#2041]
### Problem Description

In the iOS version of Adguard there is no option to use a certificate to filter HTTPS requests, while there is in the Android version. While I'm not an expert about using HTTPS filtering to block ads, I believe this should allow better filtering across all apps?

### Proposed Solution

Take advantage of Root Certificates for filtering in iOS. By doing this, filtering could be done on apps which have ads with encrypted connections like Youtube.

### Alternatives Considered

I checked out Luna VPN and they use Root Certificates to block ads, this is how I figured it might help filtering in Adguard. It seems to do the trick, however, the company behind Luna seems very shady.

**Comment by Versty** [comment]
@ItsX12 Agreed, it might be dangerous for your privacy to install certificates from an unknown non-trusted publisher. 
Side root certificates are strictly prohibited by Apple policy, so any app with the feature you suggest will be banned from the App Store.

**Comment by ItsX12** [comment]
Is this something you could add as a side app? For example the full android version of adguard isn't  avalible on the play store.

**Comment by Versty** [comment]
@ItsX12 Unfortunately, on Apple devices there is only one reliable way to install apps - via the App Store. Which is drastically differs from Android devices.
