### ISSUE TITLE
Naming the devices in user's account

### ISSUE THREAD

**Issue by most-intelligent** [AdguardTeam/AdguardForiOS#2042]
### Problem Description

I have multiple identical devices, such as several iPad Pros, but they all show up in my account as iPad Pro, and when I want to remove some of them, it's hard to tell which device is which

### Proposed Solution

In the client or account management page, add the function of naming devices for easy identification and management

**Comment by Versty** [comment]
@most-intelligent Hi! 
The @jslawler is totally right! You can rename any device in the licenses management tab.
