### ISSUE TITLE
rule doesn't work on instagram

### ISSUE THREAD

**Issue by DetachHead** [AdguardTeam/AdguardForiOS#2044]
the following rule to block sponsored posts on instagram does not work on iOS:

```
www.instagram.com##article:has(header span:has-text(/^Sponsored$/))
```

### Issue Details

- **AdGuard version:**
  - 4.4.0(954)
- **Device model and storage size:**
  - iphone 13, 128gb
- **Operating system and version:**
  - iOS 15.1.1

### Expected Behavior
sponsored post is blocked

### Actual Behavior
not blocked

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/57028336/184517218-8ba0406d-683d-48cf-94f8-62ce4c28a24d.png)

</details>

### Additional Information

tested this on desktop as well with the adguard firefox extension and the element was successfully blocked:

![image](https://user-images.githubusercontent.com/57028336/184517261-ebcbb17d-d8ba-41dd-b028-575a9ba8a3a9.png)

as far as i can tell, the html is the same in both cases.

**Comment by DetachHead** [comment]
it seems to work if you remove the `www.` from the domain but i don't understand why, because the full url is `https://www.instagram.com`

![image](https://user-images.githubusercontent.com/57028336/184517763-318516fd-9fc7-4a58-aaf9-134266317a45.png)

**Comment by Versty** [comment]
@DetachHead Hi!
Filters syntax is constructed as simple as possible, so rules get rid of the www part. 
Also in this case the rule must use an extended css selector. 
The proper rule would be `instagram.com#?#article:has(header span:has-text(/^Sponsored$/))`
You can read more about rules syntax and extended css selectors [here](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#extended-css-selectors).

**Comment by DetachHead** [comment]
@Versty 
> Filters syntax is constructed as simple as possible, so rules get rid of the www part.

is this to handle cases where websites could load either with or without the `www` subdomain? also, how come it only seems to do this on iOS but not on desktop?

> Also in this case the rule must use an extended css selector.
> The proper rule would be `instagram.com#?#article:has(header span:has-text(/^Sponsored$/))`

it seems to work without the `#?#`, is there any downside to using `##`?

**Comment by Versty** [comment]
@DetachHead 
No downside, and you're lucky it worked, but it may not. We use extended css selectors to rise the priority of the rule to make to work. 
For me, the rule works both with and without `www` on iOS.
