### ISSUE TITLE
Support IP address blocking

### ISSUE THREAD

**Issue by money-outlook** [AdguardTeam/AdguardForiOS#2045]
### Problem Description

ip filter can only block IP addresses that are included in the DNS resolution result, right? For example, if AAA.COM resolves to 3.3.3.3, and 3.3.3.3 happens to be in the ip filter, it can be blocked by the ip filter, but if I access 3.3.3.3 directly, it can't be blocked by AdGuard, right?

If AdGuard can't block the IP address, then many adware programs will access their servers directly by IP address, how can I solve this problem?

### Alternatives Considered

I remember DNSCloak seems to be able to block the direct access via IP address.

**Comment by Versty** [comment]
@money-outlook Hi! 
You are totally right, DNS filtration works like you described. 
Could you provide more details about the feature in DNSCloak that you are talking about?

**Comment by Versty** [comment]
@money-outlook Is this case still relevant?

**Comment by Versty** [comment]
@money-outlook Closed due to inactivity.
