### ISSUE TITLE
AdGuard in Share Menu doesn't appear on some websites

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForiOS#2046]
### Issue Details

- **AdGuard version:**
  - 4.4.1
- **Device model and storage size:**
  - iPhone 13 Pro
- **Operating system and version:**
  - iOS 15.6
- **Browser or App:**
  - Safari

### Expected Behavior

AdGuard appears in the Share Menu to report an app.

### Actual Behavior

AdGuard does not appear in the share menu to report an app.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/95468948/184782967-bb09cbd7-1e1e-4d92-a296-3193f39a8a7e.png)

</details>

### Additional Information

Affected Website [here](https://www.forbes.com/sites/abrambrown/2022/01/07/top-earning-tiktokers-charli-dixie-damelio-addison-rae-bella-poarch-josh-richards/?sh=254cbce43afa).

**Comment by Versty** [comment]
@jslawler Hi! 
Action extension in the share menu is an obsolete part of the app, which has been replaced by the new extension in the aA menu. `Report an issue` button also available in the new extension. Expand the menu of possible AdGuard actions to display the button.
