### ISSUE TITLE
Unable to login using AdGuard account in iOS 16.0

### ISSUE THREAD

**Issue by gabesean** [AdguardTeam/AdguardForiOS#2048]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

The issue has been present in all betas of iOS 16.0

I am unable to login to my AdGuard account using the "Use AdGuard account" login button through the app (I login through a normal email and password, not through a third-party service such as Apple or Google). When I try logging in, I get a notification saying that "You have successfully logged into your AdGuard account! The Premium version of AdGuard for iOS has been activated." This is not reflected inside the app. The app acts like I did not login at all.

- **AdGuard version:**
 4.4.1(959)
- **Device model and storage size:**
iPhone X 64gb
- **Operating system and version:**
iOS 16.0

### Expected Behavior

I expect to be able to login and have that reflected throughout the app, unlocking the premium features for me and such since I am paying for a yearly subscription.

### Actual Behavior

The login did not actually go through and no changes are reflected inside the app. I still get the "Get stronger with premium!" banner on the home tab as if I am not a paying customer.

### Additional Information

I have an active standard (Personal) license which I have used on the maximum of three devices, so no problem there. Am I the only one experiencing this issue?

**Comment by Versty** [comment]
@gabesean Hi! 
Probably, this issue is related to the beta version of iOS. 
Could you please provide logs from your device so we can take a look? 

1. Open Settings --> General --> Turn **Advanced mode** on --> Advanced settings --> Turn **Debug logs** switch on;
2. Reproduce the issue (login through a normal email and password) and remember the exact time when it happened;
3. Disable "DNS Privacy";
4. Open the settings --> Support --> **Export logs**;
5. System popup will be opened --> Choose "Mail" app
6. Enter `apple@adguard.com` as a recipient;
7. Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by gabesean** [comment]
Hello! Fantastic, I just sent it over. Thank you team for all the hard work! 😊

**Comment by Versty** [comment]
@gabesean Could you, please, try to login one more time in the AdGuard app, then open [adguard.com](https://adguard.com/en/welcome.html) in the browser, go to My Account tab and check if there is your device in the list?

**Comment by gabesean** [comment]
@Versty I just turned off iCloud Private Relay, then restarted my phone with Private Relay still off, logged into the AdGuard iOS app with my credentials (I also just turned 2FA on, so I too inputted the 6-digit code) and the same notification: "You have successfully logged into your AdGuard account! The Premium version of AdGuard for iOS has been activated" popped up but still, nothing at all happens, and no premium features are unlocked.

I logged into [adguard.com](adguard.com) and "iPhone" shows up at the top of the devices list with "Latest synchronization September 9, 2022", (after I unbinded the previous iPhone entry which is still the same iPhone I've had for years) but still, no luck at all. This is so weird...

**Comment by Versty** [comment]
@gabesean We have tried to reproduce this issue, but it works fine on our side. 
Probably the issue will be solved if you reset settings: General → Settings → Reset settings.
Then update the AdGuard application from the App Store to the latest version (4.4.3). Before logging in, please disable VPN if you use any.
