### ISSUE TITLE
No response hostnames in dns log

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#205]
Is it possible to remove the showing of dns domains that arent resolved? So the logs arent cluttered

**Comment by ameshkov** [comment]
As I remember, AG adds a record to the log right after we got the request and then updates it when response has arrived. @Stillness-2 is it so?

**Comment by jo2dan23** [comment]
@ameshkov sorry i meant the dns requests section in the app not when you export the tunnel log.

**Comment by Stillness-2** [comment]
@jo2dan23 No, at this moment. I think we can add such option on screen of the dns requests list .

**Comment by ameshkov** [comment]
It's just this information could be useful.. How cluttered is it?

**Comment by jo2dan23** [comment]
@ameshkov im just saying it would be easier to find dns requests when using the in app log so i dont see all the no response dns requests. If you know what i mean. I dont see a need for displaying them anyways. Kind of makes it harder to find stuff

**Comment by jo2dan23** [comment]
perhaps we could make it so there is a way to filter out the no response ones?
