### ISSUE TITLE
Unable to run the project locally

### ISSUE THREAD

**Issue by SaminathSafeHouse** [AdguardTeam/AdguardForiOS#2052]
I updated my details in the .env, .env.adguard and .env.pro files

Installed Ruby using **brew install ruby**

**Updated the following path in the .zshrc file**
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/usr/local/lib/ruby/gems/2.7.0/bin:$PATH"

**Ran the following commands**
sudo gem install bundler
bundle config set --local path '.bundle/vendor'
bundle install

When I run **bundle install**, I'm getting the following error
**bundle: cannot load destination package: err: exit status 1: stderr: go: go.mod file not found in current directory or any parent directory; see 'go help modules'**

Can someone please provide me the exact steps to compile the project and run it locally ? and help me debug the above mentioned issue ?

Thanks in advance

**Comment by artemiv4nov** [comment]
@SaminathSafeHouse hello!

I think you have some compatibility problems with your Go version. Please try to find out a solution to use suitable versions of Go and Ruby.

**Comment by SaminathSafeHouse** [comment]
Thanks @artemiv4nov 
Updating the Ruby version solved the bundle issue :)
