### ISSUE TITLE
Cannot fill request for new type of ad blocking because screenshot is required.

### ISSUE THREAD

**Issue by CapSel** [AdguardTeam/AdguardForiOS#2053]
How to make a screenshot of redirect? Should I make a screenshot of page that is redirecting or screenshot of page that is blocked by adguard (correctly) that first page redirects to right after is done loading?
It doesn't matter if I enable adguard or not - I'm still redirected.
It also doesn't matter what version of adguard I use.

**Comment by Versty** [comment]
@CapSel Hi! I would recommend you to create an issue with a detailed description without a screenshot.
Then reproduce the issue while the [screen recording](https://support.apple.com/en-us/HT207935) is active and send it to apple@adguard.com. Please mention the issue number in the subject.
