### ISSUE TITLE
Need help running the project locally

### ISSUE THREAD

**Issue by SaminathSafeHouse** [AdguardTeam/AdguardForiOS#2054]
I updated the match file with my developer id

For the git url, I'm not sure how to store the certificates in git and provide a url as below in the Match file

**git_url("ssh://git@bit.adguard.com:7999/adguard-ios/certificates.git")
storage_mode("git")
type("development")**

Can someone please provide the steps to add the certificate to the git and link it here ?
I exported the certificates from my local keychain and uploaded it to a git repo
And provided the repo link to the match file
But it seems to stop in the following state (Please refer attached screenshot below)

<img width="1344" alt="Screenshot 2022-09-06 at 9 15 56 PM" src="https://user-images.githubusercontent.com/97430185/188679643-409df51c-4bde-4380-866d-4e7291e02ed0.png">

When I tried to run the project after updating the provisioning profiles manually in xcode, I'm facing the following issues when trying to compile the project

<img width="804" alt="Screenshot 2022-09-07 at 10 27 35 AM" src="https://user-images.githubusercontent.com/97430185/188792196-c7303c0a-c956-4757-8611-b65cfa17a355.png">
<img width="803" alt="Screenshot 2022-09-07 at 10 13 10 AM" src="https://user-images.githubusercontent.com/97430185/188790489-f0732a4d-98e6-400e-b023-11eba3708397.png">

**Steps I followed for manual approach**
1. Cloned the project
2. brew install ruby
3. Updated .zshrc with the path for ruby
4. sudo gem install bundler
5. bundle config set --local path '.bundle/vendor'
6. bundle install
7. Then I manually changed the provisioning profiles and teams in each target and tried to run the project

Any help would be appreciated

Thanks in advance

**Comment by the-hungry-devel0per** [comment]
Can anyone please help with this ?

Thanks

**Comment by Versty** [comment]
@SaminathSafeHouse @the-hungry-devel0per HI! 
I would not recommend you to use AdGuard certificates in this case, they can cause the above errors. 
Some useful links how to properly create and sign certificates: 
- https://docs.fastlane.tools/codesigning/getting-started/
- https://developer.apple.com/support/code-signing/
- https://developer.apple.com/documentation/appstoreconnectapi/certificates
