### ISSUE TITLE
How to automatically block pictures of a specified size?

### ISSUE THREAD

**Issue by asdfj2381k** [AdguardTeam/AdguardForiOS#2057]
There is a website I like very much, the size of an image ad in it is 330px*330px

However, the administrators of the website often update the address of the pictures, which makes the blocking rules invalid.

I want to: Automatically remove all 330px*330px images in this website, what should I do?

**Comment by Versty** [comment]
@asdfj2381k Hi! 
Sure, we have an option to block by size. 
Please specify website you want to block ads on and an example of the desired content.

**Comment by asdfj2381k** [comment]
![image](https://user-images.githubusercontent.com/56584082/191027867-3deaf099-38ef-4eae-8825-f63310ec1b8d.png)


@Versty   Can you give me an example? Take this LOGO of GOOGLE as an example.

**Comment by jellizaveta** [comment]
To block this element you need to access the code of the page using the developer tools. Right click on the element --> inspect.
The `img` tag has a `height` and `width` attribute. (Width and height may vary on different screen sizes)

<details><summary>Screenshot:</summary>

<img width="1792" alt="Screenshot 2022-09-19 at 17 03 12" src="https://user-images.githubusercontent.com/91964807/191035849-95d2271e-a2b2-44f8-92f8-d7575c97b76c.png">

</details><br/>

So we can make a cosmetic rule. 

`google.com##img[height="92"][width="272"]`

`google.com` - The domain where the rule will be applied 
`##` - Cosmetic rule marker
`img[height="92"][width="272"]` - Matches all img elements with height attribute exactly equal to 92 and width attribute exactly equal to 272

More information about how to create your own filters can be found in our [documentation](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters)
