### ISSUE TITLE
Pinger app ads

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#206]
@Alex-302 
ads.aerserv.com
production-adserver-*.amazonaws.com
ads.pinger.com
cf-ads.pinger.com
tracking.applift.com
ads.yahoo.com
west.bidtellect.com

Pinger Textfree: Free Texting, Free Calling App by Pinger, Inc.
https://appsto.re/us/4xJGA.i

**Comment by Alex-302** [comment]
Added to Mobile filter
