### ISSUE TITLE
Block Yandex ads

### ISSUE THREAD

**Issue by exrector** [AdguardTeam/AdguardForiOS#2060]
Привет всей команде AdGuard. 
Вы можете заняться вплотную рекламой от Яндекса? Они на столько ошалели и остервенели от своего счастья (рекламная монополия рунета), что даже сложно назвать избыточной. От встроенных до баннеров на всю страницу. В любом браузере. При этом рекламные объявления идут с родительского домена например: (https://yandex.ru/an/count/WQOejI_zOCC0vGm0H1SAmr_KjTkCU0K0mm4nHqOgOm00000ujgL8lFJ2bgxtqCIe0O01q9u8Y07FYj_Hbm6G0RQEhl_TW8200fW1jewk_rsu0QJ0lgKbm042s07qrRsf0U01meoxgG7e0Pm22A02ujUh6V02ng2YJu03-k7csmU80-s3kwyFi0C4w0I_4VW4fgmFY0M8cG-G1QQi3w05fDS4g0MpymEm1RFp0xW5i_C3m0MEYIx81QBR2z05tz41w0K1e0QKoWEe1fJA0wa7kGNfyPr_hapW1uR2W806u0ZnwzKCw0a7-0g0jHY82n3e3860W8281A4HdvcPcPcPoO0KW8201E0K0UWKZ0AW5l3WbPa6oHQO5xwDm2-u5m705xNM0Q0Pg06u6V___m616l__ipr3odeIi1gxik7iYkZo_Ay1WXmDI754EdHASL98P55ZDwWU0R0V0P0YXCqda2A5pIUG8eRD9v0YXyqda2BHu2UG8jBW9v0Yq-0da2BKu2SA0EftC6-BT9RX0DJCfLRqEjhe7HCFQIo_ssUOJz4FDPOOjKsC0G00~1?stat-id=8&test-tag=404620279077393&banner-sizes=eyI3MjA1NzYwNjY1MzcyMzU0NyI6IjMwMHgyNTAifQ%3D%3D&format-type=118&actual-format=13&pcodever=653024&banner-test-tags=eyI3MjA1NzYwNjY1MzcyMzU0NyI6IjQyOTUwMTY0NjUifQ%3D%3D&subDesignId=393) и их не заблокировать не заблокировав вообще все сервисы яндекса. Можно, что-то придумать? Спасибо. LLAP 🖖🏻

**Comment by Versty** [comment]
@exrector Привет! 
Мы постоянно улучшаем свои продукты и стараемся, чтобы даже самая технически-сложная реклама могла быть заблокирована. 
Для браузеров рекомендуем установить два расширения вместе: [AdGuard AdBloсker](https://adguard.com/ru/adguard-browser-extension/overview.html) и AdGuard Extra.
На iOS от рекламы яндекса поможет активация [в приложении](https://adguard.com/ru/adguard-ios/overview.html) функции DNS-защиты. 
Для Mac и Windows хорошо подойдет десктопное приложение AdGuard.
