### ISSUE TITLE
NextDNS not working anymore.

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#2063]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard Pro 4.4.4(965)
- **Device model and storage size:**
  - iPhone 13 Pro Max
- **Operating system and version:**
  -  iOS 16.0.2
- **Browser or App:**
  - 

### Expected Behavior

Be able to connect to NextDNS DoQ

### Actual Behavior

 Invalid Upstream error message pops up. 

### Screenshots

Setup that used to work but that suddenly stops. 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49731083/194953892-de0c23f4-c58e-4da8-a009-55ba8feed20a.jpeg)

</details>

**Comment by Versty** [comment]
@Quorum75 
Doesn't reproduce on our side, successfully added a few NextDNS servers `quic://iPad-XXXXX.dns.nextdns.io:853` with no errors. 
If the issue still persists on your device, could you try to connect to another NextDNS DoQ endpoint?

**Comment by Quorum75** [comment]
@versty 
Hum... If you are using AdGuard Pro 4.4.4 (965) you should be able to reproduce it. It happens on all my iPhone and iPad. 

I found a workaround yesterday, but I can't explain why it is working. 

If you delete AdGuard VPN connection in iOS settings, which will disable AG DNS, and setup NextDNS in AG application, it will work. Also, I realized after a while, that some third parties DNS have also that issue like ControlD but some not like Rethink DNS. I just can't explain why. So maybe you try one third party DNS that works...

**Comment by Quorum75** [comment]
@Versty Hey! It seems this is in fact an old problem...

https://github.com/AdguardTeam/AdguardForiOS/issues/1815

FYI I facing this problem since the last AdGuard release. No issue before.

**Comment by Quorum75** [comment]
Email sent to your attention with Github issue reference number. 
Logs and some screenshots.
