### ISSUE TITLE
Adguard iOS updating lists issue

### ISSUE THREAD

**Issue by gototheskinny** [AdguardTeam/AdguardForiOS#2067]
Can't get the latest fixes on every list. Lists stuck at 14th of October while it's currently 16th of October. I tried reinstalling and disabling re-enabling but lists stuck at 14th. 

Using the latest FREE version![image](https://user-images.githubusercontent.com/51786709/196023434-8c5115a0-425b-49a9-9f6c-2422333fad6f.jpeg)
iPhone 12 iOS 15.0

**Comment by gototheskinny** [comment]
Hours later now updating works. I don't know how updating mechanism works. But if this is an issue pls solve this issue

**Comment by Versty** [comment]
@gototheskinny Hi!
Seems like you have ran into some temporary difficulties. 
Please keep me posted and reopen this thread if this issue returns.
