### ISSUE TITLE
Filters being used doesn't match what's enabled

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForiOS#2071]
Could you please explain why AdGuard for iOS > Settings > Advanced > Content Blockers shows rules being used for filter categories that aren’t even enabled?

It looks from the UI that it may even increase rule conversion time unnecessarily?
This is entirely presumptuous, but that's how it appears.

![image](https://user-images.githubusercontent.com/95468948/197943434-2eb6d84f-e384-4037-82a2-5a59e4031b06.png)

![image](https://user-images.githubusercontent.com/95468948/197943475-a3629c99-5026-47bc-96c9-934d5be7533c.jpeg)

**Comment by Versty** [comment]
@jslawler Additional rules come from the AdGuard Base filter and are used to adjust the rules from the various filter lists in this category. It may increase conversion time a little, but not drastically.
