### ISSUE TITLE
Milestones does not appear to be used anymore

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForiOS#2072]
On the GitHub Readme for AdGuard for iOS, it says future plans will appear in milestones.

There has not been an update to the Milestones for a long time, and it seems labels get used on issues instead.

https://github.com/AdguardTeam/AdguardForiOS#our-plans

![image](https://user-images.githubusercontent.com/95468948/198755485-dfe69d57-c996-4d07-8a0b-ada101b02042.png)

![image](https://user-images.githubusercontent.com/95468948/198755529-511fd3a4-822c-42e3-b442-54d644010b27.png)

**Comment by Versty** [comment]
@jslawler, hi!
Milestones were a temporary solution for scheduling and managing tasks, we recently switched to a private tracker where we store tasks. Now you can learn about upcoming features from the social media.
