### ISSUE TITLE
Updates Visibility

### ISSUE THREAD

**Issue by mhuber665** [AdguardTeam/AdguardForiOS#2075]
![IMG_2890](https://user-images.githubusercontent.com/117176404/199235157-2bcb4156-a091-4f00-ae2d-3337c19242f7.PNG)

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

When manually updating the filters in AdGuard Pro for iOS, it is always displayed for only a few seconds whether the update was successful. Therefore, you have to stare unflinchingly at the display for that long. This is extremely annoying. I would like to have a function where I can check if the last update was successful. And when it took place. And whether it was initiated automatically or manually -
![IMG_2890](https://user-images.githubusercontent.com/117176404/199235907-c669d0a3-b690-46f1-84cd-8cb7991a8413.PNG)
->

**Comment by mhuber665** [comment]
When manually updating the filters in AdGuard Pro for iOS, it is always displayed for only a few seconds whether the update was successful. Therefore, you have to stare unflinchingly at the display for that long. This is extremely annoying. I would like to have a function where I can check if the last update was successful. And when it took place. And whether it was initiated automatically or manually .

**Comment by Versty** [comment]
@mhuber665 
This feature request already exists #2035 
Therefore closed as a duplicate.
