### ISSUE TITLE
My teacher ads and trackers

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#208]
houseads.ttpsdk.info
clientlogger-prod.elasticbeanstalk.com
houseads-prod.elasticbeanstalk.com

https://appsto.re/us/lxkveb.i

**Comment by Alex-302** [comment]
Added
```
clientlogger-prod.elasticbeanstalk.com
houseads-prod.elasticbeanstalk.com
```
the first was added today.
