### ISSUE TITLE
Will not block ads on my gay porn website

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardForiOS#2082]
I tried the premium on my gay porn website gaypornhdfree.com 

but it did not block any of the ads at all
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version yes
- [ ] I checked the documentation and found no answer yes
- [ ] I checked to make sure that this issue has not already been filed
Yes
### Issue Details

- **AdGuard version:**4.4.4
  - 4.4.4
- **Device model and storage size:**Iphone 7 plus 
  - 128 GB
- **Operating system and version:**15.7.1
  - 
- **Browser or App:**
  - App

### Expected Behavior to block all ads did not block a single one on the site

 To block the ads on my website 

### Actual Behavior did not block any

No ads were blocked
### Screenshots I don’t think you want a screenshot 

<details><summary>Screenshot:</summary>

</details>

**Comment by Versty** [comment]
@malicerainbow, hi! 
Please, report incorrect blocking via in-app option in the Support tab.

**Comment by malicerainbow** [comment]
> 

What's the Support tab? Can you clarify where that is?
