### ISSUE TITLE
Auto-fill active filters on iOS and iPadOS filter report forms

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#2084]
@WoodpeckerBaby commented on [Tue Nov 29 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136137)

### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

It's a massive pain to manually type and select used filters on mobile when reporting. This should be automatic like it is on desktop. 

### Proposed solution

Automatically gather this information from the Safari extension if it's enabled. I'm not talking about just the content blockers. I'm refering to the full extension used for reporting and for advanced protection. 

### Additional information

Also, it should remember the github username and use Apple's Private Access Tokens instead of hcapcha.

**Comment by Versty** [comment]
@WoodpeckerBaby 
Active filters will be autofilled when you report an incorrect blocking via in-app option (Settings -> Support -> Report incorrect blocking). Browser extensions is much more limited in resources, that is why this feature has been implemented by half.

**Comment by WoodpeckerBaby** [comment]
I'm pretty sure its possible to achieve via the browser extension too.
