### ISSUE TITLE
Adding Control D via DoQ Crashes App

### ISSUE THREAD

**Issue by plainasday** [AdguardTeam/AdguardForiOS#2085]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS (AdGuard Pro) v4.4.4
- **Device model and storage size:**
  - iPhone 13 Pro 512gb
- **Operating system and version:**
  - iOS 16.1.2

### Expected Behavior

When adding Control D resolver via DoQ, the expectation is that the resolver would be added to the list and be able to be used by AdGuard Pro.  The resolver is "quic://p2.freedns.controld.com:853".

### Actual Behavior

When adding "quic://p2.freedns.controld.com:853" the app crashes to the Home Screen and does not add the resolver. 

### Additional Information

This occurs while using "AdGuard" under "DNS Implementation" and not the native iOS implementation. 

NextDNS's DoQ resolver can be added to AdGuard Pro for iOS without issue via "quic://dns.nextdns.io:853". Control D's DoH can be added to AdGuard Pro for iOS without issue. Control D's DoQ resolver can be added to AdGuard Home without issue.

**Comment by Versty** [comment]
@plainasday Thank you for the bug report! 
This bug is reproducing on our side as well. Seems to be related to the iOS 16.1.2 version.
