### ISSUE TITLE
[Feature request] DNS protection exceptions - add option to add VPN connections

### ISSUE THREAD

**Issue by akuropka** [AdguardTeam/AdguardForiOS#2089]
AdGuard is the number one solution for protecting the device and keep annoyances away - keep up your good work!

However, I am coming across a limitation by design:

If I enable DNS protection and connect to my company's network through VPN the DNS server set up under DNS protection > DNS server is used and domain name resolution for addresses inside the network is not working because I do not use the company's DNS server. 

I can set up exceptions for Wi-Fi which works as intended (e.g. while being in office).

I would appreciate an option to either exclude VPN connections in General (similar to the mobile data and Wi-Fi filter switches) and/or to add an exception for certain VPNs.

**Comment by Versty** [comment]
@akuropka Thank you for the feature request and kind words about our work! 
Seems like you have faced iOS limitations. iOS devices can use only one main VPN configuration at a time and an additional one Personal VPN configuration (usually IPSec protocol). Therefore, one of the VPN tunnels will be dropped if AdGuard VPN and your office VPN both use the main VPN configuration. 

So, the Wi-Fi exception is the best solution in this case or you can add the company's DNS as a custom DNS in the AdGuard app.

**Comment by akuropka** [comment]
@Versty, thx for your reply, for this use case I'm using the "Native" implementation which works as this does not depend on pseudo VPN (sorry for not mentioning before). The company's DNS server is not available outside the corporate network.
