### ISSUE TITLE
Stubhub app

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#209]
eu-content.swrve.com
eu-api.swrve.com

StubHub - Sports, Concert & Theatre Tickets by StubHub Inc.
https://appsto.re/us/_2u2v.i

**Comment by Alex-302** [comment]
Not sure about these domains. Perhaps they are used as CDN.

**Comment by jo2dan23** [comment]
swrve.com is marketing/advertising

**Comment by ameshkov** [comment]
It also provides push notifications and a/b testing functionality.

We should first check if it does not break apps using it.

Some examples:
https://www.swrve.com/customer-showcase

**Comment by jo2dan23** [comment]
The push notifications it provides has to do with marketing not like regular push notifications if that makes sense.

**Comment by jo2dan23** [comment]
The push notifications it provides has to do with marketing not like regular push notifications if that makes sense.

**Comment by jo2dan23** [comment]
The ab testing is used for marketing also. See here:

https://www.swrve.com/product/a-b-testing

**Comment by ameshkov** [comment]
Marketing is not synonym to a bad thing:)

But anyway, what I mean is that apps may rely on this functionality and blocking it can be harmful.
