### ISSUE TITLE
Can't update filter

### ISSUE THREAD

**Issue by Charlie102308** [AdguardTeam/AdguardForiOS#2092]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - Adguard for safari v1.11.6
- **Device model and storage size:**
  - Mackbook por 2020 intel
- **Operating system and version:**
  - macOS 13.0.1
- **Browser or App:**
  - 

### Expected Behavior

can update normally either by auto or manual

### Actual Behavior

Can't update filter by manual because of error

### Screenshots

<img width="1440" alt="2022-12-21 22 54 17" src="https://user-images.githubusercontent.com/94617775/208935197-efb91dce-0c34-4184-84d8-c3d30937baa8.png">

<details><summary>Screenshot:</summary>

</details>

### Additional Information
*Logs are removed for privacy reasons*

**Comment by Versty** [comment]
@Charlie102308 Hi! 
This issue is probably caused by unstable connection to the update server. 
Does it occur every time you try to update manually?
