### ISSUE TITLE
Add the Arabic language 

### ISSUE THREAD

**Issue by mohdalyahri** [AdguardTeam/AdguardForiOS#2093]
The arabic language is fully done, could you please drop it with your next update?
> Note: we ask for it before and you guys says it will be in version 4.4.5 and this not happened! 

Thank you!

**Comment by Versty** [comment]
@mohdalyahri Thank you for the kind reminder and help with the translations! 
Arabic is planned for version 4.5.0 and will be implemented. 

If you would like to discuss this topic in more detail, please, continue thread #1977.
