### ISSUE TITLE
Advanced settings naming convention

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForiOS#2094]
When enabling advanced settings it shows as 2 different names in AdGuard for iOS.
- Advanced mode, and
- Advanced settings

It likely makes sense to have them called the same thing for the sake of uniformity.

![image](https://user-images.githubusercontent.com/95468948/209035758-c8877822-1321-4cd5-8c61-1c2cdb51f9e6.jpeg)

**Comment by zzebrum** [comment]
@jslawler hi there! 

`Advanced mode` != `Advanced settings`

`Advanced mode` not only enables `Advanced settings`, but also adds lots of info into `Filtering log` and enables all `DNS filtering` settings at `DNS Protection` tab.
