### ISSUE TITLE
DoQ default port 8853

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForiOS#2097]
Why DoQ has still not been setup with port 8853?

http://www.watersprings.org/pub/id/draft-ietf-dprive-dnsoquic-02.html

All external DoQ DNS still don't work with 8853 and 853 still must be used

**Comment by sfionov** [comment]
AdGuard for iOS 4.4.5 supports RFC 9250 for DoQ, which uses port 853.

**Comment by Quorum75** [comment]
> AdGuard for iOS 4.4.5 supports RFC 9250 for DoQ, which uses port 853.

Using port 853 would cause confusion between DoQ and DNS over DTLS [RFC8094]
