### ISSUE TITLE
Latest stable (990) reads more up-to-date than the beta (985)

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForiOS#2098]
Is it intentional that the latest stable reads more up-to-date than the latest beta?

There's no prompt that a more up-to-date release may be available when on the beta and a stable is released, only if there's a new beta available via TestFlight.

For users who always like to have the most up-to-date release, this would require them to monitor the App Store and TestFlight to determine which had the latest update.

![image](https://user-images.githubusercontent.com/95468948/209748982-6c45b85b-3aa2-4588-ab03-f86b40cd6d04.jpeg)

![image](https://user-images.githubusercontent.com/95468948/209749020-2233ee44-4f1b-49a1-91fb-873f4e4aec75.jpeg)

**Comment by Versty** [comment]
@jslawler 985 and 990 builds are almost similar. In the 990 we have made a minor adjustments to the text and decided to release the version without additional beta-testing as an exception. 
Every next build with any significant changes will be provided to the beta testers first, and then released in the App Store. So, I definitely recommend you to stay on beta.

**Comment by jslawler** [comment]
Understood!
