### ISSUE TITLE
Block only the element I select on safari iOS but it blocks all similar elements

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardForiOS#2099]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version yes
- [ ] I checked the documentation and found no answer I don’t understand it
- [ ] I checked to make sure that this issue has not already been filed it’s not been filed

### Issue Details

- **AdGuard version:**
  - 4.4.5
- **Device model and storage size:**
  - iPhone 7 plus 
- **Operating system and version:**
  - 15.7.1
- **Browser or App:**
  - App

### Expected Behavior

 To block only the selected element 

### Actual Behavior

it blocks similar elements to the one I blocked 

### Screenshots

<details><summary>Screenshots:</summary>

![997A6A35-B3B0-4514-B2DE-266549D8588C](https://user-images.githubusercontent.com/118444664/209800128-4ab6c0b6-6b44-49e4-99eb-af0fa966374f.jpeg)

![6DC522A9-3224-4201-B741-C0EC7FAB1F4B](https://user-images.githubusercontent.com/118444664/209800130-674d38d3-f420-46a5-89ac-3289395a50c1.jpeg)

![F38E87E9-005C-4752-84D0-E3218F9683B7](https://user-images.githubusercontent.com/118444664/209800132-1da9c3b5-4daf-4eaf-b911-771f4a4686c8.jpeg)

![EB8D40D8-9CD9-4748-AD57-1770D2B43EFE](https://user-images.githubusercontent.com/118444664/209800136-e0ff2c9d-1510-48a9-b8e4-86c7360f2fbf.jpeg)

</details>

**Comment by Versty** [comment]
@malicerainbow Hi! 
This behavior is intended if you select an element on the page, but not a specific image.
You can block an image by creating a custom rule related with the image source.

<details><summary>For example:</summary> 
google.com##[src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBYWFRgWFRUYGBgYHBgcGRoZGRgaGBgaGRgaGhgaGBgcIS4lHB4rIRgYJjgmKy8xNTU1GiQ7QDs0Py40NTEBDAwMEA8QHxISHzQrIyQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NP/AABEIAOEA4AMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAFAAIDBAYBBwj/xAA5EAABAwIFAQYEBgIBBAMAAAABAAIRAyEEBRIxQVEGImFxgZETobHwMkLB0eHxBxRSFXLC0iNikv/EABoBAAMBAQEBAAAAAAAAAAAAAAABAgMEBQb/xAAlEQACAgIDAQACAQUAAAAAAAAAAQIREiEDMVFBEyIUBDJhcaH/2gAMAwEAAhEDEQA/APNsT+AoUEVpt191dflTuAsIujsltgkrit1cG5vCrOaQrTTE0RlRlSOUZVIwkcSCSQVGZ1JJJIo6nJq6gpCT2lMXQkOydpT2lQNcpGlQ0bQlslBTkwOXdamjqUkSAqVrlW+InNqKXEqM0i/TerVNyGMqqdlcLGUGdMORehVj1YY9CmYoKZmKCwlxs6Y8kfQsx6mY9CmYsKVuNCwlxvwtTj6FmvUjXIU3HBPGPHVZvil4VmjMZU/vArV4ZwIuFgKNdzTZabK8zmF7co7s+YjO1Qeq4JjuECzLKOQFoKFSRKnBBsVPRomebV6BabhVit/mWUteCQFkcZlzmuiFpGRnON9AwroRCjgOXFW2sY3hXZnj6CBRPRd+C7oitXENGwVR2JnhJNlNRRU+GVJRw7nmAP2C78RGcqwLiNZETsEMSoG4vLXMAcSCPDjwvyqK1mPw80ngefqFlnNQnY2qOAqRoUTQrNNiTHFjHSoy4q6aJjZNdhz0QhuTKclKSrLaSlGGTJt+lMOKe1xU7qcLghKilOS+jWucpG6l1rgp2PCWKK/LL0a1jlKym5PZUCnbXajCIvzy9GMw7lOzCOT2YpvUKdmNb1Cf44+C/kcnpikWyH8aEo/2aAbUY547uoT5Jy6Mo9mqwxhXHstIRepTouMGmB4tsonZcBdjrdCssWbWBP8Aa0/iWezXGAuMIt2kBYLgjxgx7rL0ocd0RQNkQe5xgAlW25S/RrOytYWAYaBqOxRXAv1N0OMnkfVEpuI4wizMtwZO5hV6lINMSrucvGstaYDbIPUdJWkbatmU6TpBTKsEKrrmGhbCpgnimdI0tA3NlicqquY62/0/lafF48/Dl7/C558Gj9U2SrIDUik9szYkrKU3SjrKgcx+n1Q7J8vNR3klBdlzfRcwGUF+wRd/Z17G6nCFtOzeUNYwOcFT7WZtTDCxpE+CrEhyMZVLWDSohjGQQQqL6ut11J/rAJ0KxlR1iQFTGKKs1awAIQtxRQWEGVwd0qlIESChwUrK5CVDUh72EJgLk9taTdW6YaUBplIalK0ORKjhQ4wFocF2Y1CSnTD9fTINa5SNYVtKnZcNTW9nUql4Oo+mHbhL+CI0hCaCpGNWcnZUTZYHFF9IOB7zbH0RbCveWydPusj2fxOmpBuHAiOJ4Whx9NtJoMmTeLwPBCKe9F57mu7rtLhyOFmc4ymlScX0yIIkt6dYXc0zHQzULnzhZPE5w95gyUpRvoalj2XMOwPrtaw2RI5e6i1793d6D4bqTIspDGfEdIdMgIrnbgKZefwEX9lzT5HnijohBYZM80q1i4kncptMSfK65UiTG3Cmos7pPiLdY2+f0XejgZPhKuggm5Py/lEy4PaSgXw43BJ6D9SiOExThA2jjZRJfS4P4GMow2qm8RFjZW+yrGtuet1Wy7FBpvzum5lj2Uz3OePNTCWyuSLSs0Ob9p9E02dOFUxPY7EFrahILnAEtm4nb1hZDD1C55eTde2VqxhjurWn3aFpJmcY2eL16DmPc17SCDsRBUVXEnZel9ocqbVElo1RZ+5Hh4jwK86zPBupkteNJ3afyvHVp/RJS+Mbj4C3kqPSrfwCQl8IBVZNFOEir3+uLJpoBKx0U4Kex5BV1mFMkQZ8uN1byvIald4YwTNyZs1vJceAiwoIdmsM+q9rWNJPyHiTwF6ZTxDKMNEPeBcmzQeg6oPhcOKNP4eHjgvf+Z/UgDZvAE+67WxAY0jQ7xjnx7s/NS5yf+i4wTeyfEZkHOJIA8tk9lZsShNOCXEiAQLJrWk2Bst+J5R2Y8yxlSMKy6ttCp03hWBXXMzVErahaQRYhbwYllXB63wHAQZ6rzmpWC7isSTRgFwE3E29k4oG/ozH4u5AdbobhcyLCh9S7ZvsqFOkXX3R7slj6dKtL9vvZOSeOhRdytnoeAwTXMI5HB3WS7f1dDWMa78Y748jYrQ4ztUAxj2UmkPeWNGqHwBOoiLBC+0LaOLwlSr+Crh4lp3IJsPGVzw4qkm0dE+W4tJnmgRKvhjSLTu14kIci1XMg9tNrgO41zZjqbH2XU7OVUUq5dEzv0VcOKI12tDQxvecTwNgqtTDOB0xfohOwegnlnei6n7Q4IiHAcXRrs3lAFPWRc/JWM4pjQQRNtlklUrNZSuKRicK8DifP+F7Fkj/AI+DovkSG6DBdYsOkDrtC8fw2HcXwBF7BevdiMK9uGLHn887EFoLb/RaS2RF0ywaTgNLx85+oCBZrltN4LXjU07byD1bHMK5mZfqOipqaNxz7/yqxaWt1vJE7B258pKhtUW07MBWy51Go5jjZt2nh7TsR6cdZ6J2HpB2tzjGgAlo3PARTH1CSZkwL325HoYQbK9Rebt0vBBEg7giPNUnZLVDQ3VJja58BEhSUcMYl21pHQGZ9bKZmF0EtgGGk72IEiWxv19E/NDoo02y7U4d+1wdZJDT1IM+vinYio94NQhkxYXN9x09ltMrrMoUmUqcFz266zrHvEWafAARHmsDgqRlxE2nfiDz4rQ4CqaUMcDLgHPmAGNIkT43mD4Dqkxo1eAzFr3RrDBMXD5PmYiPDhWsdhWuEiuCRc6Jt56RA9YWTe9j3h7H3FzI2bwYi5PRQvzNtRzWTUfcgatLWjxDW8eaL0VFOw9UZaNUn75FlNhWxuh2UVO6A43kzPmjIDStYSqJlyL9nZgm4VpiFI+iHCBuE3CyQFObG3K57NaBeIwxExwp8nw5qamxNjZT4+oG90blXexrWit3uVcTOQNw1DvaCIO2xTMyyCrSeGx+K7T1Xr9Ps3Se4P0wUTxWSMewB+7bA8qvor0eZ5HkGKqtaPhNdou1znRHh4of2rwbsLrpuqh9SpeoGiGt6Nnlev0KHwaTmU/xEGDveLLxnOOy+NLy57HPkk6gZ3PRL9UNWzKltk7C1dL2u6GUUxOXOojTWpva47SIsuZXkNSvJYIaCAST7wm2kgUWek4P/UqUmVPhQ5zd4gjrso8N2ZY9+sthvAiPfqrGQZeGBrI/CIutPpWEXJt70ayjFKl2CX4JjGwBA8FnczLRNgtdiQFms0ojrCszBOSZdrqg6BpJvb9V6xhMEGMA8P0We7F5REud6Iz2pxWhjQOPrwr+E/TJ5tUax9Q7RAEGL8Ss9jaj6l4FyR8rdUaqM1hwdvufH+Lqu3BODY8TEx6C/hHssW9m16BDsJqlpBmCHGxsLETyNkLw2Q63v0jToAILdxEGw8QtBhmvFbS8Q18iRqkeo2RXsxl4bVxGrdpaAItFyCPcqkJmBoVZ+HYwGlriYH4i6YHEft0VnDYY1n6SdLWEHr3njUI6/wAK1m+VuY/TFnPd3p4dBtzzCmyfDsY92pxa5/dvI2bxNrzPoqsmillOAGmrJDtLjpB/P3joB6wQSesNHVDMdTLTLjDuZkkkfmIHJ8Y3Wl7NUXN+M8s0CX6Ne15Gqdx7XhZ3NMHBLmvc5xudXieDEfogFZQo4kMdIJMxII0z5kOKusxTdYcGhs8AQJ8EJe0b+nqk2pYAmw2TKToP4bMdLjdG8NjXHYrE/EbYlHctzGm2NTlcTOXZUw5gq1UMCRdLC0g5x6KfE09LFga9AXFvcTIspcuxTqdRjp5EqrUqEugAkq0xjugn6K1ozas9oyHG62AzwEfLpC877MY0w0E3W7wz5G6sge0Qu1mjfZTSFHUZKlqxp0YjtpVw1VgY/SXflg94FVezmE0U2tYBA5HJ6ovnHZGhVcXmWuO5BVnB4JtFgYzZoUSNYypEmHpBvmp9SgpuUgKSJZXxDUFxtAOMbSjlZVcFhddQDgFUhGm7NYT4dMC580O7SgF8OPAIWroUtLAPBYvtqXta2o2SGkh1u7fa6qXQo9mVx+KYx8TJBBAmOeQpcPmAr4hlKm17nNPf02YLfmdKzGaUmvqMJdpc8wQ0kkf2tRlzxhACwCxGoOs6evkskklbNXt6IMwxNcUauJNRjGsdpbTawFzofoMudyDJ8gtJ2RxzzVFDEaHGqzXTe1uh/cglrwPAyD5qozCurOfUwpY5lQzUoVLAP/M5jxYSbkFGMu7M16b2Yms9ssg6GbMY0EkSdyVpFWyG9Aztxl4D2CLAG49OOuywOHAL61ZwLm0hz1XqXazGNcRF4EnreIXj+bY91OnWpNAio4ajy3SZt5wo7lRa1Gx2LrPq0mVjUe/U93xKbdTWUpeQ0N0/iJF5O226ssy2vUq/Ap1HOBpGpDyXaeImZE+KvdnuzrxRZUbi6bWVBJa5hcR1EAojjsQ3CMf8Il9SpGus+dRAs0Ma0d1onaw81f0g81xlJ7HFrgAQYMXuoGvVzEPL3Ocb6jebfZVEtgwqQO0JzlLSKrldaVpF0QzZZe3lEsSzuXEnpwP+79lBgGCA63h+5U1c2Np8SYb78rBI1kzKVXnWYv5CB6K3gMNUqOAYLqanhtb9OtoHRt1vezGWMZcXd1PCbJ+EWS9nKrIeSJ6dEfp45zDpeEQqVw0XKzXaDHgAOn8Bv5FNaIezU0cXqhW2OnhZHI86Y8gTdbShAAVCK1ei+8BCK2tgOtsePC0lR8GOqHY54Bg3ad/BQ4lJgrBS8wFcfgCOqI5Lg2MbI/MSQr1Z4BiN0KOgbMpWwrnWujuR5Zoh3uCrNPDgmYRFllSjQm7Ji1UMwwLajCx7Q5rrEFXQQV1MR57S7H06NQvcJBPdtMSr47PM3LSSeZ9lraoHKruhJRRWTOZNl4YIgIpiaWpjm9QQqmGqwYJVv4oVEnjeZYiA8PeA8OIMuBPl9F5diX6qpEyCflsvU/8AKWRFrjXohrtbu+3ugt1QJHW/1QzCdh2U6JdVeHVnC+k91s8AxeOqySS2jdu0kAKOLdQZpY8OG7b7HwC4zEvqsIeX9RBgnziLIu3JTTAGhh578VI8muAH36FmIeADDG23hndnxayHN/8AyqSJdGPDQHRcdFXrwN4lF8VUYZOg2/Mwh4H/AHMMOHqUGxNE/ikOb/ybx4OBuD5/NNITlSKu6fpTWhSNK0Rma2vjBTaGzcBDaubTuZ8wShGMxJe4uPWyhaojHRUpWwvg8y0PDpEeAW3yfPWNu54AXn1PCjSXG6T6RayTaU1DLoMqPTcw7VUhTJDwTqkDwWMzvOziHDQCGxB8UFoU1OtY8P1kORdy2u6k8Oa4ghek4DtlTfSAe7Q9set15WHJ7ZWr4otUK9nvtbHMNEVC4REzKB51n9NlMVJBa4SL7WXlBx9TRo1u0dJt6KpWBc0ML3Fo4JWT4JfClJH0B2WzOnXoMqMdIiPI8q3WrHU2/wCKT6DaF4X2ezurhAW03S0mS07T4dFtMi7SVcTi6LS0MaJmDJNunSyiXFJBkj1KjT7oUgCewWXSxSBA8woH41o3KtvZZZTtDUIaSOoB8ibpMaC+He6rJaYaDE7z5KwMGG3Li4+JQ3Ls4p6A1pAAtHKmxGZsixSQ2SYgxcFVK2bgDS50HqguKziCRNr/AH81ncbnAJudk0SG8y+FUvUqagLxx4WQLH5sxoDaZMAbH6X4QTGZpI7pk+6CVnvJJLtI87pFq6DmKzzUAXOAuGybgE2a4jlu4Pg8dEIxuMLtToILO69u7qZnqLlh/wCV/EO4GVarRa5HIved7ldfWd3ajRD2dx83DmbMLuojunyanFSfwUqX07XbqBe27mguI2dpG72PG4HIuBew2VRtQOuDeN4uRyHgWc3xF+oVirhywtfTJDHHUGzdjxGpoPBFoPII3SxGBa7vMtP5RaDzA46+UeK0XFJk5JFGpRAO0dWzt5HkdCk2gOsK+zDA2Ivwf0Ph99VK2i0cX2Vr+ml6P8i8ATWKanRJOy0DMOxp/CLqVlMbBbL+n/yZ5A/BYWfxExwFBmL9T9I2ajWoNkRcArO0niSSblNxUaSBOyduy4SmuqhNZUlFroCZqklRarqQOlWqEcK5Kc4jkpiBkrCvQP8AGOFHxtZOwgW6+K8+aFpezHaR2GeO4x7SRMyHeh2UzTcWkI+gqbbLrgq2XYkPY142cAdwd/EK0uE0Guast2mpaQTEggytch2aYYPYQeQgD50zLN6lCq5oJ0SYg+/zlWmdqXlzGSe84T4AugT6CfVS/wCQuzj6FRz2gupuvYHu258FmsO7/wCWen/i2B9FcI2DZoKGZVarXOiC4PNz/wDV/wD7N9kO77vxvMHop8E/u2NwY9wHN+bD7pzmX+nlwV1Q4YvszcmNDIEQuPZKRt/ac2qOoH8ea3UIrRFspvoX/hS0KcG/ILT6/wBBSvqC/eHumWI3+fsnjELJcMzVqYSA10ejhs4W9D4ErjaMWBA2O53E+G+64wgbmEqtdhuHcgn3k+if6oNnH0zN7H6+R6rrW8/fqk6sNtU3E9DZRtqC9/6QnEC7UpSAn4ajFvvzThU/RWKX9oAiNMa9knZcyZ0jfpypWAkmDz7XVh7LIaQrKVXBsDYIHKgbgKZBkCyu1mSPD9ArNCgCyCAlSCzONwDTIAsbW4Tn5Yxoi8na5RengiDYwOeiY+mQ6CZjadksI+DyZRGWMkAgepuUyvlrBADfUE2RlovteLJ78PPe8kYx8DJgVuRyJDiOVLhMqaR3g7exmEcLLX+7p+ni1kKC8E5M2XYDMNDBQc+Wt/BO48JXoLHSF45gHljpaPGfv0XpuQYwvZePQhcfPx4u0aQlegyoMSLKxChr7LnNDzP/ACJQJoPMiG3v7ev3svEPiEPJ51H6r6D7X0NdN7eo6xfcL53qWc7zP1VRdAHMAx7w6HXgfIj90RbgS6xcf25hVezbZnx/v9EeIAP1+i9LjgnG2YSdMEnL28X8ybJ9HL2G+nb90Ta0mY+7/wBrunvED+/Za/jj4LJgx2EZbuCCbrv/AE5n/H6q89gtbxTngAt9k8Y+BbBzMuG4HlN/qpH4ZsmWifSxV8P0j7vf+0zDm7pG/v8APdGKXwLZXbh2xsIiCPpb9VDWwLNwArjnQfTpwm1nWMeP7puK8C2VGbCR8rcq65nW1lk6+Me8iXERwNh5JB53LyT4lcUeWT7X/TSUF8Zq6To6qw6oOqyVHGPBnWT4EyLeCndj3m5dJ4B29lopojE0DHSbmyt06oAiRusezHP/AOZ34MKarmdQAadAAn8okyjNVdBia9rlGXAuMAFVclf8VrQHAB2okkmWloFj7hEMLlxcx1Rj9WnVwRqgTHzWf8njXbK/FJ9Fd42jrdTFu33P3CbiWGm0B/A1HciJkEWuIVf/AKjTMAPBPk4D3IWsZxl0yXFrsu6fbj0XaV3X/u8BMNYcbWjTB4vt93Sw571uTt09ONgrJCjGQLHwWs7K4uHBp+m/z2WNpOAETIEfe91pOyp1VWgbT7/cLHmVxZUXs9FUNcWUwUOI2Xnm5h+1c6HkSLHz9/VfPeKdL3Hq48Rz0X0X2oHcJ8I+Z/c+y8Az0t/2H6QB3rxsTyYTj2P4Gezje7KKVnmRvefTn9UOyN1mgW/pGPhguBPE9LdbL1uP+1HPLsbRaTbc8+/37rr7Ez6/U/UJa9BHifa1p+vomkgTJt9wN91oSOoSQePDkfcKq+p3reJ55/pWKFSZjc9L+irvZ1MWkdebfRAIme/p96jI+nzXGHzBO0eX9JWiOIHmT1+RXTZxOwaDc7XEJ2Bx2/Xc3jbhVmOkH9Z4UjL32kgT9+SbTcNoi/va/wBUhmLD7qVr1WaU8OXlqZs0WPiLoqFVdSdrVZhRK191ZZWHSfkEP1J7XoUwoJYXMH09Wg9140vHBvaOhWz7O5+S34QazvNOk7d4Du6uswvPA9SUK7mOD2mCDI6SFlyccZJlxk4s2HaPPddPQ1paXWdN4Fu40/8AGQT6BAGPgKhisWaj9bgATuBMT4Bd+N5+K04aiiZNyYXZiYAn7+4CnfmrgIF55Infp022QMVvVONZdGaIxNHhc4cxpkAkxvPpDRb1Xof+LMQ+o57nbNbxMXNrfyvHmVxFl6n/AIczBmqrTLoeWtc0dQDeOu4UcsriwjHZ64HKGtymUapLvddrOsVxGhhu2VQilU07gSPZfPjnlziTuST7mV7d2zx+gvvPcn6rxCoe8SOSUReymtGjyRziQBvuPsbI78Qj+onwWLy7FFhsSJ8URGKcCCHkSb39F6PHzJRMJR2H2vl5EG42+tlDVJL9jabfwoKNaHEhx73Jn1uuurw4kGZH5jMybiF0KRFF/DVQJtcG3BvynY10kk9Bcc8BDxjAPyCxsNIgeXQqapjHOBcQ3i3e3uOtt03IKGMfeTI5O9osAnOc9xECzgfcfZQ+rmJa0NtIN7Wg72Uv+89xsRtwIm/HRRmh4stayLOnu3PpuoaILn6d+SQOFXp64dqdYm7dt9rDf+ESZXYxgLDBcIkbg7mQqUvROzBSknfDKWgrxrOrB+DZSlO+GeiWg9EWGL8GyuhyWld0FGQYsWpPa9R6V3QVWYsWS60m1FDpS0lPMMWWGPXSVA5pAmQZ6fqE2T4ozFRZa9G+ymZCjiaT3OcGteC4NMEgfl8is3rKWsozCj7AoOaWhzYhwBBHINwhuY4zQxx+4j+14X2b/wAmYrDMFN8VWNgN1WcwWEAjcRwVbzn/ACQ6pR0MYWvJkuNwQSCR8yPRZsaRS7ZZ7re9o3Mieg+ysNCnxOKc9xc43KglNaG3Y5pVhtf+FUldlWpUSaKhjNQ9PM+Ponip+l+OsX4Wdp1S1WBi7R81vHn1snFB1jwY1G/p1Uj2OILWX53/AE5QFmLvvCsNzIgQD6rRc8a2LEfVplv4jc+vmD4qfDO8IA6/zbxQ6riCTv47pjKhmZPuo/Mky8Qs+sJNzc+/jAT2VoYAd2/SbQD4IM+pKmoYuAQRM8prn2TgQBcSSXnneTDZcSSUjGlcKSSZPwjSSSVEHAuhJJAHHJBJJBP0RXCkkgBBIrqSA+DE0pJKiThXCkkghnCkkkmSJJJJACTxskkgaHBRlJJMGf/Z"]

</details>

Read more about [creating custom filtering rules](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters).
