### ISSUE TITLE
Seatgeek app ads

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#210]
e.apsalar.com
nativesdks.mparticle.com
config2.mparticle.com

SeatGeek – Tickets to Sports, Concerts & Broadway by SeatGeek
https://appsto.re/us/E0kVI.i

**Comment by Alex-302** [comment]
> e.apsalar.com

added

**Comment by jo2dan23** [comment]
What about  The mparticle.com ones?

**Comment by jo2dan23** [comment]
What about  The mparticle.com ones?

**Comment by Alex-302** [comment]
I'm not sure about it. Could you capture these requests by Fiddler?

**Comment by jo2dan23** [comment]
@Alex-302 fiddler wont decrypt them but see here: it is used for analyitcs 

https://github.com/mParticle/mparticle-apple-sdk

**Comment by jo2dan23** [comment]
mParticle announced today that it has raised $17.5 million in Series B funding.

The New York City startup helps marketers collect user data through a variety of services and then funnel that data to other marketing and analytics tools:

https://techcrunch.com/2016/10/13/mparticle-series-b/

**Comment by Alex-302** [comment]
Ok, added
