### ISSUE TITLE
Allow disabling of activity log when using AdGuard DNS implementation

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForiOS#2101]
When using AdGuard DNS implementation, the activity log seems to populate data by default without a way to disable it.

This is a feature request to allow disabling the activity log entirely whilst the AdGuard DNS implementation is active.

![image](https://user-images.githubusercontent.com/95468948/210024920-7b4e05df-fbf5-4de3-8e42-1e18897b144c.png)

**Comment by Versty** [comment]
@jslawler Hi! 
The activity log doesn't consume additional data or device sources and is an important part of the application design. Therefore, we don't plan to add this option.
