### ISSUE TITLE
The CSS rule from Annoyances Filter is not applied on kruidvat.nl

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#2102]
@adguard-bot commented on [Thu Dec 29 2022](https://github.com/AdguardTeam/AdguardFilters/issues/138704)

### Issue URL (Incorrect Blocking)
 [https://www.kruidvat.nl/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.kruidvat.nl%2F)
### Comment
> It’s not possible to scroll on mobile safari ios.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/jPFSeyW.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/pVcWleK.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.4.5
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Dutch

---

@Alex-302 commented on [Fri Dec 30 2022](https://github.com/AdguardTeam/AdguardFilters/issues/138704#issuecomment-1367944495)

The rule, which exists in optimized AdGuard Annoyances filter, is not applied https://filters.adtidy.org/ios/filters/14_optimized.txt

```adblock
!+ NOT_OPTIMIZED
kruidvat.nl#$#body { overflow: auto !important; }
```

It works when added to user filter.

**Comment by Alex-302** [comment]
Same problem, same filter
https://github.com/AdguardTeam/AdguardFilters/issues/138708

Rule:

`theflixer.tv,sflix.se,2kmovie.cc,musichq.net,swatchseries.*,1movieshd.com,fmoviesto.*,solarmovie.pe,cineb.net,myflixerhd.ru,hdtoday.*,yesmovies.mn,divicast.com,seriestv.watch,freemoviesfull.com,dopebox.to,fmovies.*,sflix.to,myflixer.to,movies2watch.tv,ev01.to,ummagurau.com,6movies.net,tinyzonetv.to,myflixertv.to,f2movies.to,moviesjoy.*,moviesjoy.*,myflixerhd.ru,soap2day.*,solarmovie.pe,cineb.net#$##modalshare { display: none !important; }`

**Comment by Versty** [comment]
@Alex-302 The page [https://www.kruidvat.nl/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.kruidvat.nl%2F) can be scrolled if you block ads using the Advanced protection option, which relies on the ExtendedCSS rules syntax. 

Therefore, it's not a bug.
