### ISSUE TITLE
Advanced protection doesn't block ads on Kinopoisk in landscape mode

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForiOS#2104]
### Issue URL (Ads)
 [https://www.kinopoisk.ru/film/5235325/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.kinopoisk.ru%2Ffilm%2F5235325%2F)
### Comment
Username: `@rakleed`
> Реклама при горизонтальном окне просмотра, а также раздел с информацией о мобильном приложении 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/otMUKw5.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/nza8kSn.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.4.5
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian

_Originally posted by @adguard-bot in https://github.com/AdguardTeam/AdguardFilters/issues/138698#issuecomment-1372148045_

**Comment by Versty** [comment]
@rakleed Добрый день! 
Помогли ли вам решить проблему в репозитории фильтров?

**Comment by rakleed** [comment]
@Versty нет. Смотрите https://github.com/AdguardTeam/AdguardFilters/issues/138698#issuecomment-1372191014 и ниже

**Comment by Versty** [comment]
@rakleed Павел, мы добавили правило в фильтр раздражителей. Теперь промо мобильного приложения внизу страницы и соответствующая кнопка должны быть заблокированы. 
Пожалуйста, обновите фильтры и проверьте, что проблема устранена. 

Второй баннер получится заблокировать только с помощью AdGuard Extra, подробности можно найти [здесь](https://github.com/AdguardTeam/AdguardFilters/issues/138698#issuecomment-1375676452).

**Comment by rakleed** [comment]
@Versty так а почему Advanced protection не блокирует эту рекламу? Ведь на iOS нет AdGuard Extra.

**Comment by Versty** [comment]
@rakleed В данном случае правила для блокировки содержатся в AdGuard Russian filter, при обновлении фильтра и повторной проверке - баннер тоже заблокировался. Проверьте у себя, пожалуйста.
