### ISSUE TITLE
bitmoji app

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#211]
ha-api.pushwoosh.com
cp.pushwoosh.com

Pushwoosh is used for notification advertising (https://www.pushwoosh.com/features/)

Bitmoji - Your Personal Emoji by Bitstrips
https://appsto.re/us/2_CVZ.i

**Comment by Alex-302** [comment]
ok, added to mobile filter
@gshumihin please check this app with blocked that domains
