### ISSUE TITLE
Filtering is not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#2112]
@adguard-bot commented on [Wed Jan 18 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140410)

### Issue URL (Ads)
 [https://filmix.ac](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Ffilmix.ac)
### Comment
Username: @D3x7er
> На сайті filmix.ac не блокує рекламу

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/DDdp3BJ.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.4.5
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList

---

@jellizaveta commented on [Wed Jan 18 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140410#issuecomment-1387155106)

@D3x7er With your settings, the ads are blocked correctly.  
Please try to disable-enable content blockers in Safari settings and restart Safari, and check for filters update.
Do not close AdGuard window 30-60 seconds.

---

@D3x7er commented on [Wed Jan 18 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140410#issuecomment-1387259051)

> @D3x7er With your settings, the ads are blocked correctly.  
> 
> Please try to disable-enable content blockers in Safari settings and restart Safari, and check for filters update.
> 
> Do not close AdGuard window 30-60 seconds.

 Спробував, все одно не помогло
[image](https://user-images.githubusercontent.com/122988412/213213657-b871edbd-4276-4c67-9a7f-9486b6e40132.png)
[image](https://user-images.githubusercontent.com/122988412/213213744-344e8199-3f3c-4dc8-a13b-ef287730e01a.png)
[image](https://user-images.githubusercontent.com/122988412/213213772-ed7d2347-49dd-4011-b7df-09c6cf1e26b4.png)

---

@Alex-302 commented on [Wed Jan 18 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140410#issuecomment-1387418642)

@D3x7er Проверьте, определяется ли Адгард на этой странице
https://adguard.com/test.html

---

@D3x7er commented on [Thu Jan 19 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140410#issuecomment-1396102038)

@Alex-302 [image](https://user-images.githubusercontent.com/122988412/213296975-884c7d43-8e41-441f-b005-846f907b0474.png)
Не розомію чому не працює 😔

---

@D3x7er commented on [Thu Jan 19 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140410#issuecomment-1396125861)

@Alex-302 но он включен
[image](https://user-images.githubusercontent.com/122988412/213301243-51aabd8b-7058-4391-8ad4-efe6c1aa2967.png)

---

@Alex-302 commented on [Thu Jan 19 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140410#issuecomment-1396661326)

@D3x7er Сделайте скриншот информации про контент-блокеры из Settings -> Advanced settings -> Content blockers (расширенниые настройки -> Контент-блокеры)

---

@D3x7er commented on [Thu Jan 19 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140410#issuecomment-1396691917)

@Alex-302 [image](https://user-images.githubusercontent.com/122988412/213408397-34e7e089-ec40-4cce-9cbc-5d01c048c709.png)

**Comment by Alex-302** [comment]
@D3x7er

**Comment by D3x7er** [comment]
@Alex-302 І коли пробою оновити вискакую таке повідомлення ![image](https://user-images.githubusercontent.com/122988412/213540164-c3a26c84-a92d-4184-ac38-e52b86fd61dc.png)

**Comment by D3x7er** [comment]
@Alex-302 Коли обновляю то вискакує така помилка ![Uploading 213542865...]

**Comment by Versty** [comment]
@D3x7er Добрый день! 
Давайте разберемся в происхождении проблемы. Пожалуйста, переустановите приложение и нажмите на кнопку проверки обновлений еще раз. Появилось ли снова это сообщение об ошибке?

**Comment by Alex-302** [comment]
Аналогичная проблема:
https://github.com/AdguardTeam/AdguardFilters/issues/140691

**Comment by D3x7er** [comment]
@Versty переустановил не помогло

**Comment by Versty** [comment]
@D3x7er 
Пожалуйста, соберите и отправьте нам логи с вашего устройства, следуя инструкции:

1. Откройте настройки приложения -> **Общие** -> Включите **Расширенный режим** -> Расширенные настройки -> Активируйте опцию **Отладочные логи**
2. Воспроизведите проблему и запомните точное время воспроизведения. Оно понадобится нам, чтобы найти соответствующие записи в лог-файле;
4. Откройте вкладку **Настройки** --> Нажмите **Поддержка** --> **Экспортировать логи**;
5. Откроется системное окно, в котором необходимо выбрать приложение "Почта"
6. В качестве получателя укажите `apple@adguard.com`;
7. Укажите номер задачи Github `#2112` и время воспроизведения проблемы в тексте письма.

**Comment by D3x7er** [comment]
@Versty Відправив

**Comment by Versty** [comment]
@D3x7er Спасибо, логи изучили и пришли к выводу, что проблема связана с ошибкой обновления контент-блокеров. 
Это баг, и мы работаем над его исправлением. 

Если у вас появится дополнительная информация, пожалуйста, отправляйте ее нам на почту: `apple@adguard.com`

За статусом исправления проблемы можно следить в обсуждении #2118
