### ISSUE TITLE
Block CNN.com and CNN app video ads - I bet you all can not do it but at least I asked

### ISSUE THREAD

**Issue by ng4ever** [AdguardTeam/AdguardForiOS#2116]
Is this possible? If so how on iOS please?

**Comment by Versty** [comment]
@ng4ever Hi! 
Safari has no possibilities to block ads embedded in the video player.
Cnn.com uses regional advertisement targeting, that means AdGuard VPN can handle this annoyance if you connect to the proper location. The same is applicable to the CNN app. For example, if you connect to the Turkey, you will see no video ads on cnn.com.
