### ISSUE TITLE
Consider mirroring the repos to Codeberg

### ISSUE THREAD

**Issue by throwaway-d** [AdguardTeam/AdguardForiOS#2117]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

1. Codeberg is libre, free, open-source, privacy-friendly, non-profit, really fast
2. GitHub has bloated interface with captcha & GitHub is privacy-invasive, Microsoft-owned, proprietary, vendor-lock-in, Tor-hostile
3. People on Codeberg like me can contribute to the project
4. GitHub can take down our repos

### Proposed Solution

Please consider mirroring repos to Codeberg

### Additional Information

Here are some sources for you written by me: https://codeberg.org/HexagonCDN/Mirror_to_Codeberg

**Comment by Versty** [comment]
@throwaway-d Hi! Thank you for the suggestion. 
Currently we are mostly using GitHub as a public bug tracker for our non-open source projects. 
Therefore, we have no plans to migrate or mirror to the Codeberg in near future.
