### ISSUE TITLE
Filter update error

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForiOS#2118]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard for iOS 4.4.5
- **Device model and storage size:**
  - iPhone XR
- **Operating system and version:**
  -  iOS 16.2

### Expected Behavior

Filters are updated without errors.

### Actual Behavior

Error when updating filters in recent weeks has become very common.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

Logs sent to apple@adguard.com

**Comment by Versty** [comment]
@rakleed Hi! Thanks for pointing out the bug. 
Your logs have been received and examined. In some cases, updating filters can cause the content blockers error. 
This issue will be fixed in the future version.

**Comment by artemiv4nov** [comment]
We're working on this problem, the issue will be solved in the v4.6 version.

**Comment by AidanGee7** [comment]
This issue is still happening on the latest TestFlight version and iOS 17 beta 3

**Comment by artemiv4nov** [comment]
@rakleed I noticed before the issue will be fixed in the v4.6 version. This version has not been release yet, please wait for updates.

**Comment by user081five** [comment]
When will version 4.6 be released and what work around is available while waiting for it?
