### ISSUE TITLE
Use issue forms in this GitHub repository

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForiOS#2120]
Could you please use the issue forms in this GitHub repository, as you have done in many of your other repos? More details: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by Versty** [comment]
@rakleed Hi! 
New issue templates are implemented. Check it out!

**Comment by rakleed** [comment]
@Versty @Birbber @ESurina why did you roll back these https://github.com/AdguardTeam/AdguardForiOS/pull/2100 changes?
