### ISSUE TITLE
Add link to DNS System Settings after enabling native DNS

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForiOS#2123]
### Issue Details

After enabling native DNS, I have to manually open System Settings and manually search for the DNS section, which is very inconvenient.

<details><summary>Screenshot</summary>

![827F1E73-EC76-4D3A-98A5-DCDAB11207A3](https://user-images.githubusercontent.com/19418601/216753378-e2702767-6c50-407d-a19d-5d4801b3e532.png)

</details>

### Proposed solution

Add a link to DNS System Settings after enabling native DNS.

**Comment by jslawler** [comment]
Here's the settings link for it: prefs:root=General&path=ManagedConfigurationList/DNS

For the time being, this shortcut will suffice as well if needed.

https://www.icloud.com/shortcuts/95d6102f88734abeb0731f90a1cba209

**Comment by rakleed** [comment]
This is a duplicate of https://github.com/AdguardTeam/AdguardForiOS/issues/1824, but there was no mention of native DNS in it, although this is exactly what it is about.

And besides, more than 1.5 years have passed, and you still haven’t added such a feature, although it doesn’t look difficult to implement (since [encrypted DNS support appeared only with iOS 14](https://adguard.com/en/blog/encrypted-dns-ios-14.html), accordingly, there will be one URL scheme). Why?

**Comment by Versty** [comment]
@rakleed @jslawler Thank you for the request and the proper solution.  
We prioritise the implementation of requests according to importance to users. 
This part of the app will be improved for sure. If you would like to speed up the process, vote for the feature request by putting 👍 emoji on the main post in #1824.
