### ISSUE TITLE
Make minimum required iOS/iPadOS version 14 or 15

### ISSUE THREAD

**Issue by GiddyGoatGaming** [AdguardTeam/AdguardForiOS#2130]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

iOS 11.2 came out in 2017 which is over 5 years ago. Barely any devices run the os nowadays and should be considered to be “obsolete”. I propose that the new minimum required version of Adguard on iOS and iPadOS to be somewhere in the range of iOS 14 to 15. Apps like wireguard just dropped support for iOS 12 and moved up to iOS 15

More features available to implement. Easier to maintain the app without bugs on previous versions of os’s

### Proposed Solution

Update the required iOS and iPadOS version to something like iOS 14.0 or later (or something like 15.0 or later for example).

**Comment by Versty** [comment]
@GiddyGoatGaming Hi! 
Although we have plans to raise the minimum requirements over time, currently we deliver the best possible service to the users with the obsolete devices either. A user's desire to block annoying banners or tracking does not depend on the iOS they are using.
