### ISSUE TITLE
Bring h3:// (DoH3) support to iOS

### ISSUE THREAD

**Issue by GiddyGoatGaming** [AdguardTeam/AdguardForiOS#2131]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Currently, adguard iOS doesn’t let me use a dns that has h3:// at the start of the upstream name. The windows app is compatible with http/3 but not iOS. I’m asking for the option to use an upstream with h3:// at the beginning while using adguard implementation or if possible, native.

### Proposed Solution

Add the option to use upstreams containing h3:// at the beginning

**Comment by jslawler** [comment]
#2113

**Comment by GiddyGoatGaming** [comment]
> #2113

Thanks for the speedy reply. That is amazing to hear it is in a new version of dnslib!
