### ISSUE TITLE
AdGuard Safari Protection no longer filters content at all on iOS 16.4 beta

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForiOS#2134]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS Pro 4.4.5(990)
- **Device model and storage size:**
  - iPhone 13 Pro 128gb
- **Operating system and version:**
  - iOS 16.4 (20E5223e)
- **Browser or App:**
  - Safari

### Expected Behavior

AdGuard for iOS Pro no longer filters content in Safari at all. Prior to the update from iOS 16.3 to iOS 16.4 beta 1 it was working as expected. There have been no changes to AdGuard for iOS that would cause this to happen.
Loading the same pages on a device running iOS 16.3 and iOS 16.4, iOS 16.3 operates correctly, but iOS 16.4 does not.

I have tried the following solutions, with no changes being observed:

- Reinstalled the app
- Reset AdGuard for iOS Pro's settings
- Disabled/enabled Safari extensions
- Disabled/enabled filters
- Disabled/enabled Safari Protection
- Using system DNS, AdGuard DNS profile, AdGuard DNS provided by AdGuard for IOS
- Using an unfiltered DNS server (AdGuard DNS Unfiltered) and watching the query log within AdGuard for iOS (absolutely nothing was blocked on ad heavy news websites such as news.com.au and The Guardian)

### Actual Behavior

AdGuard for iOS content blockers filter correctly in Safari

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

[Here](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes) are the Safari changes in iOS 16.4. Something probably breaks the way AdGuard for iOS handles content blocking.

Debug logs have been sent to support@adguard.com, under ticket #725887.

**Comment by aleksan4eg** [comment]
I'm experiencing the same. On iPhone 12, iOS 16.2. Adguard v4.4.5(990)

**Comment by GiddyGoatGaming** [comment]
> I'm experiencing the same. On iPhone 12, iOS 16.2. Adguard v4.4.5(990). I believe the latest update breaks ad content blocking.

Works for me on iOS 16.3.1. Try turning off safari content blockers in settings and restarting your device and then reenable it. That worked for me when I updated from iOS 15 to 16 and stopped working for me

**Comment by Versty** [comment]
@jslawler @aleksan4eg @GiddyGoatGaming 
Please make sure you have granted the access to the Safari extensions for the AdGuard in the system settings.  

1. Open `Settings` -> `Safari` -> `Extensions` 
2. Make sure in the `Allow this extensions` section AdGuard is set to ON 
3. Tap this setting and in the `Permissions` section select `Allow` for All Websites

**Comment by Versty** [comment]
@jslawler @aleksan4eg @GiddyGoatGaming 
Please make sure you have granted the access to the Safari extensions for the AdGuard in the system settings.  

1. Open `Settings` -> `Safari` -> `Extensions` 
2. Make sure in the `Allow this extensions` section AdGuard is set to ON 
3. Tap this setting and in the `Permissions` section select `Allow` for All Websites

**Comment by jslawler** [comment]
All permissions and extensions are allowed. They have all been toggled off, and on, to ensure there was also no issue there.

**Comment by jslawler** [comment]
Hi @Versty,

Just an update. iOS 16.4 Developer Beta 2 released today, and AdGuard still does not filter content with Safari protection.

I did a fresh install of AdGuard Pro and wiped all backups before reinstalling.

The result is the same as reported above.

<details><summary>Screenshots of setup</summary>
<p>

![image](https://user-images.githubusercontent.com/95468948/222021301-0a037499-04de-4dac-80fa-22081bbdf9f4.jpeg)
![image](https://user-images.githubusercontent.com/95468948/222021316-47f63082-cce9-425a-9c44-58c0da97af4c.jpeg)
![image](https://user-images.githubusercontent.com/95468948/222021328-118db904-a486-4114-93f6-7cf4e3878927.jpeg)
![image](https://user-images.githubusercontent.com/95468948/222021345-3cb3a3fe-a9b3-4ea1-8d53-2b4455be191e.jpeg)
![image](https://user-images.githubusercontent.com/95468948/222021361-9d5301f1-de74-4471-bf32-9ec5fbc9fc45.jpeg)
![image](https://user-images.githubusercontent.com/95468948/222021380-33a8c777-2d49-4491-a277-90f60327bf61.jpeg)

</p>
</details>

**Comment by Versty** [comment]
@jslawler Thank you for the update, we are investigating.

**Comment by jslawler** [comment]
Just an FYI.

Clean reinstall of iOS 16.4 beta 2 carried out today, and rapid security release b installed.

Reported issue remains.

**Comment by jslawler** [comment]
@Versty this appears to be resolved in the latest beta release of iOS. I'll close the issue, but if you've come across something in the logs that were sent through, feel free to reopen it.
