### ISSUE TITLE
AdGuard Pro iOS internet does not work when using my phone as a hotspot with my iPad when AdGuard DNS is on :( 

### ISSUE THREAD

**Issue by ng4ever** [AdguardTeam/AdguardForiOS#2135]
Adguard 4.4.5
iPad Pro 11 inch 128 GB (4 th generation)
iOS 16.3.1

Internet does not work at all when AdGuard DNS is enabled while using my iPhone's hotspot when adGuard DNS is enabled on iPad Pro :( 

Maybe this is a user error and would not be surprised but doubt it. Worked on my older iPad fine.

**Comment by ng4ever** [comment]
Fixed I knew there was something I was missing. 

I did not set the DNS on the iPad to AdGuard DNS just the default DNS.

**Comment by Versty** [comment]
@ng4ever Glad everything is working well!
