### ISSUE TITLE
Support Apple passkeys

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#2137]
_Based on industry standards for account authentication, passkeys are easier to use than passwords and far more secure. Adopt passkeys to give people a simple, secure way to sign in to your apps and websites across platforms — with no passwords required._

[What are Passkeys?](https://developer.apple.com/passkeys/)
[Developer documentation](https://developer.apple.com/documentation/authenticationservices/public-private_key_authentication/supporting_passkeys)

**Comment by artemiv4nov** [comment]
In the 5.0 version, we will introduce new way to log in, please follow updates
