### ISSUE TITLE
Official AdGuard MobileConfig -  is it DoH or DoT or both? Why boostrap over plaintext?

### ISSUE THREAD

**Issue by GY8VSdYYzvL8-K6T** [AdguardTeam/AdguardForiOS#2140]
AdGuard's official MobileConfig (https://cdn.adtidy.org/public/Dns/adguard-dns.mobileconfig) lists DNS over HTTPS in XML file, but my Apple device sometimes sends queries over TCP port 853 (DNS over TLS) as well. Is it that just a fallback or do MobileConfig XML files support both DoT and DoH at the same time?

I also noticed that the official MobileConfig still uses plaintext UDP port 53 to resolve dns.adguard.com. That's not necessary if IP address (https://94.140.14.14/dns-query) is specificed instead of URL (https://dns.adguard.com/dns-query), but I don't know if Apple supports such a configuration.

Can you please update?

**Comment by Versty** [comment]
@GY8VSdYYzvL8-K6T Hi! 
Your original issue has been transferred to the AdGuardDNS repository, where it belongs: https://github.com/AdguardTeam/AdGuardDNS/issues/554.
Please monitor it for an answer.
