### ISSUE TITLE
iOS 15.0-1.1.1 jailbreak xina15 causes issues

### ISSUE THREAD

**Issue by gototheskinny** [AdguardTeam/AdguardForiOS#2143]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details
While using iOS 15.0-1.1.1 jailbreak xina15 on an iPhone 12 ios 15.0 adguard for ios premium, randomly some sites doesn't work properly like the NON-JB environment. For example  [This issue](https://github.com/AdguardTeam/AdguardFilters/issues/144552) is not there while I switch to NON-JB env. I love this app I'm a paying customer for this app please look into this issue why is this happening? I'm not a coder whatsoever but I'm willing to test or whatever I could do to help you guys to fix this issue.

- **AdGuard version:**
  -  4.4.5(990)
- **Device model and storage size:**
  - iPhone 12 64gb
- **Operating system and version:**
  - 15.0 w/ xina15 jailbreak
- **Browser or App:**
  - Safari for iOS

### Expected Behavior
![8EAAD66E-9BE9-450D-8F30-D8D86D5897C7](https://user-images.githubusercontent.com/51786709/223878460-cc35ffdc-9c09-48a4-8abb-3b9e9d095761.png)

### Actual Behavior
![3A157CCF-563F-4FE3-A006-B228481C5E1A](https://user-images.githubusercontent.com/51786709/223878572-b70cc42f-2877-4e74-89b0-613119f98746.png)

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Versty** [comment]
@gototheskinny Could you please make it clear if we have understood you correctly? 
You have 2 iOS devices with the same version of AdGuard and the same settings. On the uncracked device the filtering works fine, but on the second device filtering does not work in half of the cases.

**Comment by Versty** [comment]
@gototheskinny Got it. Let's find out what went wrong with the jailbreak on board. 

Please follow the steps below to collect and sent debug logs from your device:
1. Make sure the jailbreak enabled 
1. Open Settings --> General --> Turn Advanced mode on --> Advanced settings --> Turn Debug logs switch on;
2. Reproduce the issue and remember the exact time when it happened;
3. Open the settings --> Support --> Export logs;
4. System popup will be opened --> Choose "Mail" app;
5. Enter apple@adguard.com as a recipient;
6. Mention this issue number `#2143` in the subject and add the time the issue was reproduced at.

**Comment by gototheskinny** [comment]
> @gototheskinny Got it. Let's find out what went wrong with the jailbreak on board. 
> 
> 
> 
> Please follow the steps below to collect and sent debug logs from your device:
> 
> 1. Make sure the jailbreak enabled 
> 
> 1. Open Settings --> General --> Turn Advanced mode on --> Advanced settings --> Turn Debug logs switch on;
> 
> 2. Reproduce the issue and remember the exact time when it happened;
> 
> 3. Open the settings --> Support --> Export logs;
> 
> 4. System popup will be opened --> Choose "Mail" app;
> 
> 5. Enter apple@adguard.com as a recipient;
> 
> 6. Mention this issue number `#2143` in the subject and add the time the issue was reproduced at.
> 
> 

OK. I'm doing it right know.

**Comment by gototheskinny** [comment]
Done. if there is any issues please let me know

**Comment by gototheskinny** [comment]
> @gototheskinny Got it. Let's find out what went wrong with the jailbreak on board. 
> 
> 
> 
> Please follow the steps below to collect and sent debug logs from your device:
> 
> 1. Make sure the jailbreak enabled 
> 
> 1. Open Settings --> General --> Turn Advanced mode on --> Advanced settings --> Turn Debug logs switch on;
> 
> 2. Reproduce the issue and remember the exact time when it happened;
> 
> 3. Open the settings --> Support --> Export logs;
> 
> 4. System popup will be opened --> Choose "Mail" app;
> 
> 5. Enter apple@adguard.com as a recipient;
> 
> 6. Mention this issue number `#2143` in the subject and add the time the issue was reproduced at.
> 
> 

Any news on this issue? I hope there's a fix for us jb users🤞

**Comment by Versty** [comment]
@gototheskinny Sorry for the delayed reply. 

We should inform you that AdGuard doesn't provide official compatibility with any jailbreak apps. 
Therefore, this issue is closed.

**Comment by gototheskinny** [comment]
> @gototheskinny Sorry for the delayed reply. 
> 
> 
> 
> We should inform you that AdGuard doesn't provide official compatibility with any jailbreak apps. 
> 
> Therefore, this issue is closed.

What about debug logs why did you ask for it than? You could've told me this a month ago when I opened this issue.
