### ISSUE TITLE
AdGuard TestFlight has disappeared and showing ‘This beta isn’t accepting new testers rights now’ 

### ISSUE THREAD

**Issue by L3wDuu** [AdguardTeam/AdguardForiOS#2145]
### Issue Details

The current AdGuard testflight build has now expired and has disappeared from the testflight app. When trying to add the testflight again through: https://adguard.com/en/beta.html it gives the error “This beta is not accepting new testers right now”

- **AdGuard version:**
Latest

### Expected Behavior

AdGuard TestFlight app should be available 

### Actual Behavior

Current build has expired and unable to sign up to new builds via TestFlight 

### Screenshots

  
![image](https://user-images.githubusercontent.com/8878962/225046476-b2650ec2-1343-42e8-b577-da85699d56ec.jpeg)

<details><summary>Screenshot:</summary>

</details>

**Comment by artemiv4nov** [comment]
Hello! The new beta is already available in TestFlight, please re-check

**Comment by Ryan-Goldstein** [comment]
I do see version 4.4.5 (990) available in TestFlight, but it shows that it expires in 2 days.

**Comment by Ryan-Goldstein** [comment]
I now see `Tester Removed`, and the link at https://adguard.com/en/beta.html?platform=ios indicates "This beta isn't accepting any new testers right now." again.

**Comment by Albaniamd** [comment]
Same experience. 
![94EF8062-36E7-4F4B-B535-FFF4053F4DDA](https://user-images.githubusercontent.com/29474647/225772631-1dd8ce72-625b-4019-8bc0-6cbdc14b435f.jpeg)

**Comment by tonyping** [comment]
Yep, it's expired. @adguard @Versty  can you please renew the TestFlight?
