### ISSUE TITLE
Testflight expired

### ISSUE THREAD

**Issue by tonyping** [AdguardTeam/AdguardForiOS#2146]
I now see `Tester Removed`, and the link at https://adguard.com/en/beta.html?platform=ios indicates "This beta isn't accepting any new testers right now." again.

_Originally posted by @Ryan-Goldstein in https://github.com/AdguardTeam/AdguardForiOS/issues/2145#issuecomment-1472814973_

Re-opening this issue, as the first one was closed without a resolution.

**Comment by Versty** [comment]
@tonyping Previous beta build has expired but a new one will be available in the TestFlight very soon! You will be able to test it as usual.

**Comment by tonyping** [comment]
> @tonyping Previous beta build has expired but a new one will be available in the TestFlight very soon! You will be able to test it as usual. 

@Versty Thanks👍. One thing I might suggest though (taken from my experience with other TestFlights), is that in these cases of near-expiry without a suitable build, its better practice to push the identical build to just reset the timer, rather than letting it lapse and potentially boot a sizable portion of the tester pool.

**Comment by jslawler** [comment]
Additionally to the above, it doesn't just boot all users, it stops the app from working without a user friendly message to say that the period has expired, and the App Store version must be installed to continue use.
