### ISSUE TITLE
White border around element blocker on Google.com (dark mode)

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForiOS#2147]
### Issue Details

- **AdGuard version:**
  - 4.4.5(990)
- **Device model and storage size:**
  - iPhone 13 Pro 128gb
- **Operating system and version:**
  - iOS 16.4 (20E246)
- **Browser or App:**
  - As above.

### Expected Behavior

<p align="left">
<img src="https://user-images.githubusercontent.com/95468948/226816457-020da930-bd24-44fd-a202-0a29d680b065.png" width="300" height="650">
</p>

### Actual Behavior 

<p align="left">
<img src="https://user-images.githubusercontent.com/95468948/226816496-401150be-dc9f-49fb-991c-61c511650c69.jpeg" width="300" height="650">
</p>

**Comment by Versty** [comment]
@jslawler Thank you for the report. The issue reproduces on your devices as well.

**Comment by jslawler** [comment]
If you need another example of it, it also occurs on https://www.macrumors.com.

![image](https://user-images.githubusercontent.com/95468948/235650625-93dea28f-b208-477e-abc3-317e691d3953.png)
