### ISSUE TITLE
:has() pseudo-class defaults to extended CSS rule

### ISSUE THREAD

**Issue by pkrayzy** [AdguardTeam/AdguardForiOS#2148]
Adguard / SafariConverterLib treats all :has() pseudo-class rules as advanced extended CSS rules, however Safari and WebKit natively support CSS Selectors Level 4, including :has().

Rules prefixed with ## should default to a standard CSS rule, while more complicated and nested use of :has() prefixed with #?# or #$?# should be treated as an advanced extended CSS selector rule.

**Comment by Versty** [comment]
@pkrayzy During the development process we have discovered the [bug in the WebKit](https://bugs.webkit.org/show_bug.cgi?id=248868) that prevented us from making changes related to the `:has()` pseudo-class rules. This bug has recently been fixed, so we will continue to work on this improvement.  

Follow up the progress: https://github.com/AdguardTeam/SafariConverterLib/issues/43

**Comment by pkrayzy** [comment]
@Versty Thanks so much!
