### ISSUE TITLE
www.techbone.de Cookie filter not applied

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdguardForiOS#2149]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 4.4.5
- **Device model and storage size:**
  - iPhone Xs Max
- **Operating system and version:**
  -  16.3.1
- **Browser or App:**
  -  Safari

### Screenshots

<details><summary>Screenshot:</summary>

![68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f4755586b7544772e706e67](https://user-images.githubusercontent.com/6276915/227481269-e5bfe65a-3216-404e-8af8-b324d44b33ac.png)

</details>

### Additional Information

Refering to @Alex-302 the issue should be reported here.
Ticket: https://github.com/AdguardTeam/AdguardFilters/issues/146076

The filter to block Cookie Pop-up are included in Annoyance filter, but do not work. Other filters works fine on my phone. So he advised to open a ticket here.

**Comment by Versty** [comment]
@Morku Hi! 
The rules contained in the filter are not correct at the moment. 
As a temporary solution you can add this rules to the User rules. Annoyance filter will also be improved by @Alex-302. 

```
techbone.de#$#body { overflow: auto !important; padding-right: 0 !important; }
techbone.de#$##cookie_banner { display: none !important; }
techbone.de#$##cookie_banner ~ div.modal-backdrop { display: none !important; }
```
