### ISSUE TITLE
Yandex maps app works slowly

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#215]
Здравствуйте,заметил что когда включён Dns vpn,очень долго загружаются пробки в приложении Яндекс карты,отключив dns загружается моментально. Без dns загрузка 2 секунды, с dns 25 секунд.

Logs: 1112721

**Comment by gshumihin** [comment]
Wasn't able to reproduce this issue.

**Comment by gshumihin** [comment]
According to the log, average response time is 100-200 miliseconds.
