### ISSUE TITLE
A new protocol, DNS over QUIC, causes network performance lag.

### ISSUE THREAD

**Issue by MadeByPP** [AdguardTeam/AdguardForiOS#2150]
### Issue Details

same as title.  When dns protection is set to Adguard dns (DNS over QUIC), a delay of more than 2000 ms occurs.  I will attach a picture for help.

- **AdGuard version:**
  - AdGuard for iOS v4.4.5
- **Device model and storage size:**
  - iPhone 13 mini 128gb
- **Operating system and version:**
  - 16.4

### Expected Behavior

Should have the same or lower latency as DNS over HTTPS.

### Actual Behavior

Significantly greater latency than DNS over HTTPS

### Screenshots

<details><summary>Screenshot:</summary>

![IMG_1054](https://user-images.githubusercontent.com/64509269/228722826-4fcfc39a-4a9f-45cf-9412-4590e6cfda5f.png)
![IMG_1055](https://user-images.githubusercontent.com/64509269/228722857-48701abf-c493-42c7-aa65-2457d11f8938.png)

</details>

**Comment by Versty** [comment]
@MadeByPP Hi! 
Does this issue reproduce with AdGuard DNS Family Protection (DNS over QUIC) and AdGuard DNS Non-filtering (DNS over QUIC)? Please check on both Wi-Fi and cellular data.

**Comment by MadeByPP** [comment]
![IMG_1118](https://user-images.githubusercontent.com/64509269/229948516-a70d099e-d20d-4349-b48e-2d0e9c6f8ba0.png)

Latency of 5900 ms.  The symptoms occur on both Wi-Fi and data.

**Comment by martinspaniol** [comment]
+1

Same for me. Very high latencies of more than 3 seconds on AdGuard for iOS.

**Comment by Versty** [comment]
@martinspaniol @MadeByPP We have tried to reproduce this issue but to no avail. 
Could you send the logs from your device so we can take a look? 

1. Open Settings --> General --> Turn Advanced mode on --> Advanced settings --> Turn Debug logs switch on;
2. Reproduce the issue and remember the exact time when it happened;
3. Open the settings --> Support --> Export logs;
4. System popup will be opened --> Choose "Mail" app;
5. Enter apple@adguard.com as a recipient;
6. Mention this issue number `#2150` in the subject and add the time the issue was reproduced at.

**Comment by martinspaniol** [comment]
> @martinspaniol @MadeByPP We have tried to reproduce this issue but to no avail. Could you send the logs from your device so we can take a look?
> 
> 1. Open Settings --> General --> Turn Advanced mode on --> Advanced settings --> Turn Debug logs switch on;
> 2. Reproduce the issue and remember the exact time when it happened;
> 3. Open the settings --> Support --> Export logs;
> 4. System popup will be opened --> Choose "Mail" app;
> 5. Enter [apple@adguard.com](mailto:apple@adguard.com) as a recipient;
> 6. Mention this issue number `#2150` in the subject and add the time the issue was reproduced at.

I just submitted the logs.

**Comment by MadeByPP** [comment]
I also just sent a log about this issue.  I accidentally forgot to mention the time, it's 8:30.

**Comment by MadeByPP** [comment]
> @martinspaniol @MadeByPP We have tried to reproduce this issue but to no avail. Could you send the logs from your device so we can take a look?
> 
> 1. Open Settings --> General --> Turn Advanced mode on --> Advanced settings --> Turn Debug logs switch on;
> 2. Reproduce the issue and remember the exact time when it happened;
> 3. Open the settings --> Support --> Export logs;
> 4. System popup will be opened --> Choose "Mail" app;
> 5. Enter [apple@adguard.com](mailto:apple@adguard.com) as a recipient;
> 6. Mention this issue number `#2150` in the subject and add the time the issue was reproduced at.

I also just sent a log about this issue.  I accidentally forgot to mention the time, it's 8:30.

**Comment by Versty** [comment]
@MadeByPP @martinspaniol Thank you. 
This issue is under investigation, we are examining both log files.

**Comment by Versty** [comment]
@MadeByPP @martinspaniol Hi there! 
Please upgrade the version of AdGuard for iOS to the latest and check if the issue persists.

**Comment by MadeByPP** [comment]
I can no longer check the average latency because the average time item has disappeared in the main UI. Is there any other way to check?

**Comment by martinspaniol** [comment]
@Versty is there any way to check the latency in the UI with the new version?

**Comment by Versty** [comment]
@martinspaniol I don't think there is a way to test latency in the UI at this point. 
The application is currently under refactoring, we will keep an eye on this issue in the new version.

**Comment by MadeByPP** [comment]
@Versty It's hard to predict how the main UI will change in the future because the code is being refactoring, but I think it's okay to check the average latency elsewhere, even if it's not in the main UI.

**Comment by Versty** [comment]
@MadeByPP Will be fixed as a part of https://github.com/AdguardTeam/AdguardForiOS/issues/2161
