### ISSUE TITLE
Support for vpn while using AdGuard dns

### ISSUE THREAD

**Issue by overwatch3560** [AdguardTeam/AdguardForiOS#2155]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

You can't use other vpn apps like NordVPN or expressvpn while using all functions in the AdGuard app
### Proposed Solution

ADD support for using a vpn other than AdGuard vpn while using all functions in AdGuard for iOS and android

**Comment by Versty** [comment]
@overwatch3560 If the third-party VPN supports IPSec protocol, it can be used with AdGuard on the iOS device. 
Make sure the tunnel mode in AdGuard is set to `Split-Tunnel`.

For Android, if the device is rooted, we suggest using AdGuard in Auto proxy mode. Which makes it possible to use AdGuard with any VPN you like.
