### ISSUE TITLE
AdGuard Annoyances filters

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForiOS#2166]
I noticed that on AdGuard for Safari and AdGuard for Mac that the AdGuard Annoyances filter is no longer recommended (I assume because it's now split into its 5 seperate categories), yet it remains recommended on AdGuard for iOS.

Is this intentional?

**Comment by jslawler** [comment]
Reinstalling fixed this issue. It seems filter tags # may be held in the app somewhere?

**Comment by Versty** [comment]
@jslawler Tags are included in the [metadata file](https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/filter_4_Social/metadata.json) that comes with the filter.

**Comment by jslawler** [comment]
Thanks @Versty, I thought as much.
For whatever reason the tags weren't updating. This resolved itself after a reinstall of AdGuard.
