### ISSUE TITLE
Investing.com app tracker

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#217]
api.appsee.com

Investing.com - Stocks, Forex, Futures & News by Fusion Media Limited
https://appsto.re/us/QGxp2.i

**Comment by jo2dan23** [comment]
@Alex-302

**Comment by Alex-302** [comment]
Added

**Comment by Alex-302** [comment]
It uses also for crash recordings. @ameshkov should we block it?

**Comment by jo2dan23** [comment]
It records them for the company meaning it probably sends other information also

**Comment by Alex-302** [comment]
Ok, which information it sends? I can't add domain to filter without confidence.

**Comment by jo2dan23** [comment]
Watch every action your users do and understand exactly how they use your app

Says that on the site

**Comment by ameshkov** [comment]
@Alex-302 it seems to be more about "tracking" and not valuable functionality. Let's block it.

**Comment by Alex-302** [comment]
Ok, added
