### ISSUE TITLE
Convert filters using GitHub actions

### ISSUE THREAD

**Issue by specter78** [AdguardTeam/AdguardForiOS#2172]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Presently, filter lists are downloaded in Adblock format and then converted in safari format. 

This consumes time and battery, and is slow, especially on older devices. 

### Proposed Solution

Convert these filters using GitHub Actions, every 5 minutes, and use these directly instead of converting them on device. 

Since there are many filters, it can at least be done for inbuilt filters (adguard and easylist) and the rest can be converted on the device.

**Comment by jslawler** [comment]
It would be greatly appreciated to be able to have something such as this to avoid having to do all the conversion on-device.

It's not uncommon to have to manually open the app and update the filters, whilst waiting a couple of minutes for the process to finish.

Taking a look at many of the GitHub filter issues raised, the comments from filter developers often refer to the manual updating of the filters to reproduce or rectify issues not solved by the devices onboard updating process.

**Comment by Versty** [comment]
@specter78 Hi! Thank you for the interesting suggestion! 
Unfortunately, we do not have the technical possibility to convert the rules externally, because all enabled filters must be converted together. Each combination of filters will be converted to a different set of rules, which means that a lot of sets have to be maintained every 5 minutes.
