### ISSUE TITLE
`:contains` pseudo-selector doesn't work

### ISSUE THREAD

**Issue by DetachHead** [AdguardTeam/AdguardForiOS#2174]
### Issue Details
rules with the `:contains` pseudo-selector in them do not seem to work in safari on iOS.

example:
```
google.com##div:contains(/Trending/)
```

- **AdGuard version:**
  - 4.4.6
- **Device model and storage size:**
  - iphone 13 128gb
- **Operating system and version:**
  - iOS 15.1.1
- **Browser or App:**
  - safari

### Expected Behavior
"Trending Searches" element blocked (along with its parent divs)

### Actual Behavior
no elements blocked

### Screenshots

<details><summary>Screenshots:</summary>

![image](https://github.com/AdguardTeam/AdguardForiOS/assets/57028336/6f94037d-de64-4fd1-9ace-e7dbc454a652)
![image](https://github.com/AdguardTeam/AdguardForiOS/assets/57028336/c95bf050-896b-4f39-9781-6460f3d9e7ba)

</details>

### Additional Information
tested on chrome and it worked, so the issue seems specific to either safari or ios

**Comment by Versty** [comment]
@DetachHead Hi! 
Does the issue persist on the latest version of AdGuard for iOS (4.5)?
We have tried to reproduce the issue but it works fine on our side.
Please make sure that the Advanced protection is enabled in AdGuard and [Safari settings](https://adguard.app/kb/adguard-for-ios/web-extension/#how-to-enable-adguards-safari-web-extension) are configured properly.

**Comment by DetachHead** [comment]
It seems to be working now, however it seems like I need to close safari and disable & re-enable the rule multiple times before rule changes are applied. Thanks
