### ISSUE TITLE
`:xpath` pseudo-selector doesn't work on some sites

### ISSUE THREAD

**Issue by DetachHead** [AdguardTeam/AdguardForiOS#2175]
### Issue Details
xpath rules don't seem to work on some websites

works:
```
google.com##:xpath(//*)
```
doesn't work:
```
m.facebook.com##:xpath(//*)
```

- **AdGuard version:**
  - 4.4.6
- **Device model and storage size:**
  - iphone 13 128gb
- **Operating system and version:**
  - iOS 15.1.1
- **Browser or App:**
  - safari

### Expected Behavior

everything blocked on both sites

### Actual Behavior

- `google.com` - everything blocked
- `m.facebook.com` - nothing blocked

### Screenshots
<details><summary>rules:</summary>

![image](https://github.com/AdguardTeam/AdguardForiOS/assets/57028336/56c9a11d-1da7-4d7e-9c50-3b0f5ff6da60)

</details>
<details><summary>google.com:</summary>

![image](https://github.com/AdguardTeam/AdguardForiOS/assets/57028336/2357fd61-958d-4cb9-bff3-a0428cf071e4)

</details>
<details><summary>m.facebook.com:</summary>

![image](https://github.com/AdguardTeam/AdguardForiOS/assets/57028336/fdadac3d-8d45-4e5a-ae2b-06f539f0a749)

</details>

### Additional Information
i know the facebook screenshot says "facebook.com" in the url bar but the full url is actually "m.facebook.com/..." safari just shortens it

**Comment by Versty** [comment]
@DetachHead Does the `xpath` selector work as expected with the AdGuard for iOS 4.5 version? 
Could be the same problem as https://github.com/AdguardTeam/AdguardForiOS/issues/2174


We have tried to reproduce with rules mentioned above, but both websites are blocked correctly on our side.

**Comment by Versty** [comment]
@DetachHead Any updates?
