### ISSUE TITLE
Fox communities app tracker 

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#218]
checkip.amazonaws.com

Fox Communities Credit Union by Fox Communities Credit Union
https://appsto.re/us/6VZTL.i

**Comment by jo2dan23** [comment]
@Alex-302

**Comment by ameshkov** [comment]
@jo2dan23 not sure about this.

I mean the only purpose of that domain is to return your IP address: `checkip.amazonaws.com`
It does not track you.
