### ISSUE TITLE
Local VPN intermittently failing to reconnect when out of range of wifi, preventing internet access (DoH3)

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForiOS#2184]
### Issue Details

- **AdGuard version:**
  - 4.5
- **Device model and storage size:**
  - iPhone 13 Pro 128gb
- **Operating system and version:**
  - 16.6

### Expected Behavior

Local VPN reconnects when connecting to mobile connection after dropping out of range of wifi.

### Actual Behavior

Local VPN intermittently fails to reconnect after falling out of range of wifi and switching to a mobile connection, causing a total loss of internet until the mobile data is toggled manually, forcing the local VPN to connect again.

### Additional Information

Logs sent to apple@adguard.com, with the GH issue as the subject.

**Comment by ameshkov** [comment]
Could you please check if there are any crash reports from AdGuard tunnel?

Settings -> Privacy -> Analytics & Improvements -> Analytics Data

**Comment by ameshkov** [comment]
@jslawler look for a file named "Tunnel" there

**Comment by Versty** [comment]
@jslawler Hi! We have examined the logs and crash report from your device, there is nothing pointing to specific errors in the AdGuard app. In your case, the unstable operation of the application may be caused by the beta version of iOS itself.

**Comment by Versty** [comment]
@jslawler Temporary closed, please reopen if the issue reproduces on a stable version of iOS.

**Comment by ameshkov** [comment]
@jslawler that's different, VPN reconnection is a normal thing to happen. For instance, whenever settings change AdGuard will reconnect.

In your case the VPN was actually crashing without any visible reason for that. Unfortunately, crash report is not helpful at all so there's a chance that the crashes are due to iOS internal bugs.

**Comment by ameshkov** [comment]
Note that reconnection also occurs on a network change and by itself the reconnection is not a problem.

> The first reconnection killed the network entirely

The question is was the network okay at that moment or could it be that the signal was bad at the time?
