### ISSUE TITLE
master branch not up to date

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#2185]
It looks like the latest master is still showing [v4.4.3](https://github.com/AdguardTeam/AdguardForiOS/blob/41f284e6ca450bdc0e15c8893f5c4608528e8f48/AdguardExtension/Common-Config.xcconfig#L19), and  [v4.4.6](https://github.com/AdguardTeam/AdguardForiOS/tree/version/v4.3) branch is active but hasn't been merged into master.

I'm not sure if this intentional, but will the latest version be merged in?

**Comment by Versty** [comment]
@jslawler Hi!  
Currently, it would be correct to build the application from the 4.4.6 branch rather than master to get the most recent version.
Branch management will be improved in the near future.
