### ISSUE TITLE
Keyboard covers active text entry fields for custom DNS

### ISSUE THREAD

**Issue by phatmikey** [AdguardTeam/AdguardForiOS#2186]
### Issue Details

- **AdGuard version:**
  - latest for iOS
- **Device model and storage size:**
  - iPhone 12 mini
- **Operating system and version:**
  - 17.0 Developer beta 3
- **Browser or App:**
  - app

### Expected Behavior

I want to be able to add a custom DNS server

### Actual Behavior

The keyboard covers the active text entry fields, so I cannot see what I’m typing

### Screenshots

<details><summary>Screenshot:

![image](https://github.com/AdguardTeam/AdguardForiOS/assets/30598207/f48b02d8-7eb1-4c1c-8c1c-aad78a0f8b82)
</summary>

</details>

**Comment by maxikuzmin** [comment]
@phatmikey @jslawler all correct. It's not up to us, it's an ios 17 update bug. Waiting for fixes from apple
