### ISSUE TITLE
Ads in Kuaishou app

### ISSUE THREAD

**Issue by hewit-hue** [AdguardTeam/AdguardForiOS#2190]
### AdGuard Extension version

4.1.56

### Browser version

chrome 106

### OS version

for ios 4.5.0(1002)

### Issue Details

快手等软件的启动广告无法拦截，ios设备，浏览器内的可以拦截，就是软件启动无法拦截

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@hewit-hue Hi! 
If the issue occurs in the AdGuard for iOS application, fill out the bug report form via this link: https://github.com/AdguardTeam/AdguardForiOS/issues/new/choose
