### ISSUE TITLE
AdGuard running in background for hours

### ISSUE THREAD

**Issue by RevENGE-code** [AdguardTeam/AdguardForiOS#2191]
### Issue Details
- **AdGuard version:**
  - AdGuard for iOS v4.4.6(998)
- **Device model and storage size:**
  - iPhone 13 Pro 1TB
- **Operating system and version:**
  - iOS 16.5.1 (20F75) 
  - [iOS 16.5.1 (a) (20F770750b)] 

### Expected Behavior
Adguard should only run in background for refreshing filters. (Which should only take a couple minutes each day, not hours)

### Actual Behavior
Adguard runs for hours on end in the background for no reason (?). This week alone, adguard ran for 9 hours in the background.

### Screenshots
![image](https://github.com/AdguardTeam/AdguardForiOS/assets/54822494/870675ee-8d6c-4d59-a9aa-9d162e5f278f)

### Additional Information
- I have 12 filters activated, + 19 custom rules. 
- The AdGuard extension for Safari  is enabled.
- set AdGuard to refresh every 24 hours(low-level-settings).
- I am not using the app's dns, but instead AdGuard's native DNS Profile from their site.

**Comment by dnmTX** [comment]
This is what i've noticed as well with DNS Protection ON. It drains the battery fast and it's not cool!!!!!!!!! 😞

**Comment by RevENGE-code** [comment]
> This is what i've noticed as well with DNS Protection ON. It drains the battery fast and it's not cool!!!!!!!!! 😞 

I am not using AdGuard's DNS Protection, I am using their DNS Profile. As stated in my Issue Post. Nor I am experiencing any significant battery drain. See attachment for battery drain for running in the background for 9 hours.
![image](https://github.com/AdguardTeam/AdguardForiOS/assets/54822494/8d987254-1d91-4917-8a78-dda82b793c0e)

**Comment by dnmTX** [comment]
Well...that's me since updating to the latest version and turning on the DNS Protection. AdGuard once again got the top spot for battery usage 😞 : 
<img width="359" alt="AG" src="https://github.com/AdguardTeam/AdguardForiOS/assets/34774426/6310f5c6-4ff4-4025-be75-97f6675a7f0d">

**Comment by Versty** [comment]
@dnmTX Battery drain issue will be fixed in version 4.6. Keep an eye on #1899 for more details.

@RevENGE-code AdGuard application runs in the background even with DNS protection disabled to maintain proper filtering in Safari browser. As you mentioned above, in this case, the app doesn't consume much battery or other resources of the device.
