### ISSUE TITLE
Unable to Open AdGuard for iOS 4.5.0 on iOS 13.x

### ISSUE THREAD

**Issue by PavelParkhomenko** [AdguardTeam/AdguardForiOS#2194]
### Issue Details

Several users (crm 779700, 778535 and 780008; and [on Reddit](https://www.reddit.com/r/Adguard/comments/14z8ruj/crash_on_ios/)) have reported that since the update to version 4.5, they are unable to open the AdGuard Pro app. When attempting to open the app, it instantly opens and closes. Despite this issue, it appears that the protection functionality is still active, as indicated by the AdGuard test page detecting the presence of the AdGuard app or extension.
- **AdGuard version:**
  - AdGuard for iOS and AdGuard Pro 4.5.0
- **Device model and storage size:**
  - iPhone X, iPhone SE 
- **Operating system and version:**
  -  iOS Version 13.7 (17H35), 13.5.1

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Woitler** [comment]
Здравствуйте, я столкнулся с этой проблемой на iPhone SE 1-го поколения, iOS 13.7 (17H35), сразу после обновления AdGuard Pro до версии 4.5, о чём сообщил в техническую поддержку AdGuard, номер обращения 778535. К обращению прикрепил несколько системных журналов и запись экрана, для наглядной демонстрации проблемы.

Такое поведение приложений, на iOS 13.7, не ново, я столкнулся с ним уже несколько раз за последние полгода. Точно такая же проблема была у меня ранее с приложениями: Guru Maps Pro, Альфа Страхование и Честный Знак.

Вот что сообщили мне разработчики мобильного приложения Guru Maps Pro:
«После небольшого расследования оказалось, что проблема, действительно, есть и это не совсем наша вина. Apple с последним обновлением Xcode (среда для разработчиков) неправильно собирает приложения для устройств на iOS 13.X. Мы попробуем исправить это на своей стороне в обновленной версии приложения…»

Я пытался сообщить о проблеме с Xcode в Apple, но для этого нужен активный аккаунт разработчика, так что, я не смог этого сделать.

**Comment by THE-FINAL-GOAT** [comment]
Since the ADGUARD PRO 4.5 update published a week ago, I can no longer open my application.  The app opens and closes instantly.  I specify that I am under iOS 13.5.1 with an iPhone X and that before this damn update everything worked perfectly.  I have already tried to reinstall the application and restart the mobile without success...

**Comment by THE-FINAL-GOAT** [comment]
It...doesn’t even appear in there -_-‘ (I tried to erase/reinstall the app, doesn’t seems to change)

**Comment by THE-FINAL-GOAT** [comment]
@jslawler doesn’t work, it doesn’t even appear in my iCloud !

**Comment by THE-FINAL-GOAT** [comment]
Good morning,

 I wanted to share some information with you that may be able to guide you.. another of my applications (IMGPlay) closed exactly the same way since an update, they updated it and since then it has worked again.. 

And another Problem, visibly the last ADGUARD update is 4.6.... mine was 4.5 a week ago.. does it mean that it will no longer be updated and that we are therefore going to be left with an update that kills the application ?

**Comment by Versty** [comment]
@THE-FINAL-GOAT Hi there! 
We are aware of this issue and investigating the depths. 
Seems like the problem is caused by the iOS version, please check for the system updates on your device. 
Apple rolled out a fix in the latest update a couple days ago.

**Comment by Versty** [comment]
@Woitler Добрый день! 
Спасибо за подробности. Мы изучили проблему и, похоже, что краши вызваны специфической версией iOS. 
Apple на днях выпустили обновление для системы, которое содержит исправления, пожалуйста, обновите устройство. 
Если вдруг проблема останется - сообщайте, мы постараемся найти решение на нашей стороне.

**Comment by Woitler** [comment]
@Versty К сожалению, у меня нет возможности установить обновление для iOS 13. Для моего устройства, Apple предлагает обновление до iOS 15.7.7, которое, я тоже не могу установить, из-за технических особенностей моего устройства. Видимо, мне придётся ждать исправлений в приложении AdGuard Pro, простите.

**Comment by THE-FINAL-GOAT** [comment]
@Versty в приложении ADGUARD pro больше не будет патчей, они уже есть в 4.6, а мы остались в 4.5.  Подводя итог, они поэтому посадили нас, как крыс, предложив финальное обновление, которое уничтожило их приложение на наших устройствах.  Я хотел бы отметить, что тонны других приложений сумели решить проблемы (например, imgplay), но, к сожалению, они, похоже, высмеивают это.

**Comment by enakr** [comment]
crm 782428 - same issue
IOS version 13.1.3

**Comment by Subway4M** [comment]
crash ips log of adguard booting in IOS 13.5 
 [Adguard-2023-08-28-094703.log](https://github.com/AdguardTeam/AdguardForiOS/files/12449591/Adguard-2023-08-28- 094703.log)
`Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Assertion failed: (gotLocation), function applyFixupsToImage_block_invoke_3, file /Library/Caches/com.apple.xbs/Sources/dyld/dyld-750.4.2/dyld3/Loading.cpp, line 779.
Highlighted by Thread:  0`

**Comment by artemiv4nov** [comment]
We will release a new version soon (ETA 1-2 weeks), please follow the Beta updates to get a new version faster.

**Comment by Versty** [comment]
@Woitler Мы исправили проблему при запуске AdGuard на iOS 13.x в новой бета версии (4.5.1). 
Пожалуйста, удостоверьтесь, что приложение стало запускаться штатно на вашем устройстве. 

[Как присоединиться к бета-тестированию AdGuard for iOS](https://adguard.info/ru/beta.html?platform=ios).

**Comment by Versty** [comment]
@Subway4M Hi! 
Please, check on the latest beta version (4.5.1), the problem should be fixed. 

[How to join us as a beta tester.](https://adguard.com/en/beta.html?platform=ios)

**Comment by THE-FINAL-GOAT** [comment]
Hello, I just can’t join: can you send me a code ?




Envoyé de mon iPhone

**Comment by Versty** [comment]
@THE-FINAL-GOAT The invitation has been sent to your email.
