### ISSUE TITLE
Requested to re-accept AdGuard in-app EULA agreement again

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#2195]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 4.5
- **Device model and storage size:**
  - 
- **Operating system and version:**
  - iPhone 13 Pro 128gb iOS 16.6
- **Browser or App:**
  - 

### Expected Behavior

Agree to the AdGuard EULA once upon initial running of the app, and never again.

### Actual Behavior

Randomly got asked again today to agree to the EULA, after having it installed and running for weeks.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ESurina** [comment]
Closed. If this happens again, please, open it by yourself and send us the logs by email.
