### ISSUE TITLE
The text in the filter description is partially hidden for filters with a too long name 

### ISSUE THREAD

**Issue by psnrk** [AdguardTeam/AdguardForiOS#2198]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x]  I checked to make sure that this issue has not already been filed

### Issue Details

В настройках фильтров, уже не первую версию есть проблема. При активации некоторых фильтров, например внутри дополнительных, с длинными названиями, часть строки с версией фильтра, и датой обновления уходит под зеленую линию. Просьба уже поправить интерфейс, а то смотрится не солидно. 

- **AdGuard version:**
  - AdGuard for iOS 4.5
- **Device model and storage size:**
  - iPhone 14 128gb
- **Operating system and version:**
  - 16.6

### Expected Behavior
Текст в описаними фильтра показывается полностью

### Actual Behavior
<details><summary>Screenshot</summary>

![IMG_6A2639948BA8-1](https://github.com/AdguardTeam/AdguardForiOS/assets/107266340/e0c19743-788d-4512-ab57-adfe899a3ee3)

</details>

**Comment by Versty** [comment]
@psnrk Добрый день! 
Пожалуйста, предоставьте скриншоты проблемы.

**Comment by psnrk** [comment]
Здравствуйте, да смогу, просто чуть позже, сейчас в командировке, а телефон с ios и полной версией программы у жены, поэтому отправлю на днях. Но вообще эта проблема идет давно, и от версии ios (с 14 точно), и от версии iphone не зависит (11, 14). Странно, что самостоятельно эту проблему не видите. Там суть в том, что когда ползунки включения фильтров выключены, например в дополнительных, а они по умолчанию выключены, то всё норм, но если их начать включать, то часть фильтров, с длинными названиями начинают «плыть» и вторая строка, где хештег, версия и дата, частично скрывается, на работу это, естественно не влияет, но перфекционист во мне протестует, вид, как у плохого китайского приложения). Прислать скриншоты можно сюда, письмом?

**Comment by psnrk** [comment]
Да, естественно

**Comment by psnrk** [comment]
Добрый день! Наконец руки дошли до скриншотов.
Пару проявлений этого эффекта, на первом скриншоте — Фильтр баннеров моб.. после включения и отключения фильтра  ползунком, на втором во включенном состоянии - Счетчик фильтров.
Как уже писал ранее, с телефоном проблем нет, стоят последние версии всего, и тот же эффект один в один был на старом iPhone 11. Версия Adguard — полная, пожизненная.

**Comment by Versty** [comment]
@psnrk Спасибо за подробное описание. К сожалению, в вашем сообщении нет картинок. 
Пожалуйста прикрепите скриншоты в следующем ответе или отправьте их на почту apple@adguard.com и в теме сообщения укажите номер `2198`.

**Comment by Versty** [comment]
@psnrk Спасибо! 
Мы исправим проблему в следующих версиях приложения.

**Comment by danidoedel** [comment]
This duplicates #1980 as far as I can see.

**Comment by Versty** [comment]
@danidoedel Correct, thank you! 

Closed as duplicate.
