### ISSUE TITLE
wishbone app tracker

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#220]
https://appsto.re/us/aex1X.i

event.scimo.io

**Comment by jo2dan23** [comment]
@Alex-302

**Comment by Alex-302** [comment]
I don't know what it does.
@gshumihin could you please capture session by Fiddler?

**Comment by ameshkov** [comment]
@gshumihin ?

**Comment by gshumihin** [comment]
Didn't see any ads in this app. What's the problem here @jo2dan23 ?

**Comment by jo2dan23** [comment]
@gshumihin no its a tracking pixel.

**Comment by Alex-302** [comment]
Added
