### ISSUE TITLE
I can't unlock my Apple Watch with my iPhone because of an add-on.

### ISSUE THREAD

**Issue by sH1222J** [AdguardTeam/AdguardForiOS#2202]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ o] I am running the latest version
- [ o] I checked the documentation and found no answer
- [ o] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**  AdGuard for iOS v4.5.0

- **Device model and storage size:** iPhone 13 pro 256gb 
  
- **Operating system and version:** 16.6
  
- **Browser or App:** Apple Watch Face ID

### Expected Behavior
If your iPhone or Apple Watch is on your wrist, you can unlock it without Face ID.

### Actual Behavior
However, after installing the ad-supported VPN, unlocking my Apple Watch didn't work. I then uninstalled the VPN and rebooted and it worked.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Versty** [comment]
@sH1222J Hi! 
Could you please describe step by step what you did that resulted in Face ID failing to unlock your device?

**Comment by Versty** [comment]
@sH1222J Any updates?

**Comment by Versty** [comment]
@sH1222J Closed due to lack of activity. Please reopen if needed.
