### ISSUE TITLE
information getting invisible on iPad

### ISSUE THREAD

**Issue by alx-xlx** [AdguardTeam/AdguardForiOS#2205]
on iOS the months traffic gets invisible due to the green background.
the part that says `This month's traffic` gets invisible when light mode is turned ON 
![1474-1024](https://github.com/AdguardTeam/AdguardForiOS/assets/42188371/5cab8750-b4b3-4269-a697-9011e981fd89)

**Comment by ESurina** [comment]
We are not going to introduce design changes. Therefore, we can offer you to turn the iPad over.
