### ISSUE TITLE
Adguard Pro 4.5.0 (1002) failed with CoreDNS DNS-over-QUIC

### ISSUE THREAD

**Issue by pengelana** [AdguardTeam/AdguardForiOS#2207]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - Adguard Pro 4.5.0 (1002)
- **Device model and storage size:**
  - iPhone 14 Pro
- **Operating system and version:**
  - iOS 16.6

DNS-over-QUIC supported by CoreDNS since v1.11.0 and working well with Adguard dnsproxy and dnslookup but failed with Adguard Pro. 

Error log exported from Adguard Pro:

~~~
2023/08/21 12:56:28:064 [1191144(NewDnsServerController.dnsCheckQueue)]  (NetworkUtils) - upstreamIsValid; Error: Error Domain=com.adguard.dnsproxy Code=13 "Error at ag::dns::test_upstream_internal:51: Upstream exchange error: 
Caused by: Error at ag::dns::DoqUpstream::disconnect:1153: Connection error: " UserInfo={NSLocalizedDescription=Error at ag::dns::test_upstream_internal:51: Upstream exchange error: 
Caused by: Error at ag::dns::DoqUpstream::disconnect:1153: Connection error: }
~~~

**Comment by pengelana** [comment]
Hi @ameshkov,

Can you help with this issue? 
Thanks

**Comment by ameshkov** [comment]
Is there any public CoreDNS-based server we can test it with?

**Comment by pengelana** [comment]
Hi @ameshkov,

Thank you for reply, you can test with quic://doh.tiar.app at port 784 or port 853.

**Comment by ameshkov** [comment]
Thank you, we'll see what's wrong here: https://github.com/AdguardTeam/DnsLibs/issues/204
