### ISSUE TITLE
draftkings app trackers

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#221]
app.adjust.io (adjust.com)
exacttarget.api.mashery.com (http://www.exacttarget.com/products/predictive-intelligence/)
consumer.exacttargetapis.com (http://www.exacttarget.com/products/predictive-intelligence/)
ence/)
app.igodigital.com (http://www.exacttarget.com/products/predictive-intelligence/)
ence/)

DraftKings - Daily Fantasy Football & More Sports by DraftKings
https://appsto.re/us/tJEwQ.i

**Comment by jo2dan23** [comment]
@Alex-302

**Comment by Alex-302** [comment]
Added
```
||app.adjust.io^
||exacttarget.api.mashery.com^
```

**Comment by jo2dan23** [comment]
What about app.igodigital.com

**Comment by Alex-302** [comment]
It is marketing service, I don't know what it does in this app.
@gshumihin Could you please record a log by fiddler?

**Comment by jo2dan23** [comment]
It used for analytics it redirects here: http://www.exacttarget.com/products/predictive-intelligence/

**Comment by jo2dan23** [comment]
It used for analytics it redirects here: http://www.exacttarget.com/products/predictive-intelligence/

**Comment by ameshkov** [comment]
We block `collect.igodigital.com` already. I suppose that blocking `app.igodigital.com` may cause problems with apps behaviour.
