### ISSUE TITLE
Safari crashes from businessinsider.com

### ISSUE THREAD

**Issue by jonny-wg2** [AdguardTeam/AdguardForiOS#2212]
### AdGuard Extension version

4.5.0(1002)

### Browser version

Safari iOS 16.6

### OS version

IOS 16.6

### What filters do you have enabled?

AdGuard Mobile Ads filter

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

After browsing the site will refresh a couple of times and then the crash and error message. I believe some type of javascript  running in the background that maybe is crashing the browser or Adguard? 

### Expected Behavior

Business insider to work and ads removed and all articles unlocked.

### Screenshots

https://drive.google.com/file/d/1V91pB_iSl4ft6O3gcZ--Ek4h5-nRrjqr/view?usp=drivesdk

### Additional Information

AdGuard version 

Version 4.5.0(1002) SafariConverterLib v2.0.39 Scriptlets v1.9.37

ExtendedCss v2.0.52

**Comment by ESurina** [comment]
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Open Settings --> General --> Turn **Advanced mode** on --> Advanced settings --> Turn **Debug logs** switch on;
2. Reproduce the issue and remember the exact time when it happened;
3. Disable "DNS Protection";
4. Open the settings --> Support --> **Export logs**;
5. System popup will be opened --> Choose "Mail" app
6. Enter `apple@adguard.com` as a recipient;
7. Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by jonny-wg2** [comment]
Great, sent logs now.

**Comment by jonny-wg2** [comment]
Any update on this issue? Are you able to reproduce or need more information from me?

**Comment by ESurina** [comment]
Thanks for the logs, we have passed them on to the developers and will let you know when there is news.

**Comment by ESurina** [comment]
Does this happen all the time? If you turn off the protection, does this still happen?

**Comment by jonny-wg2** [comment]
Yes with adguard enabled, it happens all the time. Without adguard
activated it does not happen. Adguard also allows me to read premium
content to it bypasses the paywall which is why I like it. So if we can try
to make it work then that's best. I believe it might be some type of
javascript running in the background? But I also see that it always has the
same suffix url when it errors out.

**Comment by ESurina** [comment]
Do you have the same problem if you turn on AdGuard but disable Advanced protection?

**Comment by jonny-wg2** [comment]
Yes. I just tested without advanced protection enabled and it still crashed in safari (as seen in the image.). Note that everytime it crashes it has the same `?=r=US&IR=T` if that makes sense. It will crash after probably 1 minute of browsing on any article.

![IMG_6857](https://github.com/AdguardTeam/AdguardForiOS/assets/39831372/801302e7-a5f3-41cc-b292-249754d4b2f2)

**Comment by ESurina** [comment]
Please try to disable all user rules and filters except AdGuard Base filter. Then reenable the main switch and see if the website crashes.

**Comment by jonny-wg2** [comment]
That worked! There must of been a filter that was misbehaving. Thanks so much for the help and sorry for the newbie issue.

**Comment by ESurina** [comment]
If you identify a problematic filter and it turns out to be the AdGuard filter, then please reopen the issue.
