### ISSUE TITLE
Native DNS not blocking

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#2215]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 4.5.0
- **Device model and storage size:**
  - iPhone 13 Pro 128gb
- **Operating system and version:**
  - iOS 17
- **Browser or App:**
  - 

### Expected Behavior

Native DNS blocks content when using filters

### Actual Behavior

When using native DNS, after a while of use (in this situation it was about 30mins), DNS entirely stopped filtering ads.
I noticed this when in-app ads started appearing again, then tested Sky News' website, switching between a DNS configuration profile and the AdGuard app using native DNS.

In the below video, you'll see an ad banner appearing when using native DNS, but when using a configuration profile from AdGuard Personal DNS, its blocked again.
I also tested this within apps with the same outcome.

### Screenshots

<details><summary>Screenshot:</summary>

https://github.com/AdguardTeam/AdguardForiOS/assets/95468948/a8f009fb-203d-4c61-b53f-ede4f7982907

</details>

### Additional Information

 Debug logs have been sent to apple@adguard.com during the time of the screen recording.

**Comment by ESurina** [comment]
Please change server to AdGuard DNS DoH/DoT. This should help to solve the problem.
