### ISSUE TITLE
AdGuard not working in iOS 17

### ISSUE THREAD

**Issue by backstab5983** [AdguardTeam/AdguardForiOS#2224]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 4.5.0
- **Device model and storage size:**
  - iPhone 13 Pro - 128GB
- **Operating system and version:**
  - 17.0.1
- **Browser or App:**
  - Safari

### Expected Behavior

Filters should update when clicking on the button in the top right

### Actual Behavior

If Safari is not running, the app is stuck loading forever on "updating..." and "content blockers are being updated..."
If Safari is running in the background, "filter update error" appears

### Screenshots

<details><summary>Screenshot:</summary>

![IMG_9365](https://github.com/AdguardTeam/AdguardForiOS/assets/21013752/8fab6a03-0291-4770-b39f-9a3c4c48e8a8)
![IMG_9366](https://github.com/AdguardTeam/AdguardForiOS/assets/21013752/d9750a76-8310-42a2-9d18-7bfd7502a385)

</details>

**Comment by maxikuzmin** [comment]
@backstab5983 for some users disabling `Dandelion Sprout's Annoyances List` solves this problem, you can try using this as a temporary solution
