### ISSUE TITLE
AdGuard Pro Testflight Expiring in 6 Hours

### ISSUE THREAD

**Issue by Ryan-Goldstein** [AdguardTeam/AdguardForiOS#2226]
I just noticed, at the time of writing, the AdGuard Pro Testflight app, version 4.5.0 (1002) is expiring in 6 hours, and when it expires, it becomes unable to be launched. Hopefully you plan to release a new version soon!

**Comment by ESurina** [comment]
Yes, we will release a new version!

**Comment by Ryan-Goldstein** [comment]
> Yes, we will release a new version!

Thanks, but the app is now expired in TestFlight and can no longer be used. If the new version isn't yet available, could you please re-release the prior version so we can continue using the app?

**Comment by danidoedel** [comment]
Well for me it now says "Tester removed". Like seriously? I've been beta tester for so many years...
