### ISSUE TITLE
Не работает мобильный интернет. Не работает DNS защита

### ISSUE THREAD

**Issue by PIT457** [AdguardTeam/AdguardForiOS#2229]
Использую Adguard pro 4.5.0 , iphone 12 pro max, ios 17.0.2 Не работает DNS защита. При отключении wifi перехода на мобильный интернет нет тестовая страница показывает не работающий DNS и дополнение для Safari. Прошу помочь решить проблему!Спасибо.

**Comment by ESurina** [comment]
1. Откройте экран **Настройки** -> **Общие**
2. Включите **Расширенный режим**
3. Откройте **Расширенные настройки**
4. Включите **Перезапускать защиту при изменении сети**

Также убедитесь, что у вас включена настройка **Фильтровать мобильные данные**.
Ее можно открыть так: **Защита** -> **DNS-защита** -> **Настройки сети**

**Comment by PIT457** [comment]
ДаОтправлено с мной9 окт. 2023 г., в 12:31, ESurina ***@***.***> написал(а):﻿
@PIT457  Проблему удалось решить?
