### ISSUE TITLE
Add the option to go the adguard.com/test.html or check filter update corectly

### ISSUE THREAD

**Issue by Am4hisa** [AdguardTeam/AdguardForiOS#2235]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Proposed Solution

Sometimes AdGuard on iOS does not update filters properly and bugs can occur. When this happens, I get information by accessing the test page as a reference to see if a bug is occurring or not.
So it would be great if you could add an option to open the [test page](https://adguard.com/ja/test.html) in the support area of the settings.

### Alternatives Considered

I think it would be great if there was a function to determine whether the filter is updated correctly or not, rather than accessing the test page.

**Comment by Am4hisa** [comment]
I did not report the bug in this issue.
I just request the option to check if the filter is updated correctly.

**Comment by ESurina** [comment]
Our test page does not guarantee that all filters were updated successfully, so we do not plan to add an option for opening it. If filters were updated incorrectly, you will see this error:
![](https://uploads.adguard.org/up48_uz5xq.png)
