### ISSUE TITLE
Navigating via Google search result causes remaining leftovers

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdguardForiOS#2236]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 4.5.0
- **Device model and storage size:**
  - iPhone SE2
- **Operating system and version:**
  - 17.0.3
- **Browser or App:**
  - Safari

### Expected Behavior

AdGuard for iOS hides the leftovers if you visit the webpage directly.

### Actual Behavior

AdGuard for iOS does not hide the leftovers if you visit the webpage via Google search result.

https://www.google.com.tr/search?q=Argentina+peso+collapse&client=safari&sca_esv=573172220&hl=tr-tr&tbm=nws&prmd=niv&source=lnt&tbs=qdr:m&sa=X&ved=2ahUKEwjH1bii-fKBAxUPVfEDHRg7DTgQpwV6BAgCEBE&biw=390&bih=690&dpr=3

### Screenshots

<details><summary>Screenshot:</summary>

  ![Screenshot 1](https://cdn.adguard.info/sitereports/ioz9fieyub4sw80o048o4gc0w0scckgijacimio1o0.png?nc=1)

</details>

### Additional Information

- https://github.com/AdguardTeam/AdguardFilters/issues/163702#issuecomment-1761385044

**Comment by maxikuzmin** [comment]
@piquark6046 I don't have this problem repeatedly. Could you please specify what filters you have enabled? Is DNS protection enabled, if enabled, what server are you using? Is this still recurring in version 4.5.1?

**Comment by maxikuzmin** [comment]
@piquark6046 any news?

**Comment by maxikuzmin** [comment]
@piquark6046 for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
