### ISSUE TITLE
Using AdGuard DNS on iOS causes delay in loading YouTube

### ISSUE THREAD

**Issue by AidanGee7** [AdguardTeam/AdguardForiOS#2239]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS 4.5.1 (1004)
- **Device model and storage size:**
  - iPhone 15 Pro Max 256GB
- **Operating system and version:**
  - iOS 17.1
- **Browser or App:**
  - App

### Expected Behavior

YouTube loads (images/thumbnails etc) almost instantly when using AdGuard DNS.

### Actual Behavior

When using AdGuard DNS, there is a noticeable delay when loading the video thumbnails/images on the YouTube app. This happens on the person AdGuard DNS link and also the default AdGuard DNS. When using any other DNS service this doesn't happen.

### Screenshots

I've recorded a video of me opening the YouTube app and switching between different DNS providers to showcase the issue being limited to AdGuard DNS. This has only started happening in the last few weeks. I use the same AdGuard DNS server on my desktop computer (Same WiFi etc, with no issue), this is limited to iOS.  I've also attached a screenshot of the AdGuard test page.

Also looking at the DNS stats within the app, any YouTube/Google related requests all seem to have either a 0ms cached response or a <30ms response so that doesn't appear to be the issue.

Video:
https://github.com/AdguardTeam/AdguardForiOS/assets/28673281/e1c83ba1-619e-4bea-aa97-40986afb02a8

![IMG_0714](https://github.com/AdguardTeam/AdguardForiOS/assets/28673281/886ac637-4db3-40f2-b6fc-d32a5f85caca)

</details>

### Additional Information

Let me know if you need any more info!

**Comment by Versty** [comment]
@AidanGee7 Hi! 
Please collect debug logs following the steps below.

1. Open Settings --> General --> Turn Advanced mode on --> Advanced settings --> Turn Debug logs switch on;
2. Reproduce the issue and remember the exact time when it happened;
3. Open the settings --> Support --> Export logs;
4. System popup will be opened --> Choose "Mail" app;
5. Enter apple@adguard.com as a recipient;
6. Mention this issue number `2239` in the subject and add the time the issue was reproduced at.

**Comment by AidanGee7** [comment]
> @AidanGee7 Hi! Please collect debug logs following the steps below.
> 
> 1. Open Settings --> General --> Turn Advanced mode on --> Advanced settings --> Turn Debug logs switch on;
> 2. Reproduce the issue and remember the exact time when it happened;
> 3. Open the settings --> Support --> Export logs;
> 4. System popup will be opened --> Choose "Mail" app;
> 5. Enter [apple@adguard.com](mailto:apple@adguard.com) as a recipient;
> 6. Mention this issue number `2239` in the subject and add the time the issue was reproduced at.

Logs sent 😊

**Comment by Versty** [comment]
@AidanGee7 Thank you! 
The logs have been received and will be delivered to the developers for further investigation.

**Comment by Versty** [comment]
@AidanGee7 Hi! 
We have reworked the way how DNSLibs handles DoH upstreams, so please update to the latest release version. 
And check if the problem has resolved on your device.

**Comment by AidanGee7** [comment]
It works perfectly now, thank you!
