### ISSUE TITLE
iCal sync issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#224]
Just added at 12:45 a meeting named Test iPhone scheduled at 14:00. (see logs here, Nov 1: 1021351)

It does not appear on my iPad neither on my MBP or iCloud website. 
SRT:

1. I setup on my iPad and iPhone Adguard DNS to family protection. 
2. I launch iCal and I create an event on the iPhone. I close iCal, wait few seconds then I opening on the iPad. The event does not show. 
3. I change from Family to Default protection on the iPad and suddenly the event appears. 

I use iCal from iOS or macOS Sierra. I am not using third party software.

**Comment by ameshkov** [comment]
@gshumihin please check it

**Comment by gshumihin** [comment]
That's logs for issue #191
