### ISSUE TITLE
Constant background crashes

### ISSUE THREAD

**Issue by jw154j** [AdguardTeam/AdguardForiOS#2240]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - AdGuard for iOS 4.5.1 (1004)
- **Device model and storage size:**
  - iPhone XS
- **Operating system and version:**
  -  iOS 17.0.3

### Expected Behavior

The app should continue to run as intended in the background without issues.

### Actual Behavior

Randomly I will get the “App crashed” message throughout the day. This occurs at random times and doesn’t follow any set requirements for it to happen. I rarely ever open the app, it just sits it in the background of iOS. I never force quit it. This also happens when the DNS VPN option of AdGuard Premium is turned off, as I don’t run it all the time.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

Each time I get the “App Crashed” message, I submit the report. However I don’t include any additional information as I wasn’t doing anything that interacted with the app or that would cause it to crash.  The only other thing that I can think of is if the app is trying to update filters. I have to always manually update filters as the auto-update has never worked.

**Comment by mikegwald** [comment]
I also have the same issue on iPad and iPhone iOS 17.1 

app crashes on launch

**Comment by Versty** [comment]
@mikegwald @jw154j Hi! 
We have just rolled out the beta 2 AdGuard for iOS 4.5.1, please check if crashes are fixed for you.

**Comment by Versty** [comment]
@mikegwald How is it going?

**Comment by mikegwald** [comment]
> @mikegwald @jw154j How is it going?

Everything seems to be in order now with the latest update No crashes for me at the moment.
