### ISSUE TITLE
Add Low Level Setting To Disable Safari Nagging

### ISSUE THREAD

**Issue by SocietasEvanescentes** [AdguardTeam/AdguardForiOS#2241]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

When using AdGuard only for its DNS, every time the app is opened the user gets nagged to enable safari extensions. I use both the AdGuard apps; pro for DNS and the other for Safari; this allows me to separate and troubleshoot issues I have with either when a problem occurs. Unfortunately, this is me running into these annoying "suggestions"; as an advanced user, I'd like to see a low level setting to disable the nagging instructions.

![image](https://github.com/AdguardTeam/AdguardForiOS/assets/25782090/09b761f8-99d6-47c5-b578-8b083cf93e04)

### Proposed Solution

Provide a low level setting in advanced settings like "Turn off "Content blocker disabled" banners and guide.

### Alternatives Considered

N/A

### Additional Information

N/A

**Comment by Versty** [comment]
@SocietasEvanescentes Hi! 
This improvement will be added as a part of https://github.com/AdguardTeam/AdguardForiOS/issues/1920
