### ISSUE TITLE
Block elements in Safari doesn’t work after reload 

### ISSUE THREAD

**Issue by ep0ns** [AdguardTeam/AdguardForiOS#2242]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS 4.5
- **Device model and storage size:**
  - iPhone 14 Pro 512GB
- **Operating system and version:**
  - iOS 17.1
- **Browser or App:**
  - Safari

### Expected Behavior

Using the advanced AdGuard extension in Safari one can block elements in Safari on the fly. E.g „hide one element“. 
After a new rule is added, the rule is applied, anytime the webpage gets loaded.

### Actual Behavior

The rule is only applied when creating the new rule. Upon reloading the webpage, the rule isn’t applied anymore.

**Comment by Versty** [comment]
@ep0ns Hi! 
In this case, AdGuard requires some time to recompile the content blockers. It is important to keep AdGuard in the foreground until the recompilation process is complete. 
Once this is done, the rule will be applied and the undesired element will be hidden.

**Comment by ep0ns** [comment]
Then this should be indicated in the app. Currently it just says something like „rule has been added“ after that popup I close the app…
