### ISSUE TITLE
Not blocking ads anymore iOS 17.1

### ISSUE THREAD

**Issue by danispringer** [AdguardTeam/AdguardForiOS#2243]
Latest AdGuard version (just deleted and reinstalled)
Latest iOS (17.1)
iPhone XR
Tested website: 2700chess.com

**Comment by zbyna** [comment]
Same issue:   
site tested: https://www.eurofotbal.cz/
ipadOS: 17.1

**Comment by Fdawgs** [comment]
Also hitting this on iOS 17.1 (21B80).

**Comment by Versty** [comment]
@DaniSpringer @zbyna @Fdawgs 
Hi there! 

We have tried to reproduce the issue using iOS 17.1, but to no avail. The ads are blocked as expected on our device. 

Please make sure that AdGuard content blockers is enabled in the system settings:
1. Go to Settings -> Safari -> Extensions
2. Tap on the AdGuard (or AdGuard Pro) extension 
3. Enable both `Allow Extension` and `Allow in the Private Browsing` 
4. In the permissions section below, make sure that `All Websites` is set to `Allow`
5. Return to "Extensions" screen 
6. Make sure that each AdGuard extension is enabled 
7. Restart Safari and test the problematic website in the private tab

**Comment by drlaserdev** [comment]
I've had this issue since iOS 17. It partially blocks ads, usually simple stuff like ad banners and pop-ups. It stopped blocking more complex ads (e.g. YouTube video ads). The AdGuard app also returns an error whenever I try to update the blocklists.

**Comment by zbyna** [comment]
> @DaniSpringer @zbyna @Fdawgs Hi there!
> 
> We have tried to reproduce the issue using iOS 17.1, but to no avail. The ads are blocked as expected on our device.
> 
> Please make sure that AdGuard content blockers is enabled in the system settings:
> 
> 1. Go to Settings -> Safari -> Extensions
> 2. Tap on the AdGuard (or AdGuard Pro) extension
> 3. Enable both `Allow Extension` and `Allow in the Private Browsing`
> 4. In the permissions section below, make sure that `All Websites` is set to `Allow`
> 5. Return to "Extensions" screen
> 6. Make sure that each AdGuard extension is enabled
> 7. Restart Safari and test the problematic website in the private tab

Hi, 
I gave AdGuard one more try, but no luck, everything works as I wrote in my post above. Adblock Plus has no problem with that site on my configuration so I am using it instead of AdGuard. Sorry.

**Comment by Versty** [comment]
@drlaserdev 
> The AdGuard app also returns an error whenever I try to update the blocklists.

Content blockers from time to time struggle to update due to an intentional change or a bug made by Apple in iOS 17. 
This issue has already been reported to Apple and a workaround to fix this issue will be available in the next version of AdGuard.

**Comment by Versty** [comment]
@DaniSpringer @zbyna @Fdawgs 
Please update to the latest AdGuard for iOS version (4.5.1), then check for the filters update. 
The issue should be gone.

**Comment by Fdawgs** [comment]
Thanks @Versty, that has resolved it for me!

**Comment by zbyna** [comment]
@Versty Thanks. It works again dot

**Comment by DaniSpringer** [comment]
Updated app. Reinstalled too. Still having issues. Safari shows ads and tapping on AdGuard shows it’s off. Tapping to turn it on opens AdGuard app, loads for a bit, then gives this error:
![IMG_0087](https://github.com/AdguardTeam/AdguardForiOS/assets/19246409/14f963e4-9426-4380-bb44-125dc547800d)

**Comment by DaniSpringer** [comment]
Deleted and reinstalled again, opened app, tapped refresh arrows button, loads for a while, then says filter update error.

**Comment by Ajraba04** [comment]
Hey there
Am still getting the same problem immediately after updating to (iOS 17.2 (21C5040g)) my adguard app Version is 4.5.1(1007) am on premium btw 
(SafariConverterLib v2.0.48 , TSUrlFilter v2.2.1 , v1.9.83 , ExtendedCss v2.0.52) 

the errors that I have faced until now are (not in order) : 
- popup : couldn’t communicate with a helper application 
- Popup : The operation couldn't be completed (WKErrorDomain error 6.)
- Ads aren’t being blocked 
- Rules/filters can’t update 


Attached are screenshots:
![IMG_4429](https://github.com/AdguardTeam/AdguardForiOS/assets/143622128/ba549da0-cebe-42f0-a348-8a58ba06e6cf)
![IMG_4430](https://github.com/AdguardTeam/AdguardForiOS/assets/143622128/0baba81c-e56d-450b-996b-7acd701fe9ac)

am sorry for my illiteracy ; it’s my first real interaction on github

**Comment by ksvnix** [comment]
The same problem on the latest version from AppStore:
For example: https://www.drive2.ru
ipadOS: 17.1.1

Not blocking ads anymore?

**Comment by papageno** [comment]
I am encountering the same issue on iOS 17.2 too. The [AdGuard Test](https://adguard.com/en/test.html) page says AdGuard is not running when AdGuard protection is on for all websites.

![IMG_1564](https://github.com/AdguardTeam/AdguardForiOS/assets/14852702/64cda44f-0c36-4cd6-82d9-8154d240918b)

**Comment by papageno** [comment]
> @papageno @splakish @Ajraba04 Does the issue still persist with latest AdGuard for iOS version (4.5.2)?

Thanks for your dedication! Now it works!

![Screenshot](https://github.com/AdguardTeam/AdguardForiOS/assets/14852702/5e56ac3a-899b-4c6b-9381-d5e08f1f1514)
