### ISSUE TITLE
Chrome loads the Ynet.co.il site slow with AdGuard DNS DoH

### ISSUE THREAD

**Issue by benklinger** [AdguardTeam/AdguardForiOS#2244]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v4.5.0(1002)
- **Device model and storage size:**
  - iPhone 15 Pro 128gb
- **Operating system and version:**
  - iOS 17.1
- **Browser or App:**
  - Chrome

### Expected Behavior

Both Chrome and Safari should load Ynet.co.il fast

### Actual Behavior

Ynet.co.il on Chrome takes 4-5 seconds to load. Until loading there is a white screen. On Safari loads instantly.
Started only when upgrading to iOS 17.
When disabling AdGuard it loads fast but with ads :(

### Screenshots

<details><summary>Screenshot:</summary>

https://github.com/AdguardTeam/AdguardForiOS/assets/2004146/fc811215-b4f8-4284-a2a4-971686323ba8

</details>

**Comment by Versty** [comment]
@benklinger Hi! 
Please provide details on the DNS server you are using in the AdGuard application.

**Comment by benklinger** [comment]
![IMG_5886](https://github.com/AdguardTeam/AdguardForiOS/assets/2004146/dd58575f-85be-4088-ae54-ea3409e9b9d5)

DNS-over-HTTPS

**Comment by benklinger** [comment]
I added a screenshot with the data

**Comment by Versty** [comment]
@benklinger Hi! 
Please update to the latest version (4.5.2), this issue should be gone.

**Comment by Versty** [comment]
@benklinger Any news?

**Comment by benklinger** [comment]
Thanks Versty,

I updated and it remained the same.

**Comment by vonDubenshire** [comment]
> Thanks Versty,
> 
> I updated and it remained the same.

I also tested this and it does seem to take about double time in both Edge and Chrome when using AdGuard

**Comment by Versty** [comment]
@vonDubenshire @benklinger 
Does the website load faster with Google DNS DNS-over-HTTPS selected in AdGuard application or the loading time is the same?

**Comment by Versty** [comment]
@vonDubenshire @benklinger 
Any updates?

**Comment by Versty** [comment]
@vonDubenshire @benklinger 
Closed due to lack of activity, please reopen if needed.
