### ISSUE TITLE
Advanced Protection doesn't work on `kinopoisk.ru`

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForiOS#2249]
### Issue URL (Ads)
 [https://www.kinopoisk.ru/series/77270/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.kinopoisk.ru%2Fseries%2F77270%2F)
Username: `@rakleed`

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://cdn.adguard.info/sitereports/i8zqm0v31xc0wkkgksgw0o4w00wos4c8ctndn0ltq0.png?nc=1)
</details>

### System configuration

Information | Value
--- | ---
AdGuard product: | AdGuard for iOS v4.5.1
License type: | paid
Advanced protection: | enabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian

_Originally posted by @adguard-bot in https://github.com/AdguardTeam/AdguardFilters/issues/165805#issuecomment-1803897709_

-----

Вероятнее всего скриптлетное правило не успевает примениться вовремя из-за ограничений Apple, поэтому видна реклама. Основное решение в AdGuard Extra, но, к сожалению, в iOS оно недоступно.

_Originally posted by @zloyden in https://github.com/AdguardTeam/AdguardFilters/issues/165805#issuecomment-1803963230

**Comment by ESurina** [comment]
Пожалуйста, напишите об этом в приложении:
Настройки -> Поддержка -> Сообщить о некорректной блокировке.

**Comment by rakleed** [comment]
@maxikuzmin @Versty @ESurina ping

**Comment by rakleed** [comment]
@maxikuzmin @Versty @ESurina ping

**Comment by rakleed** [comment]
@maxikuzmin @Versty @ESurina ping
