### ISSUE TITLE
Safari sees a message that the network server cannot be found.

### ISSUE THREAD

**Issue by MadeByPP** [AdguardTeam/AdguardForiOS#2251]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS v4.5.1 (1007)
- **Device model and storage size:**
  - iPhone 13 mini 128gb
- **Operating system and version:**
  - iOS 17.1
- **Browser or App:**
  - Both apps and browsers

### Expected Behavior

You must be successfully accessed to certain websites. You must also access and search the NAVER app normally.

### Actual Behavior

You cannot access sites such as clien.net, dcinside.com, ruliweb.com, etc. with the message that you can't connect to the server you see in the screenshot. The NAVER app displays an error message and does not work as expected. If you turn off Adguard's switch, it will connect normally, but if you turn it on, it won't connect properly.

### Screenshots

<details><summary>Screenshot:</summary>

![IMG_4073](https://github.com/AdguardTeam/AdguardForiOS/assets/64509269/a5b0fb04-2c18-4b4a-bc81-d8cca8bb3979)
![IMG_4074](https://github.com/AdguardTeam/AdguardForiOS/assets/64509269/00515e51-9b55-4eca-b0b3-8dff0e68c77c)
![IMG_4084](https://github.com/AdguardTeam/AdguardForiOS/assets/64509269/39848304-f606-498d-93b0-3c0a5c9ec197)
![IMG_4085](https://github.com/AdguardTeam/AdguardForiOS/assets/64509269/0fe499d2-7893-4496-b101-ffbaa92c26d6)
![IMG_4086](https://github.com/AdguardTeam/AdguardForiOS/assets/64509269/32da8a79-c0da-4daa-9ff0-b5117a93d544)
![IMG_4087](https://github.com/AdguardTeam/AdguardForiOS/assets/64509269/9dd6f5c2-b686-4f2f-a55e-55b3770ed542)

</details>

### Additional Information

- I have already sent a detailed log to apple@adguard.com, mentioning the Issues number and the date and time of the Issues.

- Same symptoms for both wifi and cellular.

- Symptoms after updating to Adguard for iOS v4.5.1 (1007)

**Comment by ESurina** [comment]
Do these sites work if you choose AdGuard DNS or turn off DNS protection? It may be a blockage on the server side.

**Comment by MadeByPP** [comment]
I have tried both the dns over https and dns over quic protocols in Adguard dns, but I get the same error message. In addition, naver.com is also not accessed properly. However, if you turn off the adguard's switch, it works normally. There is no reason for so many servers to suddenly block my connection, and there have been issues since version 4.5.1 (1007) with filter-related updates.

**Comment by C-Perfume** [comment]
I’ve experienced this issue as well.
AdGuard also blocks YouTube shorts on mobile websites on my iPhone SE 2 (iOS 17.1.1)
It only blocks under the mobile website conditions, when clicking the open links button on the selected URL, it goes to the YouTube app, then the shorts play successfully.

**Comment by azuryst** [comment]
I started experiencing this issue recently as well (within the last 2 weeks). I think it has something to do with domains that don't start with "www". I am using Split-Tunnel VPN mode on AdGuard Pro iOS. I haven't made any changes to AdGuard recently, so this appears to be an issue with the recent app update or iOS 17 update.

**Comment by azuryst** [comment]
@MadeByPP As for my issue, it ended up being the Adguard Cookie Notices filter v2.0.28.64 under DNS filters. Turning this filter list off fixed it. Your issue seems similar to mine, so just thought I'd mention it to you.

**Comment by C-Perfume** [comment]
Thank you @azuryst for the info.
According to your comment, I also turned off Yours List under DNS filters and now I can see naver.com, namuwiki.com e.t.c.
I know it’s not complete solution but At least I am happy to use the blocked websites for some reason.

**Comment by MadeByPP** [comment]
@azuryst When I applied your offer, the blocked website started to work. Thank you for the offer and this issue should continue to be investigated in accordance with @C-Perfume comments.

**Comment by ESurina** [comment]
You've added a filter (https://github.com/yous/YousList/raw/master/youslist.txt), which blocks these domains. You can add them to allowlist.

**Comment by ESurina** [comment]
If this does not help solve the problem, then re-open the issue.
