### ISSUE TITLE
Recent Activity does not stay in Blocked only filter.

### ISSUE THREAD

**Issue by ravigm87** [AdguardTeam/AdguardForiOS#2252]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [yes ] I am running the latest version
- [yes ] I checked the documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed

### Problem Description
Recent activity does not stay in the Blocked only filter mode

**Comment by ESurina** [comment]
Can you please describe the problem in more detail? What version of the application are you using and what steps lead to the problem?

**Comment by ESurina** [comment]
@ravigm87

**Comment by ESurina** [comment]
Please reopen the issue if the problem persists.
