### ISSUE TITLE
Please block "open-in-app" popups for IOS and Android applications

### ISSUE THREAD

**Issue by joetimmy** [AdguardTeam/AdguardForiOS#2258]
Please see primary source which is a new IOS app that blocks app popups preventing web views on mobile devices. 

https://apps.apple.com/us/app/banish-block-open-in-app/id1632848430

This feature should be added ASAP to adguard IOS and Android.

**Comment by Versty** [comment]
@joetimmy Hi! 
This feature is already available in AdGuard for iOS application! 
To block "open-in-app" popups please enable Advanced blocking option along with AdGuard Mobile App Banners filter for Safari protection.
