### ISSUE TITLE
Add option to unlock optimize filter

### ISSUE THREAD

**Issue by Am4hisa** [AdguardTeam/AdguardForiOS#2263]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I were to subscribe to a non-optimized filter, addressing it is possible only through custom.

### Proposed Solution

Add option to unlock optimize filter.

### Additional Information

Currently, content blockers are categorized based on the genre of filters. 
For example, subscribing to Adguard Base (non-optimized) customarily consumes to the Custom around 95k rule slots out of the available 150k, leaving an excess of slots allocated to the General.
Allowing the use of non-optimized filters allows for effective use of limited rule slots.

Related https://github.com/AdguardTeam/AdguardForiOS/issues/74 , https://github.com/AdguardTeam/AdguardForiOS/issues/2250

**Comment by Alex-302** [comment]
@Am4hisa In iOS 17 the real limit is ~40-60k rules and 10 MB filter (json) size.
https://discussions.apple.com/thread/255240753

**Comment by Am4hisa** [comment]
> In iOS 17 the real limit is ~40-60k rules and 10 MB filter (json) size. 

@Alex-302 It is an iOS bug, right? Or is it a specification that will not change in the future?
Also, The description in the Adguard App states that "each content blocker contains up to 150,000 rules."

**Comment by Alex-302** [comment]
@Am4hisa 

> It is an iOS bug, right?

Yes, not AdGuard's.

**Comment by Am4hisa** [comment]
@Alex-302 

I understand this iOS bug. It seems my previous communication may not have been clear, as English is not my native language.

What I wanted to convey in this issue is the possibility of optimizing the usage of limited rules by allowing the subscription of non-optimized filters within the same content blocker as the optimized ones. 

Despite ongoing issues with rules not functioning correctly, I understand that most of these are bugs occurring on the user side.

**Comment by Versty** [comment]
@Am4hisa Hi!
We created an optimised version of filters to provide a better user experience in terms of blocking and performance stability. We strongly recommend using optimised filters on iOS due to the Apple bug mentioned above, but you can still add an non-optimised version as a custom filter if you wish.
