### ISSUE TITLE
Advanced protection cannot be disabled

### ISSUE THREAD

**Issue by l0001-repo** [AdguardTeam/AdguardForiOS#2268]
### Issue Details

Disabled Avanced protection would remains enabled after restart the app

- **AdGuard version:**
  - AdGuard for iOS v4.5.2(1010)
- **Device model and storage size:**
  - iPhone 14 Pro 256GB
- **Operating system and version:**
  - IOS 17.2

### Expected Behavior

disabled successfully

### Actual Behavior

remain enabled

### Screenshots

<details><summary>Screenshot:</summary>

![IMG_0365](https://github.com/AdguardTeam/AdguardForiOS/assets/6596534/655858d3-4717-448c-a9ec-b6545c9c793f)

</details>

**Comment by Versty** [comment]
@l0001-repo Thank you for reporting! 
This issue duplicates #2152
