### ISSUE TITLE
Add two options to get rid of  "Enable AdGuard for Safari" and "Some content blockers are disabled" Message

### ISSUE THREAD

**Issue by l0001-repo** [AdguardTeam/AdguardForiOS#2269]
### Problem Description

Those messages are so annoying to user, and then only DNS filtering is good enough for mobile user.
Open too much extension would make the safari become lagging too
![IMG_0366](https://github.com/AdguardTeam/AdguardForiOS/assets/6596534/563a2bc1-87e2-4ac9-af62-1be25f4ea713)
![IMG_0367](https://github.com/AdguardTeam/AdguardForiOS/assets/6596534/96179e98-1a56-4d4d-b141-191c9c32200c)

### Proposed Solution

Please add an option to remove those message

### Alternatives Considered

can add a checkbox "Don't show again" on each pop up or create a new options to handle it are also fine

**Comment by Versty** [comment]
@l0001-repo Hi! 
This issue duplicates #1920
