### ISSUE TITLE
lucktastic app video ads

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#227]
api.kiip.me
config.tremorhub.com (tremorvideo.com)
l0-secure.videohub.tv (tremorvideo.com)
perf-events.cloud.unity3d.com

Lucktastic - Win Prizes. Earn Rewards. by Jump Ramp Games Inc.
https://appsto.re/us/bj2n6.i

**Comment by jo2dan23** [comment]
@Alex-302

**Comment by Alex-302** [comment]
added

**Comment by jo2dan23** [comment]
More: 

ads-secure.videohub.tv
videohub.tv.edgekey.net
mediate-ios-*.hyprmx.com
marketplace-ios-*.hyprmx.com
live.hyprmx.com

**Comment by ameshkov** [comment]
`videohub.tv.edgekey.net`

This could be used for video serving as well.

**Comment by jo2dan23** [comment]
I dont think so. Edgekey is used for cdn just like akamai and alot of ad domains host on them

**Comment by ameshkov** [comment]
Yeah, but these video ad networks are really often serve videos along with ads. It's like they provide both features: CDN for video and ad serving.

**Comment by jo2dan23** [comment]
@Alex-302 can we add the other ones? Sorry to bug you XD

**Comment by ameshkov** [comment]
@Alex-302 I suppose `hyprmx.com` subdomains may be added.

**Comment by jo2dan23** [comment]
And this ads-secure.videohub.tv

**Comment by ameshkov** [comment]
Still not sure about it. Let's leave the issue open until we can test it with the user filter.

**Comment by Alex-302** [comment]
ok, added
```
||mediate-ios-*.hyprmx.com^
||marketplace-ios-*.hyprmx.com^
||live.hyprmx.com^
```

**Comment by jo2dan23** [comment]
@Alex-302 another one

objects-secure.tremormedia.com (tremorvideo.Com)

**Comment by ameshkov** [comment]
This one is dangerous, let's not add it until it's properly tested
