### ISSUE TITLE
Allow downloading of AdGuard DNS (private) profile configuration through app

### ISSUE THREAD

**Issue by kyjhoz-mikfip-goXci0** [AdguardTeam/AdguardForiOS#2275]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

 Having to navigate to the AdGuard DNS website to download profile configurations can be a lengthly process, it would be nice to provide a quicker way to do so.

### Proposed Solution

 Allow the downloading of AdGuard DNS profile configurations via the AdGuard app.

**Comment by Versty** [comment]
@kyjhoz-mikfip-goXci0 Hi! 
The DNS configuration profiles are part of another service, which is AdGuard DNS. Therefore, we have no plans to implement the direct profile download in the AdGuard for iOS app in the near future.
