### ISSUE TITLE
Support Safari advanced protection for iOS web app

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdguardForiOS#2276]
AdGuard for iOS cannot execute an advanced adblock syntax defined as Safari advanced protection into the [web apps](https://www.macrumors.com/how-to/use-web-apps-iphone-ipad/) in iOS.
However, AdGuard content blocker does work correctly.

For example, the advanced advertisements in https://m.fmkroea.com cannot be blocked in its iOS web app. ( https://github.com/AdguardTeam/AdguardFilters/issues/168573 )
To view a screenshot about Safari DevTool, please search `FmKoreaMobile` in AdGuard's Google Drive.
To reproduce the example, please use a residential proxy with any real Korean IP address or live in South Korea.

**Comment by Versty** [comment]
@piquark6046 Unfortunately, web apps do not provide the technical possibility to execute advanced rules at the moment.
We will consider this feature as soon as it becomes technically feasible.
