### ISSUE TITLE
Add username autofill to the GitHub username box on the ad reporting tool

### ISSUE THREAD

**Issue by kyjhoz-mikfip-goXci0** [AdguardTeam/AdguardForiOS#2282]
![image](https://github.com/AdguardTeam/AdguardForiOS/assets/149243371/51fde93d-ac77-4134-af34-48b4068a92f1)

**Comment by ESurina** [comment]
Duplicate of [#223](https://github.com/AdguardTeam/ReportsWebApp/issues/223)
