### ISSUE TITLE
Popup

### ISSUE THREAD

**Issue by michael1900** [AdguardTeam/AdguardForiOS#2287]
Hi. I need help and advice on how to block ads popup banner from this site: **rbtv77.com**

I mean, go to **rbtv77.com**, choose one of the available matches and click on Play symbol. A different advertisement will open each time in a new tab. 

How to fix this? Which rules i need to set?

Thanks

Ps. for example one of the popup opened is: **ir3.xyz**, so i added this rule: **||ir3.xyz^$popup** but the popup will open anyway. Same thing with other popup/sites. It seems like they are not detected.

Why in iOS do these rules **||example.com^** and **||example.com^$popup** produce the same result?

~~How to block popup for all sites, without to specify rules for every site? Can this works: **||*^$popup** ?~~

**Comment by michael1900** [comment]
Check this similar site: **time4tv.online**
Choose one of the matches available, click on Watch live, you will see that popup will open in some new tab:
**ografazu.xyz** and **ratimsub.net**.
So i add these 2 rules: |**|ografazu.xyz^$popup** and **||ratimsub.net^$popup**

Nothing changes. I mean the popup still will open in a new tab. So the question: why these rules don't work?
And how to fix this?

**Comment by michael1900** [comment]
Who can help me? @Versty @Stillness-2 @sfionov @maxikuzmin @ameshkov

**Comment by michael1900** [comment]
Seems that rules simply don't work. Try with this site: **hes-goals.io**.

If i add this rule: **@@||hes-goals.io^$document** the site still see the adblock enabled.

**Comment by Versty** [comment]
@michael1900 The ||ir3.xyz^$popup rule is working on iOS as ||ir3.xyz^ rule. It blocks content on ir3.xyz page, but not the popup-script on initial page (rbtv77.com). 

To block the script on source page please report this issue via in-app option `Report incorrect blocking`

**Comment by michael1900** [comment]
> @michael1900 The ||ir3.xyz^$popup rule is working on iOS as ||ir3.xyz^ rule. It blocks content on ir3.xyz page, but not the popup-script on initial page (rbtv77.com).
> 
> To block the script on source page please report this issue via in-app option `Report incorrect blocking`

I need to report manually from github because from the app it ask me a screenshot, but a screenshot of who in this case? 
So which is the right section to post this incorrect block?
