### ISSUE TITLE
http://forums.hardwarezone.com.sg - ads in Opera

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#229]
1. The issue only occurs on this website so far. I have not found other websites with this type of advertisement. I only tried Opera Mini and Safari.
2. Load the URL give below. Scroll to the bottom to see the advertisement. Adguard content filter in Safari can block it. But Adguard Pro DNS filter is unable to.
3. Please refer to screenshots of the bottom of the URL where the advertisement is.

URL: http://forums.hardwarezone.com.sg/eat-drink-man-woman-16/redmart-nv-refund-me-items-were-not-delivered-5499029.html

This affects all pages in this subforum.

![image](https://cloud.githubusercontent.com/assets/15856304/20111020/6476fcd2-a5ef-11e6-9390-3f9459beff49.png)

Logs: 1446085

**Comment by gotitbro** [comment]
If you are referring to the **CrowdyNews widget** at the bottom it is not an ad its just a third party widget utilized by `hardwarezone.com.sg`.

**Comment by Alex-302** [comment]
@evgeniy-ADG what does he mean by ads?

**Comment by ameshkov** [comment]
I guess this "Advertising" label is misleading, it does not refer to the news widget, it refers to the ad which is now blocked.

**Comment by Alex-302** [comment]
It is blocked by `/advertisement_` on my end. It can't be blocked by DNS filtering.

**Comment by deLumren** [comment]
user 1523958 complains about this site as well. 
There are ads and pop-ups:
<details>

![screen shot 2017-03-16 at 9 29 14 am](https://cloud.githubusercontent.com/assets/26342177/23986085/1145bc6a-0a2b-11e7-99ca-f78a2ed6c6a7.png)


</details>

Also, it takes SUUUUUUPER LONG time to go through pages on this site when using Chrome(better with Safari). Issue exists on Windows and Mac. 
Occasionally links would not open but would instead try to download .html file onto computer.
All standard filters active.

**Comment by Alex-302** [comment]
@deLumren but he says about `Adguard for Windows on Chrome`
It works fine on my side.
Can you reproduce it?

**Comment by zebrum** [comment]
one more id 1290431 EDGE\Chrome browser hang. But it is fine when i have Adguard disabled
@Alex-302 page hangs on my side right now in chrome

**Comment by zebrum** [comment]
or maybe we should discuss this issue here: [https://github.com/AdguardTeam/AdguardForWindows/issues/1606](url)
