### ISSUE TITLE
AdGuard breaks Captive portal

### ISSUE THREAD

**Issue by MoienBowen** [AdguardTeam/AdguardForiOS#2290]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.5.2(1010)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

no link...

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, Adblock Warning Removal List

### Security

NoCoin Filter List

### DNS filters

AdGuard DNS filter

### Language-specific

AdGuard Chinese filter, AdGuard French filter, AdGuard German filter

### Add your comment and screenshots

It is a typical issue which has occurred several times, however, I do not find any relevant post...

When you are connecting a business WiFi hotspot, it always redirects to an authentication page. For example, on the flight of AirFrance, you need to access connect.airfrance.com, then, choose the service (and pay) to surf the internet. The example includes Accor hotels, airport WiFi, etc.

However, with AdGuard on, the redirection always fails to a blink page (e.g., cannot open). Once I turn AdGuard off, I can successfully open the webpage to enjoy the WiFi.

As a fact that every time, it requires a longtime to re-active AdGuard... And if the WiFi is broken, I need to repeat all this again...

Is anyone facing the same issue and have a solution to avoid it?

Thanks a lot.

### Privacy

- [X] I agree to follow this condition

**Comment by maxikuzmin** [comment]
@MoienBowen I checked this and connected to WiFi with Captive portal without any problems. 

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

- Open Settings --> General --> Turn Advanced mode on --> Advanced settings --> Turn Debug logs switch on;
- Reproduce the issue and remember the exact time when it happened;
- Disable "DNS Privacy";
- Open the settings --> Support --> Export logs;
- System popup will be opened --> Choose "Mail" app
- Enter apple@adguard.com as a recipient;
- Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by maxikuzmin** [comment]
@MoienBowen any news?

**Comment by MoienBowen** [comment]
> @MoienBowen any news?

Sorry for the delay response.
Recently, I did not have chance to get open WiFi with Captive portal. Hence, I have no relevant log for you to capture the issue.
However, I remembered that it may be caused by the AdGuard DNS. But I am not sure about this part of memory...

**Comment by maxikuzmin** [comment]
@MoienBowen any news?

**Comment by maxikuzmin** [comment]
@MoienBowen for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
