### ISSUE TITLE
[Feature Request] Option to disable logs

### ISSUE THREAD

**Issue by BrightenedDay** [AdguardTeam/AdguardForiOS#2292]
### Issue Details

There is no option to disable logging.

### Proposed solution

An option to disable logging so that it doesn't write to files anything. (:

**Comment by BrightenedDay** [comment]
To be honest, it's more of a personal preference; I just don't like having a logger enabled on stuff, and if it is possible to request such a feature, it would be great! (:

**Comment by ESurina** [comment]
Unfortunately, we will not add such a feature, as there is no objective reason to do so.
