### ISSUE TITLE
Filter update stalls and never finishes

### ISSUE THREAD

**Issue by jimmysofat6864** [AdguardTeam/AdguardForiOS#2294]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.2

### Environment

- OS:iOS 15.5
- Device:iPad 5th Generation

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter, EasyPrivacy

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies, EasyList Cookie List

### Security

NoCoin Filter List

### Advanced protection for Safari

- [X] yes, I do

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

DNS protection disabled

### DNS filtering

- [ ] yes, I do

### DNS implementation

DNS protection disabled

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1.Reset AdGuard to factory settings. 
2.Enable filters I have selected
3.AdGuard will stall and not update and keep saying updating without doing anything. 

### Expected Behavior

Filters should update. 

### Actual Behavior

Filters don't update. 

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by jimmysofat6864** [comment]
email already sent to apple@adguard.com with a debug file attached.

**Comment by jimmysofat6864** [comment]
> Could you please reboot your device and tell me if the problem reoccurs?

I was told to uninstall and reinstall the app and I also rebooted my device. Now the filter update takes about 8 minutes. Is that normal? It updates much faster in Safari on Macos and on the desktop extension.

**Comment by ESurina** [comment]
Yes, it's okay. This problem is not related to the duration of the update, but to the status display. We are already working on fixing this!
