### ISSUE TITLE
Text is garbled in the rule creation menu

### ISSUE THREAD

**Issue by SKEIDs** [AdguardTeam/AdguardForiOS#2296]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.2(1010)

### Environment

- OS: 17.2.1
- Device: iPhone 15 Pro
- language: Japanese

### Issue Details

Steps to reproduce:
1. Open the Share menu
2. Select AdGuard
3. Select "Block element on this page"

### Expected Behavior

The text display correctly.

### Actual Behavior

The text is garbled and unreadable.

### Screenshots

<details><summary>Screenshot 1</summary>

![](https://i.ibb.co/s2MtDj3/IMG-1125.png)
</details>

**Comment by Versty** [comment]
@SKEIDs Thank you for reporting! 
This issue duplicates #2055.
