### ISSUE TITLE
Build Error: 'No Such Module SharedAdGuardSDK' After Running Fastlane Build

### ISSUE THREAD

**Issue by CristianCanalesAnd** [AdguardTeam/AdguardForiOS#2299]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

**Issue Description:**

After executing 'bundle exec fastlane build', I encountered a dependency issue with 'SharedAdGuardSDK'. 
The error occurs during the build process.

**Error Output:**

```
❌  /AdguardForiOS/AdguardExtension/AdguardApp/Services/Utils/URL+CustomSchemeURLParserProtocol.swift:20:8: no such module 'SharedAdGuardSDK'

import SharedAdGuardSDK
```

**Expected Behavior:**
The build process completes without errors.

**Attempted Fixes:**
- Re-importing the module directly into the file.
- Cleaning and rebuilding the build folder.

**Comment by Versty** [comment]
@CristianCanalesAnd Are you trying to build from 4.3 branch?

**Comment by CristianCanalesAnd** [comment]
Hello @Versty

No, I'm trying to build from master branch.

**Comment by Versty** [comment]
@CristianCanalesAnd Please use the 4.3 branch and let me know the result.

**Comment by Versty** [comment]
@CristianCanalesAnd 
Any news?

**Comment by Versty** [comment]
@CristianCanalesAnd Closed due to inactivity, please reopen if needed.
