### ISSUE TITLE
German: No text when user clicks "Share" on facebook

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#23]

**Comment by dartrax** [comment]
It looked like this before:

![foto 03 11 15 14 24 52](https://cloud.githubusercontent.com/assets/15105943/11142624/16955b7a-89ef-11e5-8cbb-314bc6cadca1.png)

Now it looks like this:

![foto 06 11 15 18 36 49](https://cloud.githubusercontent.com/assets/15105943/11142626/19709116-89ef-11e5-9bd8-f0f9bcefc621.png)

still no text.

**Comment by ameshkov** [comment]
@Stillness-2 I've just checked this with ipad and it looks exactly the same as in @dartrax case.

I suppose it's not a big problem (the logo is stretched, but anyway we can't fix it - that's how itunes.apple.com works). The only question is where's the text?

**Comment by Stillness-2** [comment]
![01](https://cloud.githubusercontent.com/assets/12689/11189039/dfee3d46-8c9e-11e5-9eb1-5cc4e3e9bc16.png)
Why why why!
Where does the arrow on the top left?

**Comment by dartrax** [comment]
The Arrow in my case has the same functionality a "Cancel" button.

**Comment by IvanIin** [comment]
This behaviour is by design. Prefilling is not allowed by  Facebook Platform Policy.
https://developers.facebook.com/bugs/962985360399542/
