### ISSUE TITLE
Geico app tracker

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#230]
consumer.exacttargetapis.com (http://www.exacttarget.com/products/predictive-intelligence/)

**Comment by jo2dan23** [comment]
@Alex-302

**Comment by Alex-302** [comment]
I didn't forget, too many ads.

**Comment by jo2dan23** [comment]
Oh sorry man. My bad. And What you mean too many ads? In geico app?

**Comment by jo2dan23** [comment]
I didn't know you were subscribed to this section

**Comment by ameshkov** [comment]
@jo2dan23 i guess he meant that there're too many ad reports in AdguardFilters and forum:)

**Comment by Alex-302** [comment]
Indeed.
@jo2dan23 I don't know what purpose ща this domain.

**Comment by jo2dan23** [comment]
@Alex-302  see here: http://www.exacttarget.com/products/predictive-intelligence/

**Comment by jo2dan23** [comment]
Ive seen this same tracker on 4 apps so far

**Comment by jo2dan23** [comment]
Ive seen this same tracker on 4 apps so far

**Comment by jo2dan23** [comment]
See here: 
![img_3271](https://cloud.githubusercontent.com/assets/15130139/20249438/9d62253a-a9be-11e6-84ad-d95b9bc2d563.PNG)

**Comment by ameshkov** [comment]
Looks like this is a part of salesforce.com.

Used by this SDK:
http://salesforce-marketingcloud.github.io/JB4A-SDK-iOS/

Let's leave it open until we can properly test blocking of this domain.
