### ISSUE TITLE
Is AdGuard Extra not working on AdGuard for iOS?

### ISSUE THREAD

**Issue by Am4hisa** [AdguardTeam/AdguardForiOS#2302]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

I am using an iPhone 14 with iOS version 17.3.1, and my AdGuard version is 4.5.2 (1010), with AdGuard Premium activated. I've verified on AdGuard Extra's GitHub repository that it states, 'AdGuard Extra comes pre-installed with all premium AdGuard versions.' If I'm not mistaken, this refers to the same AdGuard Extra on the test page.

Until now, I believed my Safari was functioning correctly, but upon checking the test page, it indicates that AdGuard Extra isn't working. Any idea why this might be happening?

<details>
<summary>screenshot</summary>

![image](https://i.postimg.cc/1tqqg9z9/IMG-1484.jpg)
</details>

<details>
<summary>screenshot</summary>

![image](https://i.postimg.cc/9fv4HvYs/IMG-1485.jpg)
</details>

<details>
<summary>screenshot</summary>

![image](https://i.postimg.cc/hPgdjRRB/IMG-1486.jpg)
</details>

**Comment by ESurina** [comment]
Unfortunately, AdGuard Extra is not currently supported by AdGuard on iOS. Thank you for your contact, we will update the information on AdGuard Extra's GitHub repository.

**Comment by Am4hisa** [comment]
Okay,thank you so much.
