### ISSUE TITLE
Period bar is stuck 

### ISSUE THREAD

**Issue by DoodleFloof** [AdguardTeam/AdguardForiOS#2304]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.2

### Environment

- OS: 17.4
- Device: iPhone 13 mini

I always kept noticing that the request and data saved tracker’s line never physically adjusted, in the period bar below, since a certain point. 

The activity page and the info are all updated but seeing the visual graph not consistent feels odd. Would filter update errors cause this? Or it’s just an iOS iPadOS 17 bug?

![IMG_1155](https://github.com/AdguardTeam/AdguardForiOS/assets/162089225/03300527-35a5-46d8-b203-a68a98b9dcfe)

![IMG_1156](https://github.com/AdguardTeam/AdguardForiOS/assets/162089225/b023565b-473c-49c4-8aba-c6be463119dc)

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter, EasyPrivacy, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Other

Filter unblocking search ads and self-promotion

### Advanced protection for Safari

- [X] yes, I do

### Which DNS server do you use?

Cloudflare DNS

### DNS protocol

DNS-over-HTTPS

### DNS filtering

- [X] yes, I do

### DNS implementation

AdGuard

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Use these filters with iCloud on as well? Manually update to see if a error occurs yet the filters are updated

### Expected Behavior

I expect some visual line in the graph to adjust high or low on the graph

### Actual Behavior

Line graph stays stagnant with a visual spike always on the right end of it

**Comment by maxikuzmin** [comment]
@DoodleFloof could you be more specific about how long you've been using the AdGuard app? Presumably, if you've been using the app recently, the stats for all time and a week shouldn't be different

**Comment by DoodleFloof** [comment]
> @DoodleFloof could you be more specific about how long you've been using the AdGuard app? Presumably, if you've been using the app recently, the stats for all time and a week shouldn't be different

I used it since late november, is that too recent?

**Comment by maxikuzmin** [comment]
@DoodleFloof as far as I can see, the graphs are different on the left side. It's quite likely that you might have been using AdGuard a lot recently and a large number of requests are shown in the right part of the graph.
Anyway, your graphs are different. It's normal behavior

**Comment by DoodleFloof** [comment]
I haven’t changed my browsing behavior. So seeing everything flatline for months now looks odd. I don’t think activity monitoring is broken cause that gets updated, but this visual graph is becoming quite distracting now to the point I kinda wish I can make it go away under DNS implementation

**Comment by maxikuzmin** [comment]
@DoodleFloof maybe some apps have been making a lot of requests lately. These stats are not just from the browser. 
Are the stats for other periods the same? What about "Today", "24 hours", "30 days"?

**Comment by maxikuzmin** [comment]
@DoodleFloof I see a slight difference in the graphs. Are your graphs in the same condition today?

**Comment by DoodleFloof** [comment]
@maxikuzmin
I’m seeing slight difference too. But to have them not be visible on the larger graphs seems odd unless the y scale is shorter than say, 30 day or lifetime graph. I just really wish this could be toggled off without having to choose native os dns implementation, because my ocd thinks there should be visible ups and downs on these graphs and not just a sudden spike then flatline for months on the larger graphs

![IMG_1191](https://github.com/AdguardTeam/AdguardForiOS/assets/162089225/31b16340-d286-420f-9dce-37fd25c98e14)
![IMG_1187](https://github.com/AdguardTeam/AdguardForiOS/assets/162089225/bd03146b-4502-4eb2-a9aa-12941ae6f433)
![IMG_1188](https://github.com/AdguardTeam/AdguardForiOS/assets/162089225/d1f65190-0efa-4afd-a86a-ede3db4d21a5)
![IMG_1189](https://github.com/AdguardTeam/AdguardForiOS/assets/162089225/d6431eab-0589-43c7-ad8b-079c7b8a7288)
![IMG_1190](https://github.com/AdguardTeam/AdguardForiOS/assets/162089225/05e4448a-743b-4809-a635-fa55fc808001)

**Comment by maxikuzmin** [comment]
@DoodleFloof as far as I know, period bar will be reworked in the next update. Given that at this point we've established that the scale is not stuck, I recommend waiting for the next update and reopening this issue if you have any problems or questions. For now I'll close this issue
