### ISSUE TITLE
Permission Allow all websites not apply in extensions

### ISSUE THREAD

**Issue by pablorivassanchez** [AdguardTeam/AdguardForiOS#2310]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.2

### Environment

- OS: 17.3.1
- Device: Iphone 13

### Advanced protection for Safari

- [X] yes, I do

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

DNS protection disabled

### DNS filtering

- [ ] yes, I do

### DNS implementation

DNS protection disabled

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1. go to settings Safari extensions
2. Allow all websites in the AdGuard extension
3. Other Adguard extensions does not have permission to read or transmit content from any web pages

### Expected Behavior

Other Adguards extensions have permission

### Actual Behavior

Content is not blocked in Safari

### Screenshots

<details><summary>Adguard extensions are active</summary>

![one](https://github.com/AdguardTeam/AdguardForiOS/assets/20487828/b8e30ea7-e8e3-4bec-99de-876a07e040d4)

</details>
<details><summary>Allow all websites is always</summary>

![two](https://github.com/AdguardTeam/AdguardForiOS/assets/20487828/3164b10b-d8a7-4bda-86d9-f0ec95a5b002)

</details>
<details><summary>Other adguards extensions does not have permission to read or transmit content from any web pages</summary>

![three](https://github.com/AdguardTeam/AdguardForiOS/assets/20487828/c4cb7b1d-8c1f-43b3-9320-329823f4dc5a)

</details>
<details><summary>Ads are not blocked</summary>

![four](https://github.com/AdguardTeam/AdguardForiOS/assets/20487828/c19173d6-b26a-4fd9-8eab-9cbcc1685a0b)

</details>
<details><summary>In safari is enabled</summary>

![five](https://github.com/AdguardTeam/AdguardForiOS/assets/20487828/5dc58737-e21c-4724-97e6-f6f57293a0f8)

</details>

**Comment by maxikuzmin** [comment]
@pablorivassanchez Is the default state of the extensions. It's enough to just enable all extensions
I tried reproduce it and I'm getting ad blocking on this site
Please clarify, do you have any third party filters enabled, are there any exclusions or User rules to block ads?
It is also possible that the site is cached. Try opening the site in incognito and check this again

**Comment by pablorivassanchez** [comment]
Hi @maxikuzmin, I tried in ingcogno and the ads are still showed. Also I tried another webs and the same. I reinstall the Adguard app that I has a permanent license and the problem remains the same, the only way to block is to activate the DNS protection but I don't like since it needs a vpn config and sometimes it blocks my connection.

**Comment by maxikuzmin** [comment]
@pablorivassanchez I checked the logic in similar apps like AdGuard, and the logic is the same, for some reason the IOS system indicates "no permission" for the content blockers, although all content blockers in my case are working correctly.
Could you please clarify on which websites you check for ad blockers?

**Comment by pablorivassanchez** [comment]
Hi @maxikuzmin, 
It looks like now is working.
Thanks for your patient, you can close the ticket.

**Comment by pablorivassanchez** [comment]
Hi @maxikuzmin,
It looks like now is working.
Thanks for your patient.
