### ISSUE TITLE
Add support for more protocols 

### ISSUE THREAD

**Issue by overwatch3560** [AdguardTeam/AdguardForiOS#2317]
### Issue Details

If I’m using dns protection on adguard adblocker in can only combine them with a vpn that has the IPsec protocol but almost no provider uses that protocol except you guys please support more protocols such as wireguard or openvpn 

### Proposed solution

ADD support for openvpn/wireguard/nordlynx

**Comment by ESurina** [comment]
We have discussed your proposal and have come to a decision not to add support for more protocols yet.

**Comment by overwatch3560** [comment]
Why it would be such an improvement I'm using both on windows why not support it both on other platforms as well?
