### ISSUE TITLE
quic server addresses with case sensitive device names aren’t being parsed correctly

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#2320]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.3

### Environment

- OS: iOS 17.5
- Device: iPhone 13 Pro

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Advanced protection for Safari

- [X] yes, I do

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-QUIC

### Custom DNS

quic://John--Router-f8c555.dns.nextdns.io

### DNS filtering

- [X] yes, I do

### Custom DNS filter

AdGuard DNS filter

### DNS implementation

AdGuard

### Tunnel mode

Split-Tunnel

### Low-level settings

Bootstrap server: default
Fallback server: default
Blocking mode, etc: default

### Issue Details

Steps to reproduce:
1. Insert quic://John--Router-f8c555.dns.nextdns.io into custom DNS servers 
2. Visit https://test.nextdns.io/
3. Observe case sensitive device name not respected

### Expected Behavior

Case sensitive server addresses are respected.

### Actual Behavior

Case sensitive server addresses aren’t respected.

### Screenshots

<details><summary>Screenshot 1</summary>

**Incorrect result when using the below DoQ server address with AdGuard for iOS**
![IMG_0582](https://github.com/AdguardTeam/AdguardForiOS/assets/149243371/7354a5c0-acca-45aa-bf63-285601e7157a)

**Correct result when using a case sensitive DoQ address in AdGuard VPN**
![IMG_0583](https://github.com/AdguardTeam/AdguardForiOS/assets/149243371/2fa6572f-5d44-480d-abac-45b7e23c39c6)

</details>

**Comment by sfionov** [comment]
@jslawler-gh Thank you for report, seems to be regression.

I have to say that it will stop working in AdGuard VPN too if you update, DnsLibs is updated in the upcoming version.

**Comment by sfionov** [comment]
@jslawler-gh Yes, I'm talking about upcoming version

**Comment by zzebrum** [comment]
[Duplicate](https://github.com/AdguardTeam/DnsLibs/issues/219)
