### ISSUE TITLE
Make possible toggle on / off native DNS in iOS app. 

### ISSUE THREAD

**Issue by szl1973** [AdguardTeam/AdguardForiOS#2327]
### Issue Details

Three years old NextDNS app can activate and deactivate its own native profile. Please add this feature to the iOS app. 

### Proposed solution

Instead of in-app warning could be possible to toggle on and off native dns profile.

**Comment by Versty** [comment]
@szl1973 We will do your best to shorten the way to enable DNS protection with native implementation. 

Duplicate of https://github.com/AdguardTeam/AdguardForiOS/issues/1824
