### ISSUE TITLE
Filter error: Full page blocked, not ad blocked.

### ISSUE THREAD

**Issue by loana2918** [AdguardTeam/AdguardForiOS#2329]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

453

### Environment

- OS: IOS
- Device: iphone

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Advanced protection for Safari

- [ ] yes, I do

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

DNS protection disabled

### DNS filtering

- [ ] yes, I do

### DNS implementation

DNS protection disabled

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1. Easylist has added a filter that blocks the entire ygosu.com page.
2. When you access ygosu with the IOS Advisor, the entire page is blocked.
3. It is 100% reproducible.

### Expected Behavior

Normal screen
<img width="396" alt="image" src="https://github.com/AdguardTeam/AdguardForiOS/assets/164298716/0e6df732-e0f6-4e2a-ab8d-38f9c8248358">

### Actual Behavior

The entire ygosu.com page is blocked.

### Screenshots

<details><summary>Screenshot 1</summary>

<img width="396" alt="image" src="https://github.com/AdguardTeam/AdguardForiOS/assets/164298716/9458a39b-8328-4e74-8c0c-9b771862bb65">
</details>

### Additional Information

ygosu.com is just a domain of community websites. I don't know why they block it when it's not an advertising domain.

**Comment by Versty** [comment]
@loana2918 Please use the `Report incorrect blocking` option in the app to report issues related to filters. 
*Settings tab -> Support -> Report incorrect blocking*
