### ISSUE TITLE
Fox news app

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#233]
apm.crittercism.com
api.push.io (marketing)

Fox News by FOX News Digital
https://appsto.re/us/31x6v.i

**Comment by ameshkov** [comment]
I am 100% sure `push.io` is often used for legit purposes.

**Comment by Alex-302** [comment]
Added the first only.

**Comment by jo2dan23** [comment]
After looking at the website push.io used to advertise. It says drive real time engagement with push notifications. Scroll down a bit and look at the push notification image they show

**Comment by ameshkov** [comment]
Push notifications may be used for a lot of things including advertising, but this does not mean their API is used for advertising only.
