### ISSUE TITLE
H3 Support 

### ISSUE THREAD

**Issue by Poochy1130** [AdguardTeam/AdguardForiOS#2330]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Why in the adguard pro app in the adguard non filter section there is only the quic server and not the h3 one but yet h3 servers are supported?

**Comment by tengizmax** [comment]
Thank you for your patience, @Poochy1130 . We are pleased to inform you that, as you correctly pointed out, the DoH3 protocol is indeed supported, although it is not explicitly listed as a selectable option. To utilize this protocol, you may manually enter "h3://" in the URL field.
The ability to select DoH3 directly from the list will be  available in a future update, so please stay tuned.
