### ISSUE TITLE
Adguard Not Blocking All Trackers

### ISSUE THREAD

**Issue by oushima** [AdguardTeam/AdguardForiOS#2331]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 1.11.17 (build 329, CT 2.0.44)

### Environment

- OS: macOS / iOS
- Device: MacBook Pro 2023 / iPhone 14 Pro

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, EasyPrivacy, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Other

Filter unblocking search ads and self-promotion, AdGuard DNS filter, AdGuard Experimental filter

### Advanced protection for Safari

- [X] yes, I do

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-QUIC

### DNS filtering

- [x] yes, I do

### DNS implementation

DNS protection disabled

### Tunnel mode

DNS protection disabled

### Issue Details

Hi, Adguard for macOS and iOS is not blocking all ads. I have all settings enabled in both the Pro iOS app and for Safari.
Including all the nested settings.

### Actual Behavior

Not blocking all trackers. 

### Screenshots

<details><summary>Screenshot 1</summary>
<img width="649" alt="Screenshot 2024-05-18 at 21 34 16" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/6aaebcd7-75ce-4607-8aab-47e20075491d">
<img width="653" alt="Screenshot 2024-05-18 at 21 36 01" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/9c3c93fe-5706-49a6-b451-ed304c1fe77a">
<img width="656" alt="Screenshot 2024-05-18 at 21 35 55" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/4527d3bf-c9f9-4902-a2e2-eb7f6b46eb49">
<img width="658" alt="Screenshot 2024-05-18 at 21 35 49" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/3b672f72-1842-41be-8986-d1bb255a6b9e">
<img width="659" alt="Screenshot 2024-05-18 at 21 35 43" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/6743d649-d617-4236-a878-d70997da1776">
<img width="662" alt="Screenshot 2024-05-18 at 21 35 37" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/e40a6d03-6bca-4ac7-b2c2-fbfc62f6b22c">
<img width="657" alt="Screenshot 2024-05-18 at 21 35 31" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/89ba0aa7-5dcd-42ee-a56f-a6736adfc621">
<img width="658" alt="Screenshot 2024-05-18 at 21 35 19" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/2d968723-8398-48af-a8fe-69a34b48fc8d">
<img width="674" alt="Screenshot 2024-05-18 at 21 35 12" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/b8a386b3-7980-4298-9661-b893251f7c34">
<img width="659" alt="Screenshot 2024-05-18 at 21 35 06" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/ea323fc8-f0a2-43e8-8c05-2569680218be">
<img width="686" alt="Screenshot 2024-05-18 at 21 35 00" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/7a0c9de4-6767-4a48-9a5a-b98cac2cb896">
<img width="679" alt="Screenshot 2024-05-18 at 21 34 55" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/c61ffbd5-7923-4800-9664-69c752a148cf">
<img width="656" alt="Screenshot 2024-05-18 at 21 34 49" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/abe552ef-7c21-47f4-88d2-856be60b9571">
<img width="661" alt="Screenshot 2024-05-18 at 21 34 42" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/9531a9ca-6427-4d3b-93dd-d3d7a99e6016">
<img width="656" alt="Screenshot 2024-05-18 at 21 34 36" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/8db3308a-f667-42f1-a816-137198a0fbea">
<img width="660" alt="Screenshot 2024-05-18 at 21 34 26" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/2bd4987b-32ba-46ea-92ee-b2d61c05b257">

</details>

### Additional Information

None.

**Comment by oushima** [comment]
<img width="649" alt="Screenshot 2024-05-18 at 21 34 16" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/6a6ef01d-a6b9-48f9-84c5-07c65cebf51c">
<img width="653" alt="Screenshot 2024-05-18 at 21 36 01" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/51d3318a-5e39-4794-9356-d6177987ec74">
<img width="656" alt="Screenshot 2024-05-18 at 21 35 55" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/4464ac43-dec1-413c-b5e7-07caa1915a2e">
<img width="658" alt="Screenshot 2024-05-18 at 21 35 49" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/1e331e1d-4326-4432-95e7-17b68f045b2d">
<img width="659" alt="Screenshot 2024-05-18 at 21 35 43" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/b63c0fe0-788e-4e0c-a719-4064a491ae20">
<img width="662" alt="Screenshot 2024-05-18 at 21 35 37" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/ceedce5e-1e6c-4d07-8d25-8b8d21480902">
<img width="657" alt="Screenshot 2024-05-18 at 21 35 31" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/2758e3ab-3f52-40d2-9ab0-e567d25ef35f">
<img width="658" alt="Screenshot 2024-05-18 at 21 35 19" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/248122b3-e639-491e-869e-cd8654f9f2ec">
<img width="674" alt="Screenshot 2024-05-18 at 21 35 12" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/57375d23-f5c2-470f-9364-0c4fed2af382">
<img width="659" alt="Screenshot 2024-05-18 at 21 35 06" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/55654bb7-97ef-438e-b947-7bb44c696e16">
<img width="686" alt="Screenshot 2024-05-18 at 21 35 00" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/0a247aab-bd6a-400a-bd9a-782b1884075c">
<img width="679" alt="Screenshot 2024-05-18 at 21 34 55" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/7664b4fd-87e4-4658-9048-c64c326d6c12">
<img width="656" alt="Screenshot 2024-05-18 at 21 34 49" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/aae6a309-136f-4f43-b8eb-220bf5c8755c">
<img width="661" alt="Screenshot 2024-05-18 at 21 34 42" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/83b237f3-8819-47f5-a41f-863103c8f45d">
<img width="656" alt="Screenshot 2024-05-18 at 21 34 36" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/ff3c57f9-1989-4e46-8a21-41e564840f34">
<img width="660" alt="Screenshot 2024-05-18 at 21 34 26" src="https://github.com/AdguardTeam/AdguardForiOS/assets/27223330/dec39d90-52dd-4cd2-bc24-beda6db0f9d7">

**Comment by Versty** [comment]
@oushima Hi! 
If you have detected any missed tracker, please report it to our filter maintainers using the `Report incorrect blocking` option in the app.
