### ISSUE TITLE
iOS AdGuard app is not blocking ads in safari without dns protection

### ISSUE THREAD

**Issue by GodgamingonYT** [AdguardTeam/AdguardForiOS#2332]
### Please answer the following questions for yourself before submitting an issue

- [x] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.3 (1013)

### Environment

- iPadOS: 17.5.1
- Device: iPad 8

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, EasyPrivacy, Peter Lowe's Blocklist

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Other

Filter unblocking search ads and self-promotion, AdGuard DNS filter

### Language-specific

AdGuard Chinese filter, AdGuard Japanese filter, CJX's Annoyances List, EasyList China, xinggsf

### Advanced protection for Safari

- [X] yes, I do

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

DNS protection disabled

### DNS filtering

- [ ] yes, I do

### DNS implementation

DNS protection disabled

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1. I opened a website that have ads, etc: google ads
2. I saw it a lot of ads inside the website
3. I tested the blocking feature in d3ward testing Adblock website

### Expected Behavior

I think it will block ads in safari without dns protection but with safari protection

### Actual Behavior

It didn’t block ads at all

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by ESurina** [comment]
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Open Settings --> General --> Turn **Advanced mode** on --> Advanced settings --> Turn **Debug logs** switch on;
2. Reproduce the issue and remember the exact time when it happened;
3. Disable "DNS Protection";
4. Open the settings --> Support --> **Export logs**;
5. System popup will be opened --> Choose "Mail" app
6. Enter `apple@adguard.com` as a recipient;
7. Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by ESurina** [comment]
We remind you that we are waiting for your logs.

**Comment by GodgamingonYT** [comment]
I can’t send it. It said it is too big

「ESurina ***@***.***>」在 2024年6月4日 週二，下午9:35 寫道：

**Comment by GodgamingonYT** [comment]
Still too big I can’t send
「ESurina ***@***.***>」在 2024年6月4日 週二，下午9:35 寫道：

**Comment by ESurina** [comment]
Then could you upload the logs to Google Drive and send a link to it by mail, mentioning the issue number in the subject?

**Comment by ESurina** [comment]
Let us know when you send the logs

**Comment by ESurina** [comment]
Reopen the issue if you have an opportunity to send us logs.
