### ISSUE TITLE
My life time premium gone after I reset all settings

### ISSUE THREAD

**Issue by GodgamingonYT** [AdguardTeam/AdguardForiOS#2333]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.3 (1013)

### Environment

- iPadOS: 17.5.1
- Device: iPad 8

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, EasyPrivacy, Peter Lowe's Blocklist

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Other

Filter unblocking search ads and self-promotion, AdGuard DNS filter

### Language-specific

AdGuard Chinese filter, AdGuard Japanese filter, CJX's Annoyances List, EasyList China, xinggsf

### Advanced protection for Safari

- [X] yes, I do

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

DNS protection disabled

### DNS filtering

- [ ] yes, I do

### DNS implementation

DNS protection disabled

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1. First I got a problem as my last report bug
2. I reset all setting and try to fix it
3. My life time premium gone (beta)

### Expected Behavior

My premium is still here

### Actual Behavior

My premium gone and I can’t buy life time (I says you bought this before, do you want to get it for free?) then nothing happens

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by PavelParkhomenko** [comment]
Hello! For further assistance, please reach out to our support team at **support@adguard.com**. Kindly provide them with the following details to facilitate a prompt and effective resolution:

- Where you purchased your license
- The email address used for the purchase
- Your license key, receipt, or order confirmation email.

Thank you!
