### ISSUE TITLE
support other browsers in ios

### ISSUE THREAD

**Issue by ignorantqualm** [AdguardTeam/AdguardForiOS#2336]
### Issue Details

i'm a happy user of everything Adguard and I love how on my mac I can filter any app with the content blocker and not only at dns level.
I'd like to have the same option in ios and being able to filter content in Firefox and Orion

### Proposed solution

allow content blocker filtering in other apps/browsers

**Comment by zzebrum** [comment]
@ignorantqualm unfortunately, Apple doesn't allow content filtering in other browsers.
