### ISSUE TITLE
Social media login not working on an iPad

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#2338]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.3 (1016)

### Environment

- OS: 17.5.1
- Device: iPad 12'9

### Advanced protection for Safari

- [ ] yes, I do

### Which DNS server do you use?

System default

### DNS protocol

Regular

### DNS filtering

- [ ] yes, I do

### DNS implementation

AdGuard

### Tunnel mode

Split-Tunnel

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1. Go to AdGuard > gear > License > Log in
2. Select Google, Facebook, or Apple
3. Observe the issue

### Expected Behavior

You are logged in via selected social media network

### Actual Behavior

Infinite redirects (see the video). If you request a mobile version of the website, it stuck for a second, and then logs you in.

### Screenshots

<details><summary>Screenshot 1</summary>

https://github.com/AdguardTeam/AdguardForiOS/assets/15856304/896f8c98-a097-4f17-aeb1-05b10bfe4c11

</details>

**Comment by Eugene-Savenko** [comment]
It's reproducible on my device. 
Affected users' CRM IDs: 912911, 913232, ...

**Comment by ihurin** [comment]
+1 CRM 915840
