### ISSUE TITLE
Target app

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#234]
devices.carnivalmobile.com

Target by Target
https://appsto.re/us/2WMUr.i

**Comment by Alex-302** [comment]
I don't know what is it.
@gshumihin please capture a fiddler session for this app.

**Comment by jo2dan23** [comment]
carnivalmobile.com is marketing

**Comment by jo2dan23** [comment]
carnivalmobile.com is marketing

**Comment by jo2dan23** [comment]
carnivalmobile.com is marketing
