### ISSUE TITLE
meteoblue.com - filters not blocking annoyance / redirected from support

### ISSUE THREAD

**Issue by bbsixzz** [AdguardTeam/AdguardForiOS#2344]
This pertains to https://github.com/AdguardTeam/AdguardFilters/issues/176034

I also sent an e-mail and received this response:

> Thank you for reaching out to AdGuard Support!
>  
> Please, create an issue on our iOS repository. Don't forget to mention the fact that you were redirected there due to the reason the Filters developers weren't able to reproduce the issue with their default devices.
>  
> Let us know should you have any additional questions. Have a great day!
> Best wishes,
> AdGuard Support team

This comment is essential https://github.com/AdguardTeam/AdguardFilters/issues/176034#issuecomment-2156606887

> I removed the app and did a fresh reinstall same problem. On my iPad with same filters I have no issue.
> 
> [EDIT]
> 
> The iPad had an old filter! As soon as I updated it the ad came! Luckily I took a screenshot beforehand, something has definitely changed since then and is now broken.
> 
> [IMG_9485](https://github.com/AdguardTeam/AdguardFilters/assets/47334163/b45b8148-b21f-4af8-97ff-81933cdc1269)

**Comment by maxikuzmin** [comment]
@bbsixzz well, I checked this and I'm having a recurring problem. 
As far as I understand, the problem is with the `AdGuard Mobile Ads filter` enabled. As soon as I enable the AdGuard Mobile Ads filter, element on the website is blocked. Please check it

**Comment by maxikuzmin** [comment]
@bbsixzzz I tested this by enabling `AdGuard Base filter` and `AdGuard Popups filter`

**Comment by bbsixzz** [comment]
![IMG_9498](https://github.com/AdguardTeam/AdguardForiOS/assets/47334163/39489c30-a11a-4432-9e29-dc71b9fbcc80)
![IMG_9497](https://github.com/AdguardTeam/AdguardForiOS/assets/47334163/6e85a80a-028a-4610-b0bb-f63c0b76d199)

Popups is also enabled.

The base filter is the problem, as soon as I enable it the popup appears. This was not a problem with an older version of the base filter as shown in the screenshot from the original github submission.

**Comment by maxikuzmin** [comment]
@bbsixzzz yes, but I wrote to try the same steps with `AdGuard Mobile Ads filter `disabled, and enable only `AdGuard Base filter` and `AdGuard Popups filter`. In your screenshot, the `AdGuard Mobile Ads filter` is enabled

**Comment by bbsixzz** [comment]
`AdGuard Mobile Ads filter` disabled now and `AdGuard Base filter` and `AdGuard Popups filter` enabled gives me same problem. Like mentioned in the original https://github.com/AdguardTeam/AdguardFilters/issues/176034 where I also have video of it, the problem is `AdGuard Base filter`.

I had an old version of the `AdGuard Base filter` on my iPad which I took a screenshot of as shown. 

As soon as I updated adguard with the latest filter the popup appeared.

Maybe this has something to do with geolocation, I'm surfing from Sweden.

**Comment by maxikuzmin** [comment]
@bbsixzzz well, we found one problem that could potentially affect the popup on meteoblue.com. This problem we will fix this week, I will let you know when we make the change, please wait

**Comment by maxikuzmin** [comment]
@bbsixzzz the task I was talking about #2346. You can track it

**Comment by maxikuzmin** [comment]
@bbsixzzzz we have released version 4.5.5 with a fix for the number of filter rules. Please update and check again

**Comment by bbsixzz** [comment]
Fixed, amazing! Thank you

**Comment by maxikuzmin** [comment]
@bbsixzz glad to hear that! Good luck!
