### ISSUE TITLE
Unable to download emails from gmail accounts while AdGuard is enabled.

### ISSUE THREAD

**Issue by correii** [AdguardTeam/AdguardForiOS#2345]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.4

### Environment

- OS: 17.5.1
- Device: iPhone 14 Pro

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, EasyPrivacy, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

NoCoin Filter List

### Other

Filter unblocking search ads and self-promotion, AdGuard DNS filter, AdGuard Experimental filter

### Advanced protection for Safari

- [X] yes, I do

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### DNS filtering

- [X] yes, I do

### DNS implementation

AdGuard

### Tunnel mode

Full-Tunnel

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1. Enable everything listed above.
2. Use your phone for a while
3. Open Mail and refresh a gmail inbox.
4. You should see a notification at the bottom of your screen saying that there’s a problem with your account, and your new emails won’t download.
5. Close Mail and open AdGuard.
6. Disable protection.
7. Close AdGuard and open Mail.
8. Refresh your gmail inbox.
9. The error message should be gone and new emails will download.

### Expected Behavior

I expect AdGuard to not prevent my phone from communicating with gmail SMTP servers.

### Actual Behavior

AdGuard prevents my phone from communicating with gmail SMTP servers.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

I’m not including a screenshot because I don’t want to leak my emails. Here’s the error message though: 

"Account Error - <mail account> is currently unavailable"

**Comment by maxikuzmin** [comment]
@calvincorrieri I don't have this problem recurring. How often does it recur, how long do you have to wait before the problem starts to appear?

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

- Open Settings --> General --> Turn Advanced mode on --> Advanced settings --> Turn Debug logs switch on;
- Reproduce the issue and remember the exact time when it happened;
- Disable "DNS Privacy";
- Open the settings --> Support --> Export logs;
- System popup will be opened --> Choose "Mail" app
- Enter apple@adguard.com as a recipient;
- Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by maxikuzmin** [comment]
@calvincorrieri any news?

**Comment by correii** [comment]
I reinstalled the app, and only enabled the dns filter list, with dns and safari protection enabled. It takes a while for gmails to download, but I’m not getting the connection error anymore.On Jul 1, 2024, at 6:55 AM, maximkuzmin ***@***.***> wrote:﻿
@calvincorrieri any news?

**Comment by maxikuzmin** [comment]
@correii for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
