### ISSUE TITLE
Add a way to view logs in-app

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#2347]
### Issue Details

Currently it takes quite a few steps to view AdGuard app logs, which could be made a lot more convenient.

1. Open app
2. Navigate to Settings > Support > Export Logs
3. Save file
4. Extract file
5. Download compatible log viewer
6. Open logs in log viewer

### Proposed solution

Similarly to Proton Mail, add a section to view the app logs, rather than having to export them, then open them in a compatible viewer.

![image](https://github.com/AdguardTeam/AdguardForiOS/assets/171407720/8e09f786-34b9-4491-a71a-da503f1e58e9)

![IMG_0104](https://github.com/AdguardTeam/AdguardForiOS/assets/171407720/fbdb70e3-3714-4b24-9298-afaa57af825f)

**Comment by ESurina** [comment]
Thank you for your request! We discussed it and unfortunately decided not to implement it.
