### ISSUE TITLE
Autofill two-factor authentication code when logging in with Apple Account

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#2349]
### Issue Details

When logging in with an Apple account, autofill does not work for two-factor authentication on auth.adguard.com.

![IMG_0108](https://github.com/AdguardTeam/AdguardForiOS/assets/171407720/f3b0f252-9385-4aac-91a2-641c0ad88db9)
![IMG_0107](https://github.com/AdguardTeam/AdguardForiOS/assets/171407720/1a39658c-33c6-4588-8b9e-765ddcfbf9b0)

### Proposed solution

Add two-factor authentication autofill on auth.adguard.com.

**Comment by bigplayer-ai** [comment]
It’s missing the auto complete tag in html

otpInput.setAttribute('autocomplete', 'one-time-code');

**Comment by ESurina** [comment]
Unfortunately, we cannot add such a feature for technical reasons.
