### ISSUE TITLE
Cookies app

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#235]
rlog.9gag.com
rlog-api.under9.co

COOKIE: 90's Generation Forum & Community by 9GAG
https://appsto.re/us/wqpS5.i

**Comment by ameshkov** [comment]
Can't find any info on these domains. What info do they store there?

**Comment by Alex-302** [comment]
@ameshkov they are collects some information
<details>
![image](http://i85.fastpic.ru/big/2016/1111/1c/49e994f1656b81fcf048dbafbd93571c.png)
</details>

**Comment by ameshkov** [comment]
@Alex-302 yep, looks like tracking pixel

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||rlog.9gag.com^
||rlog-api.under9.co^
```
