### ISSUE TITLE
iOS 18: Trying filter updates produces "Filter update error"

### ISSUE THREAD

**Issue by woofingcough** [AdguardTeam/AdguardForiOS#2351]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.5

### Environment

- OS: 18.0
- Device: iPhone 15 Pro Max

### Advanced protection for Safari

- [X] yes, I do

### Which DNS server do you use?

Custom DNS

### DNS protocol

DNS-over-HTTPS

### Custom DNS

NextDNS

### DNS filtering

- [ ] yes, I do

### DNS implementation

Native

### Tunnel mode

Split-Tunnel

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1. Update the app to the latest version
2. Try to update filters
3. voila! error

### Actual Behavior

Filters being updated

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Versty** [comment]
@woofingcough Seems like this issue is resolved with iOS 18 Developer Beta 3, could you confirm?

**Comment by woofingcough** [comment]
> @woofingcough Seems like this issue is resolved with iOS 18 Developer Beta 3, could you confirm?

Yup. All is well now.
