### ISSUE TITLE
Add activation by license key

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#2356]
### Issue Details

On desktop device we can simply input our licence number to activate our product, in iOS you force us to log into an account witch is not good.

### Proposed solution

Add like others version a way to simply enter our license code to activate.

**Comment by zzebrum** [comment]
@BirdInFire, [you can do this](https://adguard.com/kb/adguard-for-ios/solving-problems/premium-activation/):

> you can just enter a valid license key in the e-mail field leaving password field blank to activate

**Comment by ghost** [comment]
> @BirdInFire, [you can do this](https://adguard.com/kb/adguard-for-ios/solving-problems/premium-activation/):
> 
> > you can just enter a valid license key in the e-mail field leaving password field blank to activate

Thanks for the trick, just hope to see a dedicated option in a future update (so people not aware of this trick can connect with license =)

**Comment by zzebrum** [comment]
I'm afraid that's a grey area with Apple. That's why we haven't implemented it yet.
