### ISSUE TITLE
Content Blockers on iOS 18 do not have permission prompts

### ISSUE THREAD

**Issue by cameren2k** [AdguardTeam/AdguardForiOS#2358]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.5

### Environment

- OS: iOS 18 Developer Beta 3
- Device: iPhone 13

### Ad Blocking

AdGuard Base filter

### Advanced protection for Safari

- [X] yes, I do

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### DNS filtering

- [X] yes, I do

### DNS implementation

Native

### Tunnel mode

Full-Tunnel

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1. open safari extension page in settings
2. open content blocker extension besides the base content blocker
3.

### Expected Behavior

have ability to allow permissions for content blocker to read webpage

### Actual Behavior

options not shown

### Screenshots

![IMG_4894](https://github.com/user-attachments/assets/b798a3ab-809f-4a8e-9b64-8875924da17a)

**Comment by Versty** [comment]
@cameren2k Hi! 
The permissions for the base AdGuard Pro content blocker are enough to provide quality ad blocking on websites. Content blockers permissions work this way in previous versions of iOS as well.
