### ISSUE TITLE
Disable AdGuard DNS for the domains (and their subdomains) below.

### ISSUE THREAD

**Issue by bigplayer-ai** [AdguardTeam/AdguardForiOS#2359]
### Issue Details

Disable AdGuard DNS for the domains (and their subdomains) below.

### Proposed solution

Disable AdGuard DNS for the domains (and their subdomains) below.

### Alternative solution

Disable AdGuard DNS for the domains (and their subdomains) below.

**Comment by maxikuzmin** [comment]
@bigplayer-ai could you clarify, do you want to add a feature to exclusion DNS filtering for domains and subdomains?

**Comment by bigplayer-ai** [comment]
> @bigplayer-ai could you clarify, do you want to add a feature to exclusion DNS filtering for domains and subdomains?

That’s correct

**Comment by maxikuzmin** [comment]
@bigplayer-ai please clarify what you need this feature for?

**Comment by bigplayer-ai** [comment]
> @bigplayer-ai please clarify what you need this feature for?

Some domains, particularly those used by enterprises, experience compatibility issues with AdGuard DNS.  To access these domains, I need to temporarily disable AdGuard DNS.

**Comment by maxikuzmin** [comment]
@bigplayer-ai hmm... Globally, the "AdGuard DNS" server uses the same blocking rules as the "AdGuard DNS filter".
In your case, you can use the "AdGuard DNS Non-filtering" server, then under "DNS filtering" add the domain you want to Allowlist. 
That should help, please try this

**Comment by bigplayer-ai** [comment]
> @bigplayer-ai hmm... Globally, the "AdGuard DNS" server uses the same blocking rules as the "AdGuard DNS filter". In your case, you can use the "AdGuard DNS Non-filtering" server, then under "DNS filtering" add the domain you want to Allowlist. That should help, please try this

But I want the AdGuard DNS Filtering, this just makes AdGuard DNS useless for my use case? I want AdGuard DNS to filter domains...

I want a whitelist for AdGuard DNS to ignore... similar to the AdGuard DNS configuration profile creator on public AdGuard DNS...

**Comment by maxikuzmin** [comment]
@bigplayer-ai  DNS filter - "AdGuard DNS filter" - will still filter domains. 
As I have already written, the rules applied in the "AdGuard DNS" server are in the "AdGuard DNS filter". 

So if you choose "AdGuard DNS Non-filtering" server and you have "AdGuard DNS filter" enabled - domain filtering will be performed, because the filter rules are exactly the same as in "AdGuard DNS" server.
This way you will keep the filtering and can add the domains you need to the Allowlist

**Comment by bigplayer-ai** [comment]
> @bigplayer-ai DNS filter - "AdGuard DNS filter" - will still filter domains. As I have already written, the rules applied in the "AdGuard DNS" server are in the "AdGuard DNS filter".
> 
> So if you choose "AdGuard DNS Non-filtering" server and you have "AdGuard DNS filter" enabled - domain filtering will be performed, because the filter rules are exactly the same as in "AdGuard DNS" server. This way you will keep the filtering and can add the domains you need to the Allowlist

But I use only the adguard iOS application with native dns settings  i don’t use extra dns server

**Comment by maxikuzmin** [comment]
@bigplayer-ai but I'm not talking about additional DNS servers. I'm only talking about those DNS servers that are in the application in DNS protection -> DNS server

Here's what you need to do:

- Go to Protection tab -> DNS protection -> DNS server -> select "AdGuard DNS Non-filtering" server
- Check if "AdGuard DNS filter" is enabled (by default it is enabled.) It is located at: Protection tab -> DNS protection -> DNS filtering -> DNS filters.
- Add the domain you need to Allowlist: Protection tab -> DNS protection -> DNS filtering -> Allowlist
- Enable protection and check access to the domain added to the Allowlist

**Comment by bigplayer-ai** [comment]
> @bigplayer-ai but I'm not talking about additional DNS servers. I'm only talking about those DNS servers that are in the application in DNS protection -> DNS server
> 
> Here's what you need to do:
> 
> * Go to Protection tab -> DNS protection -> DNS server -> select "AdGuard DNS Non-filtering" server
> * Check if "AdGuard DNS filter" is enabled (by default it is enabled.) It is located at: Protection tab -> DNS protection -> DNS filtering -> DNS filters.
> * Add the domain you need to Allowlist: Protection tab -> DNS protection -> DNS filtering -> Allowlist
> * Enable protection and check access to the domain added to the Allowlist



I don’t have DNS filtering option in any of my settings I believe this is a limitation because I use native DNS server implementation.

![](https://i.imgur.com/Q6ahpyy.png)

**Comment by maxikuzmin** [comment]
@bigplayer-ai this is because the DNS implementation is set to "Native" in your case. 
Please choose "AdGuard"

**Comment by bigplayer-ai** [comment]
> @bigplayer-ai this is because the DNS implementation is set to "Native" in your case. Please choose "AdGuard"

This is not possible for my own use case, I use different VPN provider both local and remote so I can not use adguard implementation!

**Comment by maxikuzmin** [comment]
@bigplayer-ai but in Native mode only the DNS of the system is used. In AdGuard, DNS filtering is completely disabled if you use Native mode, so you can't exclude filtering for any domain as long as you use Native mode

**Comment by bigplayer-ai** [comment]
> @bigplayer-ai but in Native mode only the DNS of the system is used. In AdGuard, DNS filtering is completely disabled if you use Native mode, so you can't exclude filtering for any domain as long as you use Native mode

So how does the Native adguard public dns configuration profile constructor exclude domains?

https://adguard-dns.io/en/public-dns.html


![](https://i.imgur.com/QXkMnEe.png)

**Comment by maxikuzmin** [comment]
@bigplayer-ai we are talking about different topics:
Using Native mode - in the AdGuard application DNS filtering is disabled, system DNS is applied, in this case we cannot affect the system DNS

Using https://adguard-dns.io/en/public-dns.html you can certainly add an exclusion in the constructor, then add the DNS address to the system and your exclusion will be applied, but the AdGuard app will not be able to affect the system DNS in this case

**Comment by bigplayer-ai** [comment]
> @bigplayer-ai we are talking about different topics: Using Native mode - in the AdGuard application DNS filtering is disabled, system DNS is applied, in this case we cannot affect the system DNS
> 
> Using https://adguard-dns.io/en/public-dns.html you can certainly add an exclusion in the constructor, then add the DNS address to the system and your exclusion will be applied, but the AdGuard app will not be able to affect the system DNS in this case

Hi maxikuzmin,

According to this post, will using AdGuard DNS Protection with Native DNS Implementation mode and the Default AdGuard DNS (DNS-over-HTTPS) server in the iOS AdGuard app **block ads and trackers**?

Can you explain why in my iOS (iPhone and iPad) using the Adguard iOS application, the AdGuard DNS test on Safari Shows that I am using the default AdGuard DNS configuration? from my own testings it blocks ads inside applications using Adguard iOS application's native implementation mode for DNS.

<img width="1066" alt="image" src="https://github.com/user-attachments/assets/f9faaadb-0e6e-40cd-9816-70e7fe009442">

Thank you!

**Comment by maxikuzmin** [comment]
@bigplayer-ai if you use AdGuard DNS server in system settings with Native mode - of course, the server functionality will be performed: blocking ads, trackers and malicious sites. If you use AdGuard DNS server - the test site will show you "running" status

**Comment by bigplayer-ai** [comment]
> @bigplayer-ai if you use AdGuard DNS server in system settings with Native mode - of course, the server functionality will be performed: blocking ads, trackers and malicious sites. If you use AdGuard DNS server - the test site will show you "running" status

the picture is taken only on a device using AdGuard iOS application native implementation of Adguard DNS.

so is it possible to add this feature of excluding domains using the adguard iOS application instead of using the public Adguard DNS?

**Comment by maxikuzmin** [comment]
@bigplayer-ai but we found out that you can configure exclusions for the domains you want using AdGuard DNS non filtering server + AdGuard DNS filter. 
When using Native mode, you can't control DNS systems, we can't add such functionality
