### ISSUE TITLE
Rearrange & Group User Filters [Feature Request]

### ISSUE THREAD

**Issue by gotitbro** [AdguardTeam/AdguardForiOS#236]
Hey guys,
I would like to request a feature whereby you can **rearrange User filters** just like you can rearrange extension in Safari (http://i.imgur.com/27TiJQs.jpg) by dragging the hamburger slider on each filter (the slider can be added on the left side).

This will vastly improve organization of **User Filters**, right now when I add a filter it stays in the last place below all previously added filters, if this feature is added I can put the filter for the same site together and so on.

Please look into this request as I believe it will benefit a lot of other users as well.

Thanks.

**Edit:** Grouping of filters can also be added, so that when I tap the "**+**" in the top right corner it asks to create a new group for filters in which we can add filters, this can be helpful when importing filters (https://github.com/AdguardTeam/AdguardForiOS/issues/27) which will create a new group for the import and ask to name to name the group when importing the filters. 
And when a filter is added from the **Action extension** the app asks which group to add it to. 
This sounds like a lot of work but will greatly improve the User Filters feature.

**Comment by gotitbro** [comment]
@ameshkov @Stillness-2 What are your thoughts about this?

**Comment by ameshkov** [comment]
@gotitbro he's on vacations:)

**Comment by ameshkov** [comment]
What for me, I suggest doing it different way.

You see, I don't like the whole `data grid` approach for user filters. It just ties your hands with what you can do with it.

Instead I suggest implementing user filter as a huge textarea field. New line - new rule.

**Comment by ameshkov** [comment]
Something like this:
http://a3.mzstatic.com/us/r30/Purple20/v4/ae/fe/91/aefe917c-cac3-0e7b-51f5-bd45a0737949/screen696x696.jpeg

**Comment by gotitbro** [comment]
@ameshkov 

> he's on vacations:)

Oh, hope he enjoys :)

> Instead I suggest implementing user filter as a huge textarea field. New line - new rule.

I would love to see something like that implemented as well that would be much more versatile than the current approach. Can this be done? I find the current approach very clunky to be honest.

**Comment by ameshkov** [comment]
> Can this be done?

This definitely can and should, but we'll do it along with the planned app re-design. Actually, new design is ready and should have been implemented along with Pro version release, but as it often happens we've missed all the deadlines:)

**Comment by gotitbro** [comment]
@ameshkov That's great, I would also like to suggest a toggle for **enabling and disabling** the whole "**User Filter**" on the **_iOS app_** and on other platforms as well (such as the **_browser extension_**). 

This would prove to be very useful as sometimes problems are caused with filters the user has created and the user would be able to test this very quickly by just disabling the toggle for the User Filter.

_Much like what **uBlock** offers in the browser extension:_ http://i.imgur.com/Pi8PoA1.png?1

Would really help dissect false positives caused by custom user filters.

**Comment by ameshkov** [comment]
This makes sense, thank you for the suggestion!

**Comment by PentagramTr** [comment]
> That's great, I would also like to suggest a toggle for enabling and disabling the whole "User Filter" on the iOS app and on other platforms as well (such as the browser extension).
> 
> This would prove to be very useful as sometimes problems are caused with filters the user has created and the user would be able to test this very quickly by just disabling the toggle for the User Filter.
> 
> Much like what uBlock offers in the browser extension: http://i.imgur.com/Pi8PoA1.png?1
> 
> Would really help dissect false positives caused by custom user filters.

---

 @ameshkov 

Hello,
It is very annoying to delete and add again the User Filter every time for false positives.A button is necessary for that.
Can this feature be added to version 2.5.0?

**Comment by ameshkov** [comment]
Possible in v3.0
