### ISSUE TITLE
Native Adguard DNS is not working after iOS 17.6

### ISSUE THREAD

**Issue by bigplayer-ai** [AdguardTeam/AdguardForiOS#2361]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.5 (1019)

### Environment

- OS: iOS 17.6/iPadOS 17.6
- Device: iPhone 12 Pro, iPad 12.9" Pro 4th Gen 2020 

### Ad Blocking

AdGuard Base filter

### Advanced protection for Safari

- [X] yes, I do

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### DNS filtering

- [X] yes, I do

### DNS implementation

Native

### Tunnel mode

Split-Tunnel

### Issue Details

Steps to reproduce:
1.Update to 17.6
2. Native DNS Adguard DNS does not work
3. see the results in adguard.com: "[https://adguard.com/en/test.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fadguard.com%2Fen%2Ftest.html)"

### Expected Behavior

Adguard DNS to work properly after iOS 17.6 update.

### Actual Behavior

Adguard DNS is not activated.

### Screenshots

<details><summary>Screenshot 1</summary>
<img src="https://github.com/user-attachments/assets/5c5358b1-9447-4f01-b06c-7c3c79b8471d" alt="image">
</details>

<details><summary>Screenshot 2</summary>
<img src="https://github.com/user-attachments/assets/050d0d64-1aec-45dd-90a4-93a09c931f62" alt="image">
</details>

**Comment by maxikuzmin** [comment]
@bigplayer-ai if you select Native - DNS filtering in AdGuard is completely disabled. If you select Native mode, the system DNS is used. What DNS do you use in the system settings?

**Comment by bigplayer-ai** [comment]
> @bigplayer-ai if you select Native - DNS filtering in AdGuard is completely disabled. If you select Native mode, the system DNS is used. What DNS do you use in the system settings?

my custom personal Adguard DNS server, so all the filtering rules and settings happens on the Adguard DNS dashboard...

**Comment by maxikuzmin** [comment]
@bigplayer-ai so you are using Native mode to use AdGuard DNS server in system settings?

**Comment by bigplayer-ai** [comment]
> @bigplayer-ai so you are using Native mode to use AdGuard DNS server in system settings?

That’s correct

**Comment by maxikuzmin** [comment]
@bigplayer-ai please specify which DNS address you are adding, and also the path you are adding the DNS to the system settings

**Comment by maxikuzmin** [comment]
@bigplayer-ai any news?

**Comment by bigplayer-ai** [comment]
> @bigplayer-ai any news?

When installing adguard dns profile it works perfectly fine, but when using the AdGuard application as the system dns it does not work...

most likely the problem is adguard application

**Comment by maxikuzmin** [comment]
@bigplayer-ai you already said that AdGuard DNS doesn't work in Native mode. Please answer my questions:

please specify which DNS address you are adding, and also the path you are adding the DNS to the system settings

**Comment by bigplayer-ai** [comment]
> @bigplayer-ai you already said that AdGuard DNS doesn't work in Native mode. Please answer my questions:
> 
> please specify which DNS address you are adding, and also the path you are adding the DNS to the system settings

When choosing application dns it doesn’t work

![IMG_7202](https://github.com/user-attachments/assets/60ddf216-46aa-49f6-8050-1f3d0818db1e)


When choosing external Adguard DNS profile it works fine, this works just fine:

![IMG_7204](https://github.com/user-attachments/assets/c5961329-511e-43bc-ab40-dd5afd5d28d6)

**Comment by maxikuzmin** [comment]
@bigplayer-ai I see. The profile may not have been installed correctly, try reinstalling the profile for Native mode.
Reinstall AdGuard and try again.
I have tested your problem on several devices - everything works correctly, the test site passes validation successfully

**Comment by bigplayer-ai** [comment]
> @bigplayer-ai I see. The profile may not have been installed correctly, try reinstalling the profile for Native mode. Reinstall AdGuard and try again. I have tested your problem on several devices - everything works correctly, the test site passes validation successfully

Idk if you did smth but it was fixed by it self :octocat:

**Comment by maxikuzmin** [comment]
@bigplayer-ai it's magic!  Glad to hear that, I'll close the issue for now, please if the problem happens again, reopen the issue
