### ISSUE TITLE
Telegram built-in browser is full of ads

### ISSUE THREAD

**Issue by mrdc** [AdguardTeam/AdguardForiOS#2366]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.5

### Environment

- OS: 17.6.1
- Device: iPad

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, EasyPrivacy, Peter Lowe's Blocklist

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

NoCoin Filter List

### Language-specific

AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Ukrainian filter, Adblock List for Finland, Bulgarian list, Dandelion Sprout's Nordic Filters, Dandelion Sprout's Serbo-Croatian List, EasyList China, EasyList Czech and Slovak, EasyList Dutch, EasyList Germany, EasyList Hebrew, EasyList Italy, EasyList Lithuania, EasyList Polish, EasyList Portuguese, EasyList Spanish, EasyList Thailand, Estonian List, Frellwit's Swedish Filter, Greek AdBlock Filter, Hungarian filter, Icelandic ABP List, IndianList, KAD - Anti-Scam, Latvian List, List-KR, Liste AR, Liste FR, Macedonian adBlock Filters, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Persian Blocker, Polish Annoyances Filters, Polish Anti Adblock Filters, Polish Anti-Annoying Special Supplement, Polish GDPR-Cookies Filters, Polish Social Filters, road-block light, ROList, ROLIST2, RU AdList - Counters, Xfiles, xinggsf, YousList

### Advanced protection for Safari

- [ ] yes, I do

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

DNS protection disabled

### DNS filtering

- [ ] yes, I do

### DNS implementation

DNS protection disabled

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1. Install recent Telegram for iPadOS (haven’t checked iOS yet)
2. Set in Telegram settings to open links in built-in browser
3. Open any link in Telegram
4. The Telegram’s built-in custom browser allows all ads on pages and these ads are not blocked by AdGuard.

### Expected Behavior

Ads are blocked.

### Actual Behavior

Ads are not blocked.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

It’s looks like despite all browsers on iOS/iPadOS use WebKit by default, ad blocking extensions are not enabled globally.

**Comment by maxikuzmin** [comment]
@mrdc in this case we can filter only at the DNS level. On IOS we use a lot of filtering as filters / rules just for Safari browser.

 By the way in android telegram HTTPS certificate will not be trusted either, and there will be the same limitation of using only DNS filtering. 
 It will be better to use compatible browsers
