### ISSUE TITLE
Invalid blocking web site loading

### ISSUE THREAD

**Issue by yoonlucas** [AdguardTeam/AdguardForiOS#2371]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.5(1019)

### Environment

- OS: IOS
- Device: Mobile iphone 15

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Advanced protection for Safari

- [ ] yes, I do

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

DNS protection disabled

### DNS filtering

- [ ] yes, I do

### DNS implementation

DNS protection disabled

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1. Enter the online gdb with adguard on mobile

### Expected Behavior

![image](https://github.com/user-attachments/assets/afad27ce-1769-4857-ae73-a05fd837cd6d)

### Actual Behavior

![image](https://github.com/user-attachments/assets/bb5afa43-3ad2-4f7e-8213-a6fd6d5f376b)

### Screenshots

<details><summary>Screenshot 1</summary>

![image](https://github.com/user-attachments/assets/bb5afa43-3ad2-4f7e-8213-a6fd6d5f376b)

</details>

**Comment by Versty** [comment]
@yoonlucas Please report any incorrect blocking via `Report incorrect blocking` option in AdGuard application. 
*Settings tab -> Support -> Report incorrect blocking*
