### ISSUE TITLE
Customizable application icon for IOS 18

### ISSUE THREAD

**Issue by OlgaPetukhova** [AdguardTeam/AdguardForiOS#2372]
### Issue Details

In iOS 18 new feature was added - users can customize their home screen by changing the colour of icons. 

### Proposed solution

To add the opportunity to change the background of AdGuard app icon to dark mode.

**Comment by ghost** [comment]
Resource: https://www.koombea.com/blog/preparing-your-app-icon-for-ios-18-dark-and-tinted-modes/

**Comment by maxikuzmin** [comment]
@OlgaPetukhova @emeritaacuity0u I checked this and icon customization for Dark and Tinted modes is available for AdGuard

**Comment by ameshkov** [comment]
@maxikuzmin let's not close it for now, we indeed don't provide icons for it so the ones available may be auto-generated (?)
