### ISSUE TITLE
Loading fail site

### ISSUE THREAD

**Issue by yoonlucas** [AdguardTeam/AdguardForiOS#2373]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.5

### Environment

- OS: 17.6
- Device: iPhone 15

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Advanced protection for Safari

- [ ] yes, I do

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

DNS protection disabled

### DNS filtering

- [ ] yes, I do

### DNS implementation

DNS protection disabled

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1. Go to ```https://picrew.me``` with adguard.

### Actual Behavior

<img width="324" alt="image" src="https://github.com/user-attachments/assets/eb80c859-ac3f-4037-800e-bba49423e873">

### Screenshots

<details><summary>Screenshot 1</summary>

<img width="324" alt="image" src="https://github.com/user-attachments/assets/71e15746-9223-4780-8284-35ddb18dea84">

</details>

**Comment by Versty** [comment]
@yoonlucas Please report this issue to our filter maintainers. Use the `Report incorrect blocking` option on Support screen in the Settings tab in AdGuard application.
