### ISSUE TITLE
http:///www.jin115.com

### ISSUE THREAD

**Issue by charlotterio** [AdguardTeam/AdguardForiOS#2374]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.5

### Environment

- OS: ios 17
- Device: iphone 14 pro

### Advanced protection for Safari

- [ ] yes, I do

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

DNS protection disabled

### DNS filtering

- [ ] yes, I do

### DNS implementation

DNS protection disabled

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1. Turn on the Adguard
2. Enter the http://www.jin115.com
3. Refresh.

Loading blocked.

### Expected Behavior

<img width="326" alt="image" src="https://github.com/user-attachments/assets/4b86e8f8-0488-4aef-94b9-fa257d00f743">

### Actual Behavior

<img width="275" alt="image" src="https://github.com/user-attachments/assets/3deb4d72-1d72-4fc6-80e7-2548192bf5c4">

<img width="321" alt="image" src="https://github.com/user-attachments/assets/2f92a423-2516-4ff1-a668-b769ab07d67e">

**Comment by Versty** [comment]
@charlotterio Hi! 
Please report the incorrect blocking via `Report incorrect blocking` option in AdGuard application. 
*Settings tab -> Support -> Report incorrect blocking*
