### ISSUE TITLE
AdGuard player shows an error "Sign in to confirm that you're not a bot"

### ISSUE THREAD

**Issue by ESurina** [AdguardTeam/AdguardForiOS#2375]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.5

### Environment

- OS: 18.0
- Device: 13 Pro

### Advanced protection for Safari

- [ ] yes, I do

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

DNS protection disabled

### DNS filtering

- [ ] yes, I do

### DNS implementation

DNS protection disabled

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1. Sign in your YouTube account
2. Open any youtube video
3. Tap on Share
4. Tap More
5. Select Block Youtube Ads

### Expected Behavior

The video is playing

### Actual Behavior

There is an error "Sign in to confirm that you're not a bot"

### Screenshots

<details><summary>Screenshot 1</summary>
![IMG_0026](https://github.com/user-attachments/assets/5fafda1f-5eaf-4286-b146-022effbba530)

</details>

### Additional Information

The problem is not always reproduced. Some VPN locations help to reproduced it stable. It looks like some kind of protection against bots.

**Comment by PavelParkhomenko** [comment]
+ticket 963067

**Comment by kael131** [comment]
@Numci why has this been closed as a "won't fix" without a comment as to why? The problem is that you can't click on anything to sign in.

edit: nvm, I realise my VPN was autoconnecting after turning it off, making sure it was properly off meant this no longer appeared.
