### ISSUE TITLE
Extension fails to provide the blocking rule for some elements on asuracomic.net to AdGuard app 

### ISSUE THREAD

**Issue by Blastorix** [AdguardTeam/AdguardForiOS#2376]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.5

### Environment

- OS: 18.0
- Device: iPhone 11 Pro

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Advanced protection for Safari

- [X] yes, I do

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

DNS protection disabled

### DNS filtering

- [ ] yes, I do

### DNS implementation

DNS protection disabled

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server: N/A (Did not change)
Fallback server: N/A (Did not change)
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1. Open asuracomic.net and select any comic for reading
2. Open a chapter of any comic
3. Use element blocking to remove certain element
4. Click open in open page in AdGuard

### Expected Behavior

A Safari User rule should be added in the app.

### Actual Behavior

No such rule is added for asuracomic.net and the element keeps comic back since the rule is not added.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Versty** [comment]
@Blastorix Thank you for reporting! 
We have tried to reproduce this issue on our side, but to no avail. 

Could you please provide a screen recording showing the mentioned problem?

**Comment by Blastorix** [comment]
Here's the video showing the issue. I don't know if there is an error on my settings' end. As you can see, there is no banner updating that the element blocked was actually added to the user rules. Please advise.

https://github.com/user-attachments/assets/3179e836-1ad7-475b-a00d-4a515cf90482

**Comment by Blastorix** [comment]
@Versty, it would be helpful if you showed me how you attempted to reproduce the problem so I can copy the settings and see if I configured something wrong.

**Comment by Versty** [comment]
@Blastorix Thank you! 
We have managed to reproduce this problem on our side. 
Remarkable that the rules for flash player elements from the same page can be added correctly to the application.

**Comment by Blastorix** [comment]
Is there a workaround that I can do on my end? Or is the only way to wait for an update?

**Comment by Versty** [comment]
@Blastorix We have discussed this problem with development team. 
Unfortunately, the blocking rule for certain elements can not be created by extension tool, but you still can enter the desired rule to the application manually.  

The article ["How to create your own ad filters"](https://adguard.com/kb/general/ad-filtering/create-own-filters/) will guide you on how to create a proper rule.
