### ISSUE TITLE
Protect from DPI like in PC version.

### ISSUE THREAD

**Issue by marknefedov** [AdguardTeam/AdguardForiOS#2381]
### Issue Details

VPN often sacrifices speed and sometimes I don’t want to have IP changed, DPI protection on Mac version fulfilled my needs.

### Proposed solution

Port DPI protection from MacOS version.

### Alternative solution

Zapret Linux, goodbye dpi windows.

**Comment by Versty** [comment]
@marknefedov Thank you for suggestion! 
This issue duplicates #2076, please proceed to the linked issue and put a 👍 emoji to the initial post to vote for implementing this feature.
