### ISSUE TITLE
Unable to connect when certain DNS servers are configured during cellular communication

### ISSUE THREAD

**Issue by Am4hisa** [AdguardTeam/AdguardForiOS#2383]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.5(1019)

### Environment

- OS: 18.0.1
- Device: iphone15 pro

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Language-specific

AdGuard Japanese filter

### Advanced protection for Safari

- [X] yes, I do

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### DNS filtering

- [X] yes, I do

### Custom DNS filter

https://filters.adtidy.org/dns/filter_1_ios.txt

### DNS implementation

AdGuard

### Tunnel mode

Full-Tunnel

### Low-level settings

 Blocked response TTL: 1s
Blocking mode: Default
Background Apps update: Default

### Issue Details

When using cellular communication, selecting Adguard DNS or Cloudflare DNS in the settings prevents the connection. This issue does not occur when using Wi-Fi. I have removed and reconfigured the VPN settings, but the problem persists. I mentioned that I subscribe to the AdGuardDNS filter, but I usually do not use it. Currently, I am subscribed as a workaround since I cannot connect to AdguardDNS due to this issue. 

### Expected Behavior

Connection should be possible.

### Actual Behavior

Connection is not possible.

### Additional Information

I have sent the log files and a screen recording of the issue via email.

**Comment by maxikuzmin** [comment]
@Am4hisa in order to troubleshoot this issue, we need to get your application logs.

Here's what we need you to do:

1. Open Settings -> General -> Turn **Advanced mode** on -> Advanced settings -> Turn **Debug logs** switch on.
2. Reproduce the problem, then remember the exact time it happened.
3. Open *Settings -> Support -> Export logs*.
4. System popup will be opened -> Choose **Mail** app.
5. Enter `qa@adguard.com` as a recipient and:
    - include `[iOS]` keyword and `ISSUE_NUMBER` in the subject of your email
    - specify the exact time when the issue occurred

**Comment by Am4hisa** [comment]
@maxikuzmin 

As mentioned in the Additional Information section, I sent the logs via email, but are you asking if additional information is needed? Or does this mean that my previous submission did not go through correctly, and I should resubmit?

For now, I have sent the same logs I previously submitted to `qa@adguard.com`.

**Comment by maxikuzmin** [comment]
@Am4hisa sorry, but I don't see your logs in email qa@adguard.com. Could you resend the logs? Make sure to include [iOS] keyword and ISSUE_NUMBER in the subject of your email and specify the exact time when the issue occurred

**Comment by Am4hisa** [comment]
I'm not sure why. The email address domain is `@kann.so`, and the subject is `[iOS] 2383 AdguardForiOS from Am4hisa`. I just sent it. 10/23/2024 17:34 (UTC)

I first sent an email to [apple@adguard.com](mailto:apple@adguard.com). The subject was AdguardTeam/AdguardForiOS Issue #2383, and I sent it on 10/15/2024 at 11:14 (UTC).

The issue happened at 10/15/2024 16:14:09. I think there's a record of this in the log file around that time.

**Comment by maxikuzmin** [comment]
@Am4hisa it's weird, but I still don't see any emails from you, including I searched by subject and @kann.so and in my spam folder. Please re-check again if you are sending correctly, check your Sent folder, or try sending from another email or app

**Comment by Am4hisa** [comment]
@maxikuzmin 
Well, I wonder why that is. Instead of sending an email, I'll write it down below.  
Since I cannot reproduce the issue after updating to 4.5.7, I can not provide any further information.
Log file: _Link have been deleted for privacy reasons._
Screen recording: _Link have been deleted for privacy reasons._
The issue happened at 10/15/2024 16:14:09. I think there's a record of this in the log file around that time.

**Comment by maxikuzmin** [comment]
@Am4hisa thank you, we'll look at your logs anyway, it'll take us a while

**Comment by maxikuzmin** [comment]
@Am4hisa we need some more time, please wait

**Comment by Am4hisa** [comment]
@maxikuzmin 

As I mentioned before, I’m not experiencing any issues on my end following the app update, so I’m not facing any problems now. However, if this issue is indeed a bug, I hope the logs and videos I provided will be helpful in resolving it.

**Comment by maxikuzmin** [comment]
@Am4hisa I think the issue has been resolved in the latest update, thanks to the CoreLibs update. I will close this issue for now. Please, if the problem happens again, please re-open the issue
