### ISSUE TITLE
Keyboard scrolling no longer works as of iPadOS 18

### ISSUE THREAD

**Issue by fancyham** [AdguardTeam/AdguardForiOS#2384]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.5

### Environment

- OS: iPadOS 18
- Device: iPad Pro 11, iPad Pro 12.9

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Advanced protection for Safari

- [ ] yes, I do

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

DNS protection disabled

### DNS filtering

- [ ] yes, I do

### DNS implementation

DNS protection disabled

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1. Browse websites in Safari using external bluetooth keyboard
2. Load a new web page
3. Try to scroll web page by using spacebar on external keyboard

### Expected Behavior

Normally web page scrolls down about one-screen’s worth

### Actual Behavior

Nothing happens

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

It feels almost like Safari is focused on an invisible text form element when the page loads, and keyboard events are going to that form field, rather than triggering a scroll? 

Sometimes I can get it to keyboard-scroll by typing esc once or twice, or tapping tab, then using the spacebar but not always.  If I tap the screen with my finger on an area of white space, I can usually keyboard scroll again.

This seems to be a new problem as of iOS 18, and it also happens when I’ve disabled all extensions/content blockers.

It feels like it’s related to ads — but if that’s the case, it shouldn’t happen when all the ads are blocked? (perhaps they’re just invisible but still focused?)

**It might just be an iOS 18 bug?  I’ve reported it in Apple’s own bug reporter as well.**

**Comment by Versty** [comment]
@fancyham Hi! 
If the problem persists with AdGuard protection disabled and content blockers disabled in Safari settings, then the error is on the iOS side.

**Comment by fancyham** [comment]
I think it’s iOS side!  Closing this issue and hoping Apple fixes the problem soon.  Thx
