### ISSUE TITLE
VPN Split-Tunnel with WireGuard VPN on Demand

### ISSUE THREAD

**Issue by Patten310** [AdguardTeam/AdguardForiOS#2385]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Hi,

i have The WireGuard VPN activated on Demand to Connect my iPhone to my Home Network. Is it possible to juse it in SplitTunnel Mode with The AdGuard DNS VPN active?

**Comment by Versty** [comment]
@Patten310 If WireGuard VPN profile can be placed to "Personal VPN" section in the system settings, while AdGuard is running from "Device VPN" section, then yes. 

Both sections can be found in the System settings -> VPN.

**Comment by CapSel** [comment]
For anyone searching how to make Wireguard work with Adguard DNS VPN - you can't.

iOS supports "Personal VPN" configurations only if one of built-in protocols is used - https://developer.apple.com/documentation/networkextension/personal-vpn
Wireguard is not mentioned there.

Only one "Device VPN" can be enabled at a time.

It also does not matter if you have "Split" mode enabled in Adguard.
