### ISSUE TITLE
Opening YouTube videos in AdGuard’s internal ad-free browser doesn’t work on iOS 18

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForiOS#2387]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.6

### Environment

- OS: 18
- Device:

### Advanced protection for Safari

- [ ] yes, I do

### Which DNS server do you use?

System default

### DNS protocol

DNS protection disabled

### DNS filtering

- [ ] yes, I do

### DNS implementation

AdGuard

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

When trying to open adgard's youtube player - nothing happens

Steps:
* Go to YouTube
* Tap the “share” button
* Select AdGuard player - nothing happens, the player doesn't work

### Expected Behavior

AdGuard player works for iOS 18

### Actual Behavior

AdGuard player doesn't work for iOS 18

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by jmeier5261** [comment]
Came here to report this. The link from the share screen is completely non functioning after update to 4.5.6.

I will add that I also removed both YouTube and AdGuard and freshly installed in addition to restarting the device. I am on iOS18 on an iPhone 13 Pro.

**Comment by maxikuzmin** [comment]
@jmeier5261 we will fix this in the upcoming 4.5.7 update
