### ISSUE TITLE
Tiktok requests going crazy 

### ISSUE THREAD

**Issue by TrapNouz** [AdguardTeam/AdguardForiOS#2390]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.7

### Environment

- OS:18.0.1
- Device:iphone 13

### Advanced protection for Safari

- [X] yes, I do

### Which DNS server do you use?

Cloudflare DNS

### DNS protocol

Regular

### DNS filtering

- [X] yes, I do

### DNS implementation

AdGuard

### Tunnel mode

Split-Tunnel

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1.
2.
3.

### Actual Behavior

I have 83 million requests from tiktok but when going in requests tiktok have 2 requests 

### Screenshots

<details><summary>Screenshot 1</summary>

![IMG_0026](https://github.com/user-attachments/assets/e21afc01-843c-42a1-b835-638dfc67f0b8)

</details>

**Comment by jordansworld** [comment]
tiktok hosts alot of trackers. i get alot of requests as well because it will keep trying to reach the domain when its blocked.

**Comment by Versty** [comment]
@NoozPrime Tiktok app sends a lot of requests to the server, as @jordansworld said. However, Recent activity log stores only last 1500 entries, that explains the difference between the number in the most active section and the number of `tiktokcdn-us.com` events in the recent activity log.
