### ISSUE TITLE
Enabling a filter is not updating the filter!

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#2394]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.7

### Environment

- OS: 18.1
- Device: iphone 14 pro
- 

I enabled a filter (for example, adguard cookie filter). After waiting for “rules are being converted” and “content blockers are being updated” messages. The date shows “2022”.

This is not how it should.

when you enable a filter, it should download the latest filter!

right now you have to enable the filters and then go to the main page and refresh to download all the latest filter updates.

### Advanced protection for Safari

- [ ] yes, I do

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

DNS protection disabled

### DNS filtering

- [ ] yes, I do

### DNS implementation

DNS protection disabled

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce (see above)

### Actual Behavior

It didn’t update the filter with the latest versions.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by ESurina** [comment]
The functionality of the application does not imply that filters should be updated when turned on. And unfortunately, we do not plan to add this function in the near future.
