### ISSUE TITLE
"Advanced protection" switch will be ON again after switch off then restart app

### ISSUE THREAD

**Issue by qlee01-dev** [AdguardTeam/AdguardForiOS#2397]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.7

### Environment

- OS:
- Device:
ios 18.1.1
iphone 14 pro

### Advanced protection for Safari

- [ ] yes, I do

### Which DNS server do you use?

Custom DNS

### DNS protocol

DNS-over-QUIC

### DNS filtering

- [ ] yes, I do

### DNS implementation

DNS protection disabled

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1. switch off advanced protection 
2.close app
3.open app

### Actual Behavior

auto switch on again

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Versty** [comment]
@qlee001 This issue duplicates #2152
