### ISSUE TITLE
Adguard premium safari ios problem

### ISSUE THREAD

**Issue by GLlgGL** [AdguardTeam/AdguardForiOS#2399]
Hi

Can someone tell me how to remove page redirections on click on this link

[Link](https://www.filma24.band/out-of-my-mind-2024-me-titra-shqip/?server=3)

I am talking for these two links which if I block them with custom rule they detect the block and a message appears.

psegeeva.....com
broadensilkslus....com

![image](https://github.com/user-attachments/assets/1f8b5b37-816d-4d8c-a9fd-0e9260877e26)

I am able to block those eith these two rules on desktop but these doesnt seem to work on ios safari

#%#//scriptlet("prevent-window-open", "!abyss.to", "1")
#%#//scriptlet('trusted-click-element', 'body > #player + #overlay')

**Comment by Versty** [comment]
@GLlgGL Hi! 

In this case, more information is required, please report the problem using [this link](https://github.com/AdguardTeam/AdguardFilters/issues/new/choose).
