### ISSUE TITLE
Ticketmaster

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#240]
bttn.io (usebutton.com)
assets.adobedtm.com (https://apps.ghostery.com/en/apps/adobe_dynamic_tag_management)

Ticketmaster -Tickets for Concerts, Sports & Shows by Ticketmaster
https://appsto.re/us/TlxZD.i

**Comment by Alex-302** [comment]
Added the first.
The second rule will break a lot os sites.
