### ISSUE TITLE
Let users to proceed with Safari's blockage like uBlock Origin ext. in computers' web browsers.

### ISSUE THREAD

**Issue by antdude** [AdguardTeam/AdguardForiOS#2400]
### Issue Details

Some web (page/site)s are blocked and would like to proceed to see them. I have to disable AdGuard to access them. Others and I like my idea as shown in https://old.reddit.com/r/Adguard/comments/1h6hcvm/is_there_a_way_to_have_adguard_pro_ask_me_what_to/.

### Proposed solution

Have Adguard give an option to proceed to the blocked web site/page.

**Comment by ESurina** [comment]
Unfortunately, Safari has technical limitations that do not allow us to do this.

**Comment by antdude** [comment]
Thanks. What about third party web browser apps?
