### ISSUE TITLE
AdGuard not working on IOS 16. No content blockers are listed in Safari.

### ISSUE THREAD

**Issue by volanin** [AdguardTeam/AdguardForiOS#2401]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.7

### Environment

- OS: 16.7.10
- Device: iPhone X and iPhone 8 Plus

### Issue Details

Steps to reproduce:
1. Install AdGuard on iOS 16
2. Update everything
3. No content blockers are displayed in Safari Settings, and ads appear

### Expected Behavior

Content blockers should be displayed in the Safari Settings.

### Actual Behavior

No content blockers are displayed in Safari Settings. The content blockers list is empty. And ads appear. Happens on both my iPhone X and my wife's iPhone 8 Plus.

I already tried uninstalling and reinstalling AdGuard.
I also tried rebooting the phone.

### Screenshots

<details><summary>AdGuard Main Screen</summary>
<img width="344" src="https://github.com/user-attachments/assets/e7d3fe4e-142d-44f4-9d6e-88d91d6839cc">

</details>
<details><summary>Safari Content Blockers Settings</summary>

<img width="344" src="https://github.com/user-attachments/assets/ef3eb7dc-1cf9-4e48-805d-120c609b5069">

</details>

**Comment by Versty** [comment]
@volanin Hi! 
Our content blockers are located in System settings -> Safari -> Extensions. 
Hope this helps!

**Comment by volanin** [comment]
What?!
I can't believe I was looking in the wrong place!

But then, there seems to be a problem in one of the filters, because I was testing in [www.slashdot.org](url) and it still has ads, and now it is also displaying an error message (screenshot attached). I tested with other urls and they are indeed working fine with no ads.

Thank you a lot!

<details><summary>Slashdot Error</summary>
<img width="344" src="https://github.com/user-attachments/assets/37bcc6f7-ea60-4eac-b77c-4ccc3dd4dd44">
</details>

**Comment by Versty** [comment]
@volanin 

Follow the steps below to sort out the banner problem:
1. Make sure that `AdGuard Base filter` and `AdGuard Mobile Ads filter` are enabled 
2. Update filters (keep the app in the foreground until filters update is finished) 
3. Enable Advanced protection toggle, if possible. 
Then go to System settings -> Safari -> Extensions -> AdGuard -> All Websites -> Allow  

If the banner is still displayed after performing the listed steps, please report this issue to our filter maintainers via this link https://github.com/AdguardTeam/AdguardFilters/issues/new/choose
