### ISSUE TITLE
Feature Request: Auto Connect/Disconnect VPN Based on Network Whitelist

### ISSUE THREAD

**Issue by lekman** [AdguardTeam/AdguardForiOS#2402]
### Issue Details

VPN connection can be automated using an automation in the Shortcuts app, but is inconsistent and spams alert messages.

### Proposed solution

Implement a better kill switch, where the user can configure if 4G should use VPN and set trusted Wi-Fi networks.

- If the user joins a trusted/whitelisted network, VPN disables.
- If the user disconnects, then VPN is automatically connected to 4G (if configured). 
- If the user joins a non-whitelisted network, then VPN is automatically connected.

**Comment by maxikuzmin** [comment]
@lekman I'd like to clarify, would you like to disable/enable AdGuard protection for specific networks or AdGuard VPN connection to location? 
For what?

**Comment by maxikuzmin** [comment]
@lekman any news?

**Comment by maxikuzmin** [comment]
@lekman for the moment, I'm closing this issue. If the problem appears again, please reopen the issue
