### ISSUE TITLE
Adguard Pro DNS Protection Fail to connect

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#2403]
Star from iOS18.1 now iOS18.2, adguard dns protection successfully add vpn but fail to connect to internet. When I check VPN in settings the connection just looping connecting and not connected on LTE and WiFi. Tried on iPhone SE 3 with Full-Tunnel, Split-Tunnel and switch dns servers.

**Comment by maxikuzmin** [comment]
@subarutendou could you elaborate on the detailed steps? Do you just turn on DNS protection and the internet connection is unavailable? I tried this on my device with IOS 18.2, but I can't reproduce it

**Comment by ghost** [comment]
Thank you. I think the issue can close now. It didn't work for a long time after ios 18.1. I didn't do anything special but somehow is working now, I just open adguard pro tap on dns protection, tap allow, enter password if is not working just delete the profile and try again.

**Comment by rflazaro** [comment]
I’m having the same issue.
Do I need to file a new ticket?
