### ISSUE TITLE
can't open the App Store app

### ISSUE THREAD

**Issue by pikesaury** [AdguardTeam/AdguardForiOS#2404]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.7

### Environment

- OS:18.2
- Device:iPhone SE3

### Advanced protection for Safari

- [ ] yes, I do

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### DNS filtering

- [ ] yes, I do

### DNS implementation

Native

### Tunnel mode

DNS protection disabled

### Low-level settings

Bootstrap server:
Fallback server:
Blocking mode, etc:

### Issue Details

Steps to reproduce:
1.Specify Adguard for iOS DNS
2.Normal use for a few hours（Go outside and switch between Wifi and LTE）
3.Open the App Store app
4.Get a warning and cannot open the App Store app

### Actual Behavior

Can open App Store app

### Screenshots

<details><summary>Screenshot 1</summary>
![IMG_6233](https://github.com/user-attachments/assets/f28e578c-e36a-4b0b-b778-563ddab8db7d)
</details>

**Comment by pikesaury** [comment]
Just in case, I'll attach the screenshot here as well.

![IMG_6233](https://github.com/user-attachments/assets/c5025b22-fa36-496c-91f8-90be7b54edfe)

**Comment by MineGene** [comment]
Seems to be the same as this: https://github.com/AdguardTeam/AdGuardDNS/issues/777

I also see the issue, but it doesn't look like there's any progress on it.

**Comment by maxikuzmin** [comment]
@MineGene you are right, it is worth continuing the discussion in the previously started Issue 
@pikesaury I'm closing this issue as a duplicate, please continue the discussion in the main[ issue](https://github.com/AdguardTeam/AdGuardDNS/issues/777)
