### ISSUE TITLE
Monte-carlo app ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForiOS#241]
1102356
лог днс:
https://onedrive.live.com/?authkey=%21AFbRauaktgb0ie4&id=5997EE259BC58E0F%21225714&cid=5997EE259BC58E0F
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20236846/001f0f34-a8cb-11e6-87af-56e36e57e18c.png)

**Comment by Alex-302** [comment]
Google Ads domain is blocked.
@gshumihin capture, please, requests of this app.

**Comment by zebrum** [comment]
app link?

closed for now.
