### ISSUE TITLE
Ozon app won't work with DNS filtering

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#242]
https://itunes.apple.com/ru/app/ozon.ru-internet-magazin/id407804998?mt=8

Проблема заключается в блокировке сервером этого адреса: t.appsflyer.com
Логов нет, не дают.

1137674

**Comment by dzamyshlyayeva** [comment]
1382035

**Comment by Alex-302** [comment]
Что именно не работает?

**Comment by jesusc31** [comment]
Приложение открывается и белый экран с надписью приложение загружается и ромашка крутится

**Comment by jesusc31** [comment]
Логи я кстати вроде отправил все по инструкции

**Comment by Alex-302** [comment]
Вижу вот такие заблокированные домены в указанное время:
```
settings.crashlytics.com
b.stats.paypal.com
h.online-metrix.net
ApP-measuRemENT.com

SSL.google-analytics.com
ads.flurry.com
data.flurry.com
e.crashlytics.com

t.appsflyer.com
stats.appsflyer.com
```
@gshumihin можешь проверить, блокировка какого домена ломает приложение? Можно сперва первые восемь добавить, чтоб удостовериться, что не они ломают.

**Comment by jesusc31** [comment]
На новой бете все так же не открывается Озон

**Comment by Alex-302** [comment]
Теперь могу сам проверять. К утру(фильтр DNS реже пересобирается), думаю, заработает:)

**Comment by Stillness-2** [comment]
@Alex-302 очень похоже что вот эти два:
t.appsflyer.com
stats.appsflyer.com

**Comment by Alex-302** [comment]
Так и есть.

**Comment by Alex-302** [comment]
@jesusc31 проверьте утром или часа через три.

**Comment by jesusc31** [comment]
Починили :) закрывайте
