### ISSUE TITLE
BBC sport app show 'no network connection' error

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#243]
https://itunes.apple.com/gb/app/bbc-sport/id377388936?mt=8

![image](https://cloud.githubusercontent.com/assets/15856304/20274347/eb178354-aa9c-11e6-9385-9d7d425be7d1.png)

logs: 1442463

**Comment by Alex-302** [comment]
Excluded
```
@@||sa.bbc.co.uk^
```
Please check again and reply

**Comment by Alex-302** [comment]
@evgeniy-ADG

**Comment by ameshkov** [comment]
@Alex-302 it appears the issue is still here:
https://github.com/AdguardTeam/AdguardDNS/issues/92

Please check it on your side.

**Comment by Alex-302** [comment]
@ameshkov not reproduced with AG Pro.

**Comment by zebrum** [comment]
obsolete
