### ISSUE TITLE
www.firstbaptist-portcrane.org - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#244]
http://family.block.dns.adguard.com/?domain=www.firstbaptist-portcrane.org

The screencast: https://www.youtube.com/watch?v=SVQmXdXYHFk&feature=youtu.be

Logs: 1448113

**Comment by Alex-302** [comment]
Not reproduced. Please check again.

**Comment by Alex-302** [comment]
@evgeniy-ADG

**Comment by zebrum** [comment]
fixed
