### ISSUE TITLE
Marktplaats app advertisement between search results

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#245]
1) download the marktplaats app
2) open the app and hit search
3) search for example: bmw x5
4) scroll the list
5) you will see adverts between search results

**Comment by worldsdream** [comment]
@Alex-302

**Comment by Alex-302** [comment]
there are few apps with this name. Please provide a direct link to the app and screenshots of ads

**Comment by worldsdream** [comment]
Marktplaats - Voor tweedehands en nieuwe spullen by Marktplaats BV

**Comment by worldsdream** [comment]
Alex any update?

Here is a screenshot of the advert: http://i.imgur.com/HRjIhNQ.jpg

**Comment by Alex-302** [comment]
We can't block it.
