### ISSUE TITLE
When HTTP PROXY is Auto in wifi setting, Adguard pro is unable to block ads in any apps. Bug PRO

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#247]
@ameshkov 

I am your Traditional Chinese translator.
I already wrote the issue by submitting the ticket.
**User ID**: 1425202

I think it's better to post the issue here and track if you solve it afterwards.

1. When I set "http proxy" as auto (space in URL) from the beginning and then connect to wifi, Adguard pro is unable to block ads in any apps.
<details><summary>Screenshot:</summary>

![Pic name](http://i.imgur.com/3KYMmta.png)
</details><br/>

Here, there is an ad.
<details><summary>Screenshot:</summary>

![Pic name](http://i.imgur.com/WUrUWwp.png)
</details><br/>

Set "http proxy" from auto to off.
Turn off wifi first and then reconnect to wifi.
<details><summary>Screenshot:</summary>

![Pic name](http://i.imgur.com/Ulu41ey.png)
</details><br/>

Adguard pro can block ads in apps. There is no ad.
<details><summary>Screenshot:</summary>

![Pic name](http://i.imgur.com/QDaHp4j.png)
</details><br/>

When http proxy is auto in wifi setting, Adguard pro is unable to block ads in any apps.
Is this a bug?
Can you solve the problem if setting http proxy?

2. Another thing. I surely didn't change my account's password on adguard.com.
But I am unable to login my account.
I know I can recover a new password.
I am just unable to understand unless my account was hacked.

**Comment by ameshkov** [comment]
Hi, thank you for reporting it!

Regarding the first question, do you use a .pac-based proxy server?

> I am just unable to understand unless my account was hacked.

Have you confirmed the account when you first registered it?

**Comment by lancelot-moon** [comment]
1. No, I almost don't use a proxy server. I changed the http proxy setting because I tried iCareFone Pro in the past.
https://appsto.re/tw/UZbJfb.i
It's an ad blocking app for only wifi via a proxy server.
I forgot to set http proxy to off.
And then I found that Adguard pro is unable to block ads in any app when enabling http proxy.

2. Yes, I also checked the account confirm email, which includes my original password.
But I was unable to login.
I surely never changed my password before.
For login successfully, I already requested to recover my password.
I use a new password now.

**Comment by ameshkov** [comment]
> Afterwards, I removed iCareFone Pro but forgot to set http proxy to off in my wifi setting.

Could it be that the proxy URL still points to the .pac configuration file (or maybe the file is somehow cached)?

> 2. I use a new password now.

Uh, that's bad, I may not be able to figure out what happened now:(

**Comment by lancelot-moon** [comment]
https://youtu.be/TrYjEzbZC6Y

For using iCareFone pro, I need to set the proxy url.
Please watch the video.
But I already deleted the proxy url since I removed iCareFone pro.
When setting http proxy to auto for testing adguard pro, I didn't fill in any proxy url, only space.

**Comment by ameshkov** [comment]
> But I already deleted the proxy url since I removed iCareFone pro.
> When setting http proxy to auto for testing Adguard pro, I didn't fill in any proxy url, only "space".
> And then Adguard pro is unable to block ads in any apps if setting http proxy to auto.

In my case setting an empty URL in that fields completely breaks net connection.
I suppose that in your case it just reuses the previous value you set there. 

> It established a fake VPN, not via a proxy server.

They install a VPN profile, which contains a list of rules controlling when iOS should try to use it. Each rule looks like "access domain example.org through the VPN". VPN points to a blackhole, so instead of accessing example.org, the rule actually blocks access to that domain. This is a very simple approach, but there was nothing better until network extensions were introduced.

**Comment by vozersky** [comment]
obsolete
