### ISSUE TITLE
Can't send emails with Outlook when VPN is enabled

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForiOS#248]
Test it please.

Original thread:
https://forum.adguard.com/index.php?threads/unable-to-send-messages-from-outlook.16255/

**Comment by vozersky** [comment]
can't reproduce so far
what email provider is used in outlook app? is it actual ms outlook or anything else? Also, it happens on wi-fi or cell?

**Comment by vozersky** [comment]
"Seems to be working now withthe latest update of outlook, will report back again if i have any issues though."
