### ISSUE TITLE
[Feature] Push notification after a selected time

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#249]
A lot of users install the adguard app, select the filters they need and then they dont even open it anymore. Even friends of me tell me that some sites are not opening or ads are showing up. They even remove the Adguard app. That is bad, because filters are getting updated every day and they are not understanding that they always need to keep it in background. 

I know that there is a task on github, to add information in the adguard app, telling them how it works. That they need to keep the app in background and so on. But a lot of the users kill the app and forget to open, they reboot the phone and so on.

Why dont we add push notifications? For example a week after not opening the adguard app, you see a push notification telling you: it's been a week, please open the app for new filter updates.

This is a nice way to protect the people, ofcourse people always can option out of the push notifications. It's an iOS setting.

What do you think?

**Comment by citrusui** [comment]
The default setting should be to only enable notifications on the app icon badge, which should be enough to let users know they need to update their AdGuard filters. Banner notifications would be an unnecessary distraction for me.

**Comment by worldsdream** [comment]
@citrusui It needs to be implented for all users and that is the default. Badges, notifications, sound. If you only want badges, you can go to settings>notifications>select your app and from there disable all and only keep badges.

**Comment by citrusui** [comment]
@worldsdream I don't like that idea. Too often mobile games send notifications to users about "collecting gems", "earning points", etc. Banner notifications would deter users, especially if the notifications appear during inconvenient times of the day.

**Comment by worldsdream** [comment]
Like i said: you can disable notitications. It's up to the user.

**Comment by ameshkov** [comment]
We'd like to try remote notifications instead of the background fetch, filters update should be more reliable then:
https://github.com/AdguardTeam/AdguardForiOS/issues/343

Please note, that it does not mean, that we will actually show notifications. It just means that we initiate filters update from the server side.

What for the visible notifications, I agree with @citrusui , it might be annoying, so unless they are really useful, notifications should be disabled by default. And I suppose, that notifying users of the filters update is not useful enough.

**Comment by ameshkov** [comment]
There was an interesting feature request in Android repo: https://github.com/AdguardTeam/AdguardForAndroid/issues/1069

What if we show some kind of an "app insights" notification when a user installs a new app?
We could inform him or her about the app behavior, what trackers or ad networks does it use, etc.

**Comment by vozersky** [comment]
let's close it, at least for now, since we decided to go for https://github.com/AdguardTeam/AdguardForiOS/issues/343
