### ISSUE TITLE
Wish app

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#250]
d.impactradius-event.com (impactradius.com tracking)

Wish - Shopping Made Fun by ContextLogic Inc.
https://appsto.re/us/tpkOF.i

**Comment by Alex-302** [comment]
we already have
```
||impactradius.com^
```

**Comment by jo2dan23** [comment]
d.impactradius-event.com Is the one that I suggested though Whats in brackets is what the domain is

**Comment by jo2dan23** [comment]
So ||d.impactradius-event.com^ is wht should be added. Sorry for the confusion. @Alex-302

**Comment by Alex-302** [comment]
added
