### ISSUE TITLE
Mytuner radio

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#251]
in.cuebiq.com
api.*.theappsales.com (marketing)

myTuner Radio - Live FM Stations & Internet Radios by Appgeneration Software
https://appsto.re/us/k5JbF.i

**Comment by Alex-302** [comment]
screenshot of ads, please

**Comment by jo2dan23** [comment]
cuebiq.com is tracking. the other is marketing. No ads appear tho.

**Comment by Alex-302** [comment]
in.cuebiq.com added
