### ISSUE TITLE
Ads go through when changing location

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#252]
I was using Adguard pro in France and ads were indeed blocked in apps. But then I went to Madagascar, and here, these same ads (in the sense that they're still targeted for the french market), are not blocked anymore, even on wi-fi.

Logs: 1450171

**Comment by evgeniy-ADG** [comment]
Any news?

**Comment by evgeniy-ADG** [comment]
@ameshkov @Stillness-2 any news?

**Comment by zebrum** [comment]
@Stillness-2 
@ameshkov 
please take a look

**Comment by zebrum** [comment]
@Stillness-2 
tested this app https://appsto.re/fr/FBL9s.i
no ads
but it seems user was talking about all his apps

**Comment by zebrum** [comment]
no answer from user
