### ISSUE TITLE
tieba bug

### ISSUE THREAD

**Issue by zhuochenming** [AdguardTeam/AdguardForiOS#253]
I use ChinaList+EasyList or EasyList China，when i visit web like http://tieba.baidu.com/f?kw=2012&fr=ala0&tpl=5，When you pull down more than that **可能感兴趣的吧** Finger on, or drag the following cell cause dislocation

**Comment by ameshkov** [comment]
@zhuochenming could you please take a screenshot of the issue?

**Comment by zhuochenming** [comment]
sorry,can not take the wrong screenshot, when I touch it ,it pop choose menu,so you need test it your self.

[https://tieba.baidu.com/f?kw=2012&fr=ala0&loc=rec&red_tag=0723144077&pn=0&](url)

use safari open it in iPhone , and scroll it to the below of 可能感兴趣的吧, just touch the bellow cell

**Comment by ameshkov** [comment]
@zhuochenming sorry, I still cannot understand (or reproduce).

Could you please record two videos: one with OK behaviour, the other with the mistake.
Here is how to do it:
http://www.apptamin.com/blog/capture-iphone-ipad-screen-video/

**Comment by zhuochenming** [comment]
[https://pan.baidu.com/s/1kVoE4zd](url) 

you can download it,just notice that when i touch the cell,it dismiss sometimes

**Comment by dzamyshlyayeva** [comment]
the same issue 
<details>
![image](https://cloud.githubusercontent.com/assets/23372054/20532831/0b939472-b0e4-11e6-9b3b-88a283957c8e.png)
![image](https://cloud.githubusercontent.com/assets/23372054/20532846/1feb59a0-b0e4-11e6-8b4a-a3ffe680928f.png)
</details>

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.0.78 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.4 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.56 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.79 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.69 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.69.48 Enabled=YES

Customer ID: 1451324

**Comment by ameshkov** [comment]
@dzamyshlyayeva should it be blocked right away? I see some "cards" being blocked on `http://tieba.baidu.com/f?kw=2012&fr=ala0&tpl=5`, but they all seem to be ads

**Comment by mickkkkk** [comment]
the same problem tieba.baidu.com. when I touch the post, the post sometimes disappear

**Comment by ameshkov** [comment]
@Alex-302 please take a look, I think we've got an incorrect blocking example.

Test page:
`http://tieba.baidu.com/f?kw=2012&fr=ala0&tpl=5`

Touching post may change `class` attribute and cause it to be hidden due to the hiding rule:
`.tl_shadow + * + li[class]:not([class="tl_shadow"])`

In fact we'd better to report it to ChinaList author.

**Comment by Alex-302** [comment]
Sadly, but I can't check baidu sites, they are never loading completely.

**Comment by ameshkov** [comment]
@Alex-302 just use chrome's data saver extension:
https://chrome.google.com/webstore/detail/data-saver/pfmgfdlgomnbgkofeojodiodmgpgmkac

**Comment by Alex-302** [comment]
Got it.
Reported:
https://forums.lanik.us/viewtopic.php?f=64&t=34302&p=108738#p108738
Waiting for their reaction:)

**Comment by zhuochenming** [comment]
thanks for your work
