### ISSUE TITLE
9to5mac 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardForiOS#254]
Description: pictures are blocked incorrectly 
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/20529406/ad4af3f2-b0d8-11e6-9d5f-1935f1d2b54d.png)

</details>
Application version: 1.1.2.24
Customer ID: 1021351

reproduced on my side

**Comment by Alex-302** [comment]
This site looks differently on my devices
http://ipic.su/img/img7/fs/kiss_415kb.1479912541.png
 I need a screenshot of correctly loaded page.

**Comment by Alex-302** [comment]
Removed few leftovers
```
9to5mac.com##.leaderboard
9to5mac.com##.adsense
9to5mac.com##div[id^="div-gpt-ad"]
```

**Comment by Alex-302** [comment]
@dzamyshlyayeva any news?

**Comment by dzamyshlyayeva** [comment]
@Alex-302 checked. still facing the same issue on my device

**Comment by Alex-302** [comment]
@dzamyshlyayeva please make two screenshots - with broken and correct.

**Comment by zebrum** [comment]
it is ok with latest Adguard version. 
closed
