### ISSUE TITLE
star wars heroes

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#259]
geoip.tnt-ea.com
data.ea.com (see tracking urls from fiddler log below)

https://pin-river.data.ea.com/pinEvents HTTP/1.1
https://river-mobile.data.ea.com/tracking/api/core/logEvent?localization=en-US&appLang=en&deviceLocale=en_US&deviceLanguage=en-US&appVer=0.7.181815&hwId=2916

Star Wars™: Galaxy of Heroes by Electronic Arts
https://appsto.re/us/w-A52.i

**Comment by Alex-302** [comment]
We should not block these domains, because authorization in some games can be blocked,
