### ISSUE TITLE
The app won't let iOS to go the sleep mode

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#260]
Программа не даёт телефону уйти в сон (время использования = времени ожидания). 
Проблема проявляется не сразу, но через несколько дней/недель эксплуатации. 
После сноса и переустановки все возвращается в норму.

1453182

**Comment by worldsdream** [comment]
I just checked and it does let it go in sleep mode. 

I tested it with latest beta on ios 9.3.3

**Comment by vozersky** [comment]
obsolete issue
