### ISSUE TITLE
Carfax

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#261]
beacon.carfax.com

CARFAX – Find Used Cars for Sale by CARFAX, Inc.
https://appsto.re/us/iSqKC.i

**Comment by ameshkov** [comment]
@jo2dan23 @Alex-302

I guess it's time to start reporting these issues to AdguardFilters repo:
https://github.com/AdguardTeam/AdguardFilters

I've added `iOS App` label there for this sort of cases.

**Comment by Alex-302** [comment]
added
```
||carfax.sc.omtrdc.net^
||beacon.carfax.com^
```
