### ISSUE TITLE
Walgreens

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#263]
config-live.swirl.com (marketing)
live.swirl.com (marketing)

Walgreens – Pharmacy, Photo, Coupons and Shopping by Walgreen Co.
https://appsto.re/us/smu_t.i

**Comment by Alex-302** [comment]
Added to Spyware filter
```
||walgreens.sc.omtrdc.net^
||mboxedge26.tt.omtrdc.net^
```
