### ISSUE TITLE
Intercept abp:subscribe and subscribe.adblockplus.org URLs

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#27]
https://issues.adblockplus.org/ticket/2208

Look at these filters:
https://adblockplus.org/subscriptions

You should first compare the subscription URL you've got with the subscription URLs of the filters you have. If it matches any you should enable this filter in AG.

If no match found we should offer user to import the rules to his "User Filter"

**Comment by slavaleleka** [comment]
still does not work for such url:
https://subscribe.adblockplus.org/?location=http://testcases.adguard.com/Filters/element-hiding-rules/test-element-hiding-rules.txt

tested on v4.3.3 (947)
