### ISSUE TITLE
Kmart

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#271]
replaycontroller.4seeresults.com (tracking)
tpat.tapjoy.net (this is the same as tapjoy.com)
api.bluecats.com (tracking)

Kmart – Download Now, Shop Online & Pick Up Today! by Sears
https://appsto.re/us/VXSbu.i

**Comment by Alex-302** [comment]
> tapjoy.net
> 4seeresults.com

added
