### ISSUE TITLE
Sears

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#272]
ws*.flightrecorder.co (this is clicktale.com which is tracking)
max.linkingmobile.com (ad network)

Sears – Download Now, Shop Online & Pick Up Today! by Sears
https://appsto.re/us/QJmns.i

**Comment by Alex-302** [comment]
Can't download.

**Comment by jo2dan23** [comment]
Do u want the fiddler log?

**Comment by Alex-302** [comment]
Yes
