### ISSUE TITLE
Meetme

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#274]
adsdk.vrvm.com

MeetMe - Chat and Meet New People by MeetMe, Inc.
https://appsto.re/us/qVInw.i

**Comment by Alex-302** [comment]
don't see this request

**Comment by jo2dan23** [comment]
@Alex-302 u have to have an account the ad appears when i go to my messages

**Comment by Alex-302** [comment]
Please make a figgler log
