### ISSUE TITLE
Apple Maps won’t fully function

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#277]
Apple Maps won’t fully function. You can get turn by turn nav, but it
doesn’t download the map graphic. Alternatively, Google Maps works fine.

![img_0667](https://cloud.githubusercontent.com/assets/15856304/20699404/defcce7a-b60f-11e6-950a-bbe0f347cc6b.png)

**Comment by Alex-302** [comment]
Don't understand. I opened the map, and see no issues - the map is loading correctly.
Could you reproduce it on your end?

**Comment by ameshkov** [comment]
@evgeniy-ADG open this sort of issues in AdguardFilters repo, there's an "iOS App" label for it.
