### ISSUE TITLE
Cannot play Podcasts using Overcast App for Podcasts

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#278]
That and the Overcast App for Podcasts, won’t download new Podcasts. You can listen to any that are already downloaded offline, but if you attempt to download a new Podcast, it won’t do it so long as Adguard DNS VPN is enabled.

https://itunes.apple.com/ua/app/overcast-podcast-player/id888422857?mt=8

**Comment by Alex-302** [comment]
excluded from DNS filter: podtrac.com
