### ISSUE TITLE
http://www.kaola.com/ - Incorrect blocking by DNS

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#280]
http://www.kaola.com/footer/freight.shtml

![image](https://cloud.githubusercontent.com/assets/15856304/20766063/93b85248-b73d-11e6-8075-021434586760.png)

Reproduced.

**Comment by Alex-302** [comment]
I can't access to mobile version. Ask for DNS log with time.

**Comment by zebrum** [comment]
with Adguard DNS it is ok now.
