### ISSUE TITLE
vk.com, steam - infinite page download

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#281]
Вот в таком положении загрузка страницы и зависает. Та же проблема в мобильном Steam. 
Проблема возникает не в фильтрах, а в вашем Adguard DNS который
работает через локальный VPN. Поэтому такая же проблема и в стороннем
браузере Chrome.

![image](https://cloud.githubusercontent.com/assets/15856304/20766438/2f5dd6e0-b73f-11e6-8331-998031177a8b.png)

Logs: 1455548

**Comment by Alex-302** [comment]
Не повторилось. Нужен точный адрес.

**Comment by evgeniy-ADG** [comment]
https://m.vk.com/artreex

**Comment by Alex-302** [comment]
У тебя повторяется?
Если выключить фильтры, что-то меняется?

**Comment by zebrum** [comment]
obsolete
