### ISSUE TITLE
DNS Family protection hides weather icons on m.yahoo.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#282]
Now on my home page (https://my.yahoo.com), the weather does not have the symbols for clouds, rain, sun, etc

Adguard Family Protection DNS servers, 176.103.130.132 and 176.103.130.134 When I used them, the weather symbols disappear. 

1080479

**Comment by Alex-302** [comment]
Not reproduced

**Comment by ameshkov** [comment]
@evgeniy-ADG can you reproduce it?

**Comment by zebrum** [comment]
can not reproduce.
and I think user was saying about safari on mac.
