### ISSUE TITLE
Flixster

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#284]
events.mobile.optimizely.com

Movies by Flixster, with Rotten Tomatoes by Flixster, Inc.
https://appsto.re/us/kFr8q.i

**Comment by ameshkov** [comment]
@jo2dan23 please report this kind of issues to AdguardFilters repo.

We've decided that AdguardForiOS repo should be devoted to the app development only.

**Comment by Alex-302** [comment]
Added to Spyware filter
```
||events.mobile.optimizely.com^
```
