### ISSUE TITLE
App crashes if you try to add an incompatible rule to User filter 

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForiOS#285]
For example, JS:

STR:
1. Add to Userfilter:  www.example.com#%#var fuckAdBlock = false

**Comment by Alex-302** [comment]
Another rule:
```
4pda.ru##body > div[id^="r"] > div[class^="r"] > div[class^="r"] > div[id^="r"] > div[class]:empty+div[class^="r"][class*=" r"]:not(:empty) > section[id]
```
If `:empty` is removed, I can add rule.

**Comment by vozersky** [comment]
> Another rule: 4pda.ru##body > div[id^="r"] > div[class^="r"] > div[class^="r"] > div[id^="r"] > div[class]:empty+div[class^="r"][class*=" r"]:not(:empty) > section[id]
If :empty is removed, I can add rule.

reproduced here

@Stillness-2 `:empty` is supposed to work in iOS, no?

**Comment by Alex-302** [comment]
@vozersky 
http://www.w3schools.com/cssref/sel_empty.asp

**Comment by ameshkov** [comment]
@Alex-302 btw `:empty` may also be unsupported in other AG versions. Are you sure it works ok in Windows/Mac/extension?

**Comment by Alex-302** [comment]
@ameshkov it works at least with AG for Windows and Chrome extension.
<details>

![image](http://imagizer.imageshack.com/img921/7453/ZuMyzA.png)
</details>

**Comment by Stillness-2** [comment]
commit c7d8a10. 
Now, If error occurs when converting of rule, app raises error modal dialog window.
