### ISSUE TITLE
Izit

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#286]
content.signal360.com (tracking company)
onesignal.com (this is automated advertising)

izit by Izit SPA
https://appsto.re/us/OQ4pN.i

**Comment by ameshkov** [comment]
Let's report these issues to https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by Alex-302** [comment]
Not sure about these domains.

**Comment by Alex-302** [comment]
Not sure about these domains.
