### ISSUE TITLE
m.legacy.com - the read more button is not available 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardForiOS#287]
http://m.legacy.com/obituaries/denverpost/obituary.aspx?n=lucy-dikeou&pid=182547156&referrer=0&preview=false - the Read More button doesn't work when AdGuard is enabled. 

<details>

![image](https://cloud.githubusercontent.com/assets/23372054/20855293/85f4a0da-b904-11e6-8759-e4b41c9ac522.png)

</details>

Application version: 1.1.2.24
Device: iPhone
OS: 10.2

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.97.34 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.14 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.42 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.26 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.23 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.51 Enabled=YES

Customer ID: 1182387

**Comment by ameshkov** [comment]
@dzamyshlyayeva please report this sort of issues to AdguardFilters repo.

**Comment by Alex-302** [comment]
Not reproduced with the same config.
Blocked social sharing buttons.

**Comment by worldsdream** [comment]
I can confirm that read more is not working when you click it. Reload page without adblocker. Read more is clickable.

**Comment by worldsdream** [comment]
@ameshkov why is this still not fixed? I dont use this website. But i guess others are using it. Read more is not clickable. 

@Alex-302 please look at this again. Thanks.

**Comment by Alex-302** [comment]
fixed
