### ISSUE TITLE
Onedio.com Social Buttons

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardForiOS#289]
https://onedio.com/haber/2016-nin-hayatimiza-kattigi-sezonluk-degil-omurluk-olan-16-harika-trend-742002

Can you block this buttons?

https://i.hizliresim.com/LZAXA1.jpg

**Comment by tagataho** [comment]
I use ENGLİSH, 
SPYWARE, 
SOCIAL MEDIA, 
Annoyances,
Mobile Ads,
SAFARI,
TURKISH,
EASYLIST FILTERS.

**Comment by ameshkov** [comment]
Weird, should have been blocked. Is it in Safari?

**Comment by vbagirov** [comment]
I will close this task, here's a new one: https://github.com/AdguardTeam/AdguardFilters/issues/3801
