### ISSUE TITLE
Rework user filter editor (use textarea)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#29]

**Comment by ameshkov** [comment]
After that issue is closed - read that thread and notice ardchoille50:
http://forums.macrumors.com/threads/the-ios-9-content-blocker-thread.1916783/page-103

**Comment by Alex-302** [comment]
>  ameshkov changed the title from Feature request: user filter and whitelist import to Rework user filter editor (use textarea) 

Is it impossible to import user filter(at least by url, which should be remembered by AdGuard)?

**Comment by ameshkov** [comment]
We have a separate feature request for the user filter import.
