### ISSUE TITLE
Hmobil.hurriyet.com.tr Social Buttons

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardForiOS#290]
http://mobil.hurriyet.com.tr/pkk-yandaslari-toplantiyi-karistirdi-40305327

http://mobil.hurriyet.com.tr/ogretmen-ogrencilere-yagli-urgan-ile-poz-verdirtti-40305352

http://mobil.hurriyet.com.tr/turkiye-icin-buyume-tahminini-dusurdu-40305564

http://mobil.hurriyet.com.tr/abdli-petrol-devi-schlumberger-25-bin-kisiyi-isten-cikardi-40058612

http://mobil.hurriyet.com.tr/volkan-demirelden-cuneyt-cakira-40305087

http://mobil.hurriyet.com.tr/istanbulda-iptal-olan-etkinlikler-hangileri-40305239

http://mobil.hurriyet.com.tr/galeri-40305369#p=1

Hi
There are some news in categories of this website.
I tried to block but i can block in news of one categories but not all.

Can you block that social buttons?

https://i.hizliresim.com/DB2rv1.jpg

**Comment by tagataho** [comment]
I use ENGLİSH, 
SPYWARE, 
SOCIAL MEDIA, 
Annoyances,
Mobile Ads,
SAFARI,
TURKISH,
EASYLIST FILTERS.

**Comment by vbagirov** [comment]
@tagataho I will transfer this one and some other tasks created by you to the other repository:
https://github.com/AdguardTeam/AdguardFilters/issues

Please, if you have similar reports in future, submit them to /AdguardFilters/issues. Use [iOS]/[Windows]/etc. prefix for every new issue you create.
There is even a template for new submissions, try to follow it. It is not always necessary to fill in every single line there, but include any information that you think will be useful in that case (especially list of enabled filters).

**Comment by vbagirov** [comment]
I will close this one, here's the new task: https://github.com/AdguardTeam/AdguardFilters/issues/3800
