### ISSUE TITLE
m.ensonhaber.com Social Buttons and unneeded bar

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardForiOS#291]
http://m.ensonhaber.com/whatsappta-kufur-eden-kadina-3-bin-100-tl-para-cezasi-2016-12-13.html

Hi
There are two bars which unneeded and useless in this site. Can you block and unappear please?

https://i.hizliresim.com/1Vv38A.jpg

**Comment by vbagirov** [comment]
I will close this task, here's a new one: https://github.com/AdguardTeam/AdguardFilters/issues/3802
