### ISSUE TITLE
shiftdelete.net Empty Bar/Buttons

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardForiOS#292]
http://shiftdelete.net/ios-10-2-yayinlandi-77695

Hi
Please block that.
https://i.hizliresim.com/1VvoDG.jpg

**Comment by tagataho** [comment]
I use ENGLİSH, 
SPYWARE, 
SOCIAL MEDIA, 
Annoyances,
Mobile Ads,
SAFARI,
TURKISH,
EASYLIST FILTERS.

**Comment by vbagirov** [comment]
This task is closed, here's a new one: https://github.com/AdguardTeam/AdguardFilters/issues/3803
