### ISSUE TITLE
m.sporx.com Social Buttons

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardForiOS#293]
http://m.sporx.com/futbol/buzz/mehmet-demirkoldan-antalyaspor-fenerbahce-yorumuSXGLQ24600SXQ

http://m.sporx.com/riekerink-33-yilda-yasadigim-en-iyi-sey-SXHBQ590381SXQ

Hi
In this pages, there is unnecessary and useless Social buttons/bar. Please block.

https://i.hizliresim.com/Er80P8.jpg

**Comment by zebrum** [comment]
@tagataho quite a lot people may use this home button.
though, you can block it manually.
