### ISSUE TITLE
m.haberturk.com All things are blocked

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardForiOS#294]
http://m.haberturk.com/

Hi
I can not use this site. Because news scroll and same things are blocked.
You check that.
Please fix it.

I use ENGLİSH, 
SPYWARE, 
SOCIAL MEDIA, 
Annoyances,
Mobile Ads,
SAFARI,
TURKISH,
EASYLIST FILTERS.

**Comment by Alex-302** [comment]
@tagataho please move you issues to AdguardTeam/AdguardFilters

**Comment by tagataho** [comment]
http://i.hizliresim.com/m4L2a0.jpg

Everthing is blocked in haberturk.com. You can see that.

**Comment by tagataho** [comment]
@Alex-302 i wrote AdguardTeam/AdguardFilters

**Comment by Alex-302** [comment]
ok
