### ISSUE TITLE
Not Open Videos in many Turkish Mobile Websites 

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardForiOS#295]
http://m.sondakika.com/haber/haber-onundei-haber-metnini-okuyamayan-nevsin-mengu-9059901/

http://m.haberler.com/onundeki-haber-metnini-okuyamayan-nevsin-mengu-9059901-videosu/

http://m.medyafaresi.com/video/nevsin-mengu-canli-yayinda-sinirlendi/799657

http://m.a24.com.tr/video/nevsin-mengu39nun-zor-anlari-16399.html?v=0

http://m.internethaber.com/buraya-unlu-olmaya-geldim-deyince-video-galerisi-1738746.htm

Hi
There are many website which can not open videos; please fix this problem.

**Comment by tagataho** [comment]
I use ENGLİSH,
SPYWARE,
SOCIAL MEDIA,
Annoyances,
Mobile Ads,
SAFARI,
TURKISH,
EASYLIST FILTERS.

**Comment by Alex-302** [comment]
1,***2***,4 - works
5 - not working without Adguard
2 - try these rules
```
m.haberler.com###adContainer
m.haberler.com##.playButton
```

**Comment by tagataho** [comment]
@Alex-302 where do i add this rules? White list or user block list?

**Comment by tagataho** [comment]
@Alex-302 i tried both of them (seperately) it is not working.

**Comment by tagataho** [comment]
@alex-302 additinally; you wrote opossite but 1-2-4 not work.
 I tried on safari in iphone

**Comment by vbagirov** [comment]
I am closing this task as I created a new one in another repository.
