### ISSUE TITLE
BFM Paris by NextRadioTV - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#296]
VPN DNS does not work on BFMParis application: BFM Paris by NextRadioTV
https://appsto.re/us/r2Bxfb.i

<details>

![image1](https://cloud.githubusercontent.com/assets/15856304/21190580/f49195f0-c22a-11e6-9aa9-1e3c1fc4eef2.PNG)

![image2](https://cloud.githubusercontent.com/assets/15856304/21190588/fc5133a4-c22a-11e6-91a9-58b6c47de67d.PNG)

</details>

State and logs: 1021351

**Comment by vbagirov** [comment]
Closing this one, new task is https://github.com/AdguardTeam/AdguardFilters/issues/3807
