### ISSUE TITLE
Create "Adguard for iOS" section on "Acknowledgments" page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#3]
**Third-party components:**
StaticDataTableViewController - https://github.com/peterpaulis/StaticDataTableViewController
GZIP - https://github.com/nicklockwood/GZIP

Ask @Stillness-2 for more info.

**Comment by Stillness-2** [comment]
Я использовал компонент этот
Вся инфа по ссылке вроде

**Comment by vbagirov** [comment]
http://adguard.com/en/acknowledgements.html#ios-acknowledgments
http://adguard.com/ru/acknowledgements.html#ios-acknowledgments
