### ISSUE TITLE
 Mediametrics не работает с Adblock pro

### ISSUE THREAD

**Issue by Flammable777** [AdguardTeam/AdguardForiOS#301]
iPhone 7, последняя прошивка, без джейла, после установки Adguard Pro и включении Adguard DNS, приложение Mediametrics не запускается (вылетает на старте). Хороший агрегатор новостей, но при этом рассадник рекламы... Что посоветуете?
Ссылка на приложение appstore:
https://appsto.re/ru/HhSOY.i

**Comment by Alex-302** [comment]
Он заблокирован и как сборщик аналитики.
Скоро выйдет новая версия, и можно будет исключать заблокированное по DNS.
Конкретно для вашего случая правило будет таким(в текущей версии не работает):
```
@@||mediametrics.ru^
```

**Comment by Stillness-2** [comment]
@Alex-302 Уже вышла та версия где это работает

**Comment by Alex-302** [comment]
Отлично:)

**Comment by Flammable777** [comment]
У меня обновления на IOS нет. Я что-то упустил? И можно подробнее, где прописать правило. Я не силен в этом)

**Comment by Stillness-2** [comment]
@Flammable777 версия какая? Должна быть 1.1.3. Посмотреть можно в пункте "О программе"

**Comment by Flammable777** [comment]
Все верно. Вносится именно 1.1.3. Добавил фильтр в белый список. Не помогло (

**Comment by Stillness-2** [comment]
@Flammable777 Больше инфы дайте пожалуйста. Дайте скриншот места куда добавили.

**Comment by Flammable777** [comment]
![enlight1](https://cloud.githubusercontent.com/assets/24727508/21469779/1e5f3432-ca78-11e6-9913-d83d6e5ec26b.jpg)
![enlight1](https://cloud.githubusercontent.com/assets/24727508/21469780/1e5fce74-ca78-11e6-837c-fd8661fdccb1.jpg)
![enlight1](https://cloud.githubusercontent.com/assets/24727508/21469781/1e74d8c8-ca78-11e6-81a1-b7fb2d30d30d.jpg)
![enlight1](https://cloud.githubusercontent.com/assets/24727508/21469782/1e874c92-ca78-11e6-9611-30bb2fb8b540.jpg)
![enlight1](https://cloud.githubusercontent.com/assets/24727508/21469783/1e8890fc-ca78-11e6-86a6-22d5fef44809.jpg)

**Comment by Stillness-2** [comment]
@Flammable777 Я Вас понял. Смотрите... В поле для ввода нового домена (там где "Отключить фильтрацию для этого сайта") надо ввести просто `mediametrics.ru`.

**Comment by Flammable777** [comment]
Роман, спасибо. Все работает!
