### ISSUE TITLE
Adguard creates 'undefined' rules

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#305]
When adding a rule to the user filter, it shows up as UNDEFINED when you save it. Rules don't work. We reinstalled the app but to no avail, unfortunately. 

![image](https://cloud.githubusercontent.com/assets/15856304/21462990/974ca324-c96b-11e6-8830-f2a8b2e17594.png)

<details>
Application version: 1.1.3.31
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: EAFF98DD-CD45-456A-A3CE-99CD3EEA93C3

Locale: ru
Region: ru

Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.76 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.74 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.88 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.23 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.68 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.91 Enabled=YES

</details>

1473533
1206882
1473497

**Comment by evgeniy-ADG** [comment]
> It happened after the update of iOS10.2 final on my iPhone 6.

1449950

**Comment by ruijinyin** [comment]
it appeared for many times

**Comment by ameshkov** [comment]
@Stillness-2 this is a major issue. Let's fix it and push an update right away.

**Comment by ameshkov** [comment]
@Stillness-2 more than this, ads blocking via safari extension is also broken:
https://forum.adguard.com/index.php?threads/cant-block-elements.18087/

**Comment by vozersky** [comment]
Confirmed in both free and PRO versions (stable)

**Comment by ruijinyin** [comment]
Dear sir, 
The PRO is being used, however, there is no difference between free and PRO version. 

2016-12-26 

s2007007 



发件人：vozersky <notifications@github.com>
发送时间：2016-12-26 18:39
主题：Re: [AdguardTeam/AdguardForiOS] Adguard creates 'undefined' rules (#305)
收件人："AdguardTeam/AdguardForiOS"<AdguardForiOS@noreply.github.com>
抄送："ruijinyin"<s2007007@126.com>,"Comment"<comment@noreply.github.com>

Confirmed in both free and PRO versions (stable)

**Comment by vozersky** [comment]
@ruijinyin  will be fixed soon, wait for the next update, please
