### ISSUE TITLE
Please add filters ABP 1102vn

### ISSUE THREAD

**Issue by staryob** [AdguardTeam/AdguardForiOS#307]
Please add filters ABP 1102vn
Link: http://abp.1102vn.com
Links filters: http://abp.1102vn.com/abp_1102vn_firefox.php

Or add setting add filter on app

Thanks Ad

**Comment by ameshkov** [comment]
@Alex-302 please check it

**Comment by Alex-302** [comment]
This filter contains only 69 rules.

**Comment by staryob** [comment]
i want creat filter for vietnamese. 
IOS filter for vietnam block not 100%. ==> i want creat filter.

It will update daily. i user adguard on ios insert filter difficult and many time.

If you can help me. insert it on filter ios. i very fun.

**Comment by rurumi66** [comment]
1102vn

**Comment by ameshkov** [comment]
@javabean yep, indeed.

@staryob once #50 is done, you'll be able to add a custom filter subscription.

Maybe you know any good existing Vietnamese filter?

> i user adguard on ios insert filter difficult and many time.

You can use any other AG extension or program to debug your filter. I mean any popular browser allows you to change user agent.

**Comment by vozersky** [comment]
#518
