### ISSUE TITLE
wp.pl mobile

### ISSUE THREAD

**Issue by xxcriticxx** [AdguardTeam/AdguardForiOS#308]
still getting ads on wp.pl mobile (`http://www.wp.pl/mini.html`) with polish list turn on. i think some parts don't work correctly with adguard. checking same page on the computer with same list blocks all of the ads. 

sample of ads:

http://imgur.com/a/cWQX4

**Comment by Alex-302** [comment]
please check these rules:
```
wp.pl##.header+div > div[class] > div[style*="display: block;"]
wp.pl###section_topnews > div:not([class])  > div[style] > div > a > img[style]
```

**Comment by xxcriticxx** [comment]
@Alex-302 i added your rules i have less ads on the main page but i still got some left over boxes 

http://imgur.com/a/P4GpB

http://imgur.com/a/VQIcA

**Comment by xxcriticxx** [comment]
paging @Alex-302 any update on this?

**Comment by ameshkov** [comment]
@Alex-302 ping.

@xxcriticxx next time please report this sort of issues to https://github.com/AdguardTeam/AdguardFilters repo.

**Comment by Alex-302** [comment]
@xxcriticxx 
please answer here
https://github.com/AdguardTeam/AdguardFilters/issues/4100
