### ISSUE TITLE
Adblocker Blocked on iPhone Safari websites

### ISSUE THREAD

**Issue by sagarb26** [AdguardTeam/AdguardForiOS#311]
I am getting error message on website links below to Disable adblocker:

http://www.ndtv.com/world-news/live-barack-obamas-last-presidential-speech-1647473?pfrom=home-lateststories

m.beautypageants.in 

![img_4714](https://cloud.githubusercontent.com/assets/25046705/21834444/05be157a-d76a-11e6-8c32-d833904c5aef.PNG)
![img_4715](https://cloud.githubusercontent.com/assets/25046705/21834445/05be9400-d76a-11e6-8667-c8810b36b9db.PNG)

**Comment by Alex-302** [comment]
iOS version has an issue with $generichide/$genericblock rules, they are works partially.
For example, tis rule should to unblock and unhide blocked elements
```
@@||m.beautypageants.in^$genericblock,generichide
```
but ad block is still detected. The same with NDTV...

**Comment by worldsdream** [comment]
It's working fine here. Alex can you confirm this is fixed on the latest ios release? If yes, you can close this thread.

**Comment by ameshkov** [comment]
Yeah, should be ok now.
