### ISSUE TITLE
Generic element hiding rules in custom filter are ignored when enabled optimized filters option

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#313]
For example:
https://9to5mac.com/
share buttons are not hidden
<details>

![image](http://i90.fastpic.ru/big/2017/0114/6f/628d780e2aaaf07e887c08df9e632a6f.jpg)
</details>
This rule is not working(ignored?):

```
##.sharedaddy
```
this works
```
9to5mac.com##.sharedaddy
````
Btw `##.sharedaddy` is exists in social filter and should hide all these social buttons, but it is not working even with only social filter enabled. It works only with full filters.
Not reproduced with Safari on Mac with browser extension.

**Comment by ameshkov** [comment]
@Alex-302 this feature disables ALL generic rules:
> optimized filters option

Anyway, the feature is experimental, we will change it eventually.

**Comment by Alex-302** [comment]
Ok, got it...
