### ISSUE TITLE
Add Iran filter 

### ISSUE THREAD

**Issue by natalysk** [AdguardTeam/AdguardForiOS#314]
User 1447133, has created Iran filter.
He is asking to add his filter to Adguard.
Here is his repository https://github.com/farrokhi/adblock-iran
and his own filter list https://raw.githubusercontent.com/farrokhi/adblock-iran/master/filter.txt

**Comment by ameshkov** [comment]
@farrokhi thank you!

Moved this issue to the appropriate repo:
https://github.com/AdguardTeam/AdguardFilters/issues/4099
