### ISSUE TITLE
Having issue blocking ads on a site

### ISSUE THREAD

**Issue by antnythr** [AdguardTeam/AdguardForiOS#324]
I just purchased Adguard Pro and I'm having some trouble blocking ads on one site and I was hoping for some advice on how to block them.

The site is neowin.net

Looking at the page source, the DIVs I think I want to block are:
class="header-banner  header-banner-ads"
class="ad"

Contained within the "ad" class are other div id's that I've tried to block as well that were unsuccessful:
id="mobile_after_3rd_article"
id="mobile_after_10th_article"

The entries I've created don't seem to work:
`neowin.net##.header-banner.header-banner-ads`
`neowin.net##.ad`

I tried an alternate version because this is the uBlock entry on my laptop
`##.header-banner-ads.header-banner`

Any ideas on how to block these?

**Comment by Alex-302** [comment]
Hi
Please write to https://github.com/AdguardTeam/AdguardForiOS about ads or incorrect blocking.
And, please, don't ignore issue template:)

**Comment by antnythr** [comment]
I don't quite get what you mean. The link you posted brings me to this github page and there's no email address or any other form of contact listed other than the issues section that I posted in.

**Comment by Alex-302** [comment]
oh, sorry:)
I mean this
https://github.com/AdguardTeam/AdguardFilters
Please reopen issue in that repository.

**Comment by ameshkov** [comment]
I wonder, have you enabled Safari content blocker? All three rules looks just okay.
