### ISSUE TITLE
[Feature request] Create a better (than DNS requests log) visual representation for 'what's blocked'

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForiOS#326]
The examples of what it can look like can be found here:
https://forum.adguard.com/index.php?threads/18382/#post-124894

**Comment by Bohdan-SUP** [comment]
User 1505466 asks:
"Could you implement in the app a visual graph with all the blocked ads and sites so we could have a visual presentation who is spying on us? :)"

**Comment by ameshkov** [comment]
Yup, we'll take this into account when we start implementing the app redesign.
