### ISSUE TITLE
www.hurriyet.com.tr Videos not open

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardForiOS#328]
Hi
http://www.hurriyet.com.tr/video/sertab-erener-vapurda-sarki-soyledi-40357417

In this website; all video do not open, you can try then will see not open.

I use filter of ENGLISH, SPYWARE, SOCIAL MEDIA, Annoyances, Mobile Ads, SAFARI, TURKISH

**Comment by tagataho** [comment]
http://mobil.hurriyet.com.tr/kesim-hatali-5-lirayi-dort-yildir-sakliyor-40356843

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/3800
