### ISSUE TITLE
http://m.sondakika.com/ Not load all news 

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardForiOS#329]
Hi
I think something  is wrong blocked in http://m.sondakika.com.

Website: http://m.sondakika.com/

Screenshot: http://i.hizliresim.com/d8YDEp.jpg

Because when i use this website; i always  see that. Can you check all blocking on this website.

My filters: english, spyware, social media, turkish, mobile, safari filters

**Comment by vozersky** [comment]
wrong repo, moved to filters for you
https://github.com/AdguardTeam/AdguardFilters/issues/4342
