### ISSUE TITLE
Vpn problems

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#333]
vpn disconnects and reconnects non stop on latest beta. What logs should i grab or am i not the only one with this problem? I am on latest ios dev beta

**Comment by ameshkov** [comment]
So that's not a coincidence after all, @Alex-302 has the same issues.

**Comment by ameshkov** [comment]
In this particular case we'd like to get iOS system logs:
https://success.trendmicro.com/solution/1106560-collecting-system-logs-on-ios-8-x-devices

**Comment by Stillness-2** [comment]
@jo2dan23 Please, send bug report from app. Also let know to us approximate time when problem occurred.

**Comment by jo2dan23** [comment]
@Stillness-2 what files do you need from Adguard app? I can post them here.

**Comment by Stillness-2** [comment]
@jo2dan23 `com.adguard.AdguardPro.tunnel.gz`, `com.adguard.AdguardPro.gz`

**Comment by jo2dan23** [comment]
https://www.dropbox.com/s/173ptfwbp54x0ug/com.adguard.AdguardPro.gz?dl=0

https://www.dropbox.com/s/0zhop6j6swbsdna/com.adguard.AdguardPro.tunnel.gz?dl=0

**Comment by jo2dan23** [comment]
Unfortunately i couldnt get the real time log sorry @ameshkov

**Comment by jo2dan23** [comment]
On newest beta. Disconnected once or twice so far. Am i the only one?

https://www.dropbox.com/s/9b7btnr6zjndty2/com.adguard.AdguardPro.tunnel.gz?dl=0
https://www.dropbox.com/s/1x8eiisya3oi0md/com.adguard.AdguardPro.gz?dl=0

**Comment by Stillness-2** [comment]
@jo2dan23 
Can you please describe what's going on? 
For example, specify the time when the problem occurred (according to logs which you'd sent before).
If you delete and reinstall the app, does the problem continue to occur?
How does VPN icon behave at the moment of the problem?

**Comment by jo2dan23** [comment]
It just happened again. I was just browsing Facebook and it disconnected then reconnected i hope this helps.

https://www.dropbox.com/s/nu56hwjlzr9oi30/com.adguard.AdguardPro1.gz?dl=0

https://www.dropbox.com/s/p72qmkudxe9rtdz/com.adguard.AdguardPro1.tunnel.gz?dl=0

**Comment by ameshkov** [comment]
What time it was? Could it be that you've reconnected to another network connection that time?

**Comment by jo2dan23** [comment]
It was at 11:12pm and no i was on wifi the whole time

**Comment by jo2dan23** [comment]
It just happened again the time was around 1:49 pm to 1:50 pm for log purposes. What happens is it completely disconnects me from wifi and the vpn then reconnects 

https://www.dropbox.com/s/06tlud8cmjjmtq5/com.adguard.AdguardPro2.gz?dl=0

https://www.dropbox.com/s/ah88cnvkdq4oed7/com.adguard.AdguardPro2.tunnel.gz?dl=0

**Comment by jo2dan23** [comment]
my log  is filled with these

2017/03/03 00:22:15:838  (ID:62213) (APTUdpProxySession) Session state is "Failed" on: 208.67.222.222 port: 53.

@ameshkov

**Comment by ameshkov** [comment]
@jo2dan23 waiting for @Stillness-2 . It seems that iOS kills the VPN process due to memory issues.

**Comment by jo2dan23** [comment]
@ameshkov so can that be fixed or no?

**Comment by ameshkov** [comment]
It should be fixed, indeed.

**Comment by ameshkov** [comment]
@Stillness-2 resolved? :)

**Comment by Stillness-2** [comment]
@ameshkov I think, Yes. More or less Yes. :)
