### ISSUE TITLE
Spark app compatibility issue

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForiOS#334]
When you run Spark mail app: 
https://itunes.apple.com/us/app/spark-love-your-email-again/id997102246?mt=8

An error message appears:
>Your VPN quality of service is too low to be used with Spark. Please connect to another VPN or use plain connection.

Happens after the update where System-wide filtering was introduced.

**Comment by ameshkov** [comment]
I wonder how do they check it?

**Comment by vbagirov** [comment]
Here's a screenshot btw:
http://i.imgur.com/jm7fZbl.png

**Comment by ameshkov** [comment]
We need logs.
I suppose, we block some domain used by spark to check the connectivity.

**Comment by thoooooooom** [comment]
May I know how to fix it?

**Comment by ameshkov** [comment]
@thoooooooom to troubleshoot we first need to take a look at the log:
https://kb.adguard.com/en/ios/solving-problems/dns-requests-log
