### ISSUE TITLE
Vpn connect delay

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#335]
There is a 1 minute and 30 second to 2 minte delay for the vpn to reconnect when adding domains to the system wide ad blocking filter lists. Black and whitelist one. Can anyone else reproduce. Im assuming it should take the same amount of time as when turning the vpn on and off from the status section on main screen but it isnt.

**Comment by zebrum** [comment]
@jo2dan23 
don't wait. just go to browser after adding domain and vpn icon will appear.

**Comment by Itsnothectic** [comment]
Yes the app does not enable the VPN properly, hence you should never trust it and always check the VPN menu under general.

There is also a delay on system startup causing leaks, work around is to switch to aeroplane mode before shutting down or at least disable mobile data.
