### ISSUE TITLE
Unconfirmed: iOS Apple/Prism hosts incorrectly reported as blocked

### ISSUE THREAD

**Issue by Itsnothectic** [AdguardTeam/AdguardForiOS#337]
These hosts bypass the VPN, you can test this by running DNSCrypt or a firewall on a Wifi hotspot while using a VPN or AdGuard on your phone.

iphone-id.apple.com
www.icloud.com
xp.apple.com (dunno what this is but seems sus)

I can not confirm because such hotspot is no longer available to me now but the Adguard logs say blocked without showing a second attempt by the system.

Steps to reproduce:

Disable mobile data and put your phone in aeroplane mode before turning off and back on, wait a minute after starting up before disabling aeroplane mode, connect to a wifi AP that can log either DNS requests or connections (not windows resource monitor).

**Comment by ameshkov** [comment]
As I recall, AG marks as "blocked" any host which is resolved to `127.0.0.1`. Could it be that specific hotspot issue?

**Comment by Itsnothectic** [comment]
It had to be the phone and not the hotspot because it was through a VPN.

Im actually not sure if apple-id bypasses the VPN.

The only thing I know for sure is that icloud does bypass at least the personal VPN in iOS 9.
