### ISSUE TITLE
[Feature request] Web Fonts

### ISSUE THREAD

**Issue by inazarab** [AdguardTeam/AdguardForiOS#338]
It'd be great if the Adguard iOS app, and other adguard apps like the mac version, had an option to block Web fonts.  Other content blockers such as iBlockify and Firefox Focus have that option. I'd love it of Adguard could add this feature.

**Comment by ameshkov** [comment]
@Stillness-2 I wonder, does AG support `$font` modifier?

If so we can simply add a rule like that:
`http*$third-party,font`

**Comment by jo2dan23** [comment]
this would be an awesome feature

**Comment by ameshkov** [comment]
Just try it:
`http*$third-party,font`

I've just taken a look at the code, and it should work.

**Comment by jo2dan23** [comment]
Cant tell if its being blocked or not. Doesnt show in log.

**Comment by ameshkov** [comment]
That's for Content Blocker only, so the only way you can check it is through Safari log.

**Comment by jo2dan23** [comment]
Oh i cant check then. The only log i can see is dns one on latest beta

**Comment by ameshkov** [comment]
And here goes the content blockers problem: Safari does not show us what was actually blocked.

It is printed to the browser console and that's the only place where you can see it.
So, to check what's blocked you should connect your device to a Mac, open desktop Safari and open mobile's browser console through `Develop` menu.

**Comment by inazarab** [comment]
I'm confused. There is a way to enable that now?

**Comment by ameshkov** [comment]
@inazarab of course, open the app, go to `User filter` and add this rule:
`http*$third-party,font`

That'd be enough.

**Comment by inazarab** [comment]
is there a way to do that on the mac app?

**Comment by ameshkov** [comment]
> is there a way to do that on the mac app?

The very same rule should work: preferences -> filters -> user filter, add that rule there.

**Comment by jo2dan23** [comment]
I think we should add a toggle to the safari content blocking section for font blocking. Do we know for sure also that it works? I have no mac so i cant diagnose
