### ISSUE TITLE
whitelisting not working

### ISSUE THREAD

**Issue by jitbit** [AdguardTeam/AdguardForiOS#340]
iOS 10.2.1, Atguard latest version

After adding a website - "Filters cannot be loaded into Safari"

**Comment by zebrum** [comment]
@jitbit 
does it happen with all websites?
did you try to add to whitelist from safari action bar?

**Comment by jitbit** [comment]
Yes, all websites. I tried doing this from inside the AtGuard app - "whitelist"

**Comment by zebrum** [comment]
hello @jitbit !
Is adding to whitelist working as expected now?
