### ISSUE TITLE
VPN failure on low battery shutdown

### ISSUE THREAD

**Issue by Itsnothectic** [AdguardTeam/AdguardForiOS#341]
I havent tried to repeat this yet. If the phone shuts down due to low battery and is then powered up automatically from being charged sufficiently. It will connect to the internet, it will report the "VPN" as connected but hosts will not be blocked or logged until the "VPN" is disconnected and reconnected in settings.

A bug with iOS 10 I am guessing?

**Comment by Itsnothectic** [comment]
Its actually happening whenever the phone is started up while being charged.

**Comment by zebrum** [comment]
@Itsnothectic 
are you sure the issue depends on charging? 
it seems fine on my side. at least when i turn on the phone while being charged.

**Comment by Itsnothectic** [comment]
I tried again and I listed the steps to reproduce incorrectly.


1) power down the phone (really just deep sleep)

2) turn on and wait for pin/password login but do not enter it.

3) wait for VPN symbol too.

4) plug in the charger, you should hear a chime sound.

5) unlock the phone and Adguard will be on but bypassed.

**Comment by Itsnothectic** [comment]
Im going to test this issue soon. Apparently this is intended behaviour of iOS so it can still do an iCloud backup in the presence of malware or a lost device password.
