### ISSUE TITLE
http://www.mangatail.com/  

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardForiOS#342]
When i enter this website; i see this warning" please disable adblock"

http://www.mangatail.com

Can you fix it?

I use filters of ENGLİSH, SPYWARE, SOCIAL MEDIA, Annoyances, Mobile Ads, SAFARI, TURKISH.

**Comment by Alex-302** [comment]
Wrong repository. Please write here
https://github.com/AdguardTeam/AdguardFilters/issues/new
