### ISSUE TITLE
m.shuhuangge.org - missed pop-ups

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardForiOS#344]
http://m.shuhuangge.org/ - a pop-up appears with Adguard enabled.
Filters: User, English, Russian, Annoyances, Social media, Spyware, Experimental, Safari.

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24067231/710c02c8-0b82-11e7-8825-510c6499097f.png)

</details>

**Comment by Alex-302** [comment]
Wrong repository. Write to AdguardFilters.
Added to English filter
```
||zymro.com^
```
