### ISSUE TITLE
stealjobs.com - incorrect blocking

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardForiOS#345]
http://stealjobs.com/standard-chartered-bank-%E6%B8%A3%E6%89%93%E9%8A%80%E8%A1%8C-cdd-analysis-%E6%94%B6%E5%85%A5/

Can't reach website while Adguard is enabled. 
Filters: English, Russian, Experimental, User, Annoyances, Spyware, Social media, Safari

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24067492/36699596-0b86-11e7-8e60-13ee28c1e4a1.png)

</details>

**Comment by Alex-302** [comment]
It works on my side. Which filter breaks the site?

**Comment by worldsdream** [comment]
I can confirm. White page on ios. Disabling adguard, page loads. 

English dutch annoyance mobile and safari filter.

**Comment by Alex-302** [comment]
Fixed
