### ISSUE TITLE
adding domains with * in them cant be blocked on latest beta, only work when using the adguard servers

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#347]
for example if i have lt*.tritondigital.com iny my dns blacklist, it only works when using either adguard default or adguard family protection in the dns settings. is this is a bug or are * filters only able to be blocked when using adguard as my dns?

**Comment by jo2dan23** [comment]
@ameshkov

**Comment by jo2dan23** [comment]
@Alex-302 can you reproduce?

**Comment by ameshkov** [comment]
Here is why:
https://github.com/AdguardTeama/AdguardForiOS/issues/348

Thanks for reporting it!

**Comment by Alex-302** [comment]
There is a typo in the issue URL
AdguardTeamA -> `AdguardTeam`

**Comment by ameshkov** [comment]
Fixed)
