### ISSUE TITLE
Improve Adguard filtering rules syntax in the System-wide ad blocker

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#348]
There are four special characters:
`||` -- http://*
`|` -- match start/end
`^` -- separator
`*` -- wildcard

**Comment by ameshkov** [comment]
Here is a rule example, that does not work:
`||anet*.tradedoubler.com^`

**Comment by jo2dan23** [comment]
Does this mean the specific rules will be able to used now? Like for example ||play.googleapis.com/log

**Comment by ameshkov** [comment]
Nope, not yet, but at least it will support wildcards properly.
