### ISSUE TITLE
9to5mac.com - Ads 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardForiOS#351]
https://9to5mac.com/2017/03/25/red-iphone-7-black-front-video/ - Missed ads 

<details>

"User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.6.16 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.23 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.46 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.90 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.69 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.14 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.65 Enabled=YES
ID=101 Name="EasyList" Version=1.0.66.79 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.67 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.66 Enabled=YES

![image](https://cloud.githubusercontent.com/assets/17320558/24330372/221ac6e6-1225-11e7-8095-91cb99843d13.png)

</details>

Ticket ID:1201289

**Comment by Alex-302** [comment]
Also not reproduce. Try to disable third party filters.
About missed ads please write to this repository
https://github.com/AdguardTeam/AdguardFilters/issues
