### ISSUE TITLE
Activating "Pro" mode blocks internet connection on 10.3.2 developer beta 1

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardForiOS#352]
Multiple complaints from various users in different regions about not being able to connect to the Internet since updating to beta iOS version 10.3.2.

And a forum topic:https://forum.adguard.com/index.php?threads/ios-10-3-2-b1.20450/

**Comment by ameshkov** [comment]
Yep, working on it right now

**Comment by dmitrik555** [comment]
Совсем не работает! Вырубает интернет соединение любого типа при включении DNS!
При включении пропадает как WiFi так и Мобильный интернет!

**Comment by vozersky** [comment]
Confirmed

**Comment by tosbsas** [comment]
I Need my vpn back. Any Info what happened?

**Comment by ameshkov** [comment]
Seems to be a dev preview bug, a lot of VPN apps are now broken.

**Comment by tosbsas** [comment]
Whow. You contacted Apple about this?

**Comment by ameshkov** [comment]
We'll report it asap.

More reports:
https://forums.developer.apple.com/thread/74990
https://www.reddit.com/r/iOSBeta/comments/626aem/bug_ios_1032_openvpn_vpns_will_not_connect/

**Comment by tosbsas** [comment]
Seems there is a work around as opera VPN seems to work :-)




___________________________

Ruben Gutknecht

Lima, Peru

Cel: +51-99349-1515<tel:+51-99349-1515>

Fax: 001-928-223-4243<tel:001-928-223-4243> International

Voice/Fax: 49 (0) 721-151-379204<tel:(0)%20721-151-379204>

http://telegram.me/tosbsas

tosbsas@gmail.com<mailto:tosbsas@gmail.com>

ttosbsas@icloud.com<mailto:ttosbsas@icloud.com>

Ruben.Gutknecht@outlook.com<mailto:Ruben.Gutknecht@outlook.com>


Am 29.03.2017 um 13:37 schrieb Andrey Meshkov <notifications@github.com<mailto:notifications@github.com>>:


We'll report it asap.

More reports:
https://forums.developer.apple.com/thread/74990
https://www.reddit.com/r/iOSBeta/comments/626aem/bug_ios_1032_openvpn_vpns_will_not_connect/

**Comment by dmitrik555** [comment]
And what now plans?

**Comment by dmitrik555** [comment]
Conferm! Opera VPN OK!

**Comment by ameshkov** [comment]
Opera VPN uses the old mobile profile configuration approach, that's why it works.

All apps which use network extensions seems to be broken.

**Comment by ameshkov** [comment]
> And what now plans?

The only thing we can do is to report this bug to Apple and wait for them to resolve the issue.

We'll be posting updates on it here.

**Comment by dmitrik555** [comment]
How it is correct to formulate in apple this problem? I too will write about it

**Comment by tosbsas** [comment]
So all we can do is to wait for beta 2

**Comment by ameshkov** [comment]
> How it is correct to formulate in apple this problem? I too will write about it

VPN apps based on Network Extension framework (https://developer.apple.com/reference/networkextension) are completely broken in this beta version.

> So all we can do is to wait for beta 2

Yep

**Comment by tosbsas** [comment]
Maybe you can keep us posted bout Any answers from Apple

**Comment by tosbsas** [comment]
Freedom VPN work too

**Comment by jesusc31** [comment]
Fixed on 10.3.2 beta 2

**Comment by dmitrik555** [comment]
Yes, thanks, works now

**Comment by ameshkov** [comment]
I wonder did they fix #353

**Comment by dmitrik555** [comment]
Да, спасибо, теперь работает

> 10 апр. 2017 г., в 20:45, Andrey Meshkov <notifications@github.com> написал(а):
> 
> I wonder did they fix

**Comment by tosbsas** [comment]
works no, one question - can Adguard Pro be closed or should I keep it running open in the background

**Comment by dmitrik555** [comment]
не понял вопроса!I did not understand the question! 10.04.2017, 20:49, "tosbsas" <notifications@github.com>:works no, one question - can Adguard Pro be closed or should I keep it running open in the background—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by tosbsas** [comment]
At the beginning of testing Adguard Pro I was told that filter update and stuff would only work if I keep the app running in the background  On killing it manually those features and even some blocking features would not work. During ios 10.3.2 beta1 problem time I used adblock where its not necessary to keep the app in the background

**Comment by vozersky** [comment]
@tosbsas Force quitting Adguard doesn't affect any filtering features, it only affects background updates. And it's the same for any other app, iOS works this way.

**Comment by dmitrik555** [comment]
А синхронизация планируется какая то в облаке? Для сохранения вручную добавленных фильтров

**Comment by tosbsas** [comment]
@vozersky
Ok thanks

**Comment by vozersky** [comment]
> А синхронизация планируется какая то в облаке? Для сохранения вручную добавленных фильтров

да, планируется, [вот задача ](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/315)

**Comment by dmitrik555** [comment]
Спс, с нетерпением ждем

**Comment by kootik** [comment]
версия 10.3.1. (14e304) (не beta) после обновление не заработало vpn не соединялся после перезагрузки вышло такое окно Adguard внимание в данный момент отсутствует соединение с интернетом нужно запустить приложение чтобы выполнить дополнительную настройку и так каждый раз после перезагрузки (после захода в приложение vpn поднимается)
притом это у всех почитайте отзывы в itunes

**Comment by ameshkov** [comment]
@kootik мы уже знаем, версия с исправлением уже в AppStore, да только ревью займет какое-то время.

**Comment by kootik** [comment]
![facepalm](https://cloud.githubusercontent.com/assets/6498896/25052481/ac8a899e-215a-11e7-9a3f-0e4112987c13.gif)

**Comment by Stillness-2** [comment]
@kootik Так я не пойму, у Вас сейчас работает нормально?

**Comment by kootik** [comment]
после отключения и повторного включения всех настроек в  adguard pro и смены и активации всех режимов оно после перезагрузки заработало но каждый раз выдает такое окно  при перезагрузке телефона  перешел на другой продукт на котором у меня бесконечная подписка  и более расширенный набор функционала 
![img_6710](https://cloud.githubusercontent.com/assets/6498896/25052596/58145812-215b-11e7-842b-403195bffa65.PNG)

**Comment by ameshkov** [comment]
> но каждый раз выдает такое окно при перезагрузке телефона

Вообще должна помогать простая переустановка.

**Comment by ameshkov** [comment]
@kootik 

Итого, решение проблемы без апдейта (если эта проблема вылезла, потому что лезет не у всех):
1. Удалить AG
2. Ребутнуться
3. Установить заново

**Comment by danidoedel** [comment]
How is the status of this? I'm on Beta 4 and it's not working for me.

**Comment by ameshkov** [comment]
@danidoedel you're the first who complaints on this, could you please send the logs to us?

**Comment by danidoedel** [comment]
What logs do you need? I'm not too familiar with log files ;)

**Comment by ameshkov** [comment]
> What logs do you need? I'm not too familiar with log files ;)

Just send a message from the app, the log file will be attached to the email.

I'll also need to know your customer ID

**Comment by zebrum** [comment]
@danidoedel thank you
user id 1322540
