### ISSUE TITLE
Ad filtering issues on iOS 10.3 and 10.3.1

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForiOS#353]
Certain ads can not be blocked or blocked correctly on devices with iOS 10.3

The reason is:
https://bugs.webkit.org/show_bug.cgi?id=169167

Part of cosmetic rules might not work anymore.

**Comment by deLumren** [comment]
User 1532426 reports ads during authorization in Metro wi-fi. He's using iOS Adguard v1.1.5.40.
iOS v10.3
For example:
<details>

![default](https://cloud.githubusercontent.com/assets/26342177/24506830/6c1fd822-1567-11e7-8300-04e9d576648c.png)

</details>

Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.12.75 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.9 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.11 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.11.8 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.48.66 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.7.55 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.77 Enabled=YES

**Comment by Itsnothectic** [comment]
I am too scared to upgrade, can Apples hosts be blocked still?

**Comment by ameshkov** [comment]
@Itsnothectic yeah, it can. What's broken in 10.3 is some types of cosmetic rules in the Safari Content Blocker. It should be resolved when new Safari version is out.

**Comment by Itsnothectic** [comment]
Thanks this is good to know.

**Comment by danidoedel** [comment]
Seems fixed in 10.3.2 Beta 3

**Comment by ameshkov** [comment]
@danidoedel yep, @Alex-302 has also confirmed it. Time to close this issue:)
