### ISSUE TITLE
Blacklist/whitelist rules should have higher priority than the regular filter

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#354]
for example googleadservices.com is in the dns exceptions list. i add it to my dns blacklist and it still is whitelisted.. can anyone reproduce? on latest official ios and latest adguard beta

**Comment by jo2dan23** [comment]
@ameshkov

**Comment by ameshkov** [comment]
Huh, that's a good question. Assigned it to the next version.

Meanwhile, regarding `googleadservices.com`, we may look for a better way to unbreak Google search results. @Alex-302 why didn't we excluded it instead of adding an exception rule?

**Comment by Alex-302** [comment]
> a ***better*** way to unbreak Google search results

I think, it does not exist. We should to unblock(by exception) `pagead.l.doubleclick.net` in addition to excluding `googleadservices.com`.

**Comment by jo2dan23** [comment]
Issue still exists in latest beta.

**Comment by jo2dan23** [comment]
h-sdk.online-metrix.net cannot be blocked on my end. Which is in the exceptions list

**Comment by ameshkov** [comment]
Will be resolved in the next beta

**Comment by jo2dan23** [comment]
Still not fixed. Googleadservices is now unblocked again causing ads in my apps and blacklisting them doesnt override exceptions.

**Comment by jo2dan23** [comment]
Hopefully it can be fixed soon :/ @ameshkov

**Comment by ameshkov** [comment]
> Still not fixed. Googleadservices is now unblocked again causing ads in my apps and blacklisting them doesnt override exceptions.

@IvanIin have you included that fix in the latest beta?

**Comment by IvanIin** [comment]
@jo2dan23 @ameshkov This fix is not included in the last beta. I'll add it to the next version.
