### ISSUE TITLE
[feature request] option to block arpa lookups

### ISSUE THREAD

**Issue by Itsnothectic** [AdguardTeam/AdguardForiOS#355]
Is it possible to have an option to block arpa lookups completely?

My friend using android showed me some wallpaper app contacting a lot of hosts, about 10 and 2 were IPs. One of those IPs was very suspicious based on some of the host names that point to it.

**Comment by ameshkov** [comment]
I guess you mean to block a network connection to a specific IP address.

Nope, right now we cannot technically do it. However, once #174 feature is implemented, you'll be able to completely block network access for an app. Not the same, but that's a good solution for wallpaper apps:)
