### ISSUE TITLE
User filter search issue

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForiOS#356]
STR:
1. Search for some words or symbols combinations you CAN actually find in UF.
2. Now add some more symbols to the same combination to transform it to one that can't be find in UF.
3. Press "search" again.

Expected result: No results found.
Actual result:  Results of the first search remain highlighted.

Screenshot:
<details>

![img_0011](https://cloud.githubusercontent.com/assets/17472907/24608787/b116750a-1880-11e7-85ef-7e7db02bccc9.PNG)

</details>

**Comment by zebrum** [comment]
one more thing:
after step 1, delete search string and type in new one, with exist in user filter.

Expected result: Aguard start new search from the beginning of UF
Actual result: searching continuing from where it stopped at the first time
