### ISSUE TITLE
ikea.com - incorrect blocking 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardForiOS#357]
Adguard doesn't allow to use a credit card on ikea.com 

Screenshots:

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24643145/a74ef17a-1914-11e7-924a-44e47ecc2f42.png)
![image](https://cloud.githubusercontent.com/assets/17320558/24643150/b0939380-1914-11e7-9d16-5d499ff16c89.png)
![image](https://cloud.githubusercontent.com/assets/17320558/24643155/b898e22e-1914-11e7-8683-ba9ba8b368c7.png)
![image](https://cloud.githubusercontent.com/assets/17320558/24643164/bf4014ee-1914-11e7-9708-093d3c9a2bd1.png)

</details>

Filters:
<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.0.97.71 Enabled=YES

ID=3 Name="Spyware filter" Version=1.0.8.18 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.13.56 Enabled=YES

ID=6 Name="German filter" Version=1.0.27.85 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.1.48 Enabled=YES

ID=107 Name="EasyList Germany" Version=1.0.60.42 Enabled=YES
</details>

Ticket ID: 1534392

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardFilters
