### ISSUE TITLE
Blocking ||io^ breaks non user filters

### ISSUE THREAD

**Issue by Itsnothectic** [AdguardTeam/AdguardForiOS#360]
The app only seems to contact filters.adtidy.org but when ||io^ is blocked only the user filter will work.

I cant confirm this properly as I only have one phone with AdGuard Pro but to test.

1. Look at a domain that is "blocked by DNS" or is listed in one of the public filters you use.

2. Ping the host to make sure its blocked

3. Add ||io^ to the user filter

4. Restart the phone

5. Ping the host again and see that it is not blocked

Bug needs confirmation please.

**Comment by IvanIin** [comment]
@Itsnothectic 
The latest versions of Adguard use a new scheme of system-wide filtering. Now, the user-defined filters are specified separately in the system-wide-> Blatsklist / Whitelist section. Does the issue repeat in the latest version of the program?
