### ISSUE TITLE
DNS makes router crash

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardForiOS#361]
Ticket ID: 1519048
User:
DNS makes my router Netgear Nighthawk R8000 crash and reboot when streaming with CanalDigitaal app. It works great on NUC5i7RYH Windows 10, android tablet but on iPad Pro 9.7 always problems.

Logs, 14.31 Brussel time:
[com.adguard.AdguardPro (2).gz](https://github.com/AdguardTeam/AdguardForiOS/files/907082/com.adguard.AdguardPro.2.gz)
[com.adguard.AdguardPro.tunnel (1).gz](https://github.com/AdguardTeam/AdguardForiOS/files/907083/com.adguard.AdguardPro.tunnel.1.gz)
[filter.gz](https://github.com/AdguardTeam/AdguardForiOS/files/907084/filter.gz)
[state (68).txt](https://github.com/AdguardTeam/AdguardForiOS/files/907085/state.68.txt)

**Comment by ameshkov** [comment]
Router? Are you sure it's not about the app?

**Comment by OlegSUP** [comment]
Asked for additional information about behaviour with DNS Off and Adguard Off, but I guess user complains about router rebooting when using this app with Adguard Pro DNS. Is it possible?

**Comment by ameshkov** [comment]
@OlegSUP never heard of anything like that. Everything can happen though:)

**Comment by zebrum** [comment]
user said problem has gone after router hard reset.
