### ISSUE TITLE
How can I block something.* for the DNS

### ISSUE THREAD

**Issue by Itsnothectic** [AdguardTeam/AdguardForiOS#363]
I looked through the documentation and tried |something^ something|| but neither work.

From what I saw in the documentation |something should work but seems to be a missing feature.

**Comment by ameshkov** [comment]
DNS-blocker has a limited support of the filters syntax. It should support basic special characters, though.

You're on the beta version, right?

**Comment by Itsnothectic** [comment]
Im using Pro from the appstore.

I dont use Safari, I use Adguard only for the DNS and I block new hosts every day that pop up on news sites and I could cut this by over 75% if I am able to block domains like track.* analytics* and *metrics*.

I notice theres too many keywords that are used in place of the old ads. prefix that should be blocked. So I think this would be a good feature.

**Comment by vozersky** [comment]
some of basic rules should be working now
