### ISSUE TITLE
Sufficient rules for blocking reuters.com missing, and a bug

### ISSUE THREAD

**Issue by Itsnothectic** [AdguardTeam/AdguardForiOS#364]
This is by far the most obnoxious site for first party trackers. 

First party trackers are not as bad as third party and most find them acceptable but I see some are blocked and some arent. There is also way too many, about 20 requests are made visiting one news article so I feel like mentioning this.

These rules are needed:

||reuters.com^
||thomsonreuters.com^
@@||mobile.reuters.com$document
@@||www.reuters.com$document

Optionally:
||reutersmedia.net^ Will break formatting
||reuters.zendesk.com^

It also sends referral to www.twitter.com.

||.mobile.reuters.com^ Is also needed but does not work.

**Comment by vozersky** [comment]
Moved to Filters: https://github.com/AdguardTeam/AdguardFilters/issues/4780
