### ISSUE TITLE
Hostname not always blocked if resolved from a different hostname

### ISSUE THREAD

**Issue by Itsnothectic** [AdguardTeam/AdguardForiOS#365]
I see a lot of hosts that point to an IP and also netdna-cdn.com which seems to be like akadns except every host that uses netdna is useless to the user and its a different name for every site.

Example here:
http://www.vocativ.com/414570/workplace-spying-surveillance-dystopia-we-work-in/

"Releases.flowplayer.org" should always be blocked if I only have ||netdna-cdn.com^

**Comment by ameshkov** [comment]
@Itsnothectic that would be very dangerous to have such a behavior. We might not know about other uses of this CDN.

So, I suppose we should block `releases.flowplayer.org` explicitly instead (and all similar domains as well).

**Comment by ameshkov** [comment]
However, in this particular case, what's wrong with `releases.flowplayer.org` domain? It seems that it's used for merely serving static files.

**Comment by Alex-302** [comment]
Why releases.flowplayer.org should be blocked? I don't understand what I should do.

**Comment by Itsnothectic** [comment]
When I visit a new website I check for trackers and anything third party I block. I blocked flowplayer and did not notice any change so I assume it is a tracker. And personally I do block widgets and such as well until an iOS browser can stop sending referrer.

So looking at what flowplayer actually is, it is a Finnish company that provides a HTML video player that can be hard to get working for webmasters, perhaps why it doesnt work on this website?

http://m.ripoffreport.com/reports/flowplayer/-/flowplayer-anssi-piirainen-tero-piirainen-bernd-backhaus-christian-ebert-courtney-cou-1251173#comment_3

Okay I ser Apple already block it for piracy reasons!

**Comment by ameshkov** [comment]
I guess they might be using flowplayer somewhere on the website and that's why you see that domain. However, it does not seem to be tracking you, it is used for serving static files only.

**Comment by vozersky** [comment]
@Alex-302 so, can I close the issue?

**Comment by ameshkov** [comment]
Sure
