### ISSUE TITLE
Think about moving the simplified domain names filter to the "System-wide ad blocking" section

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#369]
Source:
https://forums.macrumors.com/threads/adguard-pro.2039619/#post-24491280

Currently, it is completely unclear which filter is used for the system-wide ad blocking.
Also, people cannot change it in any way.

I don't yet understand how exactly should we change the UI, though.

**Comment by Itsnothectic** [comment]
Its very bad that when updating to 1.2, the list defaults to safari blocking and not both, this causes app leaks without any warning to the user.

I think the UI is fine except the system wide blocking should automatically remove || and ^ e tc and the safari should automatically add it if needed. This way its possible to copy lots of rules to either.

**Comment by ameshkov** [comment]
@Itsnothectic the problem here is that system-wide ad blocking is just too different from safari content blocking. Mostly because it cannot distinguish third-party from first-party requests, so we have to be extra cautious with it.
