### ISSUE TITLE
Redesign of the background filters update

### ISSUE THREAD

**Issue by Stillness-2** [AdguardTeam/AdguardForiOS#37]
May be we need to check version number of the filters synchronously, but download of the filter rules to do asynchronously, in system background download task (NSURLSession).

**Comment by Stillness-2** [comment]
Now, background filters update should work. But updating is performed only when device is connected to internet via WiFi.

**Comment by ameshkov** [comment]
Finally! So what about pushing new beta with this change?

**Comment by Stillness-2** [comment]
already
