### ISSUE TITLE
Option to filter dns logs by blocked unblocked or no response

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#376]
This would be helpful when searching for unblocked ads quicker

**Comment by ameshkov** [comment]
Frankly, I'd like to do more than just adding a search filter.

Have you seen the filtering log on Android?

**Comment by jo2dan23** [comment]
I agree it's really complicated and time consuming to find something in the logs atm. I used to have an android but i don't remember the filtering log part of adguard when i had it

**Comment by ameshkov** [comment]
@jo2dan23 try the beta version, you'll like it.

**Comment by jo2dan23** [comment]
I dont have an android anymore. Haha.

**Comment by ameshkov** [comment]
Heh, one moment then.

**Comment by ameshkov** [comment]
Here you are:
https://appetize.io/app/0ctb82jkamxa8aw5yf0uf2nqwm

**Comment by jo2dan23** [comment]
Oh thats cool its like a little emulator lol. I love how it shows where the Dns hostnames come from like chrome for example. So its easier to figure out which ad came from what app

**Comment by ameshkov** [comment]
Android does not use DNS-level ad blocking by default, these are real web requests.

You can enable DNS-level filtering though, but then you'll see that DNS requests come from the Anddroid itself.

**Comment by jo2dan23** [comment]
Oh cool now i see the dns logs. I like that log much better than the ios one!

**Comment by ameshkov** [comment]
Yep, that's what I'd like us to have on iOS as well.

iOS one is, you know, a bit too messy.
