### ISSUE TITLE
System-wide ad blocking breaks instagram videos

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#377]
Source:
https://www.reddit.com/r/iphone/comments/65ekr9/adguard_pro_we_just_released_the_worst_update/dgbizv2/?context=3

> Ever since the last update (I've tried deleting and reinstalling the app to no avail) auto-play videos, like those viewed on instagram, the videos play for about 3 seconds and then time out. This only happens with adguard pro enabled.

**Comment by ameshkov** [comment]
We should report it back to Reddit once we know what's the culprit.

**Comment by vozersky** [comment]
Doesn't happen anymore: [Reddit](https://www.reddit.com/r/iphone/comments/65ekr9/adguard_pro_we_just_released_the_worst_update/dge6jyt/)
