### ISSUE TITLE
Add "Open Settings..." link to the tutorial screen

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#380]
Talking about the screen with information about setting up a content blocker.

**Comment by IvanIin** [comment]
There is no legal way to open any settings except for the settings of our application (https://forums.developer.apple.com/thread/65007). There are undocumented api that allow to do this(https://stackoverflow.com/questions/43064198/open-settings-programmatically-ios-10), but using them will probably cause a app store reject.
