### ISSUE TITLE
Beta version update issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#382]
**Original report:**
> For some reason newest version of the TestFlight I has to delete the app, reboot my phone, then it allowed me to install the new version of this app. Otherwise when I went to delete the old beta to install the new one my cellular was not working which is why I had to reboot my phone. I think somehow my phone thought it so had the app installed and the VPN configuration was messing with my connection.

@vozersky please try to reproduce it.

**Comment by ameshkov** [comment]
```
Device Information:
Device: iPhone9,2
iOS Version: 10.3.1
```

**Comment by vozersky** [comment]
obsolete
