### ISSUE TITLE
state.txt feature requests

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#383]
1. Can you add information about the system-wide adblocker? It would be nice to know if it's enabled and which DNS a customer uses.
2. Can you add there how many filtering rules a user has?
3. Please fix the typo in "Optimized filters" string:

![image](https://cloud.githubusercontent.com/assets/15856304/25311446/dd32b822-2809-11e7-99c1-f90065a40adf.png)

**Comment by ameshkov** [comment]
Hecking optimazed, can't see it anymore

**Comment by Bohdan-SUP** [comment]
@ameshkov what about info on DNS options and filtering rules counter, please?

**Comment by Stillness-2** [comment]
In latest beta

**Comment by Stillness-2** [comment]
@Bohdan-SUP check please :)
