### ISSUE TITLE
Compatibility with iOS9

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#384]
Hi, previous versions I never had this issue. Now with the latest version, vpn is dropping all the time. I have removed and installed the app. Still the same. I have enabled PRO dns settings adguard.

**Comment by ameshkov** [comment]
When does it happen? How often?

I might be expected behavior. When the filter is being updated, AG destroys the VPN tunnel so that it could be reinitialized with the new settings.

**Comment by worldsdream** [comment]
Every 5-10 min. Even if I have the app killed. Never had this ever before.

**Comment by worldsdream** [comment]
If i am in safari or in an app. Does not matter. Internet will not work. Vpn in statusbar goes away. Vpn comes back in statusbar. Internet is good again. I had to turn the pro function off. Can't use the phone like that.

**Comment by ameshkov** [comment]
> Every 5-10 min. Even if I have the app killed. Never had this ever before.

That's bad, could you please send us the log?

**Comment by ameshkov** [comment]
Btw, what's the iOS version/

**Comment by irow14** [comment]
I have the same issue.
Please look at the video in the URL.
https://www.dropbox.com/s/spvu45znu5kvqud/adguard_bug.mov?dl=1
I did report bugs in this regard, but the answer was to remove and reinstall.
I doing 'Reset Network Settings' and 'Erase All Content and Settings', but the same issue continued.
There was no such issue in 1.1.6.
iPhone 6s iOS 9.3.5

**Comment by worldsdream** [comment]
I have an iphone 6s 9.3.3. Exactly the same as the video that irow14 uploaded. All was good in old version.

**Comment by ameshkov** [comment]
@irow14 @worldsdream guys, got it, thank you very much for reporting it!

It seems that the issue appears on iOS 9.x, everything is good with iOS 10.
We'll take care of it.

**Comment by Stillness-2** [comment]
@irow14 Can you give me a customer id from support email, please?

**Comment by Stillness-2** [comment]
@irow14 I think that I found your logs... Can you please turn off system-wide filtering, and use remote DNS server, for example Adguard DNS? Check please how VPN works with those settings, and then send bug report again. :)

**Comment by irow14** [comment]
@Stillness-2 I send bug report, check please.

**Comment by worldsdream** [comment]
@stillness-2. Still the same problem.

**Comment by ameshkov** [comment]
The worst thing here is that there's no easy way to install IOS9

**Comment by KozelElena** [comment]
Our customer has the same complaint 
iOS 9 

Ticket ID:1496881

**Comment by vozersky** [comment]
#385

**Comment by zebrum** [comment]
@worldsdream @irow14 hello! 
if you are using mac:
- connect your device to mac, 
- run lemonjar app http://lemonjar.com/iosconsole/
- reproduce the problem, 
- export logs https://www.dropbox.com/s/bd6rw6cr5f8ei3z/Screenshot%202017-04-26%2015.01.10.png?dl=0 and send log file to support@adguard.com

**Comment by zebrum** [comment]
and here as well an instruction for windows: https://success.trendmicro.com/solution/1106560-collecting-system-logs-on-ios-8-x-devices#collapseTwo

**Comment by irow14** [comment]
I send log file, check please.

**Comment by zebrum** [comment]
thank you @irow14 
user id 1544297

[iOS9logs1.zip](https://github.com/AdguardTeam/AdguardForiOS/files/958381/iOS9logs1.zip)

**Comment by zebrum** [comment]
@irow14 there also should be a crash report on your iOS device. Let's try to get them with Crash Logs button 

![screenshot 2017-04-26 19 11 50](https://cloud.githubusercontent.com/assets/23637588/25444623/6fd3e0b4-2ab4-11e7-8e37-5981d0711043.png)

**Comment by bigdargon** [comment]
my iphone 5s ios 9.3.3 same problem

**Comment by ameshkov** [comment]
Sorry for the late reply, we had long holidays here.

It seems that we've found a culprit, update will be ready soon.

**Comment by ameshkov** [comment]
Funny thing, it's almost impossible to downgrade to iOS9 so we had to buy a new test iphone in order to test this:)

**Comment by bigdargon** [comment]
> Funny thing, it's almost impossible to downgrade to iOS9 so we had to buy a new test iphone in order to test this:)
Adguard Pro in iOS 9 so terrible, VPNs often disconnect and then automatically reconnect a few seconds, which causes me to disconnect from the web and refresh later. Hope this bug will be fixed in the next update! Thanks

**Comment by vbagirov** [comment]
Guys, anyone with the Adguard TestFlight who is on iOS 9: is VPN stable in the last test build? Any issues?

**Comment by worldsdream** [comment]
Tested it right now. Still the same. Nothing has changed.

**Comment by ameshkov** [comment]
> Tested it right now. Still the same. Nothing has changed.

Argh, how so:(

What exact version do you see in TestFlight?

@Stillness-2 what kind of logs do we need?

**Comment by worldsdream** [comment]
Version 1.2.2 (81)

**Comment by Stillness-2** [comment]
@worldsdream @ameshkov We need logs which described above @zebrum

**Comment by ameshkov** [comment]
@worldsdream could you please assist?

I wonder why does it work okay on our iOS9 device. Maybe we should simply not add IPv6 routes for iOS9?

**Comment by worldsdream** [comment]
I have sent an e-mail to support with the logs. It happened to me and then I did make the report. So it should be on the end of the log. Let me know.

**Comment by KozelElena** [comment]
Logs are here: 1212314

**Comment by Stillness-2** [comment]
@worldsdream Can you send a mail to support from the app? We need to know your Adguard vpn settings. Or, you can send report to yourself, simply change the mail address to yours and resend  us the `state.txt` file that will be attached to it.

Also please notice if you are currently connected to WiFi or cellular network? Is IPv6 allowed in theis network?

**Comment by worldsdream** [comment]
I'm connected to wifi. Ipv6 is allowed. 
I just sent an email to support.

**Comment by ameshkov** [comment]
@Stillness-2 it'd be nice to test with the latest @IvanIin fix so that we could see the active network interfaces in the log.

**Comment by zebrum** [comment]
@worldsdream hello!

new beta 1.2.2 (86) is ready. Could you try it?

**Comment by irow14** [comment]
ios 9.3.5. Used 1 hour. Work fine.
Thx.

**Comment by ameshkov** [comment]
![ezgif-2-74fdf98443](https://cloud.githubusercontent.com/assets/5947035/26730494/ceac57f2-47b9-11e7-9933-93ef198cfb7e.gif)

**Comment by worldsdream** [comment]
It's working fine. Great job.
