### ISSUE TITLE
Error with iTunes - Adguard Pro

### ISSUE THREAD

**Issue by chetngatluon** [AdguardTeam/AdguardForiOS#385]
Cannot connect iTunes when vpn is enabled.

iPhone 5s - iOS 9.3.5

iTunes 12.6.0.100
Windows 10 & macOS Sierra

**Comment by vozersky** [comment]
reproduced

**Comment by vozersky** [comment]
@Stillness-2   15:12 -15:13
[iOS_Console_Adg's_iPhone_2017-05-0415.13.34.log.zip](https://github.com/AdguardTeam/AdguardFilters/files/976052/iOS_Console_Adg.s_iPhone_2017-05-0415.13.34.log.zip)
