### ISSUE TITLE
Way too many unblocked ads

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#389]
@@://googleadservices.com
@@://www.googleadservices.com

These filters are allowing multiple ad domains to be unblocked in apps I am using i didnt have this problem til those filters were added. I have seen about 15 ad domains if not more being reached

**Comment by jo2dan23** [comment]
There has to be a better workaround to fix google search ads?

**Comment by jo2dan23** [comment]
Here is my dns log

https://1drv.ms/u/s!AvccVnEjavPPhismoq5sCWuFJF1m

**Comment by jo2dan23** [comment]
The ads appeared for me between 5:30- and 5:50

**Comment by vozersky** [comment]
[moved](https://github.com/AdguardTeam/AdguardFilters/issues/4881)
