### ISSUE TITLE
Cosmetic filters not working in Adguard 1.2.1

### ISSUE THREAD

**Issue by gotitbro** [AdguardTeam/AdguardForiOS#390]
Cosmetic filters are not working on http://indianexpress.com on **_Safari with Adguard Content Blocker 1.2.1_**.  
I am seeing blank _google ad iframes_ which do not get hidden despite adding a specific **_User Filter_**:
`indianexpress.com##div[id^="div-gpt-ad"]` 

**SS:** https://i.imgur.com/IztXw52.png
**Error URL:** 
http://indianexpress.com/article/cities/delhi/mcd-election-result-bjp-sweeps-delhi-wins-181270-civic-wards-aap-left-holding-broom-4629845/

**Note:** The **_English filter_** already contains the filter `##div[id^="div-gpt-ad"]` it is not working as well. This was not the case in the previous version of the application though. 
I am not sure if the same is the case with other websites as well.

**Comment by Alex-302** [comment]
Don't you want to update on 1.3.1?

**Comment by gotitbro** [comment]
@ameshkov I think I might have found another issue related to this, but first I need to clarify something. Would the following rule work in iOS:
`##style[type="text/css"] + div[class]:not([id]):not([style]):not([class*=" "])` 

(https://forum.adguard.com/index.php?threads/resolved-colombia-ads-missed-ads-windows.19238/#post-125072)

**Comment by ameshkov** [comment]
Huh, it looks like a totally legit CSS selector, so it should work.

Can't check it in iOS, but it works in desktop Safari

**Comment by gotitbro** [comment]
@ameshkov Sorry for the late reply, I have been facing some issues with my email.
Thanks for clarifying that the filter is valid, I knew that it was working before. Such filters have been used to hide Colombia ads. Since the update the colombia ads are not being hidden even if a filter is added manually.

**Example: m.economictimes.com**
**SS:** https://imgur.com/a/BTOou
**Error URL:** 
http://m.economictimes.com/jobs/bulk-hiring-by-it-companies-at-tier-2-3-engineering-colleges-and-b-schools-may-hit-hard/articleshow/58831474.cms

Similarly colombia ads on other websites are not being hidden as well on iOS.
**Example:** _http://m.maharashtratimes.com, http://m.vijaykarnataka.com and others_ (https://github.com/AdguardTeam/AdguardFilters/issues/4787)


This is not limited to colombia ads either as described in the top post cosmetic filtering is not working on indianexpress.com as well. 

Another website where I found cosmetic filtering is not working is http://m.eenaduindia.com.
**SS:** http://i.imgur.com/rzVVAbs.jpg
**Error URL:** http://m.eenaduindia.com/
These blank ad frames should get hidden as well due to this `##div[id^="div-gpt-ad"]` filter in the _**English filter list**_ but aren't.

I conclude from these findings that cosmetic filtering is not working correctly in the latest _**Adguard Content Blocker 1.2.1**_ for all websites. This is a serious issue and needs to be looked upon ASAP.

_**PS:** Please tell me if it is possible to downgrade to the previous version._

**Comment by IvanIin** [comment]
What version of iOS is installed on your device? Some cosmetic rules do not work on ios 10.3.1. In version 10.3.2 this will be fixed.

https://github.com/AdguardTeam/AdguardForiOS/issues/353

**Comment by gotitbro** [comment]
@IvanIin I just updated to iOS 10.3.2 after your comment and cosmetic filtering was working again correctly.

Thanks for pointing this out :)

**Comment by ameshkov** [comment]
Yeah, I totally forgot about #353 :)
