### ISSUE TITLE
Ads are not blocked when system-wide ad blocking is ON

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#393]
Discussion:
https://forum.adguard.com/index.php?threads/ein-paar-fragen-zur-pro-version.21158/page-2

Logs:
[com.adguard.AdguardPro.tunnel (6).gz](https://github.com/AdguardTeam/AdguardForiOS/files/967581/com.adguard.AdguardPro.tunnel.6.gz)

Customer ID:
1549188

**Comment by jo2dan23** [comment]
This is happening to me ALOT. I thought it was cuz google ad services was unblocked but it isnt. Randomly ads will just appear in the app. BUT, if i turn the vpn on and off the ads will be blocked again. Seems like a bug to me

**Comment by jo2dan23** [comment]
This happened to me on the weather channel app, whisper, meetme and instasize among others. Hopefully this can be fixed.

**Comment by ameshkov** [comment]
Huh, I wonder what's going on.

Could you please be more specific? What's your current configuration (DNS/System-wide), when does it happen?

**Comment by jo2dan23** [comment]
I am using opendns home servers. It happens randomly. On wifi and cellular.

**Comment by ameshkov** [comment]
@Stillness-2 I guess we'll need a tunnel log anyway.

However, the log wouldn't be enough, we'd also need to know the exact time when it happened.
I suspect some kind of a race condition (for instance, when the tunnel is initialized, some requests might slip through or whatnot).

**Comment by jo2dan23** [comment]
I have found two unblocked ad domains in two of the apps that showed ads. I assume these are the ones that are generating all the ads

applvn.com
tangerine.nexage.akadns.net

**Comment by jo2dan23** [comment]
Here is my log. The ads started appearing at 16:55 there are multiple unblocked ad domains that started showing after then nexage domain. I dont know if those will show up the tunnel log because last time they didnt

https://1drv.ms/u/s!AvccVnEjavPPhi0sgBaAi7uxLGI-

**Comment by jo2dan23** [comment]
Here is some more:
 
moatads.com.edgekey.net
event-service-*.amazonaws.com
adsdk.vrvm.com

**Comment by Stillness-2** [comment]
@jo2dan23 I can not get the log file by your link. If you add unblocked  domains to the black list, does the problem repeat?

**Comment by jo2dan23** [comment]
@Stillness-2 sorry for the late reply. I have been gathering ad domains. I have added all the unblocked domains in the exceptions/exclusion lists and still get ads. I dont know if these will stop for good. But these are the ad domains I found in my logs:

data-agkn-com-*.amazonaws.com (ad domain for agkn.com)
cdn.liftoff.io
sessionstat-*.amazonaws.com (tracking)
s.mopub.com

**Comment by ameshkov** [comment]
> s.mopub.com

@Alex-302 shouldn't we block `mopub.com` completely in the mobile ads filter?

**Comment by jo2dan23** [comment]
This can be closed. Its basically the same as my bypass tunnel issue

**Comment by ameshkov** [comment]
Sure, closed as dup of #404
