### ISSUE TITLE
Not able to report missed ad in Safari 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardForiOS#394]
Not able to report missed ad in Safari with Adguard 
Application version: 1.1 , 1.2
Device: iPhone
OS: 10.3, 10.1
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.13.13 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.18 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.17 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.11.22 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.77 Enabled=YES

**Comment by evgeniy-ADG** [comment]
@vmalyuta add some description and steps to reproduce.

**Comment by vmalyuta** [comment]
1. Go to Safari
2. Open any website
3. Try to report missed ad/incorrect blocking 
4. Nothing happen

**Comment by Stillness-2** [comment]
@vmalyuta do you use latest version Adguard (1.2.1)? 
Do you use the standard mail app?

**Comment by vmalyuta** [comment]
1. Yes
2. Yes
