### ISSUE TITLE
[Question] Adguard DNS incorrect behavior

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#395]
On Wi-Fi, system-wide DNS filtering does not work when choosing say Google Public DNS, and outbound DNS is blocked by a firewall on the LAN. The system falls back to the DHCP assigned DNS servers when Google Public DNS is blocked, but the filtering does not work. The correct behavior should be that the fake VPN DNS server is still used for filtering, but it should forward queries to the DHCP assigned DNS servers if Google Public DNS is not reachable.

ID: 1556199

**Comment by X8716e** [comment]
I realize this isn't technically an answer if people are dead-set on using google dns, but I've two suggestions. Manually set DNS to 8.8.8.8, etc. in device's wifi config. Or use something like OpenNIC's servers @ https://OpenNICproject.org/ which are quite excellent in my experience.

**Comment by vozersky** [comment]
@evgeniy-ADG any change noticed with the latest builds?

**Comment by ameshkov** [comment]
Reopen if there're new reports.
