### ISSUE TITLE
If using Opera VPN, Adguard dosnt block!

### ISSUE THREAD

**Issue by YoKoGFX** [AdguardTeam/AdguardForiOS#396]
If you use the Opera VPN App Adguard doesnt work.
You can test this with this Website:
http://www.pietsmiet.de/gallery/categories/9-pietsmiet/25866-blobby-volley-dennis-peter

If Opera VPN is disabled Ads are Blocked.
If Opera VPN is activated Ads are NOT Blocked!

I dont know if this is a bug in your app or an bug in iOS...

**Comment by vozersky** [comment]
hi

Opera VPN is incompatible with local VPN of Adguard 
Check VPN app list [here](https://github.com/AdguardTeam/AdguardForiOS/issues/162), please:

**Comment by YoKoGFX** [comment]
I dont use the local VPN of Adguard...

**Comment by vozersky** [comment]
So you do use Safari browser, right? 
What iOS version do you have? 
Funny thing, I can't install Opera VPN, seems like "Install profile" button is broken
![image1-2](https://cloud.githubusercontent.com/assets/17472907/25952751/308a9f12-366a-11e7-9c78-c1b95bd5f3a7.PNG)

**Comment by YoKoGFX** [comment]
Yes, I use the Safari Browser :)
I run the latest iOS 10.3.2 Beta... But I know that this was already there before the beta.

**Comment by vozersky** [comment]
Ok, but how did you manage to install VPN profile for it? Tried to do it on three different devices already, doesn't work :)

**Comment by YoKoGFX** [comment]
After clicking on the Button a Box will pop up :/

![img_0387](https://cloud.githubusercontent.com/assets/18743976/25953234/0dd9bacc-3663-11e7-856f-dc4c6cb82c7c.PNG)

**Comment by vozersky** [comment]
![image](https://cloud.githubusercontent.com/assets/17472907/25953578/83f4f100-366c-11e7-9d46-099edb7ae4ed.png)

**Comment by YoKoGFX** [comment]
:/ It works on all 3 Devices I have...

**Comment by vozersky** [comment]
It looks like you are the lucky one :)
It's four devices and counting. Reported to OperaVPN devs.

**Comment by vozersky** [comment]
Let's wait for the fix and test it when it becomes possible.

**Comment by zebrum** [comment]
@YoKoGFX hi!

ad blocking in opera VPN now is a paid function. Do you use it?

**Comment by YoKoGFX** [comment]
@zebrum Hello,

nope, I sold my iPad and bought an Surface :D

**Comment by zebrum** [comment]
ok
then I'm closing it.
