### ISSUE TITLE
System-Wide and Additional VPN Not Working Correctly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#397]
**Issue description:**
https://forum.adguard.com/index.php?threads/system-wide-and-additional-vpn-not-working-correctly.21646/

What can be done about it?

**Comment by vozersky** [comment]
Yes, it looks like we do override 3rd party app's DNS settings

**Comment by vbagirov** [comment]
To make the future searches easier, the VPN in question here is Windscribe VPN.

**Comment by IvanIin** [comment]
on 1.3.0(100) in split mode works fine
