### ISSUE TITLE
Crash in the latest beta 1.2.1 (71)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#398]
Details:
https://forum.adguard.com/index.php?threads/adguard-pro-beta-crash-info-german.21682/

@Stillness-2 please check if any new crashes were reported to us through itunesconnect.
Issue description and name should be updated accordingly once we find the crash data.

**Comment by i0s1q** [comment]
Thanks :-)

**Comment by jo2dan23** [comment]
Can this be closed?
