### ISSUE TITLE
Adguard Pro 1.2.1 is broken on iOS 9.3.3

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#399]
The original post:

> Since the release of the new version with system wide ad blocking, I have been unable to use the program. I set it up, as usual, follow all the instructions correctly. Everything is perfectly set up the way it should be (double checked). I am a sysadmin and have set up VPNs for people many times. Obviously, this is a bit different, but I just wanted you to know I know what I'm looking at. As soon as the program is closed, the VPN is shut off as well. I understand that the VPN isn't a true VPN and more of a loopback, but this is truly not working. I've tested it on sites with ads when it is on and when it is off and there is a difference. I'm using an iPhone 6+ on iOS 9.3.3 at the moment. If the issue is that the new app only works on iOS 10 and above, I was not aware of that and I apologize. Just today I tried the updated new version of 1.21 which fixed a bug but had the same issue. For the moment, I've reverted to the old version 1.15.

**Comment by Stillness-2** [comment]
#384

**Comment by evgeniy-ADG** [comment]
The fact it's closed confused me, sorry.
