### ISSUE TITLE
Translation for "user filter" to Chinese is Wrong

### ISSUE THREAD

**Issue by nicedavid0629** [AdguardTeam/AdguardForiOS#400]
"个人配置" or "自定义规则" would be better. "使用过滤器" in the app means "Use Filter" in English actually.

**Comment by vozersky** [comment]
@vbagirov @altokarev

**Comment by vbagirov** [comment]
@nicedavid0629 Changed to "自定义规则". By the way, we have more similar phrases (like "您正在使用过滤器的最新版本。") in other products (Android, Windows, Mac etc) and I am not quite sure how to fix them. It would be great if you could help us maybe? 

If you are interested, please read this article: https://blog.adguard.com/en/adguard-public-translations/

**Comment by nicedavid0629** [comment]
@vbagirov Thank you and I am glad to do this. But here is a problem when I was trying to register an translator account on OneSky: 
"Thanks for your interest in becoming a OneSky translator! However, our registration is temporarily closed. Please come back later and try again." 
Should I try later or have any idea what else I can do? Thanks.

**Comment by vbagirov** [comment]
@nicedavid0629 I believe you can log in using your GitHub account. Will it work?

**Comment by nicedavid0629** [comment]
@vbagirov Got the account. I'll catch up with this later. it's pretty later here in China. Have to sleep though. Good day!

**Comment by vbagirov** [comment]
@nicedavid0629 sure! Two more things: 

1. If you suggest any changes, please leave a comment to that phrase, so we get the alert. 
2. Volunteering is nice and all, but we really would like to give you a small present if you end up making a significant contribution to translating Adguard - hook me up (preferably, via [Adguard forums](https://forum.adguard.com/index.php?members/3788/))
