### ISSUE TITLE
System crash on Mac 

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForiOS#401]
System crash on Mac 
Mac OS 10.12
![image](https://cloud.githubusercontent.com/assets/25711093/26519364/b062b66a-42c8-11e7-95ae-fe0e4b707010.png)
CustomerID: 1510104
[state.txt](https://github.com/AdguardTeam/AdguardForiOS/files/1033379/state.txt)
[debug (97).txt](https://github.com/AdguardTeam/AdguardForiOS/files/1033380/debug.97.txt)

**Comment by Michael23456** [comment]
what do we need to ask?

**Comment by evgeniy-ADG** [comment]
@Michael23456 why iOS repository?

**Comment by Michael23456** [comment]
can be closed, moved here https://github.com/AdguardTeam/AdguardForMac/issues/201
