### ISSUE TITLE
 http://edition.cnn.com/2017/05/30/politics/russians-trump-campaign-information/index.html - incorrect Adguard interface

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardForiOS#403]
Description: http://edition.cnn.com/2017/05/30/politics/russians-trump-campaign-information/index.html - incorrect Adguard interface

Current behaviour: Adguard Assistant bar is not centered on this site
Screenshot: https://prnt.sc/fe39si

System configuration

Application version: 1.2.2.81
Platform: iOS
OS: 10.3.3
Optimized enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.78 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.51 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.94 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.42 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.50.49 Enabled=NO
ID=6 Name="German filter" Version=1.0.34.44 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.93.6 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.8.53 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.39 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.63 Enabled=NO
ID=101 Name="EasyList" Version=1.0.70.48 Enabled=NO
ID=219 Name="ChinaList+EasyList" Version=1.0.2.83 Enabled=NO

Ticket ID(if exists): 1322540

**Comment by zebrum** [comment]
reproduced

**Comment by vozersky** [comment]
obsolete
