### ISSUE TITLE
$elemhide exclusion disable url blocking (1.22 86, iOS 10.3.3)

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#405]
https://github.com/AdguardTeam/AdguardFilters/issues/5265
How to reproduce:
- for example, open giga.de;
- leave only English filter and disable Pro/systemwide filtering;
- look for blocked requests in Safari console. They are exist.
Next step:
- add `@@||giga.de$elemhide` and refresh the tab;
- look in console - no blocked requests.

**Comment by Alex-302** [comment]
@vozersky or @zebrum Please check it.

**Comment by ameshkov** [comment]
@Mizzick is it intended for the $elemhide rules?

**Comment by Mizzick** [comment]
`$elemhide` rules will unblock all css-blocking rules.
Try to add some url-blocking rule, it should not be blocked.
