### ISSUE TITLE
Add build number to About screen

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#406]

**Comment by worldsdream** [comment]
Yes please

**Comment by ameshkov** [comment]
@IvanIin isn't it done already?

**Comment by IvanIin** [comment]
@ameshkov Already done and will be added to the next version of the application

**Comment by worldsdream** [comment]
@ivanlin, are you also a ios dev for adguard?

**Comment by IvanIin** [comment]
@worldsdream yes
