### ISSUE TITLE
Consider writing tunnel logs all the time, not just when DNS requests logging is enabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#409]

**Comment by jo2dan23** [comment]
I think this can be disabled in next beta. Seems it slows down the internet

**Comment by ameshkov** [comment]
> I think this can be disabled in next beta. Seems it slows down the internet

Frankly, that's odd, writing tunnel log shouldn't slow down anything (it's like a 1ms overhead max).

@jo2dan23 could you please be more specific about it? How does it look like?

**Comment by jo2dan23** [comment]
This can be closed now i think, since it will be disabled in next beta

**Comment by ameshkov** [comment]
It actually won't. The current slowdown is caused not by writing the tunnel log file, but with passing all the information to the application process (as if you had "DNS requests logging" enabled all the time).

**Comment by planet0** [comment]
I just noticed the Filtering Log has stopped logging anything from a certain point since a few days ago… I think since 1.2.2 (92) was released on TestFlight. I mention it here as I have the Filtering Log disabled but Adguard was logging it anyway in the previous build (89).

**Comment by ameshkov** [comment]
> I have the Filtering Log disabled but Adguard was logging it anyway in the previous TestFlight build (88).

Yeah, that was a bug actually. AG should write logs to the file, but it shouldn't have bothered the filtering log UI.

**Comment by jo2dan23** [comment]
Is this maybe why wifi disconnects are happening? Or was advanced logging disabled

**Comment by ameshkov** [comment]
> Is this maybe why wifi disconnects are happening? Or was advanced logging disabled

Very-very unlikely
