### ISSUE TITLE
MyDealz - redirect doesn't work with VPN enabled 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardForiOS#410]
MyDealz app - when you click on "See the deal" it redirects you to the official website, but the page cannot be loaded 
link to the app: https://itunes.apple.com/de/app/mydealz-gutscheine-schnäppchen-sale-angebote/id463557271?mt=8 

<details>

![image](https://user-images.githubusercontent.com/23372054/27122188-a87e58e0-50f2-11e7-8d73-91d2eaa9371f.png)

![image uploaded from ios](https://user-images.githubusercontent.com/23372054/27122032-2b59de84-50f2-11e7-9ab5-bc7319b366c6.jpg)

</details> 

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.3

Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.21.5 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.69 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.17 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.13.90 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.1.5 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.52.1 Enabled=NO
ID=6 Name="German filter" Version=1.0.34.82 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.65 Enabled=NO
ID=5 Name="Experimental filter" Version=1.0.26.61 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.8.71 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.47 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.71 Enabled=NO
ID=107 Name="EasyList Germany" Version=1.0.63.39 Enabled=NO
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.3.68 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.81.69 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=229 Name="I don't care about cookies" Version=1.0.0.13 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.81.57 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=NO
ID=210 Name="Spam404" Version=1.0.1.80 Enabled=NO
ID=237 Name="AdBlock Protector List (Incompatible with Adguard)" Version=1.0.0.38 Enabled=NO

Ticket ID 544841

**Comment by vozersky** [comment]
test plz @zebrum

**Comment by zebrum** [comment]
yes, it blocked by System-wide ad blocking. 

That's why all cashback and coupons\discount services ask to disable adblock apps and extensions )
