### ISSUE TITLE
Mobile network not using selected dns (problem started on build 1.2.2 (88)

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#411]
I used a dns leak test and it looks like all along open dns isnt even being used as my default dns for mobile network?

**Comment by ameshkov** [comment]
And what's used instead? The ISP's DNS?

Could you please send a log for us to check? Reproduce the issue and send the log right after

**Comment by jo2dan23** [comment]
Yeah. I assume. On wifi when i do it it shows opendns. On mobile it shows my carrier. In the log it shows the server is opendns but not on dns leak site.

**Comment by jo2dan23** [comment]
What log do you need

**Comment by ameshkov** [comment]
> What log do you need

Tunnel log.

> On mobile it shows my carrier. In the log it shows the server is opendns but not on dns leak site.

I wonder, could it be that your ISP intercepts DNS requests?

**Comment by jo2dan23** [comment]
https://1drv.ms/u/s!AvccVnEjavPPh08alBsrFRZu_WdB

So maybe i cant change what dns is used then :(

**Comment by ameshkov** [comment]
> So maybe i cant change what dns is used then :(

It might be inspecting it, but it does not mean they ignore the OpenDNS response.

What does this page show?
https://welcome.opendns.com/oops/

**Comment by jo2dan23** [comment]
![img_0017](https://user-images.githubusercontent.com/15130139/27262656-0853085c-5421-11e7-8ffe-3f6888330986.PNG)

**Comment by jo2dan23** [comment]
I wonder if its even working at all on other carriers

**Comment by jo2dan23** [comment]
Oh. I think you meant https://welcome.opendns.com/

I just tried that one and same result

**Comment by jo2dan23** [comment]
I can confirm this is a adguard problem. I used express vpn and my dns servers are using theirs not my phone carriers servers.

**Comment by jo2dan23** [comment]
So that means that all along adguard dns switching didnt work for mobile networks?

**Comment by jo2dan23** [comment]
@planet0 Can you reproduce this on your mobile network? I also tried using adguard dns server and it still doesnt override my carriers dns.

Go here: https://hidester.com/dns-leak-test/

**Comment by ameshkov** [comment]
> I can confirm this is a adguard problem. I used express vpn and my dns servers are using theirs not my phone carriers servers.

The situation is different in their case as your traffic (including DNS traffic) is being encrypted.

**Comment by ameshkov** [comment]
ISP does not intercept it, the issue appears to be pretty complicated.

**Comment by ameshkov** [comment]
@jo2dan23 let's check if DNS hijacking is present just in case.

I suggest trying to trick your ISP by using non-standard DNS port. We'll be able to do it once #412 lands.

**Comment by ameshkov** [comment]
Relevant discussion:
https://forums.developer.apple.com/thread/35027

We'll try to change the configuration of our VPN tunnel, make it a primary interface.
I am afraid that it may influence compatibility with other VPN apps -- we should re-test it.

**Comment by jo2dan23** [comment]
Ok sounds good just let me know what to change and ill do it

**Comment by jo2dan23** [comment]
I didnt know you can use other vpn apps along with adguard. Ill download one of them to test it for you when next beta is released. Just let me know what I should be looking for.

**Comment by ameshkov** [comment]
Here you can find the list: #162

**Comment by jo2dan23** [comment]
Ok. Logging will be disabled in next beta i assume and blacklist problem will be fixed? When i update to next beta what do I change in the dns settings for the proctol

**Comment by ameshkov** [comment]
Three key things to test:

1. This one with using custom DNS on mobile network.
2. The issue #404 should be re-tested as the changes are quite major.
3. Compatibility with third-party VPN apps.

**Comment by jo2dan23** [comment]
It seems like i cant use vyprvpn on ios 10.3.3 public beta 3. Even with adguard vpn turned off.. lol.

**Comment by jo2dan23** [comment]
Ok something must have changed in 10.3.3 i cant use like any vpn apps even by themselves

**Comment by jo2dan23** [comment]
Am on build 1.2.2(87) custom dns works on mobile.....

**Comment by jo2dan23** [comment]
So whatever happened between 87 and 88 is what broke custom dns

**Comment by jo2dan23** [comment]
@ameshkov did we find out what changed between the two builds? I didnt get the option for build 89 yet

**Comment by jo2dan23** [comment]
Custom dns still broke on latest beta

**Comment by jo2dan23** [comment]
@ameshkov can we revert whatever we did in build 88? Thats what broke it

**Comment by ameshkov** [comment]
@jo2dan23 have you tried the build 92 (with `Full-Tunnel` mode)?

Meanwhile, @IvanIin will check what's the difference between 87 and 88.

**Comment by jo2dan23** [comment]
Yea. Using full mode atm. Still broke unfortunately.

**Comment by ameshkov** [comment]
@jo2dan23 we need tunnel log again and exact time when it happened.

**Comment by jo2dan23** [comment]
What do you mean? Its just broken period. Or is this the wrong issue you commented on?

**Comment by ameshkov** [comment]
> What do you mean? Its just broken period. Or is this the wrong issue you commented on?

It works completely okay on our side and full tunnel mode should've fixed it for you.

As it didn't, we need to examine log file and look for a reason there.

**Comment by jo2dan23** [comment]
If i go to welcome.opendns.com it says im not using it. But on build 87 it does say im using it. I dont get how it works for you guys. Heres the log. Between 11:20-11:22 am 

https://1drv.ms/u/s!AvccVnEjavPPh2wjnHX1_Arl5FTb

**Comment by jo2dan23** [comment]
@ameshkov if you go to welcome.opendns.com it says you are using opendns on mobile network?

**Comment by planet0** [comment]
@jo2dan23 Try setting the DNS to Adguard DNS and then checking it on the [Adguard DNS page](https://adguard.com/en/adguard-dns/overview.html).

With OpenDNS and Adguard DNS, I’d also try an extended [DNS Leak Test](http://dnsleaktest.com) (different website than the one you posted earlier) on the iOS device and posting a screenshot of your results here.

**Comment by planet0** [comment]
@jo2dan23 Selecting OpenDNS on Adguard Pro with build 92 and having it on Full-Tunnel mode makes the Welcome OpenDNS page work fine on Mobile and Wi-Fi. So the Adguard Team need to figure out why it’s still not working for you.

**Comment by jo2dan23** [comment]
@planet0 i tried adguard dns and it still says its using my mobile isp 🙁

**Comment by planet0** [comment]
@jo2dan23 Try OpenDNS again and post a screenshot from the extended DNS Leak Test here to see the results.

**Comment by jo2dan23** [comment]
![img_0604](https://user-images.githubusercontent.com/15130139/27655902-a55539f2-5c0c-11e7-94a9-f10fbabb9f49.PNG)

**Comment by planet0** [comment]
@jo2dan23 Hmm. 😟 That is really bizarre.

I discovered this page for an iOS App that also changes DNS, they mention Verizon hijacking DNS and forcing it to go through their DNS no matter what the user has set: https://www.dnsoverride.com/dns-hijacking-by-some-mobile-isp/

Might be useful to see @ameshkov?

**Comment by jo2dan23** [comment]
Ok this is odd. I never saw this betore on the other dns leak test. Im back on build 87 and 2 of the servers are still using verizon.
![img_0605](https://user-images.githubusercontent.com/15130139/27656432-8d272e92-5c0e-11e7-9f6f-12e7c8e00de6.PNG)

**Comment by jo2dan23** [comment]
Wtf. Ok so on build 92 on split tunnel mode opendnsworks. But again still using 2 of my isp servers
![img_0606](https://user-images.githubusercontent.com/15130139/27656624-42dc538e-5c0f-11e7-91d4-d74deb10c050.PNG)

**Comment by planet0** [comment]
@jo2dan23 Would you be willing to reset your Network settings on your iPhone and then only launching Adguard Pro to see if that helps with this? You’d lose Wi-Fi and mobile network settings/credentials, however.

Settings > General > Reset > Reset Network Settings

**Comment by jo2dan23** [comment]
Ok i dont think this is fixable. I just did that and now it's only using verizon for my dns server on split and full tunnel

**Comment by planet0** [comment]
@jo2dan23 I’m out of ideas. Wish there was a way to know why. I’ll stay subscribed to see what happens, hopefully the Adguard team can perhaps find a way around the DNS hijacking or whatever the cause is.

**Comment by jo2dan23** [comment]
I think dns on mobile is finally fixed! All servers it using now is opendns. No verizon servers.

**Comment by ameshkov** [comment]
@jo2dan23 thank you for checking it!
