### ISSUE TITLE
Support custom ports in the custom DNS settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#412]
Currently, it accepts IP addresses only when you set up a custom DNS.

I think we should also support `IP:port` syntax just in case.
It should be optional, though.

![img_0001](https://user-images.githubusercontent.com/5947035/27279617-dcd57a0c-54ed-11e7-8662-7deed9d16495.png)

**Comment by jo2dan23** [comment]
Can this be closed?

**Comment by ameshkov** [comment]
@jo2dan23 why, it's not yet done
