### ISSUE TITLE
tieba.baidu.com - Adguard toolbar is missing

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardForiOS#416]
It is impossible to block any content on this website.

https://tieba.baidu.com/f?kz=4922758683&mo_device=1&ssid=0&from=1099b&uid=0&pu=usm@0,sz@1320_2001,ta@iphone_1_10.3_3_603&bd_page_type=1&baiduid=2088DDD58EC6C0819373B7D3A69D9431&tj=www_normal_7_0_10_title?pn=0&

<details><summary>Screenshot:</summary>

![screen shot 2017-06-21 at 7 46 36 pm](https://user-images.githubusercontent.com/27292111/27396008-70192ade-56ba-11e7-8893-1c162ee8aba9.png)

</details>

Ticket ID: 530630

**Comment by vozersky** [comment]
it's not completely missing, but it misbehaves, confirmed

![image](https://user-images.githubusercontent.com/17472907/27437259-645143de-576a-11e7-8003-5f1f8a7a964e.png)

@Stillness-2 @IvanIin  please take a look

**Comment by IvanIin** [comment]
fixed
