### ISSUE TITLE
zhihu.com - Unable to block the element 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardForiOS#417]
https://www.zhihu.com/question/61235998/answer/185699818?utm_campaign=weeklydigest261&utm_source=weekly-digest&utm_medium=email.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/27400747-c6f22144-56c9-11e7-8968-26a5a54438ec.png)

</details>

Ticket ID: 530630

**Comment by vozersky** [comment]
confirmed, @Stillness-2  @IvanIin  please take a look

**Comment by vozersky** [comment]
@veronikasav This is how [Content Security Policy](https://en.wikipedia.org/wiki/Content_Security_Policy) works on this website, it is not possible to inject the blocking tool with iOS app

**Comment by Galel** [comment]
Some other ways for cleaning ads on this site?

**Comment by vozersky** [comment]
@Galel sure, we can make filtering rules for it, if some ads are not blocked
please create an issue in [Adguard Filters](https://github.com/AdguardTeam/AdguardFilters/issues/new) repository and we will fix it

**Comment by Galel** [comment]
Thanks for your timely replay, look forward to it

**Comment by Galel** [comment]
Ads are anywhere on this site:




I don't have a filter list on this site for adguard cannot be launched.

**Comment by dzamyshlyayeva** [comment]
@Galel we've filled the task in Adguard Filters repository 
https://github.com/AdguardTeam/AdguardFilters/issues/5448
