### ISSUE TITLE
Adguard does not work properly on iOS 11

### ISSUE THREAD

**Issue by mspublic** [AdguardTeam/AdguardForiOS#418]
When trying to enable filters such as spyware or annoyances an error pops up saying "Filters cannot be loaded into Safari. Therefore, your recent changes were not applied." The only filter currently enabled is English.

**Comment by vozersky** [comment]
@mspublic here's ios11 discussion: https://github.com/AdguardTeam/AdguardForiOS/issues/407

**Comment by raubreywhite** [comment]
Hi, I am on the latest iOS with an iPhone X and this error is back.

**Comment by ameshkov** [comment]
@raubreywhite restart the Safari, it should solve the issue.

The original cause for it is the filters size #550 -- it means we need to compress filters more to avoid it completely.
