### ISSUE TITLE
Adgaurd Pro won't block any ads using dns

### ISSUE THREAD

**Issue by fwzmhmd** [AdguardTeam/AdguardForiOS#419]
Also on safari with content blocker on it won't block any youtube ADs.

Phone: iPhone 5s
Version: 9.3.1

**Comment by jo2dan23** [comment]
Which apps specifically? And is it on wifi or mobile? What adguard version

**Comment by fwzmhmd** [comment]
Apps like youtube, most games that have ads games. Using the latest adgaurd version.
  
  
  
 Thanks,  
Fawaz Mohamed
  
  
  
  

  
  
>

**Comment by vozersky** [comment]
Hi! As it stated in the [description](https://itunes.apple.com/us/app/AdGuard%20Pro%20-%20adblock%20and%20privacy%20protection/id1126386264):

> System-wide filtering and DNS ad blocking, which Adguard Pro uses, can do a lot, but not everything. Unfortunately, in some apps ads will go through. List of such (currently known) apps:
> 
> - YouTube
> - Facebook
> - Twitter
> - Instagram

If there are some other specific apps you've seen ads in, please report to [Adguard Filters](https://github.com/AdguardTeam/AdguardFilters/issues) repo and we will try to fix it.
