### ISSUE TITLE
Adguard vpn disconnects

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#420]
My vpn randomly disconnects sometimes even on wifi. Does it have to do with the advanced logging overloading the memory?  Im on latest adguard beta 1.2.2 (88)

**Comment by jo2dan23** [comment]
Just happened. What log would help? It happened between 6:08 and 6:09 pm and reconnected at 6:10 just for notes when i upload

**Comment by vozersky** [comment]
If there are no connections to filter VPN icon can disappear, this is how "VPN on demand" works

**Comment by jo2dan23** [comment]
Yeah but my wifi turns off also

**Comment by jo2dan23** [comment]
Myswell close this. Its probably because the memory gets overloaded from advanced logging. If need be ill reopen
