### ISSUE TITLE
Unprofessional translation Adguard Pro German AppStore 

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardForiOS#421]
In the German iOS App Store the title of Adugard Pro is totally wrong translated (e.g. AdGuard instead of Adguard and so on). This doesn’t make a professional overall experience. Also the description is full off translation errors. I have updated the description on OneSky.

![img_1283](https://user-images.githubusercontent.com/25068100/27517515-1cad9d6e-59ce-11e7-9e97-a087ca9203d7.jpeg)

![img_1662](https://user-images.githubusercontent.com/25068100/27517525-5afbb84e-59ce-11e7-8d1e-1b2ba8b3cb1f.jpg)

**Comment by sergerosenthaler** [comment]
Also with version 1.3.0 the App title and the description in the App Store are badly translated into German

**Comment by vbagirov** [comment]
@sergerosenthaler in the near future there will be probably another version with a different title. We will use this chance to fix the mistakes in the description.
