### ISSUE TITLE
Adguard vpn disconnecting 1.2.2 (92)

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#424]
What logs will help?

**Comment by vozersky** [comment]
just the regular tunnel log
you can send it through the app (send bug report)
please reproduce the problem and specify the time when it happened, if possible

**Comment by jo2dan23** [comment]
It seems like its not disconnecting anymore.. it might be because i was blocking this certain apple domain. But custom dns on mobile network is still broke i didnt know if i should make a new issue for that or what

**Comment by jo2dan23** [comment]
Im reopening. I just got the disconnect on wifi. Uploading log now

**Comment by jo2dan23** [comment]
Disconnect happened between 10:53-10:56 am

https://1drv.ms/u/s!AvccVnEjavPPh2tvis6J2rdutOY3

**Comment by jo2dan23** [comment]
I looked through the log and i myself dont see anything useful... I hope someone else can reproduce

**Comment by jo2dan23** [comment]
Wifi just disconnected again. Between 2:50-2:53 pm. I hope im not the only one @ameshkov

**Comment by jo2dan23** [comment]
Here is the log. Doubt it will help tho. https://1drv.ms/u/s!AvccVnEjavPPh225xILKLuPnq1m7

**Comment by jo2dan23** [comment]
Ive had about 5 or more wifi and vpn disconnects today. Something is very wrong. I don't understand how i am the only one reporting on this issue

**Comment by jo2dan23** [comment]
How am i the only one having this? I tried split tunnel and still getting disconnects

**Comment by jo2dan23** [comment]
@ameshkov could it be that im on ios 10.3.3 beta? I remember we had this problem before you said it was the memory running low. It happens about every 30 minutes maybe

**Comment by jo2dan23** [comment]
I wouldnt release this in app store till problem is solved. Alot of users will be complaining. Here is the issue i posted before u told me it was ios killing it because of low memory. https://github.com/AdguardTeam/AdguardForiOS/issues/333

**Comment by jo2dan23** [comment]
Been on build 86 for 2 hours. No wifi disconnect. Definitely a adguard issue

**Comment by ameshkov** [comment]
> I wouldnt release this in app store till problem is solved.

Sure, we won't until all the problems are resolved.

**Comment by jo2dan23** [comment]
None of my logs helped. I went through them all. So i just deleted them. But another thing id like to mention, on full tunnel or split an ad got through a couple times on a app called whisper that I use. Idk if its low memory or whats going on. It happened on wifi. And i was right next to my router

**Comment by jo2dan23** [comment]
Im guessing someone was able to reproduce? 🙂 Hopefully?

**Comment by jo2dan23** [comment]
I think this bug is finally fixed!

**Comment by jo2dan23** [comment]
Just when I thought it was fixed... my wifi disconnected :(

**Comment by jo2dan23** [comment]
@ameshkov I assume this is ios killing adguard? I wish someone else besides me could comment on this and reproduce

**Comment by jo2dan23** [comment]
This morning wifi was turning off about every 15 minutes or less. So it has to be ios killing it

**Comment by ameshkov** [comment]
That's likely to be iOS indeed, let's wait for @IvanIin to comment on this.

Just in case, it'd be better if you attach the log with the latest build, we now print more information there, it might be helpful. Along with the log we need to know when exactly did it happen last time.

**Comment by jo2dan23** [comment]
What log do you need? I just had wifi disconnect again. Between 12:38-12:40 pm for note

**Comment by ameshkov** [comment]
@jo2dan23 tunnel log at least. If you can extract iOS system log, that'd be ideal

**Comment by jo2dan23** [comment]
Can i still get the system log even tho i wasn't plugged into my pc at thetime? Or should i plug my phone into my pc and wait til it disconnects again from wifi? I need the link again where it shows how to grab it

**Comment by jo2dan23** [comment]
here is the system log. i hope it helps. because it was plugged in while it crashed and the time it crashed isnt even in the log. :(

https://1drv.ms/t/s!AvccVnEjavPPh3cXZ5rzFECZkEyN

**Comment by jo2dan23** [comment]
i see alot of these in the log: iPhone ProTunnel(NetworkExtension)[751] <Error>: NEVirtualInterface Failure in NEVirtualInterfaceWriteMultipleIPPackets at line

**Comment by ameshkov** [comment]
@jo2dan23 and tunnel log? We could compare with the system and find out what we were trying to do at that moment

**Comment by jo2dan23** [comment]
Im suprised nobody else is getting this. Must be ios 10.3.3 beta. There really isn't anything specific that causes it to crash. Its literally every 30-35 mins. Every time. My guess is the log is getting overloaded by something.

**Comment by jo2dan23** [comment]
Then again. Build 86 didn't crash... so maybe it is adguard? Its very annoying.

**Comment by jo2dan23** [comment]
@ameshkov @vozersky @IvanIin 
ok. got the logs this time! i edited out all the unimportant info. so it starts where adguard disconnected and then shows when it reconnects. all the stuff before and after that wasnt useful.

SYSTEM LOG: https://nopaste.me/view/raw/3c6a2c50
TUNNEL LOG: https://nopaste.me/view/raw/9b3fdb6f

**Comment by jo2dan23** [comment]
Ok so i have been on split tunnel for about 35 minutes. No disconnects. So only full tunnel disconnects now. Maybe thats why Nobody else has found this issue.

**Comment by jo2dan23** [comment]
Nvm. Ugh. I just got the disconnect. Im going to have to switch back to 86 i guess :(

**Comment by jo2dan23** [comment]
Any news on this? Hope it can be fixed in next beta.

**Comment by IvanIin** [comment]
I reproduced the bug with the missing wifi on the ipad mini with iOS 11.
How to reproduce:
1) in the VPN Settings disable ondemand
2) turn on VPN
3) turn off and turn on the wifi
VPN itself turns off
4) turn on VPN from the system settings

As a result, the wifi is disabled

The problem was solved experimentally. I removed ip address 0.0.0.0 from the exсluded routes. As a result, a vpn icon appeared on status bar, as it should work. And wifi began to work.
It looks like it's ios bug.

**Comment by jo2dan23** [comment]
Im guessing you meant to comment on a different issue? Do you mean the wifi disconnecting every 30 minutes?

**Comment by jo2dan23** [comment]
On latest beta. It took 18 minutes to be exact this time for vpn to disconnect. So now it disconnects even faster than before.

**Comment by jo2dan23** [comment]
I waited 35 minutes and vpn didn't disconnect in split mode. What was fixed in split mode that wasn't fixed in full mode?

**Comment by jo2dan23** [comment]
Split tunnel just disconnected. This is very frustrating.

**Comment by jo2dan23** [comment]
Apparently im the only one having this problem so i myswell just close this

**Comment by ameshkov** [comment]
@jo2dan23 let's keep it open, we may find a solution eventually

**Comment by IvanIin** [comment]
@jo2dan23 could you try to turn off wifi-assist in phone settings->Mobile Data and check this issue?

**Comment by jo2dan23** [comment]
Wifi assist was turned off when i setup ios 10

**Comment by IvanIin** [comment]
fixed

**Comment by sakhi-sl** [comment]
How was it fixed?

**Comment by Versty** [comment]
@sakhi-sl Hi! 
This bug is old enough. If you encountered the same or related issue, I suggest you create a [new discussion](https://github.com/AdguardTeam/AdguardForiOS/issues/new/choose).
