### ISSUE TITLE
"Tunnel Mode" in "Advanced settings" not translated to German 1.2.2 (92)

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardForiOS#425]
Only as a reminder: The German translation is not up to date, OneSky has been updated.

![img_1669](https://user-images.githubusercontent.com/25068100/27621418-e9c8fdd0-5bd0-11e7-8821-5a5a6375bd60.PNG)

**Comment by ameshkov** [comment]
Thank you!

I've filed a reminder issue about updating all the translations:
https://github.com/AdguardTeam/AdguardForiOS/issues/427
