### ISSUE TITLE
Full-Tunnel mode leads to no internet on cellular data

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#426]
Got a report from beta tester.

**Comment by vozersky** [comment]
can't rep on ios10, could have to test on 11
could this be an ipv6 issue?-

**Comment by ameshkov** [comment]
Just guessing, but it might be caused by switching from an IPv4-only network (wi-fi in user's case) to an IPv6-enabled network.

**Comment by ameshkov** [comment]
Follow-up: the issue happens randomly, so don't expect to reproduce it right away.

**Comment by ameshkov** [comment]
@IvanIin logs here: 1582520

**Comment by jo2dan23** [comment]
Im having a similar situation. Not exactly tho. Idk if i should make another issue for this. But i just got home and have wifi switch on if i go to settings it says im on wifi but in the wifi settings my IP address is the ip of my mobile isp? And in the status bar it says lte also.

**Comment by ameshkov** [comment]
One more report about a similar issue:

> The new beta version for AdGuard Pro in iOS 11 is very unstable. When the full tunnel was chosen, iPhone will keep restarting  if the Wifi signal is poor.  Also, when I switched Wifi off and turned cellular data on, there was few minutes that I did not have access to the Internet.

**Comment by jo2dan23** [comment]
@ameshkov my situation is similar with the poor wifi signal part. I got ads on an app when my wifi signal was poor on full tunnel. So maybe its not fully fixed?

**Comment by ameshkov** [comment]
@IvanIin found one more problem in how full-tunnel mode operates, we'll publish one more update soon.

**Comment by jo2dan23** [comment]
@ameshkov will this fix my wifi disconnect issue?

**Comment by ameshkov** [comment]
> @ameshkov will this fix my wifi disconnect issue?

Can't say yet, didn't have time to examine the logs there

**Comment by parrot5** [comment]
I previously reported the problem of no-internet-after-leaving-WiFi, and it seems to be solved with today’s update. Tried it a few times moving out of WiFi and it switched to LTE fine.

**Comment by jo2dan23** [comment]
This can be closed then
