### ISSUE TITLE
There should be a way to report missed ads or incorrectly blocked content from Safari extension

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#43]
Add to buttons to Safari extension popup:

1. Report Missed Ad >
2. Report Incorrect Blocking >

Tapping on any of these buttons opens mail app (just like we do for "Send Bug Report").

The difference is the email subject and content.

"Subject" is equal to the button text. Something like *[Adguard for iOS] Report Missed Ad*
Mail content contains link to the webpage.

**Comment by Stillness-2** [comment]
commits: 22862, 22893
