### ISSUE TITLE
iPhone crashes when Adguard is in Full tunnel mode

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForiOS#432]
Full tunnel mode was working fine on iOS 11 in the 92 build (WiFi). In the 95 build iPhone crashes every time you tap on any app.

More details later.

**Comment by vozersky** [comment]
What does "iPhone crashes" mean? 
Definitely need more details and str, as far as I can see, apps starts correctly

**Comment by jo2dan23** [comment]
I cant reproduce. Try uninstalling app completely and reinstall. Make sure to back up your filters though to a notepad or something

**Comment by vbagirov** [comment]
I'll come back with more details once the user replies.

**Comment by jo2dan23** [comment]
Oh you're not the op. My bad

**Comment by jo2dan23** [comment]
I just realized he is using ios 11. Probably why i cant reproduce.

**Comment by vbagirov** [comment]
More info from the user: 
>So when full-tunnel mode is turned on and I am on wifi and I click on an app or or go into lets say settings for wifi it crashes the phone and then cause it to reboot. Only on LTE it looks like full-tunnel mode works with no issues so far.

> when I was on 92 I had no issues with the phone crashing on wifi in full tunnel mode but it cuts out internet connection after a period of time with no use of the phone.

**Comment by ameshkov** [comment]
@IvanIin do you see anything special in his network settings? Unknown network interfaces or anything like that?

**Comment by ameshkov** [comment]
@vbagirov please ask him to update iOS beta and check if the problem persists

**Comment by mikeoleary7528** [comment]
Hi Guys!

I was the one that reported this and has the problem. I am on ios 11 beta 3 and I think I found the issue with full tunnel mode. On LTE and wifi ipv6 I have no issues but at my jobs wifi which is ipv4 it causes my phone to crash and resets when I click on any app.  If you need any more info let me know!

**Comment by vozersky** [comment]
@zebrum test please

**Comment by zebrum** [comment]
can not reproduce it.

**Comment by vozersky** [comment]
obsolete
