### ISSUE TITLE
Implement List to Block Audio Ads

### ISSUE THREAD

**Issue by NoX1De** [AdguardTeam/AdguardForiOS#434]
Can a Adguard Pro list be added which blocks audio ads globally/system-wide?  Audio ads are arguably the MOST annoying...SoundCloud or Pandora audio ads would be great examples of this...a filter list that blocked these that is optional to enable would be PHENOMENAL!...I currently have Spyware, Social Media, Annoyances, Mobile Ads, and Safari filters all enabled with System-wide Ad blocking and using Adguard default DNS and these filters are not blocking audio ads....

**Comment by zebrum** [comment]
@NoX1De hello!
Unfortunately not all ads can be blocked by Adguard DNS in system-wide ad blocking.
And default filters in Safari content blocker block sound ads in most cases. So there is no need in another one.
About any issue with missed ads you can report directly to our support team or post it in the other repo: https://github.com/AdguardTeam/AdguardFilters/issues
