### ISSUE TITLE
[Feature request] How to hide VPN icon

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardForiOS#435]
One of the customers is wondering if it is possible to add any option to the application which will be responsible for making VPN icon in the status bar invisible (like some other applications do: AdBlock, FutureMind) since it is quite annoying.

<details><summary>Screenshot:</summary>

![screen shot 2017-07-10 at 3 34 11 am](https://user-images.githubusercontent.com/27292111/27999041-af994cce-6520-11e7-94bf-178992c35585.png)

</details>

Ticket ID: 1117269

**Comment by evgeniy-ADG** [comment]
No. Please see: https://github.com/AdguardTeam/AdguardForiOS/issues/166

**Comment by ameshkov** [comment]
@evgeniy-ADG @veronikasav in fact in the new version there is a new mode -- "Full-Tunnel", and VPN icon is hidden in that mode.

The thing is that this icon hiding is not a feature, but an iOS bug, and I cannot guarantee it will be that way always.

**Comment by planet0** [comment]
> The thing is that this icon hiding is not a feature, but an iOS bug, and I cannot guarantee it will be that way always.

That was quick. The VPN icon is now always visible again for me on Full-Tunnel since the most recent TestFlight build. Oh well :)

**Comment by XMB5** [comment]
It is possible - the app Surge can do it.

**Comment by zebrum** [comment]
@XMB5 right now there are two full tunnel mode with or without vpn icon.
