### ISSUE TITLE
Full Tunnel Mode kills Mailapp Notification

### ISSUE THREAD

**Issue by tosbsas** [AdguardTeam/AdguardForiOS#438]
iPhone 7, 10.3.3 beta 6
Full Tunnel messes with Mailapp Notifications. Mail get thru but no notification. Only Happens with Mailapp. Spark and Airmail Notifiactions get thru. 
Mailapp is set on outlook Accounts.

**Comment by tosbsas** [comment]
Split tunnel works fine

**Comment by tosbsas** [comment]
But I hate the VPN sign

**Comment by jo2dan23** [comment]
Ah. Finally found someone who uses full tunnel. Are you having wifi disconnects every 30 minutes?

**Comment by tosbsas** [comment]
No - just no Mail App notification

**Comment by ameshkov** [comment]
Guys, assigned it to 1.2.3, we'd better release 1.2.2 earlier and resolve this issue after the release.

**Comment by zebrum** [comment]
@tosbsas how it works with latest beta? do you have any other mail accounts?
I've tried to reproduce with gmail and icloud mail and it's no difference to me - with or without Adguard.

**Comment by tosbsas** [comment]
Its working now with new beta

Ruben




_______________________________

Ruben Gutknecht

Lima, Perú  🇵🇪

Cel: +51-99349-1515

Fax: 001-928-223-4243 International

Voice/Fax: 49 (0) 721-151-379204

http://telegram.me/tosbsas

paypal.me/RubenGutknecht
<applewebdata://40566043-5FAC-492D-B3D9-9F4745FD6351/paypal.me/RubenGutknecht>

Deutschland

tosbsas@gmail.com

ttosbsas@icloud.com

Von: Marie <notifications@github.com> <notifications@github.com>
Antworten: AdguardTeam/AdguardForiOS
<reply@reply.github.com>
<reply@reply.github.com>
Datum: 14. November 2017 at 11:10:42
An: AdguardTeam/AdguardForiOS <adguardforios@noreply.github.com>
<adguardforios@noreply.github.com>
CC: tosbsas <tosbsas@gmail.com> <tosbsas@gmail.com>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Betreff:  Re: [AdguardTeam/AdguardForiOS] Full Tunnel Mode kills Mailapp
Notification (#438)

@tosbsas <https://github.com/tosbsas> how it works with latest beta? do you
