### ISSUE TITLE
Adguard DNS server is unreachable

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#439]
Reported by @jtb1234:
https://github.com/AdguardTeam/AdguardForiOS/issues/404#issuecomment-313685670

According to the log, packets to AG DNS are dropped.

@IvanIin the question is how can we troubleshoot it? Is there any simple way to check connectivity from an iOS device?

**Comment by IvanIin** [comment]
You can install the NSLookup application. Set DNS server 176.103.130.130 and try to get an address for google.com

**Comment by jtb1234** [comment]
I'm on the latest beta and everything seems ok other than switching between wifi and cell data takes a very long time and the LTE icon doesn't show up when switching from wifi to LTE.

**Comment by jtb1234** [comment]
If anyone is still following this topic is seems that everything is working as it should now.

**Comment by ameshkov** [comment]
Good, thank you!
