### ISSUE TITLE
System-wide stops filtration in split-tunnel mode

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForiOS#440]
Trying to imitate poor connection.
Settings:
- Adguard 1.2.2(96)
- Split-Tunnel
- another VPN running
- System-wide Ad blocking enabled, DNS system default
### Steps to reproduce

1. turn on and off flight mode several times
2. after that change internet connection type (e.g if wi-fi was turned on, turn it off so system can reconnect to mobile network)
3. run chrome browser and load any page

### Expected behavior

filtration is working, no ads
### Actual behaviour

filtration is not working 

It happens not every time, so STR are approximate.

time in logs 15.38 and 16.15:
[logs.zip](https://github.com/AdguardTeam/AdguardForiOS/files/1148541/logs.zip)

### Your environment

* Device model and storage size:  iPhone 6s
* Operating system and version: 10.3.2
* Browser Chrome
* Wi-fi \ mobile internet connection

**Comment by jo2dan23** [comment]
If your connection is poor, the system bypasses adguard vpn and allows ads through. Try using full tunnel once see if that helps

**Comment by zebrum** [comment]
obsolete
