### ISSUE TITLE
Opening the app does not check for updates automatically

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#441]
Is this something new? 

When we open the app, it did check for filter updates automatically. I saw it spinning. Now i have to scroll and click on check for updates.

**Comment by ameshkov** [comment]
It actually does check for updates silently (in case if filters are expired)

**Comment by worldsdream** [comment]
I opened the app right now. Cold startup. It's not updating. 

I clicked on check for filter updates. Some filters got updated. 

Didn't it check automatically when we loaded the app up?

**Comment by ameshkov** [comment]
> I opened the app right now. Cold startup. It's not updating.

Filters are considered expired if they were not updated for 24 hours (or 48, I don't remember exactly).

**Comment by worldsdream** [comment]
24h
