### ISSUE TITLE
[Feature request]  - A synchronizing feature in Adguard

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardForiOS#442]
### Expected behavior

One of the customers uses the app on his iPad and iPhone and the Safari browser extension on his
Mac. He likes to have all three installs configured the same, but now he
has to manually add all the sites to the whitelist three times.

Will it be possible to synchronize all devices in future?

### Customer ID 
1593806

**Comment by ameshkov** [comment]
Yes, we're working on this already. Closed as duplciate
