### ISSUE TITLE
Feature: show warning that you need to enable in safari

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#443]
Hi,

A friend of mine installed adguard and told me why he is still seeing ads. I told him did you enable filters correctly? He said: yes. I told him. Reinstall again. Reboot phone. But on the end, he did not enable it in phone settings>safari>content blocker>adguard enabled. 

Now what I am saying is: is it possible that if you open adguard and you have not enabled the adguard adblocker in safari settings panel, it shows a warning in the top or any color yellow or red?

**Comment by ameshkov** [comment]
Yeah, we want to do it. 

The problem is that detection is asynchronous and may take some time. So we might need to request notifications permission in order to show such a warning.

**Comment by ameshkov** [comment]
Duplicate of #437 (almost done btw)

**Comment by worldsdream** [comment]
Great. Thanks for telling.
