### ISSUE TITLE
Why this filter here? That filter is incompatible with Adguard

### ISSUE THREAD

**Issue by ValidatePro** [AdguardTeam/AdguardForiOS#444]
### Steps to reproduce

1.
2.
3.
4.

### Actual behaviour

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Device model and storage size: (e.g. iPhone 6s 64gb)
* Operating system and version: (e.g. 10.3.1)
* Browser (e.g. Safari)
* Wi-fi or mobile internet connection

**Comment by ValidatePro** [comment]
I cant changr anything so, https://i.hizliresim.com/7NaMNv.png that filter is incompatible with Adguard, so why this filter in Adguard? That strange.

**Comment by ameshkov** [comment]
Removing it could harm users who've enabled it, that's why we keep it in the list (but the filter itself is empty).

**Comment by ameshkov** [comment]
Eventually, we'll remove it from the list of known filters, but we should be sure that all the apps are ready for it.
