### ISSUE TITLE
Wifi doesn't automatically switch to data 1.2.2 (97) full tunnel

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForiOS#447]
If i walk down the block wifth wifi on and dont switch it off it doesn't automatically switch to data when it is no longer connected to my wifi. Even when turning airplane mode on and off or turning wifi off wont fix it. I have to open adgUard app then turn off vpn from there otherwise it gets stuck on grey wifi signal and i cant use data

**Comment by ValidatePro** [comment]
Same.

**Comment by planet0** [comment]
This has been happening to me as well, it seems to happen both ways. (#448)

Used to work fine before build 1.2.2 (97) and still occurs with 1.3.0 (100).

**Comment by mikeoleary7528** [comment]
Same, went back to 1.2.2 (95), and haven't had any real disconnect issues so far.

**Comment by zebrum** [comment]
seems to be fixed in #448
