### ISSUE TITLE
Adguard Pro resolves to the knowledge base in wrong language

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#449]
### Steps to reproduce

1. Turn on the device
2. Launch Adguard
3. Go to the User Filter section and tap the Rules syntax button (whatever it's called in English)
4. The app opens «https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters» instead of «https://kb.adguard.com/ru/general/how-to-create-your-own-ad-filters».

### Customer ID

1137674

### Your environment

* any iOS device with the language set as Russian, region - Russia
* 10.3.3 (14G57)
* Adguard Pro 1.2.2 (97)

**Comment by IvanIin** [comment]
This is not an application error. We open the URL https://kb.adguard.com/general/how-to-create-your-own-ad-filters in a safari and the server redirects us to a localized page.
