### ISSUE TITLE
Side-loading instruction for people who wants all the functionality

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#450]
Due to #445 we'll have to remove the in-app ad blocking functionality from the Pro app. 

However, thanks to AG being open source, it is still possible for people to side-load full-featured AG Pro to their devices.

What we need to prepare:

1. Special build configuration with system-wide ad blocking functionality brought back
2. Detailed instruction on how to side-load AG

**Comment by ameshkov** [comment]
@IvanIin there's an option to use Cydia Impactor for side-loading and it does not require device to be jailbroken:

**Comment by mikeoleary7528** [comment]
Hi Guys,

You should check this out for an idea for side-loading :)

https://github.com/Sn0wCh1ld/App-Installer

**Comment by ameshkov** [comment]
@mikeoleary7528 thank you for the tip!

**Comment by ameshkov** [comment]
Hm, got a problem with the side-loading. In order to have an app using VPN API, you need to have a developer account (which costs $100/yr).

**Comment by mikeoleary7528** [comment]
The other option would be a ipa signing service like ipastore.me or appdb.store I use both and they both work great.  You could in the mean time still release any pending ipa updates and have the user figure it out?

**Comment by ameshkov** [comment]
@mikeoleary7528 I wonder how trustworthy are they?

**Comment by ameshkov** [comment]
I mean we could simply let people know that they can use appdb.cc, but how can we be sure that people can trust them?

**Comment by mikeoleary7528** [comment]
The only issue I have ever ran into with them is Apple revoking any accounts with them. And when that happened which was rarely they would resign the accounts or refund your money.

**Comment by gnarnick** [comment]
How do apps like GBA4iOS manage to by pass that requirement? Is it specifically because of the VPN API?

**Comment by gnarnick** [comment]
I've been using Impactor to install Kodi on ATV on a weekly basis with the free dev account. I can test out the .ipa if you'd like to send it to me.

**Comment by IvanIin** [comment]
@dnarnick You can try to install Adguard Pro 1.2.1
[Adguard Pro.ipa.zip](https://github.com/AdguardTeam/AdguardForiOS/files/1199854/Adguard.Pro.ipa.zip)

**Comment by gnarnick** [comment]
@IvanIin tried different methods, but nothing. Just like you stated, the VPN API is the issue. Hopefully, someone finds a solution.

**Comment by jau88** [comment]
Excuse my ignorance but why not utilise Cydia?

You can host AG using an APT repository for free through [GitHub](https://github.com/winneon/tutorial-repository) or find a repository you are comfortable with hosting the app, like the [BigBoss](http://thebigboss.org/hosting-repository-cydia/submit-your-app). 

Regarding certification, well for Jailbroken devices anyway, you can "fake" code-sign your application so it will run in iOS for free with saurik's [ldid](http://iphonedevwiki.net/index.php/Ldid) or Jonathan Levin's [jtool](http://www.newosxbook.com/tools/jtool.html#sign).

This could remove the 'red tape' from development and expand capabilities, perhaps even packaging it with [DNSCrypt](https://download.dnscrypt.org/dnscrypt-proxy) for example. If you are interested, there is a wealth of information located on the [iPhoneDevWiki](http://iphonedevwiki.net/index.php/Getting_Started). I know this is not completely solving the issue but it's better than nothing.

**Comment by ameshkov** [comment]
We just wanted to first look what options do we have without jailbreak. Cydia is an option indeed.

> perhaps even packaging it with DNSCrypt for example

We'll be able to do it without jailbreak in the main branch.

**Comment by Arkbyte** [comment]
I successfully sideloaded the above linked ipa. The app never got beyond the 'loading filters into safari' screen.

**Comment by UmarFarq** [comment]
To downgrade from 1.3.0 to 1.2.1 follow my instructions [here](https://www.reddit.com/r/Adguard/comments/6v53fz/tutorial_how_to_downgrade_adguard_pro_from_130_to/)

**Comment by MatthewGieger** [comment]
I've also tried using Compactor, but couldn't get around the required apple developer account to use the vpn functionality. 

Is there an Adguard suggested way of downgrading to the 1.2.1 version? I will try @UmarFarq's solution next.

**Comment by mikeoleary7528** [comment]
Honestly guys what I’ve been doing since there’s been no solution and the latest 1.3.1 beta is stable, is using the blacklist with custom filters I made and system default as my dns seems to solve my problem. Maybe instead focus on utilizing and expanding the blacklist function feature?

**Comment by MatthewGieger** [comment]
@mikeoleary7528 Does your setup work system wide? I thought the whole point of downgrading was to restore system-wide functionality?

**Comment by mikeoleary7528** [comment]
@MatthewGieger Yep! Works system wide and with full tunnel on, the only issues I ever have really are full tunnel related not filter. I have about 20k filters in my black list.

**Comment by MatthewGieger** [comment]
@mikeoleary7528  How did you populate your blacklist?

**Comment by ameshkov** [comment]
Ok, guys, here is one more option. It should work even for those who didn't buy original AG.

Briefly:
1. Download & install the Cydia impactor: http://www.cydiaimpactor.com/
2. Use it to install the "app installer": https://github.com/Sn0wCh1ld/App-Installer
3. Use the "app installer" to install this .ipa file:
    [Adguard Pro 1.2.1.ipa.zip](https://github.com/AdguardTeam/AdguardForiOS/files/1251883/Adguard.Pro.1.2.1.ipa.zip)

**Comment by ameshkov** [comment]
Another option (works with iOS11) -- just use iFunBox to install the previous version. 

Much easier than the previous option, but it will work only if you have AG Pro purchased.

**Comment by Voland009** [comment]
@ameshkov 
_"I am wrong, you'll have to extract & download the .ipa file manually, so ifunbox is not required, you can do the same via itunes"_
sorry, could you describe in more detail how to do this? (No jabblebreak)

**Comment by ameshkov** [comment]
@Voland009 
> sorry, could you describe in more detail how to do this? (No jabblebreak, IOS10)

Here it is:
https://www.reddit.com/r/Adguard/comments/6v53fz/tutorial_how_to_downgrade_adguard_pro_from_130_to/

**Comment by ameshkov** [comment]
@Voland009 
Although I suppose this way is easier:
https://github.com/AdguardTeam/AdguardForiOS/issues/450#issuecomment-324912787

**Comment by MatthewGieger** [comment]
@ameshkov  I couldn't seem to get the compactor solution using [#450 (comment)](https://github.com/AdguardTeam/AdguardForiOS/issues/450#issuecomment-324912787) to work. Does it require a paid apple developer account? The AppInstaller app didn't seem to want to install the ipa that i hosted on my dropbox account..

**Comment by ameshkov** [comment]
@MatthewGieger tested it with a fresh apple account, worked okay. Please note that it won't work on iOS11 though.

**Comment by MatthewGieger** [comment]
Ah. ok.Thanks. I'm on ios 11 already. For now i'll just set my dns ip to the adguard servers.

**Comment by antnythr** [comment]
Will you guys maintain a branch that keeps the old vpn based in-app ad blocking? (I've already got an IPA for 1.2.1, but don't mind compiling an updated version myself)

**Comment by MatthewGieger** [comment]
@antnythr Why not just add a custom dns server to the latest version of the app? That works fine for me. No difference than before the update.

**Comment by gnarnick** [comment]
Didn’t the old versions use the in-app filters to create its custom DNS? I also felt like there was a speed difference between in-app DNS vs the 1.3.0 method.

**Comment by MatthewGieger** [comment]
@gnarnick To be honest, i'm not too sure what the difference is between the old and new methods, but the new method seems to work fine for me. I haven't noticed a speed difference, but i also haven't run any tests to verify.

**Comment by ameshkov** [comment]
All we know about the downgrade is now published here:
https://blog.adguard.com/en/how-to-downgrade-adguard-pro/
