### ISSUE TITLE
DNS Naming Bug — Adguard Pro 1.3.0 (100)

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForiOS#453]
### Steps to reproduce

1. Open Adguard Pro 1.3.0 (100)
2. Tap ‘Add Custom...'
3. Add ‘DNS’ in the Name section somewhere
4. Press ‘Done’

### Expected behavior

The exact name I typed should appear underneath the default DNS server list (eg. ‘Adguard DNS’)

### Actual behavior

Anything in capital letters turn into lowercase after the first letter, so my name is converted to Dns (eg. ‘Adguard Dns’)

### Screenshots:

![img_1211](https://user-images.githubusercontent.com/29296810/28439679-35aa2c70-6de6-11e7-8439-92f67619055a.PNG)
![img_1212](https://user-images.githubusercontent.com/29296810/28439680-367a7f6a-6de6-11e7-9e7d-2ea92ce6e8ea.PNG)

### Your environment

* iPhone 7 32GB
* iOS 10.3.3 (14G60)

**Comment by X8716e** [comment]
This has been happening for awhile. I thought it more a quirk than anything as it doesn't affect functionality.

**Comment by Stillness-2** [comment]
Name for custom servers converts to capitalized text automatically at this moment. This is standard behaviour.

**Comment by IvanIin** [comment]
fixed
