### ISSUE TITLE
Adguard for ios can not use $replace rules

### ISSUE THREAD

**Issue by ilvjyw** [AdguardTeam/AdguardForiOS#456]
See screenshot:
![61p 9jkqwska5up o0y 8q](https://user-images.githubusercontent.com/3976203/28629736-e2a2ab82-725a-11e7-95f2-ccd7e0777faf.jpg)
In user rule editor  $replace rule Cannot enter!

**Comment by vozersky** [comment]
It due to browser's restrictions 
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#advanced-modifiers-1
