### ISSUE TITLE
Adguard Pro 1.3.0 (100) German translation not updated / Strings has been translated on OneSky

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardForiOS#458]
![img_1793](https://user-images.githubusercontent.com/25068100/28825926-6b3b56c6-76c8-11e7-87c0-44671e00e209.PNG)
![img_1794](https://user-images.githubusercontent.com/25068100/28825927-6b40b7e2-76c8-11e7-9475-9a040466b9fb.PNG)

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardForiOS/issues/421

**Comment by sergerosenthaler** [comment]
Unfortunately there is a double wording... please delete the unnecessary "kann"

![bild 5](https://user-images.githubusercontent.com/25068100/29423447-0d574c5c-837c-11e7-9691-56a8922430b4.jpg)

**Comment by sergerosenthaler** [comment]
OneSky is updated and there is a comment regarding this.

**Comment by vbagirov** [comment]
The translation in Onesky had already been fixed by the time I checked it.

**Comment by zebrum** [comment]
fixed in 1.3.1(106)
