### ISSUE TITLE
Checkmark disappears when you select a DNS server

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#460]
Source report:
https://twitter.com/zznosar/status/892485823530020865

**Comment by zznosar** [comment]
@IvanIin try using an ipod touch or a wifi only iPad. When I encountered that issue, I was using iPod touch.

**Comment by altokarev** [comment]
Reproduced on iOS 11/AdGuard 1.3.1 (107): https://youtu.be/p5DeX_wrSjQ

**Comment by altokarev** [comment]
It reproduces on 1.3.2 (107) too but with a different behaviour. There is some kind of a lag of checkmark appearing while DNS setting is enabling.

**Comment by zebrum** [comment]
in 1.3.3(110) it's easily reproducible. May be we should fix it sooner then in v.2.0
