### ISSUE TITLE
Unable to check "System Default" in the app

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardForiOS#461]
### Steps to reproduce

1. Updated to the latest version this morning.  
2. Had the Pro feature turned on and had Adguard default selected as the DNS.
3. Can't select System Default.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/28847025-56c9fda2-7716-11e7-9c55-c65f8e52f2f7.png)

</details>

### Your environment
<details>

[com.adguard.AdguardPro.ActionExtension.gz](https://github.com/AdguardTeam/AdguardForiOS/files/1191958/com.adguard.AdguardPro.ActionExtension.gz)
[com.adguard.AdguardPro.gz](https://github.com/AdguardTeam/AdguardForiOS/files/1191959/com.adguard.AdguardPro.gz)
[com.adguard.AdguardPro.tunnel.gz](https://github.com/AdguardTeam/AdguardForiOS/files/1191957/com.adguard.AdguardPro.tunnel.gz)
[filter.gz](https://github.com/AdguardTeam/AdguardForiOS/files/1191960/filter.gz)
[state.txt](https://github.com/AdguardTeam/AdguardForiOS/files/1191961/state.txt)

</details>

**Comment by IvanIin** [comment]
fixed

**Comment by veronikasav** [comment]
It is not fixed. I still can not switch to System Default.

**Comment by veronikasav** [comment]
> I am unable to switch back to system default DNS. Pressing the selection on IOS does not make it get selected.

<details>

<img width="418" alt="screen shot 2017-08-15 at 3 39 56 pm" src="https://user-images.githubusercontent.com/27292111/29316292-1ef0a182-81d0-11e7-8e56-276e603548ba.png">

</details>

Ticket ID: 1446085

**Comment by IvanIin** [comment]
@veronikasav  this bug is fixed in 1.3.1(104) beta.
