### ISSUE TITLE
Adguard PRO 1.3.0 Custom DNS not working properly in Wifi  

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#462]
[Adguad Logs Mobile.zip](https://github.com/AdguardTeam/AdguardForiOS/files/1197063/Adguad.Logs.Mobile.zip)
[Adguard Logs Wifi.zip](https://github.com/AdguardTeam/AdguardForiOS/files/1197064/Adguard.Logs.Wifi.zip)

Adguard PRO 1.3.0 Custom DNS not working properly in Wifi  

Steps to reproduce
1. Enable Adguard PRO Custom DNS (Select Adguard Family Protection)
2. Enable Wifi. 
3. Open Apple News and select an Article
4. Ads is visible

Expected behaviour
Ads should not be visible in Wifi since in Mobile, ads is filtered

Actual behaviour
Ads is Visible in wifi

Screenshot:

![img_4588](https://user-images.githubusercontent.com/27464836/28871666-f9d7030c-77c8-11e7-951c-159cbf6305a8.PNG)
![img_4587](https://user-images.githubusercontent.com/27464836/28871665-f9d13b34-77c8-11e7-8898-51c5db6e9515.PNG)

![img_5534](https://user-images.githubusercontent.com/27464836/28920565-b79d4dac-7895-11e7-8d69-d515cad85228.PNG)
![img_5535](https://user-images.githubusercontent.com/27464836/28920566-b8102f8e-7895-11e7-9c50-95d548209949.PNG)

* Device model and storage size: Iphone 7 Plus 256 GB
* Operating system and version: 10.3.3
* Browser: N/A Only appearing in apps e.g. Apple News
* Wi-fi internet connection

**Comment by zznosar** [comment]
Anyone that can help??? I reinstalled version 1.2.1 for the mean time since 1.3.0 is not fully working in wifi.... so sad.

**Comment by zznosar** [comment]
@ameshkov   Please see attached. Updated with more screen shots
[Adguard Logs Wifi.zip](https://github.com/AdguardTeam/AdguardForiOS/files/1197068/Adguard.Logs.Wifi.zip)
[Adguad Logs Mobile.zip](https://github.com/AdguardTeam/AdguardForiOS/files/1197069/Adguad.Logs.Mobile.zip)

**Comment by IvanIin** [comment]
@zznosar 
I see in the logs that our VPN tunnel sends requests to the Adguard family DNS, but responses comes from some other server.
It looks like the traffic in your wi-fi network is redirects to another server.
You can check what DNS is really used - https://dnsleaktest.com/.

**Comment by zznosar** [comment]
@IvanIin , tried DNS leaks and it is using my ISP DNS which is skymesh australia.

**Comment by ameshkov** [comment]
So they hijack the DNS traffic :( That's a problem we cannot solve at the moment.

In the future versions, we will add DNSCrypt support, it'll solve DNS hijacking issues.

**Comment by zznosar** [comment]
That is sad! I have no choice but to use the old version for now until such feature is available.. Thanks guys!
