### ISSUE TITLE
iOS Assistant is incorrectlty placed on the site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#463]
The Assistant is placed below the main view so it's impossible to use it. The site in question: https://certbot.eff.org/#sharedhost-apache

### Steps to reproduce

1. Go to https://certbot.eff.org/#sharedhost-apache
2. Go to Adguard from the page
3. Try to block an element
4. See the assistant flickering outside the viewport

### Expected behavior

It should work as it works on other sites

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28911708-1cd8365c-783a-11e7-8381-c195ec439427.png)

</details>

### Your environment

* Device model and storage size: iPhone SE
* Operating system and version: iOS 11 beta 3
* Browser Safari
* Wi-fi or mobile internet connection - both

**Comment by IvanIin** [comment]
duplicate
https://github.com/AdguardTeam/AdguardForiOS/issues/416
