### ISSUE TITLE
Add DNSCrypt support to Adguard Pro

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#465]
I am not sure if we have an Issue Number to track this feature.

Can we have DNScrypt in Adguard Pro? My ISP is manipulating it's DNS so Adguard DNS is not working in Wifi (but working in Mobile LTE connection). I heard that DNScrypt can solve this issue?

Probably its the same issue people in app store are saying that it's not working (it is working but their ISPs is hijaking it).

Any thoughts?

**Comment by zznosar** [comment]
@ameshkov please please pleas help 😊😊😊

**Comment by vozersky** [comment]
As far as I know, you need a jailbreak to use DNSCrypt on iOS

**Comment by zznosar** [comment]
i saw an article that with the introduction of a new network framework in IOS 9 and also in IOS 11, this is possible.. but no one has written any code yet for this... 

https://forum.adguard.com/index.php?threads/dnscrypt-for-ios-as-a-pro-add-on-for-adguard.23496/

Probably it really is possible in IOS 11?

**Comment by ameshkov** [comment]
It is possible for sure, thanks for creating feature request!

**Comment by zznosar** [comment]
Now that The android version has dnscrypt built in the newest version, can we start adding this feature as well in ios? Ios 11 as per checking can add this feature without jailbreak. @ameshkov

**Comment by ameshkov** [comment]
@zznosar it won't be easy (technically), but it will happen in v2.X branch.

**Comment by zznosar** [comment]
Please please please include this feature to the app before the end of 2017! Is that possible? 😊😊😊😊 it would be wonderful present to all if us using the pro app! 😊😊😊

**Comment by ameshkov** [comment]
@zznosar yeah, it's possible, there is a great chance that we'll do it.

**Comment by zznosar** [comment]
@ameshkov looking forward to it. I think a lot of ios pro users will be happy once this is release. Especially for people whose ISPs have been snooping of what they are doing! Can’t wait! Thanks Guys! And keep up the good work!

**Comment by bigdargon** [comment]
+1

**Comment by bigdargon** [comment]
Hope support DNSCrypt iOS 0

> With the introduction of the Network Extension Framework in iOS 9, it may be possible to write a DNSCrypt client app that would run everywhere, without requiring a jailbroken device. 

>

**Comment by zznosar** [comment]
Bump bump bump... Is there any updates on this? Sorry! I'm just excited! :) :) :)

**Comment by ameshkov** [comment]
Still planned on v2.0, working on it

**Comment by zznosar** [comment]
@ameshkov Thanks for the info. Will it be this year or next year? any timelines? Sorry to be a pain.. me and a handful of my friends who are using this app are very eagerly and patiently waiting for this feature in iOS. :) I think only one of my mates here in Australia who is using Android has it... and we're jealous of him! :) Keep up the good work!

**Comment by ameshkov** [comment]
It should happen this year if nothing extraordinary happens

**Comment by zznosar** [comment]
@ameshkov! Ok cool. Thanks! We’re celerbating here now with my friends in Aus! Yey!! Thanks so much.

**Comment by zznosar** [comment]
Ok. This has been closed! Does that mean that it’s ready and will be available in fhe comming days? @ivanlin ?

**Comment by bigdargon** [comment]
can't wait to update DNSCrypt

**Comment by IvanIin** [comment]
This feature will be available in version 2.0. Now we are preparing version 1.3.3 for release. 2.0 will be a little later.

**Comment by zznosar** [comment]
@ivanlin thanks for the update. I can’t wait! Very excited. Hopefully it’s within this year. 😁😁 thank you so much!

**Comment by bigdargon** [comment]
@IvanIin ver 2.0.0 support iOS 9?

**Comment by ameshkov** [comment]
> @ivanlin thanks for the update. I can’t wait! Very excited. Hopefully it’s within this year. 😁😁 thank you so much!

The #545 will slow us down a bit. But anyway, we'll be able to publish beta this year.

> @IvanIin ver 2.0.0 support iOS 9?

No, dropped it. iOS9 limitations on the VPN extensions memory usage are too strict.

**Comment by zznosar** [comment]
@ameshkov, sure no worries. Though i hope that it will not be too long. Probably January release? Thanks so much! I want you guys to be the first to have this feature in App Store. 😊😊😊
