### ISSUE TITLE
Some inaccuracies in translation of PRO settings to russian

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForiOS#466]
1. Description to the Status setting not translated:
<details><summary>Screenshot:</summary>

![img_00431](https://user-images.githubusercontent.com/28726429/28974224-417088ac-793e-11e7-9642-7395b455f792.jpg)

</details>
<br>

2. `System Default` setting is not the same as `По умолчанию`:

<details><summary>Screenshot:</summary>

![img_00432](https://user-images.githubusercontent.com/28726429/28974362-cf904d0c-793e-11e7-9769-39785425bd9e.jpg)

</details>
<br>
That's misleading some users.

**Comment by IvanIin** [comment]
fixed
