### ISSUE TITLE
Turning on Adguard DNS activates pia vpn

### ISSUE THREAD

**Issue by laserstrike** [AdguardTeam/AdguardForiOS#468]
On split-tunnel mode, activating adguard DNS also activates pia vpn. Which is fine if someone wants both on, but I can't seem to get adguard DNS to work without it turning pia on. Pia won't deactivate or, even if it does, when I swipe it away and return to the app it's on again.

On full tunnel mode, pia is also turned on, with no means of turning it off—but at least in this case, my IP address remains the same.

On adguard pro 1.3 and pia 2.2.2.

**Comment by ameshkov** [comment]
Frankly, it sounds like a PIA bug, AG cannot directly interact with PIA. Maybe PIA reacts on the network state change and enables itself?

**Comment by zebrum** [comment]
no free trial in PIA VPN app now. should we buy it to check the issue @ameshkov ?

**Comment by zebrum** [comment]
@laserstrike can not reproduce not on 1.3.0 nor the latest beta. Tried both full and split mode. please try reinstall Adguard and pia apps.

**Comment by zebrum** [comment]
oh, get it now. 

It is PIA bug. You can check with Betternet VPN app - the same behavior: enable AdGuard or Betternet VPN - in PIA settings it looks like PIA VPN enabled too, but it doesn't if you check your ip address.
