### ISSUE TITLE
Sometimes tunnel does not restart correctly when the network changes

### ISSUE THREAD

**Issue by IvanIin** [AdguardTeam/AdguardForiOS#470]
Pro 1.3.0

In some cases, the tunnel does not restart when the network is changed. At the same time, it stops processing packets and actually does not work, although the VPN icon is displayed.

**Comment by polarimetric** [comment]
Happening to me on 1.3.0 every time the device hands off from wifi to LTE, iPhone 7 iOS 11 dev beta 5.

**Comment by Goddess-Bastet** [comment]
Same here on my iPad when moving from home wifi to my iPhone's hotspot, I have to turn off AG protection within the app then turn on again.

**Comment by ng4ever** [comment]
Same problem. This sucks :(

**Comment by altokarev** [comment]
Hold on, guys! A new beta is coming soon. This issue fixed there.

**Comment by rijc99** [comment]
How can I get the beta version?  I’m having connection issue with the latest version of Adguard pro VPN on iOS 11 beta.

**Comment by zebrum** [comment]
@rijc99 you can send a PM with your apple ID to [me](https://forum.adguard.com/index.php?conversations/add&to=zebrum) via our forum or send it to support@adguard.com. After that you will receive an autoreply letter with your ticket id from support team - post it here and I or @altokarev will find you e-mail and add you to beta-test group.

**Comment by polarimetric** [comment]
Can confirm that this is fixed in 1.3.1 (104) (TestFlight beta) on both iPhone and iPad running iOS 11 dev beta 5.

**Comment by ValidatePro** [comment]
I can confirm that this problem is solved with 1.3.1 (104)

**Comment by hal0003** [comment]
Can confirm that this is fixed in 1.3.1 (104)

**Comment by hal0003** [comment]
ch habe doch noch einen Fehler gefunden:

Die Umschaltung auf WLAN-Call funktioniert nicht richtig.

Wenn ich AdGuard 1.3.1 beta ausschalte schaltet das iPhone bei schlechtem LTE-Empfang sofort um auf WLAN-Call. (Wenn man im einem WLAN ist).
Wenn ich AdGuard anschalte dauert es immer eine Weile. Manchmal wird auch nicht umgeschaltet.
Dann muss ich in den Flugmodus schalten und wieder zurueck, dann dauert es einen Moment und dann wird umgeschaltet.
Ohne AdGuard - wie gesagt - geht es einwandfrei.

Testweise habe ich AdBl**k versucht. Damit funktioniert es auch einwandfrei.

**Comment by hal0003** [comment]
Die WLANCall Probleme habe ich mit Version 1.3.1 (106) immer noch.
Und myTiffi zickt immer mehr.
Jetzt bekomme ich gar keine Verbindung mehr. Auch nicht wenn ich eine feste IP benutze.

**Comment by IvanIin** [comment]
@hal0003 we need logs to solve this issue.

**Comment by hal0003** [comment]
**User ID**: 1162673

**Comment by altokarev** [comment]
[1162673_logs.zip](https://github.com/AdguardTeam/AdguardForiOS/files/1248268/1162673_logs.zip)

**Comment by hal0003** [comment]
Ich konnte das WLANcall-Problem scheinbar etwas einschraenken.
(Betrifft auch das Problem mit myTiffy)

Ich habe jetzt 1.3.1. (107) installiert. Den Effekt kann ich aber auch mit (106) nachvollziehen.

Wenn ich in den erweiterten Einstellungen Split-Tunnel anstatt Full-Tunnel waehle, dann funktioniert WLANcall und myTiffi scheinbar einwandfrei.
Wenn ich auf Full-Tunnel schalte habe ich massive Probleme.

Ich habe euch noch ein paar Log's geschickt. Habe aber bisher keine ID erhalten.

**Comment by hal0003** [comment]
Das Problem besteht weiterhin. :(
Auch mit der Beta-Version 1.3.2 (108)

**Comment by altokarev** [comment]
@hal0003 hello! Could you please collect another log at 1.3.2 (108) and specify the exact time when an issue occurs?

And one more question - do you use any other VPN apps?

Thanks!

**Comment by hal0003** [comment]
@altokarev

Ich habe keine weiteren VPN-Apps isntalliert.

Ich habe die 1.3.2 (108) wieder deinstalliert und die 1.3.1. (107) wieder installiert.
Sollte ich morgen Zeit haben, installiere ich die 1.3.2 (108) noch einmal und schicke dann die Log mit den gewuenschten Angaben.

**Comment by hal0003** [comment]
@altokarev
   **User ID**: 1162673

> ould you please collect another log at 1.3.2 (108) and specify the exact time when an issue occurs?

**28.08.2016, 19:44** no myTiffy, no WLANcall
**28.08.2016, 19:46** no myTiffy, no WLANcall
**28.08.2016, 19:48** no myTiffy, no WLANcall

**Comment by altokarev** [comment]
Thanks! Handed over to the developers.
