### ISSUE TITLE
iOS 11 beta 5 bug with VPN -- causes phone restart

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#471]
User reports this:
https://twitter.com/chaoticbuddhist/status/894238706655035393

@zebrum @IvanIin guys, plz check it on monday.

**Comment by ameshkov** [comment]
Once it's resolved, plz ask support to answer on Twitter

**Comment by zebrum** [comment]
so far @IvanIin was not not able to reproduce the issue on test device and at least @polarimetric (#470) had no complains about it. May it be an iOS bug again?

**Comment by polarimetric** [comment]
Yeah, @zebrum, I can’t reproduce this either. I’m running beta 6 now instead of 5, but I have not experienced reboots due to Adguard DNS settings on either.

**Comment by vozersky** [comment]
obsolete
