### ISSUE TITLE
Localization Problem on 1.3.1 (104)

### ISSUE THREAD

**Issue by ValidatePro** [AdguardTeam/AdguardForiOS#472]
Tunnel Mode section didn't translate on Turkish.
https://i.hizliresim.com/4Mvv7Q.png

**Comment by zebrum** [comment]
@ValidatePro hi!

there is no translation for that text piece yet.

we'll be very thankful if you can take part in translation. How to do so: https://blog.adguard.com/en/adguard-public-translations/

**Comment by zebrum** [comment]
closing it for now.
