### ISSUE TITLE
VPN can not establish connection on iOS 9

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForiOS#475]
### Steps to reproduce

1. install Adguard 1.3.1 (105) beta
2. enable Pro status
3. go to Safari and try to load a page

### Expected behavior

VPN status - connected, Adguard works
### Actual behavior

VPN status - **connecting**
No internet connection in apps
if you go back to Adguard - DNS settings: status Pro - enabled, but no VPN server is selected

### Your environment

* Device model and storage size: iPhone 5
* Operating system and version: 9.3.5
* Wi-fi

**Comment by IvanIin** [comment]
This is a very strange behavior. Ios could not start the tunnel process. At the same time, there are no errors in system logs. After rebooting the device, the error could no longer be reproduced.
