### ISSUE TITLE
[Feature Request] Incorporation of UA normalization

### ISSUE THREAD

**Issue by X8716e** [AdguardTeam/AdguardForiOS#476]
Normalization of iPhone/iPad to help reduce fingerprinting of user. See project https://github.com/mtigas/OnionBrowser for reference and possible incorporation of any relative code.

"End-user Configuration Details
End-user configuration details are by far the most severe threat to fingerprinting, as they will quickly provide enough information to uniquely identify a user. We believe it is essential to avoid exposing platform configuration details to website content at all costs. We also discourage excessive fine-grained customization of Tor Browser by minimizing and aggregating user-facing privacy and security options, as well as by discouraging the use of additional plugins and addons. When it is necessary to expose configuration details in the course of providing functionality, we strive to do so only on a per-site basis via site permissions, to avoid linkability." via section 4.6 @ https://torproject.org/projects/torbrowser/design/#fingerprinting-linkability

**Comment by ameshkov** [comment]
Unfortunately, that's not possible in iOS -- content blocking API just does not provide such capabilities.

On the other hand, we already did it in AG for Windows -- "Hide your User Agent" option strips identifiable information from the user agent.

**Comment by X8716e** [comment]
Figured as much; but I always like trying to push the existing to become more, i.e. to encourage thought.

**Comment by ameshkov** [comment]
> Figured as much; but I always like trying to push the existing to become more, i.e. to encourage thought.

Np, thank you for the feature request anyway!
