### ISSUE TITLE
Rules Syntax link from RU locale redirects to EN KB article

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForiOS#480]
In UF (free and PRO versions) we have  Rules Syntax link redirecting to knowledge base article [How to create your own ad filters](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters) 

When system language is Russian the article should be opened also in Russian.

**Comment by ameshkov** [comment]
@zebrum 
Check this link plz: https://kb.adguard.com/general/how-to-create-your-own-ad-filters

Is your language detected properly?

**Comment by zebrum** [comment]
1.3.2(108)
no, still the same problem - the article opens in eng

**Comment by ameshkov** [comment]
@zebrum 
anyways, that's a server-side issue, should be filed to the knowledge base repo and closed here

**Comment by zebrum** [comment]
yep, moving to kb repo.
