### ISSUE TITLE
[Feature Request] rule syntax in user added DSN filters 

### ISSUE THREAD

**Issue by X8716e** [AdguardTeam/AdguardForiOS#481]
**As such: whereas it's now possible for users to only block domains in DNS blacklist, I'd like to see the use of the * (wildcard) symbol, the ? (any single char) symbol, IP addressing, ports, etc. 
thanks for the consideration of expanding user-end functionality!**

**Comment by ameshkov** [comment]
> I'd like to see the use of the * (wildcard) symbol, the ? (any single char) symbol, IP addressing, ports, etc.
> thanks for the consideration of expanding user-end functionality!

The blacklist supports basic rules syntax:
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#basic-rules-syntax

Wildcard, separator, matching beginning/end of the domain name.

**Comment by X8716e** [comment]
Never got around to thanking you for your reply. I originally was under the impression only domain names were accepted in DNS blacklist rules. I'm most interested in setting up some encryption-based rules for specific URIs e.g. |https:*.github.* I visit & avoiding the use of varying TLDs for single domain entries e.g. alphabet*
