### ISSUE TITLE
Automatically import DNS blacklist from a filter

### ISSUE THREAD

**Issue by kathampy** [AdguardTeam/AdguardForiOS#486]
Please add a way to automatically import a chosen filter into the DNS blacklist. Obviously anyone who knows what this is really for would only import the Simplified domain names filter. If this borders on breaking the App Store rules, then at least provide an import button which can be manually clicked once in a while when the filters are updated.

**Comment by ameshkov** [comment]
Will add an "Import from URL" option in v2

**Comment by kathampy** [comment]
Would it handle the same format as the filter? Would it auto update?

**Comment by ameshkov** [comment]
> Would it handle the same format as the filter?

Yes, it can handle it right now if you copy/paste it there.

> Would it auto update?

Nope, that'd be too much(

**Comment by kathampy** [comment]
It fails when I copy and paste the simplified list as is. It just shows 0 domains added.

**Comment by ameshkov** [comment]
> Can you make it at least remember the last URL imported so we only have to click one button.

Sure

**Comment by lancelot-moon** [comment]
Hi guys,
This is the original interface of layout.
![Image of Yaktocat](https://i.imgur.com/eOkBKrZ.jpg)

It's my thought about the new layout for blacklist.
How do you think?

There is a button near the blacklist section.
After manually pressing the button, those filters in the blacklist will automatically download filters from the URL link which we inputed.

![Image of Yaktocat](http://i.imgur.com/WhUKRXV.png)

![Image of Yaktocat](http://i.imgur.com/KGnCOkP.png)

**Comment by ameshkov** [comment]
Duplicates #545 , it's available in v2 beta
