### ISSUE TITLE
Test page for adguard doesn't work

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardForiOS#488]
When I go to https://static.adguard.com/test.html it always says Adguard is disabled. Is this a bug?

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/29746382-0052d320-8ae1-11e7-8c35-eb1e306604f2.png)

</details>

### Customer ID 
1585281

**Comment by evgeniy-ADG** [comment]
it does not detect adguard on other platforms

**Comment by ameshkov** [comment]
Meh, we'd better create a new test page, this one is obsolete

**Comment by Goddess-Bastet** [comment]
Same for me on my iPad Pro, says AG is disabled.

**Comment by worldsdream** [comment]
Yes please, we need a working test page for ios. Also a test button that will open up this page or a popup showing that adguard is enabled and working great.

**Comment by vbagirov** [comment]
Fixed.
