### ISSUE TITLE
Adguard to AdGuard transition on OneSky

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardForiOS#489]
As I saw on new.adguard.com you have deciced to use AdGuard further on. The name transition should be reflected in all apps. Is there a way for you to to a batch translation. For me who only translates German, this is very time consuming and should be done over all languages automatically.

**Comment by vbagirov** [comment]
@sergerosenthaler of course, you shouldn't go through all the phrases and manually substitute the words. It is not the end of the world if there is some inconsistency with the names at the moment. We will fix it in batches with the forthcoming updates for different apps.

**Comment by sergerosenthaler** [comment]
@vbagirov so you take care of the name transition on OneSky. If I will translate phrases in the future, I'll use the new name AdGuard but I let the old phrases untouched, okay?

**Comment by vbagirov** [comment]
@sergerosenthaler sure! We've already fixed the phrase for Android project.
