### ISSUE TITLE
AdGuard Pro on public wifi

### ISSUE THREAD

**Issue by UmarFarq** [AdguardTeam/AdguardForiOS#490]
So I decided to connect to Teco Wifi and wanted to test if AdGuard was still working and realised ads started showing and the DNS was not connected. I am using the latest AdGuard Pro for iOS. Everything is working fine at my home but don't know why it doesn't work on public wifi. I tried both split tunnel and full tunnel but still couldn't connect to the dns. Any ideas why?

**Comment by UmarFarq** [comment]
I have even manually configured the ports like this: 
176.103.130.130:5353
176.103.130.131:5353
Still no luck

**Comment by zebrum** [comment]
@UmarFarq hello!

please reproduce the issue and send us logs from the app. also notice exact time when problem appears

**Comment by UmarFarq** [comment]
I have sent email with the required logs if u need any more info please let me know

**Comment by zebrum** [comment]
please remove this DNS 138.68.163.138 and leave only Adguard DNS servers in settings )

**Comment by UmarFarq** [comment]
Help desk id is : 1624191

**Comment by UmarFarq** [comment]
Yes it works when I remove the first dns. The first dns is anti revoke And  it works fine on my home wifi with AdGuard DNS  but not when connected to tesco wifi. I have removed it from my list. Thank for the help

**Comment by UmarFarq** [comment]
I have sent a log when connected to my home network showing AdGuard dns and AntiRevoke dns working side by side just not working when connected to tesco

**Comment by UmarFarq** [comment]
How do I block www.ocsp.apple.com with the latest AdGuard for iOS when I input it into the blacklist its not blocking the website

**Comment by zebrum** [comment]
it is a bug. 
just  turn off and on DNS status, or update to the latest beta.

**Comment by UmarFarq** [comment]
Toggling the status of AdGuard seemed to fix it thanks a ton!

**Comment by ameshkov** [comment]
Ops, closed accidentally. @zebrum @IvanIin guys plz update the issue status, have you received everything you needed?

**Comment by zebrum** [comment]
problem solved.
