### ISSUE TITLE
Adguard vpn causes device to fail to transition from wifi to LTE and requires manually disabling the vpn from adguard settings

### ISSUE THREAD

**Issue by fennectech** [AdguardTeam/AdguardForiOS#492]
### Steps to reproduce

1. Enable vpn full tunnel or partial tunnel
2.transition from wifi to LTE    the wifi icon stays in the corner of the status bar.   
3.Data now does not work when adguard is enabled.
4. To fix go to settings and turn off vpn and adguard will turn it back on.  Device is now on LTE

### Expected behavior
Device should disconnect from wifi and connect to LTE 

### Actual behavior
Device remains conenected to wifi after wifi area has been left. (it try's to use the existing connection instaid o trying to connect to a new one

</details>

### Your environment

* iPad Pro 128gb
* Operating system and version: (e.g. 10.3.1)
* safari m.     am.       my.  
* Wi-fi or mobile internet connection

**Comment by vozersky** [comment]
wasn't able to reproduce, please try @zebrum 

@fennectech is it possible to send us logs, if you still experience this issue?

**Comment by zebrum** [comment]
@fennectech what is AdGuard version?

**Comment by zebrum** [comment]
closed

**Comment by fennectech** [comment]
Sorry The issue has vanished with an adguard update   Thanks tho.
