### ISSUE TITLE
Simplified Chinese translation for "Rules Syntax" is wrong

### ISSUE THREAD

**Issue by xiaody** [AdguardTeam/AdguardForiOS#493]
https://github.com/AdguardTeam/AdguardForiOS/blob/80c6aff47a7958be4de64da8c670291f507eb26e/AdguardExtension/AdguardApp/zh-Hans.lproj/Main.strings#L74-L75

The currently used words "清除全部" actually means "Clear All".
"规则语法" is correct, like the [Traditional Chinese version](https://github.com/AdguardTeam/AdguardForiOS/blob/80c6aff47a7958be4de64da8c670291f507eb26e/AdguardExtension/AdguardApp/zh-Hant.lproj/Main.strings#L74).

**Comment by aalpatkina** [comment]
@xiaody we have changed these words. Thanks for your help!
