### ISSUE TITLE
Some opinions

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#494]
@vbagirov
@Stillness-2
@ameshkov

Hi, I sent an email to your customer support.
The title is "Some opinions and please give me the access for translating all platforms of AdGuard."
But your customer support usually replies very late.
So I write here.

1. I'm your Traditional Chinese translator.
Before, you gave me the access for translating android and ios version of AdGuard.
But I am unable to overwrite old translations in some zones.

When I modify the old translations to new ones, they keep unchanged.
Please give me the access for translating all platforms of AdGuard.

2. I already completed the translations of AdGuard for android version.
I know that you will release AdGuard v3.0 for android version in the near future.
Please ANEW take all of strings' translations from oneskyapp before releasing new version of Adguard.

3. Before, I completed the translations of AdGuard Pro for ios version.
But I modified some translations recently.
Please also ANEW take all of strings' translations from oneskyapp before releasing new version of Adguard Pro.

4. I completed the translations of iTunes App Store and  iTunes App Store (Pro).
Why do you not use them?
Please use my translations on Taiwan's iTunes App Store, thanks!

5. In AdGuard Pro for ios version, you removed System-wide ad blocking because of Apple's policy.
https://blog.adguard.com/en/adguard-ios-1-3-0/

Many your users don't know the above news.
I think most of your users feel WTF after updating AdGuard Pro to v1.3.0.
They don't know that they should manually add custom DNS servers.
176.103.130.130, 176.103.130.131 - for Adguard DNS
176.103.130.132, 176.103.130.134 - for Adguard Family protection

You can see many bad appreciations on iTunes App Store.
They say that Adguard Pro is useless.

I know that AdGuard are unable to set AdGuard DNS servers as default when finished installing AdGuard Pro app because of Apple's policy. 
You should use a better method to let all of your users know to set up AdGuard DNS servers.
Instead of manually filling in DNS servers, a smart and convenient method of importing the DNS servers is much better!
I recommend to design so:
Manually press a button, and then Adguard DNS servers are automatically imported.

I read the article about AdblockPrime here.
https://github.com/AdguardTeam/AdguardForiOS/issues/487
The method of importing the configuration profile is interesting.
Maybe you can consider how to do according to that reference.

6. Your DNS servers are public and free.
https://adguard.com/en/adguard-dns/overview.html

Anyone can free use your DNS servers. 
But we paid for AdGuard Pro.
I don't feel the obvious difference, compared with free users.
Well, for paid users, the function of whitelist / blacklist, and then Adguard DNS servers can be used for not only Wi-Fi but also cellular network, which is a small difference.
However, free users can just set up your DNS servers in the WiFi setting, enjoy free public Adguard DNS ad blocking and don't need to purchase AdGuard Pro at all.

7. Although you said "Adguard DNS blocks ads in other apps and browsers just as good as System-wide ad blocking did.", that is NOT true.
Hope that you can improve your DNS servers.

May you first solve the below issues?

For examples:
A. IQQI Keyboard
https://goo.gl/cEf7rS

This is a keyboard app.
You can search "iqqi" on Apple App Store for downloading this app.
AdGuard Pro with Adguard DNS server is unable to block the ads in app.
<details><summary>Screenshots:</summary>

![image](http://i.imgur.com/pAoKwbT.png)

![image](http://i.imgur.com/Nn43qbN.png)
</details><br/>

B. AdGuard Pro with Adguard DNS server is unable to block ads via facebook app.
Some people are used to read news via facebook app.
You can use facebook app for visiting these links which are newspaper's fan pages.
https://www.facebook.com/myudn/?fref=ts
https://www.facebook.com/ETtoday/?fref=ts

Via facebook app, you search "ETNEWS新聞雲" or "udn.com 聯合新聞網".
Then you open any news on those fan pages.
AdGuard Pro with Adguard DNS server is unable to block ad pop-ups via facebook app.

ETNEWS新聞雲 fan page:
<details><summary>Screenshot:</summary>

![image](http://i.imgur.com/P0Wki3O.jpg)
</details><br/>

udn.com 聯合新聞網 fan page:
The half-transparent pop-ups isn't blocked.
<details><summary>Screenshot:</summary>

![image](http://i.imgur.com/7FlLSs7.png)
</details><br/>

C. https://itunes.apple.com/tw/app/ptt/id918374674?l=zh&mt=8
PTT+ is an app for BBS (Bulletin Board System).
You can search "PTT+" on Apple App Store for downloading this app.
After running this app, you can type "guest" for login.
Go to any Billboards in the BBS for reading articles.
AdGuard Pro with Adguard DNS server is unable to block ads in Billboards.
<details><summary>Screenshot:</summary>

![image](http://i.imgur.com/J7dOiu8.png)
</details><br/>

I tried AdblockPrime.
Its effectiveness is the same with FutureMind's AdBlock.
They can block pop-ups when opening news on ETNEWS新聞雲 fan page via facebook app.
But there is also a half-transparent pop-ups when opening news on udn.com 聯合新聞網 fan page via facebook app.
They're unable to block ads in some apps, too.
Ex: IQQI and PTT+...etc.

I tried Android version of Adguard v2.9 (HTTPS filtering is enabled.).
ETNEWS新聞雲 fan page:
It is unable to block ad pop-ups when opening news on ETNEWS新聞雲 fan page via facebook app.
<details><summary>Screenshot:</summary>

![image](http://i.imgur.com/y1sFuEN.jpg)
</details><br/>

udn.com 聯合新聞網 fan page:
The half-transparent pop-ups isn't blocked.
The content of err_connection_refused isn't hidden.
<details><summary>Screenshot:</summary>

![image](http://i.imgur.com/X6vzXah.jpg)
</details><br/>

In PTT+, it blocks ads in app.
<details><summary>Screenshot:</summary>

![image](http://i.imgur.com/ZuyZBjz.jpg)
</details><br/>

Thanks a lot!

**Comment by ameshkov** [comment]
Hi there!

Sorry for the delay, plz give us a moment

**Comment by ameshkov** [comment]
We really should separate the app & DNS issue discussion from the translation discussion.

I've assigned this task to @aalpatkina, she'll contact you soon about the translation issues.
What for the app & DNS, let's discuss it here.

**Comment by ameshkov** [comment]
> May you first solve the below issues?

I think that it could be that your ISP may be hijacking the DNS traffic and that's why using AG DNS does not help.

Could you please try using non-standard port instead (176.103.130.130:5353)

**Comment by lancelot-moon** [comment]
@ameshkov

Hi, ok.
From 1~4, they're about translations, we don't discuss here.
Bad quality of translations in the zone of filters.
http://adguard.oneskyapp.com/collaboration/project?id=14268
In the translation of filters, you use Simplified Chinese's contents for Traditional Chinese's.
Terrible Simplified Chinese translations.
Simply, please solve it and privately contact with me by email.

From 5~7, they're about app.

Manually filling in DNS servers is a stupid method.
Please you use a smart and convenient method for manually importing Adguard DNS servers.
Especially, many your users don't know that they should use custom Adguard DNS servers.
In the back of Apple's policy, think a method to let all of your users know the news.
Otherwise, for those users, Adguard Pro is trash.

Using 176.103.130.130:5353 as DND server is useless.

At midnight, I tried to enable "enable DNS requests log" for finding the ads domains.

For IQQI, Adguard Pro is unblock ads in app because the under ad domain is not blacklisted.
api.tinyhoneybee.com

For ad pop-ups when opening news on ETNEWS新聞雲 fan page via facebook app, it's because the under ad domains are not blacklisted.
ad.ettoday.net

For ad pop-ups when opening news on udn.com 聯合新聞網 fan page via facebook app, I block the under domain.
ad1.udn.com
But the half-transparent pop-ups isn't blocked.
May you solve the half-transparent pop-ups?

For ads in PTT+, I am unable to find ads domains...
So please you solve it.

Does Adguard DNS servers have those filters?
http://adguard.oneskyapp.com/collaboration/translate/project/project/14268/language/2#/
I mean Simplified domain names filter, Annoyances filter, Adguard Filters and so on.
In the past, System-wide ad blocking used these filters.
What filter do Adguard DNS servers use since System-wide ad blocking was removed?

Please add those ad domains which I found in the blacklist of the official filter. Thanks...

**Comment by zznosar** [comment]
A bit harsh opinion. 

This is my opinion as a USER. Their filters are not perfect but it works. It works for me. Also, I use my mobile a lot using LTE so paying for a "PRO" version is no biggie for me if I can use the Adguard DNS in celular. Also, i bought it to support the developers who are trying their best to make the app work considering a ton of limitaions apple impose. Also, i know that the adguard team will further update the app in app store unlike Future Mind, as mentioned in their twitter account, abandoned their adblock apps already and may not work in future versions of ios.

You mentioned about the method about adblock prime. Regarding profile installation. i have no idea why people are pushing adguard to use this method. This method is very risky and can compromise security. There is high chance that this method will be block by apple soon.

Also, chinese ads are harder to block since it's very region specific unlike english ads that can be seen anywhere.....

Just my two cent...

**Comment by ameshkov** [comment]
> It's because your blacklist of filters is not perfect.

Hm, we should think about including some source with Chinese ad servers to the DNS filter. Any idea of a good source?

**Comment by ameshkov** [comment]
> But the half-transparent pop-ups still isn't removed.
> May you solve the half-transparent pop-ups?

Need to use cosmetic filters to block this -- not possible on the DNS-level.

**Comment by ameshkov** [comment]
> For ads in Erudite app, need to block graph.facebook.com.

This is a problem:( You see, unlike AG for Android, AG for iOS cannot detect what app makes the request. So it either blocks the domain completely or not blocks it at all.

**Comment by ameshkov** [comment]
> DNS server is not the point.
> The blacklist is the point!

AG DNS uses the same filter as the one you've copied to the blacklist, I wonder what did happen.
Anyway, yeah, you can indeed fill the blacklist and use any DNS you want.

**Comment by ameshkov** [comment]
> Please add these ad domains which I found in the blacklist of the official filter.
> api.tinyhoneybee.com
> ad.ettoday.net
> ad1.udn.com
> graph.facebook.com

> May you contact with me after you update your filter of AG DNS?

Will be soon added:
https://github.com/AdguardTeam/AdguardFilters/issues/6703

**Comment by lancelot-moon** [comment]
@zznosar
English is also not my mother tongue.
I only use simple English in my article.
I feel sorry if my expression offends anyone.

I didn't severely criticize Adguard filters.
I know that there is no perfect filter in the world.
You think too much!
I just reported missed domains.

About adblock prime, I didn't meant that Adguard should use MDM.
I am not a specialist.
But the adblock prime's method of blocking ads is fresh for me.
Let me know that there is not only the type of app but also MDM for adblock.
Because of Apple's policy, Adblockers are in the difficult situation.
I talked about adblock prime.
Maybe those Adguard specialists can get enlightenments with another angle of thinking other methods over.
What can we do?
It seems that Kaspersky app also uses MDM.
In your opinion, that's also risky if you think Kaspersky is a spyware.

I agreed that Chinese is a regional language.
Many adblockers are designed by westerners.
If it's possible, hope that there is a individual Adguard Chinese filter.

**Comment by lancelot-moon** [comment]
> Hm, we should think about including some source with Chinese ad servers to the DNS filter. Any idea of a good source?

I found the filters website.
https://filterlists.com/

But after adding EasyList China + EasyList filter's content in my Adguard Pro's blacklist and then enabling local VPN, Adguard pro is resulted in a loss of internet connection.
Why? A bug?
A large number of EasyList China + EasyList filter's content or incompatible format of filter?

Please add a individual Adguard Chinese filter in Adguard filters' section in app.
And put Adguard Chinese filter on your official website.
https://kb.adguard.com/en/general/adguard-ad-filters

> Need to use cosmetic filters to block this -- not possible on the DNS-level.

May you teach me how to make the cosmetic filter for removing the half-transparent pop-ups?

> AG DNS uses the same filter as the one you've copied to the blacklist, I wonder what did happen.
Anyway, yeah, you can indeed fill the blacklist and use any DNS you want.

In my thought, you are forced to cut off the relation between local VPN and filters because of Apple's policy.
Do you say that AG DNS server is already with Simplified domain names filter?
https://itunes.apple.com/tw/app/ptt/id918374674?l=zh&mt=8
PTT+ is an app for BBS (Bulletin Board System).
With AG DNS server:
There is ad.
![Image of Yaktocat](http://i.imgur.com/J7dOiu8.png)

If I add the content of Simplified domain names filter into my blacklist, there is no ad.
![Image of Yaktocat](http://i.imgur.com/ZuyZBjz.jpg)

Why? Since you say AG DNS uses the same filter as the one I've copied to the blacklist.

**Comment by ameshkov** [comment]
> A large number of EasyList China + EasyList filter's content or incompatible format of filter?

Yeah, it's dangerous

**Comment by ameshkov** [comment]
> May you teach me how to make the cosmetic filter for removing the half-transparent pop-ups?
> I mean the rule syntax.

Everything is here: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters
But please mind, that it will work in Safari only.

**Comment by ameshkov** [comment]
> Why is the ad not blocked by AG DNS server since you say AG DNS uses the same filter as the one I've copied to the blacklist?

That's strange indeed, they must've been blocked. The only idea I have is that it was due to DNS hijacking on your internet provider side.

**Comment by ameshkov** [comment]
> In reality, bad appreciations become more and more on iTunes App Store.
> They say that Adguard Pro is useless.

With or without DNS ad blocking, AG Pro stays the best Safari content blocker. People will be upset for some time, but eventually, they'll accept this new reality Apple put us in.

> You should use a better method to let all of your users know to set up AdGuard DNS servers.
> Is there no method in back of Apple?

This is all too risky.

**Comment by lancelot-moon** [comment]
> Yeah, it's dangerous

What dangerous thing do you mean?
Is EasyList China + EasyList filter not reliable?
Or is the format of EasyList China + EasyList filter not compatible with Adguard?

**Comment by lancelot-moon** [comment]
> That's strange indeed, they must've been blocked. The only idea I have is that it was due to DNS hijacking on your internet provider side.

I am sure that AG DNS is working because some basic ads are blocked in a newspaper app.
But AG DNS's ad blocking is not effective for many apps.
That's why I asked about what filter AG DNS uses.
Maybe those apps use unknown ad domains for your filters.

**Comment by ameshkov** [comment]
> What dangerous thing do you mean?
> Is EasyList China + EasyList filter not reliable?
> Or is the format of EasyList China + EasyList filter not compatible with Adguard?

I mean that it's dangerous to use them for DNS-level ad blocking. They may cause a lot of incorrect blocking.

**Comment by ameshkov** [comment]
> Maybe those apps use unknown ad domains for your filters.

It's just strange that it works okay when you add Simplified domain names filter, and do not work with AG DNS, as it uses the very same filter.
