### ISSUE TITLE
Why does the blacklist of Adguard for ios not accept a URL's path, compared with Android version?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#496]
@ameshkov

Hi,
I found that an app's ads can't be blocked in AG pro for ios, but can be blocked in AG for Android.
Well, AG for Android shows the ad's link is "m.104.com.tw/api/1.0/ad/.....", which is blocked by the filter's rule (it detected "/ad" in the URL's path) even I don't block the URL in my user filter of AG for Android.
Well, I can also manually input "||m.104.com.tw/api/1.0/ad^" in the user filter of AG for Android.

When I try to do so in AG pro for ios, the blacklist of Adguard pro for ios doesn't accept the format.
I guess that the blacklist of AG pro for ios only accepts to be inputted domain names.
Why do you design so?
AG for Android can do. But AG for ios can't do.
That makes Adguard pro for ios be unable to block ads if I only want to block the URL's path and don't want to block the whole domain.
Please improve it.
Thanks.

**Comment by ameshkov** [comment]
That's due to how it works.

AG for Android filters ALL the traffic and is able to retrieve all the request data (URL, headers, and such). That's why it is quite more powerful.

AG for iOS operates on the DNS-level only. This means, that it sees domain names only, and that's all.

**Comment by ameshkov** [comment]
More info about DNS filtering:
https://kb.adguard.com/en/general/dns-filtering-android

**Comment by lancelot-moon** [comment]
Thanks a lot for your reply!
I understand your meaning.
Is AG for ios still unable to block "m.104.com.tw/api/1.0/ad/" even if you add "||m.104.com.tw/api/1.0/ad^" in your official filter?
Well, I give up if no way.

@AdamWr
Hi AdamWr,
May you add "||m.104.com.tw/api/1.0/ad^" in your official filter?
That's an ad banner in 104 app.
Android:
https://play.google.com/store/apps/details?id=com.m104
ios:
https://itunes.apple.com/tw/app/104%E5%B7%A5%E4%BD%9C%E5%BF%AB%E6%89%BE/id437817158?l=zh&mt=8

Thanks.

**Comment by ameshkov** [comment]
> Is AG for ios still unable to block "m.104.com.tw/api/1.0/ad/" even if you add "||m.104.com.tw/api/1.0/ad^" in your official filter?

This rule will work in Safari only.

**Comment by ameshkov** [comment]
@lancelot-moon Adam may not hear us, specific rules should be reported the AdguardFilters repo.

Added your rule to the mobile ads filter:
https://github.com/AdguardTeam/AdguardFilters/commit/6d594bd80dd93a3da0f4195b974feada28862588

**Comment by lancelot-moon** [comment]
@ameshkov 
@AdamWr

Hi,
Say sorry first.
Today, I tried 104 app.
If blocking "m.104.com.tw/api/1.0/ad/", there is no the under ad banner.
Other features on 104 app is normal.
But it only has the problem in one place (mark with the orange frame).
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/go6mqPH.jpg)
</details><br/>

It means, "The server lost its consciousness, please refresh, thanks. (E500)"
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/iVM2xHe.png)
</details><br/>

Afterwards, I disabled Mobile ads filter.
But I still was unable to visit that place on 104 app because it's blocked by English filter's rules.
It's useless even I added m.104.com.tw in the whitelist.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/wbH2eXL.png)

![image](https://i.imgur.com/2wVgFWO.png)

![image](https://i.imgur.com/Z0Ytn5W.png)
</details><br/>

Finally, I added "@@||m.104.com.tw/api/1.0^" in my user filter.
Those URLs were not blocked by English filter, but the under ad banner appeared.
Do you have other solutions or rules to block ads under the path "m.104.com.tw/api/1.0/ad/" and let me normally visit it?

Thanks.

**Comment by zebrum** [comment]
@lancelot-moon first of all try to turn off all the filters and check if the issue persist. after that we can decide in what repo the issue should be present.

**Comment by lancelot-moon** [comment]
Without all of AdGuard's filters, the issue doesn't exist.

"The server lost its consciousness, please refresh, thanks. (E500)"
It's because that "m.104.com.tw/api/1.0/ad/" is ONLY blocked by English filter or Mobile ads filter.
It causes that one feature on 104 app is abnormal.

**Comment by zebrum** [comment]
@lancelot-moon moved to filters repo: https://github.com/AdguardTeam/AdguardFilters/issues/7763

**Comment by Alex-302** [comment]
@lancelot-moon 
I need a test account. Please add it to this issue
https://github.com/AdguardTeam/AdguardFilters/issues/7763
