### ISSUE TITLE
Please update the contents of Taiwan's iTunes App Store (PRO/Free) to Traditional Chinese.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#497]
@ameshkov
@aalpatkina

Hi,

The now content of iTunes App Store (PRO) is a little different with what on oneskyapp.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/xSMfr3N.png)

![image](https://i.imgur.com/VQx93hn.png)
</details><br/>

The back to school promo was ended.
The new description only added the sentence, "AdGuard Pro for iOS is an iPhone, iPad and iPod Touch mobile app which lets you block domains."

And then I completed their Traditional Chinese translations for iTunes App Store (PRO) and iTunes App Store (Free).
After you update the under new English content on oneskyapp, I will soon translate.
"AdGuard Pro for iOS is an iPhone, iPad and iPod Touch mobile app which lets you block domains."

On Taiwan's iTunes App Store (PRO), the AG Pro's description is still English.
On Taiwan's iTunes App Store (Free), the AG's description is Traditional Chinese description, but that content is different with what on oneskyapp.

Hope that you use my Traditional Chinese translations for Taiwan's iTunes App Store (PRO) and iTunes App Store (Free).

Thanks.

**Comment by ameshkov** [comment]
@lancelot-moon in order to update the app description, we should publish a new update.

We'll definitely do it rather soon.

**Comment by vbagirov** [comment]
@lancelot-moon we've released the v1.3.2 of the Pro version, please check if everything is ok with Traditional Chinese translation there.

**Comment by lancelot-moon** [comment]
@vbagirov 

Dear Sir,
Thank you very much!!

I give a feedback about some problems.
For AdGuard Pro:
1. I visited AdGuard Pro on app store via my iphone.
The title of app isn't transated to Traditional Chinese.
![Image of Yaktocat](https://i.imgur.com/VlmPqS0.png)

2. The description on app store via my iphone and what on app store (website) are a little different.
![Image of Yaktocat](https://i.imgur.com/zaxVGro.png)

https://itunes.apple.com/tw/app/adguard-pro-adblock-and-privacy-protection/id1126386264?mt=8

3. I updated some content since the description is updated a little on oneskyapp.
So hope that you can update my Traditional Chinese translation for app store next time.
![Image of Yaktocat](https://i.imgur.com/zaxVGro.png)

4. I updated some strings' Traditional Chinese translations on oneskyapp.
But I don't see the Traditional Chinese translations are updated in AdGuard Pro v1.3.2.
Maybe you anew take Traditional Chinese translations for AdGuard Pro next time.

For AdGuard Free:
1. https://goo.gl/Q4xkvU
That Traditional Chinese translations of app's title and description on app store are not mine.
I think they're provided by a Simplified Chinese translator.
Hope that you use my Traditional Chinese translations on oneskyapp.

Thanks.

**Comment by lancelot-moon** [comment]
@vbagirov 
@aalpatkina

Hi, I met an issue.
When I tried to change Adguard Pro to AdGuard Pro, it showed this error.
I see that you change "Adguard" to "AdGuard" in the description of iTunes App Store (PRO/Free).
But the app's name is still "Adguard" on oneskyapp's  iTunes App Store (PRO/Free).
Please solve them. Thanks.
![Image of Yaktocat](https://i.imgur.com/PgRvEjD.png)

**Comment by aalpatkina** [comment]
Hi, 
Yes, it happens because of a character limit. We'll solve this problem.

Thank you!

**Comment by lancelot-moon** [comment]
Hi,
I also found that you added "Glossary" in some platforms' translation section.
But I don't have the access to approve these new strings' translations.
![Image of Yaktocat](https://i.imgur.com/iCw2pdH.png)

Thanks a lot!

**Comment by aalpatkina** [comment]
No, it doesn't mean that we added new strings.
Glossary contains certain terms, which you can see above the original phrases, like here
![image](https://user-images.githubusercontent.com/31620257/31818517-2f068aa0-b5a1-11e7-85dd-fa51e45c8c71.png)

**Comment by lancelot-moon** [comment]
@aalpatkina
Хорошо, спасибо!
Another thing...
Did you receive my email?
The email's title is "Randomly draw lots for Taiwanese net friends".
It's ok if you deny the suggestion.
Discuss by email, not here.
B/R

**Comment by wang8850** [comment]
on issue

**Comment by vozersky** [comment]
translation has been updated :)
@aalpatkina check the previous message by @lancelot-moon please

**Comment by lancelot-moon** [comment]
@ameshkov 
@vozersky 
@aalpatkina

Hi,
I don't see the update on Taiwan's iTune app store.
Maybe it's because AdGuard Pro for iOS v1.3.3 is still not released.

For AdGuard Pro for iOS:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/VTaH1hS.png)
</details><br/>

For free AdGuard for iOS:
Title:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/OgQS89D.png)
</details><br/>

Description:
The original description is translated by a Simplified Chinese translator from China, not Taiwan.
He converted Simplified Chinese to Traditional Chinese and let you use these translations on Taiwan's iTune app store.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/PsUvTPG.png)
</details><br/>

So I hope that you update the contents of both of AdGuard Pro for iOS and free AdGuard for iOS on Taiwan's iTune app store.

Thanks.

**Comment by aalpatkina** [comment]
@lancelot-moon it seems to me that I answer the same comments about the translation updates for 'AdGuard for iOS' and 'AdGuard Pro for iOS'.
So, I've already told you, that we will update all the translations in our new release version (1.3.3)

Don't worry. You will be able to see the new content next week.
