### ISSUE TITLE
widget positioning issue on iOS 9.3.3

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#499]
Phone 5s, iOS 9.3.3. The widget looks like that:

![image](https://user-images.githubusercontent.com/15856304/30954919-9b395c34-a43a-11e7-88e1-4b06f4f35109.png)

### Your environment

* Device model and storage size: iPhone 5s
* Operating system and version: 9.3.3
* Has other ad blocking solutions installed which have widgets, too

**Comment by IvanIin** [comment]
We removed today widget for ios versions below 10
