### ISSUE TITLE
Add filter subscription by URL

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForiOS#50]
Add option to subscribe for a filter by URL.
Requester here DHH-171-66322

**Comment by ameshkov** [comment]
You'd better redirect user here so we can discuss this feature request in detail.

You see, there is a problem with iOS content blocker API: they limit the content blocker size by 50k rules.
So if user will import some huge subscription (like unmodified easylist) it won't work.

**Comment by worldsdream** [comment]
It's nice if we can add our own url, if user ads a filter and in total is more then 50K rules, a message should be shown that the limit is 50k and he needs to configure the lists properly for not exceeding 50k.

**Comment by ameshkov** [comment]
> message should be shown that the limit is 50k and he needs to configure the lists properly for not exceeding 50k.

Btw, this message will appear in v1.0.8.

**Comment by worldsdream** [comment]
Great :) i'm not a beta tester, otherwise I would have known by now. I signed up for the adguard pro beta.
