### ISSUE TITLE
Traditional Chinese translations for filters in the various platforms.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#500]
@ameshkov
@aalpatkina 

Hi,
I wrote an email to aalpatkina.
But I don't get a reply.
In the past, the Traditional Chinese translations for filters in the various platforms (Windows, Mac, Android and iOS) were incomplete.
They are Simplified Chinese and English, not Traditional Chinese interface.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/5Mdwhvi.png)
</details><br/>

Several weeks ago, I found the location of filters' translations.
And then I completed Traditional Chinese translations of filters.

But that headline was changed to "Deprecated".
Will you take my Traditional Chinese translations of filters for the various platforms there?

Thanks.

**Comment by aalpatkina** [comment]
Hi,

Sorry, but now we are thinking about how to structure our projects better and that is why we need a little time to bring everything in Miscellaneous projects in order. 

Please, don’t worry, all of your translations will be uploaded soon.

Thanks for your help!

**Comment by wang8850** [comment]
on issue

**Comment by wang8850** [comment]
on issue
