### ISSUE TITLE
[Beta] Notification of incorrect release

### ISSUE THREAD

**Issue by X8716e** [AdguardTeam/AdguardForiOS#503]
Notification came several minutes ago via both email and TestFlight notifications announcing a “new release” to test. It’s for 1.3.2 (108) which is the current beta not a new one. So within TestFlight there is no new beta release available for testing.

**Comment by ameshkov** [comment]
Hm, we've just published 1.3.2 to release, not to beta

**Comment by X8716e** [comment]
Okay, well, and here I was excited about a new release for beta. Regardless, you’ll see the pics on the Adguard Forum. Thank-you.

**Comment by ameshkov** [comment]
Weird:(

https://forum.adguard.com/index.php?threads/non-existent-new-beta-release.25821/
