### ISSUE TITLE
NEVirtualInterfaceWriteMultipl:1947 NEVirtualInterface Failure in NEVirtualInterfaceWriteMultipleIPPackets at line 1947

### ISSUE THREAD

**Issue by snowydane** [AdguardTeam/AdguardForiOS#504]
### Error
NEVirtualInterfaceWriteMultipl:1947 NEVirtualInterface Failure in NEVirtualInterfaceWriteMultipleIPPackets at line 1947.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/11337105/31524633-4ecb93ee-afbb-11e7-88d0-e0595fd0568a.png)

</details>

### Customer ID 
1535769

### Your environment
iPhone 7 MPRL2QN/A
iOS 11.1 (15B5078e)
WiFi

**Comment by IvanIin** [comment]
fixed

**Comment by sakhi-sl** [comment]
How it was fixed?

**Comment by Versty** [comment]
@sakhi-sl This is the old one bug. If you have a similar or related issue, I would suggest you create a [new discussion](https://github.com/AdguardTeam/AdguardForiOS/issues/new/choose).
