### ISSUE TITLE
Keyboard covers up text field in custom filters

### ISSUE THREAD

**Issue by IvanIin** [AdguardTeam/AdguardForiOS#505]
> For some reason when I edit user filters on iOS the keyboard covers up the text so I can’t see it

![dmamx6evoaelkxp](https://user-images.githubusercontent.com/28860202/31538466-52f6adca-b00e-11e7-8b7f-bb9986fcedda.jpg)

**Comment by IvanIin** [comment]
fixed

**Comment by wang8850** [comment]
on issue
