### ISSUE TITLE
Rule from filter is not applying on ios device

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#506]
https://forum.adguard.com/index.php?threads/resolved-voetbalwedstrijdenvandaag-nl.26050/#post-156378

Please have a look at this topic. 

When I add that rule in my user filter. It works. When I remove it. I see adblock warning. 

The filters are updated on my ios device. 

Ios 9. Adguard pro stable.

**Comment by zebrum** [comment]
@worldsdream please send logs from the AdGuard app to support and post here Id support number. Thank you.

**Comment by wang8850** [comment]
on issue

**Comment by worldsdream** [comment]
Hi. I did sent logs from adguard app. 

I did not get any id support number.

**Comment by worldsdream** [comment]
Ok got ID: 1212314

**Comment by zebrum** [comment]
@worldsdream what filters are enabled? It seems that you went over 50000 rules limit.

**Comment by worldsdream** [comment]
Please see screenshot. I dont have the 50k limit. 

Screenshot uploaded: https://ibb.co/esgQY6

Filters:

Dutch
English
Annoyance
Spyware
Mobile ads
Safari

**Comment by zebrum** [comment]
@IvanIin please take a look into logs again.

**Comment by worldsdream** [comment]
It has nothing to do with rules limit. 

Please enable ONLY english filter and dutch filter. You will see the problem.

**Comment by zebrum** [comment]
@worldsdream yeah, I get it. 

not reproduced on my side though.

**Comment by worldsdream** [comment]
Weird. Stable adguard pro. Ios 9.

**Comment by worldsdream** [comment]
It is also reproduced at my end on an ipad ios11. Adguard stable. (Not pro). Also on iphone from a friend (adguard stable. Not pro). 

So it has nothing to do with ios.

**Comment by worldsdream** [comment]
Any update?

**Comment by ameshkov** [comment]
The rule is `voetbalwedstrijdenvandaag.nl#@##sponsorText`
It is in the Dutch filter already: https://filters.adtidy.org/ios/filters/8_optimized.txt

What we do need to see is the compiled filter of yours -- it will be attached to the support message when you're trying to send it via the app.

Could you please get it from there and attach here to this issue?

**Comment by worldsdream** [comment]
Can't you look into the support ID? I did sent it over there.

**Comment by zebrum** [comment]
does reinstalling helps? or it is the same?

**Comment by worldsdream** [comment]
Reinstalled the adguard pro app. It worked.

**Comment by worldsdream** [comment]
I did not reinstall the app on adguard and it worked. 

Or something changed in filterlist or the website changed the adblocked detection

**Comment by worldsdream** [comment]
I did not reinstall the adguard app on my ipad. 
It is working fine now. 

That means the website changed the adblock detection or something changed in the filterlist.
