### ISSUE TITLE
Incorrect blocking on page https://mobil.blocket.se/

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardForiOS#508]
https://mobil.blocket.se/newad.html
The page doesn't load at all, it says the URL is blocked by a content blocker:
When AdGuard is disabled, the page loads just fine.

### Actual behavior

<details><summary>Screenshot:</summary>

![image1](https://user-images.githubusercontent.com/32528702/32148050-87910c40-bcf9-11e7-8fc8-a0c71bb154ac.png)

</details>

### Your environment

* Device model and storage size: iPhone
AdGuard version:    1.3.1.82
* Operating system and version: 10.3.2
* Browser Safari
Filters enabled:   2,3, 14, 6, 12, 207, 211, 225, 209

**Comment by zebrum** [comment]
moved here: https://github.com/AdguardTeam/AdguardFilters/issues/7295
