### ISSUE TITLE
report some issue about aduard for iOS

### ISSUE THREAD

**Issue by justforadblock** [AdguardTeam/AdguardForiOS#511]
I simply talk about it， 
this rule https://easylist-downloads.adblockplus.org/easylistchina.txt it's worked for 
 https://itunes.apple.com/us/app/adblock-browser/id1015653330?mt=8 

but doesn't work in adguard..
 [according to the ChinaList rule manager](https://imgur.com/a/IBj4g) ,  like some Incompatible problem in adguard app

you can test it.
1. use adguard && adblock-browser subscribe the same rule https://easylist-downloads.adblockplus.org/easylistchina.txt
2.  go visit http://zhongzicili.me/ on safari and check the page,  you can see adguard doesn't clean the ads, but the adblock-browser is very clean~~

https://forum.adguard.com/index.php?threads/report-some-issue-about-aduard-for-ios.26527/

**Comment by zebrum** [comment]
@justforadblock the link https://github.com/AdguardTeam/AdguardForiOS/issues/url dowsn't work

**Comment by justforadblock** [comment]
@zebrum 
?  what's you mean

**Comment by zebrum** [comment]
oh, i get it. wrong url.

**Comment by justforadblock** [comment]
@zebrum  could you reproduce?

**Comment by justforadblock** [comment]
does any body here?  
^ ^

**Comment by ameshkov** [comment]
@justforadblock have some long holidays here, @zebrum will be back today:)

**Comment by zebrum** [comment]
so this is how it looks in safari with AG: 
https://uploads.adguard.com/up03_qedv9.png

and this is how it looks in adblock browser:

https://uploads.adguard.com/up03_3hy65.png

in both cases EasyList China filter enabled. no difference for me. I'm using vpn to be able to reach this site.

**Comment by justforadblock** [comment]
in my case,

in safari with AG
https://imgur.com/a/hYVpb

in adblock browser:
https://imgur.com/a/lLrQH

adblock browser settrings:
https://imgur.com/a/0cIm4

**Comment by justforadblock** [comment]
@zebrum  use adblock browser visit again,  chinalist has been update

**Comment by zebrum** [comment]
@justforadblock nothing has changed on my side. 
provide me with 2 screenshots from safari and adblock-browser

**Comment by justforadblock** [comment]
@zebrum
screen shot on adguard 
https://imgur.com/a/He5iI

on safari
https://imgur.com/a/LU0VQ

**Comment by zebrum** [comment]
moved here: https://github.com/AdguardTeam/AdguardFilters/issues/7764
