### ISSUE TITLE
[UI][Feature Request] Support scaling for iPhone X (18:9)

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardForiOS#513]
![2017-11-03 19 52 15](https://user-images.githubusercontent.com/541725/32391288-c1de6308-c0d1-11e7-8078-2ea5377cd93c.png)

Support  for iPhone X (18:9)

**Comment by danidoedel** [comment]
Yes... please! So ugly right now... ;)

**Comment by mikeoleary7528** [comment]
Couldn’t agree more

**Comment by zebrum** [comment]
should be ok in the next build

**Comment by zebrum** [comment]
@Vincent-Michael @danidoedel @mikeoleary7528 guys! is anyone of you in beta test program? any difference with new beta on iPhone X?

**Comment by danidoedel** [comment]
@zebrum Yeah, much better now ;) Thank you!

Not sure if that is iPhone X related (missing active filter rules etc). If you click on „edit“ and go back it will be displayed though:

![87f34e70-1acd-4663-8bb0-cf716bd4679b](https://user-images.githubusercontent.com/10995998/32653609-bc72e6d2-c608-11e7-98b2-64c20c43df83.jpeg)

Also, the splash screen looks a bit weird (black bars at the top and bottom for a second). Can‘t screenshot it but I‘ll try if I can record it later.

**Comment by Vincent-Michael** [comment]
https://www.dropbox.com/s/y1wwgi90u0yq5f9/2017-11-11%2011.47.20.mp4?dl=0 yep, has bad look

**Comment by danidoedel** [comment]
@zebrum Another glitch while saving filter rules:

![8bd43711-ac25-43e7-9b89-ebab57012166](https://user-images.githubusercontent.com/10995998/32689495-6d5b04a6-c6e6-11e7-8c83-e3c32c916b4c.jpeg)

**Comment by IvanIin** [comment]
fixed

**Comment by Superkloton** [comment]
@IvanIin I hope you also fixed the problem where you can’t edit the last filters in the user filter page when the list of filters is longer than one page? They would be covered by the keyboard and there’s no way to reach them on the iPhone X.

**Comment by zebrum** [comment]
@Superkloton yeah, that has been fixed.

**Comment by Superkloton** [comment]
Awesome! 👍🏻

**Comment by danidoedel** [comment]
@zebrum New beta is much better on iPhone X. Just one thing I noticed, this text looks a bit too big for the size of the box:

![dcc15ffd-e673-4e32-9367-d0657caed4e1](https://user-images.githubusercontent.com/10995998/33141458-78d3bdf2-cfb3-11e7-8d7e-9167b932448f.jpeg)

I would suggest to use the same font size used here:

![98c16fcb-89da-46f8-9b9f-af472d6b0744](https://user-images.githubusercontent.com/10995998/33141476-913745bc-cfb3-11e7-8125-810b05bcbcc8.jpeg)

**Comment by zebrum** [comment]
Soon I hope we will get our iphone X! 

@IvanIin please pay attention to this screenshots.

**Comment by danidoedel** [comment]
@zebrum  Another small glitch. Watch the search field jumping down a few pixels:

![e4d10650-8f9f-44b0-ad19-966bbab7f335](https://user-images.githubusercontent.com/10995998/33232093-3b7ad8f6-d200-11e7-9222-e3645eb35eb9.gif)
