### ISSUE TITLE
Question re: beta release

### ISSUE THREAD

**Issue by X8716e** [AdguardTeam/AdguardForiOS#514]
Being in the beta program, I’m curious as to when a new beta will be released for testing as I see 1.3.3 is apparently ready for testing. Also, from what I can gather in release postings, seems 1.3.2 (109) is the current beta, though I’m still on 1.3.2 (108) for unknown reasons. Thank-you.

**Comment by mikeoleary7528** [comment]
Same^^

**Comment by zebrum** [comment]
new beta is in alpha test now and will be released soon

**Comment by X8716e** [comment]
@zebrum ,
Thank-you for letting us know. Now about alpha testing... ;)

**Comment by zebrum** [comment]
@X8716e the first beta has been published

**Comment by X8716e** [comment]
@zebrum ,
Indeed. I installed it as soon as I was notified via email & Tesflight. Thank-you to all involved in its creation. I nearly logged in here immediately to sumbit two reports. One regarded the VPN ‘icon’ not being visible when actively connected on both my iPad and iPhone. The was somewhat iPad specific. The ‘domain counter’ i.e. the total number of domains installed within the custom DNS blacklist was not visible on either device, though it was active and functioning just fine. It was self-correcting on my iPhone. left both devices connected to my home network, which wasn’t purposeful as I (nearly) always disconnect before sleeping unless, as in this case, I forget due to over-tiredness. Regardless, upon awawking and picking up my iPhone, I immediately noticed the VPN icon as being visible on it. I then reached for my iPad to see if it did the same, but it had not. However all it took to correct was disconnecting, uninstalling the previous build, and (re)installing beta 1.3.3 (144) as a clean install.

**Comment by subvertallchris** [comment]
Sorry to piggyback on someone else's issue, but where can the source for your beta releases be found?

**Comment by zebrum** [comment]
@subvertallchris sign the form from this [article](https://blog.adguard.com/en/adguard-beta-test/)

**Comment by zebrum** [comment]
@X8716e is the tunnel mode the same on both devices?

It's funny, but no vpn sign in full-tunnel now.

**Comment by X8716e** [comment]
Yes. But after more usage, it apparently became a random behavior. Now, however, I find I can keep the VPN icon visible by initially starting out in split-tunnel, then switching to full-tunnel. *But* when switching, normally either device would always disconnect for a brief moment before reconnecting. Now, the network oftentimes stays connected while switching tunnels. So long as it stays connected, that is when the VPN icon remains visible. Of note: I have not tested whether the tunnel actually switches modes at those times or not. I've been going by sight only - while switching tunnels and seeing the VPN icon remaining visible or not.

**Comment by X8716e** [comment]
@zebrum ,
I'm currently connected via iPhone. And right up to literally in the middle of writing this, the VPN icon was visible. Full-tunnel. Attaching screenshots from when I initially connected:
![34597595-3c60-4985-a76f-11d0489b1039](https://user-images.githubusercontent.com/18148748/32912186-42a1eee2-cadc-11e7-94ff-413b35eafa66.png)
![9d4237c7-4740-49c7-8fdc-0954387ef05a](https://user-images.githubusercontent.com/18148748/32912187-42cdc300-cadc-11e7-868d-6ecef24b36f8.png)
![e5149abe-e5de-4dc0-872e-38e8bd822d7a](https://user-images.githubusercontent.com/18148748/32912190-43195356-cadc-11e7-9492-aee467669f74.png)
What I have noticed with near certainty is that my iPad stays connected full-tunnel w/ VPN icon visible for total time I am using it but icon only remains on iPhone for very limited time period.

**Comment by vozersky** [comment]
@X8716e 1.3.3 beta should be fine
