### ISSUE TITLE
Custom IPv6 DNS servers

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#515]
Details:
https://github.com/AdguardTeam/AdguardDNS/issues/202

> Warning You are connected to an ipv6-only network. In such networks you cannot use custom DNS servers. The 'System Default' DNS settings will be used instead.

@IvanIin please remind me what's wrong with supporting custom IPv6 DNS servers in IPv6-only networks?

**Comment by IvanIin** [comment]
Many ipv6-only networks use DNS64/NAT64 technologies, which allow access to ipv4. If you configure a custom ipv6 DNS server, only ipv6 addresses will be reachable.
