### ISSUE TITLE
Exception list should have higher priority

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForiOS#520]
### Steps to reproduce

in DNS Setting add to Blacklist this rules
` ||lenta.ru^ `
`@@||lenta.ru^
 `

### Expected behavior

domain `lenta.ru` is unblocked
### Actual behavior

domain `lenta.ru` is blocked

**Comment by X8716e** [comment]
This is something that when corrected would allow users to create a so-called “reverse whitelist” specific to the DNS custom domain lists. I find the term “reverse whitelist” a bit too vague in reference to the the wide scope of applications/uses it would open up to us. For example, say I wanted to block all connections except to one specific domain. I’d now be able to by using a single wildcard within the DNS Blacklist, effectivley blocking all connections. I then add the single domain I wish to access within the DNS Whitelist, thus allowing me to achieve this objective. This is useful for both research purposes and for routing your traffic to a specific sever using only Adblock Pro.

**Comment by IvanIin** [comment]
fixed
