### ISSUE TITLE
Rework widget feature

### ISSUE THREAD

**Issue by LaxusiC** [AdguardTeam/AdguardForiOS#522]
It's kinda annoying when you need to enable or disable adguard, it always open the app and waste a lot of time instead of it should be enable / disable for just 1 click

Is it possible to rework this

**Comment by zebrum** [comment]
Hello @LaxusiC 
[here](https://github.com/AdguardTeam/AdguardForiOS/issues/312#issuecomment-318376189) is the answer to your question
