### ISSUE TITLE
No VPN icon on mobile connections in iOS11.2 b1

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#523]
### Actual behavior:

<details> <summary> screenshot </summary>

![image](https://user-images.githubusercontent.com/15856304/32688713-d5672820-c6de-11e7-8072-7708b1da9914.png)

</details>

### Expected behavior

<details> <summary> screenshot </summary>

![image](https://user-images.githubusercontent.com/15856304/32688714-df48b002-c6de-11e7-88e9-27a66ad45e83.png)

</details>

### User ID: 
1602225

**Comment by X8716e** [comment]
I am experiencing a similar problem. I've not tested cellular, however. My specific issue is the VPN icon not being visible in full-tunnel mode. It is visible only using split-tunnel. I find full-tunnel mode preferable & always use it. Until now. My custom DNS blacklist still functions, but it's 'weird' not seeing that icon confirming my blacklist is at work. I'm not submitting screenshots, though I do have them. The behavior has been erratic, at times showing the VPN icon in full-tunnel mode, but nearly all of the time it fails to do so. If screenshots are required as confirmation, please let me know. I've been saving them. I am also running 11.2b1.

**Comment by zebrum** [comment]
not a bug
I should have wrote about it in beta-tester's note though.
