### ISSUE TITLE
After first editing blacklist, enabling DNS setting of AdGuard Pro sometimes causes the internet disconnection.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#524]
@ameshkov

Hi,
After first editing blacklist, enabling DNS setting of AdGuard Pro sometimes causes the internet disconnection.
Sometimes, not always.
The only way of recovering internet connection is rebooting iphone.
The bug also exists in the previous version of AdGuard Pro.
I tested it in Wi-Fi.
I am not sure if it also occurs in cellular network because my only sim card is in my Android phone.

The Wi-Fi icon exists.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/JB21Kav.png)
</details><br/>

After first editing blacklist, enabling DNS setting of AdGuard Pro sometimes causes the internet disconnection.
The Wi-Fi icon disappeared.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/gsaSUqN.png)
</details><br/>

Though the internet disconnection occurred (no Wi-Fi icon), it still shows that it's connected to Wi-Fi in iOS Wi-Fi setting.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/qdzH11j.png)
</details><br/>

B/R

**Comment by LaxusiC** [comment]
I have this too, after I edited my blacklist rule (49k rules) and it started not working

**Comment by lancelot-moon** [comment]
If you add too much rules in the blacklist, AdGuard Pro crashes.
For example: EasyList China + EasyList

However, I only have around 10 rules in my blacklist.
After first editing blacklist, enabling DNS setting of AdGuard Pro sometimes causes the internet disconnection.
The only way of recovering internet connection is rebooting iphone.

**Comment by LaxusiC** [comment]
It's crashed because your device is low spec, I have iPad Pro and it run smoothie even with 30k rules, just added another today and the bug happen (not crashed)

**Comment by LaxusiC** [comment]
Look like if I have over 40k rules, DNS stop working or can't connect. Works fine with 30k rules, that suck tho

**Comment by zebrum** [comment]
@lancelot-moon split or full tunnel?

**Comment by lancelot-moon** [comment]
@zebrum 

Is it associated to split or full tunnel?
I remember that I met the issue both with split or full tunnel.

**Comment by zebrum** [comment]
for me it is not clear how to reproduce this bug. 
As you said it happens sometimes in both modes.  and with both connection types. 
rarely reproducible on our test devices unfortunately

**Comment by lancelot-moon** [comment]
If I meet the issue again, I'll record it by video.
Thanks.

**Comment by lancelot-moon** [comment]
The disconnection of Wi-Fi occurred again when enabling DNS setting.
But I didn't edit the blacklist this time.
Generally, I use a router's Wi-Fi for internet.

Today, I use my Android phone's hotspot for sharing network because my iPhone doesn't have cellular network.
Afterwards, I found that I already manually set AdGuard DNS server in the Wi-Fi setting of iOS setting in the past.

https://www.youtube.com/watch?v=5bN3U_yZK58&feature=em-upload_owner

Is there a conflict if setting AdGuard DNS server in the Wi-Fi setting of iOS setting and enabling AdGuard DNS server in AdGuard Pro for iOS?

**Comment by lancelot-moon** [comment]
I tried AG Pro v1.2.1.
Sometimes the Wi-Fi disconnection also occurred when enabling AG protection.
The issue exists from the past until now.

**Comment by ameshkov** [comment]
But what about logs? Is there anything helpful there?

From what you tell it seems that AdGuard's tunnel started crashing and to figure why we need to take a look at the logs.

**Comment by lancelot-moon** [comment]
I think the issue is not difficult to be reproduced.
Constantly editing blacklist or enabling/disabling Safari's filters, there is the chance that the Wi-Fi disconnection occurrs when enabling AG protection.

Ok, I'll provide the log when it happens again.

It's midnight in Russia.
Sleep early, good night.

**Comment by ameshkov** [comment]
Thx, good night:()

**Comment by lancelot-moon** [comment]
I have sent the bug report to support@adguard.com at 21:34 (GMT+8) on 4th Dec, 2017.
User ID: 1425202
Subject: [Adguard Pro for iOS] bug report

**Comment by IvanIin** [comment]
@lancelot-moon 
This is a very unusual situation. According to logs, you have an old version of AdGuard VPN tunnel installed. It is possible that one of AdGuard updates went wrong at some point, and you ended up with an old VPN profile instead of a new one (or both old and new VPN profiles simultaneously). You can check this in the system settings, in the 'VPN' section. Again, this is a very, very strange and uncommon situation. iOS should always delete the older tunnel version. I can see only one solution to this: reinstalling the app. Just in case, after you uninstall the app, please make sure that AdGuard VPN profile has been deleted too.

**Comment by lancelot-moon** [comment]
Several days ago, I downgrade AdGuard Pro from v1.3.2 to v1.2.1.
Today, I just directly upgrade from v1.2.1 to v1.3.2 for the test.
Maybe that's why you see old VPN profile.
I'll remove and reinstall AdGuard Pro.
Try later.

**Comment by lancelot-moon** [comment]
@ameshkov 
@IvanIin 

Hi,
I again sent the bug report to support@adguard.com at 00:14 (GMT+8) on 5th Dec, 2017.
User ID: 1425202
Subject: [Adguard Pro for iOS] bug report

No sim card in my iphome. No cellular network.
I first removed AdGuard Pro and then rebooted iphone & installed AdGuard Pro for iOS v1.3.2.
1. I again rebooted iphone and didn't connect to Wi-Fi. No any internet connection.
2. I ran AdGuard Pro first, and it showed a warning when trying to enter AdGuard Pro's DNS setting because of no internet connection.
3. Close AdGuard Pro.
4. Connect to Wi-Fi.
5. Open AdGuard Pro and then edit blacklist.
6. Enable DNS Protection.
Wi-Fi disconnection occurred!

**Comment by zebrum** [comment]
@lancelot-moon those wi-fi disconnection from your video is normal behaviour! 
@IvanIin can tell us why AG VPN works like that in this case.

**Comment by lancelot-moon** [comment]
Hi,
Why do I must reboot iphone for relieving Wi-Fi disconnection when enabling AdGuard DNS protection if you mean it's normal behavior?

**Comment by zebrum** [comment]
of course it is not normal.
but does the phone must be rebooted every time when wi-fi disconnection happens?

**Comment by lancelot-moon** [comment]
Yes! Rebooting iphone is necessary.
Otherwise, enabling AdGuard DNS protection will always cause Wi-Fi disconnection in that situation.

**Comment by zebrum** [comment]
probably this situation with old tunnel related to downgrade procedure.
Did you try v1.3.3?

**Comment by lancelot-moon** [comment]
No, I already told that I first removed AdGuard Pro v1.2.1 and then rebooted iphone & installed AdGuard Pro for iOS v1.3.2.
I didn't directly update from v1.2.1 to v1.3.2.
The old tunnel should been deleted.

I found that you released AG Pro v1.3.3 this week.
I'll try if the issue still exists.

**Comment by lancelot-moon** [comment]
@ameshkov 

The issue still occurred in unreleased AG Pro v2.0.0 (124).

I tested unreleased AdGuard Pro v2.0.0 (124).

I edited blacklist/whitelist and tried between Full tunnel/Split tunnel.

And then my internet connection was always disconnected if enabling AdGuard VPN.
After disabling AdGuard VPN, my internet connection was back.
(I only use Wi-Fi because there is no sim card in my iPhone.
I am not sure if the issue will also occur in cellular network.)

I have sent the bug report to support@adguard.com at 20:50 (GMT+8) on 13th Jan, 2018.
User ID: 1425202
Subject: [Adguard Pro for iOS] bug report

**Comment by lancelot-moon** [comment]
Hi,

I just recorded the video when the bug occurred in AdGuard Pro beta v2.0.0(132).
https://youtu.be/2bldYPGtp8U

I also have sent the bug report at 23:30 (GMT+8) on 14th February, 2018.

 **User ID**: 1425202
 **Subject**: [AdGuard Pro for iOS] bug report

**Comment by lancelot-moon** [comment]
Keep the latest one and close this due to a duplication
