### ISSUE TITLE
Half-transparent pop-ups on udn.com 聯合新聞網 fan page via facebook app.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#526]
@ameshkov 
@AdamWr

Hi AdamWr,

https://github.com/AdguardTeam/AdguardFilters/issues/6703

Lancelot-moon:
> Adguard can remove ad pop-ups on ETNEWS via facebook app.
Why can it not remove half-transparent pop-ups on udn.com 聯合新聞網 fan page via facebook app?

AdamWr:
> Because they are provided in different way.
On ETNEWS this popup can be blocked by blocking ad server.
On udn.com this popup is provided by this script:
https://s.udn.com.tw/static/js/dist/bundle.mobile.js?2017081701
so to block this in Facebook app we would have to block s.udn.com.tw what would break the page.
Only proper way to hide this, it is using "cosmetic" rules which are impossible to use in-app.

Do you remember it?

Today, I do the test.
You can directly search "中火機組展延許可退件 台電人員：不發電了嗎？" on facebook app.
Read the news of udn.com 聯合新聞網 fan page on facebook app.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/5ZMtreD.png)
</details><br/>

https://udn.com/news/story/7238/2815798

Not every news on udn.com 聯合新聞網 fan page has ad pop-ups on facebook app.
You can first disable AdGuard and then find any news which have the ad pop-up on udn.com 聯合新聞網 fan page via facebook app for your test.

I found that Mobile ads filter of AdGuard for Android v2.10 can not only block the ad pop-up but also hide the half-transparent pop-up.
(I disabled all of official ad filters, except for Mobile ads filter and my user filter.)
I don't need to block s.udn.com.tw as what you said.

Without AdGuard:
That's the ad pop-up.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/3eG7L0b.jpg)
</details><br/>

With Mobile ads filter of AdGuard for Android v2.10:
Even the half-transparent pop-up is hidden.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/3CObhyd.png)
</details><br/>

AdGuard Pro for iOS v1.3.2 with AdGuard DNS server:
Although the ad is blocked, the half-transparent pop-up can't be hidden.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/XcchZgF.png)
</details><br/>

Why?
I feel curious!
May you explain about it?
I read the content of Mobile ads filter.
Only the 2 rules are about udn.com.
udn.com##.overlay-container
udn.com##.only_mobile.mm-slideout

Is it possible to block and hide the half-transparent pop-up if using AdGuard Pro for iOS v1.2.1 (system-wide ad blocking) with Mobile ads filter?

My AdGuard Pro for iOS is v1.3.2, not v1.2.1.
May you try to test?

Mobile ads filter of AdGuard for Android v2.10 can block and hide the half-transparent pop-up.
Can AdGuard Pro for iOS do so after improving?

Thanks a lot!

**Comment by AdamWr** [comment]
Hi,

I can't confirm it.
I still see "the half-transparent pop-up" for first visit on Android. I guess that it is basing on cookie/cache, because after I close this popup and then go to another article, I don't see it anymore, but if I close Facebook app and then go again to the same article I see this popup at the first visit.
Could you please check it again?

<details><summary>Screenshot</summary>

![udn](https://user-images.githubusercontent.com/29142494/32729084-e80c23d6-c882-11e7-9018-b8e44219f149.png)

</details>
<br>

I know that you also opened few issues in `AdguardFilters`, but there are many other new issues, so please be patient, they will be checked, but later :)

Regards,
Adam

**Comment by lancelot-moon** [comment]
Hi AdamWr,

Do you use AdGuard for Android v2.10 and enable Mobile ads filter?
I remember that there is still the ad pop-up on udn.com 聯合新聞網 fan page via facebook app when using older version of AdGuard for Android with Mobile ads filter.

I first tried many different udn news which have ad pop-ups on facebook app without AdGuard.
And then I enabled AdGuard for Android v2.10 with Mobile ads filter and visited those the same news.
There was no half-transparent pop-up anymore.

Well, I'll try again.

**Comment by AdamWr** [comment]
> Do you use AdGuard for Android v2.10 and enable Mobile ads filter?

Yes, I use AdGuard v2.10 and I have enabled Mobile ads filter.

**Comment by lancelot-moon** [comment]
I ONLY enabled Mobile ads filter.
The half-transparent pop-ups on udn.com 聯合新聞網 fan page via facebook app was also hidden by my AdGuard for Android v2.10.171 RC.
https://www.youtube.com/watch?v=qOVDdMtlYGw&feature=em-upload_owner

Why could your AdGuard for Android not hide that half-transparent pop-ups?
I have no idea.

I just want to know...
Is it possible to block and hide the half-transparent pop-up if using AdGuard Pro for iOS v1.2.1 (system-wide ad blocking) with Mobile ads filter since my AdGuard for Android with Mobile ads filter can do it?

B/R

**Comment by lancelot-moon** [comment]
> Yes, I use AdGuard v2.10 and I have enabled Mobile ads filter.

Did you also  enable HTTPS filtering in AdGuard for Android?

**Comment by AdamWr** [comment]
> Did you also enable HTTPS filtering in AdGuard for Android?

Yes, I also checked with only Mobile ads filter enabled and for first visit I see this popup in web browser built in Facebook app.
In Chrome or Firefox this popup is hidden on my end.

Do you know which rule block this popup at your end in web browser built in Facebook app?

**Comment by lancelot-moon** [comment]
I'm not sure which rule hid the half-transparent pop-ups on udn.com 聯合新聞網 fan page via facebook app.
I only enabled Mobile ads filter.
This is the log file for your reference.
https://app.box.com/s/fr2ou3xs8ssrxdg4z3ar9wqw6o1oheo9

Thanks.
