### ISSUE TITLE
Need a better layout of management for the blacklist. (Feature request)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#527]
@ameshkov
@vbagirov

Hi,
We ever discussed about that there.
https://github.com/AdguardTeam/AdguardForiOS/issues/486

The latest version of AdGuard Pro for iOS is just v1.3.2.
But you planned to add the feature of importing a filter from URL in v2.0.0, which is quite late.

You know AdBlock by FutureMind.
From AdBlock v4.0, it started to provide local DNS and DNS proxy log.
From AdBlock v4.1, it improved DNS proxy rules import and export.

Honestly, AdBlock has better layout of management for the filters.
Classified groups of filters and importing filters from URLs are totally what I want!

AdBlock's Setting:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/TW64qfN.png)
</details><br/>

The local DNS.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/IgHsstj.png)
</details><br/>

Oh my God! The classified groups of filters. <3 <3 <3
‧★,:*:‧\(￣▽￣)/‧:*‧°★*
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/YmhWs2p.png)
</details><br/>

Oh Jesus! It can import filters by URLs and choose where to save. 
Посыпать цветами (*￣▽￣)/‧☆*"`'*-.,_,.-*'`"*-.,_☆
Even AdGuard Pro for iOS is unable to do so now.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/hcESMNZ.png)
</details><br/>

It allows the format of a hosts file.
It's convenient.
I don't need to worry too much about the different formats of filters' sources.
Do you know NetGuard?
https://play.google.com/store/apps/details?id=eu.faircode.netguard&hl=zh_TW

If wishing adblock, need to download & install the latest NetGuard version from M66B GitHub, not from google play.
https://github.com/M66B/NetGuard/blob/master/ADBLOCKING.md

Its default link of the hosts file is StevenBlack's hosts file.
https://github.com/StevenBlack/hosts/blob/master/readme.md

Well, I can input the filter's url and choose to save the filter in which group.
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/J6Jzw8c.png)
</details><br/>

I made a group "StevenBlack" in advance.
That's the saved path.
But AdBlock has a bug.
It can't accept too many contents of a filter.
If the filters have too many contents, the process of filters' backup to iCloud sync is very slow.
Damn it! AdBlock does iCloud sync every time when opening it from the beginning.

The layout of AdGuard Pro for iOS's blacklist is very poor.
Especially, the system-wide ad blocking of AdGuard Pro for iOS has been removed, and it has no default filter for filtering all internet traffic.
The management of the blacklist becomes important!
AdGuard for Android still has the feature of system-wide ad blocking and those filters.
Although its layout of user filter is simple, it's ok.
But the poor layout of blacklist is a very obvious shortcoming in now AdGuard Pro for iOS.
We need and want to manually make the classified groups of filters and import filters from URLs.
And then please don't forget to give the button of manual updates for a user's all filters!

We can get the links of AdGuard filters there.
https://kb.adguard.com/en/general/adguard-ad-filters

I want to manually make myself English filter, Spyware filter, Social media filter, Annoyances filter, Mobile ads filter and EasyList China filter as my user filters...

Under the same Apple's policy, why can AdBlock do, but AdGuard Pro can't do?

Thanks a lot!

**Comment by bigdargon** [comment]
+1

**Comment by lancelot-moon** [comment]
Forget to say.
Hope that the user filter of AG for Android and the blacklist of AG Pro for iOS can be sorted according to names.

**Comment by LaxusiC** [comment]
I also want to request import and delete duplicate domain feature too

**Comment by lancelot-moon** [comment]
It seems that I misunderstood from the beginning.
Sorry...
Even if having System-wide Ad Blocking, AdGuard Pro only can use Simplified domain names filter and can not use English filter, mobile ads filter and others with local VPN because of the iOS structure, right? 

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/QZFDkDM.png)
</details><br/>

AdGuard for Android can block ads url path under a domain.
AdGuard Pro with System-wide Ad Blocking still is unable to block ads url paths under a domain.
The rule syntax in filters are not supported in iOS, right?
In System-wide Ad Blocking of AdGuard Pro v1.2.1, ads url paths are unable to be inputted in its blacklist.
It only accepts domain.

However, we still hope a better layout of management for the blacklist for new version of AdGuard Pro.

Thanks for your great work!
