### ISSUE TITLE
The filter of AdGuard DNS server was not working.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#528]
@ameshkov
@vozersky
@AdamWr

Hi,

My iOS is v11.1.2 in iPhone 6 Plus.
I use AdGuard Pro v1.3.2.
Generally, I surf on internet over a router's Wi-Fi because my iPhone doesn't have cellular network.
When enabling AdGuard Pro with AdGuard DNS server, the filter of AdGuard DNS server is working in this condition.

A Taiwanese net friend who uses iPhone X told me that ads were not blocked after enabling AdGuard Pro with AdGuard DNS server over Wi-Fi.
I felt strange.
I tried 2 different Wi-Fi sources for the test and met the same issue.
When enabling AdGuard Pro, the filter of AdGuard DNS server is working over a router's Wi-Fi.

However, the filter of AdGuard DNS server is not working when enabling AdGuard Pro over my Android phone hotspot's Wi-Fi.
I used "Auto" in the Wi-Fi setting's DNS of iOS setting.
And then I enabled AdGuard Pro with AdGuard DNS server.
I opened Mo PTT.
I found that ads on Mo PTT were not blocked.
So I went to view DNS Requests Log in AdGuard Pro.
Oh my God!
AdGuard DNS server didn't block those ads domains in Simplified domain names filter.
https://www.youtube.com/watch?v=qJJG52y7LQo&feature=em-upload_owner

For this issue, the temporary solution is copying and pasting the full contents of Simplified domain names filter in the blacklist for blocking ads since any ads domains in Simplified domain names filter are not blocked by AdGuard DNS server.

B/R

**Comment by zznosar** [comment]
Are or your friend using the same internet service provider?

When you or your friend added the adguard dns, did you specify a port in the dns?

It’s highly likely that the ISP is altering the connection that’s why ads are not getting blocked.

**Comment by lancelot-moon** [comment]
A unfamiliar net friend wrote mail to me for reporting the issue.
I also verified the issue by myself.
Different ISP.
One is a router's Wi-Fi.
Another is my Android phone hotspot's Wi-Fi.

We didn't specify a port for AdGuard DNS server.

**Comment by zebrum** [comment]
@lancelot-moon 
yeap, @zznosar said one of the possibility what happens. try to add this servers to AdGuard DNS
176.103.130.130:5353
176.103.130.131:5353

**Comment by lancelot-moon** [comment]
Specifying a port to AdGuard DNS server is useless.

This issue occurred over my Android phone hotspot's Wi-Fi.

My original setting of AdGuard DNS server is no specific port.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/NUpOD1j.png)
</details><br/>

Open Mo PTT.
The ads were not blocked.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/yMXXso0.png)
</details><br/>

Go to view DNS Requests Log in AdGuard Pro.
AdGuard DNS server didn't block those ads domains in Simplified domain names filter.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/YFeNLeT.png)
</details><br/>


Well, the specific port is 5353 for your test.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/txt5AaZ.png)
</details><br/>

Open Mo PTT.
The ads were still not blocked.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/BC3uMXJ.jpg)
</details><br/>

Go to view DNS Requests Log in AdGuard Pro.
AdGuard DNS server still didn't block those ads domains in Simplified domain names filter.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/zGJowzC.png)
</details><br/>

**Comment by zebrum** [comment]
@lancelot-moon send logs to support team then, don't forget to specify the exact time
post here your user ID from support team
thank you

**Comment by lancelot-moon** [comment]
I have sent the bug report to support@adguard.com at 23:42 (GMT+8) on 20th Nov, 2017.
**User ID**: 1425202
**Subject**: [Adguard Pro for iOS] bug report

**Comment by zebrum** [comment]
@IvanIin please take a look

**Comment by IvanIin** [comment]
@lancelot-moon 
It looks like the DNS hijacking on your internet provider side. The only way to block advertising in this situation is copy-paste the full contents of Simplified domain names filter in the blacklist

**Comment by lancelot-moon** [comment]
My cellular network's ISP (Chunghwa Telecom) doesn't do DNS hijacking.

In my case, my iPhone surfed on internet over my Android phone hotspot whose ISP is Chunghwa Telecom.

Why is AdGuard DNS server working when directly using its cellular network by a sim card if this ISP does DNS hijacking?

**Comment by ameshkov** [comment]
We'd better re-test it when DNSCrypt is available in AdGuard Pro
