### ISSUE TITLE
"css-display-none" rules are not applied to a new tab, opened in background

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#53]
Possible Safari bug, @Stillness-2 please check this.

> Another thing I noticed: when opening a tab for an article in the background, no matter what the website, it will not block the social buttons. The ads are still blocked, but the page will have to be reloaded before the social buttons are blocked. This occurs on iOS, but not OS X.
> 
> This occurs on every website, but examples include www.macrumors.com, www.engadget.com, www.polygon.com, and www.theverge.com. This is system-wide and can be reproduced by opening a tab for any website in the background. It will show the social buttons until the page is reloaded.

**Comment by Stillness-2** [comment]
Tested on iPhone 5s, Adguard 1.0.3 (30), www.macrumors.com.  Effect exists.

**Comment by ameshkov** [comment]
Huh. The same bug on desktop Safari.

"css-display-none" rules aren't applied if the page is loaded in non-active tab.

I'll file a bug report to webkit.

**Comment by ameshkov** [comment]
Filed a bug report:
https://bugs.webkit.org/show_bug.cgi?id=151702

**Comment by ameshkov** [comment]
Resolved in newer versions of iOS
