### ISSUE TITLE
Popup on website

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#530]
Hi gents,

Why can't we block the popup on this page: www.sceper.ws? 
Do we need an update for adguard for ios? We should be completely ad free, at the moment we are not.

www.sceper.ws
go down below and click on page 2
you will get a popup

Opened a topic on the forum but can't be fixed on iOS, so it means its not a rule issue.
https://forum.adguard.com/index.php?threads/resolved-sceper-ws.11931/

**Comment by ameshkov** [comment]
@worldsdream that's the problem with Safari content blockers -- too limited, there're multiple cool things we simply cannot do with it:(

**Comment by ameshkov** [comment]
And I am not sure it will be fixed ever by Apple, they're quite happy with what they provide.

**Comment by worldsdream** [comment]
Thanks for the clarification. We will see if apple gives more freedom to the developers.

**Comment by ameshkov** [comment]
Hope so. They didn't implement a single feature request I've opened, though.
