### ISSUE TITLE
Rate and share labels have wrong alignment

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardForiOS#531]
### Expected behavior

Labels should be in alignment with the other labels

### Actual behavior
Labels are not aligned correctly

<details><summary>Screenshot:</summary>

![7432adce-936d-4a71-b02d-5a79b77125b0](https://user-images.githubusercontent.com/10995998/33232202-0e1e9332-d202-11e7-8be6-7de408c189f2.jpeg)

</details>

### Your environment

* iPhone X
* iOS 11.2
* AdGuard Pro 1.3.3

**Comment by vozersky** [comment]
fixed 
will be in the next beta
