### ISSUE TITLE
Integrate AdGuard for iOS with the web reporting tool

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForiOS#533]
When user selects "AdGuard Pro" in the action extension menu in Safari, instead of having two "Contact the Support" buttons there should be one leading to reports.adguard.com with a set of parameters. 

The list of parameters to send and an example link can be found in the reporting tool repo: https://github.com/AdguardTeam/ReportsWebApp

**Comment by ameshkov** [comment]
Actually, I disagree.

There should be multiple options in the app.

1. Rename `Send Bug Report` to `Send Feedback`
2. Show a "picker" with the following options:
    * `Missed ad`
    * `Broken website/app`
    * `Social media elements`
    * `Annoyance`
    * `Anti-adblock script`
    * `Bug in AdGuard`

First 5 lead to reports.adguard.com.
`Bug in AdGuard` works as it worked before -- opens a mail app.

**Comment by vozersky** [comment]
this should be done asap
way too many support tickets from iOS app about missed ads/incorrect blocking

**Comment by worldsdream** [comment]
Yes this is important

**Comment by IvanIin** [comment]
done
