### ISSUE TITLE
Please update Traditional Chinese translations.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#534]
Hi,
@aalpatkina
Because I amended some strings/phraseology and translated new strings, please anew take all Traditional Chinese translations file from oneskyapp and update Traditional Chinese translations in AdGuard Pro for iOS v1.3.3.

(I'm not sure what I amended is also used for free AdGuard for iOS or not.
Maybe you can update the Traditional Chinese translations of free AdGuard for iOS next time.)

Please also remember to update the description on Apple Taiwan's iTunes App Store (PRO/Free).
https://github.com/AdguardTeam/AdguardForiOS/issues/497

Thanks.

**Comment by aalpatkina** [comment]
@lancelot-moon 
Hello,
Of course, we'll update all the translations in our new version release.

Thanks for your assistance.
