### ISSUE TITLE
"Can't connect to the App Store" when you press "Rate this app"

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForiOS#536]
**STR:**

1. Press "Rate this app" in Adguard's menu

**Expected result**
App's page in App Store is opened

**Actual result**
"Can't connect to App Store" error

both free and PRO versions are affected
reproduced with 1.3.3 beta, and 1.3.1 stable

### Your environment

* iPhone X, iPhone 8, iPhone SE, Iphone 6
* Operating system and version: **iOS 11**

Can't reproduce with iOS 10

**Comment by vozersky** [comment]
doesn't look like an App Store issue to me

**Comment by IvanIin** [comment]
fixed in 1.3.3
