### ISSUE TITLE
VPN icon using full-tunnel.

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#538]
Upon awakening I noticed I had a VPN icon. I then checked to ensure I hadn't switched to split-tunnel. I hadn't; it was and still is using full-tunnel. What's most odd is the fact that during a previous beta, the same thing happened - after falling asleep with my wifi still on in full-tunnel I awoke with a VPN icon. As it can't be related to my sleeping, one would reasonably conclude, the obvious choice would be time-related. However, it has never naturally occurred during long daytime periods of use, only while I sleep. So, the time factor isn't necessarily the cause. My only other conclusion is my dog is far more intelligent than I know she already is and has been acting the role of Trickster.
![db9449dd-23ae-4317-a752-6f8fa8259495](https://user-images.githubusercontent.com/18148748/33731645-c483f2fe-db51-11e7-8ef0-f849b0e77ff5.png)

**Comment by zebrum** [comment]
@X8716e what about logs? :)

**Comment by X8716e** [comment]
@zebrum , Sure thing. I'll send em in. On a semi-related note, I spent a few hours reproducing / attempting to reproduce this. In the very beginning, it took no effort, it simply did it every time, no matter how I dis/re/connected. It semi-slowly became quite random. After ~1.5 days it stopped altogether, though I did _something_ - I really cannot remember if it was using the wifi function [Forget This Network] & then rejoining it or something else, so I do hope everything you need is contained within AdGuard's logs. If not, I'm definitely willing to send you wifi logging or anything else you may need via what I'm able to extract from iOS beta logs.

**Comment by zebrum** [comment]
@X8716e remind me your ticket id from support please

**Comment by X8716e** [comment]
@zebrum , I mistakenly thought I had responded to your request for my ticket ID. I only noticed it now when going through past issues. If it’s still at all relevant or helpful, it’s dated Su 17. Dec 2017 12:21 & the ID is: 1600731. Thank-you.

**Comment by zebrum** [comment]
@X8716e In the next beta there will be three tunnel mode. Let's see how it will work.

**Comment by X8716e** [comment]
Sounds quite interesting. Can’t wait to see!

**Comment by X8716e** [comment]
Sounds Intersting. Can’t wait to see!

~ apologies for

**Comment by ameshkov** [comment]
https://adguard.com/en/blog/adguard-pro-discontinued/
