### ISSUE TITLE
Feature Request - Dark Mode in AdGuard PRO Application

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#540]
Can we have dark mode in the iOS AdGuard Pro Application - like a switch? 

This is a very good addition to those users craving for dark mode in their iOS device and application.

**Comment by vozersky** [comment]
Hi! We've decided not to maintain two ui color modes at the same time, but since the dark color scheme is more popular\convinient the new app design is actually dark\black: https://github.com/AdguardTeam/AdguardForiOS/issues/455 It's coming soon :)

**Comment by zznosar** [comment]
Cool. I really can't wait! :) :) :)

**Comment by vozersky** [comment]
yeah, same here :)
