### ISSUE TITLE
Custom filters are not visible

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardForiOS#542]
Custom filters are not visible since they are hidden behind my keyboard. 

Expected behavior: they should scroll up so that they are visible when I’m editing them. 

<details><summary>Screenshot:</summary>

![screen shot 2017-12-11 at 3 36 05 pm](https://user-images.githubusercontent.com/27292111/33833686-18d36aee-de89-11e7-97ff-d482a9b528d6.png)

![screen shot 2017-12-11 at 3 36 16 pm](https://user-images.githubusercontent.com/27292111/33833691-1aab7406-de89-11e7-80a1-3518074bb81b.png)

</details>

### Customer ID 1075559

Application version: 1.3.1.82
Device: iPhone
Platform: iOS
OS: 11.1.2

**Comment by zebrum** [comment]
It has been fixed in beta version.
