### ISSUE TITLE
Add "Blocking Lists" settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#545]
Mockup:
https://app.moqups.com/ameshkov/rbJNBa7sH3/view/page/ade12e19d

**Please note, that screenshots might be taken from an old mockup. Use mockup above as a guide**

Here is how we should change the "Privacy" block on the main screen:
https://uploads.adguard.com/up04_90yci_AdGuard_for_iOS_-_Privacy__Moqups_.png

Empty "Blocking Lists":
https://uploads.adguard.com/up04_u06s5_AdGuard_for_iOS_-_Privacy__Moqups_.png

Adding new subscription:
https://uploads.adguard.com/up04_tt1os_AdGuard_for_iOS_-_Privacy__Moqups_.png

A couple of subscriptions added:
https://uploads.adguard.com/up04_ew4r4_AdGuard_for_iOS_-_Privacy__Moqups_.png

Subscription details:
https://uploads.adguard.com/up04_jot6v_AdGuard_for_iOS_-_Privacy__Moqups_.png

The pre-defined list of subscriptions:

Name | Description | URL |
------------ | ------------- | -------------
AdGuard SDN filter | Simplified Domain Names filter. Composed of several other filters (English filter, Social media filter, Spyware filter, Mobile ads filter, EasyList and EasyPrivacy) and simplified specifically to be better compatible with DNS-level ad blocking. | https://filters.adtidy.org/windows/filters/15.txt
AdAway default blocklist | Blocking mobile ad providers and some analytics providers | https://adaway.org/hosts.txt
hpHosts - Ad and Tracking servers | Hosts in the hpHosts database with the ATS classification ONLY. | https://hosts-file.net/ad_servers.txt

**Comment by ameshkov** [comment]
You should first implement this:
https://github.com/AdguardTeam/AdguardForiOS/issues/546

**Comment by X8716e** [comment]
The entire community is going to love this!

**Comment by IvanIin** [comment]
done
