### ISSUE TITLE
Blacklist should support both "adblock" and "hosts files" syntax

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#546]
This is a prerequisite to https://github.com/AdguardTeam/AdguardForiOS/issues/545.

How should it be implemented

1. Lines starting with `# ` and `! ` are considered comments.
2. Lines looking like `example.org ip_address` is a "hosts" rule and should be applied in a different way. Regex: `\s*[a-zA-Z0-9-_.]+\s+[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\s*`
3. Other lines are considered "adblock" rules (and applied just like we did it before).

For "hosts" syntax AG should fully support it, e.g. it should use resolve the domain name to the specified IP address.

**Comment by IvanIin** [comment]
done
