### ISSUE TITLE
Visual bug v1.3.3

### ISSUE THREAD

**Issue by LaxusiC** [AdguardTeam/AdguardForiOS#548]
When you using the full tunnel and turn off wifi, the wifi icon is greyed out instead of dissappear. Also there is no vpn icon showing when you use full tunnel

![ff7137b7-1abf-4333-a77d-bd6d2c78c28b](https://user-images.githubusercontent.com/9650215/33928955-45b90c8e-e01a-11e7-8aa8-92c1b5cc046d.png)

Also Adguard doesn't show how many domains are in blacklist

![e09d9002-42bc-4587-a4cb-21c5d5bc0fa5](https://user-images.githubusercontent.com/9650215/33929490-41cd015a-e01c-11e7-966c-451125e3b7cb.png)

**Comment by zebrum** [comment]
@LaxusiC no vpn icon is expected and not a bug in full tunnel.
about first and third issues @IvanIin will think a little more )
thank you!

**Comment by ameshkov** [comment]
> When you using the full tunnel and turn off wifi, the wifi icon is greyed out instead of dissappear. 
> Also there is no vpn icon showing when you use full tunnel

Both are caused by the same iOS bug. This is how it behaves with certain VPN tunnel settings.

Regarding third, moved to a separate issue:
https://github.com/AdguardTeam/AdguardForiOS/issues/553
