### ISSUE TITLE
Missed translation for the title of free AdGuard for iOS on iTunes App Store.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#549]
Hi,

Thanks a lot!
I checked the translations for AdGuard Pro and free AdGuard for iOS on iTunes App Store.
Others are fine.
But I found that the title of free AdGuard for iOS on iTunes App Store is still not updated.
Is it possible that too long strings can't be on title?
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/XRItDnE.png)
</details><br/>

Oneskyapp:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/z12MhrS.png)
</details><br/>

**Comment by aalpatkina** [comment]
@lancelot-moon we are very sorry. It's our fault.
We'll certainly update the title in our new version. 

Thank you very much for your assistance!

**Comment by lancelot-moon** [comment]
It's ok.
Don't worry!
Thanks for your hard work!

**Comment by lancelot-moon** [comment]
Hi, it seems that you changed the title of free AdGuard for iOS on iTunes app store,
AdGuard — adblock&privacy
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/p0y02OD.png)
</details><br/>

It's different with what on oneskyapp.
Oneskyapp:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/z12MhrS.png)
</details><br/>

It's ok.
You decided to use which title.
Maybe "AdGuard — adblock&privacy".

And then I know that you use "AdGuard".
But "AdGuard" in the strings were recovered to "Adguard" for several times.
It's strange on oneskyapp since I don't like that it shows "updated words" due to only "Adguard".
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/7uKMEL3.png)
</details><br/>

Just small problems.
Don't worry.
Thanks.

**Comment by vozersky** [comment]
@aalpatkina

**Comment by ameshkov** [comment]
Closing this issue, duplicates https://github.com/AdguardTeam/AdguardForiOS/issues/667
