### ISSUE TITLE
Missed ads at https sites

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardForiOS#55]
Here are some screenshots:
http://screencast.com/t/sD2JVrXT
http://screencast.com/t/yjLYIZKx6
http://screencast.com/t/5zfqHKhkyCT

**Comment by ameshkov** [comment]
```
m.vk.com##.wall_item[data-ad-view]
```

**Comment by ameshkov** [comment]
meduza.io - this is emulator issue, just ignore it

**Comment by ameshkov** [comment]
@gshumihin I can't reproduce facebook issue, do you have english filter enabled?
