### ISSUE TITLE
English filter blocks too much on designboom 

### ISSUE THREAD

**Issue by Superkloton** [AdguardTeam/AdguardForiOS#552]
English filter blocks images for similar articles under the active articles:

![Image](https://i.imgur.com/LwMnTR8.jpg)

Problem seems to be EasyList.

**Comment by ameshkov** [comment]
Moved to https://github.com/AdguardTeam/AdguardFilters/issues/8529

@Superkloton you can use this page to report issues with any website/app:
https://reports.adguard.com/en/new_issue.html

**Comment by Superkloton** [comment]
I can but uploading images there is a pain since you have to host it yourself instead of letting Github do it for you. Besides, it then shows up here anyway so what’s the point.

**Comment by ameshkov** [comment]
> I can but uploading images there is a pain since you have to host it yourself instead of letting Github do it for you

Yeah, agreed. We'll make it easier eventually.
