### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by LaxusiC** [AdguardTeam/AdguardForiOS#554]
For example: I have 2 wifi. I was using wifi 1 and somehow wifi 1 lost the internet ios will automatically connected to wifi 2 (has internet connection), the problem is internet connection will lost even wifi is still connected. To fix this you need to turn off adguard and them reopen. 

iOS 11.1.1, iPad Air 2, Adguard Pro 1.3.3

**Comment by ameshkov** [comment]
Frankly, I've no idea how can it happen.

@LaxusiC can you reproduce this and record AdGuard logs?

**Comment by LaxusiC** [comment]
How do i find the log

**Comment by ameshkov** [comment]
When you click "Send Feedback" inside of the app, it will open a Mail.app with the email template. Log files will be attached to that email. Just send it to yourself, grab the logs and attach to this issue.

**Comment by LaxusiC** [comment]
[adguardproforiosbugreport.zip](https://github.com/AdguardTeam/AdguardForiOS/files/1606918/adguardproforiosbugreport.zip)

Here is the data

**Comment by ameshkov** [comment]
@LaxusiC thank you! Waiting for @IvanIin to check the logs

**Comment by ameshkov** [comment]
https://adguard.com/en/blog/adguard-pro-discontinued/
