### ISSUE TITLE
Add support for DNSSEC & DNSCurve

### ISSUE THREAD

**Issue by akmAa** [AdguardTeam/AdguardForiOS#555]
"please look into adding and fully supporting DNSSEC and DNSCurve for your DNS servers (both IPv4 and IPv6) to maximize security. With DNSCrypt, DNSSEC, and DNSCurve, your DNS servers would be the go-to choice for anyone that knows of AdGuard and how great your apps and DNS already are."

customer id 1556407

**Comment by ameshkov** [comment]
This is about AG DNS, not AG for iOS.

We have such a feature request already there.
