### ISSUE TITLE
Add per-app, per-filter support of iCloud Sync

### ISSUE THREAD

**Issue by akmAa** [AdguardTeam/AdguardForiOS#556]
"It would be awesome if you could add a “Sync With iCloud” feature or option so that users can automatically receive the exact same setup through all of their devices. The iCloud sync should be very carefully specific to the corresponding app, such as the AdGuard Pro app and the regular AdGuard app. Both apps may be used by users which could very well have different filters selected in either app so that they cover a more of a broad spectrum of filters. With completely different filters selected inside either app, the iCloud sync would definitely have to be application specific to assure than filters are exactly how users programmed. 

Example: AdGuard Pro = filters 1,2 and 3

AdGuard = filters 4,5 and 6

(iCloud Sync should keep these filters synced exactly how users selected within the particular apps, hence, “application specific”) "

customer id 1556407

**Comment by vozersky** [comment]
dup https://github.com/AdguardTeam/AdguardForiOS/issues/479
