### ISSUE TITLE
Minor visual glitch in the DNS Settings > Add Custom section

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#557]
Reported by the  iPhone 7+, iOS 11.2.5 Dev β2 user here: 1703473

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/34350104-e464bcae-ea1d-11e7-8ec3-2d17fb0d941e.png)

![image](https://user-images.githubusercontent.com/15856304/34350142-12e48280-ea1e-11e7-925e-32eb94be129b.png)

</details>

### Your environment

* Device model and storage size: iPhone 7+
* Operating system and version: 11.2.5 Dev β 2.
* Browser (e.g. Safari) n/a
* Wi-fi or mobile internet connection n/a

**Comment by ameshkov** [comment]
Resolved in the new UI
