### ISSUE TITLE
Error compiling Content Blocker

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForiOS#56]
From logs:  Error occured: Не удалось завершить операцию. (ContentExtensionsDomain, ошибка 19)

Relevant tickets examples: MPJ-761-36282, YTB-821-62332

**Comment by ameshkov** [comment]
I need to know which filters do they use

**Comment by ameshkov** [comment]
Seems to be fixed in 1.0.3. Reopen this issue if there will be new complaints.
