### ISSUE TITLE
Filters screen UI bug

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForiOS#560]
AdGuard 2.0.0

1. In edit mode the grey selection area interferes with checkmarks: you can't see the difference between checked and unchecked item.

2. When you are on filters list screen and select one of them for more details, there is a check mark appears like if filter is turned on. Also no need in grey rectangle selection

### Actual behavior

<details><summary>Screenshot:</summary>

![up03_6enpf](https://user-images.githubusercontent.com/23637588/34435704-ad334ad6-eca0-11e7-942f-c234aafd9039.png)

</details>

**Comment by IvanIin** [comment]
fixed
