### ISSUE TITLE
Testbuilt 2.0.0 (121) Personal Hotspot bug

### ISSUE THREAD

**Issue by tosbsas** [AdguardTeam/AdguardForiOS#561]
When enabling Personal Hotspot Other devices cannot Access Internet. Connects to hotspot but cant Access Internet. 

iOS 11.2.5
Fulltunnel
Adguard DNS Servers crypto

**Comment by ameshkov** [comment]
I am almost sure that this behavior is normal for the full-tunnel mode.

@tosbsas could you please check if you have that issue with default settings?

**Comment by tosbsas** [comment]
No problem There. Used it very often




_______________________________

Ruben Gutknecht

Lima, Perú  🇵🇪

Cel: +51-99349-1515

Fax: 001-928-223-4243 International

Voice/Fax: 49 (0) 721-151-379204

http://telegram.me/tosbsas

paypal.me/RubenGutknecht
<applewebdata://40566043-5FAC-492D-B3D9-9F4745FD6351/paypal.me/RubenGutknecht>

Deutschland

tosbsas@gmail.com

ttosbsas@icloud.com

Von: Andrey Meshkov <notifications@github.com> <notifications@github.com>
Antworten: AdguardTeam/AdguardForiOS
<reply@reply.github.com>
<reply@reply.github.com>
Datum: 3. Januar 2018 at 06:51:25
An: AdguardTeam/AdguardForiOS <adguardforios@noreply.github.com>
<adguardforios@noreply.github.com>
CC: tosbsas <tosbsas@gmail.com> <tosbsas@gmail.com>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Betreff:  Re: [AdguardTeam/AdguardForiOS] Testbuilt 2.0.0 (121) Personal
Hotspot bug (#561)

I am almost sure that this behavior is normal for the full-tunnel mode.

**Comment by ameshkov** [comment]
Just in case, could you plz also check it with 1.3.3. If I am right, you'll run into the same issue there.

**Comment by tosbsas** [comment]
Used 133 before. As I said worked perfect

Sent from Astro <https://www.helloastro.com> for iOS


On Jan 3, 2018 at 8:12 AM, Andrey Meshkov <notifications@github.com> wrote:


Just in case, could you plz also check it with 1.3.3. If I am right, you'll
run into the same issue there.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AdguardTeam/AdguardForiOS/issues/561#issuecomment-355008700>,
or mute the thread

**Comment by ameshkov** [comment]
That's odd, okay then, I guess we'll be able to reproduce it on our side.

**Comment by zebrum** [comment]
Reproduced

**Comment by IvanIin** [comment]
fixed in 122
