### ISSUE TITLE
A Good filter source: 1hosts.cf

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#562]
https://forum.xda-developers.com/android/general/badmojr-one-host-file-to-block-t3713360

It integrated many popular filter, included AdGuard's filter.
So it's more comprehensive than AdGuard Simplified domain names filter.
http://1hosts.cf/

I read the article about new AdGuard for Mac.
https://blog.adguard.com/en/adguard-for-mac-1-5-3/

[Added] Filter subscription by URL

It should represent that new AdGuard Pro for iOS will also has the feature soon.

But, can AdGuard let users set the custom filter's name?
I mean classification!
Classified filters in user filter.
Or does it only import rules into the one user filter? <- This is simply bad.

For a large number of rules, just setting classified filter profiles is better.
Of course, if AdGuard can let users edit rules in those imported user filters, it's great.
Hope that AdGuard can support the format of 0.0.0.0 example.com.
General hosts file.

**Comment by ameshkov** [comment]
> But, can AdGuard let users set the custom filter's name?

Yes, it can.

> Hope that AdGuard can support the format of 0.0.0.0 example.com.

It does support that format, but keep in mind that iOS has some strict limitations on the VPN tunnel RAM, and you won't be able to use multiple subscriptions of that size.

**Comment by lancelot-moon** [comment]
> It does support that format, but keep in mind that iOS has some strict limitations on the VPN tunnel RAM, and you won't be able to use multiple subscriptions of that size.

Yes, I know that 1hosts.cf has a large size.
I'll only use it if it keeps updating.

Simplified domain names filter is unable to block ads in Erudite Dictionary app.
https://goo.gl/sD8jPv

StevenBlack hosts file can do it due to include those ad domains which AdGuard doesn't have.
And then 1hosts.cf also integrates StevenBlack hosts file and other filters.
For some local ad domains, they're often not in Simplified domain names filter, but they're in 1hosts.cf.
It's more comprehensive.

However, I could directly copy and paste the all content of Simplified domain names filter into blacklist in the past version.

But it's invalid for AdGuard Pro v1.3.3 even my blacklist is space from the beginning.
Why?
Is the number of entries in Simplified domain names filter already over the upper limit?
Or a bug?

B/R

**Comment by ameshkov** [comment]
> But it's invalid for AdGuard Pro v1.3.3 even my blacklist is space from the beginning.

v1.3.3 does not support "hosts" files syntax, it requires blacklist entries to be in the "ad blocking rules" format.

**Comment by lancelot-moon** [comment]
I meant that I was unable to copy and past all of Simplified domain names filter's contents into the blacklist in AG Pro for iOS v1.3.3.
I didn't mean a hosts file.

**Comment by ameshkov** [comment]
At the moment you need to remove all the lines containing `##` symbols.

We'll fix that later, these lines shouldn't be in the filter.

**Comment by lancelot-moon** [comment]
Thanks for your answer!
You know that AdGuard DNS is not very fast for those who live in Asia.
After importing filters by URL is ready, I think that using a fast DNS and a comprehensive local filter is better, especially sometimes AdGuard DNS filtering is invalid...
(Maybe there is trouble in VPN tunnel or DNS hijacking.)

As AdGuard's translator, my family told me that a parcel from abroad was arrived yesterday.
I guess that it's AdGuard's gift.
After tracking the parcel on Taiwan post office website, my guess is right.
After work, I was tired and still didn't open it.
Hope that there is the cute doll or the cool satchel in the parcel. XDDD
https://vk.com/adguard?z=photo-53764934_456239410%2Fwall-53764934_8336
Anything is fine for me.))

I am already very happy because I receive a gift from Russia.
Although I had been to Russia and have some Russian friends on VK, I never received a postcard or gift from Russia.
Only I shipped gifts to my Russian friends. XDD

Thanks again!!!
Happy New Year!

**Comment by ameshkov** [comment]
That's awesome, thank you:)

Frankly, I don't know what gifts did @aalpatkina send, I hope it's something cool:)

**Comment by mikeoleary7528** [comment]
What is the limit on VPN Tunnel RAM? Is there a way the app can tell us if we have too many filters?

**Comment by ameshkov** [comment]
The limit is 15MB.

> Is there a way the app can tell us if we have too many filters?

We can make a rough estimate indeed.

**Comment by mikeoleary7528** [comment]
And that 15mb limit is the same for split or full right?

**Comment by lancelot-moon** [comment]
You do compression for rules, right?
So AdGuard Pro v2.0.0 can contain such large numbers of entries.
Another tester imported more than 70k entries in Subscriptions, which is amazing.
Marking a rough estimate indeed in the section of Subscriptions is good!
