### ISSUE TITLE
Add support for PAC config / HTTP Proxy

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#563]
Could you add full support for PAC config/HTTP Proxy (Auto Proxy) so that users can import (PAC) filters using (an easily prepped url such as) https://cdn.ghostery.com/pac/pac-0-no_gr.js

The user should be able to simply paste the PAC config/HTTP Proxy url into a specific section. If possible, there should also be the ability to add multiple urls without any of them fluctuating with the other. This could work if each url has its own section so that users can simply (add) paste multiple urls and aren’t forced to compile syntax (manually), which could be challenging as most users don’t understand syntax. It should all be processed (much more simply) and configured based off of the PAC config/HTTP Proxy url(s) users add.

Not taking away from any “advanced user” the ability to program their own syntax as they may love that option as well. It is a great feature, although I had a little difficult adding syntax because the format would automatically change. When the format automatically changes after adding a ton of syntax, it may cause much of the syntax rules not to function correctly. If the format stays exactly how it’s entered initially, it seems that it would function just as it was intended. Please look into that as it could be a simple bug fix. 

CS ID 1556407

[pac-0-no_gr.js.zip](https://github.com/AdguardTeam/AdguardForiOS/files/1600226/pac-0-no_gr.js.zip)

**Comment by ameshkov** [comment]
This is an awesome feature request. Yes, we can and we should.

**Comment by X8716e** [comment]
Many host files / blacklists give the user the ability to use a PAC file, e.g. Peter Lowe’s Lists, Hexium Threat List, among others. It’s definitely a nice feature request, as PAC files function somewhat differently than do host files with the PAC file, strictly speaking, operating directly at the network level on one’s device. Though AdGuard does this also via its DNS level blocking, one needs to use specific name servers to accomplish this until AdGuard’s upcoming groundbreaking release. This of course reduces one’s voices of available name servers, some of which have zero respect for end users’ privacy. There are some available from @opennic - https://opennic.org/ - that use Peter Lowe’s list & either have loggingtuned off completely or have Fail2Ban in place & use logging only for said purpose. Others have blacklists in place for .bit domains serving malware. This gives one, as I see it, a choice of two organization’s DNS servers - AdGuard & OpenNic. That is, of course, until the dev’s complete the work they’re doing for us & the next version of AdGuard Pro is released. I’m unnaturally excited about it. Does that make me a nerd? Nvm, I was born one. 🚨 Oh, I nearly forgot to warn you & others about using Ghostery’s “services”. So the info sticks, I’ll not state it here. Take 5 - 6min to look into who actually ownsGhostery and the goals of said owners. It’s worth the time.

**Comment by ameshkov** [comment]
> So the info sticks, I’ll not state it here. Take 5 - 6min to look into who actually owns Ghostery and the goals of said owners.

I am not so sure about it since Cliqz has acquired it:
https://cliqz.com/en/about

**Comment by X8716e** [comment]
@ameshkov , precisely! Knowledge truly is power.

**Comment by ameshkov** [comment]
https://adguard.com/en/blog/adguard-pro-discontinued/
