### ISSUE TITLE
VPN split tunneling for apps (feature request)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#564]
Some real VPN providers have the feature, VPN split tunneling.
https://www.bestvpn.com/vpns-for-split-tunneling/

Split Tunneling: Protect all connected devices or applications except for a selected few.
Inverse Split Tunneling: Only protect selected connected devices or applications.

PureVPN for Android can do VPN split tunneling.

As what we know, AdGuard for Android also can do it in apps management.
I don't know if you can realize it for iOS version of AdGuard Pro.

B/R

**Comment by ameshkov** [comment]
AG Pro does operate in split tunnel mode by default, intercepting DNS traffic only.

However, on iOS it's not possible to make it work on a per-app basis.
