### ISSUE TITLE
UI issues v2.0

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForiOS#569]
1.  
<details><summary>Screenshot:</summary>

![image uploaded from ios](https://user-images.githubusercontent.com/23637588/34827002-c3b3f78a-f6e9-11e7-9d90-dac9ebd78d9a.jpg)

</details>

Make it like in Content blocker filters update

2.Add circle symbol while updating filters here: 
<details>

![img_0007](https://user-images.githubusercontent.com/23637588/34827486-5d1937ea-f6eb-11e7-8841-81bcede1444d.jpg)

</details>

3. Maybe we should add one more entry 'Last checked' with last update time and date?
<details>

![image uploaded from ios](https://user-images.githubusercontent.com/23637588/34827597-bbf37c8a-f6eb-11e7-8dd7-41b8b3e17607.png)

</details>

4. 
<details>

![img_0004](https://user-images.githubusercontent.com/23637588/34827722-2c09af12-f6ec-11e7-97e1-e1661c9130cc.jpg)

</details>

**Comment by zebrum** [comment]
5. 
<details>

![img_0008](https://user-images.githubusercontent.com/23637588/34830017-a39a188a-f6f3-11e7-8aea-32bd04bacd1a.jpg)


</details

**Comment by X8716e** [comment]
*Agreed. And while UI enhancements are being discussed, here’s one more to add to your work...*
————-
![bfb929bf-a0bf-440b-8a26-c14a4a17b9d0](https://user-images.githubusercontent.com/18148748/34852381-5739b4ec-f6fc-11e7-8122-00ad075db881.png)

![aa9f2380-608c-4aa4-b35c-2afde9238cc3](https://user-images.githubusercontent.com/18148748/34852382-57635248-f6fc-11e7-9b5d-c17b54777d0e.png)

![1b3f33e1-4df3-4273-9e3b-d6b5de97bacf](https://user-images.githubusercontent.com/18148748/34852383-5779eecc-f6fc-11e7-8e0a-a8af98f30a17.png)
————
___As you can see, number of trackers remains a constant zero, despite the fact that it does block precisely what you want it to.___

**Comment by zznosar** [comment]
I think the tracker actually works. Mine has 1. 
![d84bd302-8f78-4f4b-85b0-18585fe6dc92](https://user-images.githubusercontent.com/27464836/34865998-08fdd1cc-f7cf-11e7-889a-1092edf6ac59.jpeg)

**Comment by X8716e** [comment]
My iPhone shows zero. My iPad shows some but not all.

**Comment by zebrum** [comment]
'Trackers detected' is not the same as 'trackers blocked'. 
Maybe we can discuss how trackers detection works here: #579

**Comment by IvanIin** [comment]
fixed
