### ISSUE TITLE
DNSCrypt stops working after the network change

### ISSUE THREAD

**Issue by tosbsas** [AdguardTeam/AdguardForiOS#570]
When on full Tunnel Mode After several hours of use it seems like Connection is having trouble processing data. It gets Slow and breaks. Only way to get connected again is Turn DNS off and on. 

Dunno about inner workings but it feels like a cache being Filled up and turning off and on releases it.

**Comment by ameshkov** [comment]
Logs?

**Comment by tosbsas** [comment]
Does Not produce them :-(( but I can replícate it always.

Maybe it has to do with dnscrypt as i did Not See that on 133 and only your
Server

Ruben




_______________________________

Ruben Gutknecht

Lima, Perú  🇵🇪

Cel: +51-99349-1515

Fax: 001-928-223-4243 International

Voice/Fax: 49 (0) 721-151-379204

http://telegram.me/tosbsas

paypal.me/RubenGutknecht
<applewebdata://40566043-5FAC-492D-B3D9-9F4745FD6351/paypal.me/RubenGutknecht>

Deutschland

tosbsas@gmail.com

ttosbsas@icloud.com

Von: Andrey Meshkov <notifications@github.com> <notifications@github.com>
Antworten: AdguardTeam/AdguardForiOS
<reply@reply.github.com>
<reply@reply.github.com>
Datum: 11. Januar 2018 at 08:45:56
An: AdguardTeam/AdguardForiOS <adguardforios@noreply.github.com>
<adguardforios@noreply.github.com>
CC: tosbsas <tosbsas@gmail.com> <tosbsas@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Betreff:  Re: [AdguardTeam/AdguardForiOS] Connection “fill up” on 2.0 (121)
(#570)

Logs?

**Comment by ameshkov** [comment]
Let's check it with the public beta (we'll push it today, expect one more day on the review)

**Comment by tosbsas** [comment]
Ok. Perfect :-)

Ruben




_______________________________

Ruben Gutknecht

Lima, Perú  🇵🇪

Cel: +51-99349-1515

Fax: 001-928-223-4243 International

Voice/Fax: 49 (0) 721-151-379204

http://telegram.me/tosbsas

paypal.me/RubenGutknecht
<applewebdata://40566043-5FAC-492D-B3D9-9F4745FD6351/paypal.me/RubenGutknecht>

Deutschland

tosbsas@gmail.com

ttosbsas@icloud.com

Von: Andrey Meshkov <notifications@github.com> <notifications@github.com>
Antworten: AdguardTeam/AdguardForiOS
<reply@reply.github.com>
<reply@reply.github.com>
Datum: 11. Januar 2018 at 08:49:01
An: AdguardTeam/AdguardForiOS <adguardforios@noreply.github.com>
<adguardforios@noreply.github.com>
CC: tosbsas <tosbsas@gmail.com> <tosbsas@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Betreff:  Re: [AdguardTeam/AdguardForiOS] Connection “fill up” on 2.0 (121)
(#570)

Let's check it with the public beta (we'll push it today, expect one more

**Comment by lancelot-moon** [comment]
Excuse me.
How can I download the unreleased version of AdGuard Pro?
May I join the group?

**Comment by tosbsas** [comment]
Team has to let you in. Ask andrev

**Comment by lancelot-moon** [comment]
I found the article and separately finished filling in the form for the tester of Android and iOS versions of AdGuard.
https://blog.adguard.com/en/adguard-beta-test/

Can I directly download the unreleased beta version of AdGuard Pro from Apple app store after you accept my request?

B/R

**Comment by tosbsas** [comment]
Its vía TestFlight and you Need an invitation. Please don’t keep chAngeing
tópic here.




_______________________________

Ruben Gutknecht

Lima, Perú  🇵🇪

Cel: +51-99349-1515

Fax: 001-928-223-4243 International

Voice/Fax: 49 (0) 721-151-379204

http://telegram.me/tosbsas

paypal.me/RubenGutknecht
<applewebdata://40566043-5FAC-492D-B3D9-9F4745FD6351/paypal.me/RubenGutknecht>

Deutschland

tosbsas@gmail.com

ttosbsas@icloud.com

Von: lancelot-moon <notifications@github.com> <notifications@github.com>
Antworten: AdguardTeam/AdguardForiOS
<reply@reply.github.com>
<reply@reply.github.com>
Datum: 11. Januar 2018 at 11:32:45
An: AdguardTeam/AdguardForiOS <adguardforios@noreply.github.com>
<adguardforios@noreply.github.com>
CC: tosbsas <tosbsas@gmail.com> <tosbsas@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Betreff:  Re: [AdguardTeam/AdguardForiOS] Connection “fill up” on 2.0 (121)
(#570)

I found the article and separately finished filling in the form for the

**Comment by zznosar** [comment]
I experienced this in my iPod touch on once, but fixed it by restarting.

Haven’t notice this yet in hte ipad yet

 I will try to test it again multiple times in both ipad pro and ipod touch and reportback with logs. My version is testflight 2.0 124

**Comment by X8716e** [comment]
Using too many filters will have this effect, if i’m interpreting you correctly.

**Comment by tosbsas** [comment]
I am only using 43200 of 50.000 Limit and didnt See that befolge 2.0 (121).
By the way so far 124 is Not doing this anymore

Ruben




_______________________________

Ruben Gutknecht

Lima, Perú  🇵🇪

Cel: +51-99349-1515

Fax: 001-928-223-4243 International

Voice/Fax: 49 (0) 721-151-379204

http://telegram.me/tosbsas

paypal.me/RubenGutknecht
<applewebdata://40566043-5FAC-492D-B3D9-9F4745FD6351/paypal.me/RubenGutknecht>

Deutschland

tosbsas@gmail.com

ttosbsas@icloud.com

Von: intr0 <notifications@github.com> <notifications@github.com>
Antworten: AdguardTeam/AdguardForiOS
<reply@reply.github.com>
<reply@reply.github.com>
Datum: 11. Januar 2018 at 18:09:12
An: AdguardTeam/AdguardForiOS <adguardforios@noreply.github.com>
<adguardforios@noreply.github.com>
CC: tosbsas <tosbsas@gmail.com> <tosbsas@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Betreff:  Re: [AdguardTeam/AdguardForiOS] Connection “fill up” on 2.0 (121)
(#570)

Using too many filters will have this effect, if i’m interpreting you

**Comment by X8716e** [comment]
I was only able to push it to ~limit as you had, if not a bit less. 50k filters is overly generous, imo. Unnecessary as well. I obtain precision blocking with less than half of the 50k limit; in fact, I can do so with a third, approximately, of 50k by removing redundancies if parsing a manual blacklist, or choosing only what you actually need if using lists via URIs. If you at any time want a list of available filters - efficient ones unlike the HPhosts Ad/Tracking hosts file which alone will clog your system with useless filters - please simply ask me and I’d be happy to provide you with either my full collection or specific filter types of your choosing. 🚨

**Comment by tosbsas** [comment]
Thing is I Need spanisch , German and the  Basic englisch Filter.

I would love to See your Filters.

Ruben




_______________________________

Ruben Gutknecht

Lima, Perú  🇵🇪

Cel: +51-99349-1515

Fax: 001-928-223-4243 International

Voice/Fax: 49 (0) 721-151-379204

http://telegram.me/tosbsas

paypal.me/RubenGutknecht
<applewebdata://40566043-5FAC-492D-B3D9-9F4745FD6351/paypal.me/RubenGutknecht>

Deutschland

tosbsas@gmail.com

ttosbsas@icloud.com

Von: intr0 <notifications@github.com> <notifications@github.com>
Antworten: AdguardTeam/AdguardForiOS
<reply@reply.github.com>
<reply@reply.github.com>
Datum: 11. Januar 2018 at 18:45:49
An: AdguardTeam/AdguardForiOS <adguardforios@noreply.github.com>
<adguardforios@noreply.github.com>
CC: tosbsas <tosbsas@gmail.com> <tosbsas@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Betreff:  Re: [AdguardTeam/AdguardForiOS] Connection “fill up” on 2.0 (121)
(#570)

I was only able to push it to ~limit as you had, if not a bit less. 50k

**Comment by X8716e** [comment]
Ask and you shall receive. May I use your provided email to send my recommendations?

**Comment by tosbsas** [comment]
😀😀yes please :-)




_______________________________

Ruben Gutknecht

Lima, Perú  🇵🇪

Cel: +51-99349-1515

Fax: 001-928-223-4243 International

Voice/Fax: 49 (0) 721-151-379204

http://telegram.me/tosbsas

paypal.me/RubenGutknecht
<applewebdata://40566043-5FAC-492D-B3D9-9F4745FD6351/paypal.me/RubenGutknecht>

Deutschland

tosbsas@gmail.com

ttosbsas@icloud.com

Von: intr0 <notifications@github.com> <notifications@github.com>
Antworten: AdguardTeam/AdguardForiOS
<reply@reply.github.com>
<reply@reply.github.com>
Datum: 11. Januar 2018 at 18:49:21
An: AdguardTeam/AdguardForiOS <adguardforios@noreply.github.com>
<adguardforios@noreply.github.com>
CC: tosbsas <tosbsas@gmail.com> <tosbsas@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Betreff:  Re: [AdguardTeam/AdguardForiOS] Connection “fill up” on 2.0 (121)
(#570)

Ask and you shall receive. May I use your provided email to send my

**Comment by X8716e** [comment]
You got it! I’ll get them together & send them. I’ll provide choices for you, keeping in mind that using them all is a bad idea. The email will be sent from `domainvoider@protonmail.ch`

**Comment by tosbsas** [comment]
👍




_______________________________

Ruben Gutknecht

Lima, Perú  🇵🇪

Cel: +51-99349-1515

Fax: 001-928-223-4243 International

Voice/Fax: 49 (0) 721-151-379204

http://telegram.me/tosbsas

paypal.me/RubenGutknecht
<applewebdata://40566043-5FAC-492D-B3D9-9F4745FD6351/paypal.me/RubenGutknecht>

Deutschland

tosbsas@gmail.com

ttosbsas@icloud.com

Von: intr0 <notifications@github.com> <notifications@github.com>
Antworten: AdguardTeam/AdguardForiOS
<reply@reply.github.com>
<reply@reply.github.com>
Datum: 11. Januar 2018 at 18:55:21
An: AdguardTeam/AdguardForiOS <adguardforios@noreply.github.com>
<adguardforios@noreply.github.com>
CC: tosbsas <tosbsas@gmail.com> <tosbsas@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Betreff:  Re: [AdguardTeam/AdguardForiOS] Connection “fill up” on 2.0 (121)
(#570)

You got it! I’ll get them together & send them. I’ll provide choices for

**Comment by X8716e** [comment]
I’ve emailed you. Here is the list for future reference if necessary:

https://filters.adtidy.org/extension/chromium/filters/15.txt

https://easylist-downloads.adblockplus.org/easylistspanish.txt

https://easylist-downloads.adblockplus.org/easylistgermany.txt

https://www.dshield.org/feeds/suspiciousdomains_High.txt

https://hosts-file.net/hjk.txt

https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/MiningServerIPList.txt

https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list.txt

https://raw.githubusercontent.com/HexxiumCreations/threat-list/gh-pages/hexxiumthreatlist.txt

https://fanboy.co.nz/enhancedstats.txt

https://fanboy.co.nz/fanboy-antifonts.txt

**Comment by tosbsas** [comment]
Got it




_______________________________  
Ruben Gutknecht
Lima, Perú 🇵🇪  
Cel: +51-99349-1515(tel:+51-99349-1515)
Fax: 001-928-223-4243(tel:001-928-223-4243) International
Voice/Fax: 49 (0) 721-151-379204(tel:(0)%20721-151-379204)  
http://telegram.me/tosbsas
paypal.me/RubenGutknecht(applewebdata://40566043-5FAC-492D-B3D9-9F4745FD6351/paypal.me/RubenGutknecht)
Deutschland
tosbsas@gmail.com(mailto:tosbsas@gmail.com)
ttosbsas@icloud.com(mailto:ttosbsas@icloud.com)



Von: intr0 <notifications@github.com>(mailto:notifications@github.com)
Antworten: AdguardTeam/AdguardForiOS <reply@reply.github.com>(mailto:reply@reply.github.com)
Datum: 12. Januar 2018 at 16:34:39
An: AdguardTeam/AdguardForiOS <adguardforios@noreply.github.com>(mailto:adguardforios@noreply.github.com)
CC: tosbsas <tosbsas@gmail.com>(mailto:tosbsas@gmail.com), Author <author@noreply.github.com>(mailto:author@noreply.github.com)
Betreff: Re: [AdguardTeam/AdguardForiOS] DNSCrypt stops working after the network change (#570)

**Comment by X8716e** [comment]
Update - use **https://filters.adtidy.org/ios/filters/15_optimized.txt** in place of https://filters.adtidy.org/extension/chromium/filters/15.txt

**Comment by tosbsas** [comment]
You still enable englisch Filter or only yours?

Ruben




_______________________________

Ruben Gutknecht

Lima, Perú  🇵🇪

Cel: +51-99349-1515

Fax: 001-928-223-4243 International

Voice/Fax: 49 (0) 721-151-379204

http://telegram.me/tosbsas

paypal.me/RubenGutknecht
<applewebdata://40566043-5FAC-492D-B3D9-9F4745FD6351/paypal.me/RubenGutknecht>

Deutschland

tosbsas@gmail.com

ttosbsas@icloud.com

Von: intr0 <notifications@github.com> <notifications@github.com>
Antworten: AdguardTeam/AdguardForiOS
<reply@reply.github.com>
<reply@reply.github.com>
Datum: 12. Januar 2018 at 17:10:41
An: AdguardTeam/AdguardForiOS <adguardforios@noreply.github.com>
<adguardforios@noreply.github.com>
CC: tosbsas <tosbsas@gmail.com> <tosbsas@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Betreff:  Re: [AdguardTeam/AdguardForiOS] DNSCrypt stops working after the
network change (#570)

Update - use *https://filters.adtidy.org/ios/filters/15_optimized.txt

**Comment by X8716e** [comment]
I have every filter in that list enabled. And only those filters. The AdGuard Simplified Domain Names list includes an optimized version of the AdGuard English Filter.

**Comment by tosbsas** [comment]
Hm Andrey is saying there is way more in the englisch Filter and its needed
for Adguard to run. But getting back to the Office i Will try your List.

Ruben




_______________________________

Ruben Gutknecht

Lima, Perú  🇵🇪

Cel: +51-99349-1515

Fax: 001-928-223-4243 International

Voice/Fax: 49 (0) 721-151-379204

http://telegram.me/tosbsas

paypal.me/RubenGutknecht
<applewebdata://40566043-5FAC-492D-B3D9-9F4745FD6351/paypal.me/RubenGutknecht>

Deutschland

tosbsas@gmail.com

ttosbsas@icloud.com

Von: intr0 <notifications@github.com> <notifications@github.com>
Antworten: AdguardTeam/AdguardForiOS
<reply@reply.github.com>
<reply@reply.github.com>
Datum: 12. Januar 2018 at 17:14:58
An: AdguardTeam/AdguardForiOS <adguardforios@noreply.github.com>
<adguardforios@noreply.github.com>
CC: tosbsas <tosbsas@gmail.com> <tosbsas@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Betreff:  Re: [AdguardTeam/AdguardForiOS] DNSCrypt stops working after the
network change (#570)

I have every filter in that list enabled. And only those filters. The

**Comment by X8716e** [comment]
How many rules in that list?

**Comment by tosbsas** [comment]
40000 - he said it should better be called basic filter. 

I tried your lists. Work Fine but a lot of empty space in several pages

**Comment by IvanIin** [comment]
fixed
