### ISSUE TITLE
Unable to Add Custom DNSCrypt Server

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#571]
Tried adding a custom DNSCrypt Server and it’s not doing anything

### Steps to reproduce

1. Open AdGuard Pro
2. Go to DNS Settings
3. Add Custom DNSCrypt Server

### Expected behavior

Should be able to add custom DNSCrypt Server

### Actual behavior

Add Custom is not doing anything when clicked.

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Device model and storage size: iPad Pro10.5
* Operating system and version: 11.2.2
* AdGuard Pro v2.0 testbuild
![f1f55c53-418e-448c-a538-5d0dfb2e9972](https://user-images.githubusercontent.com/27464836/34842534-e9af87f8-f75f-11e7-902b-ac91793ec6dd.jpeg)

**Comment by X8716e** [comment]
This is **definitely** an issue. And I was _so looking forward_ to using some private servers. Perhaps this should be high priority as I’ve only discovered one other issue - and it's more cosmetic than anything. I’ll be posting it asap.

**Comment by IvanIin** [comment]
fixed

**Comment by zebrum** [comment]
@IvanIin we need to add input validation for Name' Address and Public key fields.

Also there is the issue when the cursor in the Public key input field, the Done button is not active - you can't save DNS server.

**Comment by X8716e** [comment]
@zebrum @IvanIin 
>  input validation for Name' Address and Public key fields.

👍

**Comment by IvanIin** [comment]
done
