### ISSUE TITLE
Loading filters list is too slow on old devices

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#572]
I am not sure, if it’s just my device, but the app is sluggish in my ipod touch 6th gen. Loading filters, adding blocklist subscrption. Might be the same with 5s and 6 since they share same specs...

In my iPad Pro, it’s amazing... LOVE IT!

UPDATE:

1. Loading filters is very slow in ipod touch 6th Gen.
2. Adding Blocklist subscription in ipod touch 6th gen is doing nothing.

Please see video below:

* Device model and storage size: iPod Touch 6th 128GB
* Operating system and version: 11.2.2

Proposed solution (by @ameshkov):
https://github.com/AdguardTeam/AdguardForiOS/issues/572#issuecomment-367265271

**Comment by ameshkov** [comment]
@zznosar could you plz record a video? It's unclear what do you mean by sluggish. IMO, all the old devices with iOS 11 are generally quite slow :)

**Comment by zznosar** [comment]
@ameshkov, i will post a video soon and will update the details of this issue.

**Comment by zznosar** [comment]
@ameshkov please see this: https://vimeo.com/250898730

I have updated the details of the Issue as well. If there are other best testers that use older devices, it will be great if they can test it, especially the Block List part as it's doing nothing.

**Comment by ameshkov** [comment]
Now I got it, thank you:)

**Comment by zznosar** [comment]
This seems to be fixed in the newest beta. Wow. I am so amazed how fast it is in the block list and filters in my very old ipod touch device. I will try again some more.

**Comment by zznosar** [comment]
Unfortunately, the slownes is back when you Open AdGuard - Filters - List of Filters in beta 136.

It takes a while to show all the filters in the device... it shows though. It just so slow.

**Comment by zznosar** [comment]
It’s very fast and fluid again in beta 137. Wow! Thanks guys!

**Comment by ameshkov** [comment]
Heh, who knows why, we didn't change anything:)

**Comment by zznosar** [comment]
Spoke too soon. The filter loading was fast when not connected to wifi. I was like WOW! :-)

But slows down when connected. There is spinning wheel.

I think the since the device it self is old and low memory and with iOS 11, this is expected. In my iPhone and iPad, its very fast.

Functionality wise, it still works.

**Comment by ameshkov** [comment]
> Spoke too soon. The filter loading was fast when not connected to wifi. I was like WOW! :-)

That's expected indeed as it was not trying to refresh the filters list from the server :)

**Comment by ameshkov** [comment]
@IvanIin let's do a very simple thing: if refreshing takes more than 5 seconds -- show the filters metadata that we have in the database.

**Comment by zznosar** [comment]
I think that’s a good idea. :-) since iPhone 5s and iPod Touch share the same geekbench score, they might encouter this as well. iPhone 6 is safe due to higher cpu clock.

I can’t test it in my spare iphone 5s as it’s water damage and fixing it here in Australia is bloody expensive. Lol.

Again, thank you team for still supporting old ios devices! :-)

**Comment by zznosar** [comment]
Fixed! Yehey! So fast! 

https://vimeo.com/257776161
