### ISSUE TITLE
A HUGE THANK-YOU FOR THE NEW RELEASE!!!

### ISSUE THREAD

**Issue by X8716e** [AdguardTeam/AdguardForiOS#573]
Everything is working perfectly so far. I’ve been playing with what is essentially my new toy for the past (?) hour/s. I’m currently using d0wn’s random IPv6 server (based in Netherlands; the other is in Moldova & soon I’ll be playing with that one. Now my day will consist of throwing name servers at this just to see what happens. I’ll also be subscribing to what is a huge collection of available lists from around the net which I’ve been amassing over the past (?)months. In other words, I’ll be doing my best to break this release because it’s the best way to test it. Plus it’s fun as ****.

**Comment by ameshkov** [comment]
Thank you:)
