### ISSUE TITLE
Blocking List - Click Here not working

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#574]
Click here to learn more is not working in blocking list. Please dont forgrt to add this as this will be helpfulfor firstimers.

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

![3319654d-2a16-4f56-97f0-4cc4d5abb0c7](https://user-images.githubusercontent.com/27464836/34866226-f62e16be-f7cf-11e7-90d3-8e03d23b5c5c.jpeg)

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Device model and storage size: (e.g. iPhone 6s 64gb)
* Operating system and version: (e.g. 10.3.1)
* Browser (e.g. Safari)
* Wi-fi or mobile internet connection

**Comment by zebrum** [comment]
I think it's just we don't have anything where the link supposed to lead. 
@ameshkov are we planning an article about hosts files support?

**Comment by ameshkov** [comment]
@zebrum yeah, we should first write a KB article:)

**Comment by ameshkov** [comment]
@zebrum the article to be updated:
https://kb.adguard.com/en/ios/features#adguard-pro-features
