### ISSUE TITLE
Excessive battery consumption

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForiOS#576]
<details>

![image uploaded from ios](https://user-images.githubusercontent.com/17472907/34878310-ce638d90-f7ba-11e7-9bef-8043666e1ec1.png)

</details>

logs provided directly

**Comment by ameshkov** [comment]
@vozersky we need to know what blocking list subscriptions have you added

**Comment by vozersky** [comment]
none of them

also, Adguard DNSCrypt server was in use the whole time
changed to OPEN DNS right before sending the log

**Comment by ameshkov** [comment]
@IvanIin first of all, I see quite a few `Vpn configuration successfully loaded` records in the log file, this looks odd.

**Comment by ameshkov** [comment]
@IvanIin 
fihished -> finished

**Comment by ameshkov** [comment]
@vozersky last question -- have you noticed that issue before when you had VPN tunnel disabled?

**Comment by vozersky** [comment]
@ameshkov no, I have not

**Comment by X8716e** [comment]
If it matters, I’m not having an issue with battery consumption thus far.
![980ecd93-4740-4d4e-97fb-edbed1e35f61](https://user-images.githubusercontent.com/18148748/34909473-d44e22d2-f86f-11e7-8bd5-ddab36044f42.png)

**Comment by ameshkov** [comment]
> If it matters, I’m not having an issue with battery consumption thus far.

We've got it on the test iphone X device, no issues on older iphones

**Comment by IvanIin** [comment]
I think that high battery consumption is caused by a dnscrypt restart error. In the tunnel logs I see that for 2500 dns requests, only 700 responses were received.
I also noticed one feature of the iPhone X - in the Xcode tools, the energy impact section shows the use of the display for our extensions. On other iOS devices the display usage is shown only for the main application. It's possible that this is an iOS issue, and iPhone X is incorrectly counts battery usage for extensions.

**Comment by lancelot-moon** [comment]
The situation of excessive battery consumption occurred on my iPhone, too.
Is it also possible because DNS requests log is always on in AdGuard Pro v2.0.0 (124)?
Will it be helpful if we can disable DNS requests log?

**Comment by zznosar** [comment]
I am running this test in two of my devices and I can confirm that I cannot reproduce this issue.

The iPad Pro 10.5's battery is the same with 1.3.3 including the iPod Touch.

Screen time on mine is 30 minutes in both and consumes less than 5%.

@lancelot-moon , please include the "screen time" in your screen shot just like what @X8716e did. 

This is not related to the DNS logging.... I am using DNS logging in my iPhone X with 1.3.3 and NO effect in the battery.

**Comment by lancelot-moon** [comment]
Updated screenshots.
Well, I'll run other apps on screen for the same time which AdGuard Pro v2.0.0 (124) used.

**Comment by zznosar** [comment]
Weird. It's probably because of different factors:

1. You have an older phone ~ probably a 5S or 6
2. You haven't restarted your phone for a while after you install the beta.
3. You install the beta on top of 1.3.3 without turning OFF the Pro mode and you did not restart your phone.

I will try to test it again in my iPod Touch. If I can find a spare iPhone 5S, I will test in that.

**Comment by X8716e** [comment]
I should try my iPhone 5, if it functions with that model. I’ll need to do it carefully because the phone’s screen is shattered. Still works, though. lol

**Comment by ameshkov** [comment]
I'd better wait for the next beta when other major bugs are resolved.

As @IvanIin said, the excessive battery usage might've been caused by some other bugs:
https://github.com/AdguardTeam/AdguardForiOS/issues/576#issuecomment-358228861

**Comment by X8716e** [comment]
Looking forward to next beta :: custom DNSCRYPT servers. Heaven.

**Comment by zznosar** [comment]
Yeah. You’re right. I will restest again in the next beta. I am actually very excited with this release. Hopefully the final version can be released soon. My friends would love this!!!

**Comment by X8716e** [comment]
We’ll have to create a list of public DNSCRYPT providers that are not available on the provided list. If you want, I can get one together as can you, and we merge them. Post them somewhere for those persons wanting to try their hand at connecting to some alternate servers may do so. I’ll create my list regardless for this purpose; I’ll likely have it complete within the next 3-4 days depending on what else I need/feel like doing.

**Comment by ameshkov** [comment]
Seems to be resolved
