### ISSUE TITLE
Add information about blocking lists and encrypted DNS to the "state.txt" file

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#577]
Not all settings are printed to the state.txt file.

We should add all the metadata we have about DNSCrypt settings and blocking lists state.

Also, it'd be better to add more data about currently active filters subscriptions (last time updated at least).

I'd prefer if you used json format for that file instead of the plain text we use at the moment.

**Comment by IvanIin** [comment]
done
