### ISSUE TITLE
Update trackers db

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#579]
Use disconnect's db for now (all the categories).

We'll switch to the new one later.

**Comment by X8716e** [comment]
Keep in mind that using all of Disconnect’s categories will block access to most social sites. I consider that a feature, however many people do not.

**Comment by ameshkov** [comment]
@X8716e it is used for trackers detection only, not for blocking them.

**Comment by X8716e** [comment]
@ameshkov , understood. Thank-you.

**Comment by IvanIin** [comment]
done

**Comment by lancelot-moon** [comment]
Do you mean you'll start to use disconnect trackers and analytics database?

Or from disconnect database to another new database?

**Comment by zebrum** [comment]
We are using Disconnect database until we make our own trackers db.

**Comment by lancelot-moon** [comment]
Thanks for the reply.
Just I also ask a question about tracker db in my another article?

I don't use AdGuard DNS and SDN filter.
But there are still DNS Requests shown by bright red.
How does DNS Requests Log know they are trackers and analytics?
Is Disconnect db built in AdGuard Pro app?
Or are my DNS requests still filterd by remote disconnect db in the background even if I don't use AdGuard DNS server?
