### ISSUE TITLE
Use an updated mobile Assistant version

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#581]
Removing "preview" button was definitely not the best solution. Updated UI is on the way.

**Comment by ameshkov** [comment]
Waiting for @4-life to finish the mobile Assistant.

**Comment by ameshkov** [comment]
You can use the dev build temporarily:
https://adguardteam.github.io/AdguardAssistant/mobile/script.js

**Comment by ameshkov** [comment]
Release build:
https://github.com/AdguardTeam/AdguardAssistant/releases/tag/4.0.17

**Comment by IvanIin** [comment]
done

**Comment by ameshkov** [comment]
@IvanIin one more update:
https://github.com/AdguardTeam/AdguardAssistant/releases/tag/4.0.18

**Comment by IvanIin** [comment]
done
