### ISSUE TITLE
Add AdGuard DNS (default, family) to the list of known DNS providers

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#582]

**Comment by zznosar** [comment]
@ameshkov @ivanlin when we add back these dns server, can we use port 5353? I can only bypass my isp’s hijacking if i use 5353 in your dns (regulard dns). If not, i can just manually add them again vwith this port...

**Comment by ameshkov** [comment]
@zznosar why, you can simply use DNSCrypt that won't allow your ISP to hijack your DNS traffic.

**Comment by zznosar** [comment]
@ameshkov, yeah you’re right! 😊 i almost forgot about that one! Please disregard my old comment 😁😁

**Comment by IvanIin** [comment]
done
