### ISSUE TITLE
Change labels in the DNS settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#583]
CUSTOM DNS SERVERS -> REGULAR DNS SERVERS
DNS CRYPT SERVERS -> ENCRYPTED DNS SERVERS

In light of https://blog.adguard.com/en/bye_dnscrypt/ we'd better just use the word "encrypted". Eventually, we'll add DNS over TLS support.

**Comment by IvanIin** [comment]
done
