### ISSUE TITLE
"Share this app" doesn't work in unreleased AG Pro v2.0.0 (124)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#586]
After tapping "Share this app", no response.

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/fDiufNV.png)
</details><br/>

**Comment by zznosar** [comment]
Not a bug. You need to click the required icons. Mail icon for mail and mesage icon for message. The same behavior in 1.3.3.

**Comment by lancelot-moon** [comment]
I never knew that I should click the required icons.
Generally, users will click the banner of "Share this app".
It's my fault. /_\

**Comment by zznosar** [comment]
Because you can share the apps in many ways. :-) . Via message or mail.

**Comment by zznosar** [comment]
@lancelot-moon should we close this issue? I created a feature request for better app sharing.
