### ISSUE TITLE
Language selection (feature request)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#588]
You know that 1 English word may have many meanings.
It's impossible that there is each screenshot of app interface for each English string on oneskyapp.
It's useful for translators while checking if the translations are correct or not, especially the translators may not be your testers for unreleased version.

When reporting issues by non-English speaking users, it's better that we capture screenshots of English app interface, isn't it?

**Comment by zznosar** [comment]
Isn’t the language controlled by the OS it self? I haven’t seen any app that has it’s own language selection except translator app....  eg google translate...

**Comment by lancelot-moon** [comment]
I don't want to change my iOS language setting.
Why can I not directly change the language of AdGuard (Pro) for iOS, such as AdGuard for Android? 
That's the reason.

**Comment by zznosar** [comment]
I will let @ameshkov to decide of this is really a good idea. There might be some restriction / limitations in ios. It’s not the same as android.

But personally, i would not use this feature. If a user wants to have the app in their language, 90% of the time, they will want the whole OS to be have that language as well. Just my opinion though... dont take it personally.
