### ISSUE TITLE
Feature Request - Use the Default iOS Sharing functionality

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#590]
Insted of clicking the desired icon in the “ Share this App “ section, can we use the built in share mechanism in ios.

Old Share This App icons

![536429ef-1680-4b9d-b048-c09a3a364f35](https://user-images.githubusercontent.com/27464836/34907944-3687584a-f8db-11e7-9693-07a60920d3b4.jpeg)

When selecting Share This App, can we use the below ios native functionality?

![0be9b196-303c-4f2e-bdf6-1f9182acf25d](https://user-images.githubusercontent.com/27464836/34907952-629698ce-f8db-11e7-8d2f-310c2f0c8d59.jpeg)

**Comment by lancelot-moon** [comment]
My idea:
It will jump a horizontal half-transparent pop-up including those "larger" icons (email, message, facebook and twitter...etc.), and then users can tap one of them for sharing this app.

**Comment by zznosar** [comment]
That is good as well. :) the only downside of that is its not flexible whereas the existing ion Share functionality is flexible. As long as the app has the share api., it will appear there. Like facebook, twitter, messeger, wechat, etc.

![8b215623-0157-4d28-93b0-20b43043ebf7](https://user-images.githubusercontent.com/27464836/34910113-a9142e70-f902-11e7-8ca4-cd0f1012552b.jpeg)
![2893ff48-ffef-4164-b91b-5425ad655481](https://user-images.githubusercontent.com/27464836/34910114-a949e790-f902-11e7-8577-34252db0b3b9.jpeg)

**Comment by ameshkov** [comment]
@IvanIin is it easy to do?

**Comment by IvanIin** [comment]
@ameshkov yes, it's easy

**Comment by ameshkov** [comment]
@IvanIin let's do it in v2 then. We can make all the social icons visible there and simply open that system dialog.

**Comment by IvanIin** [comment]
done

**Comment by zznosar** [comment]
This works very well. Tested and found no issues.
