### ISSUE TITLE
Please give max size of 20 custom DNS servers in DNS setting from AG Pro v2.0.0. & Improve the layout in DNS setting.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#591]
The same idea from my another article:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1621

A. After adding some popular DNS providers, it arrives max size of 10 for now manual custom DNS servers in DNS setting.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/XD3YpyS.png)
</details><br/>

Even I still don't add other popular DNS providers and local ISP DNS servers in Taiwan.
So please additionally give max size of 20 custom general DNS servers by users in DNS setting.

Additional:
Add more known DNS providers to the list by ameshkov.
https://github.com/AdguardTeam/AdguardForiOS/issues/543

B. About the improvement for the layout of DNS setting:
(If the wishful layout isn't on time in AG Pro v2.0.0 release version, maybe in the future version...
Or you don't adopt the idea...)
1. The now layout is unable to let me intuitively see DNS IP addresses and servers location on the screen of DNS setting.
I want to simply see **DNS server name, IP addresses, description and servers location** on screen.

2. I don't want to scroll down "so long" here.
It's better that it only shows System default, 1 custom DNS server's (REGULAR DNS SERVER) information and 1 DNS CRYPT SERVER's (ENCRYPTED DNS SERVER) information on the screen of DNS setting.

3. Design that it will enter next screen or jump a pop-up with those many DNS servers after clicking the sections of REGULAR DNS SERVER and ENCRYPTED DNS SERVER.

4. Please let those many DNS servers including manual custom DNS servers be automatically sorted according to name.

**Comment by lancelot-moon** [comment]
In v2.0.0(132), you add Quad 9 DNS in the default regular DNS servers.

In the past version, I could only additionally add 10 custom DNS servers.
Now, I can additionally add 11 custom DNS servers in v2.0.0(132).
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/CfRDiW1.png)
</details><br/>

I supposed that you already give additional space for 20 custom DNS servers by users.
My thought was wrong. XD
I'll wait.
Thanks.

**Comment by ameshkov** [comment]
https://adguard.com/en/blog/adguard-pro-discontinued/
