### ISSUE TITLE
Please update Traditional Chinese translations for AdGuard Pro v2.0.0.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#592]
@aalpatkina 

Sorry that I don't know the next version after v1.3.3 is v2.0.0.
I supposed that I need to wait for a long time.

I look forward to AdGuard Pro v2.0.0 very much, so I joined the tester.

The new strings for AdGuard Pro v2.0.0 are translated 100% now.
(If there are new strings again, I'll translate them soon.)
But I also modified some translations of old strings.
One English word which has many meanings in AdGuard Assistant was translated wrongly.
That's why I request language selection if it's available in iOS.
https://github.com/AdguardTeam/AdguardForiOS/issues/588

Please anew take Traditional Chinese translations from oneskyapp.

Sorry & thanks a lot!

**Comment by zebrum** [comment]
closed as dup.

**Comment by lancelot-moon** [comment]
@aalpatkina 
Actually, this is for AG pro app itself, Not the same with my another issue for filters' translations in all platforms.

In the past, your filters' strings were on your server, which don't belong to app interface translations.
