### ISSUE TITLE
Subscriptions automatically disappeared in unreleased AG Pro v2.0.0 (124). (bug)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#594]
@ameshkov
https://youtu.be/Waak18AAgc8

Reproduction steps:
Don't need to enable AdGuard VPN.
1. Open AG Pro v2.0.0 (124) and add Subscriptions.
2. Close AG Pro v2.0.0 (124) from the background.
3. Open AG Pro v2.0.0 (124).
4. Click "Check Updates" in Subscriptions of Blocking Lists.
5. Close AG Pro v2.0.0 (124) from the background.
6. Open AG Pro v2.0.0 (124). And then Subscriptions automatically disappeared.

May AdGuard team note my other issues for AG Pro v2.0.0?
https://github.com/AdguardTeam/AdguardForiOS/issues/524#issuecomment-357439349

https://github.com/AdguardTeam/AdguardForiOS/issues/550#issuecomment-357440506

Thanks.

**Comment by zznosar** [comment]
@lancelot-moon you recreated it as well. This was raised under issue #575

**Comment by zebrum** [comment]
closed as dup of #575
