### ISSUE TITLE
A wrong word in Strings of Adguard for iOS on oneskyapp.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#595]
@aalpatkina 

Original strings:
You are "connecteed" to the ipv6-only network. In such networks you can not use custom DNS servers. The 'System default' DNS setting will be used instead.

"connected", not "connecteed"
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/wFrHUXC.png)
</details><br/>

**Comment by lancelot-moon** [comment]
@aalpatkina 

Again, AdGuard -> Adguard....
You fixed the word "Categories" before, and then it became "Catigories" back.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/NztYrqf.png)
</details><br/>

**Comment by aalpatkina** [comment]
@lancelot-moon These typos were corrected. Thank you!
'Adguard' was replaced with 'AdGuard' in Adguard for iOS project again.

**Comment by lancelot-moon** [comment]
@aalpatkina 

It became "Catigories" back again...
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/OsIeIsR.png)
</details><br/>

**Comment by aalpatkina** [comment]
@lancelot-moon corrected again

**Comment by lancelot-moon** [comment]
@aalpatkina 

It became "connecteed" back again...

"connected", not "connecteed"
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/wFrHUXC.png)
</details><br/>

**Comment by aalpatkina** [comment]
Thank you. Corrected again.
