### ISSUE TITLE
The new feature and improvement of layout for subscriptions, blacklist/whitelist in user rules of Blocking Lists and the user filter & whitelist in SAFARI Content Blocking

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#596]
@ameshkov

It's better that I post a new issue.

In unreleased AG Pro v2.0.0 (124), some features are done.

Is it possible that there are these new features in v2.0.0 release version or future version?

The incomplete points:
For the subscriptions: (Large numbers of rules)

1. The subscriptions are automatically sorted according to names or time.

2. In unreleased AG Pro v2.0.0 (124), I can add or delete profiles of subscriptions.
But I can't edit profiles of subscriptions!
Editing profiles is necessary if subscriptions' links are changed or re-editing their names/descriptions.

3. Separate taps for enabling or disabling each subscription.

4. Show the time of tapping in the section of "Check Updates".
<details><summary>Screenshot for point 3rd & 4th:</summary>

![image](https://i.imgur.com/80MFcA8.png)
</details><br/>

5. Select to periodically or manually backup the profiles of custom DNS servers, the blacklist/whitelist in user rules of Blocking Lists, subscriptions (filters) in Blocking Lists and the user filter & whitelist in SAFARI Content Blocking to iCloud.
Synchronize these profiles between all users' devices by using iCloud.

For the blacklist/whitelist in user rules of Blocking Lists and the user filter & whitelist in SAFARI Content Blocking: (A few numbers of rules)

1. One tap for enabling or disabling the blacklist / whitelist in user rules of Blocking Lists and the user filter / whitelist in SAFARI Content Blocking.

One tap for enabling or disabling the blacklist / whitelist in user rules of Blocking Lists:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/80MFcA8.png)
</details><br/>

One tap for enabling or disabling the user filter / whitelist in SAFARI Content Blocking:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/9xusgPj.png)
</details><br/>

2. Please let us separately enable or disable each rule (domain) in the blacklist / whitelist of Blocking Lists' user rules and the user filter & whitelist in SAFARI Content Blocking, 

Tap each rule (domain) for editing, deleting, cancelling and ok.
The layout about the rules in user filter of AG for Android is the reference!
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/OQ2X9Rw.png)
</details><br/>

3. The rules are automatically sorted according to names or time.

4. Select to periodically or manually backup the profiles of custom DNS servers, the blacklist/whitelist in user rules of Blocking Lists, subscriptions (filters) in Blocking Lists and the user filter & whitelist in SAFARI Content Blocking to iCloud.
Synchronize these profiles between all users' devices by using iCloud.

**Comment by zebrum** [comment]
@lancelot-moon  I've made several new issues: #600 #601 for 1,2,3 and 1 entries.

4 is here #569 

let's discuss entry 5 and 4 when icloud sync will be ready. 

2 is here #602

**Comment by lancelot-moon** [comment]
@ameshkov 
@zebrum 

4. Show the time of tapping in the section of "Check Updates".
I need to know when I manually clicked "Check Updates" for subscriptions.
I am not sure if this is a reduplicate request.
<details><summary>Screenshot for point 3rd & 4th:</summary>

![image](https://i.imgur.com/80MFcA8.png)
</details><br/>
