### ISSUE TITLE
In unreleased AG Pro v2.0.0 (124), after entering "user filter" or "whitelist" in Safari Content Blocking and then leaving for DNS requests log, while doing "search" above DNS requests log, the color of "cancel" is dark, not gray.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#597]
Normal:
After clicking "search" above DNS requests log, the color of "cancel" should be gray.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/766sw6S.png)
</details><br/>

Abnormal:
But the color of "cancel" is SOMETIMES dark, not gray, which is not obvious.
I ever clicked "search" here and didn't know how to leave "search" [ Finally, I closed AG Pro v2.0.0 (124) for leaving. ] because I didn't find "cancel" due to dark "cancel" at that time. /_\
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/o2kr6RT.png)
</details><br/>

**Comment by zznosar** [comment]
I cannot recreate this in my iPad Pro... am i missing a step?
![727221fa-2824-4ff0-8d58-c4691e65a074](https://user-images.githubusercontent.com/27464836/34937443-0110d254-fa39-11e7-96ec-81a9e2487e34.jpeg)

**Comment by lancelot-moon** [comment]
I already said "sometimes".
My screenshot is the proof.
Try more times.

**Comment by zznosar** [comment]
Ok. I did it like 10 times already with different strings to search... will try spme more.

**Comment by lancelot-moon** [comment]
No, you misunderstood my meaning.
If the "cancel" is already gray, you don't need to try more time.

Simply, when you use AdGuard Pro v2.0.0 (124), randomly go to DNS requests log and do "search".

This is my meaning of trying more times.

Of course, I'll try to find the reproduction steps...

**Comment by zebrum** [comment]
I was able to reproduce the issue on previous builds not on .124.  
I thought it's gone on the latest build. So thank you @lancelot-moon

**Comment by lancelot-moon** [comment]
I just start to join the beta testers from v2.0.0 (124).
V2.0.0 is really great work, especially if my those suggestions for new features and layout can be done.

Thank AdGuard team very much!

**Comment by zznosar** [comment]
I agree with @lancelot-moon. This beta version 2.0 (124) is really good and this will keep on getting better. I'm excited for the final product! :)

Thanks Team! @ameshkov @IvanIin

**Comment by lancelot-moon** [comment]
Привет!
I can reproduce the issue 100%.
https://youtu.be/qgebP03Xwvw

Reproduction steps:
Don't need to enable AdGuard VPN.
1. Open AdGuard Pro v2.0.0 (124).
2. Enter "user filter" or "whitelist" in Safari Content Blocking. (Just enter. Do nothing and then leave.)
3. Enter DNS requests log.
4. Do "search" above DNS request log. The "cancel" is dark, not gray.

**Comment by zebrum** [comment]
@lancelot-moon thanks
@IvanIin steps to reproduce above.

**Comment by lancelot-moon** [comment]
Another:
In unreleased AG Pro v2.0.0 (124), first directly entering "filters" in Safari Content Blocking, while doing "search" above filters, the color of "cancel" is dark, not gray.

https://youtu.be/u-cYIFpHrXo

Reproduction steps:
Don't need to enable AdGuard VPN.

1. Open AdGuard Pro v2.0.0 (124).
2. First directly enter "Filters" in Safari Content Blocking.
3. Do "search" above those filters. The "cancel" is dark, not gray.

**Comment by IvanIin** [comment]
fixed
