### ISSUE TITLE
Add separate switches to turn on and off each subscription 

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForiOS#601]
AdGuard v.2.0

3. Separate taps for enabling or disabling each subscription, blacklist and whitelist (#596) :(https://camo.githubusercontent.com/1f01c3f371f54d38e0a9ee1b3401af26a8e1336e/68747470733a2f2f692e696d6775722e636f6d2f38304d466341382e706e67)

Also add the same switches for User filter and whitelist of Content blocker:

(https://camo.githubusercontent.com/b91e09d4529566092ca1f72d682c81a93131bb40/68747470733a2f2f692e696d6775722e636f6d2f3978757367506a2e706e67)

**Comment by lancelot-moon** [comment]
Hi, maybe AdGuard team can also add a tap for default "filters" in Safari Content Blocking.
The interface will look harmonious.
Anyway, you decide if a tap is necessary for default "filters".
I have no opinion.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/9MMqgP7.png)
</details><br/>

B/R

**Comment by ameshkov** [comment]
https://adguard.com/en/blog/adguard-pro-discontinued/
