### ISSUE TITLE
Checkbox to enable/disable rule

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForiOS#602]
Add checkboxes to enabling/disabling rules in User filter, Whitelist, Blocking lists like we have in android/windows versions:

https://camo.githubusercontent.com/ac58b2e0d316dc61938c2e64c0b61b0b0904223b/68747470733a2f2f692e696d6775722e636f6d2f4f5132583952772e706e67

**Comment by lancelot-moon** [comment]
1. Separately enable or disable each rule (domain) in the blacklist / whitelist of Blocking Lists' user rules.
2. Separately enable or disable each rule (domain) in the user filter & whitelist in SAFARI Content Blocking,
3. Tap each rule (domain) for editing, deleting, cancelling and ok.

**Comment by worldsdream** [comment]
Duplicate. This was already asked by me:

https://github.com/AdguardTeam/AdguardForiOS/issues/194

**Comment by lancelot-moon** [comment]
Not actually.
Your feature request is only my 2nd point.
2. Separately enable or disable each rule (domain) in the user filter & whitelist in SAFARI Content Blocking.

I have other 3 points which you didn't talk about.

**Comment by nsahub** [comment]
But... I have 5 points which _you_ didn't talk about.
