### ISSUE TITLE
Change Adguard to AdGuard in widget

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#603]
It's still Adguard in both 1.3.3 and 2.0 beta.

![image](https://user-images.githubusercontent.com/15856304/35036691-ccabc01e-fb7d-11e7-9cef-4b0fec43eef1.png)

**Comment by lancelot-moon** [comment]
Change all "adguard" to AdGuard.
Ex: "How to enable adguard?"
Somewhere it's still "adguard" in v2.0.0 (124).

**Comment by ameshkov** [comment]
Duplicates #618
