### ISSUE TITLE
Blacklist gets deleted AdGuard 2.0 iOS 

### ISSUE THREAD

**Issue by mikeoleary7528** [AdguardTeam/AdguardForiOS#605]
Hi,

Sometimes when app crashes, phone shut downs or after a certain amount of time the blacklist I have imported into the blocklist vanishes. I’m on iOS 11.2.5 beta 6 and AdGuard 2.0(124)

**Comment by zebrum** [comment]
dup of #575 ?

**Comment by ameshkov** [comment]
Yep, it is
