### ISSUE TITLE
What's the difference between bright/dark red in DNS requests log? (question)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#606]
Originally, I supposed that only there is dark red in DNS requests log if that DNS request is blocked.
However, I saw bright red in DNS requests log and then those DNS requests were only processed, "not blocked".
Why are they not blocked since it's red color?
Something which I misunderstood?
What's the difference between bright/dark red in DNS requests log?

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/w9XUYO4.png)
</details><br/>

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/cB7xwTh.png)
</details><br/>

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/qypXqZS.png)
</details><br/>

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/JSFOqqT.png)
</details><br/>

Additionally, I note that not every DNS request shows the "service information".
Most DNS requests only show the "response".
Why is "service information" not shown in every DNS request detail?
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/hoL0hu5.png)
</details><br/>

**Comment by zebrum** [comment]
It means they were detected, not blocked: 
https://github.com/AdguardTeam/AdguardForiOS/issues/579#issuecomment-357936375

**Comment by lancelot-moon** [comment]
I think that you should indicate they're trackers.
Are trackers unnecessary to be blocked?
Why does AG Pro show bright red for trackers since AG Pro doesn't block them?

**Comment by lancelot-moon** [comment]
@ameshkov 

1. I didn't use AdGuard DNS server and only used AdGuard SDN filter as the subscription at that time.
There is the rule, ||voicefive.com^, in AdGuard SDN filter.
It's strange that sb. voicefive.com wasn't blocked, only processed.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/cB7xwTh.png)
</details><br/>

Is the priority of trackers database higher than ad filter?

2. I deleted AdGuard SDN filter and didn't use AdGuard DNS server.
I used 1hosts.cf as the subscription.
Well, that includes AdGuard filter (the format of hosts file).

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/MIBkMar.png)
</details><br/>

Why could AdGuard Pro still know it's a tracker and show bright red in DNS requests log without  AdGuard SDN filter and AdGuard DNS server?
Is the trackers database built in AdGuard Pro?
I don't think so...
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/DP8CMsa.png)
</details><br/>

3. May you tell about the max limit of entries' counts in subscriptions?
It seems that it's still ok even if I imported about 57000 entries into AdGuard Pro.

Thanks!
