### ISSUE TITLE
The status in DNS request detail of unreleased AdGuard Pro v2.0.0 (124).

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#607]
Before, I also noted the issue.
https://github.com/AdguardTeam/AdguardForiOS/issues/584

If using default AdGuard SDN filter in subscriptions, the status in blocked DNS request will only show "blocked by blacklist".
It should indicate what exact "blocking list" has blocked a request.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/3cXAdrR.png)
</details><br/>

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/z3VUC3n.png)
</details><br/>

If using a custom filter in subscriptions, the status in blocked DNS request will normally show "blocked by which subscription".
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/8d3YXCh.png)
</details><br/>

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/DgJkfNo.png)
</details><br/>

Well, it seems that it can only show "blocked by blacklist" and it's unable to normally indicate what exact "blocking list" has blocked a request if using the default subscriptions.

**Comment by zebrum** [comment]
@lancelot-moon please let's discuss this topic in #584  
Why create similar issues? :)
