### ISSUE TITLE
Adguard for iOS returns error when refreshing filters (iOS 11.2.5 beta, iPhone X)

### ISSUE THREAD

**Issue by solusla** [AdguardTeam/AdguardForiOS#609]
1. Install Adguard on an iPhone X running iOS 11.2.5 beta.
2. Load filters.
3. Quit Adguard.
4. Open Adguard again and try to refresh filters.

### Expected behavior
It should refresh the rule set.

### Actual behavior
It returns an error saying the it cannot load the filters into Safari.

I cannot always reliably reproduce this problem and often have to wait several hours after a successful refresh for the problem to recur. Once the error does occur, however, I can only resolve it by restarting the device—quitting the app via the switch and relaunching does not fix it.

### Your environment
* Device model and storage size: iPhone X 256GB.
* Operating system and version: iOS 11.2.5 beta.
* Browser (e.g. Safari): Safari.
* Wi-fi or mobile internet connection: WiFi or Cellular.

**Comment by zebrum** [comment]
Hi @solusla !
This is the known issue, you can read more info here: #550 
Closed as duplicate
