### ISSUE TITLE
Questions about HTTPS filtering

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#610]
Excuse me, bother you again...
I want to clarify some questions.

I don't fully understand the difference between AdGuard Pro for iOS and AdGuard for Android in the aspect of HTTPS filtering.

1. Can AdGuard Pro for iOS do HTTPS filtering without AdGuard certificate installed?
I know adblockers on iOS can only do DNS filtering...
So AdGuard Pro for iOS can't do HTTPS filtering, right?

2. If ads are under the path from the internal server, and we can't block that whole domain because it includes general data...
A. AdGuard Pro for iOS can only filter domains, not paths. So it can't block ads.
B. AdGuard for Android can block not only domains but also paths. So it can block ads as long as its HTTPS filtering can resolve all network traffic.

3. As what we know, AdGuard for Android is unable to directly filter network traffic which doesn't trust AdGuard certificate.
If there is a path which calls external ad servers (The ads aren't under the path. Not from the internal server.), and we can't block that whole domain because it includes general data...
a. Can AdGuard Pro for iOS block those ads? <- This is what I specially want to check.
b. We only talk about Android v7/v8 users.
With root access, AdGuard for Android can block ads after moving AdGuard certificate to system store.
Without root access, AdGuard for Android can't block ads. (Don't depend on "Parallel Space" app.)

May you answer me if my thought is wrong?
Thank you very much! :3

**Comment by ameshkov** [comment]
> Can AdGuard Pro for iOS do HTTPS filtering

It cannot do it at all :(

> A. AdGuard Pro for iOS can only filter domains, not paths. So it can't block ads.

Yes.

> B. AdGuard for Android can block not only domains but also paths. So it can block ads as long as its HTTPS filtering can resolve all network traffic.

Yes.

> a. Can AdGuard Pro for iOS block those ads? <- This is what I specially want to check.

Nope, it cannot.

> b. We only talk about Android v7/v8 users.
> With root access, AdGuard for Android can block ads after moving AdGuard certificate to system store.

Yes, mostly. Some apps do their own certificate check (facebook, twitter, instagram), we cannot do anything with them. Fortunately, the list of such apps is very short.

> Without root access, AdGuard for Android can't block ads. (Don't depend on "Parallel Space" app.)

Yes, unless you use a "parallel space" approach. This is an interesting topic actually, we'll see maybe we can implement the same functionality in AdGuard.

**Comment by ameshkov** [comment]
The iOS and Android versions might simply be quite different under the hood.
