### ISSUE TITLE
Distorted logo in 2.0.0.124

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#611]
![image](https://user-images.githubusercontent.com/15856304/35184736-174770f6-fe02-11e7-85b9-78b21b025276.png)

### Your environment

* Device model and storage size: iPhone iPhone 5s
* Operating system and version: 2.0.0.124
* Browser (e.g. Safari) n/a
* Wi-fi or mobile internet connection n/a

**Comment by ameshkov** [comment]
Duplicate of #578
