### ISSUE TITLE
Please update the filters' translations in Traditional Chinese language file.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#615]
@aalpatkina 

Do I need to post the request in all platforms (AdguardBrowserExtension, AdguardForiOS, AdguardForAndroid, AdguardForWindows and AdguardForMac) on AdGuard's GitHub?

Or will you automatically update filters' translations to Traditional Chinese translations in all platforms?
Then I only post the request here.

I guess that you moved filters' strings from a server to here, right?
http://adguard.oneskyapp.com/collaboration/translate/project/project/119172/language/2#/page/1

Although I didn't receive this notification about the new location of filters' strings, I had completed them all 100%!
In the past, you wrongly applied Simplified Chinese in Traditional Chinese language file.
Taiwanese people detest seeing Simplified Chinese.

Hope that I can see Traditional Chinese in the section of filters in AdGuard Pro for iOS v2.0.0, AdGuard for Android v2.11 and other platforms' future version.
Thanks a lot!

**Comment by lancelot-moon** [comment]
@ameshkov

Do you not change the name of English filter to Base filter, Universal filter or other this time?

**Comment by zebrum** [comment]
> Do you not change the name of English filter to Base filter, Universal filter or other this time?

@lancelot-moon not yet.

Translations will be updated before final release. Don't worry.

**Comment by lancelot-moon** [comment]
@vbagirov 
@ameshkov 
@aalpatkina 

Sir, please don't change my translations on oneskyapp.
Especially, your some translations are unsuitable.
Ex:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/WjIZA3a.png)
</details><br/>

You used "俄文過濾規則" for Russian filter.
That's wrong.
規則=rule
In "Russian filter", there is no "rule".
filter=過濾器(n) or 過濾(v)

Because you modified them, I have to spend time anew recovering them back one by one...
AdGuard team have higher authority on oneskyapp than translators.
If you modified any translations, I don't know the things, and it's trouble to find them all.
Those are written by my mother tongue.
I have spent a lot of time on translating your website and apps...
Please don't add my loading.
For quality translations, please don't change my translations on oneskyapp again.

Thanks again.

**Comment by vbagirov** [comment]
@lancelot-moon that was necessary, unfortunately. We had to move all existing translations from the old project (**Miscellanous (Deprecated)**) to the new one (**Miscellanous**), for all languages. To do it manually would take an awful lot of time, so there was some splash damage after the automatic phrases uploading. This is a one-time measure and it won't normally happen.

**Comment by lancelot-moon** [comment]
Thanks a lot.
Please don't mind.
I ask myself to do quality translation.
If translations are filled in by other translators, I can know and check the quality.
But if they are approved by AdGuard team, it's difficult to find them all and check.
Taiwanese wait the Traditional Chinese for filters for a long time.
So I specially care about them.

In some aspects, I am a perfectionist.
Sorry if offending you.
Please don't put them on your mind.
Thanks a lot!

**Comment by vbagirov** [comment]
No problem! It is me who should apologize :) We should have at least informed you and moderators of the other affected languages about this.

**Comment by zebrum** [comment]
closed as It's not really about iOS app.
