### ISSUE TITLE
Warn user if there're too many blocking lists added

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#616]
Due to the VPN tunnel RAM limit, adding too many blocking lists may break the tunnel (and the internet as well).

We should find a way to alert user when this happens.

**Comment by IvanIin** [comment]
We can roughly calculate the required memory and display a warning when the limit is exceeded. Also we can detect crash in the tunnel itself due to a lack of memory and then show the message in the main application. We can also turn off filtering in this case.

**Comment by mikeoleary7528** [comment]
Those are great feature ideas! What about checking for double entries from different filter list?  So if I have two filters and both have adsmop.com to block it use the first filter one and not the other?  That would also help on memory issues too.

**Comment by ameshkov** [comment]
Duplicates are eliminated of course

**Comment by javabean** [comment]
> Duplicates are eliminated of course

This does not seem to be the case with AdGuard 4.0.
I created 2 very similar DNS filters, each totaling about 40k entries.
Upon activating them, the total reported was 80k rules, when it should be 40k if it was correctly deduplicating.
