### ISSUE TITLE
Custom DNSCRYPT feature works beautifully thus far!

### ISSUE THREAD

**Issue by X8716e** [AdguardTeam/AdguardForiOS#617]
I’m going to continue testing, using a (tentative) list of providers I’ve got recorded. If any problems occur with those I know to function, I’ll post here. Any (tentatively) dead providers, after I confirm they’re dead via desktop, I will remove from list. When the list is thus trimmed, I will finally post it as a community resource for those wanting it. I think my 3-4 day time estimate has expired so I’m adding another 48 hours. 👍

**Comment by zznosar** [comment]
I have to agree with @X8716e . Loving this version. Good work guys! Well done AdGuard Team. @ameshkov

**Comment by vozersky** [comment]
great :)
reopen if something goes wrong :)
