### ISSUE TITLE
Change Adguard to AdGuard in the list of DNS

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#618]
Just some minor tweaks. Can we change Adguard to AdGuard in the list of known DNS?
![584f2051-f6cd-402e-b11d-6b8bdab1555c](https://user-images.githubusercontent.com/27464836/35354503-45069c02-019e-11e8-828e-a2efa2a7ff79.jpeg)

**Comment by lancelot-moon** [comment]
Simply, even if AdGuard team fixed Adguard to AdGuard, it will become Adguard back after some time.
Or wrong words were back.
So v2.0.0 (128) applies defective English strings at that time.

It seems that @aalpatkina has solved the issue on oneskyapp.

In Traditional Chinese interface, it applies my translations, so it totally shows AdGuard in app.

**Comment by zznosar** [comment]
Some more string that needs updating:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/27464836/36470859-75721ea4-1740-11e8-8d9e-35a446767c33.png">

Thanks!

**Comment by zznosar** [comment]
Fixed in beta 138. So good. I think it’s ready for release, not unless major bugs are discovered. Thanks team!

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/27464836/36559079-f2deb5de-1860-11e8-86e4-8bc7cc875172.png">

<img width="1112" alt="image 2" src="https://user-images.githubusercontent.com/27464836/36559109-0a484a28-1861-11e8-9705-9de5dc9a2fbc.png">
