### ISSUE TITLE
Please change color in DNS requests log.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#620]
Bright color easy let eyes feel tired and uncomfortable if looking at DNS requests log for more time.
1. For trackers and analytics, please change the color from bright red to dull yellow.
2. For general domains, please change the color from bright white to dull white.

May someone answer about my questions?
https://github.com/AdguardTeam/AdguardForiOS/issues/606#issuecomment-359168460

Thanks.

**Comment by zznosar** [comment]
I actually like the red color. I will automatically know that something is not right or traking me. Instead of yellow which is not striking. Because if it’s red, you will know something is not right.

The same for the white color. White color automatically turns dull white when night shift is enable. So i am like the current white more.

**Comment by zznosar** [comment]
I also forgot, changing these colors to Yellow and dull white will impact devices that uses True Tone display and night shift.

**Comment by lancelot-moon** [comment]
For trackers, even google.com is shown bright red.
Since trackers are not blocked (only processes), I feel that red isn't suitable.
Dull yellow is better for trackers.
Like traffic lights, it will be colorful in log.

And then bright color isn't good in log.
That's why they are dull red for blocked and dull green for whitelist now.
So should they be bright red and bright green according to your opinion?

In log, maybe there are many domains.
Dull color is suitable to view for a long time.
Let eyes be comfortable!
Do you know why words in the article on PTT BBS are designed to dull white?
That's the reason!

**Comment by zznosar** [comment]
Dull white and yellow will not show correctly when a device has true tone display on and night shift. Probably a different color is ok.

**Comment by zznosar** [comment]
True tone display automatically adjust the color temperature in your screen (color saturation). Including night shift. Please try enabling them in your device if tou have them. They protect your eyes in theory. You will know what i mean! :-) :-)

**Comment by lancelot-moon** [comment]
The background of log is black.
Dull yellow is visible enough.
I'll try True tone display.
However, general users don't specially do other setting.
I like my thought from traffic lights.

AdGuard team will decide which is better.
I have no opinion after they knock down.

**Comment by X8716e** [comment]
I haven’t yet looked @ DNS log colors; however the entire UI in 2.0.0 (132) is nicely recreated.

**Comment by lancelot-moon** [comment]
Sir,

These are examples for your reference.
On mobile PTT BBS app, dull colors are used for words in articles for comfortably reading.
Because the background is black, dull white and dull yellow are visible enough.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/Nd30JWB.png)

![image](https://i.imgur.com/RQdLrkH.png)
</details><br/>

**Comment by X8716e** [comment]
@lancelot-moon , ok ok I hadn't yet looked @ logs at that point. I see no colors like you are, however. I’d actually enjoy having purple, cyan, yellow, etc. It looks as though your phone displays the CY... color spectrum in full-force, which is odd though nice (I think). I really have no answews for you. I do agree w @zznosar regarding night shift, though. I always use it, often during the time I’m awake as well during the day. I set mine @ max on a schedule & adjust it as necessary for daytime use. And I know @zznosar & myself aren't among a minority of people who do use it. I highly doubt Apple would've listened to just a few beta testers regarding implementing the feature now known as ‘Night Shift’.

**Comment by lancelot-moon** [comment]
I have actually tried to enable ‘Night Shift’ on my iPhone.
In my real experiment, dull yellow and dull white are obviously different under ‘Night Shift’, and they're visible enough in the black background!

@ameshkov 
You can try to read the article on PTT BBS by website mode under ‘Night Shift’.
The writer used some different dull colors for Chinese characters in his article.
https://www.ptt.cc/bbs/JinYong/M.1517759182.A.EC0.html

Since trackers and analytics aren't blocked, it's not better to use bright red for them.
Simply, please privately do the experiment (use dull yellow and dull white) in AdGuard Pro beta version for the test.

B/R

**Comment by zznosar** [comment]
Hopefully the AdGuard Team can accomodate the colours you suggested in such a way that it will show correctly with users who always use night shift like @X8716e ,  people who always use both true tone and night shift like me and also for different types of screen - oled and lcd - as both of them shows colour a bit differently. 

Or they can select what ever colour is suitable. Me and @X8716e will test it and provide feedback, if applicable.

**Comment by zebrum** [comment]
It will be done in #656
