### ISSUE TITLE
Feature Request : Enhance AdGuard Widget

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#621]
Is it possible to have a very informative and interactive widget for AdGuard Pro in the future versions?

Probably something that will show the below:

![e541c059-ee8c-40a3-93e3-64b38866039e](https://user-images.githubusercontent.com/27464836/35383204-b5f87bc0-0215-11e8-991e-0c08e769dd0a.jpeg)

And the DNS name where you are connected plus toggle on / off

**Comment by zebrum** [comment]
@Roshanalexander we can't do this: https://github.com/AdguardTeam/AdguardForiOS/issues/312#issuecomment-318376189

**Comment by ameshkov** [comment]
https://adguard.com/en/blog/adguard-pro-discontinued/
