### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by X8716e** [AdguardTeam/AdguardForiOS#625]
How are alternative ports handled / chosen when connecting to any of the pre-listed DNSCRYPT resolvers?

**Comment by IvanIin** [comment]
We use [this](https://github.com/dyne/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv) list of servers. Custom ports are specified in the usual way 0.0.0.0:555 for ipv4 and [0::0]:555 for ipv6. The user can not change the predefined servers, but can set ports for custom servers by the same rules.

**Comment by X8716e** [comment]
@IvanIin , thank-you. Though I was specifically thinking of servers with multiple listening ports such as d0wn’s servers. How are the ports used chosen for his servers? And for @fusl’s anycast servers as she also has multiple listening ports opened.

**Comment by ameshkov** [comment]
> How are alternative ports handled / chosen when connecting to any of the pre-listed DNSCRYPT resolvers?

Copy/pasting from another issue, we're getting it from here:
https://dnscrypt.info/public-servers

**Comment by X8716e** [comment]
@ameshkov , when will the sever list included with AdGuard be updated to match the above referenced https://dnscrypt.info/public-servers?

**Comment by ameshkov** [comment]
@X8716e waiting till it's stabilized, things are changing quickly there :)
