### ISSUE TITLE
List I’ve been promising.

### ISSUE THREAD

**Issue by X8716e** [AdguardTeam/AdguardForiOS#626]
This is a partial list as Eduardo at @opennic has other servers available. Also, as stated, the two Canadian servers are only available to those who’ve been whitelisted. Becoming whitelisted is a simple process, requiring an email address as your only source of info. Setting up a Protonmail.com account strictly for this purpose is recommended for anyone who desires an added layer of privacy. They’ve a free iOS app. Sign up @ `https://opennic.org/` to be whitelisted.

```
A 146.185.176.36
AAAA 2a03:b0c0:0:1010::1a7:c001

Location:

52 22 12.777 N 4 53 42.604 E 9.47m 19m 100m 10m
Amsterdam, Netherlands

Policy: No logs kept.

DNSCrypt-Name: 2.dnscrypt-cert.opennic.peer3.famicoman.phillymesh.net

DNSCrypt-Key:

B88F:4860:5517:3696:A3D2:BFE0:ECC7:6175:198F:E012:E101:B4FE:869C:1E9C:4C35:E74F

IPv4 ports: 5353 IPv6 ports: 5353

=========

A 128.52.130.209
AAAA 2001:470:1f06:10b::2

Location:

42 21 43.072 N 71 5 24.941 W 0.00m 0m 100m 10m
Cambridge, MA, USA City, region, country

Policy: no query logging

DNSCrypt-Name: 2.dnscrypt-cert.onic.csail.mit.edu

DNSCrypt-Key:

128D:B1BD:E10C:7CA1:D52B:091F:633E:99C1:937D:14F5:F812:B0CB:5B3C:F5CB:CC04:7272

IPv4 ports: 443 IPv6 ports:

=========

A 81.2.241.148
AAAA 2001:15e8:0110:0994:0000:0000:0000:0001

Location:

2 38403 384 03 E

City, region, country
Kti, Czechia

Policy: Only abuse query are logged(For fail2ban ban system)

DNSCrypt-Name 2.dnscrypt-cert.cz.edoardocolombo.eu

DNSCrypt-Key

3B7D:AD0D:7DC9:7321:A7B0:B0B3:3A43:DF5B:1E1A:0E62:1374:FB54:5A9E:9AE4:998 8:6319

IPv4 ports 443 IPv6 ports 443

Status page: https://status.edoardocolombo.eu

=========

2.dnscrypt-cert.ns3.ca.luggs.co

1C19:7933:1BE8:23CC:CF08:9A79:0693:7E5C:3410:2A56:AC7F:6270:E046:25B2:EDDB:04E3

IPv4 Ports 443 IPv6 Ports 443

A 142.4.205.47
AAAA 2607:5300:120:a8a:142:4:205:47`

Location 46 51 28.800 N 71 20 45.960 W 0.00m 1m 10000m 10m

No Logging
Whitelist Only

=========

2.dnscrypt-cert.ns4.ca.luggs.co

BCBF:B7E0:50C1:3DA2:422C:00B0:B1AC:9AD6:48C5:C264:BCB6:170B:883D:718A:C86E:BA09

IPv4 Ports 443 IPv6 Ports 443

A 142.4.204.111
AAAA 2607:5300:120:a8a:142:4:204:111

Location 46 51 28.800 N 71 20 45.960 W 0.00m 1m 10000m 10m

No Logging
Whitelist Only
=========
```

**Comment by ameshkov** [comment]
> Becoming whitelisted is a simple process, requiring an email address as your only source of info

That's a weird limitation.

We are usually loading the available filters list from the central resolvers list (it is now located here: https://dnscrypt.info/), it makes sense to add these servers to that list.

**Comment by X8716e** [comment]
More detail:

1. It gives one membership in the @OpenNic decentralized, alternative NIC “organization”.
2. One’s provided address is given only to @OpenNic , not individual server providers.
3. Those persons who run whitelist-only servers do so to provide members with servers that are more responsive as they do not incur the burden of the heavy traffic that the public servers do.
4. The servers I listed are run by a well respected individual - @luggs-co - who has the logging function of his whitelisted severs _totally disabled_ meaning even if he were for any reason coerced into providing any records of user actions, it would simply not be possible because they never existed in the first place.
5. So it is less an issue of privacy than is connecting to servers that do have logs for any stated reason(s), no matter how long they are kept. And that’s discounting what those who do have logging functions enabled actually do with those logs voluntary either for profit or for reasons _required by local law_ as countries around the world do have laws requiring providers of network services either a) store the collected logs for an indefinite period of time and/or b) turn over those logs for given periods of time in a pre-emptive manner.

**Comment by luggs-co** [comment]
Thanks for the reference @X8716e

**Comment by luggs-co** [comment]
Whitelisting requires an account on opennic and you submitting the IP you want whitelisted to the api which our servers pull from.

More information here: https://wiki.opennic.org/api/whitelist

**Comment by X8716e** [comment]
@luggs-co Thanks for the link to the [specific manpage](https://wiki.opennic.org/api/whitelist) in the wiki; it’s a resource I often forget. I’ve used your severs since discovering how exceptionally reliable & responsive they are; that was soon joining @opennic (x)years ago. @shdwdrgn & @ahanselka are my other two go to providers, though they haven’t @dnscrypt enabled.
