### ISSUE TITLE
A warning when entering DNS setting without internet.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#627]
The issue exists from the past until now.
When entering DNS setting without internet, it shows the warning.
"You are connected to the ipv6-only network. In such networks you can not use custom DNS servers. The 'System default' DNS setting will be used instead."
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/wwIVtUy.png)
</details><br/>

Is it a bug?
May you let the warning not occur when entering DNS setting without internet?

Thanks.

**Comment by IvanIin** [comment]
fixed
