### ISSUE TITLE
Please show the sum of current active rules on the top of Blocking Lists. Move "check updates" and "Add subscriptions" on the top of Subscriptions.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#631]
Ameshkov taught us that the limit for VPN tunnel is 15 MB.
https://github.com/AdguardTeam/AdguardForiOS/issues/562#issuecomment-360200728

1. I tried to test Blocking Lists' limit of rules on my iPhone 6 Plus.
About 89166 rules, VPN tunnel is still normally working.
But VPN tunnel broke down when there were 91363 rules.

Its limit for VPN tunnel is around 90k rules.
I already got the number of upper limit in my mind.
After all, my iPhone 6 Plus is an old device.
I am not sure if iPhone 8 and X are so.

May you design to show the current active rules' sum of blacklist, whitelist and subscriptions on the top of Blocking Lists?
Under it, that's the warning which reminds users to not enable the numbers of rules over what AdGuard team roughly calculate.
Just an example.
Maybe you have more beautiful layout.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/E1Sxbyd.png)
</details><br/>

2. If adding some subscriptions, the length of subscriptions screen is a little long.
I don't want to scroll down.
Please move "Check updates" and "Add subscriptions" on the top of Subscriptions.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/oiOXdtO.png)
</details><br/>

3. For managing more subscriptions, the feature which I requested is necessary.
https://github.com/AdguardTeam/AdguardForiOS/issues/601

<details><summary>Screenshot</summary>

![image](https://i.imgur.com/80MFcA8.png)
</details><br/>

Users maybe subscribe some filters.
And then it's easy over the upper limit of rules.
It's inconvenient to always delete them for avoiding over the upper limit.
I need to anew fill in subscriptions' name and URL for adding them back.
That's not a smart method.
For blocking lists, I wish better management, not only the 2 operations of adding and deleting.
Please give us individual switches for enabling or disabling the blacklist, whitelist and each subscription.

I would rather wait until AdGuard Pro v2.0.0 release version is really ready and presents the best to its users.

Someone just has narrow horizons and simply don't understand & appreciate:
 **Good things are worth the wait!**
> The Major Features are ready to be released. That’s what I meant. You focus too much on little things.
Try to appreciate the bigger ones.

**Comment by Sailor-Chibimoon** [comment]
@lancelot-moon you need to stop igniting the fire with your last detail. This will start a fight again. I really now understand what that person said. 

You really sounded like you are commanding AdGuard Team the app cannot be release if they dont don’t fulfill your request. Sadly,  but it’s true.

We can have your request in the future version rights? And not in v2.0? It’s very obvious that you want your request in v2.0... You need to relax. And let the team decide when.

This request is more like AdBlock by Future Mind which has switches. 

I actually have both. 

But I use adGuard since it’s more simple.

Adblock by future mind is very complex and is not user friendly. I like the simplicity is AdGuard Pro.

Just select and forget.

I would like to try the DNSCrypt.

In my opinion, release the DNSCrypt version first before doing the above. I read many people are waiting it for since a couple of years now.

**Comment by lancelot-moon** [comment]
I have stayed on AdGuard's GitHub for more than 1 year.
I don't need to be suffered such unreal accusation, Beginner @Sailor-Chibimoon.

Everyone can express his standpoint.
However, someone and you started to attack and tag me with some malicious words.
Before you edited mistakes in your original article, your English teacher was crying behind you.
Maybe my tune is direct, but such these words, "please, sorry..etc.", are also often in my article.
I very thank AdGuard team for the such great app.
Maybe my tune is direct.
The gramma of my English is correct.

Well, I supposed that you love your Taiwanese husband, so you had learned some Chinese.
How about writing a Chinese article by yourself?
Do you think I'll ridicule your bad Chinese?

How much of time have you spend on discussing about AdGuard after you came to here, Beginner Sailor-Chibimoon from AdBlock by Future Mind?
It's strange that you spent more time on me.
It proves that you more like arguments, compared with discussing about AdGuard.

Particularly read your articles to me, they're full of frivolous English and emoji.
Please do not write "Sailor" in the front of my user name, Beginner Sailor-Chibimoon!
Why not watch the Japanese anime, "Sailor Moon", at your home?
From the beginning, you're only a busybody and don't know to respect other people.

I quoted those words because the articles by someone and you are excessive in another post.

Everyone can express his standpoint.
We can be aimed at things, not attack a person.

For you, you just know enjoyment.
You only thought that it's a productivity tool.
Even said "not a game".
Could you think about other things if men concentrate on something, except for a game?
Could you understand that some persons devoted themself to AdGuard?
No, you just enjoy.

For me, I treat AdGuard as work although I am only a volunteer.
We report bugs and user experience to AdGuard team.
Additionally, I am its translator.

Which situation is there the pressure if a bos asks you to complete work tomorrow or let you have enough time to well do work?

Your logic is strange.

And then I never ask AdGuard to not release AdGuard v2.0.0 before my requests are done.

Focus on bigger things, or only see what someone wishes and then ignore other important points?

Even web reporting tool is still not integrated in AdGuard v2.0.0 beta version since that feature is planned in AdGuard v2.0.0 release version.

You guys only think of yourself.

AdGuard team decide the schedule and listen users' voice.

They do their good work in design, and I do my good work in translating, reporting bugs & providing my ideas.
We together complete our best for users.

You have molested me.
Your sense of superiority, frivolousness and malice behind your articles let me feel disgusted.
Simply, leave me alone.

I came here for discussing with AdGuard team and those who like AdGuard.
AdGuard team have taught me much.
Sorry for this.

Simply, you leave me alone if you sincerely want to stop arguments.
Everything will be fine.

**Comment by Sailor-Chibimoon** [comment]
Ok. I wonder what happened why your english becomes so good this time. Probably you asked someone to do it for you. 

I will just shut up then since you still obviously does not know what’s wrong with you. 

Who am I to judge. I am just a beginner. 😊😊😊 Relax. 

And yes i love sailor moon.

That why when I see your username, i really think it’s cute. 

You’re a sailor soldier. 

Ok. Bye now. I wonder if you are this “playful” to new users of AdGuard. If you are their employee, with this attitude, they will probably lose users because of you.... ✌️✌️✌️

**Comment by lancelot-moon** [comment]
It's funny.
I'm resposible to translate AdGuard's English interface to Traditional Chinese. 
And you constantly insult my English.
I wrote that at midnight by myself.
My English isn't fluent but it's enough to do quality translations for AdGuard.
How about writing a Chinese article by yourself and not depending on your Taiwanese husband and google translator? 
Will it let you have the sense of superiority or fun by insulting other people?
Please don't add unreal accusation on me. Respect different standpoints.
Your frivolousness has offended me.
What you did is pouring oil on the fire.
Sorry, maybe my tone is serious.
Simply, leave me alone.
It's better for us.

End. Let unhappy things be gone.
Thanks.

**Comment by Sailor-Chibimoon** [comment]
Ohh.😊😊😊 Cutie. Here is a remembrance of our good time together. Sailor @lancelot-moon 
 Til next time! 

![img_8004](https://user-images.githubusercontent.com/36011305/35804751-2127f3f2-0acd-11e8-9fd1-2a31c47d5a67.JPG)

**Comment by ameshkov** [comment]
https://adguard.com/en/blog/adguard-pro-discontinued/
