### ISSUE TITLE
Feature Request : What’s New Section in AdGuard Pro

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#632]
Hi AdGuard Team, 

Is it possible to have a “What’s New” section inside About and splash screen in AdGuard after we update the app? I think it will be helpful for users to know what was fixed or enhance or the new features in an update or a version.

The splash screen will only show once you update the app and open the app after the upgrade. It can also be shown during first install.

It’s nice to have and will be informative especially for people who have Automatic Updates enabled.

Sample screen shot 1 
![img_3509](https://user-images.githubusercontent.com/27464836/35724126-cb2a2872-0850-11e8-8561-0f56b1991809.JPG)

Sample screen shot 2
![img_3510](https://user-images.githubusercontent.com/27464836/35724140-d2e10f9a-0850-11e8-88a0-5997f78ce253.JPG)

**Comment by Sailor-Chibimoon** [comment]
I love this request. Hopefully they can implement it soon ~ when applicable.
