### ISSUE TITLE
Feature Request : Face ID and Touch ID Support

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#633]
Not sure if there is an existing request, but can we have touch id and face id support in AdGuard Pro to prevent unauthorised access / changes to the app especially with people that have kids (intelligent kids that will disable AdGuard Family DNS or rules...)

Not a hight priority. Just nice to have. Please close if there is already an existing request.

**Comment by zebrum** [comment]
yes. there is #474
