### ISSUE TITLE
AdGuard crashes while checking updates in Subscriptions

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForiOS#637]
### Steps to reproduce

1. go to Blocking Lists - Subscriptions
2. Tap 'Check updates

### Actual behavior

AdGuard crashes.

**Comment by X8716e** [comment]
Fixed in 2.0.0 (132)

**Comment by zznosar** [comment]
No crash in the current beta 2.0 (132). Tried in two devices.
