### ISSUE TITLE
Change string 'Check for filter update' and date format 

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForiOS#640]
Let's have 'Update filters' for en and 'Обновить' for ru locale.

Date format: 
- display only time if filters were updated today 

else

- display only date if filters were updated any day before today.

**Comment by lancelot-moon** [comment]
Honestly, I more like the now format of time for "Check for updates" in subscriptions...
It's clearer.

**Comment by zznosar** [comment]
Tested. Seems to be ok. I only check filter / blocking list updates once in a while ( as you can see in the screenshot below) i’m ok with the new approach.

<img width="320" alt="image 6" src="https://user-images.githubusercontent.com/27464836/36331741-2eb49b3e-13c3-11e8-9478-0ebbeffff315.png">

<img width="320" alt="image 7" src="https://user-images.githubusercontent.com/27464836/36331754-3a278c56-13c3-11e8-99f5-c960309378a6.png">
