### ISSUE TITLE
Personally verified as functioning well thus far:

### ISSUE THREAD

**Issue by X8716e** [AdguardTeam/AdguardForiOS#643]
2.0.0 (132)
- [x] Update subscriptions
- [x] Clear DNS logs
- [x] UI both easy on the eyes & easy to see
- [x] Safari extentsion - blocking web elements [note for users with javascript turned off - turn it on for this to function.]

**Comment by zznosar** [comment]
I completely agree with @X8716e . The above mentioned works really well. 

The app keeps getting better and better. 

 Well done AdGuard Team.
