### ISSUE TITLE
Report tool leads to Russian version

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardForiOS#644]
The report tool seems to always lead to the Russian version although my device is set to the German language. 

<details><summary>Screenshot:</summary>

![038a9412-0e12-4a3d-b223-2cf7f8a03756](https://user-images.githubusercontent.com/10995998/36043322-3c257116-0dcf-11e8-9320-c36b0c86e7e7.png)

</details>

### Your environment

* Device model and storage size: iPhone X
* Operating system and version: 11.3
* Browser: Safari
* AdGuard Pro 2.0.0 (132)

**Comment by ameshkov** [comment]
@danidoedel ops :)

@IvanIin  @zebrum подстава, нас раскрыли:)
