### ISSUE TITLE
More Details in Quick Tour - Welcome page

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#646]
Can we have more details in the Quick Tour -> Welcome page.

Currently, it just says “AdGuard helps you”. Probably we can say how AdGuard can help?

This is in the current beta 2.0 132.

![img_8008](https://user-images.githubusercontent.com/27464836/36051123-2aa6a1c6-0e3d-11e8-8e14-b02c8bbc76d0.JPG)

**Comment by zebrum** [comment]
Thanks, we will think about adding more information to the welcome page.

**Comment by ameshkov** [comment]
@zebrum we definitely need to resolve that before the public release. This is just a placeholder text right now.

**Comment by ameshkov** [comment]
![](https://img.memecdn.com/internet-guide-8-0_o_293618.jpg)

**Comment by zznosar** [comment]
LOLz! Haha. I don’t mind having that as a welcome page! :-)

**Comment by zznosar** [comment]
this is much better than last time!

<img width="1112" alt="image 3" src="https://user-images.githubusercontent.com/27464836/36559210-64781a96-1861-11e8-98bb-ddd1403ced75.png">
