### ISSUE TITLE
Simplified Chinese translation for "Blacklist" is wrong

### ISSUE THREAD

**Issue by liyiecho** [AdguardTeam/AdguardForiOS#647]
https://github.com/AdguardTeam/AdguardForiOS/blob/80c6aff47a7958be4de64da8c670291f507eb26e/AdguardExtension/AdguardApp/zh-Hans.lproj/Main.strings#L299-L300

The "Blacklist" in Simplified Chinese translation actually means "黑名单" not “白名单”.
It just like the Traditional Chinese version.
https://github.com/AdguardTeam/AdguardForiOS/blob/80c6aff47a7958be4de64da8c670291f507eb26e/AdguardExtension/AdguardApp/zh-Hant.lproj/Main.strings#L299-L300

**Comment by lancelot-moon** [comment]
The link which you gave is a outmoded language file.
It can't represent the now language file.

However, you're right.
That string's translation is wrong until now.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/8ZCn7jX.png)
</details><br/>

As a translator, I can say that the quality of Simplified Chinese translations is not good.
But you can help yourself and others if being a new translator.

**Comment by aalpatkina** [comment]
@liyiecho your translation was approved. Thank you!

**Comment by liyiecho** [comment]
@aalpatkina the "clear" also is wrong. The "clear" in Simplified Chinese translation actually means "清除" not “请求”. The "请求" in English means "request".
<details>
  <summary>Screenshot:</summary>
  ![41c31c64-a851-47a1-bfea-5e4149c1b79b](https://user-images.githubusercontent.com/5213722/36148688-dbfac6b6-10f7-11e8-9d9d-1dc99614760e.png)
</details>

**Comment by aalpatkina** [comment]
@liyiecho corrected. Thanks!
