### ISSUE TITLE
Is "Popular Subscriptions" removed from "New Subscription"? [ v2.0.0(132) ]

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#648]
There is already no "Popular Subscriptions" in the section of "New Subscription" in v2.0.0(132).
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Co58rHX.png)
</details><br/>

Have you remove "Popular Subscriptions" from "New Subscription" because of Apple's policy?
Or just forget?

And some new strings are added in app, but I don't see those new strings on oneskyapp.
Some finished translations also aren't applied in v2.0.0(132).
Several strings which have finished translations are shown in English.
We need to update languages files in the next beta version.

Thanks.

**Comment by zebrum** [comment]
You will find popular subscriptions by tapping the link 'Here' in the description.

**Comment by lancelot-moon** [comment]
@ameshkov 
@zebrum 

Hi, I am sure that you misunderstood my meaning.
I am earlier to report the bug than another one's post.
The under post is a duplication with mine.
However, you closed my early issue, did not close the duplication issue...
https://github.com/AdguardTeam/AdguardForiOS/issues/650

The feature of adding "Popular Subscriptions" disappeared in the section of "New Subscription".
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Eh46ERw.png)
</details><br/>

You really don't understand what I reported!

And then the link of "here" still doesn't lead users to the introduction of subscriptions now as what you replied in my another post.
https://github.com/AdguardTeam/AdguardForiOS/issues/651
