### ISSUE TITLE
Trouble with ecigtalk.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForiOS#65]
"Заметил вот какую странность, при переходе на сайт с помощью закладки на рабочем столе реклама есть и после обновления исчезает (т.е. все по старому, проблема есть). При переходе на сайт с помощью закладки на экспресс панели браузера safari рекламы нет- блокировка работает корректно"

Логи и скрины в JMO-468-97600

**Comment by ameshkov** [comment]
@gshumihin please test this

**Comment by gshumihin** [comment]
Не получается повторить. Что при открытии с рабочего стола, что из закладок. Так же, проверил открытие сайта просто при загрузке сафари (он был в одной из вкладок до закрытия сафари). Фильтрация присутствует, помощник имеется. 
У меня версия сафари 9.0.2
Версия Adguard 1.1.4 beta

**Comment by ameshkov** [comment]
I need a detailed description in english in order to file a bug report to webkit.

**Comment by gshumihin** [comment]
Whenever you open site from main screen ads are missing.
As example you can use this site: ecigtalk.ru

And here are steps to reproduce the issue:
1. Add ecigtalk.ru to main screen:
<img src="http://content.screencast.com/users/shumegor/folders/Jing/media/b39ef6c7-3e4e-4ef6-8c93-0f3a8a19063c/00000950.png" width="150">
2. Close all tabs in safari.
3. Close safari.
4. Open ecigtalk.ru from main screen:
<img src="http://content.screencast.com/users/shumegor/folders/Jing/media/e6fe6276-033c-4259-b865-0f3f0cec8213/00000951.png" width="150">

**Comment by zebrum** [comment]
can not reproduce
