### ISSUE TITLE
The link of [Click “here” to learn more about it.] and [“Here” you can find examples...].

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#651]
In v2.0.0(132), you set a link for “here/Here”.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/RntdZaY.png)

![image](https://i.imgur.com/Co58rHX.png)
</details><br/>

But the following website isn’t related to subscriptions.
https://kb.adguard.com/en/ios/features

I supposed that the link will lead users to the page:
https://github.com/AdguardTeam/AdguardForiOS/issues/545

Or you make a new page which introduces some other good subscriptions on AdGuard official website, such like this:
https://github.com/collinbarrett/FilterLists

v3 (Alpha): https://beta.filterlists.com/
v2 (Stable, Frozen): https://filterlists.com

On that website, there are many filters.
But not every filter can be applied in AdGuard Pro for iOS since it can only filter domains, not support rule syntax.
Maybe AdGuard can introduce some other good filters for domains on a new page, especially about the blocking of Coin Miners and Ransomware on the web.
Ex: NoCoin and so on.
And then the link of “here/Here” will lead users to there.

**Comment by zebrum** [comment]
The first link is correct and leads to knowledge base as i should , it's about #574 - We will rewrite the whole article, add some screenshots, etc. on the next week.


The second one leads to Popular Subscriptions.

**Comment by lancelot-moon** [comment]
Thanks for the answer.
Just wait that you rewrite the whole article there.

**Comment by lancelot-moon** [comment]
https://github.com/collinbarrett/FilterLists
It seems that https://filterlists.com is frozen.

Add the link for your reference:
Many the latest filters.
https://beta.filterlists.com/

Thanks.
