### ISSUE TITLE
How to solve the priority sequence of different rules for the same domain in subscriptions? [ v2.0.0(132) ]

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#654]
@ameshkov
@IvanIin

Ex: app-measurement.com

app-measurement.com is blocked in 1hosts.cf filter.
http://1hosts.cf/
0.0.0.0 app-measurement.com

But app-measurement.com is NOT blocked in AdGuard SDN filter.
https://filters.adtidy.org/extension/chromium/filters/15.txt
! ||app-measurement.com^

Well, we subscribe the 2 filters in subscriptions.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/rxCbj8V.png)
</details><br/>

After several updates, it seems that the sequence of 1hosts.cf filter is higher than other filters.
app-measurement.com was shown "blocked" in the log.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/hZjsdSs.png)
</details><br/>

We deleted AdGuard SDN filter and then just anew added it in subscriptions.
Re-start to enable the fake VPN.
app-measurement.com was NOT shown "blocked" in the log.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/sWwy05N.png)
</details><br/>

Finally, we clicked "Check for updates" at this time.
After checking, app-measurement.com was again shown "blocked" in the log.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/nppEJbU.png)
</details><br/>

May Ivanlin tell us how it works?

Should we not block app-measurement.com since ! ||app-measurement.com^ is in one of subscriptions?
**I mean:**
**Should we maybe give the higher priority sequence to ! ||example.com^ and @@||example.com^ in a filter even if example.com is blocked in other filters?**

How to solve the priority sequence of different rules for the same domain in subscriptions?

Thanks.

**Comment by ameshkov** [comment]
`! ||example.com^ ` -- this is just a comment, means nothing.
`@@||example.org` -- this is an exception rule, it has the highest priority and does not let any other subscription block that domain
