### ISSUE TITLE
Change color of 'Clear Selected' and 'Cancel' buttons in edit mode (filters list)

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForiOS#658]
AdGuard v2.0
<details>

![image uploaded from ios 1](https://user-images.githubusercontent.com/23637588/36258028-46a4b58a-126a-11e8-850b-c188f01e357f.jpg)

</details>

**Comment by zznosar** [comment]
Tested. Fixed in beta 136.

<img width="1112" alt="image 3" src="https://user-images.githubusercontent.com/27464836/36330129-980f47e8-13bc-11e8-815c-0ffd1a6b6f9c.png">
