### ISSUE TITLE
[Feature Request] Bring Back Day Mode + Night Mode Option + Auto Night Mode Option

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#659]
Currently the AdGuard 2.0 is all night mode. It is difficult to see. 

Can you make it by default is Day Mode (White) and add the option called Night Mode. Those who love the night mode can turn on that option. If you on the Night Mode, there is another option called Auto Night Mode. Meaning when Day it will turn white and when night it will turn black like Chamelon

**Comment by worldsdream** [comment]
Yup. I need this too. I guess that would fit everyone needs. 

You can also make an option. Two finger swip up is day mode (white). Two finger swipe down is night mode (dark). Another application got this functionality and it rocks!

**Comment by zzebrum** [comment]
we can consider this feature request done I suppose.
