### ISSUE TITLE
Wrong English strings are back on oneskyapp.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#660]
@ameshkov
@aalpatkina

Wrong English strings are again back on oneskyapp.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/boItTfR.png)
</details><br/>

AdGuard -> Adguard

right: [ This is used in beta v2.0.0(132). Well, **it's Adguard in the strings.** We need to modify it. ]
Adguard Pro works in two different modes. In the Split-Tunnel mode Adguard is compatible with so-called "Personal VPN" apps (full list <a href="https://github.com/AdguardTeam/AdguardForiOS/issues/162">here</a>). As a trade-off, in this mode AdGuard may be bypassed by system in case of bad connectivity. On the contrary, in the Full-Tunnel mode AdGuard can't be run along any other VPN apps, but also can't be bypassed regardless of the connection quality.

outmoded:
Adguard Pro works in two different modes. In the Split-Tunnel mode Adguard is compatible with so-called "Personal VPN" apps (full list: <a href="https://github.com/AdguardTeam/AdguardForiOS/issues/162">https://github.com/AdguardTeam/AdguardForiOS/issues/162</a>). As a trade-off, in this mode Adguard may be bypassed by system in case of bad connectivity. On the contrary, in the Full-Tunnel mode Adguard can't be run along any other VPN apps, but also can't be bypassed regardless of the connection quality.

Lack "?" in the string.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/8HIwQtq.png)
</details><br/>

They're "connected" and "IPv6".
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/LZUnkbN.png)
</details><br/>

Oh my God, many mistakes.
**You need to anew check for all strings.**

You should think a method to solve it.....
Otherwise, Adguard is instead of AdGuard.
And then wrong strings and outmoded strings will always be back and be instead of those modified correct strings...

And we translators waste our time on always clicking buttons for cancelling the exclamation marks (!) on oneskyapp for many times because of Adguard, wrong strings or outmoded strings if translators are perfectionist...
I really don't like those exclamation marks (!) on oneskyapp if it's not because the strings are correctly updated, which is annoying. (☍﹏⁰。)

◢▆▅▄▃崩╰(〒皿〒)╯潰▃▄▅

**Comment by lancelot-moon** [comment]
Adguard for iOS Strings
Again AdGuard -> Adgaurd.

Yes, I'm also lazy to report this.
I won't remind anymore.
Sorry to bother you.
Originally, it's translation team's work.

Since I constantly suffered from Sailor-Chibimoon's harassment, no AdGuard administrator forbade him commenting on AdGuard GitHub.
I must reported abuse to GitHub by myself.
I'm disappointed at AdGuard team.

Maybe the native English speaking users will often see Adgaurd, wrong words or outmoded strings.
Good luck.

**Comment by ameshkov** [comment]
@IvanIin WTF

**Comment by ameshkov** [comment]
@lancelot-moon I'm sorry for that, we've discussed it multiple times with @IvanIin, and still, we're making the same stupid mistake while updating strings in Oneskyapp. We'll now sort it out once and for all now.

Regarding the trolling issue, I'll keep an eye on that.

**Comment by lancelot-moon** [comment]
I only take some screenshots, and I'm lazy to check all strings.
**Translation team check all strings by themselves.**

It's easy to modify Adguard to AdGuard.
But it's trouble to find those outmoded strings.
The outmoded strings are often instead of the latest strings.

I start to believe that my Traditional Chinese translations are much better than the English strings.

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/fXFRqFP.png)
</details><br/>

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/cgyQjUv.png)
</details><br/>

**Comment by ameshkov** [comment]
First of all, let me explain the source of confusion.

There're TWO english languages there.

The first one -- `EN-US-POSIX` -- is not supposed to be used as a base language. It actually contains strings **identifiers** and not the actual strings. Also, it must not be edited by any translator/reviewer.
The second one -- `EN` -- is the proper english that should've been used as a base language.

Unfortunately, we messed it up somewhere and everyone was using `EN-US-POSIX` as a base language.

**Comment by lancelot-moon** [comment]
For example:
The latest strings:
AdGuard Pro works in two different modes. In the Split-Tunnel mode AdGuard is compatible with so-called "Personal VPN" apps (full list <a href="https://github.com/AdguardTeam/AdguardForiOS/issues/162">here</a>). As a trade-off, in this mode AdGuard may be bypassed by system in case of bad connectivity. On the contrary, in the Full-Tunnel mode AdGuard can't be run along any other VPN apps, but also can't be bypassed regardless of the connection quality.

Now, the above latest strings were instead by the under outmoded strings.
Your translation team only modified Adguard to AdGuard.
They don't know these are outmoded strings.
The outmoded strings:
Adguard Pro works in two different modes. In the Split-Tunnel mode Adguard is compatible with so-called "Personal VPN" apps (full list: <a href="https://github.com/AdguardTeam/AdguardForiOS/issues/162">https://github.com/AdguardTeam/AdguardForiOS/issues/162</a>). As a trade-off, in this mode Adguard may be bypassed by system in case of bad connectivity. On the contrary, in the Full-Tunnel mode Adguard can't be run along any other VPN apps, but also can't be bypassed regardless of the connection quality.

**Comment by ameshkov** [comment]
Again, trying to modify `EN-US-POSIX` strings in oneskyapp was a mistake. We should've modified `EN` instead.

So when translating you should choose `EN` on the left side:
https://adguard.oneskyapp.com/collaboration/translate/project/project/44557/language-from/1/language/2/#/

**Comment by ameshkov** [comment]
So, what we need to do now:
1. @aalpatkina please update the `EN-US-POSIX` --> `EN` translation
2. @aalpatkina please update the oneskyapp projects description so that this scheme was clear to translators
3. @IvanIin get the latest strings from oneskyapp.

@aalpatkina @IvanIin let me know when it's done.

After v2.0 we need to simplify this scheme: https://github.com/AdguardTeam/AdguardForiOS/issues/666

**Comment by lancelot-moon** [comment]
Ever the 2 strings were modified to the under strings:
A.
AdGuard Pro provides you with advanced capabilities via **the use of** custom DNS servers. Parental control, protection from phishing and malware, protecting your DNS traffic from intercepting and snooping.

B.
AdGuard Pro works in two different modes. In the Split-Tunnel mode AdGuard is compatible with so-called "Personal VPN" apps (full list <a href="https://github.com/AdguardTeam/AdguardForiOS/issues/162">here</a>). As a trade-off, in this mode AdGuard may be bypassed by system in case of bad connectivity. On the contrary, in the Full-Tunnel mode AdGuard can't be run along any other VPN apps, but also can't be bypassed regardless of the connection quality.

Due to the mess,  those strings were back / modified to the original strings.
a.
AdGuard Pro provides you with advanced capabilities via using custom DNS servers. Parental control, protection from phishing and malware, protecting your DNS traffic from intercepting and snooping.

b.
AdGuard Pro works in two different modes. In the Split-Tunnel mode AdGuard is compatible with so-called "Personal VPN" apps (full list: <a href="https://github.com/AdguardTeam/AdguardForiOS/issues/162">https://github.com/AdguardTeam/AdguardForiOS/issues/162</a>). As a trade-off, in this mode AdGuard may be bypassed by system in case of bad connectivity. On the contrary, in the Full-Tunnel mode AdGuard can't be run along any other VPN apps, but also can't be bypassed regardless of the connection quality.

Which are the latest strings?
In beta v2.0.0(137), I use the Traditional Chinese translations of A and B.

For those new strings, Traditional Chinese translations are 100% done.
Please don't forget to apply the Safari filters' Traditional Chinese translations because they're still not applied in beta v2.0.0.

Thanks...

**Comment by ameshkov** [comment]
@lancelot-moon 

> Due to the mess, those strings were back / modified to the original strings.

**Comment by ameshkov** [comment]
Some of the strings must've been automatically deprecated by Oneskyapp but they weren't, need a mnaualy review

**Comment by ameshkov** [comment]
> AdGuard Pro provides you with advanced

Deprecated now.

> AdGuard Pro works in two different modes

As I've said, look at `EN`, **not `EN-US-POSIX`**

**Comment by lancelot-moon** [comment]
I had looked at EN.
Simply, when I translated, those 2 strings were still not modified at that time.
Only I am careful of the strings on oneskyapp.
I know the things, but other translators don't know it.
Translation team should send a notification email to translators.

Now,
A:
The string was deleted on oneskyapp.

B: I just found that you use a new strings.
AdGuard Pro works in two different modes. In the Split-Tunnel mode AdGuard is compatible with so-called "Personal VPN" apps (<a href="https://github.com/AdguardTeam/AdguardForiOS/issues/162">full list</a>). As a trade-off, in this mode AdGuard may be bypassed by system in case of bad connectivity. On the contrary, in the Full-Tunnel mode AdGuard can't be run along any other VPN apps, but also can't be bypassed regardless of the connection quality.

Even so, there are still a few wrong words in strings of "EN".
Adguard for iOS IB Strings:
grammar: results in + n
The 2 strange English...
This switch lets you choose between filtering the website and excluding it from filtering. Adding a website to exceptions results in **AdGuard** ignoring the website and displaying all ads.

This switch lets you choose between filtering the website and excluding it from filtering. Adding a website to exceptions results in **AdGuard's** ignoring the website and displaying all ads.

Maybe:
**This switch lets you choose between filtering the website and excluding it from filtering. Adding a website to exceptions leads AdGuard to ignore the website and display all ads.**

Adguard for iOS Strings:
connected, IPv6
You are **connecteed** to the **ipv6**-only network. In such networks you can not use custom DNS servers. The 'System default' DNS setting will be used instead.

AdGuard
Loading filters to Safari. Please do not turn off **Adguard**, the process will take no more than 30 seconds...
