### ISSUE TITLE
Resolve the mess with oneskyapp

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#666]
Let's do it after v2.0 release.

1. We need to get rid of two different english languages there (`EN-US-POSIX` and `EN`). Keep a single `EN-US-POSIX` as a base language. The drawback is that every time we update the english text on the oneskyapp side, it will lead to creating a new string identifier. I guess we can find peace with it.

2. Get rid of numerous subprojects. Merge Strings and IB Strings into a single project.

**Comment by lancelot-moon** [comment]
It seems that there is trouble when choosing "EN".
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/EpbwxBi.png)
</details><br/>

Why do you not delete "EN-US-POSIX" from oneskyapp of AG (Pro) for iOS?

**Comment by lancelot-moon** [comment]
Adguard for iOS iPhone/iPad App
This string is for "EN-US-POSIX", not for "EN".
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/zTqnW0R.png)
</details><br/>

**Comment by IvanIin** [comment]
@lancelot-moon 

> That string is for "EN-US-POSIX", not for "EN"

Thank you. I fixed it.
