### ISSUE TITLE
Update the app translations

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#667]
Guys, let's update translations in the beginning of the next week.

**Comment by lancelot-moon** [comment]
1. Please update the title and description of free AdGuard & AdGuard Pro on iTunes App Store.
2. Please don't forget to apply Traditional Chinese translations for Safari filters because they're still not applied in beta v2.0.0.

**Comment by lancelot-moon** [comment]
@aalpatkina 

Adguard for iOS iTunes App Store (PRO) on oneskyapp:
Adguard -> AdGuard
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/z1uo2uJ.png)
</details><br/>

On oneskyapp, I just found that you use new descriptions for AdGuard Pro on iTunes App Store.
I have updated those new descriptions' Traditional Chinese translations for AdGuard Pro this midnight.

Free Adguard for iOS iTunes App Store on oneskyapp:
The now string on oneskyapp is an outmoded title for Free AdGuard for iOS.
Actually, you use "AdGuard - adblock&privacy" on iTunes App Store.
So I also fill in "AdGuard - adblock&privacy" there.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/Eolj3jK.png)
</details><br/>

I also updated the descriptions' Traditional Chinese translations for Free AdGuard somewhere.

Please check that you use the latest Traditional Chinese translations for Free AdGuard & AdGuard Pro on Taiwan iTunes App Store.

Thanks a lot!

**Comment by sergerosenthaler** [comment]
German AppStore translation for AdGuard and AdGuard Pro needs to be updated too.

**Comment by ameshkov** [comment]
@aalpatkina don't forget to add a size limit for the app name in oneskyapp

**Comment by sergerosenthaler** [comment]
@ameshkov AppStore titels and descriptions for the regular and Pro versions are up to date, check oneskapp and let me know.

**Comment by ameshkov** [comment]
Thank you!

**Comment by lancelot-moon** [comment]
I just check the Traditional Chinese translations on iTunes App Store via a browser.

You didn't use the latest Traditional Chinese translations.

Often you delayed new strings on oneskyapp, but you soon apply new English strings but outmoded translations on itunes app store or in apps...
