### ISSUE TITLE
2.0 Still can't update filters while DNS/VPN is turned on

### ISSUE THREAD

**Issue by gh0sti** [AdguardTeam/AdguardForiOS#668]
### Steps to reproduce
1. Turn on the DNS/VPN in the app
2. Update filters
3. Fails to update filters
4. profit as in of course it doesn't work

### Expected behavior
should update filters

### Actual behavior
does not update filters

### Your environment

* iPhone X
* iOS 11.3 b3
* Safari
* both Wi-fi/mobile internet connection

**Comment by ameshkov** [comment]
> Fails to update filters

How does it look like?

> Turn on the DNS/VPN in the app

What exact DNS have you chosen?

**Comment by zznosar** [comment]
If it helps, i don’t encounter this issue in iPad Pro and not anymore in iPod Touch. I am using beta 2.0 138 with stable ios 11.2.6 via AdGuard’s Encrypted DNS.

There is an ios bug in ios 11.3 beta 3 that the AdGuard team is checking with Apple and other testers. Probably this is somehow related to that?

**Comment by zebrum** [comment]
@gh0sti any updates? can you collect logs for us?

**Comment by X8716e** [comment]
@gh0sti - try whitelisting, e.g. `raw.githubusercontent.com` if you’re pulling updates via GitHub. Basically, whitelist those domains from which your filter updates are being pulled.

**Comment by ameshkov** [comment]
Reopen if it happens again plz
