### ISSUE TITLE
AdGuard Pro 2.0.0(138) German localization and widget name

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardForiOS#669]
In the latest build there is an untranslated section and a too long German translation (this has been corrected on OneSky)
![img_3496](https://user-images.githubusercontent.com/25068100/36583276-480d3436-1875-11e8-8798-2343c2f55ba4.jpg)

When you activate the AdGuard Widget there is still the old name Adguard present, instead of AdGuard.
![img_3497](https://user-images.githubusercontent.com/25068100/36583336-9280da54-1875-11e8-8c6d-a18ae8374180.jpg)

**Comment by zznosar** [comment]
Widget is fixed in beta 140.

<img width="320" alt="image 4" src="https://user-images.githubusercontent.com/27464836/36754790-2dc2d684-1c5e-11e8-83d2-f247dfb47dde.png">
