### ISSUE TITLE
Please change the arrangement of tutorial videos from vertical stack to overlapping on the main screen.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#671]
Now, the arrangement of tutorial videos is vertical stack on the main screen in beta v2.0.0(138).
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/2NgkhVI.jpg)
</details><br/>

Please change the arrangement of tutorial videos to overlapping on the main screen.
Maybe use 1st type.
Or only use 2nd type.
Or only use 3rd type.
Or use 1st and 3rd types together.
Or use 2nd and 3rd types together.
You decide it.
So the feature, "**hide video**", for tutorial videos is maybe unnecessary.
( I hid one of the tutorial videos on the main screen.
There is no method to recover it, which lets me feel sad. (☍﹏⁰。) )

Swipe slide:
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/j3IV8AR.jpg)

![image](https://i.imgur.com/ewl8cE8.jpg)
</details><br/>

I can't understand why AdGuard team so like "vertical stack" in the design, which results in very long screen.
(Well, "vertical stack" is easier to designers.)
As a user, I suppose that I need to constantly scroll down until the end of time. Σ(ﾟДﾟ；≡；ﾟдﾟ)
( Sorry for the cold joke. (≧∀≦)ゞ )
Ex: The so~ so~ so long screen of DNS setting....

I ever suggested to use a pop-up or next screen for the selection of DNS servers in DNS setting.
https://github.com/AdguardTeam/AdguardForiOS/issues/591

Another user wishes to hide unnecessary DNS servers.
https://github.com/AdguardTeam/AdguardForiOS/issues/623

Why???
The screen of app is too long!
Such style, "vertical stack", is always used in the mobile version of AdGuard, Android and iOS version.
But mobile devices have smaller screen.
**Do AdGuard team have no sense to the so long screen of app?**

Maybe you can try to break the old-fashioned thought and change the style in the design of app's interface/layout.
Tapping for the selection from a pop-up/next screen or swiping slide is better.
Succinct style on the main screen is intuitive and comfortable.
Succinct, intuitive and comfortable interface, which is why people love Apple.

B/R

**Comment by zebrum** [comment]
You don't need to have tutorial videos always at the top of the screen. You watch both videos after you've install the program, after that you can swipe them. If you will need to watch them again - videos will appear in About section.

**Comment by lancelot-moon** [comment]
Sir,

I was talking about aesthetics of app's interface on the main screen.

Aesthetics is also important, which is my point.

**Comment by zebrum** [comment]
> Did team never think so long screen is not succinct, intuitive and comfortable?

That's why you can swype videos away.

**Comment by lancelot-moon** [comment]
In DNS setting, there is no tutorial video.
It’s so long.

Stack of tutorial videos or no tutorial video will make AdGuard Pro’s main screen lose aesthetics.
Swiping videos away is not my point.

If 1 video on main screen gives prettier feeling, overlapping videos is the best solution.
Also, swiping slide can let users see 2 videos.

Hiding videos is bad because there is no method to let it recover.

Don’t say that videos are still in “About”, which is not important.
You don’t understand that I am talking about aesthetics.

**Comment by worldsdream** [comment]
I did not know that I could swipe the videos away. I swiped and I did hide them. Would be nice to show a tooltip that you can hide it? Because not everyone clicks the video in the top.
