### ISSUE TITLE
Automatically jump a pop-up to notify users about the thing along with clearing DNS Requests Log when the log file achieves certain big size.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#672]
It seems that you decide to remove the switch for DNS Requests Log forever, right?

I believe that there are users who never or rarely use DNS Requests Log.
However, DNS Requests Log is enabled by default, which maybe lets DNS Requests Log accumulate a lot of data if users don't notice it.
So please automatically jump a pop-up to notify users about the thing along with clearing DNS Requests Log when the log file achieves certain big size or occupies too much resource of RAM.

I got the answer here.
https://github.com/AdguardTeam/AdguardForAndroid/issues/1734#issuecomment-368560757

If AdGuard Pro for iOS is the same with AdGuard for Android (this log only keeps the record of the last 500 requests), please close the issue.

Thanks.

**Comment by zebrum** [comment]
AdGuard for iOS keeps logs 12 hours

**Comment by lancelot-moon** [comment]
Oh, different with filtering log of AdGuard for Android.

How about also setting the limit numbers for DNS Requests Log?

Need to think about a method for avoiding the much occupation of RAM’s resource.

**Comment by ameshkov** [comment]
> How about also setting the limit numbers for DNS Requests Log?

Yes, that's a good idea.
