### ISSUE TITLE
Please fix AdGuard Assistant to Traditional Chinese translations in AdGuard (Pro) for iOS.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#673]
@ameshkov 
@aalpatkina 

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ntpjzL9.png)
</details><br/>

They're Simplified Chinese translations, not Traditional Chinese translations.
**Please never use Simplified Chinese translations in AdGuard's Traditional Chinese language files for Taiwanese.
Taiwanese use Traditional Chinese but don't use Simplified Chinese.
If there is no Traditional Chinese translation, simply using English is still better than using Simplified Chinese translations.**

I ever reported about this in AdguardTeam/AdguardAssistant.
Obviously, you ignore that Simplified Chinese translations are still wrongly used in AdGuard (Pro) for iOS for Taiwanese.
https://github.com/AdguardTeam/AdguardAssistant/issues/169

May you also check the language interface of AdGuard Assistant for Windows and Mac?

And then I noticed that Filters for Safari already became English in AG Pro beta v2.0.0(140).
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/CBCbztx.png)

![image](https://i.imgur.com/EToilfm.png)
</details><br/>

I guess that you're preparing to apply my Traditional Chinese translations for Safari's Filters .
Thanks for the hard working!

B/R

**Comment by aalpatkina** [comment]
@lancelot-moon 
We do apologize. It's our mistake. We will try to fix it today/tomorrow and, of course, we'll also check the interface language for Windows and Mac. 

And about translations for filters: I know that you've completed translations and checked all updated phrases in "Miscellaneous" project. Thank you for that. We'll update filters translations very soon. Please do not worry :)
