### ISSUE TITLE
Persistent VPN connection issue (Full-Tunnel mode).

### ISSUE THREAD

**Issue by jau88** [AdguardTeam/AdguardForiOS#674]
When WiFi is disabled and Airplane Mode is on, the AdGuard VPN connection remains using Full-tunnel, I reproduced the steps below with _**Split-Tunnel and the error did not occur**_.

### Steps to reproduce
1. Enable AdGuard Pro DNS (with Full-tunnel)
2. Disable WiFi in the settings app
3. Enable Airplane Mode in the settings app
4. Notice the WiFi remains on due to DNS remaining connected.

### Expected behavior
WiFi/DNS connection should completely disconnect

### Actual behavior
WiFi signal remains, DNS remains on, Airplane Mode has no effect, the operating system and apps like Safari still try to connect to the network but result in timeouts. The issue is caused by the Full-Tunnel Mode override.

### Screenshots

[WiFi off> Settings View](https://user-images.githubusercontent.com/7542509/36828721-aaa96250-1d6f-11e8-87f0-135bb625cbc1.jpeg)

[WiFi off > VPN View](https://user-images.githubusercontent.com/7542509/36828722-aaee980c-1d6f-11e8-91ed-9c0f250f544c.jpeg)

•••

[WiFi off + Airplane Mode > Settings View](https://user-images.githubusercontent.com/7542509/36828725-ab6add2c-1d6f-11e8-9fb7-071bf5fecf9c.jpeg)

[WiFi off + Airplane Mode > VPN View](https://user-images.githubusercontent.com/7542509/36828724-ab29ceb8-1d6f-11e8-9b73-603f18a2d519.jpeg)

[WiFi off + Airplane Mode > Safari attempting to connect](https://user-images.githubusercontent.com/7542509/36828726-aba76d00-1d6f-11e8-8246-602bf505292d.jpeg)

[WiFi off + Airplane Mode > AdGuard View](https://user-images.githubusercontent.com/7542509/36830013-d57629d6-1d75-11e8-9b17-d88f328520d5.png)

### Bug Report
   **User ID**: 1775482
   **Subject**: [AdGuard Pro for iOS] Bug Report

### Environment
* iPhone 7+ 128gb
* iOS 11.1.2
* Adguard Pro 2.0.0(140)
* Home Wi-fi, no other VPNs/Proxies used.

**Comment by lancelot-moon** [comment]
Yes, I also found this before and originally I'll prepare to report about this after work. XD
With Split-tunnel VPN, VPN icon will disappear while disabling Wi-Fi.
However, with Full-tunnel VPN, VPN in setting still be on while disabling Wi-Fi.

**Comment by zznosar** [comment]
I have tried this in the current stable version 1.3.1 and it can be replicated, so I think this is not v2.0 exclusive.

Funny thing is i have another app called DNSCloak, and the behavior is the same. 

AdGuard Team can give details why.. probably it’s an expected behavior or an iOS bug?

**Comment by X8716e** [comment]
@zznosar @lancelot-moon @jau88 -

It’s a feature of full tunnel mode: staying connected during low-connectivity, in which no-connectivity is included. It does eventually disconnect. I actually find it quite useful for faster reconnects.

**Comment by zznosar** [comment]
@X8716e , I see. Thanks for the info. Yes. It make sense.
