### ISSUE TITLE
English filter alone uses up more rules than the 50000 Safari allows

### ISSUE THREAD

**Issue by chaNcharge** [AdguardTeam/AdguardForiOS#675]
### Expected behavior
The English filter rules were normally and should be below 50000

### Actual behavior
It's way above it, even just by itself

Screenshot:
![img_4703](https://user-images.githubusercontent.com/11594018/36887831-c31d0408-1da7-11e8-88ea-c43d031704a6.PNG)

### Your environment

* iPhone 6 Plus 64 GB
* iOS 11.2.6
* Safari
* Wi-Fi

**Comment by ameshkov** [comment]
Yeah, there was an issue with rules optimization yesterday, it is now resolved, please check filters updates

**Comment by LaxusiC** [comment]
Is there a way to bypass 50k limit? My device is jailbroken btw

**Comment by ameshkov** [comment]
No, it seems to be hardcoded in Safari.

**Comment by ameshkov** [comment]
Resolved, plz check filters updates.

Meanwhile, we'll change the compiler code to ensure that this never happens again.
