### ISSUE TITLE
AdGuard Pro 2.0.0 (140) Warning message „More than 50‘000 rules active“ remains

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardForiOS#676]
### Steps to reproduce

1. Click on Check for filter updates
2. Warning message „over 50’000 rules active...“ appears
3. Disabel a few filters
4. Check again for updates, warning message remains
5. Close and open the App
6. Check again for updates
7. Warning message remains
8. Force quit the App and restart it
9. warning message has disappeared 

### Expected behavior
Warning message should disappear automatically as soon as there are no longer more than 50‘000 rules active.

### Actual behavior
As soon as the warning message „More than 50‘000 rules active appears, it remains.

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Device model and storage size: (e.g. iPhone 6s 64gb)
* Operating system and version: (e.g. 10.3.1)
* Browser (e.g. Safari)
* Wi-fi or mobile internet connection

**Comment by zznosar** [comment]
This is also happening in 1.3.3 and not exclusive to 2.0. You don't need to force restart the app. Click Check for Updates, Go the to the Filter Selection (the database will refresh) then back to the main screen. The warning will disappear.

**Comment by IvanIin** [comment]
@sergerosenthaler @zznosar 
I can not reproduce this issue. Please check if it reproduces on the latest beta.

**Comment by zebrum** [comment]
reopen if needed
