### ISSUE TITLE
How can real VPN with its own adblock feature let yahoo sponsored ads disappear since only DNS filtering is available on iOS devices?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#678]
1. Well, I want to use chrome.
But chrome doesn’t have a content blocker.
So AdGuard Pro is unable to hide yahoo sponsored ads on chrome.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/7dkfVCj.png)
</details><br/>

Afterwards, I tried real VPN with its own adblock feature, and then yahoo sponsored ads on chrome were disappeared without a content blocker.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/pVOAJfH.png)
</details><br/>

Why?
Does it do HTTPS filtering on real VPN servers for iOS devices?

Is it possible that AdGuard sets up not only DNS servers but also HTTPS filtering servers?

Sorry for my fantasy.
I'm really curious why real VPN servers can do more powerful adblocking for iOS devices.

2. What kind of ad is yahoo sponsored ad?
Is it a HTTPS ad or an element?
DNS filtering is unable to block it.
Generally, we use rule syntax in a content blocker for hiding elements on pages.

Thanks.

**Comment by gslb86** [comment]
You can use brave browser. It built in adblock and HTTPS Everywhere

**Comment by lancelot-moon** [comment]
Hi,

Thanks for your reply!
But you don't understand my requirement.
I early knew it.
I can simply use Safari with AdGuard Pro Content Blocker.
Don't need brave browser app.

But what I **intentionally** talk about is browser apps **without content blocker**.
Browser apps with content blocker is not my topic.

**I just want to discuss real VPN with its own adblock feature with AdGuard team.**

I purchased some real VPN service which provide adblock feature.
Even one of the VPN provider gives the blacklist and whitelist which only support domains for the configuration of adblock for servers and do not support adblock rule syntax.
It seems that it maybe only does DNS filtering, too.

As what we generally know, yahoo sponsored ads are blocked by filter's advanced rule syntax.
So AdGuard Pro with DNS filtering is useless for browser apps without content blocker.
But the real VPN with its own adblock feature can block yahoo sponsored ads for browser apps without content blocker, even AdGuard Pro with DNS filtering is unable to do this.
Why?
I think AdGuard team are specialists in this field.
So I request the answers.
Can we block HTTPS ads for iOS devices through the help of external servers with HTTPS filtering?
As long as the OS of external servers isn't iOS (Unix, Linux even Windows server?), it should support HTTPS filtering...
Will it not show HTTPS ads on iOS devices according to my thought, right?

**Comment by ameshkov** [comment]
> Does it do HTTPS filtering on real VPN servers for iOS devices?

Check the yahoo certificate. I doubt it, though.

**Comment by lancelot-moon** [comment]
The only thing which I know is:
Local VPN on iOS is unable to block yahoo sponsored ads due to only DNS filtering.
But external real VPN (Unix servers?) with its own adblock feature can block yahoo sponsored ads.

What's the rule syntax for blocking yahoo sponsored ads?
May you tell me?

Thanks.

**Comment by ameshkov** [comment]
Click on a green lock icon and check what certificate is there.

I've examined `tw.mobi.yahoo.com` and it seems that the only way to hide sponsored ads is to apply cosmetic filtering, e.g. decrypt https. It's interesting if they're really doing it.

**Comment by lancelot-moon** [comment]
Real VPN with adblock feature:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/qdOh9r7.png)
</details><br/>

No VPN:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/2YgDHff.png)
</details><br/>

The certificates are the same.
So the filtering is directly done on server, right?

**Comment by etsintzas** [comment]
Most probably, Yahoo does not serve sponsored ads to the VPN server location/IP.

**Comment by ameshkov** [comment]
That's the only idea I have so far

**Comment by lancelot-moon** [comment]
Yes, you got it!

I disabled its adblock feature.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/NCrZuEy.png)
</details><br/>

Enable the real VPN and visit yahoo with Chrome.
Well, a pop-up.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ohTqt3z.jpg)
</details><br/>

But it seems that yahoo sponsored ads are not served to the VPN server.
There is no yahoo sponsored ad.
Why?
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/tGvlwzA.png)
</details><br/>

**Comment by ameshkov** [comment]
> Why?

Check the VPN server location:
https://www.whatismyip.com/my-ip-information/

**Comment by lancelot-moon** [comment]
I found interest things.
1. I disabled real VPN's adblock and connected to a foreign server.
ex: USA server
a. I use chrome for visiting yahoo news in Taiwan. No yahoo sponsored ad.
b. I use chrome for visiting yahoo news in USA. Yahoo sponsored ad appeared.

2. I enabled real VPN's adblock and connected to a foreign server.
ex: USA server
a. I use chrome for visiting yahoo news in Taiwan. No yahoo sponsored ad.
b. I use chrome for visiting yahoo news in USA. No yahoo sponsored ad.

So can we sure that real VPN service with its own adblock do HTTPS filtering?

**Comment by ameshkov** [comment]
> So can we sure that real VPN service with its own adblock do HTTPS filtering?

Yep, i am 100% sure there's no https filtering

**Comment by lancelot-moon** [comment]
Yahoo served sponsored ads to real VPN server when visiting yahoo whose location is the same country with the real VPN server.
How does real VPN service with its own adblock hide yahoo sponsored ads without content blocker or HTTPS filtering?
