### ISSUE TITLE
AdGuard filter descriptions not translated to German 2.0.0

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardForiOS#683]
![img_0083](https://user-images.githubusercontent.com/25068100/37024504-571e6ca8-2129-11e8-8195-889c58465b15.png)

**Comment by ameshkov** [comment]
You're just in time, we'll be able to push it to the todays hotfix

**Comment by ameshkov** [comment]
@IvanIin check the filters translations plz:
https://github.com/AdguardTeam/FiltersRegistry/blob/gh-pages/ios/filters_i18n.json

**Comment by sergerosenthaler** [comment]
And there seems to be another translation bug in the blocking list section. Shouldn't this be called "AdGuard DNS-Filter" and not "AdGuard SDN-Filter"?

![img_3507](https://user-images.githubusercontent.com/25068100/37037885-9b30a562-2153-11e8-93a0-983d967ef40d.jpg)

**Comment by ameshkov** [comment]
SDN == Simplified Domain Names :)

**Comment by sergerosenthaler** [comment]
@ameshkov my fault, sorry *.*

**Comment by sergerosenthaler** [comment]
@IvanIin I have made some translation corrections on OneSky this morning. Please check.
