### ISSUE TITLE
[Question] Does DNS log affect performance?

### ISSUE THREAD

**Issue by wzxu** [AdguardTeam/AdguardForiOS#687]
It got me thinking because AdBlock by FutureMind offers an option to turn off logging when not used. Seeing that Adguard goes even further by showing how many requests are possibly trackers and response time, in addition to all the details of DNS requests, I want to ask does keeping the log affect blocking performance, or even system performance in any way?

If so, could you provide an option to let users turn on/off logging on demand?

**Comment by zebrum** [comment]
Hi @wzxu. 
This is a dup of #589
