### ISSUE TITLE
Handle T-Mobile and Deutsche Telekom cases properly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#688]
T-Mobile relies on their own custom DNS server in order to provide connectivity with IPv4 servers over their IPv6-only network.

Domain names are resolved to some private IPv6 addresses which are then re-routed to the real IPv4 addresses (invisibly for the user).

The problem with that is that you simply cannot use a custom DNS server in that case. At least we need to warn T-Mobile users about that.

**We need help from T-Mobile users who have this issue**

**Comment by akmLaVx** [comment]
We've got something that looks like the same but is related to Japanese carrier DOCOMO.
Logs and all related information available under 543636.
