### ISSUE TITLE
Possible bug in iOS

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#69]
Steps to reproduce:
1. Register a content blocker with one rule (for example blocking google.com).
2. Enable content blocker in safari settings and check that rule is working
3. Disable content blocker in safari settings (and check that it is really disabled)
4. Register an updated version of this content blocker (add one more rule for blocking apple.com now).
5. Enable content blocker
6. Check if the rule from step 4 is working

@gshumihin please post the result here.

Source:
http://forums.macrumors.com/threads/ios-9-content-blockers-mini-reviews.1918483/page-20#post-22498999

**Comment by gshumihin** [comment]
Both rules from step 1 and 4 are working.

**Comment by ameshkov** [comment]
Closing the issue then.
