### ISSUE TITLE
Please change the mechanisms of "auto updates" and the feature & description of "Auto Update over Wi-Fi only".

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#690]
@ameshkov 

In the past, I worried about Apple's policy, so I didn't talk about auto updates.
Since I read the issue, https://github.com/AdguardTeam/AdguardForiOS/issues/682...

**Besides this issue, you need to together do the change from another issue in the same next version**, https://github.com/AdguardTeam/AdguardForiOS/issues/663.

a. May you change the mechanism of auto updates?
Please design AdGuard Pro to automatically update Safari filters & Privacy Settings' subscriptions in the background via cellular network / Wi-Fi by default.

b. Also, need to modify the mechanism of "Auto Update over Wi-Fi only".
Please let it be my 1st point in another article.
https://github.com/AdguardTeam/AdguardForiOS/issues/689#issue-302812255

Making the purpose of "Auto Update over Wi-Fi only" is for those who want to **save the data usage of cellular network**.
**After enabling "Auto Update over Wi-Fi only", automatically updating by AdGuard app itself or manually updating via cellular network is not allowed.**

Please change the description for "Auto Update over Wi-Fi only".
Original: "If this setting is enabled, AdGuard will only use WiFi for background filter updates." <- It's "Wi-Fi", not "WiFi". Please fix it on oneskyapp.
New: "**If this setting is enabled, AdGuard will only use Wi-Fi for the auto updates of Safari filters & Privacy Settings' subscriptions in the background, and then automatically or manually updating them via cellular network is not allowed.**"
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/KEzTw9b.png)
</details><br/>

c. We maybe also need to notify users to disable the setting (a pop-up) if they forget enabling "Auto Update over Wi-Fi only" in the past and want to now manually update Safari filters or Privacy Settings' subscriptions via cellular network.

The pop-up of notification:
"**If you want to manually check for updates for Safari filters or Privacy Settings' subscriptions via cellular network, you need to disable "Auto Update over Wi-Fi only" in the Advanced Settings.**"

When clicking "Check for updates" for Safari filters via cellular network with "Auto Update over Wi-Fi only" enabled, jump the error:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/yUszhfj.png)
</details><br/>

When clicking "Check for updates" for subscriptions via cellular network with "Auto Update over Wi-Fi only" enabled, jump the error:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/54tPl8N.png)
</details><br/>

B/R

**Comment by Versty** [comment]
@lancelot-moon Manual update over cellular now works correctly even if the `Auto-update over Wi-Fi only` option is enabled.
