### ISSUE TITLE
Cannot download App Store Updates with DNS Server enabled (AdGuard Pro 2.0.0(143)

### ISSUE THREAD

**Issue by navinmaini** [AdguardTeam/AdguardForiOS#693]
### Steps to reproduce

1. Select DNS Server from DNS Settings (e.g. CS England DNSCrypt server)
2. Enable Privacy
3. Open App Store to check for updates
4. Attempt to install any available updates from App Store

### Expected behavior

Updates from App Store should be downloadable.

### Actual behavior

Updates do not download - stuck with 'Update' badge. When disabling Privacy in AGP (effectively switching off DNS server), updates in App Store download normally again.

Tested on 4 devices (2 x iPhone 8 Plus and 2 x iPad Pro) and unable to download App Store updates when Privacy is on and using the selected DNS server (CS England DNSCrypt server, in this case).

### Your environment

* iPhone 8 Plus 64GB
* iOS 11.3 Public Beta 4
* Wi-Fi

**Comment by zebrum** [comment]
@navinmaini It seems to be a problem with that DNS server, but now it works ok. Also you can check with any other DNS server.

**Comment by navinmaini** [comment]
Thanks; will keep an eye on this because I don't currently have any updates showing. When I do, I will check if it is now working or not.

**Comment by zznosar** [comment]
I just tried it using AdGuard DNS and it worked. It’s actually fast. I was not able to record a video to show.

**Comment by navinmaini** [comment]
Yes, thanks. I tried on my iPad now and had a few updates complete with no issue now. It was something temporary which fixed itself (always the best way!).
