### ISSUE TITLE
Не работает авторизация в метро

### ISSUE THREAD

**Issue by zhilinskiyaleksandr** [AdguardTeam/AdguardForiOS#694]
не работает авторизация в метро Москвы.
AdGuard Pro 2.0.0
iOS 11.2.6
iPhone 7
браузер Safari 
список фильтров: English, Spyware, Social media, Russian, Safary, Mobile ads.
AdGuard DNS выключен.
Адрес сайта где проходит авторизация https://auth.wi-fi.ru/
Фильтры обновлены.
![img_1619](https://user-images.githubusercontent.com/37153844/37108732-07a9f658-2249-11e8-878c-62b7a43a285c.PNG)

**Comment by zhilinskiyaleksandr** [comment]
https://auth.wi-fi.ru/

**Comment by ameshkov** [comment]
Правильно я понимаю, что проблема именно при включенном AdGuard DNS?

**Comment by zhilinskiyaleksandr** [comment]
добрый день! 
Я пробовал и при включенном AdGuard DNS и при выключенном.
Результат один и тот-же.
![img_1619](https://user-images.githubusercontent.com/37153844/37108463-3626cf5c-2248-11e8-8e37-8dfdb413b1d7.PNG)
![img_1620](https://user-images.githubusercontent.com/37153844/37108465-364ae608-2248-11e8-8441-78961de229e6.PNG)

**Comment by ameshkov** [comment]
А когда выключаешь блокировку в Safari дополнительно?

**Comment by zhilinskiyaleksandr** [comment]
если в настройках Safari выключить "Правила блокирования контента" - тогда авторизация срабатывает.
но тогда от приложения никакого толку, так как оно выключено получается.
или Вы что-то другое имели в виду?

**Comment by Alex-302** [comment]
А фильтры обновлены?

**Comment by zhilinskiyaleksandr** [comment]
все фильтры были обновлены.

**Comment by zebrum** [comment]
Подключилась с включенным контент блокером и нашим днс нормально.

**Comment by ameshkov** [comment]
@zhilinskiyaleksandr нужен тогда полный список фильтров

**Comment by zhilinskiyaleksandr** [comment]
уважаемый Ameshkov! Полный список фильтров: English, Spyware, Social media, Russian, Safary, Mobile ads.

**Comment by zhilinskiyaleksandr** [comment]
уважаемая zebrum!
только что попробовал зайти еще раз, так как Вы написали, 
в настройках DNS включил AdGuard "Стандартный", но авторизация не сработала
![img_1622](https://user-images.githubusercontent.com/37153844/37118659-06d530d6-2266-11e8-8647-ec9f7d43e14c.PNG)

**Comment by Alex-302** [comment]
> Если попробовать войти с компьютера

из внешней сети или вы с ноутом в метро?

> DNS включил AdGuard "Стандартный", но авторизация не сработала

а если выключить фильтры, включив DNS AdGuard? Если не пустит, откройте журнал DNS и посмотрите какие домены были заблокированы в момент попытки авторизации.

**Comment by zhilinskiyaleksandr** [comment]
я сейчас уже дома и пробую заходить из внешней (домашней) сети.
отключил все фильтры, включил DNS AdGuard "Стандартный" - авторизация не сработала.
а вот что в журнале DNS
![img_1623](https://user-images.githubusercontent.com/37153844/37120049-4c9d29b2-226a-11e8-81e1-7a0a0838b316.PNG)

**Comment by Alex-302** [comment]
не пустило или сайт не доступен?

**Comment by zhilinskiyaleksandr** [comment]
на сайт пустило, но выскочила все та-же картинка с собачкой.

**Comment by Alex-302** [comment]
а попробуйте секунд через 10 после появления собаки обновить журнал(свайпнуть вниз), может не все записи появились.
Для надёжности можно выкл/вкл интернет, чтоб очистить кэш DNS.

**Comment by zhilinskiyaleksandr** [comment]
![img_28b68b57c8f5-1](https://user-images.githubusercontent.com/37153844/37121275-b483c60a-226d-11e8-9a99-51f811f98a19.jpeg)

**Comment by zebrum** [comment]
может они таки как-то детектят контент-блокер? Надо проверить в другом браузере.

**Comment by zhilinskiyaleksandr** [comment]
сегодня попробовал авторизоваться - и все работает.
видимо они как-то выборочно детектят и блокируют на сутки в качестве наказания, 
так как при вчерашней блокировке я не мог авторизоваться даже когда полностью удалил приложение с телефона.
посмотрю что будет позже.

**Comment by ameshkov** [comment]
> видимо они как-то выборочно детектят и блокируют на сутки в качестве наказания,
> так как при вчерашней блокировке я не мог авторизоваться даже когда полностью удалил приложение с телефона.

Именно так. Они не сразу блокируют, и при этом еще и банят на некоторое время.
