### ISSUE TITLE
Add an explanation in all AppStores that translations are made by a community

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardForiOS#696]
Maybe it would be a good idea to add an explanation in all AppStores where AdGuard is present that explains why a translation may be incorrect or not finished. Something like this

AdGuard in your language
The translations of our AdGuard app are made by community members. If there is something wrong or missing you can support us translation the app to your native language. Further informations are available under https://kb.adguard.com/en/general/adguard-translations

**Comment by javabean** [comment]
Maybe even in the application itself for a couple of releases. French translation is a disaster! :-(
(I submitted updated strings in OneSky, but I guess they need more votes to become officially endorsed…)
