### ISSUE TITLE
Can use other VPNs even when AdGuard is in Full Tunnel mode.

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#697]
### Steps to reproduce
1. Launch AdGuard in Full VPN mode
2.  You'll still be able to launch and use personal VPN in parallel

### Expected behavior
Full tunnel mode shouldn't allow the use of other VPNs

### Actual behavior
You are able to launch and use personal VPN in parallel

### Customer ID, screenshots, logs
1760615

### Your environment

* Device model and storage size: iPhone, unspecified model
* Operating system and version: 11.2.5
* Browser (e.g. Safari): N/A
* Wi-fi or mobile internet connection: Both

**Comment by IvanIin** [comment]
@akmLaVx
It only seems that another VPN is working. In fact, this is not true. You can easily see this. Look at your external IP through any "my ip" service. If you turn off the AdGuard and turn on/turn off the other VPN, then the IP address will change. With the enabled AdGuard, the IP address does not change.
