### ISSUE TITLE
Disappearing hosts file subscriptions

### ISSUE THREAD

**Issue by knirirr** [AdguardTeam/AdguardForiOS#698]
### Steps to reproduce
1. Subscribe to one or more hosts files on Github, e.g. https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
2. Use the phone normally for a day or so.
3. Check the privacy settings and discover that the links added in 1 are now missing; the subscriptions settings have returned to the default of none.

### Your environment
* iPhone 7
* iOS 11.2.6

I've not included a screenshot as there's nothing in particular to see. I've noted this behaviour twice since upgrading to the latest version.

**Comment by lancelot-moon** [comment]
duplicate
https://github.com/AdguardTeam/AdguardForiOS/issues/575

**Comment by knirirr** [comment]
Thanks - apologies for not spotting the original.
