### ISSUE TITLE
Add an option to contact support through a third party mail app or web mail

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#70]
Can we use mailto:// link to do it?

**Comment by worldsdream** [comment]
This would be good, as I do use the Spark email app and not the standard iOS mail app!

**Comment by zebrum** [comment]
We send bug reports with standard iOS "Mail" app.

Some people don't use it, so they get an error "No Configured Email" when they try to send a ticket.

This is not a common problem for iOS users at the moment, but we might need to think about reworking it.

From #379 #387

**Comment by IvanIin** [comment]
duplicate #1304
