### ISSUE TITLE
An option to add subscription from a local file

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#701]
As requested by user #1785577,

"- Privacy setting subscriptions should have option to enable/disable without delete it
- If we could support subscriptions with format zip/7zip. It's really helpful to reduce time and bandwidth to load it.
- Widget should not open the app. It's kind of annoying when on/off via widget when another app is in foreground."

**Comment by ameshkov** [comment]
@akmLaVx could you please divide it into three different feature requests?

> Widget should not open the app. It's kind of annoying when on/off via widget when another app is in foreground."

As far as I know this is not possible technically

**Comment by lancelot-moon** [comment]
The 1st point is duplicate with mine.
https://github.com/AdguardTeam/AdguardForiOS/issues/601

**Comment by solitary1510** [comment]
@ameshkov I see AdBlock can do that. So I think AdGuard is possible too

**Comment by zebrum** [comment]
here is the explanation why we didn't do it: https://github.com/AdguardTeam/AdguardForiOS/issues/312#issuecomment-318376189
