### ISSUE TITLE
YouTube app crashes when iOS Pro is launched

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#703]
### Steps to reproduce
1. Launch any YouTube video through the app when AdGuard protection is enable
2. A grey screen will appear for a second
3. YouTube app will crash
4. Stopping protection resolves the issue

### Expected behavior
AdGuard should block ads in YouTube without impacting its functionality

### Actual behavior
AdGuard causes YouTube app to crash

### Customer ID & logs
1785904

### Your environment
* Device model and storage size: Unspecified iPhone
* Operating system and version: 11.2.6
* Browser: In-app
* Wi-fi or mobile internet connection: Unspecified, presumably both

**Comment by LaxusiC** [comment]
You cannot block ads in Youtube App unless you use a modified youtube version, if you block the domain it will cause the app crash (cannot connect to server maybe?) that what i know

**Comment by zebrum** [comment]
can't repro so far, waiting for additional info from user

**Comment by evgeniy-ADG** [comment]
The customer said it doesn't crash on him anymore.

**Comment by zebrum** [comment]
YAY!
