### ISSUE TITLE
AdGuard for iOS Pro slows down page loads

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#707]
### Steps to reproduce
1. Enable protection
2. Load up any page
3. Significant page load slowdown occurs

### Expected behavior
AdGuard for iOS Pro 2.0 shouldn't slow down page load THAT significantly

### Actual behavior
Page loads very, very slowly

<details><summary>Screen recordings:</summary>

Page loads w/ ADG 1.3 and ADG 2.0 are in the ticket 1627942.

</details>

### Customer ID & Logs 
1627942

### Your environment
* Device model and storage size: unspecified iPhone
* Operating system and version:  iOS 11.3b4
* Browser (e.g. Safari): Safari
* Wi-fi or mobile internet connection: WF

**Comment by akmLaVx** [comment]
Pro features are disabled, so using default DNS.
Filters: English, Spyware, Social Media, Annoyances, Mobile ads, Safari, Fanboy Annoyances
No info about privacy subscriptions, will ask separately.

**Comment by akmLaVx** [comment]
Additional info from the user:

No additional pro, privacy features being used. The same whitelist, and filters being used in both versions. No advanced features being used in either version.

**Comment by bug-killer** [comment]
Additional info from the user:

English filter slows safari down dramatically. Just disabling the English filter and using the EasyList filter make page loads faster. Ever since version 2.0 Adguard has slowed safari page loads. Something is not quite right since the update.

**Comment by zebrum** [comment]
@akmLaVx @bug-killer couple examples?  I need to compare.

**Comment by bug-killer** [comment]
Reply from the user:
Macrumors.com
TMZ.com
Imore.com

**Comment by ameshkov** [comment]
https://adguard.com/en/blog/adguard-pro-discontinued/
