### ISSUE TITLE
Make the tutorial videos disappear or go down after first watch

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#711]
As reported by user 1522340,

"Please arrange the videos / instructions in the GUI / surface below!
Man must always scroll over the links to the videos to get to the settings - e.g. Manual filter updates etc
These instructions are only needed once or very rarely to not at all."

**Comment by lancelot-moon** [comment]
Well, users think that the vertical stack of tutorial videos is not good, which is anticipated.
But I guess that he doesn't know that he can hide tutorial videos.
Oh no~~~ please keep tutorial videos on the top of main screen.
Simply, please modify tutorial videos to overlap.
Swiping slide is better.
https://github.com/AdguardTeam/AdguardForiOS/issues/671

**Comment by zebrum** [comment]
@akmLaVx user able to swipe videos to the left to hide them.
