### ISSUE TITLE
AdGuard 2.0 fails to load filters into Safari on jailbroken iOS

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#716]
> AdGuard Pro (2.0.2.146) On my iPhone 7 Plus iOS 11.1.2 does not work while in Jailbroken state whatsoever. I have had problems with it ever since the most recent major update. The only way I have been able to get the app functioning again is to return to a non-jailbroke state. Basically, the app says there are too many filters to load into Safari, and won’t let me make any changes. Even if there are no filters selected at all. I have spent the past week or so digging through forums & such, trying to problem solve on my own to no avail.

### Expected behavior

AdGuard works as expected

### Actual behavior

It can't load filters and throws the "too many filters" error. The app has been reinstalled, disabled and enabled back in the content blocker settings, nothing helps.

### Customer ID 
1792515

### Your environment

* Device model and storage size: iPhone 7 plus
* Operating system and version: iOS 11.1.2 w/ jailbreak
* Browser Safari
* Wi-fi or mobile internet connection n/a

**Comment by evgeniy-ADG** [comment]
> AdGuard Pro shows the error message that safari content blocker is disabled while I'm on jailbroken state. Is there any integrity protection in AdGuard software that does not allow it to work on jailbroken devices? I'm pretty sure it’s not any of my tweaks because it returns the same error running in safe mode. Any ideas that could help solve this?

**Customer ID**
1812641


**Your environment**

- Device model and storage size: iPhone ?
- Operating system and version: iOS 11.1.2 w/ jailbreak
- Browser Safari
- Wi-fi or mobile internet connection n/a

**Comment by Eugene-Savenko** [comment]
> My device has jailbroken, ios 10.3.1. Prior to the jailbreak, the Adguard application still detects the active content blocker. But after the jailbreak, the Adguard application has disabled the Content blocker! Although not detected, but the safari still block ads like no jailbreak.

<details> <summary> screenshot </summary>

![image](https://user-images.githubusercontent.com/15856304/39967904-86082792-56cc-11e8-808c-1f65a67d6165.png)

</details>

**Customer ID**
1542905


**Your environment**

- Device model and storage size: iPhone ?
- Operating system and version: iOS 11.1.3 w/ jailbreak
- Browser Safari
- Wi-fi or mobile internet connection n/a

**Comment by ameshkov** [comment]
@Eugene-Savenko can you ask them to narrow the issue down to a specific filter maybe?

**Comment by worldsdream** [comment]
I am jailbroken on ios 11.3.1. Latest Adguard Pro. No issues. Always have been jailbroken.
