### ISSUE TITLE
Websites stall when using AdGuard

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#717]
> With VPN/DNS switched on, web pages stall, no matter what name service is chosen on an iPad. Work on iPhone. Same versions of software and iOS. BTW, I have restarted the device, reset it several times, reinstalled AdGuard, and tried both of the VPN settings.

### Steps to reproduce

1. Begin with thestar.com loaded properly using the system's DNS.
2. Switch on AdGuard to your DNS
3. Try to load thestar.com in Safari and watch it stall.
4. Switch to system DNS
5. Look at log.
6. Try to load thestar.com in Safari and watch it stall.
7. Look at log and try to reload log.
8. Disable AdgGuard.
9. Watch Safari load thestar.com.

### Expected behavior

Web pages are fully downloaded with AdGuard

### Actual behavior

For some reason they stall

<details><summary>Screen recording:</summary>

https://uploads.adguard.com/tw2jp.MP4

</details>

### Customer ID 
1787731

### Your environment

* Device model and storage size: iPad
* Operating system and version: 11.2.6
* AdGuard 2.0.2.146
* Browser (e.g. Safari) - Safari
* Wi-fi or mobile internet connection - both

**Comment by zebrum** [comment]
this is connected with #723 I think
