### ISSUE TITLE
AdGuard 2.0.2 crashes on iOS 10.2.1

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#718]
The screen recording: https://www.youtube.com/watch?v=MAP6V0nNaTc

### Customer ID 
1797554

### Your environment

* Device model and storage size: iPhone
* Operating system and version: 10.2.1
* Browser (e.g. Safari)
* Wi-fi or mobile internet connection

**Comment by zebrum** [comment]
Did user try clean install?

**Comment by worldsdream** [comment]
Adguard free crashing on ios 9
Will try a fresh install and report back

**Comment by ameshkov** [comment]
@worldsdream the fix is on the way (waiting for Apple review)
