### ISSUE TITLE
Change section "Adguard for iOS" on https://adguard.com/en/acknowledgements.html#ios-acknowledgments

### ISSUE THREAD

**Issue by Stillness-2** [AdguardTeam/AdguardForiOS#72]

**Comment by Stillness-2** [comment]
We need to add links to Third-Party Software:

- Tony Million for Reachability component (https://github.com/tonymillion/Reachability)
License: https://github.com/tonymillion/Reachability/blob/master/LICENCE.txt
- August «Gus» Mueller for Fmdb component (https://github.com/ccgus/fmdb)
https://github.com/ccgus/fmdb/blob/master/LICENSE.txt

**Comment by vbagirov** [comment]
Done.
