### ISSUE TITLE
New feature request: App-based whitelist

### ISSUE THREAD

**Issue by Sawengchuan** [AdguardTeam/AdguardForiOS#720]
Not sure this feature already exist.

As per title, would it possible to provide feature to whitelist ads based on App? So instead of hunting down all ads domain used by App to whitelist all of them, we simply provide App name/Id to AdGuard, and AdGuard will let all ads through for the whitelisted App.

Sometimes we want to support App.

**Comment by lancelot-moon** [comment]
It's impossible to split VPN for apps on iOS.
(AdGuard for Android can do so.)
You can only whitelist those ad domains.

**Comment by Sawengchuan** [comment]
Okay. Noted.

Thanks for the reply.

Sent from my iPhone

On 20 Mar 2018, at 18:00, lancelot-moon <notifications@github.com<mailto:notifications@github.com>> wrote:


It's impossible to split VPN for apps on iOS.
(AdGuard for Android can do so.)
You can only whitelist those ad domains.
