### ISSUE TITLE
Bug in French translation, unable to access the list of subscriptions in the Privacy section

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#722]
There's no link on Here (ici) word. See the screenshot below.

### Expected behavior

There's a link on "ici" word.

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/37641720-7c62b226-2c23-11e8-924b-04d8269e1911.png)

</details>

### Your environment

* Device model and storage size: iPhone
* Operating system and version: 11.2.1
* Browser (e.g. Safari)
* Wi-fi or mobile internet connection

**Comment by aalpatkina** [comment]
fixed on OneSky platform

**Comment by ameshkov** [comment]
@aalpatkina please verify that it's okay in other languages
