### ISSUE TITLE
Adguard pro 2.x for ios 9.0?

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#724]
Can you give users with ios 9 the option to upgrade to version 2.x?

**Comment by zebrum** [comment]
@worldsdream hotfix is on its way! Sorry for inconvenience.

**Comment by ameshkov** [comment]
Wait-wait.

PRO won't support iOS 9 anymore, we use some specific iOS 10 features and it would be too hard to do it. Free version will continue to support iOS 9 for some time.

**Comment by worldsdream** [comment]
Got it. Will revert to the free version. As I do like the new changes. 

I'm on ios9 jailbroken. That is why.
