### ISSUE TITLE
3rd-party filters don't work after updating to AdGuard 2.0 (non-pro)

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#725]
### Steps to reproduce
1. Update from AdGuard for iOS 1.x to 2.0

### Expected behavior
Third-party filters such as Adblock Warning Removal List, EasyPrivacy, etc should be able to update themselves

### Actual behavior
Third-party filters do not update automatically

### Logs
Available under 1798450.

### Your environment
* Device model and storage size: Unspecified iPhone
* Operating system and version: iOS 11.2.6
* Browser: N/A
* Wi-fi or mobile internet connection: N/A

**Comment by zebrum** [comment]
We had some troubles with filter auto update on some devices, but we didn't change that part of code in new version. 

Also we are planning to rework that filters update part.
