### ISSUE TITLE
Amazon Track Your Package Site since version 2.0 blocked

### ISSUE THREAD

**Issue by Basic-income** [AdguardTeam/AdguardForiOS#726]
If open amazon site and go to in my account the track your package site or tap this in the email inbox.
Then is the url blocked or not loading this site. 

### Your environment

* Device model and storage size: iPad 9.7
* Operating system and version: iOS 11.2.6
* Browser: Safari
* Mobile internet connection
* EasyPrivacy list only 
* Adguard Pro 2.0.2

Notes: Adguard 1.3.3 with EasyPrivacy list only. No a issue.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardFilters #13535](https://github.com/AdguardTeam/AdguardFilters/issues/13535) via [**ZenHub**](https://www.zenhub.com/)
