### ISSUE TITLE
Part of User Filter section is blocked by keyboard

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#728]
### Steps to reproduce
1. Try to add a rule to User Filter using a web report tool
2. Sometimes the on-screen keyboard will block a part of User Filter screen, preventing it from adjusting its position on the screen.

### Expected behavior
OSK shouldn't block User Filter window

### Actual behavior
OSK blocks user filter window

<details><summary>Screenshot and screen recording:</summary>

Available under 1799999.

</details>

### Customer ID 
1799999

### Your environment
* Device model and storage size: iPhone 5S
* Operating system and version: iOS 11
* Browser:  n/a
* Wi-fi or mobile internet connection: both

**Comment by zebrum** [comment]
@akmLaVx I need more details about this situation. 
And please tell the user he can swipe video to the left :)

**Comment by akmLaVx** [comment]
User has replied:

Unfortunately, I can’t find steps to reproduce the issue - even though I’ve seen it happen several times.

Here is what I’m doing when it sometimes happens: I’ll block an element on a website - which will open AdGuard to the user filter screen. I double tap near the bottom of the code that was just added and all of the code usually shifts up to make room for the keyboard... but sometimes that shift doesn’t happen and the keyboard covers the code of interest.

I usually have Spotify and a few other things running in the background - so I just figured that my iPhone 5S was too busy to shift the code up. Is the OS supposed to cause the shift or does AdGuard have to make it happen?

**Comment by zebrum** [comment]
@akmLaVx can you ask the user of issue still persist?

**Comment by ameshkov** [comment]
Reopen if there's new info
