### ISSUE TITLE
Message about unknown option in the log

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#73]
For example:
```
2016/02/03 09:43:52:543  Javascript Info: Cannot create rule from /homadconfig.json$replace=/"enabled":\s*true\,/"enabled": false\,/i,domain=spiegel.de, cause Unknown option: REPLACE
2016/02/03 09:43:52:543  Javascript Info: Cannot create rule from ://*.damoh.golem.de/$replace=/(<VAST(.|\s)*?>)(.|\s)*<\/VAST>/\$1<\/VAST>/,domain=video.golem.de, cause Unknown option: 1<\/VAST>/
```

**Comment by ameshkov** [comment]
You should ignore rules with "replace" modifiers.

**Comment by ameshkov** [comment]
Ah, it should be done on converter side, I got it.

@Mizzick, please fix this.

**Comment by Mizzick** [comment]
But it's ignored already?

**Comment by ameshkov** [comment]
It would be better to suppress that message.

$replace option is known, it is just unsupported by extension.

**Comment by ameshkov** [comment]
You can simply remove rules with replace modifier on the server side (I mean remove it from chrome.adtidy.org)

**Comment by Mizzick** [comment]
Ok, done.
