### ISSUE TITLE
Not able to turn vpn off in settings on iPad or iPhone 

### ISSUE THREAD

**Issue by streetglide2018** [AdguardTeam/AdguardForiOS#732]
I’m using AdGuard pro on my ipad and iPhone. Trying to watch tv on my time Warner app it says vpn not supported please disable in settings. When i go into my settings and click to disable it turns it right back on. Then if i click it back off it turns back on. I cant get it to stay off to be able to use the app for my tv.

**Comment by zebrum** [comment]
you'd better turn off Pro status in AdGuard settings. 
But I'm curious why it says that. What DNS server do you use? Can you run the app, then open DNS requests log in AdGuard (by tapping on the stats tab in the app's main menu) and check what domains are blocked?

**Comment by zebrum** [comment]
@streetglide2018 
https://uploads.adguard.com/up03_9bjku.png

**Comment by streetglide2018** [comment]
Ok. Thank you.
