### ISSUE TITLE
AdGuard become not stable in connecting if the Subscription rules reached certain amount

### ISSUE THREAD

**Issue by gslb86** [AdguardTeam/AdguardForiOS#734]
### Steps to reproduce

1. Go to Subscription Add the Subscription lists
2. Then go to filterlists.com to find the subscription lists that you wish to add
3. My subscription list are AdGuard SDN filter, AdAway default Blocklist, hpHosts - Ad and Tracking Sites, Fanboy's Annoyances List, I Don't Care Cookies, Cookies Blocklist, AdGuard Annoyances Filter, Disconnect Advertising Filter List and Disconnect Malvertising Filter List
4. After you can these filter, go to Setting => VPN you will see the AdGuard Pro VPN keep connecting and disconnected 

### Expected behavior
After you can these filter, go to Setting => VPN you will see the AdGuard Pro VPN connected

### Actual behavior
After you can these filter, go to Setting => VPN you will see the AdGuard Pro VPN keep connecting and disconnected 

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Device model and storage size: iPhone X 256 GB
* Operating system and version: 10.2.6
* Browser (e.g. Safari)
* Wi-fi or mobile internet connection: Wifi

**Comment by ameshkov** [comment]
Yeah, that's expected as iOS imposes a 15MB limit on the VPN tunnel RAM. We will warn people about that: #616 

> My subscription list are AdGuard SDN filter, AdAway default Blocklist, hpHosts - Ad and Tracking Sites, Fanboy's Annoyances List, I Don't Care Cookies, Cookies Blocklist, AdGuard Annoyances Filter, Disconnect Advertising Filter List and Disconnect Malvertising Filter List

These filters are not really usable on the DNS level as they consist of cosmetic rules:
Fanboy's Annoyances List, I Don't Care Cookies, Cookies Blocklist
