### ISSUE TITLE
I'm unable to get :has() to work

### ISSUE THREAD

**Issue by MrDemocracy** [AdguardTeam/AdguardForiOS#736]
When I use this filter `##.splitboard-inner-wrap div:has(iframe)`, I get a syntax error (the filter get's highlighted in red).

### Customer ID 

1797554
### Your environment

* Device model and storage size: iPhone 6S 128GB
* Operating system and version: 10.2.1
* Browser: Safari
* Wi-fi or mobile internet connection: 4G (mobile internet)

**Comment by ameshkov** [comment]
Cosmetic rules on iOS are limited to regular CSS, you can't use cool [ExtCss](github.com/AdguardTeam/ExtendedCss) features like `:has` :(

**Comment by krystian3w** [comment]
How this works now in Safari 15.4? Run without WebExtension?

**Comment by ameshkov** [comment]
Yes, it runs via WebExtension. Unfortunately, `:has` cannot be used via regular content blockers (we filed a bug report already).
