### ISSUE TITLE
Block dns host only app

### ISSUE THREAD

**Issue by staryob** [AdguardTeam/AdguardForiOS#739]
Please help my. Block dns domain online app. 

Please help me. 

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Device model and storage size: (e.g. iPhone 6s 64gb)
* Operating system and version: (e.g. 10.3.1)
* Browser (e.g. Safari)
* Wi-fi or mobile internet connection

**Comment by zebrum** [comment]
If you have a problem with AdGuard app, please submit the detailed description using template.
