### ISSUE TITLE
Feature request: allow using non-optimized filters on iOS

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#74]
Not yet planned on any release.

**Comment by worldsdream** [comment]
Isn't this already in the iOS app? We can switch simplified ON/OFF.

**Comment by ameshkov** [comment]
Nah, that switch is a bit different. It disables generic hiding rules.

What I mean here is switching between filter versions non-optimized (huge, with redundant rules) and optimized for mobile (where redundant rules are removed).
