### ISSUE TITLE
Which formats of subscription does AdGuard support? (question)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#741]
Well, the question existed in my heart...
I wish answers.

When I see these formats of blocking list on the website, I'm not sure if AdGuard for all platforms support them.
https://ransomwaretracker.abuse.ch/blocklist/

formats of subscription:
**a. Only domains, ex: example.com
b. URL, ex: http://example.com or http://00005ik.rcomhost.com/7fg3g
c. IP, ex: 103.43.75.87
d. hosts file, ex: 0.0.0.0 example.com
e. basic adblock rule syntax, ex: ||example.com^
f. advanced adblock rule syntax, ex: example.com#@#.afs_ads**

May you answer the question about external subscription's formats of AdGuard for all platforms for system-wide adblocking?
AG for Android: Don't support external subscriptions now.
AG Pro for iOS: d, e (Does it support a and c?)
AG for Windows: ?
AG for macOS: ?

Thanks.

**Comment by ameshkov** [comment]
AG for Mac/Win supports the e. and f.
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters
