### ISSUE TITLE
Documentation needed for DNS network extension max # rules

### ISSUE THREAD

**Issue by javabean** [AdguardTeam/AdguardForiOS#745]
As per AdGuard 2.0, user can now import a DNS subscription from a URL, as documented in https://kb.adguard.com/en/ios/features

This page notes:
> NOTE: Important to notice that too many subscriptions can lead to tunnel crash, i.e. the app will stop responding and the filtering will cease.

but gives no indication on many rules / DNS domains can fit before the network extension runs out of memory (and hence crash).

I understand that this maximum number or rules will depend on the length of each entry, as well as the iOS version (iOS 9 allows less memory to network extensions than 10 & 11), but an estimation of such a maximum would be highly desirable.

**Comment by zebrum** [comment]
@javabean it's about 90k rules
and yes, we are planning to notify users about limit.
