### ISSUE TITLE
Consider creating a filter for Smart Banners

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForiOS#75]
When using Safari on iOS devices and visiting a homepage, which provides an App in the App Store,
one quite often sees a banner on the top end of site advertising to load the app in the store.

Apple calls this Smart Banners: https://developer.apple.com/library/mac/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html

Idea here - KGE-833-58481

**Comment by ameshkov** [comment]
That's impossible to do with a content blocker API:(
