### ISSUE TITLE
AdGuard Pro 2.1.0 (149) DNS protocol clear dialog strings not translated / not on OneSky

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardForiOS#753]
For German it should be:
Protokoll löschen und Statistiken zurücksetzen
Protokoll löschen

![img_3612](https://user-images.githubusercontent.com/25068100/38849247-b6e39c50-420b-11e8-95ce-be08cbb383b0.jpg)

**Comment by aalpatkina** [comment]
Done. Thank you.
