### ISSUE TITLE
Updating filters while PRO/VPN turned on not working v2.1.0(149)

### ISSUE THREAD

**Issue by gh0sti** [AdguardTeam/AdguardForiOS#755]
I have asked about this issue in the past multiple times and have gotten emails from support saying it would be fixed in the next update, ect. Repeating circle has this issue been fixed or will it never be fixed?
I paid for this VPN/PRO access as well.
### Steps to reproduce

1.have PRO?VPN option turned on
2.try to update filters
3.filter updating errors
4.profit?

### Expected behavior
Filters should update even with the VPN on

### Actual behavior
fitler updating fails to update

### Your environment

* Device model and storage size: iPhone X
* Operating system and version: iOS 11.3
* Browser: Safari
* Wi-fi or mobile internet connection: both

**Comment by gh0sti** [comment]
I have also tried non testflight builds and testflight builds of this app still the same issue.

**Comment by zebrum** [comment]
Hi!
Have you sent logs to support? If so, please tell me your user_id so we could find the letter?

**Comment by gh0sti** [comment]
looks like I was able to resolve this after emailing support with logs by deleting and reinstalling the app, it somehow kept a bug from 1.3 which was blocking the filter update while on vpn
