### ISSUE TITLE
Please soon let Traditional Chinese Web Reporting Tool be online.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#756]
For Taiwanese users, now web reporting tool still leads to Russian website in AG Pro v2.0.2(146) & beta v2.1.0(151).

Long~long time ago, Traditional Chinese Web Reporting Tool was very early 100% finished.
Please give Traditional Chinese Web Reporting Tool to Taiwanese users from AG Pro v2.1.0 & next version of free AG for iOS.

And allow iOS users to report in-app ads by Web Reporting Tool.
https://github.com/AdguardTeam/ReportsWebApp/issues/143#issuecomment-383398624

Thanks.

**Comment by lancelot-moon** [comment]
@aalpatkina 
@IvanIin 

Traditional Chinese for critical.xliff file of website is all finished.
Please let Traditional Chinese website and web reporting tool be online.

Thanks a lot.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/ReportsWebApp #156](https://github.com/AdguardTeam/ReportsWebApp/issues/156) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ameshkov** [comment]
> The rate of progress for Traditional Chinese:

> Total website: 81.3%

@vbagirov what's the minimum percent when we add translations for non-critical pages?

> Web reporting tool: 100%

It's online, the latest translations will be updated in due course (it happens rather often).
