### ISSUE TITLE
Please add more hosts files in the list of "popular subscriptions".

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#757]
1hosts.cf:
http://1hosts.cf/

Originally, 1hosts has more than 61k+ rules.
But I contacted with its maintainer and requested for a slim 1hosts.
He is a good guy!
He reduced the amount of rules to only 47k+ rules, which gives me more flexible choice for adding other good subscriptions.
I also reported some Taiwanese bad or ad domains which I got from other popular hosts files to him.

CoinBlockerLists:
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts

CoinBlockerLists (optional):
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_optional.txt

CoinMiner:
https://raw.githubusercontent.com/anudeepND/blacklist/master/CoinMiner.txt

NoCoin (hosts):
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt

Hexxium Creations Threat List:
https://raw.githubusercontent.com/HexxiumCreations/threat-list/gh-pages/hexxiumthreatlist.txt

Ransomware Tracker Domain Blocklist:
https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt

AdZHosts: (Well, this is a big guy. But it's also a good hosts file.)
https://adzhosts.fr/hosts/AdZGuardFilter.txt

This is my now subscriptions. (81512 rules in subscriptions.)
Thank 1hosts to slim its size. :D
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/munupvN.png)
</details><br/>

B/R

**Comment by ameshkov** [comment]
https://adguard.com/en/blog/adguard-pro-discontinued/
