### ISSUE TITLE
2.1.0 (149 - 153) tunnel doesn't work

### ISSUE THREAD

**Issue by SA727SS** [AdguardTeam/AdguardForiOS#758]
### Steps to reproduce

Bug A-1. Add any URL to blacklist
A-2. Using split tunnel or full tunnel (without VPN icon)
A-3. Visit added URL on any browser

Bug B-1. Switch to full tunnel
B-2. Open safari and open any website

### Expected behavior

Bug A. Block URL
Bug B. Website should open normally

### Actual behavior

Bug A. Nothing is blocked, and zero DNS Request logs at AdGuard
Bug B. Safari error: Safari cannot open the page because the server cannot be found

### Customer ID 
 1842900

### Your environment

* iPhone 6s Plus 64GB
* iOS 10.3.3
* Browser: Safari
* Wi-Fi internet connection

**Comment by zebrum** [comment]
@SA727SS 
It looks like tunnel doesn't work, please contact support from the app and attach logs, then post here your user_id from auto reply email from support team.

**Comment by SA727SS** [comment]
Tunnel still not working properly on 152 & 153.

Same behavior as early 2.1.0 version.

**User ID**: 1842900

**Comment by IvanIin** [comment]
@SA727SS 
I see in logs that you use ipv6 dnscrypt server. But you don't have working ip6 network interface. Try to choose other dns server.

**Comment by SA727SS** [comment]
@IvanIin I'm pretty sure IPv6 is working, sometimes even get warning say I was using IPv6 only and only can use system default. And I tried other DNS (both DNSCrypt and regular), even system default, but doesn't seem to be working.
![img_0096](https://user-images.githubusercontent.com/38157428/39360998-15921264-4a53-11e8-9728-6d048c30502d.PNG)

**Comment by ameshkov** [comment]
https://adguard.com/en/blog/adguard-pro-discontinued/
