### ISSUE TITLE
A wrong sentence in your new description for AG Pro on App Store (oneskyapp).

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#760]
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/VMzQV8W.png)
</details><br/>

Original: Block add like a pro with the public and AdGuard filters.
Fixed: Block ads like a pro with the public AdGuard filters.

Original: For more than 6 years, AdGuard helps all of our users enjoy the safe and clean Internet.
Fixed: For more than 6 years, AdGuard helps all of **its** users enjoy the safe and clean Internet.

Will you change the title of AG Pro to "AdGuard Pro - no ads & popups"?

B/R

**Comment by lancelot-moon** [comment]
@aalpatkina 
@zebrum 

Hi,
You forgot to fix this.
You can also update Traditional Chinese description on app store since it's new description.

**Comment by zebrum** [comment]
@lancelot-moon 

add --> ads - definitely
the public and AdGuard --> the public AdGuard - nope
our --> its - yes, probably your suggestion is better. 

thank you!
