### ISSUE TITLE
Auto-Update over Wi-Fi Not Working

### ISSUE THREAD

**Issue by tempestxax** [AdguardTeam/AdguardForiOS#761]
On my iPhone X, running the latest iOS 11.3, but on all previous versions of iOS 11 as well, my AdGuard Pro will not auto-update content filters.

I have background app refresh on in general and for the app, and I leave the app running in the background and foreground, but the auto-update for filers never works.

I always have to manually press Check for Updates in order to get my filters to update.

**Comment by ameshkov** [comment]
How often do you check? It happens once in 48 hours or so

**Comment by tempestxax** [comment]
Hello, Andrey.

So the way I tested it was to manually update it one day, then wait to see
if it would update at any point over the next few days.

After the latest app update, however, the filters automatically updated on
their own yesterday.

**Comment by zebrum** [comment]
@tempestxax so everything is good now?
anyway I'll keep an eye on it.
