### ISSUE TITLE
Newly blocked domains aren't reflected in past DNS request log

### ISSUE THREAD

**Issue by wzxu** [AdguardTeam/AdguardForiOS#762]
### Steps to reproduce
1. Enable Privacy protection and watch the DNS request log.
2. Pick a domain  shown in the log to add to blacklist.
3. Watch the request log.
4. Go back to main page or even relaunch the app and then watch the request log.

### Expected behavior
After the domain gets added to blacklist, it should be reflected in the request log right away (colored red and says "Blocked").

### Actual behavior
Past request log entries containing the domain don't get updated immediately, or even after relaunch the view or the app, for that matter. Have to tap to see the detail and make sure the action now says "Remove from Blacklist" to confirm it was indeed blocked.

<details><summary>Screenshot:</summary>

![png image](https://user-images.githubusercontent.com/5619348/39197037-29ef7f56-4816-11e8-8afb-316a35135e6f.png)

</details>

**Comment by ameshkov** [comment]
> After the domain gets added to blacklist, it should be reflected in the request log right away (colored red and says "Blocked").

But what if the domain was resolved before it was added to the blacklist. Marking it as "blocked" would be misleading.

**Comment by zebrum** [comment]
Domain wasn't blocked at that time. Why this status should be changed for earlier requests?
