### ISSUE TITLE
It should be unable to enable AG Pro Protection without internet connection.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#763]
@IvanIin 

In now version, we can enable AG Pro Protection in app without internet connection.
The logic is strange.
May you design that it will show a warning message about "no internet connection" and not allow to enable AG Pro VPN if having no internet connection?

Such like the mechanism of other VPN app for no internet connection.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/KDGnDLF.png)
</details><br/>

Thanks.

**Comment by ameshkov** [comment]
> In now version, we can enable AG Pro Protection in app without internet connection.

But what's the point?

**Comment by lancelot-moon** [comment]
When not connecting to internet, AdGuard Pro Protection should not be enabled.

It should jump an error message, "No internet connection." and not allow to enable it.

**Comment by ameshkov** [comment]
> When not connecting to internet, AdGuard Pro Protection should not be enabled.
> It should jump an error message, "No internet connection." and not allow to enable it.

I've got the idea, but I don't understand why do you think it should work like that.

AG is not a regular VPN and the protection status does not mean that your traffic goes through a VPN tunnel. It means that the protection is enabled and that's what matters.

**Comment by lancelot-moon** [comment]
Can we enable VPN when having no internet?
But AG Pro Protection can be on with no internet connection.
It's strange.
That's a logic problem and my point.

**Comment by ameshkov** [comment]
> But AG Pro Protection can be on with no internet connection.

Just an example, but what if you're inside an intranet and want to block smth on a local intranet portal?

I can understand why regular VPN apps do it -- they literally cannot work without an internet connection. AdGuard, on the other hand, **can** work, and that's why I think that limiting the app capabilities is unnecessary.
