### ISSUE TITLE
Can't block + not translated

### ISSUE THREAD

**Issue by D25SK** [AdguardTeam/AdguardForiOS#764]
1) can't add filter rule to contents blocker.
‪minkara.carview.co.jp##ul > li:has(.pr_on_top)‬
![image](https://user-images.githubusercontent.com/6007916/39345159-6957b980-49d6-11e8-92dd-afd0093b58d3.png)

2)Action lists are English on Japanese environment. This needs to add "ja.lproj" folder.
![image](https://user-images.githubusercontent.com/6007916/39345171-7e0bd2da-49d6-11e8-9d79-b2642a0775ee.png)
Sorry about crappy English.

**Comment by ameshkov** [comment]
> 2)Action lists are English on Japanese environment. This needs to add "ja.lproj" folder.

Thx to @IvanIin I now know that the issue will be resolved once we add the Japanese language support:)

**Comment by D25SK** [comment]
Thx.
Any alternative filter for :has?

**Comment by ameshkov** [comment]
> Any alternative filter for :has?

Unfortunately, nothing as good, you need to stick to CSS3
