### ISSUE TITLE
Missed word in Turkish translation in the iOS app

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#765]
In the Safari filter description.

How it is:

![image](https://user-images.githubusercontent.com/15856304/39347424-6ebcee3e-49fb-11e8-9f13-0dda554d327c.png)

How it should be:

![image](https://user-images.githubusercontent.com/15856304/39347413-64b17a86-49fb-11e8-992f-e316d15f0423.png)

**Comment by PentagramTr** [comment]
@ameshkov 
Hi,
A new bug in the Pro version.
There is a missing word in the description of the Turkish filter.The missing word here is "**filtre**".

<details><summary>Screenshot</summary>

![github com](https://user-images.githubusercontent.com/34379403/40634553-456ca242-62fe-11e8-8bc9-09080bf8adbe.png)


</details>

**Comment by ameshkov** [comment]
Seems to be okay on the server side now:
https://filters.adtidy.org/ios/filters_i18n.json
