### ISSUE TITLE
Why are some domains not in DNS Requests Log when using browsers? (question)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#767]
@ameshkov 
@IvanIin 
@Alex-302 

**Please AdGuard team to solve the issue for your iOS users!**

In Mobile Ads filter and SDN filter, ||google-analytics.com^ blocks **www.google-analytics.com**, which makes us not to open news on [line today](https://today.line.me/).
https://github.com/AdguardTeam/AdguardFilters/issues/14202#issuecomment-385164860

In Spyware filter, the 2 rules also block analytics.js, which makes us not to open news on line today.
||google-analytics.com/analytics.js
||google-analytics.com/analytics.js$third-party

**We can't block analytics.js under www.google-analytics.com, otherwise some websites will be broken.
We should add the rule, @@||www.google-analytics.com/analytics.js$third-party**

**I found that www.google-analytics.com didn't appear in DNS Requests Log after enabling AG Pro VPN and then visiting line today via Safari with Content Blocker.**

In such situation, www.google-analytics.com would appear in DNS Requests Log after enabling AG Pro VPN and then visiting line today via Google Chrome.
So adding www.google-analytics.com in the whitelist of privacy settings is valid for other browsers for solving the issue of line today.
That's why we still can't open news on [line today](https://today.line.me/) even if adding www.google-analytics.com in the whitelist of Safari Content Blocker or adding @@||www.google-analytics.com^ in the userfilter of Safari Content Blocker.

One of the ways to open news on [line today](https://today.line.me/) via Safari with AG Pro (SDN filter in subscription) is disabling Spyware filter, Mobile Ads filter & SDN filter in Content Blocker for Safari and adding www.google-analytics.com in the whitelist of privacy settings.

Why are some domains not in DNS Requests Log?
**Why is there the difference?
Is it because that www.google-analytics.com has been blocked by Mobile Ads filter/SDN filter or www.google-analytics.com/analytics.js has been blocked by Spyware filter?
So www.google-analytics.com won't appear in DNS Requests Log, right?**

B/R

**Comment by Alex-302** [comment]
added to Spyware filter:
`@@||google-analytics.com/analytics.js$domain=today.line.me`

**Comment by lancelot-moon** [comment]
Hi,
You forget other browsers and line app for visiting line today.

You can keep ||google-analytics.com^ in SDN filter.
But please add @@||www.google-analytics.com^ in SDN filter.

**Comment by ameshkov** [comment]
> You can keep ||google-analytics.com^ in SDN filter.
> But please add @@||www.google-analytics.com^ in SDN filter.

The problem is that `@@||www.google-analytics.com^` completely denies the `||google-analytics.com^` so it will basically unblock Google Analytics everywhere.

> You forget other browsers and line app for visiting line today in iOS.

I have not forgotten about them, and I understand that the website is extremely popular, but unblocking Google Analytics means exposing every AG DNS user to an aggressive third-party tracking (as the AG DNS work is based on the simplified domain names filter).

Unfortunately, the DNS-level blocking is simply not flexible enough to solve both issues.

You can add `google-analytics.com` to your DNS filtering whitelist and it will solve the issue for you.
