### ISSUE TITLE
HTTP(S) Filtering Log for Safari (feature request)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#768]
I am not sure if I misunderstand.
Content blockers of browsers do HTTPS filtering for websites on iOS, right?

Some domains of URL which are pre-blocked by AdGuard Content Blocker for Safari won't appear in System-wide's DNS Requests Log, right?
Ex:
https://github.com/AdguardTeam/AdguardForiOS/issues/767
www.google-analytics.com/analytics.js is blocked by AG Content Blocker for Safari (Spyware filter, Mobile Ads filter and SDN filter).
www.google-analytics.com would be not shown in DNS Requests Log.

**I want to know what AG Content Blocker for Safari blocked.
May you separate the now DNS Requests Log into" HTTP(S) Filtering Log for Safari" and DNS Requests Log?**
https://github.com/AdguardTeam/AdguardForAndroid/issues/1706

I'm tired to modify a photo from the screenshot of AG Pro's log.
So I directly modify the photo from AG for Android...
**This is the example of layout for "HTTP(S) Filtering Log for Safari" and DNS Requests Log, which is what I wish.
Importantly, please remember to give us the switch for pausing/disabling logging!**
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Z5wL1Jk.png)
</details><br/>

Thanks a lot!

**Comment by IvanIin** [comment]
We can't show Safari Content Blocker request log because we don't control the blocking process. We just load blocking rules to Safari Content Blocker and it blocks the advertisement. However, it does not provide us with any information about blocked requests.
