### ISSUE TITLE
Background update doesn't work.

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForiOS#77]
User reports he's got to enter the app to manually update the filters every few days.
Please see JJK-306-26395 for logs.

**Comment by vbagirov** [comment]
The problem is also present here: YSY-876-10836

**Comment by Stillness-2** [comment]
possible it fixed in the feature/issues/35 branch

**Comment by vozersky** [comment]
Also reported here XVI-720-70819

**Comment by Stillness-2** [comment]
new
