### ISSUE TITLE
AdGuard Pro 2.1.0(153) "Filters update error" not translated

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardForiOS#770]
"Filters update error" has not been translated. Please fix!
For German it should be "Fehler beim Aktualisieren der Filter".
![img_3657](https://user-images.githubusercontent.com/25068100/39471328-dfc84bf6-4d42-11e8-89a0-d4324f0d6550.jpg)

**Comment by sergerosenthaler** [comment]
@zebrum still not fixed and 2.1.0 has been released. Maybe moving this to a new milestone is a good idea. Please make sure the correct translation is on OneSky.

**Comment by tenbad** [comment]
I had this issue since 18 May. till now, even reboot or clean the personal filters.
