### ISSUE TITLE
DNS filtering / privacy module disabled after some time

### ISSUE THREAD

**Issue by kevandoyle2** [AdguardTeam/AdguardForiOS#771]
This has been occurring in all 3 modes, including the new mode of full-tunnel (with the VPN icon, a feature that I assume is new as of the update yesterday). When I say disabled, I do not mean it toggles itself off, rather, it continues to be toggled on but it will not filter DNS traffic and sometimes stop internet connections all together.

### Steps to reproduce
1. Enable the privacy module
2. Close the app and continue to use device as normal, opening apps that run ads and using them
3. After using an app for a few seconds, close it. Open the Adguard app again and open the DNS request log. Close request log and repeat 2 and 3. If nothing happens, try switching between wifi and cellular networks. Another way to induce this issue is by switching between the two full-tunnel modes while the module is enabled.
4. Eventually, device traffic will stop being filtered, even though the privacy module remains enabled, allowing ads to be displayed.

I have not tried this with split-tunnel, only with the new and old version of full-tunnel. When this bug happens, I have found turning the module off and on again will usually fix it, but in some cases I have had to restart my entire device to get it working again. It should be able to remain connected continuously, even when switching between cellular and wifi networks, and between modes.

### Customer ID 
1860764

### Your environment
* Device model and storage size: iPhone 8 64gb
* Operating system and version: iOS 11.3.1
* Browser: Safari
* Wi-fi or mobile internet connection: BOTH

**Comment by rafuse** [comment]
Same thing happens to me.
After the latest update 2.1.0, with "Full-Tunnel" mode I have no connection to the internet (wifi or mobile). 
"Split-Tunnel" works fine.

AdGuard Pro 2.1.0
iPhone 7 on iOS 11.0.3

**Comment by IvanIin** [comment]
@kevandoyle2 @rafuse 
To resolve this issue i need logs from your devices. Please choose "report an issue" -> "contact the support" to send us logs and write your user ids here. Also write a time when such behavior was observed.

**Comment by kevandoyle2** [comment]
My user ID as per the auto reply email: 1860764

**Comment by IvanIin** [comment]
@kevandoyle2 
I did not find not blocked advertising domains in the logs. Could you specify the exact time when the advertisement appears?

**Comment by kevandoyle2** [comment]
It is no advertisement or time in particular. It is just the issue in which the app will stop filtering DNS traffic, even though the module is still toggled on. This is most likely why it does not show up in the logs.

**Comment by X8716e** [comment]
This is eerily similar to the issue I encountered in #748 . I’ve not run into this since the latest β release; it’s unfortunate others are, though it does certainly help in bug squashing. So for that I am grateful you both @kevandoyle2 & @rafuse for running into this.

**Comment by kevandoyle2** [comment]
No problem at all, love the app.

Is there a reasonable eta you might have on a hotfix?

**Comment by zznosar** [comment]
Split Tunnel seems to be fine. The Full Tunnels have some weird issues when jumping to network... Still love the app. But i am in Split Tunnel for the time being since i always jump networks from cellular to wifi and vice versa.

**Comment by kathampy** [comment]
I have the same issue after that last update. Full-Tunnel Mode doesn’t work anymore on 4G. It only works on Wi-Fi. All apps show connection errors.

**Comment by X8716e** [comment]
@kevandoyle2 , I was rereading the various posts & this caught my attention:

> It is no advertisement or time in particular. It is just the issue in which after a while of use the app will stop filtering DNS traffic, even though the module is still toggled on. This is most likely why it does not show up in the logs.

If by “[stopping] filtering DNS traffic” you mean stopping all ad, tracking, etc. blocking, then this does actually differ from my own experience in the two previous releases in one important way. Yes, logging had stopped. My DNSCrypt server connection was interrupted, returning to using my iPhone’s default DNS servers. But never did any of [AdGuard’s](https://github.com/AdguardTeam/AdguardForiOS) blocking capabilities stop functioning.

**Comment by kevandoyle2** [comment]
@X8716e in your case, AG’s functionality remains in tact because either your device or yourself made the switch back to default DNS. I never meant to say there was an issue with AG’s ad blocking capabilities, rather the way it handles the connection to my selected dns server. In my case, when that connection is interrupted (to dnscrypt), it would remain on dnscrypt until I restart the module or manually change dns servers. This is what I meant by stopping the filtering of dns traffic.

As a note, up to now I have only been having that issue with the full tunnel modes, not split tunnel.

**Comment by X8716e** [comment]
@kevandoyle2 , thank-you for the clarification.

**Comment by rafuse** [comment]
> Do you mind signing up for the beta test?

If it helps, I'd be happy to sign up! Where do I have to do this?

**Comment by X8716e** [comment]
Here is the form to use: https://docs.google.com/forms/d/e/1FAIpQLSf5JWqO_Qsdri1nwJphse46Qk48YHVyc3IZs1l-XmJ3ff0dDQ/viewform

**Comment by zebrum** [comment]
Guys! Who of you want to check if the problem was fixed? I need to know your apple_id to add you to a small beta test group. Contact me in Telegram (the same name as here) or write me an email to mg@adguard.com

**Comment by Marco224** [comment]
hi guys, in my case AdGuard beta version 2.1.1 (158) did not solve the problem :(

**Comment by ameshkov** [comment]
Could you please send the logs to `devteam at adguard.com`?

**Comment by Marco224** [comment]
I have sent it, here is the video recording 

https://ufile.io/i7j5j

**Comment by bug-killer** [comment]
[Archive.zip](https://github.com/AdguardTeam/AdguardForiOS/files/2041627/Archive.zip)
The logs from @Marco224

**Comment by zebrum** [comment]
@Marco224 post here a link to the app. Does the problem appear in other apps?

**Comment by Marco224** [comment]
The problem appears in all the apps. It is easy for me to reproduce it, just activate "wifi assistance" in settings-> cellular -> scroll down to the end -> activate "wifi assistance". This setting speeds up the transition between wifi and cellular network, so just go to an area where the wifi has a medium-low signal and use any app that requires internet data in daily use or in the steps between the various menus or pages. (I say this only to make the problem even more evident, actually it appears even if the wifi assistance is off).

the app that I used in the video is Newsify, just a rss reader, but then again, the ads appear in the same way in all the other apps, here the link:
https://itunes.apple.com/us/app/newsify-rss-reader/id510153374?mt=8

**Comment by Marco224** [comment]
Hi guys I’m here again, it seems that the problem is not solved yet, I have tested the same app previously linked and here is the video using the new version 2.1.1 (161) and all privacy module suggestions enable:
https://ufile.io/cifvp

I did a quick test but it seems that as before, the ads appear in all the apps.
I have already sent the log file.
**User ID**: 1148487

**Comment by Marco224** [comment]
Here is another video using google news app where at the end appears the ads. Normally it would be so:
![img_4598](https://user-images.githubusercontent.com/38478493/41169945-ca51ca4c-6b4a-11e8-87ec-52ffb6d4c6db.png)

https://ufile.io/xb1iv

I have sent the log again

**Comment by IvanIin** [comment]
@Marco224  
In the log to the firs video I see that system wide blocking works as it should. You can see the blocked domains in request log(to view it tap on dns requests statistics cell). Perhaps our filter does not contains the necessary domain names. You can try to block domains directly from request log. hello.lqm.io looks like an ads domain, try to block it first.

**Comment by Marco224** [comment]
Tanks to reply, I have add that domain to black list but nothing is change

**Comment by ameshkov** [comment]
Make sure that this domain is now blocked (check the filtering log).

It does seem we're missing some of the ad domains, otherwise it's hard to explain why you see ads.

And one more thing, the ad you see have a small rectangle "ad choices" icon in the corner of the banner. Try tapping on it -- it will show where the ad comes from.

**Comment by Marco224** [comment]
That domain doesn’t appear again in the filtering log... anyhow I did as you said but the domain of advertising already blocked in the log even if I continue to see it. this happens only with a weak connection that leads to the change between wifi and cellular data, not using a stable connection.
![2888030d-5740-4c3c-a5df-a92c9306dd46](https://user-images.githubusercontent.com/38478493/41184432-99dda760-6b80-11e8-86f3-e3dfbe192a3f.jpeg)
![f805691a-01ff-403b-a5dc-ad727ea87c65](https://user-images.githubusercontent.com/38478493/41184433-9a07f1d2-6b80-11e8-9f7c-d466bd4a3fa9.jpeg)

**Comment by ameshkov** [comment]
Hm, weird. Does switching to full tunnel change anything?

**Comment by Marco224** [comment]
in full tunnel with vpn icons also happens sometimes that in the passage to cellular data the internet connection is stopped until you activate and deactivate the airplane mode or connect to the Wi-Fi network.. so it is better without vpn icon for me.
![0ada6363-1531-4eda-b4fb-0aa01b4843d8](https://user-images.githubusercontent.com/38478493/41185109-6805bfde-6b85-11e8-8c88-137355521e62.png)

**Comment by bug-killer** [comment]
[logs.zip](https://github.com/AdguardTeam/AdguardForiOS/files/2086551/logs.zip)
Logs from @Marco224

**Comment by ameshkov** [comment]
@Marco224 one more thing regarding changing between Wi-Fi and Cellular: in the new beta version there's a new flag that lets you disable tunnel restart on a network change. Could you please try it and see if it changes anything?

**Comment by Marco224** [comment]
I did a quick test, but it seems to be perfect right now disabling tunnel restart :)

**Comment by ameshkov** [comment]
@Marco224 that's great news, thank you for testing it!

@IvanIin I guess this might help with the issue @Goddess-Bastet faces in #772.

First of all, let's consider making it the default behavior (again). Second, to mitigate the issue, consider adding a slight delay after the Wi-Fi - Mobile data transition.

**Comment by Marco224** [comment]
It’s just perfect, in all tunnel mode disabling tunnel restart, full tunnel without vpn icon doesn’t show ads during switch anymore and full tunnel with vpn icon doesn’t block internet connection. 

There’s only another little thing I have noticed: the switching between the two full tunnel mode isn’t immediate and need a update filter check in the privacy module to be active instantly.

I only have one question, the disabling tunnel restart can involve something negative?

**Comment by Marco224** [comment]
@ameshkov I do not know if it can help, but in the past I also had the same problem of Goddess-Bastet and I solved with a forced reboot (home + sleep until the apple appears), probably not an error of adguard but it is an error of ios: some recommend a reset of the network settings in case the forced restart does not solve the problem.

**Comment by ameshkov** [comment]
> I only have one question, the disabling tunnel restart can involve something negative?

In theory, it should work just okay.

**Comment by Goddess-Bastet** [comment]
First thing I tried @Marco224 & it didn’t work. 
Afaik the network reset is for WiFi settings but I will try it.

**Comment by Marco224** [comment]
So, forget I said anything... probably mine was due to something different, if I remember it happened after a bad iOS update or a restore of a backup. I know, it was really frustrating for me.

**Comment by Goddess-Bastet** [comment]
It’s good that we’re sharing what is working for us.
I first suspected it was 4G which was the problem as it appeared 3G was fine (when I was in a 3G area) but that wasn’t the case.
For me the problem is intermittent - it can go away for days then return.

**Comment by Marco224** [comment]
@Goddess-Bastet Mmh it is a stranger things... probably in your case I would try to circumscribe the problem with the various gradually deeper reset (network reset etc. ..) always after a backup in the original situation. This always after confirming that it is not a problem related to the new version of AdGuard or some interference with some other vpn configuration. This would take a long time...

Anyway I do not know why but the problem with advertising this morning has returned :( happens the same thing that previously, in the log file advertising appears blocked but is always visible in applications ... this happens however much more rarely than before, as if in some rare times the tunnel is restarted even if the option is deactivated.The ads that appear have the most diverse sources: AppLovin (again as the screen), Amazon-adsystem or appstore app ... I have the various screens but I do not want to clog the thread unnecessarily.

![2363fe2f-3d84-4548-b6ff-e566feef4797](https://user-images.githubusercontent.com/38478493/41200680-d47babae-6ca9-11e8-955b-09111aade9f0.jpeg)
![e6d26454-5789-47f8-8344-66ce3134b4fc](https://user-images.githubusercontent.com/38478493/41200681-d4a7a06a-6ca9-11e8-8a30-26c1ee00711f.jpeg)
![27332876-3ede-4cb8-8f29-6652b72f299d](https://user-images.githubusercontent.com/38478493/41200682-d4c779f8-6ca9-11e8-9b3e-327a91f1c879.jpeg)

**Comment by ameshkov** [comment]
@Goddess-Bastet have you tried disabling the tunnel restart in the AG advanced settings?

**Comment by ameshkov** [comment]
@Marco224 
> Anyway I do not know why but the problem with advertising this morning has returned :(

Is there anything common in the situations when it returns? For instance: network change, device wakeup or smth like this?

**Comment by Marco224** [comment]
now it is much rarer to reproduce it, but as before, it always happens in the transition between wifi and cellular. Is it possible that the tunnel is not 100% stable and does it restart some time during the switch?

**Comment by Goddess-Bastet** [comment]
Yes & so far that seems to work in my case.

**Comment by Marco224** [comment]
I have done some test on iPad, it is very easy to reproduce here... 
here is the video and dns log: https://ufile.io/jous4

**Comment by zebrum** [comment]
How it goes on build .165?

**Comment by Goddess-Bastet** [comment]
Good providing the ‘restart when network changes’ switch is off but as soon as you turn it on everything is blocked again.

**Comment by ameshkov** [comment]
> Good providing the ‘restart when network changes’ switch is off but as soon as you turn it on everything is blocked again.

What matters is that the default switch value is now "off". I doubt we can do anything with how it behaves when it's "on".

**Comment by Marco224** [comment]
In my case nothing has changed, it certainly happens much less than when the switch is on, but the problem is not solved. Ads that are blocked in the log continue to appear.

**Comment by Marco224** [comment]
However now when the switch is off now if imposed full-tunnel with VPN icon at the time of network change the AdGuard vpn no longer starts.
Here is the video: https://ufile.io/2gmdd

**Comment by zebrum** [comment]
Hi @Marco224 ! Why is it 'ipad' on your video in top-left corner instead of the mobile carrier name when wi-fi is turned off?

Also can you record a video of what is happening on settings->general->VPN screen when VPN can't start?

**Comment by zebrum** [comment]
@Marco224 I would appreciate if you catch the moment on video when VPN won't connect after switching from wi-fi to mobile. (settings->general->VPN screen is enough). And logs too apple at adguard.com

**Comment by Marco224** [comment]
I'm not sure what you mean I should do... what should I do on adguard.com? Sorry but my English is very bad... the problem only happens if you load any content that requires an internet connection while you change the connection, so this (the split screen on iPad) is the only way I have to show the settings on the vpn while loading a content. Unfortunately I don't have an iPad with mobile connection and I can't test the WiFi- Mobile data- WiFi step showing the settings on the vpn, and the split screen is not available on iPhone. I hope I have not misunderstood what you meant.
Here is the video: https://ufile.io/1mmzx

**Comment by zebrum** [comment]
@Marco224 ok, I need you to reproduce the problem when filtering stops after switching from wi-fi to mobile and send logs to us, specify the exact time when issue happened.

**Comment by veronikasav** [comment]
User ID 1148487
[Archive.zip](https://github.com/AdguardTeam/AdguardForiOS/files/2117813/Archive.zip)

**Comment by Marco224** [comment]
Hi! I sent yet another log where a different case occurred, in this case the vpn icon has not disappeared but the ads have appeared anyway while I’m on cellular data... in the log the ads are displayed in yellow and no longer in red (AppLovin).🧐

As always I have the screen if you need

It happened at 8:46

**Comment by rafuse** [comment]
Version 2.1.1 with ‚Tunnel restart‘ enabled fixes the issue for me. 
Full Tunnel Mode works fine now, network changes are not a problem anymore.

Thanks!

**Comment by Marco224** [comment]
Hi guys! I'm back here :) I quickly tested the new build (166) and, in my case, I didn't notice any differences when the "Restart when network changes" switch is off: the problem is still there. Ma... I tried to reactivate the switch "Restart when network changes" it seems that the problem disappears both on iPad (WiFi on- WiFi off- WiFi on) and on iPhone (WiFi- cellular- WiFi). Ads that are red in the log are correctly blocked even during connection changes. 🤔 It's strange, but in my case, for now it simply works perfectly when the switch is on. 

In any case, I do not want to rush to conclude; I will update you if I still have any problems. Good job!

**Comment by Marco224** [comment]
Nothing to do, there was only a day after the update that seemed completely disappeared, now the problem always comes up again even with "restart when network changes" activated.  In exactly the same way as before.  I don't know how @rafuse  managed to solve it.

**Comment by zebrum** [comment]
@Marco224 there is one more guess about wi-fi assist option enabled. Can you try to disable it?

**Comment by Marco224** [comment]
I will try with the option disabled.  I already tested AdGuard 2.1.1 with WiFi assistant disabled and it didn't change anything.  I will let you know, although it does not seem a solution to the problem deactivate a useful system function

**Comment by Marco224** [comment]
I confirm that nothing changes, the only thing that changes is the distance from the wifi where the problem occurs, where the connection speed is obviously slower because it insists on using the wifi connection too weak because of the distance

**Comment by ameshkov** [comment]
Guys, bad news:
https://adguard.com/en/blog/adguard-pro-discontinued/

**Comment by drlivesey** [comment]
@ameshkov It is quite possible that renaming the app will help. Let's call it DnsGuard ;)
This way it will totally "use APIs and frameworks for their intended purposes..."
You developed a very nice and unique product! I hope you will be able to save it.
