### ISSUE TITLE
Bug report -  Adguard Pro 2.1.0(153)

### ISSUE THREAD

**Issue by accountforadg** [AdguardTeam/AdguardForiOS#773]
## i use this app (https://itunes.apple.com/us/app/adblock/id691121579?mt=8) to subscribe easylistChina
![photo_2018-05-10_23-27-37](https://user-images.githubusercontent.com/39081420/39877936-bcddb914-54a9-11e8-99e3-828851319351.jpg)
## and go to visit this site https://m.miaobige.com/ 
![photo_2018-05-10_23-29-38](https://user-images.githubusercontent.com/39081420/39878101-1b7535d8-54aa-11e8-950a-d0f0ee70cbb8.jpg)
## **and i swtich to Adguard Pro 2.1.0(153)  , subscribe easylistChina**
![39769447-cd8bf636-531e-11e8-8e70-05deb9e6172b](https://user-images.githubusercontent.com/39081420/39878313-9f186f04-54aa-11e8-86bd-d3ed9dc820dc.png)
##  and go to visit this site https://m.miaobige.com/ 
![68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f37596339794b472e6a7067](https://user-images.githubusercontent.com/39081420/39878334-a912a628-54aa-11e8-8a23-30857192dfbe.jpg)

## you can see the different  
  #   This problem is not caused by easylichina. It is caused by adguard ios.

**Comment by accountforadg** [comment]
@AdamWr  hi,Adam

**Comment by accountforadg** [comment]
The same rule shows different results in both softwares, and the result of adguard is wrong.

**Comment by accountforadg** [comment]
@zebrum What data do you need from me?

**Comment by zebrum** [comment]
@accountforadg have you try the rule or not? It still seems to be filters problem.

**Comment by accountforadg** [comment]
@zebrum @@||img.miaobige.com^$script,domain=miaobige
Added,but does'nt work

**Comment by ToniKumpula** [comment]
@accountforadg

Have you tried to uncheck default China EasyList in the Adblock app and manually adding it via Add Subscription?

Here’s the list you need to add:

https://easylist-downloads.adblockplus.org/easylistchina.txt

Just copy the link and open up Adblock app and then hit Add Subscription button to manually add it, then test that website again.
