### ISSUE TITLE
Checking for filters updates in AdGuard 2.1.0.153 blocks internet connections

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#774]
> Every time I go to update the filters and the Privacy setting subscription updates it disconnects and tries to reconnect over and over. The only solution is if I turn off WiFi - turn off Adguard Pro Status - turn on airplane mode - turn it back on- turn WiFi on and then open Adguard Pro and enable Privacy Status then go to privacy settings and click update subscriptions and then it connects. FYI - I also use a VPN (Torguard) which I never had a problem before. I also have several other VPNs and I get the same problem

### Steps to reproduce

1. Install AdGuard 2.1.0.153 on iOS 11.3.1
2. Go to the Privacy > Check for updates 
3. In some cases, you can't access the internet after that
4. Using the workaround outlined above fixes the issue for some time

### Expected behavior

AdGuard does not interrupt the connection

### Actual behavior

It blocks connections in some cases for some users

### Your environment
1598535 with screen recordings and iOS console logs @zebrum 

* Device model and storage size: 
* Operating system and version: iOS 11.3.1
* Browser (e.g. Safari) n/a
* Wi-fi or mobile internet connection Wi-Fi

**Comment by SirBrindle** [comment]
Has anyone else experienced this issue? Adguard Pro for iOS works fine but when I go to update the Privacy Subscription filters it has issues connecting/reconnecting non-stop.

**Comment by IvanIin** [comment]
I see in logs that too many subscriptions are used and the tunnel crashes due to memory limit is exceeded. You must use fewer blocking subscriptions.
