### ISSUE TITLE
[NSFW] Safe Search does not work with AdGuard Family protection DNS

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#775]
I made it work once but than I couldn't. Here's the screen recording: https://uploads.adguard.com/8zvth.MP4

### Expected behavior

Users can't search for adult content when AdGurd Family Protection DNS is being used

### Actual behavior

The actual can

### Customer ID 
me

### Your environment

* Device model and storage size: iPhone SE 16Gb
* Operating system and version: 11.3.1
* Browser (e.g. Safari) Safari
* Wi-fi or mobile internet connection: both
* AdGuard 2.1.0 (153) with AdGuard SDN subscription and AdGuard FP DNS enabled
* Other VPN apps: no
* VPN mode: full tunnel with no icon

**Comment by zebrum** [comment]
It seems that it is disabled on our side. Will be fixed.
