### ISSUE TITLE
AdGuard in the full-tunnel mode (with VPN) interferes with FaceTime 

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#778]
Works in other modes, similar bug: https://github.com/AdguardTeam/AdguardForiOS/issues/501

### Steps to reproduce

1. Go to AdGuard > Advanced and set the full-tunnel mode with VPN
2. Go to FaceTime and call someone
3. You'll get the error message while on another person's end it'll stuck in "connecting"

### Expected behavior

Users are able to make calls on FaceTime

### Actual behavior

The can't, see the screenshots below

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/39967513-25c2371c-56c5-11e8-9399-39d2cbc3e791.png)

![image](https://user-images.githubusercontent.com/15856304/39967507-158997f0-56c5-11e8-8106-2c6c7214e296.png)

</details>

### Your environment

* Device model and storage size: SE 16Gb
* Operating system and version: 11.3.1
* Browser (e.g. Safari) n/a

**Comment by X8716e** [comment]
From what is vidible in your screenshot, this is in essence the issue people have been experiencing using either of the two full tunnel modes while on a cellular connection. Is the Full-Tunnel with VPN icon the only mode in which Face Time fails? Or does it also fail using the ‘standard’ Full-Tunnel mode?

**Comment by zebrum** [comment]
@Eugene-Savenko by design. 
users need to use the second full-tunnel without the icon unstable mode.

**Comment by X8716e** [comment]
@bigdargon , I realize you’ve directed your question to Andrey & Ivanlin; however, here’s the answer that Marie has already given: 

> by design.
users need to use the second full-tunnel without the icon unstable mode.

There is also a **`Wontfix`** label applied to the (non)issue.
I hope this helps in your understanding.
