### ISSUE TITLE
VPN connection failure on all types of network connections

### ISSUE THREAD

**Issue by kclejeune** [AdguardTeam/AdguardForiOS#779]
### Steps to reproduce

1. Install AdGuard Pro
2. Connect DNS
3. Open Settings->VPN
4. VPN will attempt to connect and fail repeatedly.

### Expected behavior

Enabling DNS protection should result in a VPN connection.
### Actual behavior

**This works for a limited amount of time after reinstalling the app, and then proceeds to fail again.**
VPN fails to connect repeatedly using all 3 VPN modes, regardless of network type (tested on both cellular network and wifi).  

<details><summary>Screenshot:</summary>

https://imgur.com/a/qEpdsio
</details>

### Customer ID 

1870724
### Your environment

* Device model and storage size: (e.g. iPhone 6s 64gb)
iPhone 7+
* Operating system and version: (e.g. 10.3.1)
iOS 11.3, AdguardPro version 2.1.0(153)
* Browser (e.g. Safari)
N/A
* Wi-fi or mobile internet connection
Issue repeatable using both

**Comment by zebrum** [comment]
@kclejeune so, what's your customer_id? did you send logs to support?

**Comment by kclejeune** [comment]
I sent the logs but never got an email - should I just try again?

**Comment by kclejeune** [comment]
Added customer ID

**Comment by bug-killer** [comment]
Additional comment: The general issue is the vpn trying to connect and failing repeatedly on
all networks and in all 3 vpn modes.

**Comment by IvanIin** [comment]
@kclejeune 
You use too many blocking rules. AdGuard tunnel closes due to memory limitation. You can solve the problem by setting up fewer subscriptions in Privacy Settings.

**Comment by kclejeune** [comment]
Is there a specific number where this starts to happen?  I ask just because most decent lists have 30-40k hosts.
