### ISSUE TITLE
Add "Requirements" section to README.md

### ISSUE THREAD

**Issue by xxcriticxx** [AdguardTeam/AdguardForiOS#78]
what are the cpu requirements for this app? will this work on non 64bit cpu (older iphone/ipad)?

should this be in some kind of wiki or sticky?

**Comment by ameshkov** [comment]
> what are the cpu requirements for this app? will this work on non 64bit cpu (older iphone/ipad)?

Nope, the app uses content blocking API which is available for 64bit only.

> should this be in some kind of wiki or sticky?

Yep, it should. We'll add "Requirements" section to readme.md.

**Comment by xxcriticxx** [comment]
big thank you

**Comment by vbagirov** [comment]
Done.
