### ISSUE TITLE
How does the DNS setting of AdGuard Pro actually work?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#784]
Well, I reported a DNS resolution issue to Cloudflare.
https://community.cloudflare.com/t/unable-to-open-the-train-timetable-information-of-taiwan-railways-website-with-cloudflare-dns/18631

With Cloudflare DNS, I’m unable to visit the train timetable information of Taiwan Railways website.
http://twtraffic.tra.gov.tw/twrail

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/xpwePHn.png)
</details><br/>

If directly and manually configure Cloudflare DNS 1.1.1.1 and 1.0.0.1 in Wi-Fi setting, I'm unable to visit the train timetable information of Taiwan Railways website.

With Cloudflare DNS via AdGuard for Android, I got the same issue.

But why could I visit that website with Cloudflare DNS via AdGuard Pro for iOS? (Auto DNS configuration in Wi-Fi setting of iOS setting)

How does the DNS setting of AdGuard Pro actually work?
Does it actually not only connect to the DNS servers which we chose?
I mean that there are other DNS resolvers which work in the background even if choosing specific DNS service, right?
Otherwise, why can it still resolve a domain to correct ip?
(In my case, now Cloudflare DNS is unable to resolve twtraffic.tra.gov.tw.)

Thanks.

**Comment by lancelot-moon** [comment]
I just have checked.

If using auto DNS setting in Wi-Fi setting with Cloudflare DNS via AG Pro, I’m able to visit that website.
Except for specific DNS by user in AG pro, it seems that system default DNS service also works in the background.
That’why it still can correctly resolve the domain.

If first manually configuring Cloudflare DNS in Wi-Fi setting with Cloudflare DNS via AG Pro, I’m unable to visit that website.

**Comment by s-s** [comment]
iOS fallbacks to system resolver when app's one fails.

**Comment by lancelot-moon** [comment]
Ok, thanks for the answer!
iOS system does well in the aspect.
