### ISSUE TITLE
After enabling EasyList China and then checking for update, it shows the error, "Filters cannot be loaded into Safari...".

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#785]
The issue didn't occur several days ago.
But it suddenly happened recently.
I intentionally disabled English filter for decreasing the amount of rules (22k rules).
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/eVvkJIh.png)
</details><br/>

However, it would show the error as long as I enabled EasyList China and then checked for update.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/o8mEuyp.png)
</details><br/>

If I only disabled EasyList China, there was no the error.
It could successfully update filters for Safari.

B/R

**Comment by ameshkov** [comment]
@Alex-302 plz take care

**Comment by ameshkov** [comment]
Moving to the Filters repo

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardFilters #16648](https://github.com/AdguardTeam/AdguardFilters/issues/16648) via [**ZenHub**](https://www.zenhub.com/)
