### ISSUE TITLE
Create a new filter with rules which are unsuitable for all users. And let the new filter in popular subscription list.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#787]
@ameshkov 

Dear Sir,

For iOS, AdGuard Pro only can do DNS filtering for system-wide ad blocking.
Although some rules in SDN filter may break the websites or apps, AdGuard team still don't want to delete them from SDN filter due to the protection of security or privacy from tracking.

**However, most of common users don't know how to make rules for solving the broken websites or apps.**
If asking AdGuard team to delete the rules or whitelist them, AdGuard team also don't want to do so.
Those whitelisted domains are only suitable in the user side, not suitable in official public filters for all users.
May you create a new filter with rules which are only suitable for the user himself but unsuitable for all user and let the new filter in popular subscription list?

Ex:
The rule, ||google-analytics.com^, in SDN filter blocks www.google-analytics.com/analytics.js, which breaks [Line Today](https://today.line.me) on mobile devices.
Unable to read news on Line Today (on mobile website and in Line app).
AdGuard team can still block ssl.google.analytics.com.
I just want the rule, @@||www.google-analytics.com^.
But there are maybe other trackers under www.google-analytics.com, not only analytics.js.
So AdGuard team don't allow the rule, @@||www.google-analytics.com^, in SDN filter.
Unblocking www.google-analytics.com is only suitable in the user side, not in the public side.

**A default new filter for DNS filtering for only personal use is my idea.
And let the new filter in popular subscription list.**
I think this kind of rules should be not many.
So there is simple description for every rule in the new filter.
Let users have the ability to directly open and review the content in the filter from AdGuard app.

Filter name:
Unblock filter

Filter description:
The rules in unblock filter are only suitable for personal use, not for public use.
It may solve the broken websites or apps, but lower your security or privacy.
If using the unblock filter, please take your own risks!

Rule:
@@||www.google-analytics.com^

Rule description:
Solution for broken Line Today on mobile website and in Line app...etc.

B/R

**Comment by zebrum** [comment]
obsolete
