### ISSUE TITLE
After stopping private I do not have a internetconnection

### ISSUE THREAD

**Issue by Cees8** [AdguardTeam/AdguardForiOS#789]
Privacy mode gives a VPN and I can’t use my VPN by AVM to my Fritzbox router.
But disabeling Private-mode disconnects my internet totally.
Since your last update (9 may) AdguardPro can’t hold the connection, so once a day or 2, I must reconnect to internet by renewing the VPN-connection.
iPadair2, iPhone SE, iPadmini4, all on latest iOS 11.3.1 reacting the same.
Fritzbox 7490, software  fritzOS 6.98 (beta)
DNS : DNSCRYPT.EU. Changing to not crypt no difference.

### Steps to reproduce

1.Privacy on: VPN sign on, internet.
2.Privacy off: no VPNsign, no internet.
3.only changing in General, VPN, Connection gives VPN through Adgaurd back: internet working.
4.

### Expected behavior
Privacy off: I can use my own VPN (and of course internet-use)

### Actual behavior

No internetconnection

<details><summary>Screenshot:</summary>
Blanco, VPNserver does’t react (of course, no internetconnection

</details>

### Your environment
<!--- Please include all relevant details about the environment you experienced the bug in --
iPadAir2 11
* safari
* Wi-fi
Mobile 4G works good: Privacy off and I can use my own VPN

**Comment by zebrum** [comment]
@Cees8 both wi-fi and mobile connection?

**Comment by Cees8** [comment]
Found the culprit I think.
Changing the DNSserver in my router back to the provider Ziggo:
Internet back on Privacy off and my VPN working again.
Just tried the Adguard DNS 176.103.130.130 also working great!
Wonder how it worked the last months, but for now: great!

Thanks, Luc Kalishoek

**Comment by Cees8** [comment]
Well, I found out what was not working: the DNSserveradress in the router was not allright.
Changing it in Adguard 176.103.130.130 and all was working again as normal!
Mystery why it worked till recently, but happy it wasn’t Adguard!
Thanks
