### ISSUE TITLE
Blocking all picture and video in ensonhaber.com 

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardForiOS#790]
I use AdGuard pro in my iphone, and update periodically.
But i use a website for news.
The filters is blocking all picture and video in this website 

Example:
https://m.sondakika.com/haber/haber-eli-ayagi-baglanan-doktora-gasp-iddiasi-10900636/

### Steps to reproduce

1. https://m.sondakika.com/haber/haber-eli-ayagi-baglanan-doktora-gasp-iddiasi-10900636/
2. https://m.sondakika.com/haber/haber-fenerbahce-josef-de-souza-teklifini-reddetti-12-10901262/

MY FILTERS:
English Filter, 
Spyware Filter, 
Social Media Filter, 
Turkish Filter, 
Mobile Ads Filter, 
Safari Filter

### Expected behavior

Without filters, i can see videos and pictures on a page of websites.
1. https://i.hizliresim.com/b64v0V.jpg

### Actual behavior

With filters, i can’t all except text.
1. https://i.hizliresim.com/RD6gvj.jpg

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Device model and storage size: iPhone 6s 64gb
* Operating system and version: 11.3
* Browser: Safari
* Wi-fi or mobile internet connection: both (i tried both of theö, the results are same.)

**Comment by PentagramTr** [comment]
@tagataho 
Konuyu yanlış bölüme açmışsın.Bu konunun "AdGuard Filters" bölümüne açılması gerek.
https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by tagataho** [comment]
ios işletim sistemle bir cihazda iphone’da bu sorunu alıyorum @PentagramTr

**Comment by PentagramTr** [comment]
@tagataho 
Bu bölüm AdGuard programı ile ilgili sorunları bildirmek için.Sizin sorununuz filtrelerle ilgili.Filtre içindeki bir kural yanlış engellemeye sebep olduğu için bu sorun oluşmuş.

Nasıl sorun ve reklam raporlanır basitçe anlatayım.
İlk önce "ensonhaber.com" sitesi açıkken Safari paylaş butonuna tıklayın ve  ardından AdGuard Pro uzantısına tıklayın.Açılan pencereden "Bu sitede bir sorun bildir" başlığına tıklayın.(Açılan websitesinin adı aslında Raporlama Aracı)Alt ekran görüntüsüne bakın.

<details><summary>Screenshot</summary>

![picsew_6435](https://user-images.githubusercontent.com/34379403/40852795-63eed130-65d4-11e8-8db6-a873f6a1cad2.PNG)



</details><br/>

Karşınıza çıkan websitesi zaten bilgilerin çoğunu otomatik dolduracak.Size sadece ekran görüntüsü eklemek kalıyor.Ve yorum bölümüne istediğinizi yazın.Gönderdikten sonra o rapor AdGuard Filters bölümüne sorun olarak gidecek.

Bundan sonra bu tip reklam raporlarını buraya değilde,yukarıda anlattığım yöntemle bildirin lütfen.Şu an bu açtığınız konuyu "Close" butonununa basarak kapatın.Gerek yok artık.

**Comment by zebrum** [comment]
@tagataho It seems like filters problem. Try to disable all filters and check if it helps. After that turn on one by one so you could find the culprit.

**Comment by PentagramTr** [comment]
@zebrum 
Hi,
Please close this issue because the problem is solved.#17373
Thanks.

**Comment by PentagramTr** [comment]
@zebrum 
Hi,
Please close this issue because the problem is solved.
AdguardTeam/AdguardFilters#17373
Thanks.
