### ISSUE TITLE
Feature: option to input our github username in adguard

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#791]
When we want to report a website. We can fill our github username. It’s better for the devs. Because the user can interact with them. But right now we have to type it every time. 

Would like to see an option in adguard where we can fill in our github username. 

When we report an issue, the github username automatically gets inserted.

**Comment by zebrum** [comment]
oh, I found it: https://github.com/AdguardTeam/ReportsWebApp/issues/141
