### ISSUE TITLE
New DomainVoider home

### ISSUE THREAD

**Issue by analogbuffalo** [AdguardTeam/AdguardForiOS#792]
Apologies for opening this as an issue, though knowing people use the subscriptions provided by DomainVoider, it lives on GitLab.

https://gitlab.com/intr0/DomainVoider/raw/master/MainVOID.txt

https://gitlab.com/intr0/DomainVoider/raw/master/modVOID.txt

https://gitlab.com/intr0/DomainVoider

Thank-you from intr0

👍

**Comment by lancelot-moon** [comment]
Those filters include advanced adblock rule syntax.
AG Pro only does DNS filtering for system-wide ad blocking and doesn't support those rules for HTTPS filtering.
The subscription of AG Pro only supports the format of domains, hosts file and basic adblock rule syntax.

**Comment by analogbuffalo** [comment]
> Those filters include advanced adblock rule syntax.
AG Pro only does DNS filtering for system-wide ad blocking and doesn't support those rules for HTTPS filtering.
The subscription of AG Pro only supports the format of domains, hosts file and basic adblock rule syntax.
Those filters can be used for future AdGuard for Android v3, not for the subscription of AdGuard Pro for iOS.
Otherwise, they can be in Safari Content Blocker.

You’re most welcome to your opinion. Allow me, however, to state these facts:

1. “Those filters” were hosted on GitHub for well over a year; not once did you seem
to take notice, even though you might have easily viewed them by having a look at  my account any one of the numerous times I conversed with you. Note: I removed my DomainVoider account from GitHub the day Microsoft finalised their takeover of GitHub.
2. “Those filters” are tested only on iOS and they work quite well, actually, regardless of your dislike of the person who creates “those filters”. From everything I’ve witnessed here, you seem to have a ‘holier than thou’ attitude no matter to whom you are ‘speaking’.
3. “[T]hose rules for HTTPS filtering” would apply to the most basic `||thosefilters.*^` rules, so that fact alone reveals that “those rules” _do work_.
4. Most importantly, “those filters” are used by many persons with whom correspondence via email occurs. The two types of email I receive most are those of gratitude for my work and appreciation “those filters” work.
5. I find your comment not only unnecessary but rude. And though stated in the past by your daughter that you should be ignored for you know not how to communicate via English in a manner that would not seem thus, this particular post of yours begged a response. And so I give it.

Sincerely,
@analogbuffalo aka intr0
#microsoftkillsfreedom

**Comment by lancelot-moon** [comment]
You're just a rude guy who doesn't wish the fact and intentionally contorts my character.
I'm not aimed at anyone.
I also didn't say that I dislike the person who creates “those filters”.
You're purely slandering on me.
Simply, what you provided is not correct for the subscription of AG Pro for iOS.

https://github.com/AdguardTeam/AdguardForiOS/issues/741#issuecomment-379197442

AdGuard team already gave the answer!

In those filters, there are many rule syntax which are not supported by AG Pro for iOS.
ex:
||assets.htvapps.com/lumiere/fallback/analytics.js
||assets.jumpstartmediavault.com/abd/v2/jam_abd.min.js
||assets.jumpstartmediavault.com/abd/v2/jam_abd_nag.min.js

and other many unsupported rules for the subscription of AG Pro for iOS.
For those rules for HTTPS filtering, we only want to block something under the general domain and don't block the whole domain.

In my previous reply, I only talked about things, not people.
But you are slandering on me in your reply.
You should learn to modestly face the fact and not attack people.

**Comment by ameshkov** [comment]
Removed the off-topic. Guys, please be civilized, there is absolutely no need for such a heat.

@analogbuffalo I suggest you use a very simple python script we use to build the SDN filter:
https://github.com/AdguardTeam/AdguardDNS/blob/master/Filters/parser.py

The point is that it will remove cosmetic rules which anyway cannot be applied on the DNS level and make the filter smaller.

**Comment by ameshkov** [comment]
> Then they were placed back due to a few user requests who insist they do refine the appearance of webpages (not everyone uses Safari) as well as within other Apps they use.

Got it. Makes sense if they use the filter lists in a non-iOS ad blocker or import them into the user filter in AG.

> It’s sure quite easier to not use them

Mm, tbf I don't remember if we filter them out or load into memory. I'll check the code.

> I do have a question regarding a private matter so please be on the lookout for an email from the same address used for the old GitHub repo. Thank-you.

Sure, feel free to contact me.
