### ISSUE TITLE
Add a light UI theme

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForiOS#795]
Can we please get the white theme back? I know a lot love the dark theme. But believe me, a lot love the white theme. It would be nice if we could choose in settings. 

Or two fingers swipe down will change to dark. And two finger swipe up will change to white. Tweetbot app does that.

**Comment by ameshkov** [comment]
It won't be simple, I'll mark this as a feature request for now.

**Comment by worldsdream** [comment]
This was implemented and working great.
