### ISSUE TITLE
QUESTION regarding recent blog article about setting up your own proxy with DNS-Crypt

### ISSUE THREAD

**Issue by SirBrindle** [AdguardTeam/AdguardForiOS#797]
Am I able to set up DNS-Crypt as well while I follow the instructions
on the more recent article about using Vultr or others?

I read and followed the steps on:
https://adguard.com/en/blog/configure-proxy/

But I also read this on DNS-Crypt:
https://github.com/jedisct1/dnscrypt-proxy/wiki/DNSCrypt-server-with-vultr.com

So basically my question is am I able to kill two birds with one stone or
do I need to sign up for two servers to accomplish this?

Additionally, in the article AG posted they mentioned a follow up article
about using shadowsocks but have not found much information about it - if
you can elaborate more on that or guide me to where I can learn more about
it I would greatly appreciate it, keep up the great work and hope to hear
back soon.

Big Thanks!

**Comment by ameshkov** [comment]
> So basically my question is am I able to kill two birds with one stone or
> do I need to sign up for two servers to accomplish this?

Sure, you can have several server apps on a single server.

> about using shadowsocks but have not found much information about it - if
> you can elaborate more on that or guide me to where I can learn more about
> it I would greatly appreciate it, keep up the great work and hope to hear

Shadowsocks is basically a secure alternative to regular proxy servers:
https://shadowsocks.org/

The difference is that in the case of a regular proxy, it is possible to sniff what IPs and domains you connect to. This is not possible with shadowsocks.
