### ISSUE TITLE
Action extension dialog window is too small on iPad

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#80]
Why is that so?

**Comment by Stillness-2** [comment]
@ameshkov It's an optical illusion.:)

This is current implementation.
![img_0001](https://cloud.githubusercontent.com/assets/12689/15015177/60877ede-121b-11e6-9367-cd62a9c0fb7d.PNG)
I increased the distance between the icons. Also the size of the icons close to the size of system icons.

**Comment by ameshkov** [comment]
Hm, ok, let's use it for now.
