### ISSUE TITLE
Sound is silenced when using Carplay playback with privacy status turned on.

### ISSUE THREAD

**Issue by kpryor98** [AdguardTeam/AdguardForiOS#800]
I can literally toggle the sound on and off in my car and the playback continues just by toggling the status. 

I am currently on 11.4 on iPhone X

**Comment by zebrum** [comment]
related #802 I guess.  
@kpryor98 What tunnel mode do you use in AdGuard settings?

**Comment by zebrum** [comment]
closed as dup
