### ISSUE TITLE
System wide filters being reset

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#801]
https://youtu.be/vNp4Cxg44rw

Invalid ad blocking ever happened in the old version of AG Pro.
I met the issue again in AG Pro v2.1.1(165).

From the video, you can see that banner ads and pop-ups in the newspaper app were not blocked.
I checked DNS Requests Log.
Those domains in subscriptions showed "yellow" or "white" in DNS Requests Log.
Ex:
doubleclick.net
tktracker.aotter.net
tkmftc.aotter.net
flurry.com
They're in SDN filter, but they were not blocked.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/THekwKM.png)

![image](https://i.imgur.com/k8l0fFE.png)
</details><br/>

In DNS Requests Log, only domains in the blacklist would be noted by "red".
Ex:
I added graph.facebook.com in my blacklist.
graph.facebook.com was noted by red in DNS Requests Log.
But I tried to visit facebook.
It seems that browsing facebook was still normal even if blocking graph.facebook.com.
I was not sure if the blacklist really worked at that time.

Changing another DNS server in AG Pro or rebooting iPhone was unable to recover ad blocking.
Finally, after I clicked "Check for updates" for subscriptions, ad blocking was back.
(The situation is a little different with what I met before.
In the past, when I met invalid ad blocking, I tried to ever use real VPN (connect to real VPN once) for letting AG Pro's ad blocking back.
But this method was useless this time.)

When ad blocking of AG Pro was invalid, Disconnect Premium's ad blocking could normally work.
https://itunes.apple.com/us/app/disconnect-best-blocking-award/id935480186?ls=1&mt=8

I already sent the bug report to AdGuard Support at 19:42 on 24th June (GMT+8).
User ID: 1425202
Subject: [AdGuard Pro for iOS] 程式錯誤報告 (bug report)

iPhone 6 Plus
iOS v11.4
AG Pro v2.1.1(165), split VPN tunnel + general DNS server

Sorry that I don't have 100% reproduction steps.
I only can describe the process.
I idled my iPhone (no sim card) for several hours.
And then I enabled AG Pro's protection on iPhone but I found that I forgot to open Wi-Fi hotspot from my Android phone.
So I disabled AG Pro's protection.
After iPhone connected to the Wi-Fi hotspot from my Android phone, I enabled AG Pro's protection and found that ad blocking was invalid.

B/R

**Comment by Marco224** [comment]
Try to deactivate “tunnel restart” in advance settings. In my case it reduces the frequency of the problem even if it does not solve it.

**Comment by lancelot-moon** [comment]
Hi,
The invalid ad blocking isn't solved in beta v2.1.2(166).
**Even it becomes stranger because it seems that DNS Request Log doesn't catch all DNS requests.**

Please watch the video.
https://youtu.be/FghtSvqrSso

I tried the app.
In the past, I let AdGuard team add rules in filters for blocking ads in app.
https://github.com/AdguardTeam/AdguardFilters/issues/13171

But banner ads and pop-ups in the app were not blocked.

Before enabling AG Pro VPN, I deleted a domain from the blacklist.
After enabling AG Pro VPN, I found that ad blocking was invalid, and **a lack of DNS requests in DNS Requests Log**.

I already sent the bug report to AdGuard Support at 15:33 on 28th June (GMT+8).
User ID: 1425202
Subject: [AdGuard Pro for iOS] 程式錯誤報告 (bug report)

B/R

**Comment by lancelot-moon** [comment]
Why did "system wide filters being reset" cause a lack of DNS requests in DNS Requests Log?

Or the modified title only explains about invalid ad blocking, right?

Thanks.

**Comment by lancelot-moon** [comment]
I idled my iPhone.
I removed a domain from the blacklist and then enabled AG Pro VPN.
Invalid adblock and a lack of DNS requests in DNS Requests Log appear in beta v2.1.2(167).

The same bug with beta v2.1.2(166).


https://youtu.be/ua964FaqmpM

I already sent the bug report to AdGuard Support at 13:12 on 4th July (GMT+8).
User ID: 1425202
Subject: [AdGuard Pro for iOS] 程式錯誤報告 (bug report)

**Comment by lancelot-moon** [comment]
@ameshkov 

I just did some interesting experiments when the bug which was caused by AG Pro occurred.
Please watch the video.
https://youtu.be/ieyJL8Mdtxg

1. When the bug which was caused by AG Pro occurred, adblock was still invalid even if I manually set AdGuard DNS as the system DNS. (only Wi-Fi, no cellular network)

Disconnect Premium provides local VPN mode or real VPN mode with simple adblock.
2. With Disconnect Premium's local VPN, adblock was still invalid.

3. With Disconnect Premium's real VPN, adblock was recovered.

AG Pro caused the bug, even changing system DNS is useless.
The abnormal situation would be latched & continued.
Only ever connecting to real VPN can dissolve the abnormal situation.

**Comment by zebrum** [comment]
@lancelot-moon 

> Why did "system wide filters being reset" cause a lack of DNS requests in DNS Requests Log?

when there is an update of the subscriptions in the background mode while the internet connection is absent - they all being reset. 

In your logs there is another problem: all requests are bypassed AdGuard in split mode
It may be related to #771 #772 tasks.

@IvanIin will check your logs and I'll create a new task if necessary.
