### ISSUE TITLE
CarPlay crash

### ISSUE THREAD

**Issue by richgoga** [AdguardTeam/AdguardForiOS#802]
Using latest AdGuard Pro on iPhone X
Split Tunnel AdGuard default activated. 
CarPlay will crash completely when phone switches from home WiFi to 4G... ie when driving away from home. 
CarPlay DOES NOT crash if WiFi is toggled off before starting off. 
CarPlay does not crash when switching from 4G to WiFi... ie when returning home
CarPlay does not crash if AdGuard is disabled.

**Comment by zebrum** [comment]
@richgoga hi! please reproduce the issue and send logs right away to support team (AdGuard main menu - Report an issue - Contact support). In your email specify the time when issue happened.
You will get an auto reply letter with your ticket_id from support team, post it here so we could find your logs. 
Also have you try it in full tunnel mode?

**Comment by richgoga** [comment]
Hi, thanks for the quick reply!

I’m working at the moment (UK time), so will reproduce ASAP.

**Comment by zebrum** [comment]
@richgoga no problem
There is one more thing you can try to to toggle on (or off) this new option 'Restart when network changes' in Advanced settings.

**Comment by richgoga** [comment]
Sorry for the delay. 
I have just submitted logs, id 1918906
This was in split tunnel mode with the ‘restart when network changes’ toggle On

**Comment by richgoga** [comment]
Further logs just submitted, same ID number. 
This time I had AdGuard disabled. CarPlay didn’t crash when switching from WiFi to 4G.

**Comment by Eugene-Savenko** [comment]
@zebrum could you please look into this? thanks!

**Comment by richgoga** [comment]
Further logs submitted Full Tunnel on. Still crashes.

**Comment by zebrum** [comment]
@richgoga when exactly the app started crashing? Was there any update? How did it work with previous AdGuard version?

it looks similar to #164 judging by logs so I'll try to reproduce it.

**Comment by zebrum** [comment]
@richgoga 

1. is wi-fi assist enabled in settings on your device? If so can you try to disable it?
2. do you have any other VPN app to check the problem with it? TunnelBear for example, it has some free traffic.
3. there is a possibility the problem is not on our side and you need to report it to CarPlay. Can you do that too?

**Comment by richgoga** [comment]
1.) Still crashed with WiFi assist off. 
2.) I don’t use other VPNs
3.) I’ve logged with Apple support, but seeing as crashes only occur with AdGuard enabled, it’s very unlikely that the issue is with CarPlay

**Comment by zebrum** [comment]
> it’s very unlikely that the issue is with CarPlay

How can you tell that if you don't use other VPN? :)

Well, I did quick research and indeed CarPlay has some troubles with different VPN apps, not only with AdGuard.

@IvanIin any thoughts?

**Comment by ameshkov** [comment]
:(
https://adguard.com/en/blog/adguard-pro-discontinued/
