### ISSUE TITLE
Does "Auto Update over Wi-Fi only" work for subscriptions in privacy settings?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#804]
I remembered "Auto Update over Wi-Fi only" also includes subscriptions in privacy settings:
https://github.com/AdguardTeam/AdguardForiOS/issues/682

But I never see that subscriptions are auto updated over Wi-Fi.
The last time of "Check for updates" is never changed if not manually updating my subscriptions.
Every time, I must manually update my subscriptions.
May you check it?

Thanks.

**Comment by zebrum** [comment]
It should be ok on the latest beta.

please, reopen if needed
