### ISSUE TITLE
Future outlook.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#807]
I don't know if AdGuard team plan to provide real VPN in the future.

https://block.blokada.org/post/2018/04/09/vpn-vote-results/
Honestly, although I have several VPN providers' lifetime licenses, I don't often use real VPN because of slower internet speed.
Even if the VPN server's internet speed is not bad, I still don't often use.
I use VPN when I wish foreign IP.
However, the speed of nearer location's servers is better, so I mind if it provides Taiwan & Japan VPN servers.

After all, maintaining real VPN servers around the world maybe needs to afford a lot of expense...
I don't know if the market of VPN is mature.
That's what AdGuard team should seriously consider.

Just outlook.
Real VPN with adblock can be additional paid service.
1. Can it do HTTPS filtering on real VPN servers?
Especially, it can't do HTTPS filtering for system wide ad blocking on local iOS devices.
2. Data compression via real VPN servers.
After filtering ads, do data compression on server side.
3. Please give local VPN mode and real VPN mode in AdGuard app such as Disconnect Premium app.
Well, it can be called AdGuard Premium.
VPN is illegal in some countries.
Keep AdGuard Pro for them.
AdGuard Premium for worldwide.
Disconnect Pro: only local VPN with filters.
Disconnect Premium: Real VPN or local VPN with filters.
4. Provide Taiwan & Japan VPN servers. XDD Please don't mind.

(Interesting vote results:
Most of the results are in what I expected.
https://block.blokada.org/post/2018/06/15/features-vote-results/
I also ever suggested AdGuard team to give DNS speed test tool in AdGuard app.)

**Comment by zebrum** [comment]
@lancelot-moon we don't have plans about VPN service.
