### ISSUE TITLE
AdGuard 2.1.1 does not reflect changes when enabling Simplified filters

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#810]
It shows almost the same number of active rules with and without "Use Simplified Filters" option.

### Steps to reproduce

1. Go to AdGaurd > Filters, see the number of active filters
2. Go to AdGuard > Advanced and toggle Use Simplified Filters
3. Return to Filters

### Expected behavior

The number of cosmetic rules is deducted, the total amount of rules is less than it was before applying simplified rules

### Actual behavior

It changed from 46.589 to 46.561; checking for updates didn't help. See the screen recording below

<details><summary>Screen recording:</summary>

https://uploads.adguard.com/simplified_filtes_dont_work_07-09-12-24.MP4

</details>

### Your environment

* Device model and storage size: SE 16 Gb
* Operating system and version: 12 beta 2
* Browser: Safari
* Wi-fi or mobile internet connection: both

**Comment by ToniKumpula** [comment]
I tested this on my iPhone 8+ (iOS 12 DB3) and my filters went from 49224 to 49199 after enabling Simplified filters option.

This might also depend on which filters you have enabled, it might not affect every single filter I’m assuming.

**Comment by Eugene-Savenko** [comment]
I can't reproduce this either on iPhone SE 16Gb with iOS 12 beta 2, but we have a complaint from another user who's been insisting this is a bug... Hope it's a one-time issue that no one will ever face.

**Comment by zebrum** [comment]
There are not that many rules disabled by the option.  Not a bug @Eugene-Savenko
