### ISSUE TITLE
German translation glitches in latest Beta 2.1.2

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardForiOS#811]
There are some German translation glitches in the latest Beta. I have corrected them on OneSky. Please update.
![img_3897](https://user-images.githubusercontent.com/25068100/42491213-37f71174-8414-11e8-9dc7-bdd07b017de3.png)
![img_3898](https://user-images.githubusercontent.com/25068100/42491214-382b3378-8414-11e8-88c5-26010875b08f.png)

**Comment by aalpatkina** [comment]
The corrections have been approved on OneSky platform
