### ISSUE TITLE
Status Panel goes black in Privacy Settings > Add Subscription & DNS Settings > Add Custom

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#812]
### Steps to reproduce
1. Open up AdGuard Pro v2.1.2 (167) beta
2. Navigate to Privacy Settings > Add Subscription 
3. Notice how Status Panel goes black
4. It should stay white like it stays in other menus

### Expected behavior
Status Panel should stay white

### Actual behavior
Status Panel goes black

<details><summary>Screenshot:</summary>

![59aa3cf2-26ae-4d85-8f72-afe00b707c00](https://user-images.githubusercontent.com/40921053/42583547-d7027d14-8539-11e8-842c-b719e94fad29.png)

</details>

### Customer ID 
1931201

### Your environment
* Device model and storage size: Apple iPhone 8+ 64GB
* Operating system and version: iOS 12 Developer Beta 3
* Browser: N/A
* Wi-fi or mobile internet connection: N/A

**Comment by ToniKumpula** [comment]
One interesting fact by the way that I noticed when I opened the Add Subscription window, it always slides from the bottom to the top, in other areas windows will always slide from right to left.

So maybe that’s why I’m getting this UI glitch that will make the Status Panel black.

Here, I attached a short screen recording demonstrating the window animation.

https://www.dropbox.com/s/rs09rnd6a8ifmvr/Video%2012-07-2018%2C%201.45.54%20AM.mp4?dl=0

**Comment by ToniKumpula** [comment]
I’m not the only one with this issue, check the Youtube video below:

https://youtu.be/rdGtO5brCAA

Look closely at 2:40 and you will see the window animation coming from the bottom to the top instead of right to left, and you will see the Status Panel go black.

**Comment by ToniKumpula** [comment]
@vozersky 

Status Panel goes black in DNS Settings > Add Custom too, the window slides from the bottom to the top like in my original issue.

![40b3fdff-eb72-4bc6-9904-8422c3f5182e](https://user-images.githubusercontent.com/40921053/42653157-3f8b1650-861d-11e8-8f86-a2fbde791510.png)

**Comment by ameshkov** [comment]
https://adguard.com/en/blog/adguard-pro-discontinued/
