### ISSUE TITLE
Feature request: Make Family Protection DNS password enabled feature

### ISSUE THREAD

**Issue by ToniKumpula** [AdguardTeam/AdguardForiOS#814]
### Steps to reproduce
1. Make Family Protection DNS password enabled
2. So kids can not turn off Family Protection DNS without my password
3. Without a password this is kinda worthless feature

### Expected behavior
Family Protection DNS is a password protected feature

### Actual behavior
Users can turn off Family Protection DNS without a password

<details><summary>Screenshot:</summary>

</details>

### Customer ID 
This is a feature request, ID is not needed

### Your environment
* Device model and storage size: Apple iPhone 8+ 64GB
* Operating system and version: iOS 12 Developer Beta 3
* Browser: N/A
* Wi-fi or mobile internet connection: N/A

**Comment by zebrum** [comment]
closed as a dup #135
