### ISSUE TITLE
Differences between iPad and iPhone

### ISSUE THREAD

**Issue by florianorama** [AdguardTeam/AdguardForiOS#815]
Hello,

Both devices have iOS 11.4.1 and have allocated IP v6 @ over WiFi

DNS settings set to AdGuard DNS (IPv6) on both

iPad cannot access the app store but the iPhone can.

Need to switch to AdGuard DNS on iPad to access the app store.

Same issue with other apps like Ghostery.

iPhone 8+ 256 Gb
iPad Pro 10.5-inch 64Gb 2017
V2.2.1

**Comment by zebrum** [comment]
@florianorama it's hard to say why. Maybe because iPhone has ipv4 interface also, AdGuard sees it and set up tunnel differently. 
Use ipv4 AdGuard DNS
