### ISSUE TITLE
AdGuard Pro will be discontinued because of Apple's policy.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#816]
Some people already knew the bad news from Telegram's AdGuard group.
Maybe AdGuard Pro will have no update anymore on app store.
I guess that AdBlock and Weblock by FutureMind also met the same situation.
They're not updated for a long time.

Andrey:
> what it means for users:
>1. no updates to AG Pro
>2. we'll focus on regular AG and focus on additional content blocking features, I'll describe a new road map later.

A. You'll focus on free AdGuard for iOS.
Well, maybe in-app purchasing for those additional content blocking features in regular AdGuard for iOS.
System-wide ad blocking will be given up.
After all, time is money.
I can understand that AdGuard team maybe won't spend time and spirit on AdGuard Pro...
Those mysterious vpn-api-related bugs maybe tired you.
**If possible, still hope that you can fix some critical bugs and then release new AG Pro beta on TestFlight.**

Before releasing AG Pro v2, this is what I mostly worried about for AG Pro for iOS. 😔
That's why I thought that giving more time to developers and designing the more features which users wish in AG Pro v2 before formally releasing it are better...
Nobody understood my thought, even I was blamed by somebody at that time.
From the beginning, I wish AG Pro v2 could be the best as possible because I don't think that AG Pro v2 is always safe under Apple's policy.
Anyway, really thank AdGuard team.

B. Except for system-wide ad blocking, how about DNSCrypt v2 for encrypted DNS?
Apple should still allow DNS changer on app store, shouldn't it?

C. Will you push another product on app store since AG Pro for iOS will be discontinued?
Is it possible that customize blacklist, whitelist and filters subscriptions are at server side, not in app itself?
As what I know, some real VPN providers provide adblock.
**They don't design adblock function in apps, they let users manage adblock function at server side via official website instead.
Users need to login into their accounts on official website for managing adblock function.**
I know AdGuard team don't have plans for real VPN service now.
I don't know if there is such technology for DNS servers.

I think about Puffin Browser.
Puffin speeds up browsing by shifting the workload from the resource-limited devices **to the cloud servers**, and resource-demanding webpages can run super-fast on your devices.

**Is it possible that AdGuard team design another app to do ad filtering via cloud servers and let users manage blacklist, whitelist and filters subscriptions at server side?**

Thanks.

**Comment by rezhajulio** [comment]
Sad, I just bought AdGuard Pro on iOS a few hours before this was announced.

**Comment by lancelot-moon** [comment]
Andrey:
> We won’t take it down, but without updates it will slowly degrade

I disagree with the opinion.
AdBlock by FutureMind is not updated for a long time.
But AdBlock by FutureMind often ranks high on Taiwan app store.
After introducing AG Pro on Taiwanese social community, more and more Taiwanese people know AG Pro is better than AdBlock by FutureMind.
A good app is worth being paid as long as it isn't taken down from app store.

I just hope that users can be more patient and give more time to developers.
And developers can collect and finish beta testers' ideas, feature requests and suggestions before formally releasing it.
We can't forget about Apple's policy.
AG Pro is the best adblocker on app store, but it's still imperfect.
Here, many feature requests are still not realized in AG Pro, except for unsolved bugs.

**Comment by ameshkov** [comment]
> > We won’t take it down, but without updates it will slowly degrade
> I disagree with the opinion.
> AdBlock by FutureMind is not updated for a long time.

I cannot define "slowly" though. It may take a year for instance, or they might introduce some change in iOS 12 that will render AG useless. It's hard to predict.

**Comment by lancelot-moon** [comment]
Хорошо, the best thing is: I'm mainly an Android user. XDD
Wait for your future plan and sincerely thank AdGuard team for the great work (AG Pro).

**Comment by ameshkov** [comment]
Published it on our blog:
https://adguard.com/en/blog/adguard-pro-discontinued/

**Comment by norbertc** [comment]
For some reason, I just saw an update to DNSCloak a few hours ago and DNSCloak also uses fake-VPN to change DNS.

**Comment by ameshkov** [comment]
Good news, it means that DNS changing functionality can be saved, and their problem with us is in the optional privacy subscriptions feature.

**Comment by lancelot-moon** [comment]
I can accept if ONLY removing subscription in Privacy Settings but keeping the blacklist and whitelist.

AdGuard Pro needs to update its poor known DNS service list and DNSCrypt v2.

**Comment by imTHAI** [comment]
Isn’t tene a way to install it if we have a dev account ?
