### ISSUE TITLE
The time of checking for updates was not changed.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#817]
I use AG Pro beta v2.1.2(167).
The last updating date of subscriptions is 20th July.

At the midnight of 22th July, after clicking "Check for updates", it spent a lot of time on checking for updates.
Finally, the time of checking for updates was not changed.
It seems that it's failed to update subscriptions.
Very strange.
Before updating subscriptions, I ever updated Safari's filters.

https://youtu.be/eFXorxQSKH8

I already sent the bug report to AdGuard Support at 01:32 on 22th July (GMT+8).
User ID: 1425202
Subject: [AdGuard Pro for iOS] 程式錯誤報告 (bug report)

(I turned off my iPhone at midnight. After getting up in the morning, I successfully updated subscriptions.)

**Comment by zebrum** [comment]
@lancelot-moon is it still reproducible on your side?

**Comment by lancelot-moon** [comment]
Even if it happened again, I would not know the reproduction steps.
I already sent that log before.
If you couldn't find the cause from that log, it still happened or not, which doesn't make sense...

**Comment by TheHasagi** [comment]
Unable to reproduce, all subscriptions were updated fast & properly.
