### ISSUE TITLE
Split filters into several content blockers

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#819]
Generally, filters might depend on each other, and splitting them into multiple content blockers is not an ideal solution. However, the 50k limit is also an issue and we need to find a compromise.

Generally, several filters categories are more or less independent (see categories here: https://github.com/AdguardTeam/AdguardForAndroid/issues/1806)

1. `Privacy` -- does not depend on other filters
2. `Social Widgets` and `Annoyances` are often used together so we'd better have them as a single content blocker
3. `Security` -- does not depend on other filters
5. `Other` category might be also independent
4. All other categories must use the same content blocker. It is too often when a regional filter extends the base filter.
5. Custom filters (imported by an URL) will be imported into the `Custom` content blocker.

So, the final list of the content blockers:

* `AdGuard - General`
* `AdGuard - Privacy`
* `AdGuard - Social Widgets and Annoyances`
* `AdGuard - Other`
* `AdGuard - Custom`

Additionally, we need to make "Whitelist" and "User filter" interact with every other filter. This means that the rules from there will be included into every content blocker.

**Comment by lancelot-moon** [comment]
@ameshkov

Specific languages filter is usually a big guy, ex: EasyList China.

Is specific languages filter an individual content blocker?

For now AG content blocker for Safari, I enabled Base filter, Mobile Ads filter, Spyware filter, Social media filter, Annoyances filter and EasyList China.

The total rules are over 49k entries.
Specific languages filter is must an individual content blocker.

Thanks.

**Comment by lancelot-moon** [comment]
In the app interface, separate specific languages filters into different tabs (zone).

In Safari content blocker, only 1 switch represents the content blocker of specific languages filters.

**Comment by kiicia** [comment]
any update on this isse? as time goes on, sum of even default (curated adguard) lists is almost 50k

you simply cannot any other list (especially regional) without crossing the threshold...

also when you actually cross limit, there is no indication which filters are ommited or which lists are incomplete due to that

**Comment by zzebrum** [comment]
@kiicia  The issue was implemented in the latest AdGuard for iOS v3.0

**Comment by kiicia** [comment]
I have AdGuard pro 2.1.1 (seems to be current version according to AppStore), am I missing something?
