### ISSUE TITLE
[Feature request] Implement a 'no images' option

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForiOS#82]
To minimize network load in cases such as public WiFi where bandwith is very low.

**Comment by worldsdream** [comment]
This is easy to add, isn't it? Just make sure to have all the images extensions and when this feature: "disable images" is enabled, they go into userfilter.

**Comment by ameshkov** [comment]
It can be done with a single filter rule, so yes, it is easy.
`http*$image`
