### ISSUE TITLE
“No Respond” Error

### ISSUE THREAD

**Issue by validatedev** [AdguardTeam/AdguardForiOS#821]
Sometimes I can’t reach internet connection with Pro enabled, although I have connection. Generally I have encountered this problem randomly when I’m on Wifi -Cellular . When I look DNS logs, it says “No Response” for all of the sites, connections, etc. Disable-enable Pro or switch connection may solve that, but not always.

Device: iPhone 8 Plus 64 GB
iOS Version: 12.0 Developer Beta 6 (16A5345f)
Adguard Pro Version: 2.1.2(167)

**Comment by zebrum** [comment]
Sorry about late reply. It seems to be this problem: #772 and #771. Unfortunately we won't fix it because of [this](https://adguard.com/en/blog/adguard-pro-discontinued/)
You can try to turn on Restart when network changes option in Advanced settings and see how it goes.

**Comment by validatedev** [comment]
https://ibb.co/fgepXp
https://ibb.co/mT3GCp

I reproduced that ATM.
“Yanıt yok” means “No response”.
Restarting or switching with “Restart when network changes” option status ON have fixed but it isn’t a permanent fix.
