### ISSUE TITLE
[Bug] in-app browser Blocker stopped functioning on iPad 

### ISSUE THREAD

**Issue by abyxcos** [AdguardTeam/AdguardForiOS#822]
![img_0003](https://user-images.githubusercontent.com/662820/43992721-77685f84-9d50-11e8-92ee-72ad52084481.jpeg)

The blocker for the in app browser on my iPad stopped working. Unfortunately, the error is almost useless. The blocker on my iPhone continues to work fine. I tried adding then removing a rule set to recompile the filter, but no luck. It continues to work just fine in safari.app on the same iPad.

**Comment by ameshkov** [comment]
Does it help to reinstall the app?

**Comment by abyxcos** [comment]
Unfortunately a reinstall changed nothing. (Still works in Safari.app, and same error in the in-app browsers.)

**Comment by zebrum** [comment]
@abyxcos what iOS version you have on your device?

**Comment by karina-archazh** [comment]
reopen if needed
