### ISSUE TITLE
Why doesn't the tunnel use "defaultPath"?

### ISSUE THREAD

**Issue by Ricardo1980** [AdguardTeam/AdguardForiOS#823]
Hello,

This is not a bug, it is just a design question I have.

I see that the tunnel:
https://github.com/AdguardTeam/AdguardForiOS/blob/728e10b0c641229fdf9054a5e14b6604dfc87216/AdguardExtension/AdguardPro/tunnel/PacketTunnelProvider.m

has something like a reachability observer, however, according the docs it seems we have to use "defaultPath" and observe that value.
https://developer.apple.com/documentation/networkextension/neprovider/1406740-defaultpath

Is there any reason why this is not used in this program?
I'm curious.

Thanks for suggestions.

**Comment by ameshkov** [comment]
There was a reason for that, but I don't remember what exactly :)

@IvanIin do you remember why?

**Comment by zebrum** [comment]
Ivan said we had't known about it :)

**Comment by Ricardo1980** [comment]
About what?
Do you mean you don't remember the reason? Or that you didn't know you were not using defaultPath?
Thanks a lot.
