### ISSUE TITLE
Не обновляет автоматически фильтры

### ISSUE THREAD

**Issue by zhilinskiyaleksandr** [AdguardTeam/AdguardForiOS#824]
![95238812-f01d-4fd4-8937-55e3d6e4cd09](https://user-images.githubusercontent.com/37153844/44019730-548042a4-9ee8-11e8-88e2-a4814e758ea6.png)
iPhone X
iOS 11.4.1
AdGuard pro 2.1.1
Автоматически не обновляет фильтры.
Сейчас 13 августа, зашёл в приложение, и там указано, что последнее обновление фильтров было 21 июля.

**Comment by ameshkov** [comment]
Старая проблема которая не особо лечится. Если вы хоть раз смахнули приложение, то iOS ему больше не даст запуститься в бэкграунде и соответственно оно не сможет проверять обновления. Просто нужно его не смахивать.

**Comment by zhilinskiyaleksandr** [comment]
ну так сделайте хотя бы автоматическое обновление фильтров при открытии приложения, если в фоновом режиме оно не может это делать.

**Comment by ameshkov** [comment]
> ну так сделайте хотя бы автоматическое обновление фильтров при открытии приложения, если в фоновом режиме оно не может это делать.

А оно есть
