### ISSUE TITLE
Cannot block page auto-refresh on "corriere.it" domain

### ISSUE THREAD

**Issue by gelbrait** [AdguardTeam/AdguardForiOS#825]
Good morning.
I was really disappointed hearing from you that Apple wasn't approving your wonderful application anymore. It's indeed a true must have for iOS devices. And it works flawlessly as it's expected to.

Unfortunately, due to my poor knowledge in setting filters, I cannot block a truly very annoying page auto-refresh on "corriere.it" domain. When I first connect to that site I use the bookmark "https://www.corriere.it". After a very few minutes the page auto-refreshes and on the address bar I see the following address:
- https://www.corriere.it/index.shtml?refresh_ce
or
- https://www.corriere.it/index.shtml?refresh_ce-cp

In my desktop environment, Firefox 55.0.3 with uBlock Origin installed, I have setted two filters:
- ||www.corriere.it/index.shtml?refresh_ce$inline-script,domain=*.corriere.it*
- corriere.it##script:contains(corriere.it/index.shtml?refresh_ce)

where the second one seems to have done the miracle to block this frustrating behaviour of that site.

I've tried to set both these filters in Adguard Pro (v. 2.1.1) installed on my iPhone 6s Plus mounting iOS 11.4.1 obviously not jailbroken (but the same is also valid for my iPad mini 4 iOS 11.4.1) and the result is that these two filter expressions are not accepted (they are coloured in red).
So I tried to adapt these filters to Adguard (and Safari) environment setting the following filters:
- |https://www.corriere.it/index.shtml?refresh_ce.js
- |script:contains(?refresh_ce)
- script:contains(?refresh_ce)
- ||script:contains(?refresh_ce)

but with no luck.
I'm sure that the domain uses a kind of javascript injection but I cannot figure how to block it. And I'm also sure that Adguard is able to prevent that site from auto-refreshing.

May you help me, please?

**Comment by Alex-302** [comment]
Hi
Please check this rule:
`||stadvtools.akamaized.net/trackingservice/`

**Comment by gelbrait** [comment]
Hi
First of all I would like to thank you for your super fast reply.
Unfortunately, adding your rule to my private ones did not the trick.
I've also tried to blacklist "stadvtools.akamaized.net" in my "privacy settings" but that site keeps on auto-refreshing. I've also disabled "link preload" in "Settings > Safari > Advanced > Experimental features" but with no avail.
I also browse another site, which domain is "lastampa.it", and I managed to stop the auto-refresh feature by setting these two filters:
- |http://www.lastampa.it/common/js/refresh.js*
- ||www.lastampa.it/common/js/refresh.js?id=1$script,domain=www.lastampa.it

but in that case there was a well defined script that uBo intercepted.
Any other idea?

**Comment by gelbrait** [comment]
Hi
I have to deeply apologize with you. In fact, the rule you suggested to me works.
The domain "https://corriere.it" kept on bringing me to "https://www.corriere.it/index.shtml?refresh_ce" and I stubbornly was turning back to the original page. I realized only after that the auto-refresh stops once I am redirected to the new address.
Thank you so much for your help.

**Comment by gelbrait** [comment]
Okay, "corriere.it" site is literally driving me crazy.
Previous rule
@@||stadvtools.akamaized.net/trackingservice/
was working, not perfectly, but in an acceptable way.
That filter didn't prevent site from auto-refreshing but allowed to maintain the reading position in which I was located. Not even this now. The site reloads the page and I find myself in a position much higher, just below the head of the newspaper, compared to where I was previously reading.
I tried to set up dozens of filters but nobody seems to work.
I'm looking for help. Any suggestion is much appreciated.

**Comment by Alex-302** [comment]
@gelbrait could you, please, try to find a filter, which causes it?

**Comment by gelbrait** [comment]
@Alex-302 
First of all, please accept my apologies for the heavy delay with which I answer you.
I finally managed to find a rule that prevents the site from auto-refreshing:

`||js2.corriereobjects.it^$important`

seems to be effective in counteracting the behaviour of that site.

Thanks for your help and patience.
Kind regards

**Comment by gelbrait** [comment]
@Alex-302 
Hello
The filter in the previous post works well but, at the same time, prevents the loading of images, slides and videos that require javascript.
So I've looked into that and redefined the rule more precisely and I believe that what I was looking for is:

```
||js2.corriereobjects.it/includes2013/LIBS/js/tracking/*$script,domain=www.corriere.it
||js2.corriereobjects.it/includes2013/LIBS/js/vendor/plugins/checkadblock.js*$script,domain=www.corriere.it
||js2.corriereobjects.it/includes2013/LIBS/js/corriere_home_2018.sjs*$script,domain=www.corriere.it
||js2.corriereobjects.it/includes2013/LIBS/js/_top2018.sjs*$script,domain=www.corriere.it
```

To prevent the appearance of a banner that offers a subscription to the newspaper, you may also add:

```
corriere.it###pwl_ma > div.pwl_content:nth-child(2)
corriere.it###pwl_ma > div.pwl_content:nth-child(2) > div
corriere.it###pwl_ma > div.rightside:last-child
corriere.it###pwl_ma > div.rightside:last-child > a.ma_logo_corriere
```

Now, if you want, you can close the thread as fixed.
Have a nice day

**Comment by gelbrait** [comment]
I'm closing this request for the reason that it's resolved.
