### ISSUE TITLE
FaceTime calls do not connect with AdGuard VPN on

### ISSUE THREAD

**Issue by chillipal** [AdguardTeam/AdguardForiOS#828]
FaceTime calls work with DNSCloak. To rule out any filtering issue, I ran the Privacy module (AdGuard Pro VPN) with no subscription, no blacklist and no whitelist. FaceTime calls ring, on answering the call, the screen display states “Connecting” for a long time and then drops the call as failed call.

### Steps to reproduce

1. If it is a new install of Acguard Pro, set up AdGuard Pro VPN by toggling Privacy Status switch to on (green position). Enter your device passcode to let the OS create the vpn profile
2. With Privacy On (AdGuard Pro VPN) running, ask a friend to call you via FaceTime audio. 
3. Answer the call and wait for the call to connect or end. 
4. Now, again with AdGuard Pro VPN running call someone via FaceTime. Call will fail even if the other person person answers. 

### Expected behavior
FaceTime calls connect when answered. 

### Actual behavior

FaceTime calls do not connect when answered

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Device model and storage size: iPhone X; 256 GB
* Happens both on WiFi and LTE.

**Comment by zebrum** [comment]
@chillipal What tunnel do you use: split or full in advanced settings of AdGuard?

**Comment by Eugene-Savenko** [comment]
it's due to this https://github.com/AdguardTeam/AdguardForiOS/issues/778

**Comment by zebrum** [comment]
more likely

**Comment by cn46375** [comment]
It looks like FaceTime broke again, regardless of which tunnel mode is chosen and using mobile data. It will connect for a brief moment, and then later on immediately say that the FaceTime call failed.

**Comment by SoLenny** [comment]
@cn46375 Hello, can you please specify if you are using the pro or lite version?

**Comment by cn46375** [comment]
@SoLenny this is happening on the lite version, but I have a lifetime license that I had applied. I can try out the pro version and see if that makes any difference.

**Comment by SoLenny** [comment]
@cn46375 Thanks for answer. Unlucky, i can't reproduce it on my side with the lite version.
Did you try to reinstall the app?
If it won't help, please reproduce the issue and send logs to apple@adguard.com
Mention this issue number in the email text.

**Comment by cn46375** [comment]
@SoLenny how do I go about obtaining the logs after replicating the issue?

**Comment by SoLenny** [comment]
@cn46375 Reproduce the issue, then open Settings -> Send Feedback ->Export logs.

**Comment by SoLenny** [comment]
@chillipal Hello. Any updates on this?

**Comment by cn46375** [comment]
So I replicated the bug earlier, but it looks like my email domain didn't allow for attaching the logs that time. Weirdly however, it looks like it's working fine again.

**Comment by SoLenny** [comment]
@chillipal Nice to know. Let us know if something won't work again.
