### ISSUE TITLE
Crimpd

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#829]
@adguard-bot commented on [Thu Aug 16 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21165)

### Issue URL (Incorrect Blocking)
https://itunes.apple.com/ru/app/crimpd/id1252333138?mt=8
### Comment
Username: @OnTheRocksBrew
> When DNS filtering is enabled the error screen appears in the app when launching. Force closing the app, turning off DNS filtering, and reopening the app makes the issue go away. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Q012KZd.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | iOS
AdGuard version: | 2.1.1
Browser: | Crimpd (iPhone App Store)
System wide filtering: | enabled
Simplified filters: | disabled
AdGuard DNS: | Default
Filters: | Filter unblocking search ads and self-promotion,<br>Safari,<br>Annoyances,<br>English,<br>Spyware,<br>Social media

---

@OnTheRocksBrew commented on [Thu Aug 16 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21165#issuecomment-413585752)

Just to be clear the URL is a dummy URL used just to allow me to submit the form at https://reports.adguard.com/en/new_issue.html?ios.DNS=Default&filters=2.3.4.10.12.14&ios.simplified=false&browser=Safari&product_version=2.1.1&product_type=iOS&ios.systemwide=false … the issue is actually with the iPhone App “Crimpd”. 

---

@Alex-302 commented on [Tue Aug 21 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21165#issuecomment-414622946)

What do you see in DNS filtering log?

---

@OnTheRocksBrew commented on [Tue Aug 21 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21165#issuecomment-414795656)

Geeez, how did I forget to include those? Ok so the first one is after clearing and having othe apps running in the background. The second is just with AdGuard Pro and Crimpd running. What’s weird to me is it doesn’t look like anything is getting blocked … or am I misreading what I’m seeing?

![0202ebab-3775-4b18-bd85-4725e4eb2a16](https://user-images.githubusercontent.com/42444852/44424592-2e255c80-a54f-11e8-997a-1c21aa3cfb66.png)
![f4c43011-7b54-4e49-8f11-b1a28bddfbd8](https://user-images.githubusercontent.com/42444852/44424593-2e255c80-a54f-11e8-834f-d3fd46dd3a8f.png)

---

@Alex-302 commented on [Thu Aug 23 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21165#issuecomment-415499482)

Maybe cache. Please close this app, clear DNS log, turn off/on your network connection and reproduce the issue.

---

@OnTheRocksBrew commented on [Sat Aug 25 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21165#issuecomment-415928504)

Actually, it doesn’t seem to matter what “DNS Settings” are used. Even “System Default” (which is nothing for me) triggers the issue. Are you able to reproduce this or is it just me?

---

@OnTheRocksBrew commented on [Sat Aug 25 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21165#issuecomment-415928582)

Oh and I didn’t have any luck with your suggestion unfortunately. 

---

@Alex-302 commented on [Mon Aug 27 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21165#issuecomment-416248214)

At the moment I can't open this site
`DNS_PROBE_FINISHED_NXDOMAIN`

---

@OnTheRocksBrew commented on [Fri Aug 31 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21165#issuecomment-417554808)

Hi Alex,

I apologize for any potential confusion (I tried to clear it up with my first comment). The issue is with the "Crimpd" iPhone app, not the site "justletmesubmitthisform.com"; sorry, but in order to get the form at https://reports.adguard.com/en/new_issue.html?ios.DNS=Default&filters=2.3.4.10.12.14&ios.simplified=false&browser=Safari&product_version=2.1.1&product_type=iOS&ios.systemwide=false to submit, I had to put in a dummy URL.

Are you able to reproduce the issue with the "Crimpd" iPhone app?

Thanks!
-Jay

---

@Alex-302 commented on [Fri Aug 31 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21165#issuecomment-417641276)

Reproduced, and no blocked domains, as I see.

**Comment by TheHasagi** [comment]
Unable to reproduce. Should be reopened if needed.
