### ISSUE TITLE
Filter not updating properly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#83]
**Source:**
http://forum.adguard.com/showthread.php?10606-Filter-not-updating-properly

> On my iPad there's been multiple times when I've done a filter update, it will state no updates found and yet my filter list will be a couple of versions behind my other devices, repeatedly requesting a filter update doesn't seem to resolve this.
> 
> Force closing the Adguard app and then loading it up again will then show the correct version number for the filter so I'm wondering if it's just not updating the version number correctly?

**Comment by vozersky** [comment]
obsolete
