### ISSUE TITLE
White-list not working properly 

### ISSUE THREAD

**Issue by R3TZ3V** [AdguardTeam/AdguardForiOS#833]
### Steps to reproduce
There are some sites that are not properly shown while AdGuard is on. But when you white-list them, it doesn’t change anything. You need to reload them manually without blocking content using Safari’s twisted arrow (and you have to do it every time for each page of that site)
1. Visit a site, e.g.
- www.merlin.pl (site is not complete and some functions doesn’t work)
- www.online.citibank.pl/citispecials/ (when content is blocked, you can’t click anything)
- www.humblebundle.com (also problems with showing images)
- store.steampowered.com (also problems with showing images)

2. White-list them, see that nothing happens. 
3. Reload them without blocking using twisted arrow at the right side of address bar (press and hold it for a moment and choose “Reload without content blocking” from drop-down menu).

### Expected behavior
After white-listing a page, it should be automatically shown as it is after holding twisted arrow and choosing “Reload without content blocking”

### Actual behavior
White-listing doesn’t change anything at all. You need to manually finish blocking for that page.

### Your environment
* iPad Air 2
* Operating system and version: iOS 11.4.1
* AdGuard version: 2.1.2(101)
* Browser: Safari
* Wi-fi and mobile internet connection (problem on both types of connection)

**Comment by TheHasagi** [comment]
Can you say which DNS is used?

Unfortunately, I cannot reproduce the issue you described.

We need more information:

1. What DNS enabled? (Default/Family protection - encrypted or not)
2. Your mobile provider

**Comment by R3TZ3V** [comment]
Hello,

 

In my iPad preferences when I’m connected to wi-fi, my DNS is set to “Automatic”.

My mobile provider is Play (in Poland). iPad preferances say “Carrier 32.0”.

The problem occurs independently from network connection (only wi-fi, only cellular/mobile or both active at the same time).

 

I’m sending screenshots to show the problem. White-listing doesn’t work as the “Reload without content block” (that button makes page to load correctly)

 

 

Yours sincerely,

Gregory Nazar

**Comment by R3TZ3V** [comment]
Hello again. I found the problem - it was Firefox Focus app, that also blocked some content on sites. After clearing it’s permission to do that I don’t even have to white-list those pages. Sorry for problem, but I forgot that FF Focus could affect Safari browser.
Should I close the git-hub subject?


Pozdrawiam serdecznie,
Grzegorz Nazar
Doradca Finansowy
- - - - - - - - - - - -
tel. (+48) 697 58 67 58
www.grzegorznazar.pl

________________________________
Od: Alexander <notifications@github.com>
Wysłano: środa, września 12, 2018 3:51 PM
Do: AdguardTeam/AdguardForiOS
DW: R3TZ3V; Author
Temat: Re: [AdguardTeam/AdguardForiOS] White-list not working properly (#833)


Can you say which DNS is used?

Unfortunately, I cannot reproduce the issue you described.

We need more information:

  1.  What DNS enabled? (Default/Family protection - encrypted or not)
  2.  Your mobile provider
