### ISSUE TITLE
Apple Music won't start properly with AdGuard

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForiOS#834]
Apple Music wont start properly when Adguard is on (see screenshots)

<details><summary>Screenshot:</summary>

![image1](https://user-images.githubusercontent.com/37797229/45267225-3e0acf00-b471-11e8-96ac-14095dc9c55c.png)

</details>

### Customer ID 

1138152
### Your environment

* Device model and storage size: (e.g. iPhone 6s 64gb)
* Operating system and version: 2.1.1.165
* Only with mobile connection (Megafon)

**Comment by Goddess-Bastet** [comment]
I have AdGuard pro & Apple Music is fine for me. 
Tested on WiFi & 4G cellular. 
iPhone 5s.

**Comment by zebrum** [comment]
@TheHasagi does it make any difference if you change DNS server?

**Comment by Eugene-Savenko** [comment]
@zebrum another report here (maybe it's not related, but still): 2030024

> Hi. The problem is that every time I enable the privacy VPN (right now I have it set to full tunnel with VPN icon) and even if I’m not subscribed to any lists, Apple Music isn’t able to load any music. As soon as I turn off the privacy VPN it works. I checked the logs and nothing is being reported as blocked.

and after some conversations, we've narrowed the issue down to:

> If I select “AdGuard Default” or “OpenDNS Home” or “Google Public DNS”, I am not able to load any websites. However, once I change the tunnel type to split mode, I am now able to load websites using these DNS servers. Furthermore, if I access Apple Music under the split tunnel mode, it works.
