### ISSUE TITLE
Add full stop at the end of the Russian filter description in Turkish translation

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#838]
>Hello,
>Please put a dot at the end of the Russian filter description. All filter descriptions end with a dot. Only there is no dot in the Russian filter description. AdGuard version 2.1.2

<details> <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/15856304/46945981-fd5d3180-d07e-11e8-8cad-8bf91b6704d1.png)

</details>

**Comment by aalpatkina** [comment]
Corrected on OneSky
