### ISSUE TITLE
iOS YouTube app connects very slowly with VPN on

### ISSUE THREAD

**Issue by level1807** [AdguardTeam/AdguardForiOS#839]
### Steps to reproduce
Turn on AdGuard VPN. Open the YouTube app after a few minutes of not using it.

### Expected behavior
YouTube instantly loads the feed, thumbnails etc.

### Actual behavior
YouTube doesn’t load anything and shows a “No connection” bar at the bottom for about 10 seconds, then finally switches to a green “connected” bar and loads the feed. Loading videos via direct links still happens instantly. The problem also occurs when leaving a currently playing video,
 No issues when VPN is off.

### Your environment 
* IPhone 6s 64gb
* 12.0.1
* safari
* Wi-fi

**Comment by zebrum** [comment]
@level1807 what DNS server have you chosen in AdGuard DNS settings?
