### ISSUE TITLE
[Feature request]  making background update possible even after force closing the app

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForiOS#84]
User states that some adblockers keep updating when force closed:

https://itunes.apple.com/us/app/norton-ad-blocker-browse-faster./id1045186459?mt=8

https://itunes.apple.com/us/app/blockr-privacy-media-ad-blocker/id1032344361?mt=8
https://itunes.apple.com/ru/app/purify-blocker-no-ads.-no/id1030156203?mt=8

Can we study it? Please assist.

Please refer to QMU-134-16255

**Comment by vozersky** [comment]
@gshumihin, please assist.

**Comment by Stillness-2** [comment]
About Purify. You can get answer here: https://twitter.com/purify_app/status/657656822531248128

**Comment by Stillness-2** [comment]
About Norton. You can get answer here: https://support.norton.com/sp/en/us/norton-mobile/current/solutions/v115518328_EndUserProfile_en_us

"If Background App Refresh is off in device's Settings, or if you have quit Norton Ad Blocker from the app switcher, it cannot receive the updates."
