### ISSUE TITLE
Have you exclude $app rules and those specific rules for apps from Mobile Ads filter of content blocker?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#840]
For now AG content blocker for Safari, I enabled Base filter, Mobile Ads filter, Spyware filter, Social media filter, Annoyances filter, Safari filter and EasyList China.
The total rules are already over 49k entries.
Critical boundary.

Some rules in Mobile Ads filter are for mobile apps.
Have you exclude $app rules and those specific rules for apps from Mobile Ads filter?

You know there are 50k upper limit for Safari content blocker.
This is just a question which I want to confirm.
Thanks.

**Comment by zzebrum** [comment]
@lancelot-moon in the next version of AdGuard for iOS there will be an opportunity to use more than 50k rules :)
