### ISSUE TITLE
Doesn't work "Remove" (section Whitelist)

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#845]
### Steps to reproduce
1. Go to Whitelist section
2. Select the domain
3. Tap on "Remove"

### Expected behavior
The domain removed.

### Actual behavior
The domain doesn't remove.

#
https://uploads.adguard.com/ScreenRecording_11-20-2018_14-09-36.MP4.mp4

### Your environment
* Adguard 2.5.0 (110)
* Operating system and version: (ios 12.1)

**Comment by zzebrum** [comment]
not fixed

**Comment by PentagramTr** [comment]
The Remove button still does not work.If I close the Whitelist and enter again, the domain is deleted.
iPhone 5s iOS 12.3.1
AdGuard Premium
