### ISSUE TITLE
Groups and filters enabled by default

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#852]
The logic what groups and filters should be enabled by default is explained here: https://github.com/AdguardTeam/AdGuardForSafari/issues/57

! Doesn’t enable AdGuard safari filter (section Other filters) in default settings in ios 11 (ios 12 - it's ok)

#

### Your environment
* Adguard 2.5.0 (110)
* Operating system and version: (ios 12.1)

**Comment by zzebrum** [comment]
check after #885 will be fixed

**Comment by aspasskaya** [comment]
#### 1. Language specific filters group should be enabled by default.
! Also, language specific filter should be automatically activated.
#### 2. Custom filters group should be disabled by default.
##### Actual behavior
First install -> Settings -> Filters -> Get premium -> Custom filters group enabled.
![image](https://user-images.githubusercontent.com/43952607/54991339-c7c55880-4fcd-11e9-839b-6b8f2cdcf5f4.png)
