### ISSUE TITLE
Make file names different when exporting Whitelist and User filter

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#856]
Go to WhiteList and User Filter sections and export.
One name for export files - user_filter.txt.
#
https://uploads.adguard.com/one_name_for_export_files.MP4
### Your environment
* Adguard 2.5.0 (110)
* Operating system and version: (ios 12.1)

**Comment by aspasskaya** [comment]
Also, make file name different when exporting Whitelist (inverted).
# 
![image](https://user-images.githubusercontent.com/43952607/50908095-0a997a80-143a-11e9-8d91-b2f1037fc5ac.png)

**Comment by zzebrum** [comment]
check after #952 will be fixed
