### ISSUE TITLE
Search on tag in filter groups doesn’t work correctly

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#858]
### Steps to reproduce
1. Go to the Ad Blocking filter group
2. Scroll the list and tap on the tag.
3. The search field is not fixed.

#
https://uploads.adguard.com/search_on_tag_in_filters.MP4

### Your environment
* Adguard 2.5.0 (110)
* All devices

**Comment by IvanIin** [comment]
fixed in 122
