### ISSUE TITLE
Invert Whitelist does not work on Safari for iOS

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#859]
Expected behavior: When enabled, ads in every site outside of the whitelist should be unblocked

What actually happens: Ads are blocked everywhere

**Comment by aspasskaya** [comment]
Failed to check. 
- AdGuard doesn't save changes in Advanced settings section for 'Inverted whitelist' and 'Use simplified filters' #880

**Comment by aspasskaya** [comment]
The problem still exists.
