### ISSUE TITLE
AdGuard Pro 2.1.1.165 blocks internet connection

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForiOS#865]
Since iOS 12.1, AdGuard prevents users from accessing the internet when a type of connection changes (maybe in some other cases as well). Happens in the full tunnel modes. You won't be able to reproduce it a will in 100% of attempts though.

The "Restart when network changes" is enabled.

### Steps to reproduce

1. Enable AdGuard
2. Go out of the Wi-fi zone or enable/disable the Airplane mode 

### Expected behavior

AdGuard restarts the protection, the connection works as before

### Actual behavior

The internet does not work. If you go out of the Wi-fi zone, you may notice that you're still 'connected' to the same hotspot and there's no connection. Used to work fine before the 12.1 update

### Customer ID 

You can find a screen recording here - 1431791, will update it with a better one if needed

### Your environment

* Device model and storage size: iPhone X, iPhone 7
* Operating system and version: 12.1
* Browser (e.g. Safari) all
* Wi-fi or mobile internet connection: when switching from one to another

**Comment by planet0** [comment]
Same issue on an iPhone 8 Plus.

**Comment by TheHasagi** [comment]
"Restart when Network Changes" should be enabled.
