### ISSUE TITLE
Roadmap for AdGuard Pro on iOS?

### ISSUE THREAD

**Issue by tomiams** [AdguardTeam/AdguardForiOS#866]
I'm unsure if this topic has already been tackled, if so, pardon me & please refer me to the appropriate place.

The recent halt in development in AdGuard Pro due to the weird App Store regulations has left many unclear on where this crucial project is heading. Perhaps a short article to tackle that?

I would have to ask the question of wether the app store is the only way to an iOS device? 
iOS configuration profiles have been used by many developers and they let you install their apps, many of which are against the App Store guidelines, by completely circumventing the App Store.
I'm unaware if that is something you considered, just throwing it out there in hopes of a solution.

Some features are somewhat overdue like Shortcuts/Siri integration to implement the starting and closing of AdGuard DNS VPN through workflows, a way to circumvent the 50,000 safari rule limit by the content blocking module, adding custom user filter subscriptions, and some of the android-version features (the awesome apps management, proxy/tor, and so on)

I realize that the majority of these features are not possible with App Store regulations and iOS sandboxing, but could it be time to leave the app store behind?

In all cases, if there is already a TestFlight alpha/beta ongoing, I'd like to jump onboard.

**Comment by ameshkov** [comment]
In coming weeks we'll announce the open beta test of AdGuard for iOS 2.0.

At first, we are concentrating on the content blocking part of it, and there are a lot of new stuff there including multiple content blockers and custom filter subscriptions. AG Pro will be kept unchanged for some more time until we polish the new features.

**Comment by tomiams** [comment]
That's very good to know. I'll keep an eye out for the beta program!

**Comment by Zayatoshi** [comment]
hi. good news. is it possible to participate in the beta of the V3 please?

**Comment by planet0** [comment]
> In coming weeks we'll announce the open beta test of AdGuard for iOS 3.0.

Hi @ameshkov is there any news or updates with the open beta test or similar? Currently on Nightly for Windows, macOS and Android but the only one left out is iOS.

**Comment by ameshkov** [comment]
@planet0 internal testing at the moment. Too many bugs to call it a public beta yet:(

**Comment by planet0** [comment]
@ameshkov No problem, I appreciate the update!
