### ISSUE TITLE
Adguard doesn't count enable custom filters 

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#869]
### Steps to reproduce
1. Go to Custom filters and add a filter
2. Go back to the previous screen

### Expected behavior 
The added filter enabled and count in custom filters group correctly.

### Actual behavior
The added filter enabled and doesn't count in custom filters group correctly.

#
https://uploads.adguard.com/Custom_filters_group_doesnt_count.MP4

### Your environment
* Adguard 2.5.0 (111)
* Operating system and version: (ios 12.1)

**Comment by aspasskaya** [comment]
The problem still exists.
! Also, if we delete the custom filter, it doesn't count in custom filters group correctly too.
![image](https://user-images.githubusercontent.com/43952607/50892766-4e778a00-1410-11e9-8a1c-790ba9e92c02.png)
# 
https://uploads.adguard.com/assa_mu03t.MP4
# 
https://uploads.adguard.com/assa_mk16m.MP4

**Comment by aspasskaya** [comment]
The problem is still exist. 
![image](https://user-images.githubusercontent.com/43952607/54937117-df043780-4f34-11e9-9085-b4b5c615ddaa.png)
![image](https://user-images.githubusercontent.com/43952607/54937131-e4618200-4f34-11e9-8af8-c5d42d09e352.png)

**Comment by zzebrum** [comment]
also:
<details>

![IMG_626C577B4487-1](https://user-images.githubusercontent.com/44832195/55560563-28087880-56f9-11e9-99c0-7d3b2f7fb435.jpeg)


</details>
