### ISSUE TITLE
Another filter update issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#87]
I also have error in Adguard for iPad when I want update filters - https://www.dropbox.com/s/a4kipvl0l5tm17w/Zdj%C4%99cie%2004.05.2016%2C%2013%2042%2036.png?dl=0
I think it is related with Polish filter (Adblock polskie reguły), because if I disable Polish filter I does not have an error.
Can you check this?

RVI-479-68768

**Comment by ameshkov** [comment]
@Alex-302 this is the same issue with regular expressions with negative loopback.

**Comment by ameshkov** [comment]
We should exclude it from all filters for now.

**Comment by ameshkov** [comment]
Ah, got it, one more pattern to exclude:
```
\/\/(?!
```

**Comment by ameshkov** [comment]
@evgeniy-ADG fixed, update will be available soon.
