### ISSUE TITLE
Unable to launch Adguard Assistant due to security policy

### ISSUE THREAD

**Issue by accountforadg** [AdguardTeam/AdguardForiOS#873]
A thousand words is not as good as a video.

https://mega.nz/#!YrwWiICJ!mZvKsUqanldBpMoubMum-v4q0z_o8e6eZWsZtea0K4Y

reproduced URL: https://www.zhihu.com/question/271346096

**Comment by accountforadg** [comment]
This problem has existed for a long time, regardless of the system version and software version.

**Comment by accountforadg** [comment]
This problem has existed for a long time (more than one year), regardless of the system version and software version.

**Comment by zzebrum** [comment]
Unfortunately, we can do nothing about this. It's not a bug, just a restriction from the website.
