### ISSUE TITLE
WiFi issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#879]
@adguard-bot commented on [Tue Dec 04 2018](https://github.com/AdguardTeam/AdguardFilters/issues/26506)

### Issue URL (Incorrect Blocking)
[https://itunes.apple.com/eg/app/adguard-pro-adblock/id1126386264?mt=8](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fitunes.apple.com%2Feg%2Fapp%2Fadguard-pro-adblock%2Fid1126386264%3Fmt%3D8)
### Comment
> Since updating my iphone to IOS 12 and till its latest version IOS 12.1 everytime I enable Adguard pro privacy module , iPhone loses its Wifi connection as you can see in attached photos which demonstrate that when I enable Adguard privacy module iphone loses Wifi connection and when I disable privacy module iphone reconnect to Wifi network and you should know that I use latest version of Adguard pro and that privacy module rules are up to date and I tried deleting adguard pro app and reinstall it from App store this didn’t fix the problem and that under Adguard pro’s advanced settings I enabled full tunnel mode (with VPN icon) and Restart when network changes option.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/0tLIrJP.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/OcQ09DI.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | iOS
AdGuard version: | 2.1.1
System wide filtering: | disabled
Simplified filters: | disabled
AdGuard DNS: | Other - System Default
Filters: | EasyList

**Comment by articrevised** [comment]
Same issue :/

**Comment by Goddess-Bastet** [comment]
Look under advanced settings>turn off ‘restart with network changes’.

**Comment by TheHasagi** [comment]
Unable to reproduce after the iOS update.
