### ISSUE TITLE
Add Fanboy Anti-Third Party Social filter

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#88]
Since I can no longer enable all the filter lists I want (now using all the small filters for my language and region except for the large easylist and easyprivacy lists) and preliminarily seem to be getting excellent coverage except for various facebook annonyances/ tracking. I would love it if you added the compact (only 63 filters) Fanboy Anti-Third Party Social filter list (https://www.fanboy.co.nz/fanboy-antifacebook.txt) as an option as it would plug a bad remaining hole and give excellent coverage with my combination of filters.

HGV-402-93379

**Comment by mmigi** [comment]
The "Anti-Facebook List" filter is added. Now you can find it by it's name 'fanboyAntifacebook' in our filter list.
