### ISSUE TITLE
AdGuard doesn't save changes in Advanced settings section for 'Inverted whitelist' and 'Use simplified filters' 

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#880]
### Steps to reproduce
1. Advanced settings -> enable all
2. Go back to the previous screen and back.

### Expected behavior
The 'Inverted whitelist' and 'Use simplified filters' settings enabled after changes.

### Actual behavior
The 'Inverted whitelist' and 'Use simplified filters' settings disabled after changes.

#
https://uploads.adguard.com/ScreenRecording_12-14-2018_13-34-18.MP4

### Your environment
* Adguard 2.5.0 (112)
* All devices

**Comment by zzebrum** [comment]
@IvanIin not fixed!
