### ISSUE TITLE
Rules in subscriptions blcok the domain, but not the www hostname

### ISSUE THREAD

**Issue by Imagnobody** [AdguardTeam/AdguardForiOS#882]
![d7ef9d39-65e0-4f48-adba-5d49ba899c66](https://user-images.githubusercontent.com/22177457/50043542-04211880-00b1-11e9-9200-5ad9c2dd1a61.jpeg)
![0435b483-cdbe-4766-a8bd-66491bf63ec5](https://user-images.githubusercontent.com/22177457/50043543-04211880-00b1-11e9-8cb1-0b6d686313e0.jpeg)
![30c30f92-8e40-4f6e-903a-dbcd93e59727](https://user-images.githubusercontent.com/22177457/50043544-04211880-00b1-11e9-80fc-d0329dbda6fb.jpeg)
![61c4e09e-6636-4938-9e74-cda1bf517e6f](https://user-images.githubusercontent.com/22177457/50043545-04b9af00-00b1-11e9-9027-edca1304395c.jpeg)
![d4e5a1f7-6396-485d-9e90-c00c74d5e8b0](https://user-images.githubusercontent.com/22177457/50043546-04b9af00-00b1-11e9-95cf-6b6a595a8414.jpeg)
![b29657e8-d5f5-4da2-a04a-191948ee299c](https://user-images.githubusercontent.com/22177457/50043547-04b9af00-00b1-11e9-8de8-49f96dc27b26.jpeg)

Please delete this if this is just me misunderstanding network concepts,
but judging from inconsistent behavior, I assume its a bug.

When going to websites in safari that are blocked in one of my subscriptions,
the domain is blcoked, but then it gets redirected to a www hostname of the same site, and loads successfully.

However when I try a domain that’s in my self edited blacklist, the www hostname gets blocked as well (am sure that the blacklist only contains the domain name without www), which I assume is the correct behavior.

Screenshots added.

**Comment by zzebrum** [comment]
The thing is User filter and Subscriptions are working a little different. So in subscriptions, we working with rules like ||domain.com^ and the domain blocked exactly as the rule says. In the User Filter AG takes a domain name and can block both with www and without exactly like in your example.
