### ISSUE TITLE
Dark mode should not be only for premium users :)

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#884]
![image.png](https://images.zenhubusercontent.com/5bbf23f1307bc60241e3ae0e/f56232ca-ba49-4468-80cc-cf389ed00f1d)
![image](https://user-images.githubusercontent.com/43952607/51179206-ec1dfe00-18d5-11e9-9642-3bb074dddf67.png)
![image](https://user-images.githubusercontent.com/43952607/51188024-2398a480-18ee-11e9-8ce1-2eef187f2739.png)

**Comment by MercuryXIII** [comment]
It’s such a minor feature, why the hell would it be pay locked?

**Comment by IvanIin** [comment]
fixed in 121

**Comment by ameshkov** [comment]
The dark mode is back to be free :)

PS: Sorry guys, I admit I should've listened.
