### ISSUE TITLE
Add "DNS Privacy" settings section

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#887]
@AlikhanAliev we need a sketch for this section. 

Briefly, what we need there:
1. A short explanation of what DNS encryption is
2. ON/OFF switch + feature status (Your DNS queries are private/not private)
3. Custom DNS settings. The layout should look like what we have in AG for Android v3.0 (recommended DNS providers, custom DNS providers, adding a custom provider). Additionally, there should be a "DNS requests log" section.
4. Make it mandatory for a user to select a DNS provider when this feature is enabled first time.

**Comment by lancelot-moon** [comment]
How will you realize it?
VPN or MDM profile?

Will you use MDM profile change system DNS service?

**Comment by lancelot-moon** [comment]
Does iOS v12 support private DNS?

https://medium.com/cleanbrowsing/private-dns-on-android-pie-9-dns-over-tls-e6c0923bbcc2

Android v9 supports private DNS...

**Comment by ameshkov** [comment]
> VPN or MDM profile?

VPN

> Just carefully develop it due to Apple policy.

Yeah, we know that very well:)

> Does iOS v12 support private DNS?

Nope:(

**Comment by lancelot-moon** [comment]
I think that I roughtly know what you provide in the next regular AG for iOS.

Well, improved Safari content blocker and AG Pro v1.3 without DNS requests log, whitelist and blacklist.

But Taiwanese users who read news on line today will meet trouble with AG DNS service.
https://github.com/AdguardTeam/AdguardFilters/issues/27510#issuecomment-450295037

**Comment by lancelot-moon** [comment]
Except for local VPN profile, I hope that you can provide other methods to modify system DNS service.

I mean **APN profile or MDM profile**.
Let users **selectively** choose which mode to use if users don't wish local VPN mode.
I know your short-term plan of AG for iOS.
But hope that local HTTP proxy mode can be considered in the future.

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/abdb84ec-dba2-40f8-b39e-c24ca195a75e
