### ISSUE TITLE
No way for users to find out about FaceTime workaround for full-tunnel mode

### ISSUE THREAD

**Issue by sjmduncan** [AdguardTeam/AdguardForiOS#888]
### Steps to reproduce

1. Go to “Advanced Settings”
2. Scroll down and read the info text under the TUNNEL MODE section, noting that it does not mention any potential issues aside from compatibility with other VPN apps
3. Enable full-tunnel (with VPN icon) 

### Expected behavior

The info text under TUNNEL MODE should mention that FaceTime will only work in split-tunnel and the “unstable” full-tunnel mode. 

### Actual behavior

FaceTime is broken without warning and to get it working again I have to:
1. realise that it might be caused by AdGuard
2. somehow find the github issues related to this (#828 #778 #501)
3. eventually end up reading [this comment](https://github.com/AdguardTeam/AdguardForiOS/issues/778#issuecomment-388748796)

And then either select the “unstable” full-tunnel Mode or go back to split tunnel.

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Device model and storage size:iPhone SE 32GB, 6th gen IPad 32GB
* Operating system and version: iOS 12.1.1
* Wi-fi and mobile

**Comment by zzebrum** [comment]
perhaps we can mention the issue in [kb](https://kb.adguard.com/en/ios/solving-problems).

**Comment by sjmduncan** [comment]
> perhaps we can mention the issue in [kb](https://kb.adguard.com/en/ios/solving-problems).

That’s only slightly better than finding out via github issues but given that FaceTime is a default iOS app that a lot of people use, and that this seems specific to FaceTime(?) it would be waaaaay better to mention it in the info section for that setting in the app.

**Comment by zzebrum** [comment]
I've created a task [here](https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/291).

**Comment by vokain** [comment]
I have this problem with split tunnel mode too

**Comment by zzebrum** [comment]
@vokain try to check with another DNS server. If the problem is still reproducible, please send a log file to apple[at]adguard[dot]com

**Comment by vokain** [comment]
> @vokain try to check with another DNS server. If the problem is still reproducible, please send a log file to apple[at]adguard[dot]com

yep, very reproducible. CloudFare and Adguard servers it happens. Have submitted bug report via the app.

see:
https://www.icloud.com/photos/#0HtiR9nokC0gyVuQRB-ov5BCA

**Comment by ameshkov** [comment]
@vokain could you please the customer ID or send it to `apple@adguard.com` as well?

**Comment by vokain** [comment]
just  submitted an email to apple@adguard.com <mailto:apple@adguard.com>

thank you

**Comment by zzebrum** [comment]
@vokain  you haven't attached log files to your email. please reproduce the issue and send logs file to apple[at]adguard.com (AdGuard settings - Send feedback - Contact support - change the recipient here)
