### ISSUE TITLE
Add support for different hosts format

### ISSUE THREAD

**Issue by XxDarKxDukexX** [AdguardTeam/AdguardForiOS#889]
Add this support as when I subscribe to this link https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/Hosts.txt all of the hosts will give errors and block many normal websites which isn’t the purpose of the hosts

**Comment by lancelot-moon** [comment]
Domain format is early supported in AG Pro's filters subscriptions.
And AG Pro won't be updated for a long long time due to Apple's policy...

**Comment by zzebrum** [comment]
indeed you can subscribe to hosts file via subscriptions in AdGuard Pro.
