### ISSUE TITLE
32-bit models and compilation

### ISSUE THREAD

**Issue by vit9696** [AdguardTeam/AdguardForiOS#89]
Hi,

Thanks for opensourcing Adguard. You left a mistake in  
`AdguardForiOS-master/AdguardExtension/project.xcconfig`
and ACTION_JAVASCRIPT_SELECTOR points to a local file. Unsure if the commented out url is the correct one though :)  

Another issue is a 64-bit requirement. Apple does not recommend uploading 64-bit content blockers to App Store, but the APIs are actually supported e.g. if you sideload the app. Removing "Required device capabilities" → arm64 and adding armv7 and armv7s to the list of valid architectures allows Adguard to work on all the models supporting iOS 9. I do recommend you fixing the README, and it would be nice if your App Store version also supported this, perhaps, without explicitly stating it. 

Vit

**Comment by Stillness-2** [comment]
About local file - 26cba8d

**Comment by ameshkov** [comment]
> Another issue is a 64-bit requirement. Apple does not recommend uploading 64-bit content blockers to App Store

They won't allow it into the app store without it. However, I guess @Stillness-2 could add some info about sideloading to readme.

**Comment by worldsdream** [comment]
I have seen another adblocker, that is accepted in the appstore. It shows in the information that it will work on ios 8, 9 and 10. On both 32 and 64 but devices. It does also block ads in other apps.

**Comment by vozersky** [comment]
not relevant, closing


@worldsdream sorry for not coming back to you that time :(
