### ISSUE TITLE
The filters in the default list is not updated 

### ISSUE THREAD

**Issue by visvital** [AdguardTeam/AdguardForiOS#891]
The update date for the filters from filters section doesn't match the date specified on the page of the filter. Have to use the privacy filters instead to get the last version.

### Steps to reproduce

1. Open Filters
2. Select any filter (ex. Russian)
3. Observe the last modified date 
4. Last modified: 28/12/2018 00:30
5. Navigate to the Filter Homepage
6. Navigate to View All Rules
7. Observe the time updated
8. TimeUpdated: 2019-01-08T00:30:36+03:00

### Expected behavior

After #3 Last modified value should be TimeUpdated: 2019-01-08 00:30
### Actual behavior

After #3 Last modified value Is 28/12/2018 00:30

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Device model and storage size: (e.g. iPhone 6s 64gb)
* Operating system and version: (e.g. 10.3.1)
* Browser (e.g. Safari)
* Wi-fi or mobile internet connection

**Comment by zzebrum** [comment]
@visvital it seems that filters were not updated in general app settings on min screen.
