### ISSUE TITLE
custom filter not accepted by ios app

### ISSUE THREAD

**Issue by sschmiedleitner** [AdguardTeam/AdguardForiOS#892]
For a specific news site I need a custom filter in order to prevent adblocker detection. Specifically I need to be able to remove a cookie.

Therefore, I would like to add following custom filter:
`derstandard.at#%#document.cookie = "MGUID=";`

but unfortunately is is marked as red and not being accepted.

This is also not working:
`derstandard.at##script:inject(cookie-remover.js, /^MGUID/)`

I am using adguard on my iphone - latest version.

**Comment by krystian3w** [comment]
iOS no support scriptlets.

AdGuard also no convert uBO scriptlet syntax now. This is feature request.

**Comment by sschmiedleitner** [comment]
But how can I solve this then. Is it possible to solve it with the uBO scriptlet syntax then?

**Comment by krystian3w** [comment]
uBO/Nano Defender also troubles to defend this anti-adblock walls (one activates others not).


For me, it only helps to pass the next advertising scripts and then cut out what they cut out so that the systems will not comment.

**Comment by sschmiedleitner** [comment]
Sorry I cannot follow...
Is there another app for ios "ublock origin" or "nano defender" that would help? Unfortunately I haven't found them in the app store...

@krystian3w 
Could you please describe the steps in more detail how you solved it?

**Comment by sschmiedleitner** [comment]
Thank you very much, seems to work, will test it a bit!

**Comment by sschmiedleitner** [comment]
Ok after some testing we could proceed with the needed rules to add to the filterlist by https://github.com/AdguardTeam/AdguardFilters/issues/28046?

**Comment by zzebrum** [comment]
Such rules are not supported on iOS
