### ISSUE TITLE
Design and menu items should be the same (Custom filters and Whitelist/User filter sections) 

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#893]
1. delete "+" in the upper right corner in Whitelist and User filter sections
2. a different view "+ add a ... " 
3. there is no menu at the bottom 
4. description in the custom section

![image](https://user-images.githubusercontent.com/43952607/50899822-52150c00-1424-11e9-9389-e51124beecd0.png)

**Comment by aspasskaya** [comment]
## User filter / Whitelist / Whitelist (inverted)
1. Delete "+"
2. Menu items should be the same as in the custom filters - 'Add a filter' 
![image](https://user-images.githubusercontent.com/43952607/54926768-030a4d80-4f22-11e9-8548-5bac9764e51f.png)

**Comment by IvanIin** [comment]
fixed in 127
