### ISSUE TITLE
Can't use any "advanced" rules in custom filter

### ISSUE THREAD

**Issue by imkzh** [AdguardTeam/AdguardForiOS#900]
i'm unable to add any "advanced" custom filters just like:
    
    example.org$$script[data-src="banner"]
    example.org##div:matches-css(position:fixed)

but some other simple rule works fine, like:

    example.org##div

is that because i'm using a free version of adguard?

### Steps to reproduce
1. select custom filter in main menu

2. enter:

    example.org$$script[data-src="banner"]

(Note: this line would be completely correct in syntax, as it is copied form documentation)

3. tap `Done` at top right corner.

4. result: newly added line being highlighted in red and cannot be added.

### Screenshot:
![eadf3e96f6363c6a35c752eb5e0bbe03](https://user-images.githubusercontent.com/5917425/51542410-28cd9480-1e96-11e9-8a13-d00b37582cce.png)

### Your environment
* Device model and storage size: iPhone X 64GB
* Operating system and version: 12.1.2
* Browser: mobile Safari
* Wi-fi or mobile internet connection: irrelevant
* App Version: 2.1.2(101) (fresh install, free version)

**Comment by imkzh** [comment]
I uploaded `state.txt`, `filter.gz`, etc.
and get my USER ID: `2100236`

**Comment by zzebrum** [comment]
That's because Safari doesn't support such rules.
