### ISSUE TITLE
custom filter editor automatically discard changes when it is showed for a second time

### ISSUE THREAD

**Issue by imkzh** [AdguardTeam/AdguardForiOS#901]
Custom filter editor automatically discard changes, and revert to last saved state when:
* you switch to another app and switch back
* you reached the control center while editing
* you reached the notification center while editing
* device is locked and unlocked while editing
* you slightly swipe back to main menu(but not letting the view go)

this is super annoying when you are checking some thing like `kb.adbuard.com`(official documentation) and the editor keeps reverting your edit again and again.

**Comment by imkzh** [comment]
I've got the screen captured for better illustration:
![ezgif-4-8f7ccdd61729](https://user-images.githubusercontent.com/5917425/51547622-a4810e80-1ea1-11e9-99ec-bf3c18a7627d.gif)

**Comment by zzebrum** [comment]
In the new version there will be different editor, so the issue should not happen there.
