### ISSUE TITLE
First do system-wide HTTPS filtering for only browsers?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#904]
@ameshkov

If the new AG for iOS can only do system-wide HTTPS filtering for all browsers on iOS, it more attracts people.

**Users want AG filters to work in not only Safari but also other browsers!**

Don't need JB.
Users can manually set AG certificate as root trusted certificate!
https://support.apple.com/en-us/HT204477

Compared with Android, Android v7 and the above already don't trust user certificates unless having root access and moving certificates to system certificate store.

Well, maybe even apps management (firewall).

How about your thought?
Do you want to try?

**Comment by lancelot-moon** [comment]
May you seriously develop HTTPS filtering for only browsers **after** moving the new features (improvement of Safari content blocker and encrypted DNS proxy) of regular AG v3 to AG Pro since Apple has approved the update of AG Pro?

You know Safari doesn't support advanced adblock rules.
If AG Pro can do system-wide HTTPS filtering for only browsers first, there are many benefits.
Chrome for iOS will be also filtered.

**Comment by ameshkov** [comment]
I seriously doubt we will be allowed to do it by Apple
