### ISSUE TITLE
DNS server never starts with too many rules

### ISSUE THREAD

**Issue by vlldk** [AdguardTeam/AdguardForiOS#905]
The DNS server in AdGuard Pro never starts if the user is subscribed to too many rules 

### Steps to reproduce
1. Subscribe to these host rules in Privacy Settings
`https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
http://sysctl.org/cameleon/hosts
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://hosts-file.net/ad_servers.txt`

### Expected behavior
AdGuard Pro’s DNS server starts and blocks all ~150.000 domains

### Actual behavior
The DNS server never starts.  
It works with just these domains:
`https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt`

### Your environment
* Device model and storage size: iPad Air 2, 64gb
* Operating system and version: 12.1.4
* WiFi

**Comment by lancelot-moon** [comment]
Simply decrease your subscriptions.
Limit rules in 90k.

**Comment by zzebrum** [comment]
@vlldk 
Actually, @lancelot-moon is right, the limit is ~90k rules.
