### ISSUE TITLE
Stuck on (20%) loader

### ISSUE THREAD

**Issue by iMehroz** [AdguardTeam/AdguardForiOS#906]
### Steps to reproduce

1.
2.
3.
4.

### Expected behavior
Pages load without stopping at 20% of the website.

### Actual behaviour
Always stop at 20% of loading, this is with all websites and when I use AdGuard Pro with Safari. When it’s off then pages load. The issue is while Ad Guard is ON, the website stuck at 20% and I have to manually press the refresh button OR to press the URL and then press the GO button on the keyboard to load the page again. It doesn’t load as normal. Always stuck at that. I have a screenshot to show.

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Device model and storage size: (e.g. iPhone 6s 64gb)
* Operating system and version: (e.g. 10.3.1)
* Browser (e.g. Safari)
* Wi-fi or mobile internet connection

**Comment by zzebrum** [comment]
@iMehroz AdGuard version? Is DNS filtering enabled?

**Comment by TheHasagi** [comment]
@iMehroz 

Closed. Will be reopened if needed.
