### ISSUE TITLE
Is AdGuard on iOS dead?

### ISSUE THREAD

**Issue by antnythr** [AdguardTeam/AdguardForiOS#907]
I’m using AdGuard Pro and I know that product is dead. AdGuard non-pro hasn’t had any updates for a very long time.

There was a post here at least 3 months ago saying “in the coming weeks” there would be some kind of status update however that post has somehow disappeared and there are no details about the future of the product.

Can we expect an update anytime soon or is this project abandoned?

**Comment by ameshkov** [comment]
Yes, there will be an update, and I am sorry that the new update takes SO LONG.

The app was rewritten from scratch and we are in process of fixing bugs and debugging it.

**Comment by ameshkov** [comment]
Regarding the ETA, we'll announce the public beta test soon.

**Comment by mo0424** [comment]
I have sent you email, I want to be part of public beta test. Email title is “AdGuard beta test”

**Comment by zzebrum** [comment]
@mo0424 I'm not sure I can find your email. Please apply for beta test here: https://adguard.com/en/beta.html

**Comment by mo0424** [comment]
Email is,

mohsin0424@hotmail.com<mailto:mohsin0424@hotmail.com>

Sent from my iPhone

On Mar 14, 2019, at 5:11 AM, zzebrum <notifications@github.com<mailto:notifications@github.com>> wrote:


@mo0424<https://github.com/mo0424> I'm not sure I can find your email. Please apply for beta test here: https://adguard.com/en/beta.html
