### ISSUE TITLE
Calls in telegram app conflicts with Adguard

### ISSUE THREAD

**Issue by one2gov** [AdguardTeam/AdguardForiOS#910]
### Steps to reproduce
1. Enable Adguard
2. Try to make a call through Telegram app

### Expected behavior
Normal phone call

### Actual behaviour
The call can't be accepted. If I make a call, there is interactions every second

### Customer ID 
Doesn't have one when click send report. I bought a lifetime license. 

### Your environment

* Device model and storage size: (e.g. iPhone se 32gb)
* Operating system and version: (e.g. 10.2.1)
* Telegram app
* Wi-fi and mobile internet connection

**Comment by zzebrum** [comment]
@one2gov  which AdGuard version do you use? DNS server?

**Comment by one2gov** [comment]
Pro version
Default Adguard DNS

**Comment by zzebrum** [comment]
we've checked with AdGuard DNS and each tunnel mode and couldn't reproduce the problem. 
Switch to another DNS server, check if it helps.

**Comment by one2gov** [comment]
A had this issue with calls on wifi in 2 different apartments (and routers), but yesterday I tried to call with dns from lte (while simultaneously tethering my friend from my lte) and everything worked perfect. I'll return with a test from wifi router in several days.

**Comment by zzebrum** [comment]
@one2gov yep, also check with your ISP default DNS servers.

**Comment by one2gov** [comment]
Couldn't recreate the problem
¯\_(ツ)_/¯
