### ISSUE TITLE
Rules count shows 0 after custom filter was added

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForiOS#912]
v3.0.0(117)

### Steps to reproduce

1.go to Settings - Filters - Custom

2.add a custom filter - save it

3.tap on the custom filter to see the details

### Expected behavior
Rules count shows the right number of rules in the filter

### Actual behavior
Rules count shows 0 rules.

**Comment by aspasskaya** [comment]
The problem still exist.
![image](https://user-images.githubusercontent.com/43952607/57626109-e5f71000-759d-11e9-9970-672c303c1f58.png)

**Comment by IvanIin** [comment]
fixed in 127
