### ISSUE TITLE
Suggest to use Chinese date format for filters' update time in Chinese interface.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#913]
Suggest to use Chinese date format for filters' update time in Chinese interface.
Use 24-hour clock.
Don't need AM or PM.
ex: March 08, 2019 19:23:56
Chinese date format:
2019年3月8日 19:23:56
("YYYY年MM月dd日 HH:mm:ss")

Because AG for iOS v3 testflight version isn't released, I can't check its Chinese date format.
Please note it.
If you already did it, please ignore this request.
Thanks.

**Comment by ameshkov** [comment]
@lancelot-moon please check if it works okay in the current version

**Comment by lancelot-moon** [comment]
No, it's like so.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/hP37jF2.png)
</details><br/>

Hope it can be modified as the below.
21.05.19
-> 2019年5月21日

Thanks.

**Comment by lancelot-moon** [comment]
This was fixed in the latest testflight version.
