### ISSUE TITLE
Enable filters groups after update

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForiOS#915]
It seems that the enabled filters list is correct, but filters groups are disabled. Despite the fact that content blockers are disabled by default in Safari settings, we should enable filters group after an update.

**Comment by zzebrum** [comment]
Currently, it's using #852 algorithm for enabling filters group after an update which is wrong. For an update from previous version Filter group should be enabled if it has filter(s) enabled in it.

**Comment by zzebrum** [comment]
@IvanIin it's still working incorrectly after an update from previous v2.0

**Comment by IvanIin** [comment]
fixed in 125

**Comment by zzebrum** [comment]
@IvanIin @ameshkov 
after update from v2.5 to v3.0 on iOS 11 filters group status disabled :(

**Comment by ameshkov** [comment]
@zzebrum please test update from the latest stable version
