### ISSUE TITLE
An option to disable User Filter

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForiOS#919]
It may be useful since we don't have a common editor now.

**Comment by lancelot-moon** [comment]
From here:
https://github.com/AdguardTeam/AdguardForiOS/issues/596

One switch for enabling or disabling the user filter / whitelist in SAFARI Content Blocking:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/9xusgPj.png)
</details><br/>

I wish switches for custom filters, too.

**Comment by zzebrum** [comment]
done in v4.0
