### ISSUE TITLE
Separately enable or disable each rule (domain) in the user filter & whitelist in SAFARI Content Blocking

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#920]
Please let us separately enable or disable each rule (domain) in the user filter & whitelist in SAFARI Content Blocking, 

a. Tap each rule (domain) for editing, deleting, cancelling and ok.
The layout about the rules in user filter of AG for Android is the reference!
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/OQ2X9Rw.png)
</details><br/>

b. The rules (domains) are automatically sorted according to names or time.

From here:
https://github.com/AdguardTeam/AdguardForiOS/issues/596

**Comment by zzebrum** [comment]
closed as dup #602
