### ISSUE TITLE
Hope the interface adapts to the iPhone XR

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#921]
Hope the interface adapts to the iPhone XR, and the current version shows blurred interface and font on the XR, which greatly affects the experience.

**Comment by zzebrum** [comment]
Can you please provide with a screenshot or video of how it looks on iPhone XR?

**Comment by Andjustsoso** [comment]
The UI and fonts look not clearly on XR, it feels like a picture is simply enlarged. But the screenshot looks better than the actual display.
[Image]
获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: zzebrum <notifications@github.com>
发送时间: 星期五, 三月 22, 2019 5:48 下午
收件人: AdguardTeam/AdguardForiOS
抄送: Andjustsoso; Author
主题: Re: [AdguardTeam/AdguardForiOS] Hope the interface adapts to the iPhone XR (#921)


Can you please provide with a screenshot or video of how it looks on iPhone XR?

―

**Comment by Calefornia** [comment]
I've tested on the XR, and it looks fine. There are no issues with fonts or layout positioning. Will attach screenshots later

**Comment by zzebrum** [comment]
@Calefornia thanks!
