### ISSUE TITLE
[Question] ETA on 3.0 release?

### ISSUE THREAD

**Issue by gurgun-dayioglu** [AdguardTeam/AdguardForiOS#922]
Hey I was wondering if there is an ETA on the new 3.0 release...

**Comment by F3000** [comment]
Interested too.

**Comment by ameshkov** [comment]
Guys, I prefer not to give ETAs because literally every time I do it, we miss it by a mile.

You can see by the new issues that the internal testing is in progress, there are some bugs to handle.
