### ISSUE TITLE
Moonwalk ( плеер ) AdGuard не даёт выбрать качество

### ISSUE THREAD

**Issue by XNoInformationX** [AdguardTeam/AdguardForiOS#923]
### Steps to reproduce

hdrezka.ag
1. Выбираете любой фильм/сериал
2. Заходите 
3. Жмёте копку старт на плеере 
4. Пытаетесь выбрать качество, вместо этого он останавливает и запускает видео 

### Actual behavior

<details><summary>Screenshot:</summary>
Не приложу, так как не выйдет это заснять

</details>

### Your environment

* Device model: iPad Pro
* Operating system and version: 10.3.3
* Browser - Safari
* Wi-fi or mobile internet connection - Wi-Fi

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardFilters #31602](https://github.com/AdguardTeam/AdguardFilters/issues/31602) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
@XNoInformationX перенёс в подходящий репозиторий.
