### ISSUE TITLE
Error landscape orientation in 'Add custom DNS server'

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#924]
### Steps to reproduce
1. Settings -> DNS privacy -> Server -> Add custom DNS server
2. Enable autorotate
3. Rotate the device to landscape orientation

### Actual behavior
![image.png](https://images.zenhubusercontent.com/5bbf23f1307bc60241e3ae0e/1e51b2d8-ab0f-4ca6-834c-0931efcf7693)

### Your environment
* Adguard 3.0.0 (118)

**Comment by TheHasagi** [comment]
The UI bug:

<details>

![image](https://user-images.githubusercontent.com/37797229/57711514-8705c980-7677-11e9-803d-51244803eb1d.png)

![image](https://user-images.githubusercontent.com/37797229/57711530-8ec56e00-7677-11e9-910f-e9cc9087e571.png)

![image](https://user-images.githubusercontent.com/37797229/57711548-95ec7c00-7677-11e9-9100-1e89f39ba3f7.png)


</details>

**Comment by zzebrum** [comment]
You either not let scrolling or show `Save and select` and `Cancel` buttons here:

<details>

![IMG_9DBC41A89834-1](https://user-images.githubusercontent.com/44832195/62785587-9dca8980-bac9-11e9-9a81-1493bb1e6090.jpeg)

![IMG_328BC2C4395A-1](https://user-images.githubusercontent.com/44832195/62785606-a753f180-bac9-11e9-8645-96fc78e078d3.jpeg)


</details>
