### ISSUE TITLE
Remove duplicate "Select this server" button in the DNS privacy section

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#925]
Settings -> DNS privacy -> Server -> Choose any server

### Actual behavior
![image](https://user-images.githubusercontent.com/43952607/54929673-03f1ae00-4f27-11e9-94a0-077bfd342894.png)

**Comment by zzebrum** [comment]
It would be just 'Select' button.

**Comment by IvanIin** [comment]
fixed in 121
