### ISSUE TITLE
Add a “secure search” icon in DNS server section

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#926]
### Steps to reproduce
Settings -> DNS privacy -> Server -> AdGuard DNS Family or Cisco OpenDNS with Family Shield

### Expected behavior
- Search icon 
- Green color
![image](https://user-images.githubusercontent.com/43952607/54930704-c8f07a00-4f28-11e9-9021-66cccb6cd87b.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/43952607/54930641-aa8a7e80-4f28-11e9-860b-09f2bf41834b.png)

**Comment by IvanIin** [comment]
fixed in 121
