### ISSUE TITLE
No blocking the ad

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#93]
Using current ios and adguard version. and using default filter + 20 other. no blocking!! if add in custom list and reload this site, not working. ad come back!!

http://www.notebookcheck.com/Samsung-Smartphones-mit-flexiblem-Display-im-naechsten-Jahr.167522.0.html

![image](https://cloud.githubusercontent.com/assets/13907702/15987577/c0fe7130-302c-11e6-9968-0e67f8737abe.jpeg)

**Comment by ameshkov** [comment]
Wrong repo, moved it to:
https://github.com/AdguardTeam/AdguardFilters/issues/2328

**Comment by Alex-302** [comment]
@ghost
please update German filter and check again
