### ISSUE TITLE
Filter update error when enabled 'auto-update over wi-fi only'

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#930]
### Steps to reproduce
1. Advanced settings -> Enable 'Auto-update over wi-fi only'
2. Disable wi-fi, only Cellular network
3. Home -> update filters
4. Advanced settings -> Disable 'Auto-update over wi-fi only'
5. Home -> update filters

### Expected behavior
Filters should be updated.

### Actual behavior
Filter update error.

**Comment by ameshkov** [comment]
Cannot reproduce this issue on .134
