### ISSUE TITLE
Better UI  for reporting an issue 

### ISSUE THREAD

**Issue by F3000** [AdguardTeam/AdguardForiOS#933]
Hello , 

when I want to create a report I have difficult to see all the options from the drop down menu because the keyboard hides some of the entries

Would be nice when this drop down can be replaced by I iOS own drop down funtion.

**Comment by F3000** [comment]
![ACFB842D-2971-43D7-8A6A-B74DC8AD12F1](https://user-images.githubusercontent.com/8161283/55187271-d613a000-5198-11e9-8788-07384f37f584.png)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/ReportsWebApp #193](https://github.com/AdguardTeam/ReportsWebApp/issues/193) via [**ZenHub**](https://www.zenhub.com/)
