### ISSUE TITLE
Unable to update apps via App Store while AdGuard Pro is enabled

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForiOS#935]
### Steps to reproduce
1. Enable the protection
2. Try to update any application via App Store
3. Won't update

### Expected behavior
Apps should update

### Actual behavior
Apps won't update

<details><summary>Screenshot:</summary>
Not applicable
</details>

### Customer ID & Logs
2146938

### Your environment
* Device model and storage size: unspecified iPhone
* Operating system and version: iOS 10.3.3
* Browser: N/A
* Wi-fi or mobile internet connection: Both
* DNS: AdGuard Default, split-tunnel

**Comment by Loeivy** [comment]
check if "iosapps.itunes.apple.com" is in any of your DNS blacklists, if it is, remove it - it appears to break at least app updates (if not all app downloads from App Store)

**Comment by dmitall** [comment]
No, this process is not included in the dns blacklist. Updating applications does not occur, only through a mobile connection - several operators, if you turn on Wi-Fi everything works.

**Comment by Loeivy** [comment]
If you are using Full-Tunnel and have cellular data for Adguard disabled, try enabling it, that solved Adguards DNS feature not working at all for me!

**Comment by dmitall** [comment]
As a result, I added apple.com to the white list and it all worked!

**Comment by TheHasagi** [comment]
Unable to reproduce the issue, looks like it depends mostly on what DNS server is selected.
