### ISSUE TITLE
Add ability to comment in privacy black/whitelist

### ISSUE THREAD

**Issue by L-i-v-y** [AdguardTeam/AdguardForiOS#937]
For finding new tracking mechanics and blacklisting those it would be nice to have an option to add comments to the privacy black and whitelists; either full lines only or next to an entry. also it would be very helpful to be able to comment certain entries in order to see what DNS request block may cause a service to break (currently the only way of doing this is by breaking the entry with a character for full lines, but there is no way of adding a comment next to an entry).
For readability in the case of testing, paragraph functionality in the list would also be a nice addition (would be obsolete with the option to comment by commenting empty lines).

**Comment by lancelot-moon** [comment]
Apple doesn't allow AdGuard Pro updating unless removing system-wide blocking (blacklist, whitelist and filters subscriptions).
https://adguard.com/en/blog/adguard-pro-discontinued/

**Comment by Loeivy** [comment]
Thank you for the information, it slipped through my knowledge that another block happened. What do the 3.0.0 requests refer to then? Is there any Testflight one can apply to join in on?

**Comment by lancelot-moon** [comment]
Free AG for iOS will be updated to v3 with in-app purchasing advanced features for Safari content blocker and dark mode.
No system-wide blocking features.
(Well, it will support encrypted DNS changer.
Users can choose DNS service with content blocking.)

AG Pro for iOS can't be updated.
Stay in v2.1.1.
