### ISSUE TITLE
Make the whole Filter group name area clickable for enabling\disabling

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#939]
Filter groups:
- Ad blocking
- Privacy
- Social Widgets
- Annoyances
- Security
- Other
- Language-specific
- Custom

![image.png](https://images.zenhubusercontent.com/5bbf23f1307bc60241e3ae0e/a1e1ef1f-0609-4f1c-9318-75f41bf7525e)

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForiOS/issues/1033
