### ISSUE TITLE
No blocking if comes ios update

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForiOS#94]
I using ios 9.3.3 public beta 1, then loading public beta 2, ios device restart and install this update. 10 min done. now open safari and go to website woth ad. you can see no blocking.

then I see in settings from safari, the app is on!! in this case disable and activate again. go to website again, now blocking!!

this is bug!! always if update new ios version!! 

please fix

**Comment by ameshkov** [comment]
So, if I am getting this right, when you update iOS version, ad blocking is gone until you manually turn it off and on again?

**Comment by lilghost** [comment]
@ameshkov 
Yes. Can you reproduce? I can to 100%. Other content blocker same issue e.g from mozilla

Bug in the app? iOS api issue?

**Comment by ameshkov** [comment]
Sounds like an iOS issue, it'd better to report it to Apple.

**Comment by ameshkov** [comment]
Here is a bug in bugzilla (maybe posted by you?)
https://bugs.webkit.org/show_bug.cgi?id=158874

@Stillness-2 could you please take a closer look at this issue?
