### ISSUE TITLE
Fix the addition of an empty custom DNS server

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#945]
### Steps to reproduce
1. Go to DNS settings and  'Add custom DNS server'
2. Tap on 'Save and select'

### Expected behavior
Custom DNS server doesn't added and error message applied.

### Actual behavior
![image.png](https://images.zenhubusercontent.com/5bbf23f1307bc60241e3ae0e/5b394ab0-d0e6-43c5-a5ed-37ce54d21e37)

![image](https://user-images.githubusercontent.com/43952607/57636925-d8985080-75b2-11e9-8a21-f5ed8c816dc9.png)

### Your environment
* Adguard 2.5.0 (119)
* Operating system and version: (ios 12)

**Comment by zzebrum** [comment]
#917 dup
