### ISSUE TITLE
DNS Privacy is not working properly

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForiOS#948]
DNS Privacy is not working properly, if you choose the Cloudflare DNS (DoH/DoT) as upstream and no matter if it would be custom DNS or not, for example, DNS-over-HTTPS/DNS-over-TLS and open the [link](https://1.1.1.1/help)

See the screenshot:

![img](https://uploads.adguard.com/TheHasagikg4id.jpg)

**Comment by ameshkov** [comment]
Try the same with Android version.

It occurs to me that the bug is not on our side.

**Comment by lancelot-moon** [comment]
@ameshkov

No, if using Cloudflare DoH/DoT, it can detect.

But if using other DNS DoH/DoT, it shows "No" in the result.

AG for Android is such situation.

In that screenshot, he used Google DNS, not Cloudflare DNS.

No DoH or DoT...
Why?
