### ISSUE TITLE
Minor grammatical issues

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForiOS#95]
I've had no issues using the app but I did find a few very small, very minor grammatical items. Across your desktop app and extension, I noted that you're spot-on with this kinda stuff, so I thought I'd share a few of the omissions within the iOS app with you (see screenshots below).
![image](https://cloud.githubusercontent.com/assets/15856304/16014241/16989374-3199-11e6-8814-6b9d4329c6f7.png)

![image](https://cloud.githubusercontent.com/assets/15856304/16014281/4677013e-3199-11e6-8ce0-5598a27a9174.png)

id 1307027

**Comment by lilghost** [comment]
@evgeniy-ADG 
Please post your suggestion here. New grammatical version

**Comment by evgeniy-ADG** [comment]
Start description from the capital letter, add period in the end of the sentence, obviously.

**Comment by Stillness-2** [comment]
@mmigi Check please description for EasyPrivacy filter.

**Comment by worldsdream** [comment]
You added the missing "dot" behind period. It does show period. But the "dot" needs to be in small black. Like all the others. Only "this article" needs to be blue and bold. Please adjust correctly.

**Comment by Stillness-2** [comment]
![user_filter_add_rule](https://cloud.githubusercontent.com/assets/12689/16414057/871511be-3d46-11e6-9437-657cb378a9b5.png)

**Comment by worldsdream** [comment]
Perfect

**Comment by Stillness-2** [comment]
@worldsdream It seems that it is iOS bug. We don't know how to solve this problem on our level.

**Comment by mmigi** [comment]
Now *EasyPrivacy* filter description starts with a capital letter and ends with period.
