### ISSUE TITLE
Adguard blocks ads even when I don't have ad blockers enabled.

### ISSUE THREAD

**Issue by MoistTowellettes** [AdguardTeam/AdguardForiOS#954]
### Steps to reproduce

1.
2.
3.
4.

### Expected behavior

Adguard shouldn't block ads when I disable adblockers
![CD44A620-4E67-4EB3-ABA7-4144E1350246](https://user-images.githubusercontent.com/47674293/56220523-92dd7c00-6036-11e9-860a-9859821f92e7.png)

### Actual behavior

Adguard blocks ads when the adblockers are disabled.

<details><summary>Screenshot:</summary>

 

> [`@[</details>](url)`](url)

### Your environment

* iPad mini 4 with cellular
* iOS 12.2
* Safari
* Wi-fi

**Comment by Goddess-Bastet** [comment]
I’ve found you also have to disable AdGuard under disable adblockers within settings>Safari otherwise yes it still blocks ads even though it setting within AG is off.

**Comment by TheHasagi** [comment]
As I can see, the VPN is active what probably means that you didn't turn off the AdGuard, so the ads will be blocked till you turn AdGuard off.

**Comment by MoistTowellettes** [comment]
I want to use adguard but I don't want to block ads.
