### ISSUE TITLE
I want to use Adguard without having to block ads

### ISSUE THREAD

**Issue by MoistTowellettes** [AdguardTeam/AdguardForiOS#955]
### Steps to reproduce

1.
2.
3.
4.

### Expected behavior

If I disable adblockers adguard should not block any ads

### Actual behavior

Adguard blocks advertisements even if adblockers are disabled

<details><summary>Screenshot:</summary>

![29C61F1F-6BF9-44FF-B536-A5BA064A9A4E](https://user-images.githubusercontent.com/47674293/56456559-14d1eb80-633c-11e9-817b-b792e2f89af1.png)

</details>

### Your environment

* iPad mini 4 Wifi+Cellular 64gb
* iOS 12.2
* Safari
* Wi-fi

**Comment by Goddess-Bastet** [comment]
I’ve found you also have to disable AdGuard under disable adblockers within settings>Safari otherwise yes it still blocks ads even though it setting within AG is off.
I agree that disabling AdGuard should disable the Adblocker.

**Comment by MoistTowellettes** [comment]
I do not want to disable AdGuard, I only want to disable adblocking. That is a bug

**Comment by Goddess-Bastet** [comment]
As AdGuard is an ad blocker your bug report doesn’t make sense. The app is designed to block ads. This is not a bug. 
The only way to allow ads is to add the url to the whitelist. If you wish to turn off the adblocking then uninstall the app.
What do you expect the app to do if not block ads?

**Comment by MoistTowellettes** [comment]
I expect it to not block ads when I turn off the filters that block ads.

**Comment by Goddess-Bastet** [comment]
I agree in that if you turn off the ad blocking it should not continue to block ads but there’s still the Safari settings for adguard (which should turn off in theory when you disable adguard) so currently this continues to block ads.

**Comment by MoistTowellettes** [comment]
AdGuard has a bug, just fix it.

**Comment by Goddess-Bastet** [comment]
I’m just a fellow user - not connected to AdGuard.

**Comment by TheHasagi** [comment]
@MoistTowellettes 

Hello there, 

I bet you did not disable DNS filtering (AdGuard) that's why the ads are still blocked.

**Comment by MoistTowellettes** [comment]
I just disabled my DNS filtering app (1.1.1.1) and it seems to have worked,
thanks.
