### ISSUE TITLE
Sync filters' translations and lists by checking for filters' updates.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForiOS#958]
@IvanIin 

For AG for iOS v2.1.2:
In filters section, press, swipe down and then release for synchronizing filters' translations and lists.

But I wish AG for iOS v3 can sync filters' translations and lists by checking for filters' updates such like AG for Android v3.
(The translations of **filters disabled** would be **also synchronized**.)

**Comment by lancelot-moon** [comment]
This is a feature request, not a question.

**Comment by lancelot-moon** [comment]
@ameshkov

The latest testflight version uses outmoded filters list and description.

Is there a convenient way to sync filters information with AG server by users ourselves?

Thanks.

**Comment by SoLenny** [comment]
Need to check that bug #1266 will be fixed.

**Comment by lancelot-moon** [comment]
@SoLenny 
You may not understand.
In the issue below, you may use outmoded filters list.
It's not my issue.
https://github.com/AdguardTeam/AdguardForiOS/issues/1266

But I wish a feature to sync filters' list and translations.
Ex:  "Web Annoyance Ultralist" filter isn't a default filter in AG Pro for iOS v2.
However, AG Pro for iOS v2 provides a feature to sync filters' list and translations with AG server.
In filters section of AG Pro for iOS v2, press, swipe down and then release for synchronizing filters' translations and lists.
Even if AG Pro can't be allowed updating by Apple, users can still have the latest filters list.
