### ISSUE TITLE
Add Norwegian filter

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForiOS#96]
User request - 1300243
There was Norsk adblockliste, but hasn't been updated for a while.

**Comment by ameshkov** [comment]
@Alex-302 could you please check that filter?

**Comment by Alex-302** [comment]
@ameshkov 
I found only this filter
https://github.com/ytakano/adchecker/blob/master/adblock.txt
it was updated two years ago.

**Comment by ameshkov** [comment]
Got it, so that filter is simply abandoned.
