### ISSUE TITLE
User filter does not work properly when the terminal is Japanese.

### ISSUE THREAD

**Issue by reki** [AdguardTeam/AdguardForiOS#960]
I was looking for and couldn't find it, but I am sorry if this problem is duplicated.
And I am Japanese and not good at English.

### Steps to reproduce
1.Change the language of iPhone to Japanese.
2.Launch the app and open the user filter.
3.Write a filter.

### Expected behavior
It is input correctly.

### Actual behavior
Even if you enter symbols such as parentheses, they will not be displayed.
It is input only when it is not displayed.
After applying the filter, it will be displayed correctly.

For example, if you enter "## div: not (test)", the display will be as follows.

![IMG_341AE1DABE20-1](https://user-images.githubusercontent.com/32325296/57208827-c0ec2580-7010-11e9-8b7a-376398928699.jpeg)

### Your environment

* Device model and storage size: iPhone 8 plus 256GB
* Operating system and version: 12.2
* Browser Safari
* Wi-fi

**Comment by TheHasagi** [comment]
Unable to reproduce.
