### ISSUE TITLE
DNS protection won't start after DNS server is set

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForiOS#963]
### Steps to reproduce

1. Install and open AdGuard
2. Go to Settings - DNS Privacy - <choose any server> - Allow creating VPN profile
3. Get back to the previous menu and check the protection status

### Expected behavior

Protection should be turned on

### Actual behavior

Protection is off

**Comment by IvanIin** [comment]
fixed in 130
