### ISSUE TITLE
Incorrect sorting in filters group

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForiOS#965]
The sort order must be: `enabled, display number, name`

**Comment by IvanIin** [comment]
fixed in 125

**Comment by zzebrum** [comment]
broken again

**Comment by 08kovalchuk03** [comment]
@zzebrum it sorts filters when you enter a screen, if they were filtered every time we on/off them, they would bounce from top to bottom while we editing them
Maybe I haven't understood the way they must be sorted?
