### ISSUE TITLE
Selection of custom DNS server does not work correctly

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#967]
### Steps to reproduce
1. Go to DNS privacy and add first custom DNS server -> e.g. tls://1.1.1.1
2. Add second DNS server -> Save and Select
3. Then select first custom DNS server or any DNS server

### Expected behavior
DNS server selected and worked correctly.

### Actual behavior
DNS server is not selected.

### Your environment
* Adguard 2.5.0 (121)
* Operating system and version: (ios 12.2)

**Comment by zzebrum** [comment]
Also, choosing any DNS server from the list after you've added custom DNS is not working.

**Comment by IvanIin** [comment]
fixed in 130
