### ISSUE TITLE
Filters group status resets

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForiOS#968]
So I disabled all filters group except Custom, added and enabled a custom filter, surfed the internet for some time. After that, all filters group became enabled in AdGuard like they were reset to default. Logs were sent to @IvanIin

**Comment by planet0** [comment]
Same thing has occurred here, I had some filter groups enabled and lists enabled to my liking. After some time, all filter groups were enabled and I also had Peter Lowe’s list enabled on its own.

**Comment by planet0** [comment]
Seems to have happened again, checked 24 hours later, all filter groups enabled again.

**Comment by planet0** [comment]
As of 3.0.1(143), I'm continuing to have the Security category automatically enabled even though no filters are enabled.
