### ISSUE TITLE
The time doesn't change in DNS filtering log

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#970]
![image](https://user-images.githubusercontent.com/43952607/57768511-72c3da00-7714-11e9-9b2b-1f70d0f432ef.png)

**Comment by tosbsas** [comment]
Same here

And

How to delete log?

**Comment by IvanIin** [comment]
fixed in 132

**Comment by zzebrum** [comment]
@tosbsas #997
