### ISSUE TITLE
The word does not fit. UI

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForiOS#971]
3.0.0 (123)

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/37797229/57768244-e1ecfe80-7713-11e9-88df-e4683b4cd2e5.png)

![image](https://user-images.githubusercontent.com/37797229/57768302-0517ae00-7714-11e9-9729-22722db9f3c9.png)

</details>

**Comment by TheHasagi** [comment]
<details>

![image](https://user-images.githubusercontent.com/37797229/57776341-df949f80-7727-11e9-9b68-fbf2eee85c22.png)

</details

**Comment by zzebrum** [comment]
#1008 as well
