### ISSUE TITLE
Add widget to AdGuard v3

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#973]
![image](https://user-images.githubusercontent.com/43952607/57778939-d1498200-772d-11e9-958c-4f970cdefb1d.png)

**Comment by F3000** [comment]
Where I can find version 3?

**Comment by tosbsas** [comment]
Needed raise prio, please

**Comment by ameshkov** [comment]
@tosbsas this will be done in v3.2 as a part of restoring AG Pro functionality.
