### ISSUE TITLE
Fix the DNS settings in the report link 

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#974]
### Steps to reproduce
1. DNS privacy -> Enable 'AdGuard DNS' or 'AdGuard DNS Family Protection'
2. Send feedback -> Report Incorrect Blocking
3. Go to step 4 'App configuration'

### Actual behavior
![image](https://user-images.githubusercontent.com/43952607/57792635-22ff0600-7748-11e9-9b18-a0548c766bb5.png)

**Comment by IvanIin** [comment]
fixed in 132
