### ISSUE TITLE
All filters group are enabled after reinstalling the app

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForiOS#976]
### Steps to reproduce

1. install AG v3.0
2. delete the app
3. install the app one more time

### Expected behavior
default settings

### Actual behavior
all filters group are enabled. 
filters groups status should not rely on content blockers status in Safari settings

**Comment by F3000** [comment]
Do you have a Download Link for v3.0 ? 

Doesn’t see any update on iOS

**Comment by ameshkov** [comment]
@F3000 it's not publicly available yet

**Comment by F3000** [comment]
What did you mean with the Twitter post last night ?

**Comment by planet0** [comment]
@ameshkov this has happened to me without any warning in the background. All filter groups just turned on, and also enabled Peter Lowe’s List all by itself.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForiOS/issues/968
