### ISSUE TITLE
Show which filters were updated

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForiOS#98]
Feature request:
https://forum.adguard.com/index.php?threads/show-us-which-filters-got-updated-on-ios-app.11238/

@Stillness-2 what do you think?

**Comment by worldsdream** [comment]
@stillness-2 can you tell if you are able to do this in iOS?

**Comment by ameshkov** [comment]
As I understand this is not an easy task as current UI just does not allow to show a long string there.

**Comment by worldsdream** [comment]
Ok and what about if you update for example adguard filters. It shows 5 filters updated. User can go to the filter section and he will see an "icon" on the filterlists that got updated? If user goes back to adguard main page, and go back again to filters, icons are gone. Because they are already watched.

**Comment by ameshkov** [comment]
I think this is just too complicated. What if we make "Filters updated: 5" a link, tapping on it opens some kind of an update log/

**Comment by worldsdream** [comment]
That would be good too

**Comment by Stillness-2** [comment]
I think we should convert the "Last Checked" into button with '>'. Subscreen will be contain the information about last updated filters. But it's still doing not five minutes.

**Comment by ameshkov** [comment]
@Stillness-2 could you please assign it to a milestone? This is a low priority issue, but anyway would be good to have it. Having such update log should also help us with resolving different update & apply issues like #85
