### ISSUE TITLE
[3.0 Beta] Filter tags not all shown, scrollable

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForiOS#981]
The filter categories are not all shown, anything past the first line is hidden and is scrollable to reveal the rest.

Should not be scrollable and all categories should be visible.

<details><summary>Screenshot:</summary>

![IMG_0325](https://user-images.githubusercontent.com/46271764/58051614-032b7000-7b96-11e9-8bc9-ad5d22ec60cf.PNG)
</details>

**Comment by lancelot-moon** [comment]
On iPad Pro 11", the tags for filters are all gone.

**Comment by ameshkov** [comment]
Guys, please tell us what exact iOS versions do you use

**Comment by planet0** [comment]
iOS 12.3 (16F156)
iPhone 8 Plus (MRT72X/A)

**Comment by mdmitriyan** [comment]
![C5C6E02D-B1FF-4A08-8038-89850914E38F](https://user-images.githubusercontent.com/31324750/58211317-426fd300-7cf4-11e9-9463-c8ee0006a47e.png)

**Comment by mdmitriyan** [comment]
iPhone Xs, iOS 12.4 beta 2

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForiOS/issues/1033
