### ISSUE TITLE
[3.0 Beta] Login UI glitch?

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForiOS#982]
Is it normal that the UI jumps after clicking on „passwords“? 
Screen recording: https://we.tl/t-zUJVa83ALT

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by specter78** [comment]
There’s another issue in login page. After entering email and password, pressing return should send authentication request automatically instead of needing to press login button explicitly.

**Comment by mozdevcontrib** [comment]
@specter78 yes and no; it's choice of devs to set explicit action to login via the login button.
