### ISSUE TITLE
[3.0 Beta] Add small refresh/update icon next to "Filters updated"

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForiOS#983]
It isn't clear that you can tap on the text on the home screen to update the filters. This could be resolved by adding a small refresh/update button next to the "Filters updated" text, or by removing the functionality completely and replacing it with pull-to-refresh #972.

<details><summary>Current:</summary>

![IMG_0326](https://user-images.githubusercontent.com/46271764/58052564-88178900-7b98-11e9-8435-b1d2cf7490a3.png)

</details>

<details><summary>Mockup:</summary>

![IMG_0326_1](https://user-images.githubusercontent.com/46271764/58052551-7c2bc700-7b98-11e9-8879-9d8ae41f5fc3.png)

</details>

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/31209705-232c-4523-b6aa-3c2c8a9a634c?mode=design&sha=b4de1363446b44c3f98a082c6c78019091659677
vzhukh!
