### ISSUE TITLE
[3.0 Beta] Login/Device not visible on AdGuard Account

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForiOS#984]
I noticed that although AdGuard was activated, I don't see this anywhere on my AdGuard Account.

**Comment by planet0** [comment]
I was also not asked which license I would like to use for the Pro features. That would be nice to see if the account has more than one eligible license bound.

**Comment by lancelot-moon** [comment]
Now, still don't restrict iOS devices amounts according to your licenses.
If iOS devices will be enrolled in AG account, maybe AG company will restrict iOS devices amounts according to users' licenses.

**Comment by ameshkov** [comment]
> I noticed that although AdGuard was activated, I don't see this anywhere on my AdGuard Account.

Yeah, we have not yet implemented the devices number limitation on the server side so it accepts more devices than it should.

We will do it later in the future, though.
