### ISSUE TITLE
[3.0 Beta] Universal filter search 

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForiOS#989]
I noticed you can only search within Filter groups, and not search all filter subscriptions together.

Would be good to have a search function on the Filters overview section, as I’d like to see all ‘recommended’ filters at once, for example.

**Comment by mozdevcontrib** [comment]
@planet0 I like the idea of a search function. The baked-in filters are few enough in number to both have a search function and to allow people to use the UI. Also, as an aside, if you ever want to import a list, there's a FOSS app `LibTerm` - use the cURL command as such: cURL get https://filter.example.com \ (make sure to use the `\`) which will fetch any filterlust subscription in full for you. Then use a copy all/paste into your choice of file / document apps & you've got yourself a list to import. 🙂

**Comment by ameshkov** [comment]
Merged into https://github.com/adguardteam/adguardforios/issues/1033
