### ISSUE TITLE
Adguard Pro

### ISSUE THREAD

**Issue by Stillness-2** [AdguardTeam/AdguardForiOS#99]

**Comment by Stillness-2** [comment]
8965842162d850657641aa49ccc7d45c6fc3a505
4fc52c01ab478cf0451d8cd4e2b42e3c5f58c308

**Comment by tiberian83** [comment]
Any update when the public beta test will start?

**Comment by Stillness-2** [comment]
Yet no. Later. :)

**Comment by Stillness-2** [comment]
**We need remember to add all changes from 1.0.9 milestone**
