### ISSUE TITLE
3.0 Beta:  DNS-over-TLS on Adguard Server not Filtering out Ads

### ISSUE THREAD

**Issue by shad0whawk** [AdguardTeam/AdguardForiOS#990]
### Steps to reproduce
1.  Enable DNS Privacy
2.  Select Adguard server which defaults to DNS-over-TLS
3.  Open Chrome and navigate to TheVerge.com

### Expected behavior
I expect to see no ads and a place holder where the ad should have been

### Actual behavior
I see ads. Also, when I check where the DNS queries are going, it appears that they’re going directly to my mobile service provider. 

If I select DNSCrypt or DNS-over-HTTPS for the protocol, the ads are not displayed as expected and instead shows the placeholder where the ad should have been. 

### Your environment
iOS 12.3 on iPhone XS Max and iPhone 8.  Testing was done on both a WiFi and cellular connection.

**Comment by mozdevcontrib** [comment]
@shad0whawk  Interesting. I'll have to experiment with alternative DoT servers. I'll let you know my findings.

**Comment by shad0whawk** [comment]
I wanted to tack on some more information this bug report which may be related, otherwise I can open a separate report.  The ad filtering on the version 3 beta using DNS Privacy with the AdGuard server under DNSCrypt and DNS-over-HTTPS are extremely inconsistent in their filtering.  I’ve been switching between these two methods since the TLS method doesn’t work and the results have been inconsistent—sometimes it filters the ads out and other times not.  If I turn on AdGuard Pro with DNSCrypt instead of AdGuard v3, then it works flawlessly.

**Comment by planet0** [comment]
I will also add that I experience the same behaviour as @shad0whawk. As I’ve come from Pro, I’ve noticed sometimes it behaves as expected with apps not showing ads or sponsored content, and then other times they are leaking through.

Other times, the VPN ignores connections or freezes altogether... apps never connect or get stuck connecting. I’m noticing other Issues being placed about particular apps not working, might be related. The query log isn’t showing me anything when I try to test and check for new entries. If I switch between DNSCrypt and DNS-over-HTTPS or turn off and on the DNS Privacy, everything starts behaving normally again.

**Comment by ameshkov** [comment]
What we really need is AdGuard logs.

To get the logs, go to "Settings" -> "Send Feedback" -> "Contact Support". Send it to `apple@adguard.com` and mention this issue number there.

**Comment by shad0whawk** [comment]
Done — sent some logs for the issue with DNS-over-TLS enabled but not blocking ads.  I’ll send some more when I see the inconsistent blocking using the other methods.

**Comment by ameshkov** [comment]
Also, I guess we will make DNS-over-HTTPS the default protocol.

The thing is ISPs might be blocking non-standard ports (853 for DOT or 5443 for DNSCrypt), but they can't block HTTPS port.

**Comment by shad0whawk** [comment]
Changing the default to DOH makes sense and then the user can switch it from there.  Adguard Pro DNS privacy has been super reliable so I’m hoping version 3 will get there.

**Comment by ameshkov** [comment]
> Done — sent some logs for the issue with DNS-over-TLS enabled but not blocking ads. I’ll send some more when I see the inconsistent blocking using the other methods.

Hm, I can't see anything in the `apple@adguard.com` inbox.

Please note that by default it will be sent to support and not to the devs.

**Comment by shad0whawk** [comment]
Oops resent it to apple@adguard.com instead of the default.

**Comment by ameshkov** [comment]
Thank you!

Meanwhile, I've been able to reproduce the issue so we'll fix it for sure.

**Comment by shad0whawk** [comment]
Well the latest release seems to be much more stable and consistent overall.  The DNS-over-TLS and displaying ads is till broke (which I know takes time to fix) but I wanted to add a positive comment on the overall stability.  Thanks!

**Comment by ameshkov** [comment]
Good news is that I figured what the issue is and managed to fix it in the app.

The bad news is that it's triggered by a bug of the DOT implementation on AdGuard DNS. We're yet to fix it.

**Comment by akmLaVx** [comment]
Meanwhile, logs are in. User id 2199436
