### ISSUE TITLE
Smooth; Easy to use custom DNSCrypt v2; DoH; DoT

### ISSUE THREAD

**Issue by mozdevcontrib** [AdguardTeam/AdguardForiOS#992]
### Steps to reproduce

- **Preliminary report**

1. See title.
2. Filter choices are abundant.
3. Subscribing to a hosts file went smoothly.
4. Importing Blacklist & Whitelist also went smoothly.
5. Dark Theme looks great! Easy on the eyes.
6. Currently on iPhone 6 Plus w/ a 65k rule hosts file + an imported DNSBL, using a custom DoH server from @opennic - and all is functioning more smoothly than prior iOS beta pro releases.

- Will report in regularly with updates.
- @mozdevcontrib

**Comment by lancelot-moon** [comment]
AG for iOS v3 should not support hosts files in custom filter for Safari filters.

**Comment by mozdevcontrib** [comment]
Do you really want to base a comment on semantics? It’s neither helpful nor useful. I use the phrase `hosts` interchangeably with `every other possible term to denote a filter list` of which there are many. The `user filter` is essentially a `blacklist`, just as its counterpart is labeled a ’whitelist`.

**Comment by ameshkov** [comment]
Thank you! There is a bunch of bugs in the first beta, though. We have a lot of work to do yet:(

**Comment by mozdevcontrib** [comment]
OFC, and I would like to note my initial reply regarding my use of the term 'hosts file' interchangeably with the numerous other "ad-blocking" filter formats.

- intr0

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
