### ISSUE TITLE
Linio App needs Start kill restart to load

### ISSUE THREAD

**Issue by tosbsas** [AdguardTeam/AdguardForiOS#995]
Linio app 

Start - Stays on Startup Screen 
Kill it
Restart - all well
DNS Protection adguard enabled - over tls 
Works Fine with https setting

**Comment by tosbsas** [comment]
Still wierd

**Comment by tosbsas** [comment]
Yes. But to DO-tls

**Comment by tosbsas** [comment]
But i gets better :-)

**Comment by ameshkov** [comment]
DOT is problematic in .134.

If it works okay with DNS-over-HTTPS server, then the issue will be resolved automatically in the next update.

**Comment by ameshkov** [comment]
Please reopen this issue if the problem comes back after the next beta version.

**Comment by tosbsas** [comment]
Ok :))




_______________________________

Ruben Gutknecht

Lima, Perú  🇵🇪

Cel: +51-99349-1515

Fax: 001-928-223-4243 International

Voice/Fax: 49 (0) 721-151-379204

http://telegram.me/tosbsas

paypal.me/RubenGutknecht
<applewebdata://40566043-5FAC-492D-B3D9-9F4745FD6351/paypal.me/RubenGutknecht>

Deutschland

tosbsas@gmail.com

ttosbsas@icloud.com

Von: Andrey Meshkov <notifications@github.com> <notifications@github.com>
Antworten: AdguardTeam/AdguardForiOS
<reply@reply.github.com>
<reply@reply.github.com>
Datum: 23. Mai 2019 at 11:55:27
An: AdguardTeam/AdguardForiOS <adguardforios@noreply.github.com>
<adguardforios@noreply.github.com>
CC: tosbsas <tosbsas@gmail.com> <tosbsas@gmail.com>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Betreff:  Re: [AdguardTeam/AdguardForiOS] Linio App needs Start kill
restart to load (#995)

Closed #995 <https://github.com/AdguardTeam/AdguardForiOS/issues/995>.
