### ISSUE TITLE
Restore clear DNS Requests Log

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForiOS#997]
I often like to clear the DNS Requests Log and refresh to easily check new requests coming soon from the moment it’s cleared.

Could it possible to restore the ‘Clear’ button on the top right of the Requests Log?

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/26cbe8a4-2f91-4678-b7c4-b6e22b3eba86?sha=8e71139c70bde3aa5c2e2ea2a4dbe1596f36f97c
